
ALTER TABLE IDS_PROD.TXN.FN_SYSTEM
	ADD CONSTRAINT R_9 FOREIGN KEY (FN_SYSTEM_CATEGORY_CODE) REFERENCES IDS_PROD.TXN.FN_SYSTEM_CATEGORY (FN_SYSTEM_CATEGORY_CODE);

ALTER TABLE IDS_PROD.TXN.FN_SYSTEM_TO_MEASURE_REFERENCE
	ADD CONSTRAINT R_5 FOREIGN KEY (FN_SYSTEM_ID) REFERENCES IDS_PROD.TXN.FN_SYSTEM (FN_SYSTEM_ID);

ALTER TABLE IDS_PROD.TXN.FN_SYSTEM_TO_MEASURE_REFERENCE
	ADD CONSTRAINT R_11 FOREIGN KEY (FN_MEASURE_ID) REFERENCES IDS_PROD.TXN.FN_MEASURE (FN_MEASURE_ID);

ALTER TABLE IDS_PROD.TXN.FN_SYSTEM_GL_ACCOUNT_TO_MEASURE_REFERENCE
	ADD CONSTRAINT R_31 FOREIGN KEY (FN_SYSTEM_ID) REFERENCES IDS_PROD.TXN.FN_SYSTEM (FN_SYSTEM_ID);

ALTER TABLE IDS_PROD.TXN.FN_SYSTEM_GL_ACCOUNT_TO_MEASURE_REFERENCE
	ADD CONSTRAINT R_32 FOREIGN KEY (FN_MEASURE_ID) REFERENCES IDS_PROD.TXN.FN_MEASURE (FN_MEASURE_ID);

ALTER TABLE IDS_PROD.TXN.FN_DAILY_REV_MEASURE
	ADD CONSTRAINT R_3 FOREIGN KEY (FN_SYSTEM_ID) REFERENCES IDS_PROD.TXN.FN_SYSTEM (FN_SYSTEM_ID);

ALTER TABLE IDS_PROD.TXN.FN_DAILY_REV_MEASURE
	ADD CONSTRAINT R_10 FOREIGN KEY (FN_MEASURE_ID) REFERENCES IDS_PROD.TXN.FN_MEASURE (FN_MEASURE_ID);

ALTER TABLE IDS_PROD.TXN.FN_WEEKLY_REV_MEASURE
	ADD CONSTRAINT R_13 FOREIGN KEY (FN_MEASURE_ID) REFERENCES IDS_PROD.TXN.FN_MEASURE (FN_MEASURE_ID);

ALTER TABLE IDS_PROD.TXN.FN_WEEKLY_REV_MEASURE
	ADD CONSTRAINT R_15 FOREIGN KEY (FN_SYSTEM_ID) REFERENCES IDS_PROD.TXN.FN_SYSTEM (FN_SYSTEM_ID);

ALTER TABLE IDS_DEV."INT_REF"."REV_CTR_ITEM"
	ADD CONSTRAINT R_14 FOREIGN KEY (REV_CTR_ID) REFERENCES IDS_DEV."INT_REF"."REV_CTR" (REV_CTR_ID);