CREATE OR REPLACE VIEW VW_PNLDETAIL_PERIOD
AS
   SELECT FISCAL_PERIOD_NUMBER,
          FISCAL_YEAR,
          RES.REST_NUMBER,
          RES.REST_NAME,
          RES.REST_STATUS,
          RES.ARG_AREA_NUMBER,
          RES.ARG_AREA_NAME,
          RES.ARG_DISTRICT_NUMBER,
          RES.ARG_DISTRICT_NAME,
          RES.ARG_SUBREGION_NUMBER,
          RES.ARG_SUBREGION_NAME,
          RES.ARG_REGION_NUMBER,
          RES.ARG_REGION_NAME,
          ACCOUNT_SORT_NUMBER,
          CHILD_ACCOUNT_NUMBER,
          CHILD_ACCOUNT_TYPE,
          CHILD_ACCOUNT_DESC,
          PARENT_ACCOUNT_NUMBER,
          PARENT_ACCOUNT_DESC,
          LINE_NUMBER,
          LINE_NAME,
          LINE_DESCRIPTION DESCRIPTION,
          INVOICE_NUMBER,
          CASE
             WHEN INVOICE_DATE = '1753-01-01' THEN CAST ('' AS VARCHAR (10))
             ELSE CAST (INVOICE_DATE AS VARCHAR (10))
          END
             INVOICE_DATE,
          VENDOR_NAME,
          BATCH_NAME,
          SOURCE_NAME,
          ACTUAL_PTD_AMOUNT,
          ISACTIVE_STORE_VIEW,
          ISACTIVE_AREA_VIEW,
          ISACTIVE_DISTRICT_VIEW
     FROM EDW_DEV.ARB.FACT_PNLSUMMARY_DETAIL_PERIOD PSD
          JOIN EDW_DEV.ARB.DIM_RESTAURANT RES
             ON PSD.REST_NUMBER = RES.REST_NUMBER AND RES.ISCURRENT = 1 AND REST_TYPE = 'Arg';