CREATE STAGE IF NOT EXISTS INC_FACT_PNLSUMMARY_DETAIL_PERIOD_ADLS2
    URL = 'azure://ibue2dev01udpadls2.blob.core.windows.net/arbys/edw/Pnlsummary_Detail_Period/'
    STORAGE_INTEGRATION = UDP_STORAGE_INT_DEV
    FILE_FORMAT = EDW_DEV.ARB.EXASOL_INCR_FILE_FORMAT;

CREATE STAGE IF NOT EXISTS INC_DIM_RESTAURANT_ADLS2	
	URL = 'azure://ibue2dev01udpadls2.blob.core.windows.net/arbys/edw/DIM_RESTAURANT/'
	STORAGE_INTEGRATION = UDP_STORAGE_INT_DEV
    FILE_FORMAT = EDW_DEV.ARB.EXASOL_INCR_FILE_FORMAT;