CREATE FILE FORMAT IF NOT EXISTS EXASOL_FF_CSV_ENCODE1252
    TYPE = 'CSV'
    FIELD_DELIMITER = ','
    RECORD_DELIMITER = '\n'
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
    EMPTY_FIELD_AS_NULL=True
    SKIP_HEADER=1
    ENCODING = 'WINDOWS1252';