CREATE STAGE IF NOT EXISTS EDW_HIST_STAGE_ADLS2
	URL = 'azure://ibue2dev01udpadls2.blob.core.windows.net/arbys/edw/'
	STORAGE_INTEGRATION = UDP_STORAGE_INT_DEV
    FILE_FORMAT = EDW_DEV.ARB.EXASOL_FF_CSV_ENCODE1252;