create TABLE IF NOT EXISTS FLYWAY_SCHEMA_HISTORY (
	INSTALLED_RANK NUMBER(38,0) NOT NULL,
	VERSION VARCHAR(50),
	DESCRIPTION VARCHAR(200),
	TYPE VARCHAR(20) NOT NULL,
	SCRIPT VARCHAR(1000) NOT NULL,
	CHECKSUM NUMBER(38,0),
	INSTALLED_BY VARCHAR(100) NOT NULL,
	INSTALLED_ON TIMESTAMP_LTZ(9) NOT NULL DEFAULT CURRENT_TIMESTAMP(),
	EXECUTION_TIME NUMBER(38,0) NOT NULL,
	SUCCESS BOOLEAN NOT NULL,
	primary key (INSTALLED_RANK)
);
create view IF NOT EXISTS OPS_HIERARCHY(
	LOC_ID,
	L1_ID,
	L1_NAME,
	L1_MGR_ID,
	L1_MGR_NAME,
	L2_ID,
	L2_NAME,
	L2_MGR_ID,
	L2_MGR_NAME,
	L3_ID,
	L3_NAME,
	L3_MGR_ID,
	L3_MGR_NAME,
	L4_ID,
	L4_NAME,
	L4_MGR_ID,
	L4_MGR_NAME,
	L5_ID,
	L5_NAME,
	L5_MGR_ID,
	L5_MGR_NAME,
	FRAN_CONSULTANT1_NAME,
	FRAN_CONSULTANT2_NAME,
	FRAN_CONSULTANT3_NAME,
	DIVISION_VP_NAME,
	BRAND_ID,
	CDM_LOAD_DATE,
	LOAD_TYPE,
	SOURCE_SYSTEM_NAME,
	LOAD_ID,
	LOAD_DTTM,
	UPDATE_ID,
	UPDATE_DTTM
) as 	
 SELECT
	  c.LOCATION_ID                  AS LOC_ID
	, c.LEVEL1_ID                    AS L1_ID
	, c.LEVEL1_NM                    AS L1_NAME
	, c.LEVEL1_MANAGER_ID            AS L1_MGR_ID
	, c.LEVEL1_MANAGER_NM            AS L1_MGR_NAME
	, c.LEVEL2_ID                    AS L2_ID
	, c.LEVEL2_NM                    AS L2_NAME
	, c.LEVEL2_MANAGER_ID            AS L2_MGR_ID
	, c.LEVEL2_MANAGER_NM            AS L2_MGR_NAME
	, c.LEVEL3_ID                    AS L3_ID
	, c.LEVEL3_NM                    AS L3_NAME
	, c.LEVEL3_MANAGER_ID            AS L3_MGR_ID
	, c.LEVEL3_MANAGER_NM            AS L3_MGR_NAME
	, c.LEVEL4_ID                    AS L4_ID
	, c.LEVEL4_NM                    AS L4_NAME
	, c.LEVEL4_MANAGER_ID            AS L4_MGR_ID
	, c.LEVEL4_MANAGER_NM            AS L4_MGR_NAME
	, c.LEVEL5_ID                    AS L5_ID
	, c.LEVEL5_NM                    AS L5_NAME
	, c.LEVEL5_MANAGER_ID            AS L5_MGR_ID
	, c.LEVEL5_MANAGER_NM            AS L5_MGR_NAME
	, c.FRANCHISE_CONSULTANT1_NM     AS FRAN_CONSULTANT1_NAME
	, c.FRANCHISE_CONSULTANT2_NM     AS FRAN_CONSULTANT2_NAME
	, c.FRANCHISE_CONSULTANT3_NM     AS FRAN_CONSULTANT3_NAME
	, c.DIVISION_VICE_PRESIDENT_NAME AS DIVISION_VP_NAME 
	, c.BRAND_ID                     AS BRAND_ID
	, c.CDM_LOAD_DT                  AS CDM_LOAD_DATE
	, c.LOAD_TYP                     AS LOAD_TYPE
	, c.SOURCE_SYSTEM_NM             AS SOURCE_SYSTEM_NAME
	, c.LOAD_ID                      AS LOAD_ID
	, c.LOAD_DTTM                    AS LOAD_DTTM
	, c.UPDATE_ID                    AS UPDATE_ID
	, c.UPDATE_DTTM                  AS UPDATE_DTTM
FROM IDM_DEV.COREDIM_BV.OPERATION_MANAGEMENT_HIERARCHY_BV c;