create TABLE IF NOT EXISTS FLYWAY_SCHEMA_HISTORY (
	INSTALLED_RANK NUMBER(38,0) NOT NULL,
	VERSION VARCHAR(50),
	DESCRIPTION VARCHAR(200),
	TYPE VARCHAR(20) NOT NULL,
	SCRIPT VARCHAR(1000) NOT NULL,
	CHECKSUM NUMBER(38,0),
	INSTALLED_BY VARCHAR(100) NOT NULL,
	INSTALLED_ON TIMESTAMP_LTZ(9) NOT NULL DEFAULT CURRENT_TIMESTAMP(),
	EXECUTION_TIME NUMBER(38,0) NOT NULL,
	SUCCESS BOOLEAN NOT NULL,
	primary key (INSTALLED_RANK)
);
create view IF NOT EXISTS EMPLOYEE_PAY_DAY_V(
	EMPLOYEE_ID,
	BUSINESS_DT,
	STORE_ID,
	JOB_ID,
	JOB_NM,
	PAY_TYP_ID,
	HOURLY_RT,
	TOTAL_HRS_NBR,
	EARNED_AMT,
	EFFECTIVE_START_DT,
	EFFECTIVE_END_DT,
	BRAND_ID,
	CDM_LOAD_DT,
	SOURCE_SYSTEM_NM,
	LOAD_ID,
	LOAD_DTTM
) as 
SELECT EMPLOYEEPAYDAY_FACT.EMPLOYEEID,EMPLOYEEPAYDAY_FACT.BUSINESSDATE,EMPLOYEEPAYDAY_FACT.STOREID,EMPLOYEEPAYDAY_FACT.JOBID,EMPLOYEEPAYDAY_FACT.JOBNAME,EMPLOYEEPAYDAY_FACT.PAYTYPEID,EMPLOYEEPAYDAY_FACT.HOURLYRATE,EMPLOYEEPAYDAY_FACT.TOTALHOURS,EMPLOYEEPAYDAY_FACT.AMOUNTEARNED,EMPLOYEEPAYDAY_FACT.EFFECTIVESTARTDATE,EMPLOYEEPAYDAY_FACT.EFFECTIVEENDDATE,EMPLOYEEPAYDAY_FACT.BRANDID,EMPLOYEEPAYDAY_FACT.CDMLOADDATE,EMPLOYEEPAYDAY_FACT.SOURCE,EMPLOYEEPAYDAY_FACT.LOADID,EMPLOYEEPAYDAY_FACT.LOADDTTM
FROM POLARIS_DEV.OPDM.EMPLOYEEPAYDAY_FACT;
create view IF NOT EXISTS GUEST_EXPERIENCE_DAY_PART_OSAT_VAPP(
	BRAND_ID,
	STORE_ID,
	BUSINESS_DT,
	DAY_PART_NM,
	DAY_OF_WEEK_NM,
	FISCAL_WEEK_NBR,
	FISCAL_WEEK_START_DT,
	FISCAL_PERIOD_NBR,
	FISCAL_PERIOD_START_DT,
	FISCAL_QUARTER_NBR,
	FISCAL_YEAR_NBR,
	OSAT_RESPONSE_CNT,
	OSAT_5_CNT,
	OSAT_5_PCT,
	OSAT_4_CNT,
	OSAT_4_PCT,
	OSAT_3_CNT,
	OSAT_3_PCT,
	OSAT_2_CNT,
	OSAT_2_PCT,
	OSAT_1_CNT,
	OSAT_1_PCT,
	OSAT_CLEANLINESS_RESPONSE_CNT,
	OSAT_CLEANLINESS_5_CNT,
	OSAT_CLEANLINESS_5_PCT,
	OSAT_CLEANLINESS_4_CNT,
	OSAT_CLEANLINESS_4_PCT,
	OSAT_CLEANLINESS_3_CNT,
	OSAT_CLEANLINESS_3_PCT,
	OSAT_CLEANLINESS_2_CNT,
	OSAT_CLEANLINESS_2_PCT,
	OSAT_CLEANLINESS_1_CNT,
	OSAT_CLEANLINESS_1_PCT,
	OSAT_ACCURACY_RESPONSE_CNT,
	OSAT_ACCURACY_5_CNT,
	OSAT_ACCURACY_5_PCT,
	OSAT_ACCURACY_4_CNT,
	OSAT_ACCURACY_4_PCT,
	OSAT_ACCURACY_3_CNT,
	OSAT_ACCURACY_3_PCT,
	OSAT_ACCURACY_2_CNT,
	OSAT_ACCURACY_2_PCT,
	OSAT_ACCURACY_1_CNT,
	OSAT_ACCURACY_1_PCT,
	OSAT_FOOD_TASTE_RESPONSE_CNT,
	OSAT_FOOD_TASTE_5_CNT,
	OSAT_FOOD_TASTE_5_PCT,
	OSAT_FOOD_TASTE_4_CNT,
	OSAT_FOOD_TASTE_4_PCT,
	OSAT_FOOD_TASTE_3_CNT,
	OSAT_FOOD_TASTE_3_PCT,
	OSAT_FOOD_TASTE_2_CNT,
	OSAT_FOOD_TASTE_2_PCT,
	OSAT_FOOD_TASTE_1_CNT,
	OSAT_FOOD_TASTE_1_PCT,
	OSAT_FRIENDLINESS_RESPONSE_CNT,
	OSAT_FRIENDLINESS_5_CNT,
	OSAT_FRIENDLINESS_5_PCT,
	OSAT_FRIENDLINESS_4_CNT,
	OSAT_FRIENDLINESS_4_PCT,
	OSAT_FRIENDLINESS_3_CNT,
	OSAT_FRIENDLINESS_3_PCT,
	OSAT_FRIENDLINESS_2_CNT,
	OSAT_FRIENDLINESS_2_PCT,
	OSAT_FRIENDLINESS_1_CNT,
	OSAT_FRIENDLINESS_1_PCT,
	OSAT_SERVICE_SPEED_RESPONSE_CNT,
	OSAT_SERVICE_SPEED_5_CNT,
	OSAT_SERVICE_SPEED_5_PCT,
	OSAT_SERVICE_SPEED_4_CNT,
	OSAT_SERVICE_SPEED_4_PCT,
	OSAT_SERVICE_SPEED_3_CNT,
	OSAT_SERVICE_SPEED_3_PCT,
	OSAT_SERVICE_SPEED_2_CNT,
	OSAT_SERVICE_SPEED_2_PCT,
	OSAT_SERVICE_SPEED_1_CNT,
	OSAT_SERVICE_SPEED_1_PCT,
	LIKE_TO_RETURN_RESPONSE_CNT,
	LIKE_TO_RETURN_SCORE_5_CNT,
	LIKE_TO_RETURN_SCORE_5_PCT,
	LIKE_TO_RETURN_SCORE_4_CNT,
	LIKE_TO_RETURN_SCORE_4_PCT,
	LIKE_TO_RETURN_SCORE_3_CNT,
	LIKE_TO_RETURN_SCORE_3_PCT,
	LIKE_TO_RETURN_SCORE_2_CNT,
	LIKE_TO_RETURN_SCORE_2_PCT,
	LIKE_TO_RETURN_SCORE_1_CNT,
	LIKE_TO_RETURN_SCORE_1_PCT,
	DMA_CD,
	DMA_NM,
	OWNERSHIP_TYP,
	LOC_LEVEL1_NM,
	LOC_LEVEL1_MANAGER_NM,
	LOC_LEVEL2_NM,
	LOC_LEVEL2_MANAGER_NM,
	LOC_LEVEL3_NM,
	LOC_LEVEL3_MANAGER_NM,
	LOC_LEVEL4_NM,
	LOC_LEVEL4_MANAGER_NM,
	LOC_LEVEL5_NM,
	LOC_LEVEL5_MANAGER_NM,
	STORE_CONFIGURATION_BRAND_CD
) as
SELECT 
BRAND_ID , STORE_ID , BUSINESS_DT, DAY_PART_NM 
  , DAY_OF_WEEK AS DAY_OF_WEEK_NM 
  , FISC_WEEK_NBR , FISC_WEEK_START_DT 
  , FISC_PERIOD_NBR , FISC_PERIOD_START_DT 
  , FISC_QUARTER_NBR , FISC_YEAR_NBR 
  , OSAT_RESPONSE_CNT 
  , OSAT_5_CNT , OSAT_5_PCT 
  , OSAT_4_CNT , OSAT_4_PCT 
  , OSAT_3_CNT , OSAT_3_PCT 
  , OSAT_2_CNT , OSAT_2_PCT 
  , OSAT_1_CNT , OSAT_1_PCT 
  , OSAT_CLEANLINESS_RESPONSE_CNT 
  , OSAT_CLEANLINESS_5_CNT , OSAT_CLEANLINESS_5_PCT
  , OSAT_CLEANLINESS_4_CNT , OSAT_CLEANLINESS_4_PCT 
  , OSAT_CLEANLINESS_3_CNT , OSAT_CLEANLINESS_3_PCT 
  , OSAT_CLEANLINESS_2_CNT , OSAT_CLEANLINESS_2_PCT 
  , OSAT_CLEANLINESS_1_CNT , OSAT_CLEANLINESS_1_PCT 
  , OSAT_ACCURACY_RESPONSE_CNT 
  , OSAT_ACCURACY_5_CNT , OSAT_ACCURACY_5_PCT 
  , OSAT_ACCURACY_4_CNT , OSAT_ACCURACY_4_PCT 
  , OSAT_ACCURACY_3_CNT , OSAT_ACCURACY_3_PCT 
  , OSAT_ACCURACY_2_CNT , OSAT_ACCURACY_2_PCT 
  , OSAT_ACCURACY_1_CNT , OSAT_ACCURACY_1_PCT 
  , OSAT_FOOD_TASTE_RESPONSE_CNT 
  , OSAT_FOOD_TASTE_5_CNT , OSAT_FOOD_TASTE_5_PCT 
  , OSAT_FOOD_TASTE_4_CNT , OSAT_FOOD_TASTE_4_PCT
  , OSAT_FOOD_TASTE_3_CNT , OSAT_FOOD_TASTE_3_PCT 
  , OSAT_FOOD_TASTE_2_CNT , OSAT_FOOD_TASTE_2_PCT 
  , OSAT_FOOD_TASTE_1_CNT , OSAT_FOOD_TASTE_1_PCT 
  , OSAT_FRIENDLINESS_RESPONSE_CNT 
  , OSAT_FRIENDLINESS_5_CNT , OSAT_FRIENDLINESS_5_PCT 
  , OSAT_FRIENDLINESS_4_CNT , OSAT_FRIENDLINESS_4_PCT 
  , OSAT_FRIENDLINESS_3_CNT , OSAT_FRIENDLINESS_3_PCT 
  , OSAT_FRIENDLINESS_2_CNT , OSAT_FRIENDLINESS_2_PCT 
  , OSAT_FRIENDLINESS_1_CNT , OSAT_FRIENDLINESS_1_PCT 
  , OSAT_SERVICE_SPEED_RESPONSE_CNT 
  , OSAT_SERVICE_SPEED_5_CNT , OSAT_SERVICE_SPEED_5_PCT 
  , OSAT_SERVICE_SPEED_4_CNT , OSAT_SERVICE_SPEED_4_PCT 
  , OSAT_SERVICE_SPEED_3_CNT , OSAT_SERVICE_SPEED_3_PCT 
  , OSAT_SERVICE_SPEED_2_CNT , OSAT_SERVICE_SPEED_2_PCT 
  , OSAT_SERVICE_SPEED_1_CNT , OSAT_SERVICE_SPEED_1_PCT 
  , LIKE_TO_RETURN_RESPONSE_CNT 
  , LIKE_TO_RETURN_SCORE_5_CNT , LIKE_TO_RETURN_SCORE_5_PCT
  , LIKE_TO_RETURN_SCORE_4_CNT , LIKE_TO_RETURN_SCORE_4_PCT
  , LIKE_TO_RETURN_SCORE_3_CNT , LIKE_TO_RETURN_SCORE_3_PCT
  , LIKE_TO_RETURN_SCORE_2_CNT , LIKE_TO_RETURN_SCORE_2_PCT
  , LIKE_TO_RETURN_SCORE_1_CNT , LIKE_TO_RETURN_SCORE_1_PCT
  , DMA_CD , DMA_NM --moved cols per ODI-7558
  , OWNERSHIP_TYP --moved cols per ODI-7558
  , LOC_LEVEL1_NM , LOC_LEVEL1_MANAGER_NM 
  , LOC_LEVEL2_NM , LOC_LEVEL2_MANAGER_NM 
  , LOC_LEVEL3_NM , LOC_LEVEL3_MANAGER_NM 
  , LOC_LEVEL4_NM , LOC_LEVEL4_MANAGER_NM 
  , LOC_LEVEL5_NM , LOC_LEVEL5_MANAGER_NM 
  , STORE_CONFIG AS STORE_CONFIGURATION_BRAND_CD
FROM TABLE( IDS_DEV.CUST.GUEST_EXPERIENCE_OSAT_INIT('DAY_PART') );
create view IF NOT EXISTS GUEST_EXPERIENCE_ORDER_FULFILLMENT_OSAT_VAPP(
	BRAND_ID,
	STORE_ID,
	BUSINESS_DT,
	SURVEY_ORDER_FULFILLMENT_NM,
	DAY_OF_WEEK_NM,
	FISCAL_WEEK_NBR,
	FISCAL_WEEK_START_DT,
	FISCAL_PERIOD_NBR,
	FISCAL_PERIOD_START_DT,
	FISCAL_QUARTER_NBR,
	FISCAL_YEAR_NBR,
	OSAT_RESPONSE_CNT,
	OSAT_5_CNT,
	OSAT_5_PCT,
	OSAT_4_CNT,
	OSAT_4_PCT,
	OSAT_3_CNT,
	OSAT_3_PCT,
	OSAT_2_CNT,
	OSAT_2_PCT,
	OSAT_1_CNT,
	OSAT_1_PCT,
	OSAT_CLEANLINESS_RESPONSE_CNT,
	OSAT_CLEANLINESS_5_CNT,
	OSAT_CLEANLINESS_5_PCT,
	OSAT_CLEANLINESS_4_CNT,
	OSAT_CLEANLINESS_4_PCT,
	OSAT_CLEANLINESS_3_CNT,
	OSAT_CLEANLINESS_3_PCT,
	OSAT_CLEANLINESS_2_CNT,
	OSAT_CLEANLINESS_2_PCT,
	OSAT_CLEANLINESS_1_CNT,
	OSAT_CLEANLINESS_1_PCT,
	OSAT_ACCURACY_RESPONSE_CNT,
	OSAT_ACCURACY_5_CNT,
	OSAT_ACCURACY_5_PCT,
	OSAT_ACCURACY_4_CNT,
	OSAT_ACCURACY_4_PCT,
	OSAT_ACCURACY_3_CNT,
	OSAT_ACCURACY_3_PCT,
	OSAT_ACCURACY_2_CNT,
	OSAT_ACCURACY_2_PCT,
	OSAT_ACCURACY_1_CNT,
	OSAT_ACCURACY_1_PCT,
	OSAT_FOOD_TASTE_RESPONSE_CNT,
	OSAT_FOOD_TASTE_5_CNT,
	OSAT_FOOD_TASTE_5_PCT,
	OSAT_FOOD_TASTE_4_CNT,
	OSAT_FOOD_TASTE_4_PCT,
	OSAT_FOOD_TASTE_3_CNT,
	OSAT_FOOD_TASTE_3_PCT,
	OSAT_FOOD_TASTE_2_CNT,
	OSAT_FOOD_TASTE_2_PCT,
	OSAT_FOOD_TASTE_1_CNT,
	OSAT_FOOD_TASTE_1_PCT,
	OSAT_FRIENDLINESS_RESPONSE_CNT,
	OSAT_FRIENDLINESS_5_CNT,
	OSAT_FRIENDLINESS_5_PCT,
	OSAT_FRIENDLINESS_4_CNT,
	OSAT_FRIENDLINESS_4_PCT,
	OSAT_FRIENDLINESS_3_CNT,
	OSAT_FRIENDLINESS_3_PCT,
	OSAT_FRIENDLINESS_2_CNT,
	OSAT_FRIENDLINESS_2_PCT,
	OSAT_FRIENDLINESS_1_CNT,
	OSAT_FRIENDLINESS_1_PCT,
	OSAT_SERVICE_SPEED_RESPONSE_CNT,
	OSAT_SERVICE_SPEED_5_CNT,
	OSAT_SERVICE_SPEED_5_PCT,
	OSAT_SERVICE_SPEED_4_CNT,
	OSAT_SERVICE_SPEED_4_PCT,
	OSAT_SERVICE_SPEED_3_CNT,
	OSAT_SERVICE_SPEED_3_PCT,
	OSAT_SERVICE_SPEED_2_CNT,
	OSAT_SERVICE_SPEED_2_PCT,
	OSAT_SERVICE_SPEED_1_CNT,
	OSAT_SERVICE_SPEED_1_PCT,
	LIKE_TO_RETURN_RESPONSE_CNT,
	LIKE_TO_RETURN_SCORE_5_CNT,
	LIKE_TO_RETURN_SCORE_5_PCT,
	LIKE_TO_RETURN_SCORE_4_CNT,
	LIKE_TO_RETURN_SCORE_4_PCT,
	LIKE_TO_RETURN_SCORE_3_CNT,
	LIKE_TO_RETURN_SCORE_3_PCT,
	LIKE_TO_RETURN_SCORE_2_CNT,
	LIKE_TO_RETURN_SCORE_2_PCT,
	LIKE_TO_RETURN_SCORE_1_CNT,
	LIKE_TO_RETURN_SCORE_1_PCT,
	DMA_CD,
	DMA_NM,
	OWNERSHIP_TYP,
	LOC_LEVEL1_NM,
	LOC_LEVEL1_MANAGER_NM,
	LOC_LEVEL2_NM,
	LOC_LEVEL2_MANAGER_NM,
	LOC_LEVEL3_NM,
	LOC_LEVEL3_MANAGER_NM,
	LOC_LEVEL4_NM,
	LOC_LEVEL4_MANAGER_NM,
	LOC_LEVEL5_NM,
	LOC_LEVEL5_MANAGER_NM,
	STORE_CONFIGURATION_BRAND_CD
) as
SELECT 
f.BRAND_ID , f.STORE_ID , f.BUSINESS_DT, sof.SURVEY_ORDER_FULFILLMENT_NM 
  ,f. DAY_OF_WEEK AS DAY_OF_WEEK_NM 
  , f.FISC_WEEK_NBR , f.FISC_WEEK_START_DT 
  , f.FISC_PERIOD_NBR , f.FISC_PERIOD_START_DT 
  , f.FISC_QUARTER_NBR , f.FISC_YEAR_NBR 
  , f.OSAT_RESPONSE_CNT 
  , f.OSAT_5_CNT , f.OSAT_5_PCT 
  , f.OSAT_4_CNT , f.OSAT_4_PCT 
  , f.OSAT_3_CNT , f.OSAT_3_PCT 
  , f.OSAT_2_CNT , f.OSAT_2_PCT 
  , f.OSAT_1_CNT , f.OSAT_1_PCT 
  , f.OSAT_CLEANLINESS_RESPONSE_CNT 
  , f.OSAT_CLEANLINESS_5_CNT , f.OSAT_CLEANLINESS_5_PCT
  , f.OSAT_CLEANLINESS_4_CNT , f.OSAT_CLEANLINESS_4_PCT 
  , f.OSAT_CLEANLINESS_3_CNT , f.OSAT_CLEANLINESS_3_PCT 
  , f.OSAT_CLEANLINESS_2_CNT , f.OSAT_CLEANLINESS_2_PCT 
  , f.OSAT_CLEANLINESS_1_CNT , f.OSAT_CLEANLINESS_1_PCT 
  , f.OSAT_ACCURACY_RESPONSE_CNT 
  , f.OSAT_ACCURACY_5_CNT , f.OSAT_ACCURACY_5_PCT 
  , f.OSAT_ACCURACY_4_CNT , f.OSAT_ACCURACY_4_PCT 
  , f.OSAT_ACCURACY_3_CNT , f.OSAT_ACCURACY_3_PCT 
  , f.OSAT_ACCURACY_2_CNT , f.OSAT_ACCURACY_2_PCT 
  , f.OSAT_ACCURACY_1_CNT , f.OSAT_ACCURACY_1_PCT 
  , f.OSAT_FOOD_TASTE_RESPONSE_CNT 
  , f.OSAT_FOOD_TASTE_5_CNT , f.OSAT_FOOD_TASTE_5_PCT 
  , f.OSAT_FOOD_TASTE_4_CNT , f.OSAT_FOOD_TASTE_4_PCT
  , f.OSAT_FOOD_TASTE_3_CNT , f.OSAT_FOOD_TASTE_3_PCT 
  , f.OSAT_FOOD_TASTE_2_CNT , f.OSAT_FOOD_TASTE_2_PCT 
  , f.OSAT_FOOD_TASTE_1_CNT , f.OSAT_FOOD_TASTE_1_PCT 
  , f.OSAT_FRIENDLINESS_RESPONSE_CNT 
  , f.OSAT_FRIENDLINESS_5_CNT , f.OSAT_FRIENDLINESS_5_PCT 
  , f.OSAT_FRIENDLINESS_4_CNT , f.OSAT_FRIENDLINESS_4_PCT 
  , f.OSAT_FRIENDLINESS_3_CNT , f.OSAT_FRIENDLINESS_3_PCT 
  , f.OSAT_FRIENDLINESS_2_CNT , f.OSAT_FRIENDLINESS_2_PCT 
  , f.OSAT_FRIENDLINESS_1_CNT , f.OSAT_FRIENDLINESS_1_PCT 
  , f.OSAT_SERVICE_SPEED_RESPONSE_CNT 
  , f.OSAT_SERVICE_SPEED_5_CNT , f.OSAT_SERVICE_SPEED_5_PCT 
  , f.OSAT_SERVICE_SPEED_4_CNT , f.OSAT_SERVICE_SPEED_4_PCT 
  , f.OSAT_SERVICE_SPEED_3_CNT , f.OSAT_SERVICE_SPEED_3_PCT 
  , f.OSAT_SERVICE_SPEED_2_CNT , f.OSAT_SERVICE_SPEED_2_PCT 
  , f.OSAT_SERVICE_SPEED_1_CNT , f.OSAT_SERVICE_SPEED_1_PCT 
  , f.LIKE_TO_RETURN_RESPONSE_CNT 
  , f.LIKE_TO_RETURN_SCORE_5_CNT , f.LIKE_TO_RETURN_SCORE_5_PCT
  , f.LIKE_TO_RETURN_SCORE_4_CNT , f.LIKE_TO_RETURN_SCORE_4_PCT
  , f.LIKE_TO_RETURN_SCORE_3_CNT , f.LIKE_TO_RETURN_SCORE_3_PCT
  , f.LIKE_TO_RETURN_SCORE_2_CNT , f.LIKE_TO_RETURN_SCORE_2_PCT
  , f.LIKE_TO_RETURN_SCORE_1_CNT , f.LIKE_TO_RETURN_SCORE_1_PCT
  , f.DMA_CD , f.DMA_NM --columns moved per ODI-7559
  , f.OWNERSHIP_TYP --columns moved per ODI-7559
  , f.LOC_LEVEL1_NM , f.LOC_LEVEL1_MANAGER_NM 
  , f.LOC_LEVEL2_NM , f.LOC_LEVEL2_MANAGER_NM 
  , f.LOC_LEVEL3_NM , f.LOC_LEVEL3_MANAGER_NM 
  , f.LOC_LEVEL4_NM , f.LOC_LEVEL4_MANAGER_NM 
  , f.LOC_LEVEL5_NM , f.LOC_LEVEL5_MANAGER_NM 
  , f.STORE_CONFIG AS STORE_CONFIGURATION_BRAND_CD 
FROM 
TABLE( IDS_DEV.CUST.GUEST_EXPERIENCE_OSAT_INIT('ORDER_FULFILLMENT') )  f
LEFT OUTER JOIN
IDS_DEV.INT_REF_BV.SURVEY_ORDER_FULFILLMENT_BV AS sof ON f.SURVEY_ORDER_FULFILLMENT_ID = sof.SURVEY_ORDER_FULFILLMENT_ID;
create view IF NOT EXISTS GUEST_EXPERIENCE_ORDER_PLACEMENT_OSAT_VAPP(
	BRAND_ID,
	STORE_ID,
	BUSINESS_DT,
	SURVEY_ORDER_PLACEMENT_NM,
	DAY_OF_WEEK_NM,
	FISCAL_WEEK_NBR,
	FISCAL_WEEK_START_DT,
	FISCAL_PERIOD_NBR,
	FISCAL_PERIOD_START_DT,
	FISCAL_QUARTER_NBR,
	FISCAL_YEAR_NBR,
	OSAT_RESPONSE_CNT,
	OSAT_5_CNT,
	OSAT_5_PCT,
	OSAT_4_CNT,
	OSAT_4_PCT,
	OSAT_3_CNT,
	OSAT_3_PCT,
	OSAT_2_CNT,
	OSAT_2_PCT,
	OSAT_1_CNT,
	OSAT_1_PCT,
	OSAT_CLEANLINESS_RESPONSE_CNT,
	OSAT_CLEANLINESS_5_CNT,
	OSAT_CLEANLINESS_5_PCT,
	OSAT_CLEANLINESS_4_CNT,
	OSAT_CLEANLINESS_4_PCT,
	OSAT_CLEANLINESS_3_CNT,
	OSAT_CLEANLINESS_3_PCT,
	OSAT_CLEANLINESS_2_CNT,
	OSAT_CLEANLINESS_2_PCT,
	OSAT_CLEANLINESS_1_CNT,
	OSAT_CLEANLINESS_1_PCT,
	OSAT_ACCURACY_RESPONSE_CNT,
	OSAT_ACCURACY_5_CNT,
	OSAT_ACCURACY_5_PCT,
	OSAT_ACCURACY_4_CNT,
	OSAT_ACCURACY_4_PCT,
	OSAT_ACCURACY_3_CNT,
	OSAT_ACCURACY_3_PCT,
	OSAT_ACCURACY_2_CNT,
	OSAT_ACCURACY_2_PCT,
	OSAT_ACCURACY_1_CNT,
	OSAT_ACCURACY_1_PCT,
	OSAT_FOOD_TASTE_RESPONSE_CNT,
	OSAT_FOOD_TASTE_5_CNT,
	OSAT_FOOD_TASTE_5_PCT,
	OSAT_FOOD_TASTE_4_CNT,
	OSAT_FOOD_TASTE_4_PCT,
	OSAT_FOOD_TASTE_3_CNT,
	OSAT_FOOD_TASTE_3_PCT,
	OSAT_FOOD_TASTE_2_CNT,
	OSAT_FOOD_TASTE_2_PCT,
	OSAT_FOOD_TASTE_1_CNT,
	OSAT_FOOD_TASTE_1_PCT,
	OSAT_FRIENDLINESS_RESPONSE_CNT,
	OSAT_FRIENDLINESS_5_CNT,
	OSAT_FRIENDLINESS_5_PCT,
	OSAT_FRIENDLINESS_4_CNT,
	OSAT_FRIENDLINESS_4_PCT,
	OSAT_FRIENDLINESS_3_CNT,
	OSAT_FRIENDLINESS_3_PCT,
	OSAT_FRIENDLINESS_2_CNT,
	OSAT_FRIENDLINESS_2_PCT,
	OSAT_FRIENDLINESS_1_CNT,
	OSAT_FRIENDLINESS_1_PCT,
	OSAT_SERVICE_SPEED_RESPONSE_CNT,
	OSAT_SERVICE_SPEED_5_CNT,
	OSAT_SERVICE_SPEED_5_PCT,
	OSAT_SERVICE_SPEED_4_CNT,
	OSAT_SERVICE_SPEED_4_PCT,
	OSAT_SERVICE_SPEED_3_CNT,
	OSAT_SERVICE_SPEED_3_PCT,
	OSAT_SERVICE_SPEED_2_CNT,
	OSAT_SERVICE_SPEED_2_PCT,
	OSAT_SERVICE_SPEED_1_CNT,
	OSAT_SERVICE_SPEED_1_PCT,
	LIKE_TO_RETURN_RESPONSE_CNT,
	LIKE_TO_RETURN_SCORE_5_CNT,
	LIKE_TO_RETURN_SCORE_5_PCT,
	LIKE_TO_RETURN_SCORE_4_CNT,
	LIKE_TO_RETURN_SCORE_4_PCT,
	LIKE_TO_RETURN_SCORE_3_CNT,
	LIKE_TO_RETURN_SCORE_3_PCT,
	LIKE_TO_RETURN_SCORE_2_CNT,
	LIKE_TO_RETURN_SCORE_2_PCT,
	LIKE_TO_RETURN_SCORE_1_CNT,
	LIKE_TO_RETURN_SCORE_1_PCT,
	DMA_CD,
	DMA_NM,
	OWNERSHIP_TYP,
	LOC_LEVEL1_NM,
	LOC_LEVEL1_MANAGER_NM,
	LOC_LEVEL2_NM,
	LOC_LEVEL2_MANAGER_NM,
	LOC_LEVEL3_NM,
	LOC_LEVEL3_MANAGER_NM,
	LOC_LEVEL4_NM,
	LOC_LEVEL4_MANAGER_NM,
	LOC_LEVEL5_NM,
	LOC_LEVEL5_MANAGER_NM,
	STORE_CONFIGURATION_BRAND_CD
) as
SELECT 
f.BRAND_ID , f.STORE_ID , f.BUSINESS_DT, sop.SURVEY_ORDER_PLACEMENT_NM 
  ,f. DAY_OF_WEEK AS DAY_OF_WEEK_NM 
  , f.FISC_WEEK_NBR , f.FISC_WEEK_START_DT 
  , f.FISC_PERIOD_NBR , f.FISC_PERIOD_START_DT 
  , f.FISC_QUARTER_NBR , f.FISC_YEAR_NBR 
  , f.OSAT_RESPONSE_CNT 
  , f.OSAT_5_CNT , f.OSAT_5_PCT 
  , f.OSAT_4_CNT , f.OSAT_4_PCT 
  , f.OSAT_3_CNT , f.OSAT_3_PCT 
  , f.OSAT_2_CNT , f.OSAT_2_PCT 
  , f.OSAT_1_CNT , f.OSAT_1_PCT 
  , f.OSAT_CLEANLINESS_RESPONSE_CNT 
  , f.OSAT_CLEANLINESS_5_CNT , f.OSAT_CLEANLINESS_5_PCT
  , f.OSAT_CLEANLINESS_4_CNT , f.OSAT_CLEANLINESS_4_PCT 
  , f.OSAT_CLEANLINESS_3_CNT , f.OSAT_CLEANLINESS_3_PCT 
  , f.OSAT_CLEANLINESS_2_CNT , f.OSAT_CLEANLINESS_2_PCT 
  , f.OSAT_CLEANLINESS_1_CNT , f.OSAT_CLEANLINESS_1_PCT 
  , f.OSAT_ACCURACY_RESPONSE_CNT 
  , f.OSAT_ACCURACY_5_CNT , f.OSAT_ACCURACY_5_PCT 
  , f.OSAT_ACCURACY_4_CNT , f.OSAT_ACCURACY_4_PCT 
  , f.OSAT_ACCURACY_3_CNT , f.OSAT_ACCURACY_3_PCT 
  , f.OSAT_ACCURACY_2_CNT , f.OSAT_ACCURACY_2_PCT 
  , f.OSAT_ACCURACY_1_CNT , f.OSAT_ACCURACY_1_PCT 
  , f.OSAT_FOOD_TASTE_RESPONSE_CNT 
  , f.OSAT_FOOD_TASTE_5_CNT , f.OSAT_FOOD_TASTE_5_PCT 
  , f.OSAT_FOOD_TASTE_4_CNT , f.OSAT_FOOD_TASTE_4_PCT
  , f.OSAT_FOOD_TASTE_3_CNT , f.OSAT_FOOD_TASTE_3_PCT 
  , f.OSAT_FOOD_TASTE_2_CNT , f.OSAT_FOOD_TASTE_2_PCT 
  , f.OSAT_FOOD_TASTE_1_CNT , f.OSAT_FOOD_TASTE_1_PCT 
  , f.OSAT_FRIENDLINESS_RESPONSE_CNT 
  , f.OSAT_FRIENDLINESS_5_CNT , f.OSAT_FRIENDLINESS_5_PCT 
  , f.OSAT_FRIENDLINESS_4_CNT , f.OSAT_FRIENDLINESS_4_PCT 
  , f.OSAT_FRIENDLINESS_3_CNT , f.OSAT_FRIENDLINESS_3_PCT 
  , f.OSAT_FRIENDLINESS_2_CNT , f.OSAT_FRIENDLINESS_2_PCT 
  , f.OSAT_FRIENDLINESS_1_CNT , f.OSAT_FRIENDLINESS_1_PCT 
  , f.OSAT_SERVICE_SPEED_RESPONSE_CNT 
  , f.OSAT_SERVICE_SPEED_5_CNT , f.OSAT_SERVICE_SPEED_5_PCT 
  , f.OSAT_SERVICE_SPEED_4_CNT , f.OSAT_SERVICE_SPEED_4_PCT 
  , f.OSAT_SERVICE_SPEED_3_CNT , f.OSAT_SERVICE_SPEED_3_PCT 
  , f.OSAT_SERVICE_SPEED_2_CNT , f.OSAT_SERVICE_SPEED_2_PCT 
  , f.OSAT_SERVICE_SPEED_1_CNT , f.OSAT_SERVICE_SPEED_1_PCT 
  , f.LIKE_TO_RETURN_RESPONSE_CNT 
  , f.LIKE_TO_RETURN_SCORE_5_CNT , f.LIKE_TO_RETURN_SCORE_5_PCT
  , f.LIKE_TO_RETURN_SCORE_4_CNT , f.LIKE_TO_RETURN_SCORE_4_PCT
  , f.LIKE_TO_RETURN_SCORE_3_CNT , f.LIKE_TO_RETURN_SCORE_3_PCT
  , f.LIKE_TO_RETURN_SCORE_2_CNT , f.LIKE_TO_RETURN_SCORE_2_PCT
  , f.LIKE_TO_RETURN_SCORE_1_CNT , f.LIKE_TO_RETURN_SCORE_1_PCT
  , f.DMA_CD , f.DMA_NM --moved columns per ODI-7556
  , f.OWNERSHIP_TYP --moved columns per ODI-7556
  , f.LOC_LEVEL1_NM , f.LOC_LEVEL1_MANAGER_NM 
  , f.LOC_LEVEL2_NM , f.LOC_LEVEL2_MANAGER_NM 
  , f.LOC_LEVEL3_NM , f.LOC_LEVEL3_MANAGER_NM 
  , f.LOC_LEVEL4_NM , f.LOC_LEVEL4_MANAGER_NM 
  , f.LOC_LEVEL5_NM , f.LOC_LEVEL5_MANAGER_NM 
  , f.STORE_CONFIG AS STORE_CONFIGURATION_BRAND_CD 
FROM 
TABLE( IDS_DEV.CUST.GUEST_EXPERIENCE_OSAT_INIT('ORDER_PLACEMENT') ) AS f
LEFT OUTER JOIN
IDS_DEV.INT_REF_BV.SURVEY_ORDER_PLACEMENT_BV AS sop ON f.SURVEY_ORDER_PLACEMENT_ID = sop.SURVEY_ORDER_PLACEMENT_ID;
create view IF NOT EXISTS GUEST_EXPERIENCE_OSAT_VAPP(
	BRAND_ID,
	STORE_ID,
	BUSINESS_DT,
	DAY_OF_WEEK_NM,
	FISCAL_WEEK_NBR,
	FISCAL_WEEK_START_DT,
	FISCAL_PERIOD_NBR,
	FISCAL_PERIOD_START_DT,
	FISCAL_QUARTER_NBR,
	FISCAL_YEAR_NBR,
	OSAT_RESPONSE_CNT,
	OSAT_5_CNT,
	OSAT_5_PCT,
	OSAT_4_CNT,
	OSAT_4_PCT,
	OSAT_3_CNT,
	OSAT_3_PCT,
	OSAT_2_CNT,
	OSAT_2_PCT,
	OSAT_1_CNT,
	OSAT_1_PCT,
	OSAT_CLEANLINESS_RESPONSE_CNT,
	OSAT_CLEANLINESS_5_CNT,
	OSAT_CLEANLINESS_5_PCT,
	OSAT_CLEANLINESS_4_CNT,
	OSAT_CLEANLINESS_4_PCT,
	OSAT_CLEANLINESS_3_CNT,
	OSAT_CLEANLINESS_3_PCT,
	OSAT_CLEANLINESS_2_CNT,
	OSAT_CLEANLINESS_2_PCT,
	OSAT_CLEANLINESS_1_CNT,
	OSAT_CLEANLINESS_1_PCT,
	OSAT_ACCURACY_RESPONSE_CNT,
	OSAT_ACCURACY_5_CNT,
	OSAT_ACCURACY_5_PCT,
	OSAT_ACCURACY_4_CNT,
	OSAT_ACCURACY_4_PCT,
	OSAT_ACCURACY_3_CNT,
	OSAT_ACCURACY_3_PCT,
	OSAT_ACCURACY_2_CNT,
	OSAT_ACCURACY_2_PCT,
	OSAT_ACCURACY_1_CNT,
	OSAT_ACCURACY_1_PCT,
	OSAT_FOOD_TASTE_RESPONSE_CNT,
	OSAT_FOOD_TASTE_5_CNT,
	OSAT_FOOD_TASTE_5_PCT,
	OSAT_FOOD_TASTE_4_CNT,
	OSAT_FOOD_TASTE_4_PCT,
	OSAT_FOOD_TASTE_3_CNT,
	OSAT_FOOD_TASTE_3_PCT,
	OSAT_FOOD_TASTE_2_CNT,
	OSAT_FOOD_TASTE_2_PCT,
	OSAT_FOOD_TASTE_1_CNT,
	OSAT_FOOD_TASTE_1_PCT,
	OSAT_FRIENDLINESS_RESPONSE_CNT,
	OSAT_FRIENDLINESS_5_CNT,
	OSAT_FRIENDLINESS_5_PCT,
	OSAT_FRIENDLINESS_4_CNT,
	OSAT_FRIENDLINESS_4_PCT,
	OSAT_FRIENDLINESS_3_CNT,
	OSAT_FRIENDLINESS_3_PCT,
	OSAT_FRIENDLINESS_2_CNT,
	OSAT_FRIENDLINESS_2_PCT,
	OSAT_FRIENDLINESS_1_CNT,
	OSAT_FRIENDLINESS_1_PCT,
	OSAT_SERVICE_SPEED_RESPONSE_CNT,
	OSAT_SERVICE_SPEED_5_CNT,
	OSAT_SERVICE_SPEED_5_PCT,
	OSAT_SERVICE_SPEED_4_CNT,
	OSAT_SERVICE_SPEED_4_PCT,
	OSAT_SERVICE_SPEED_3_CNT,
	OSAT_SERVICE_SPEED_3_PCT,
	OSAT_SERVICE_SPEED_2_CNT,
	OSAT_SERVICE_SPEED_2_PCT,
	OSAT_SERVICE_SPEED_1_CNT,
	OSAT_SERVICE_SPEED_1_PCT,
	LIKE_TO_RETURN_RESPONSE_CNT,
	LIKE_TO_RETURN_SCORE_5_CNT,
	LIKE_TO_RETURN_SCORE_5_PCT,
	LIKE_TO_RETURN_SCORE_4_CNT,
	LIKE_TO_RETURN_SCORE_4_PCT,
	LIKE_TO_RETURN_SCORE_3_CNT,
	LIKE_TO_RETURN_SCORE_3_PCT,
	LIKE_TO_RETURN_SCORE_2_CNT,
	LIKE_TO_RETURN_SCORE_2_PCT,
	LIKE_TO_RETURN_SCORE_1_CNT,
	LIKE_TO_RETURN_SCORE_1_PCT,
	DMA_CD,
	DMA_NM,
	OWNERSHIP_TYP,
	LOC_LEVEL1_NM,
	LOC_LEVEL1_MANAGER_NM,
	LOC_LEVEL2_NM,
	LOC_LEVEL2_MANAGER_NM,
	LOC_LEVEL3_NM,
	LOC_LEVEL3_MANAGER_NM,
	LOC_LEVEL4_NM,
	LOC_LEVEL4_MANAGER_NM,
	LOC_LEVEL5_NM,
	LOC_LEVEL5_MANAGER_NM,
	STORE_CONFIGURATION_BRAND_CD
) as
SELECT 
BRAND_ID , STORE_ID , BUSINESS_DT 
  , DAY_OF_WEEK AS DAY_OF_WEEK_NM 
  , FISC_WEEK_NBR , FISC_WEEK_START_DT 
  , FISC_PERIOD_NBR , FISC_PERIOD_START_DT 
  , FISC_QUARTER_NBR , FISC_YEAR_NBR 
  , OSAT_RESPONSE_CNT 
  , OSAT_5_CNT , OSAT_5_PCT 
  , OSAT_4_CNT , OSAT_4_PCT 
  , OSAT_3_CNT , OSAT_3_PCT 
  , OSAT_2_CNT , OSAT_2_PCT 
  , OSAT_1_CNT , OSAT_1_PCT 
  , OSAT_CLEANLINESS_RESPONSE_CNT 
  , OSAT_CLEANLINESS_5_CNT , OSAT_CLEANLINESS_5_PCT
  , OSAT_CLEANLINESS_4_CNT , OSAT_CLEANLINESS_4_PCT 
  , OSAT_CLEANLINESS_3_CNT , OSAT_CLEANLINESS_3_PCT 
  , OSAT_CLEANLINESS_2_CNT , OSAT_CLEANLINESS_2_PCT 
  , OSAT_CLEANLINESS_1_CNT , OSAT_CLEANLINESS_1_PCT 
  , OSAT_ACCURACY_RESPONSE_CNT 
  , OSAT_ACCURACY_5_CNT , OSAT_ACCURACY_5_PCT 
  , OSAT_ACCURACY_4_CNT , OSAT_ACCURACY_4_PCT 
  , OSAT_ACCURACY_3_CNT , OSAT_ACCURACY_3_PCT 
  , OSAT_ACCURACY_2_CNT , OSAT_ACCURACY_2_PCT 
  , OSAT_ACCURACY_1_CNT , OSAT_ACCURACY_1_PCT 
  , OSAT_FOOD_TASTE_RESPONSE_CNT 
  , OSAT_FOOD_TASTE_5_CNT , OSAT_FOOD_TASTE_5_PCT 
  , OSAT_FOOD_TASTE_4_CNT , OSAT_FOOD_TASTE_4_PCT
  , OSAT_FOOD_TASTE_3_CNT , OSAT_FOOD_TASTE_3_PCT 
  , OSAT_FOOD_TASTE_2_CNT , OSAT_FOOD_TASTE_2_PCT 
  , OSAT_FOOD_TASTE_1_CNT , OSAT_FOOD_TASTE_1_PCT 
  , OSAT_FRIENDLINESS_RESPONSE_CNT 
  , OSAT_FRIENDLINESS_5_CNT , OSAT_FRIENDLINESS_5_PCT 
  , OSAT_FRIENDLINESS_4_CNT , OSAT_FRIENDLINESS_4_PCT 
  , OSAT_FRIENDLINESS_3_CNT , OSAT_FRIENDLINESS_3_PCT 
  , OSAT_FRIENDLINESS_2_CNT , OSAT_FRIENDLINESS_2_PCT 
  , OSAT_FRIENDLINESS_1_CNT , OSAT_FRIENDLINESS_1_PCT 
  , OSAT_SERVICE_SPEED_RESPONSE_CNT 
  , OSAT_SERVICE_SPEED_5_CNT , OSAT_SERVICE_SPEED_5_PCT 
  , OSAT_SERVICE_SPEED_4_CNT , OSAT_SERVICE_SPEED_4_PCT 
  , OSAT_SERVICE_SPEED_3_CNT , OSAT_SERVICE_SPEED_3_PCT 
  , OSAT_SERVICE_SPEED_2_CNT , OSAT_SERVICE_SPEED_2_PCT 
  , OSAT_SERVICE_SPEED_1_CNT , OSAT_SERVICE_SPEED_1_PCT 
  , LIKE_TO_RETURN_RESPONSE_CNT 
  , LIKE_TO_RETURN_SCORE_5_CNT , LIKE_TO_RETURN_SCORE_5_PCT
  , LIKE_TO_RETURN_SCORE_4_CNT , LIKE_TO_RETURN_SCORE_4_PCT
  , LIKE_TO_RETURN_SCORE_3_CNT , LIKE_TO_RETURN_SCORE_3_PCT
  , LIKE_TO_RETURN_SCORE_2_CNT , LIKE_TO_RETURN_SCORE_2_PCT
  , LIKE_TO_RETURN_SCORE_1_CNT , LIKE_TO_RETURN_SCORE_1_PCT
  , DMA_CD , DMA_NM --moved cols per ODI-7577
  , OWNERSHIP_TYP --moved cols per ODI-7577
  , LOC_LEVEL1_NM , LOC_LEVEL1_MANAGER_NM 
  , LOC_LEVEL2_NM , LOC_LEVEL2_MANAGER_NM 
  , LOC_LEVEL3_NM , LOC_LEVEL3_MANAGER_NM 
  , LOC_LEVEL4_NM , LOC_LEVEL4_MANAGER_NM 
  , LOC_LEVEL5_NM , LOC_LEVEL5_MANAGER_NM 
  , STORE_CONFIG AS STORE_CONFIGURATION_BRAND_CD
FROM TABLE( IDS_DEV.CUST.GUEST_EXPERIENCE_OSAT_INIT('BUSINESS_DT') );
create view IF NOT EXISTS GUEST_EXPERIENCE_SURVEY_CHANNEL_OSAT_VAPP(
	BRAND_ID,
	STORE_ID,
	BUSINESS_DT,
	SURVEY_CHANNEL_NM,
	SURVEY_SUB_CHANNEL_NM,
	DAY_OF_WEEK_NM,
	FISCAL_WEEK_NBR,
	FISCAL_WEEK_START_DT,
	FISCAL_PERIOD_NBR,
	FISCAL_PERIOD_START_DT,
	FISCAL_QUARTER_NBR,
	FISCAL_YEAR_NBR,
	OSAT_RESPONSE_CNT,
	OSAT_5_CNT,
	OSAT_5_PCT,
	OSAT_4_CNT,
	OSAT_4_PCT,
	OSAT_3_CNT,
	OSAT_3_PCT,
	OSAT_2_CNT,
	OSAT_2_PCT,
	OSAT_1_CNT,
	OSAT_1_PCT,
	OSAT_CLEANLINESS_RESPONSE_CNT,
	OSAT_CLEANLINESS_5_CNT,
	OSAT_CLEANLINESS_5_PCT,
	OSAT_CLEANLINESS_4_CNT,
	OSAT_CLEANLINESS_4_PCT,
	OSAT_CLEANLINESS_3_CNT,
	OSAT_CLEANLINESS_3_PCT,
	OSAT_CLEANLINESS_2_CNT,
	OSAT_CLEANLINESS_2_PCT,
	OSAT_CLEANLINESS_1_CNT,
	OSAT_CLEANLINESS_1_PCT,
	OSAT_ACCURACY_RESPONSE_CNT,
	OSAT_ACCURACY_5_CNT,
	OSAT_ACCURACY_5_PCT,
	OSAT_ACCURACY_4_CNT,
	OSAT_ACCURACY_4_PCT,
	OSAT_ACCURACY_3_CNT,
	OSAT_ACCURACY_3_PCT,
	OSAT_ACCURACY_2_CNT,
	OSAT_ACCURACY_2_PCT,
	OSAT_ACCURACY_1_CNT,
	OSAT_ACCURACY_1_PCT,
	OSAT_FOOD_TASTE_RESPONSE_CNT,
	OSAT_FOOD_TASTE_5_CNT,
	OSAT_FOOD_TASTE_5_PCT,
	OSAT_FOOD_TASTE_4_CNT,
	OSAT_FOOD_TASTE_4_PCT,
	OSAT_FOOD_TASTE_3_CNT,
	OSAT_FOOD_TASTE_3_PCT,
	OSAT_FOOD_TASTE_2_CNT,
	OSAT_FOOD_TASTE_2_PCT,
	OSAT_FOOD_TASTE_1_CNT,
	OSAT_FOOD_TASTE_1_PCT,
	OSAT_FRIENDLINESS_RESPONSE_CNT,
	OSAT_FRIENDLINESS_5_CNT,
	OSAT_FRIENDLINESS_5_PCT,
	OSAT_FRIENDLINESS_4_CNT,
	OSAT_FRIENDLINESS_4_PCT,
	OSAT_FRIENDLINESS_3_CNT,
	OSAT_FRIENDLINESS_3_PCT,
	OSAT_FRIENDLINESS_2_CNT,
	OSAT_FRIENDLINESS_2_PCT,
	OSAT_FRIENDLINESS_1_CNT,
	OSAT_FRIENDLINESS_1_PCT,
	OSAT_SERVICE_SPEED_RESPONSE_CNT,
	OSAT_SERVICE_SPEED_5_CNT,
	OSAT_SERVICE_SPEED_5_PCT,
	OSAT_SERVICE_SPEED_4_CNT,
	OSAT_SERVICE_SPEED_4_PCT,
	OSAT_SERVICE_SPEED_3_CNT,
	OSAT_SERVICE_SPEED_3_PCT,
	OSAT_SERVICE_SPEED_2_CNT,
	OSAT_SERVICE_SPEED_2_PCT,
	OSAT_SERVICE_SPEED_1_CNT,
	OSAT_SERVICE_SPEED_1_PCT,
	LIKE_TO_RETURN_RESPONSE_CNT,
	LIKE_TO_RETURN_SCORE_5_CNT,
	LIKE_TO_RETURN_SCORE_5_PCT,
	LIKE_TO_RETURN_SCORE_4_CNT,
	LIKE_TO_RETURN_SCORE_4_PCT,
	LIKE_TO_RETURN_SCORE_3_CNT,
	LIKE_TO_RETURN_SCORE_3_PCT,
	LIKE_TO_RETURN_SCORE_2_CNT,
	LIKE_TO_RETURN_SCORE_2_PCT,
	LIKE_TO_RETURN_SCORE_1_CNT,
	LIKE_TO_RETURN_SCORE_1_PCT,
	DMA_CD,
	DMA_NM,
	OWNERSHIP_TYP,
	LOC_LEVEL1_NM,
	LOC_LEVEL1_MANAGER_NM,
	LOC_LEVEL2_NM,
	LOC_LEVEL2_MANAGER_NM,
	LOC_LEVEL3_NM,
	LOC_LEVEL3_MANAGER_NM,
	LOC_LEVEL4_NM,
	LOC_LEVEL4_MANAGER_NM,
	LOC_LEVEL5_NM,
	LOC_LEVEL5_MANAGER_NM,
	STORE_CONFIGURATION_BRAND_CD
) as
SELECT 
f.BRAND_ID , f.STORE_ID , f.BUSINESS_DT, sc.SURVEY_CHANNEL_NM, sc.SURVEY_SUB_CHANNEL_NM
  ,f. DAY_OF_WEEK AS DAY_OF_WEEK_NM 
  , f.FISC_WEEK_NBR , f.FISC_WEEK_START_DT 
  , f.FISC_PERIOD_NBR , f.FISC_PERIOD_START_DT 
  , f.FISC_QUARTER_NBR , f.FISC_YEAR_NBR 
  , f.OSAT_RESPONSE_CNT 
  , f.OSAT_5_CNT , f.OSAT_5_PCT 
  , f.OSAT_4_CNT , f.OSAT_4_PCT 
  , f.OSAT_3_CNT , f.OSAT_3_PCT 
  , f.OSAT_2_CNT , f.OSAT_2_PCT 
  , f.OSAT_1_CNT , f.OSAT_1_PCT 
  , f.OSAT_CLEANLINESS_RESPONSE_CNT 
  , f.OSAT_CLEANLINESS_5_CNT , f.OSAT_CLEANLINESS_5_PCT
  , f.OSAT_CLEANLINESS_4_CNT , f.OSAT_CLEANLINESS_4_PCT 
  , f.OSAT_CLEANLINESS_3_CNT , f.OSAT_CLEANLINESS_3_PCT 
  , f.OSAT_CLEANLINESS_2_CNT , f.OSAT_CLEANLINESS_2_PCT 
  , f.OSAT_CLEANLINESS_1_CNT , f.OSAT_CLEANLINESS_1_PCT 
  , f.OSAT_ACCURACY_RESPONSE_CNT 
  , f.OSAT_ACCURACY_5_CNT , f.OSAT_ACCURACY_5_PCT 
  , f.OSAT_ACCURACY_4_CNT , f.OSAT_ACCURACY_4_PCT 
  , f.OSAT_ACCURACY_3_CNT , f.OSAT_ACCURACY_3_PCT 
  , f.OSAT_ACCURACY_2_CNT , f.OSAT_ACCURACY_2_PCT 
  , f.OSAT_ACCURACY_1_CNT , f.OSAT_ACCURACY_1_PCT 
  , f.OSAT_FOOD_TASTE_RESPONSE_CNT 
  , f.OSAT_FOOD_TASTE_5_CNT , f.OSAT_FOOD_TASTE_5_PCT 
  , f.OSAT_FOOD_TASTE_4_CNT , f.OSAT_FOOD_TASTE_4_PCT
  , f.OSAT_FOOD_TASTE_3_CNT , f.OSAT_FOOD_TASTE_3_PCT 
  , f.OSAT_FOOD_TASTE_2_CNT , f.OSAT_FOOD_TASTE_2_PCT 
  , f.OSAT_FOOD_TASTE_1_CNT , f.OSAT_FOOD_TASTE_1_PCT 
  , f.OSAT_FRIENDLINESS_RESPONSE_CNT 
  , f.OSAT_FRIENDLINESS_5_CNT , f.OSAT_FRIENDLINESS_5_PCT 
  , f.OSAT_FRIENDLINESS_4_CNT , f.OSAT_FRIENDLINESS_4_PCT 
  , f.OSAT_FRIENDLINESS_3_CNT , f.OSAT_FRIENDLINESS_3_PCT 
  , f.OSAT_FRIENDLINESS_2_CNT , f.OSAT_FRIENDLINESS_2_PCT 
  , f.OSAT_FRIENDLINESS_1_CNT , f.OSAT_FRIENDLINESS_1_PCT 
  , f.OSAT_SERVICE_SPEED_RESPONSE_CNT 
  , f.OSAT_SERVICE_SPEED_5_CNT , f.OSAT_SERVICE_SPEED_5_PCT 
  , f.OSAT_SERVICE_SPEED_4_CNT , f.OSAT_SERVICE_SPEED_4_PCT 
  , f.OSAT_SERVICE_SPEED_3_CNT , f.OSAT_SERVICE_SPEED_3_PCT 
  , f.OSAT_SERVICE_SPEED_2_CNT , f.OSAT_SERVICE_SPEED_2_PCT 
  , f.OSAT_SERVICE_SPEED_1_CNT , f.OSAT_SERVICE_SPEED_1_PCT 
  , f.LIKE_TO_RETURN_RESPONSE_CNT 
  , f.LIKE_TO_RETURN_SCORE_5_CNT , f.LIKE_TO_RETURN_SCORE_5_PCT
  , f.LIKE_TO_RETURN_SCORE_4_CNT , f.LIKE_TO_RETURN_SCORE_4_PCT
  , f.LIKE_TO_RETURN_SCORE_3_CNT , f.LIKE_TO_RETURN_SCORE_3_PCT
  , f.LIKE_TO_RETURN_SCORE_2_CNT , f.LIKE_TO_RETURN_SCORE_2_PCT
  , f.LIKE_TO_RETURN_SCORE_1_CNT , f.LIKE_TO_RETURN_SCORE_1_PCT
  , f.DMA_CD , f.DMA_NM --moved cols per ODI-7557
  , f.OWNERSHIP_TYP --moved cols per ODI-7557
  , f.LOC_LEVEL1_NM , f.LOC_LEVEL1_MANAGER_NM 
  , f.LOC_LEVEL2_NM , f.LOC_LEVEL2_MANAGER_NM 
  , f.LOC_LEVEL3_NM , f.LOC_LEVEL3_MANAGER_NM 
  , f.LOC_LEVEL4_NM , f.LOC_LEVEL4_MANAGER_NM 
  , f.LOC_LEVEL5_NM , f.LOC_LEVEL5_MANAGER_NM 
  , f.STORE_CONFIG AS STORE_CONFIGURATION_BRAND_CD 
FROM 
TABLE( IDS_DEV.CUST.GUEST_EXPERIENCE_OSAT_INIT('SURVEY_CHANNEL') ) AS f
LEFT OUTER JOIN
IDS_DEV.INT_REF_BV.SURVEY_CHANNEL_BV AS sc ON f.SURVEY_CHANNEL_ID = sc.SURVEY_CHANNEL_ID;
create view IF NOT EXISTS LABOR_QTR_HR_V(
	BUSINESS_DT,
	START_TM,
	END_TM,
	STORE_ID,
	ACTUAL_HOURS_NBR,
	SCHEDULED_HOURS_NBR,
	IDEAL_HOURS_NBR,
	PLANNED_CREDIT_HOURS_NBR,
	UNPLANNED_CREDIT_HOURS_NBR,
	BRAND_ID,
	SOURCE_SYSTEM_NM,
	CDM_LOAD_DT,
	LOAD_TYP,
	LOAD_ID,
	LOAD_DTTM
) as 
SELECT LABOR_QTRHR_FACT.BUSINESSDATE,LABOR_QTRHR_FACT.STARTTIME,LABOR_QTRHR_FACT.ENDTIME,LABOR_QTRHR_FACT.STOREID,LABOR_QTRHR_FACT.ACTUALHOURS,LABOR_QTRHR_FACT.SCHEDULEDHOURS,LABOR_QTRHR_FACT.IDEALHOURS,LABOR_QTRHR_FACT.PLANNEDCREDITHOURS,LABOR_QTRHR_FACT.UNPLANNEDCREDITHOURS,LABOR_QTRHR_FACT.BRANDID,LABOR_QTRHR_FACT.SOURCE,LABOR_QTRHR_FACT.CDMLOADDATE,LABOR_QTRHR_FACT.LOADTYPE,LABOR_QTRHR_FACT.LOADID,LABOR_QTRHR_FACT.LOADDTTM
FROM POLARIS_DEV.OPDM.LABOR_QTRHR_FACT;
create view IF NOT EXISTS LOCATION_HIERARCHY_V(
	LOCATION_ID,
	LEVEL1_ID,
	LEVEL1_NM,
	LEVEL1_MANAGER_ID,
	LEVEL1_MANAGER_NM,
	LEVEL2_ID,
	LEVEL2_NM,
	LEVEL2_MANAGER_ID,
	LEVEL2_MANAGER_NM,
	LEVEL3_ID,
	LEVEL3_NM,
	LEVEL3_MANAGER_ID,
	LEVEL3_MANAGER_NM,
	LEVEL4_ID,
	LEVEL4_NM,
	LEVEL4_MANAGER_ID,
	L4_MANAGER_NM,
	LEVEL5_ID,
	LEVEL5_NM,
	LEVEL5_MANAGER_ID,
	LEVEL5_MANAGER_NM,
	FRANCHISE_CONSULTANT1_NAME,
	FRANCHISE_CONSULTANT2_NAME,
	FRANCHISE_CONSULTANT3_NAME,
	BRAND_ID,
	SOURCE_SYSTEM_NM,
	CDM_LOAD_DT,
	LOAD_TYP,
	LOAD_ID,
	LOAD_DTTM
) as 
SELECT LOCATION_HIERARCHY_DIM.LOCATIONID,LOCATION_HIERARCHY_DIM.L1ID,LOCATION_HIERARCHY_DIM.L1NAME,LOCATION_HIERARCHY_DIM.L1MANAGERID,LOCATION_HIERARCHY_DIM.L1MANAGER,LOCATION_HIERARCHY_DIM.L2ID,LOCATION_HIERARCHY_DIM.L2NAME,LOCATION_HIERARCHY_DIM.L2MANAGERID,LOCATION_HIERARCHY_DIM.L2MANAGER,LOCATION_HIERARCHY_DIM.L3ID,LOCATION_HIERARCHY_DIM.L3NAME,LOCATION_HIERARCHY_DIM.L3MANAGERID,LOCATION_HIERARCHY_DIM.L3MANAGER,LOCATION_HIERARCHY_DIM.L4ID,LOCATION_HIERARCHY_DIM.L4NAME,LOCATION_HIERARCHY_DIM.L4MANAGERID,LOCATION_HIERARCHY_DIM.L4MANAGER,LOCATION_HIERARCHY_DIM.L5ID,LOCATION_HIERARCHY_DIM.L5NAME,
LOCATION_HIERARCHY_DIM.FRANCHISE_CONSULTANT1_NAME,LOCATION_HIERARCHY_DIM.FRANCHISE_CONSULTANT2_NAME,LOCATION_HIERARCHY_DIM.FRANCHISE_CONSULTANT3_NAME
,LOCATION_HIERARCHY_DIM.L5MANAGERID,LOCATION_HIERARCHY_DIM.L5MANAGER,LOCATION_HIERARCHY_DIM.BRANDID,LOCATION_HIERARCHY_DIM.SOURCE,LOCATION_HIERARCHY_DIM.CDMLOADDATE,LOCATION_HIERARCHY_DIM.LOADTYPE,LOCATION_HIERARCHY_DIM.LOADID,LOCATION_HIERARCHY_DIM.LOADDTTM
FROM POLARIS_DEV.OPDM.LOCATION_HIERARCHY_DIM;
create view IF NOT EXISTS OPERATION_MANAGEMENT_HIERARCHY_BV(
	LOCATION_ID,
	LEVEL1_ID,
	LEVEL1_NM,
	LEVEL1_MANAGER_ID,
	LEVEL1_MANAGER_NM,
	LEVEL2_ID,
	LEVEL2_NM,
	LEVEL2_MANAGER_ID,
	LEVEL2_MANAGER_NM,
	LEVEL3_ID,
	LEVEL3_NM,
	LEVEL3_MANAGER_ID,
	LEVEL3_MANAGER_NM,
	LEVEL4_ID,
	LEVEL4_NM,
	LEVEL4_MANAGER_ID,
	LEVEL4_MANAGER_NM,
	LEVEL5_ID,
	LEVEL5_NM,
	LEVEL5_MANAGER_ID,
	LEVEL5_MANAGER_NM,
	FRANCHISE_CONSULTANT1_NAME,
	FRANCHISE_CONSULTANT2_NAME,
	FRANCHISE_CONSULTANT3_NAME,
	BRAND_ID,
	CDM_LOAD_DT,
	LOAD_TYP,
	SOURCE_SYSTEM_NM,
	LOAD_ID,
	LOAD_DTTM,
	UPDATE_ID,
	UPDATE_DTTM
) as SELECT
	LOCATION_ID,
	LEVEL1_ID,
	LEVEL1_NM,
	LEVEL1_MANAGER_ID,
	LEVEL1_MANAGER_NM,
	LEVEL2_ID,
	LEVEL2_NM,
	LEVEL2_MANAGER_ID,
	LEVEL2_MANAGER_NM,
	LEVEL3_ID,
	LEVEL3_NM,
	LEVEL3_MANAGER_ID,
	LEVEL3_MANAGER_NM,
	LEVEL4_ID,
	LEVEL4_NM,
	LEVEL4_MANAGER_ID,
	LEVEL4_MANAGER_NM,
	LEVEL5_ID,
	LEVEL5_NM,
	LEVEL5_MANAGER_ID,
	LEVEL5_MANAGER_NM,
	FRANCHISE_CONSULTANT1_NM,
	FRANCHISE_CONSULTANT2_NM,
	FRANCHISE_CONSULTANT3_NM,
	--DIVISION_VICE_PRESIDENT_NAME,
	BRAND_ID,
	CDM_LOAD_DT,
	LOAD_TYP,
    SOURCE_SYSTEM_NM,
	LOAD_ID,
	LOAD_DTTM,
    UPDATE_ID,
    UPDATE_DTTM
FROM IDM_DEV.COREDIM.OPERATION_MANAGEMENT_HIERARCHY;
create view IF NOT EXISTS ORDER_LINE_ITEM_PREP_V(
	STORE_ID,
	BUMP_DTTM,
	SEND_DTTM,
	FIRE_DTTM,
	ORDER_LINE_PREP_LOCATION_ID,
	ORDER_LINE_ID,
	ORDER_ID,
	CDM_LOAD_DT,
	SOURCE_SYSTEM_NM,
	BRAND_ID,
	LOAD_ID,
	LOAD_DTTM
) as 
SELECT ORDERLINEPREP_FACT.STOREID,ORDERLINEPREP_FACT.BUMPTIME,ORDERLINEPREP_FACT.SENDTIME,ORDERLINEPREP_FACT.FIRETIME,ORDERLINEPREP_FACT.ORDERLINEPREPLOCATIONID,ORDERLINEPREP_FACT.ORDERLINEID,ORDERLINEPREP_FACT.ORDERID,ORDERLINEPREP_FACT.CDMLOADDATE,ORDERLINEPREP_FACT.SOURCE,ORDERLINEPREP_FACT.BRANDID,ORDERLINEPREP_FACT.LOADID,ORDERLINEPREP_FACT.LOADDTTM
FROM POLARIS_DEV.OPDM.ORDERLINEPREP_FACT;
create view IF NOT EXISTS SALES_FORECAST_DAY_V(
	STORE_ID,
	BRAND_ID,
	BUSINESS_DT,
	SALES_AMT,
	TRANSACTION_CNT,
	FORECAST_TYP,
	SOURCE_SYSTEM_NM,
	CDM_LOAD_DT,
	LOAD_TYP,
	LOAD_ID,
	LOAD_DTTM
) as 
SELECT SALESFORECAST_DAY_FACT.STOREID,SALESFORECAST_DAY_FACT.BRANDID,SALESFORECAST_DAY_FACT.BUSINESSDATE,SALESFORECAST_DAY_FACT.SALESAMOUNT,SALESFORECAST_DAY_FACT.NUMBEROFTRANSACTIONS,SALESFORECAST_DAY_FACT.FORECASTTYPE,SALESFORECAST_DAY_FACT.SOURCE,SALESFORECAST_DAY_FACT.CDMLOADDATE,SALESFORECAST_DAY_FACT.LOADTYPE,SALESFORECAST_DAY_FACT.LOADID,SALESFORECAST_DAY_FACT.LOADDTTM
FROM POLARIS_DEV.OPDM.SALESFORECAST_DAY_FACT;
create view IF NOT EXISTS SALES_FORECAST_QTR_HR_V(
	STORE_ID,
	BRAND_ID,
	BUSINESS_DT,
	QTR_HOUR_BEGIN_DT,
	QTR_HOUR_END_DT,
	SALES_AMT,
	TRANSACTION_CNT,
	FORECAST_TYP,
	LOAD_TYP,
	SOURCE_SYSTEM_NM,
	CDM_LOAD_DT,
	LOAD_ID,
	LOAD_DTTM
) as 
SELECT SALESFORECAST_QTRHR_FACT.STOREID,SALESFORECAST_QTRHR_FACT.BRANDID,SALESFORECAST_QTRHR_FACT.BUSINESSDATE,SALESFORECAST_QTRHR_FACT.QUARTERHOURBEGIN,SALESFORECAST_QTRHR_FACT.QUARTERHOUREND,SALESFORECAST_QTRHR_FACT.SALESAMOUNT,SALESFORECAST_QTRHR_FACT.NUMBEROFTRANSACTIONS,SALESFORECAST_QTRHR_FACT.FORECASTTYPE,SALESFORECAST_QTRHR_FACT.LOADTYPE,SALESFORECAST_QTRHR_FACT.SOURCE,SALESFORECAST_QTRHR_FACT.CDMLOADDATE,SALESFORECAST_QTRHR_FACT.LOADID,SALESFORECAST_QTRHR_FACT.LOADDTTM
FROM POLARIS_DEV.OPDM.SALESFORECAST_QTRHR_FACT;
create view IF NOT EXISTS SCHEDULE_AND_ACTUAL_HRS_V(
	EMPLOYEE_PUNCHES_KEY,
	STORE_ID,
	DATE,
	CLOCKIN_DT,
	CLOCKIN_TM,
	CLOCKOUT_DT,
	CLOCKOUT_TM,
	PUNCH_TYP,
	ACTIVITY_TYP,
	HOURS_NBR,
	JOB_CD,
	BRAND_ID,
	LAST_NM,
	FIRST_NM,
	LOAD_TYP,
	SOURCE_SYSYTEM_NM,
	CDM_LOAD_DT,
	LOAD_ID,
	LOAD_DTTM
) as 
SELECT SCHEDULEDANDACTUALHOURS_FACT.EMPLOYEEPUNCHESKEY,SCHEDULEDANDACTUALHOURS_FACT.STOREID,SCHEDULEDANDACTUALHOURS_FACT.DATEKEY,SCHEDULEDANDACTUALHOURS_FACT.CLOCKINDATE,SCHEDULEDANDACTUALHOURS_FACT.CLOCKINTIME,SCHEDULEDANDACTUALHOURS_FACT.CLOCKOUTDATE,SCHEDULEDANDACTUALHOURS_FACT.CLOCKOUTTIME,SCHEDULEDANDACTUALHOURS_FACT.PUNCHTYPE,SCHEDULEDANDACTUALHOURS_FACT.ACTIVITYTYPE,SCHEDULEDANDACTUALHOURS_FACT.HOURS,SCHEDULEDANDACTUALHOURS_FACT.JOBCODE,SCHEDULEDANDACTUALHOURS_FACT.BRANDID,SCHEDULEDANDACTUALHOURS_FACT.LASTNAME,SCHEDULEDANDACTUALHOURS_FACT.FIRSTNAME,SCHEDULEDANDACTUALHOURS_FACT.LOADTYPE,SCHEDULEDANDACTUALHOURS_FACT.SOURCE,SCHEDULEDANDACTUALHOURS_FACT.CDMLOADDATE,SCHEDULEDANDACTUALHOURS_FACT.LOADID,SCHEDULEDANDACTUALHOURS_FACT.LOADDTTM
FROM POLARIS_DEV.OPDM.SCHEDULEDANDACTUALHOURS_FACT;
create view IF NOT EXISTS SPEED_OF_SERVICE_V(
	STORE_ID,
	BUSINESS_DT,
	CAR_ID,
	DAY_PART_NM,
	ARRIVAL_DTTM,
	DEPARTURE_DTTM,
	GOAL_NM,
	REPORTING_NM,
	GOAL_SECONDS_NBR,
	SERVICE_POINT_NBR,
	DISCARD_IND,
	DISCARD_CD,
	BRAND_ID,
	SOURCE_SYSTEM_NM,
	CDM_LOAD_DT,
	LOAD_TYP,
	LOAD_ID,
	LOAD_DTTM
) as 
SELECT SPEEDOFSERVICE_FACT.STOREID,SPEEDOFSERVICE_FACT.BUSINESSDATE,SPEEDOFSERVICE_FACT.CARID,SPEEDOFSERVICE_FACT.DAYPARTNAME,SPEEDOFSERVICE_FACT.ARRIVAL,SPEEDOFSERVICE_FACT.DEPARTURE,SPEEDOFSERVICE_FACT.GOALNAME,SPEEDOFSERVICE_FACT.REPORTINGNAME,SPEEDOFSERVICE_FACT.GOALSECONDS,SPEEDOFSERVICE_FACT.SERVICEPOINTTIME,CASE WHEN SPEEDOFSERVICE_FACT.DISCARD = 'True' THEN 1 WHEN SPEEDOFSERVICE_FACT.DISCARD = 'False' THEN 0 ELSE NULL END AS DISCARD 
,SPEEDOFSERVICE_FACT.DISCARDCODE,SPEEDOFSERVICE_FACT.BRANDID,SPEEDOFSERVICE_FACT.SOURCE,SPEEDOFSERVICE_FACT.CDMLOADDATE,SPEEDOFSERVICE_FACT.LOADTYPE,SPEEDOFSERVICE_FACT.LOADID,SPEEDOFSERVICE_FACT.LOADDTTM
FROM POLARIS_DEV.OPDM.SPEEDOFSERVICE_FACT;
create view IF NOT EXISTS STORE_HRS_V(
	STORE_ID,
	DAY_OF_WEEK_NM,
	OPEN_TM,
	CLOSE_TM,
	BRAND_ID,
	CDM_LOAD_DT,
	LOAD_ID,
	LOAD_DTTM
) as 
SELECT STOREHOURS_DIM.STOREID,STOREHOURS_DIM.DAYOFWEEK,STOREHOURS_DIM.OPENTIME,STOREHOURS_DIM.CLOSETIME,STOREHOURS_DIM.BRANDID,STOREHOURS_DIM.CDMLOADDATE,STOREHOURS_DIM.LOADID,STOREHOURS_DIM.LOADDTTM
FROM POLARIS_DEV.OPDM.STOREHOURS_DIM;
create view IF NOT EXISTS VISIT_SURVEY_V(
	SURVEY_ID,
	STORE_ID,
	SURVEY_DT,
	QUESTION_ID,
	QUESTION_LABEL_TXT,
	QUESTION_TXT,
	RESPONSE_TXT,
	POINTS_POSSIBLE_NBR,
	BRAND_ID,
	CDM_LOAD_DT,
	LOAD_ID,
	LOAD_DTTM
) as 
SELECT VISITSURVEY_FACT.SURVEYID,VISITSURVEY_FACT.STOREID,VISITSURVEY_FACT.SURVEYDATE,VISITSURVEY_FACT.QUESTIONID,VISITSURVEY_FACT.QUESTIONLABEL,VISITSURVEY_FACT.QUESTIONTEXT,VISITSURVEY_FACT.RESPONSETEXT,VISITSURVEY_FACT.POINTSPOSSIBLE,VISITSURVEY_FACT.BRANDID,VISITSURVEY_FACT.CDMLOADDATE,VISITSURVEY_FACT.LOADID,VISITSURVEY_FACT.LOADDTTM
FROM POLARIS_DEV.OPDM.VISITSURVEY_FACT;