create or replace view CUST_ADDRESS_PLR_BV(
	MEMBERID,
	ADDRESSLINE1,
	ADDRESSLINE2,
	CITY,
	STATE,
	COUNTRYCODE,
	ZIPCODE,
	OPTIN,
	LOADEDDATE,
	MODIFIEDDATE,
	PRIVACY,
	BRANDID,
	CDMLOADDATE,
	INSPIREID,
	SOURCE,
	FILENAME
) as SELECT
 "MEMBERID", "ADDRESSLINE1", "ADDRESSLINE2", "CITY", "STATE", "COUNTRYCODE", "ZIPCODE", "OPTIN", "LOADEDDATE", "MODIFIEDDATE", "PRIVACY", "BRANDID", "CDMLOADDATE", "INSPIREID", "SOURCE", "FILENAME"
 FROM %%CDMSYNC%%.IRB."CUST_ADDRESS_PLR";