create TABLE IF NOT EXISTS FLYWAY_SCHEMA_HISTORY (
	INSTALLED_RANK NUMBER(38,0) NOT NULL,
	VERSION VARCHAR(50),
	DESCRIPTION VARCHAR(200),
	TYPE VARCHAR(20) NOT NULL,
	SCRIPT VARCHAR(1000) NOT NULL,
	CHECKSUM NUMBER(38,0),
	INSTALLED_BY VARCHAR(100) NOT NULL,
	INSTALLED_ON TIMESTAMP_LTZ(9) NOT NULL DEFAULT CURRENT_TIMESTAMP(),
	EXECUTION_TIME NUMBER(38,0) NOT NULL,
	SUCCESS BOOLEAN NOT NULL,
	primary key (INSTALLED_RANK)
);
create view IF NOT EXISTS REST(
	REST_KEY,
	BRAND_ID,
	REST_ID,
	SITE_ID,
	OWNER_ID,
	FRAN_IND,
	REST_NAME,
	ADDRESS_LINE1_TXT,
	ADDRESS_LINE2_TXT,
	ADDRESS_LINE3_TXT,
	CITY,
	COUNTRY_NAME,
	STATE,
	PROVINCE,
	ZIP_CODE,
	REST_STATUS_TYPE,
	REST_EMAIL_TXT,
	REST_PHONE_NBR,
	DIVISION_NBR,
	OPEN_DATE,
	CLOSURE_DATE,
	LEGAL_NAME,
	FRANCHISEE_NAME,
	DIVISION_NAME,
	TEMP_CLOSED_DATE,
	REOPEN_DATE,
	TEMP_CLOSURE_REASON,
	REMODEL_LEVEL_TYPE,
	REMODEL_ACTIVITY_TYPE,
	REMODEL_PROGRAM,
	CONSTRUCTION_STATUS_CODE,
	PROJECTED_UNDER_CONSTRUCTION_DATE,
	UNDER_CONSTRUCTION_DATE,
	COMPLETED_DATE,
	CONSTRUCTION_DUE_DATE,
	DMA_CODE,
	DMA_NAME,
	DMA_SOURCE_NAME,
	TIME_ZONE,
	LATITUDE_NBR,
	LONGITUDE_NBR,
	FACILITY_TYPE,
	BUILDING_TYPE,
	PARKING_CNT,
	SEAT_CNT,
	OWNERSHIP_TYPE,
	BREAKFAST_IND,
	DRIVETHRU_IND,
	BUILDING_SQFT_NBR,
	CDM_LOAD_DATE,
	SOURCE_SYSTEM_NAME,
	LOAD_ID,
	LOAD_DTTM,
	UPDATE_ID,
	UPDATE_DTTM
) as 
SELECT c.STORE_KEY AS REST_KEY
, c.BRAND_ID AS BRAND_ID
, c.STORE_ID AS REST_ID
, c.SITE_ID AS SITE_ID
, c.OWNER_ID AS OWNER_ID
, c.FRANCHISEE_IND AS FRAN_IND
, c.STORE_NM AS REST_NAME
, c.ADDRESS_1_TXT AS ADDRESS_LINE1_TXT
, c.ADDRESS_2_TXT AS ADDRESS_LINE2_TXT
, c.ADDRESS_3_TXT AS ADDRESS_LINE3_TXT
, c.CITY_NM AS CITY
, c.COUNTRY_NM AS COUNTRY_NAME
, c.STATE_NM AS STATE
, c.PROVINCE_NM AS PROVINCE
, c.ZIP_CD AS ZIP_CODE
, c.STORE_STATUS_TYP AS REST_STATUS_TYPE
, c.STORE_EMAIL_TXT AS REST_EMAIL_TXT
, c.STORE_PHONE_NBR AS REST_PHONE_NBR
, c.DIVISION_NBR AS DIVISION_NBR
, c.OPEN_DT AS OPEN_DATE
, c.CLOSURE_DT AS CLOSURE_DATE
, c.LEGAL_NM
, c.FRANCHISEE_NM
, c.DIVISION_NM
, c.TEMP_CLOSED_DT AS TEMP_CLOSED_DATE
, c.REOPEN_DT AS REOPEN_DATE
, c.TEMP_CLOSURE_REASON_TXT AS TEMP_CLOSURE_REASON
, c.REMODEL_LEVEL_TYP AS REMODEL_LEVEL_TYPE
, c.REMODEL_ACTIVITY_TYP AS REMODEL_ACTIVITY_TYPE
, c.REMODEL_PROGRAM_TYP AS REMODEL_PROGRAM
, c.CONSTRUCTION_STATUS_CD AS CONSTRUCTION_STATUS_CODE
, c.PROJECTED_UNDER_CONSTRUCTION_DT AS PROJECTED_UNDER_CONSTRUCTION_DATE
, c.UNDER_CONSTRUCTION_DT AS UNDER_CONSTRUCTION_DATE
, c.COMPLETED_DT AS COMPLETED_DATE
, c.CONSTRUCTION_DUE_DT AS CONSTRUCTION_DUE_DATE
, c.DMA_CD AS DMA_CODE
, c.DMA_NM AS DMA_NAME
, c.DMA_SOURCE_NM AS DMA_SOURCE_NAME
, c.TM_ZONE_NM AS TIME_ZONE
, c.LATITUDE_NBR AS LATITUDE_NBR
, c.LONGITUDE_NBR AS LONGITUDE_NBR
, c.FACILITY_TYP AS FACILITY_TYPE
, c.BUILDING_TYP AS BUILDING_TYPE
, c.PARKING_CNT AS PARKING_CNT
, c.SEAT_CNT AS SEAT_CNT
, c.OWNERSHIP_TYP AS OWNERSHIP_TYPE
, c.BREAKFAST_IND AS BREAKFAST_IND
, c.DRIVETHRU_IND AS DRIVETHRU_IND
, c.BLDG_SQFT_NBR AS BUILDING_SQFT_NBR
, c.CDM_LOAD_DT AS CDM_LOAD_DATE
, c.SOURCE_SYSTEM_NM AS SOURCE_SYSTEM_NAME
, c.LOAD_ID AS LOAD_ID
, c.LOAD_DTTM AS LOAD_DTTM
, c.UPDATE_ID AS UPDATE_ID
, c.UPDATE_DTTM AS UPDATE_DTTM
FROM IDM_DEV.COREDIM_BV.RESTAURANT_SCD_DIM_BV c
WHERE c.CURRENT_IND = 'Y';
create view IF NOT EXISTS REST_SCD(
	REST_KEY,
	BRAND_ID,
	REST_ID,
	EFFECTIVE_START_DATE,
	SITE_ID,
	OWNER_ID,
	FRAN_IND,
	REST_NAME,
	ADDRESS_LINE1_TXT,
	ADDRESS_LINE2_TXT,
	ADDRESS_LINE3_TXT,
	CITY,
	COUNTRY_NAME,
	STATE,
	PROVINCE,
	ZIP_CODE,
	REST_STATUS_TYPE,
	REST_EMAIL_TXT,
	REST_PHONE_NBR,
	DIVISION_NBR,
	OPEN_DATE,
	CLOSURE_DATE,
	LEGAL_NAME,
	FRANCHISEE_NAME,
	DIVISION_NAME,
	TEMP_CLOSED_DATE,
	REOPEN_DATE,
	TEMP_CLOSURE_REASON,
	REMODEL_LEVEL_TYPE,
	REMODEL_ACTIVITY_TYPE,
	REMODEL_PROGRAM,
	CONSTRUCTION_STATUS_CODE,
	PROJECTED_UNDER_CONSTRUCTION_DATE,
	UNDER_CONSTRUCTION_DATE,
	COMPLETED_DATE,
	CONSTRUCTION_DUE_DATE,
	DMA_CODE,
	DMA_NAME,
	DMA_SOURCE_NAME,
	TIME_ZONE,
	LATITUDE_NBR,
	LONGITUDE_NBR,
	FACILITY_TYPE,
	BUILDING_TYPE,
	PARKING_CNT,
	SEAT_CNT,
	OWNERSHIP_TYPE,
	BREAKFAST_IND,
	DRIVETHRU_IND,
	BUILDING_SQFT_NBR,
	CDM_LOAD_DATE,
	EFFECTIVE_END_DATE,
	CURR_IND,
	SOURCE_SYSTEM_NAME,
	LOAD_ID,
	LOAD_DTTM,
	UPDATE_ID,
	UPDATE_DTTM
) as 
SELECT c.STORE_KEY AS REST_KEY
, c.BRAND_ID AS BRAND_ID
, c.STORE_ID AS REST_ID
, c.EFFECTIVE_BEGIN_DT AS EFFECTIVE_START_DATE
, c.SITE_ID AS SITE_ID
, c.OWNER_ID AS OWNER_ID
, c.FRANCHISEE_IND AS FRAN_IND
, c.STORE_NM AS REST_NAME
, c.ADDRESS_1_TXT AS ADDRESS_LINE1_TXT
, c.ADDRESS_2_TXT AS ADDRESS_LINE2_TXT
, c.ADDRESS_3_TXT AS ADDRESS_LINE3_TXT
, c.CITY_NM AS CITY
, c.COUNTRY_NM AS COUNTRY_NAME
, c.STATE_NM AS STATE
, c.PROVINCE_NM AS PROVINCE
, c.ZIP_CD AS ZIP_CODE
, c.STORE_STATUS_TYP AS REST_STATUS_TYPE
, c.STORE_EMAIL_TXT AS REST_EMAIL_TXT
, c.STORE_PHONE_NBR AS REST_PHONE_NBR
, c.DIVISION_NBR AS DIVISION_NBR
, c.OPEN_DT AS OPEN_DATE
, c.CLOSURE_DT AS CLOSURE_DATE
, c.LEGAL_NM
, c.FRANCHISEE_NM
, c.DIVISION_NM
, c.TEMP_CLOSED_DT AS TEMP_CLOSED_DATE
, c.REOPEN_DT AS REOPEN_DATE
, c.TEMP_CLOSURE_REASON_TXT AS TEMP_CLOSURE_REASON
, c.REMODEL_LEVEL_TYP AS REMODEL_LEVEL_TYPE
, c.REMODEL_ACTIVITY_TYP AS REMODEL_ACTIVITY_TYPE
, c.REMODEL_PROGRAM_TYP AS REMODEL_PROGRAM
, c.CONSTRUCTION_STATUS_CD AS CONSTRUCTION_STATUS_CODE
, c.PROJECTED_UNDER_CONSTRUCTION_DT AS PROJECTED_UNDER_CONSTRUCTION_DATE
, c.UNDER_CONSTRUCTION_DT AS UNDER_CONSTRUCTION_DATE
, c.COMPLETED_DT AS COMPLETED_DATE
, c.CONSTRUCTION_DUE_DT AS CONSTRUCTION_DUE_DATE
, c.DMA_CD AS DMA_CODE
, c.DMA_NM AS DMA_NAME
, c.DMA_SOURCE_NM AS DMA_SOURCE_NAME
, c.TM_ZONE_NM AS TIME_ZONE
, c.LATITUDE_NBR AS LATITUDE_NBR
, c.LONGITUDE_NBR AS LONGITUDE_NBR
, c.FACILITY_TYP AS FACILITY_TYPE
, c.BUILDING_TYP AS BUILDING_TYPE
, c.PARKING_CNT AS PARKING_CNT
, c.SEAT_CNT AS SEAT_CNT
, c.OWNERSHIP_TYP AS OWNERSHIP_TYPE
, c.BREAKFAST_IND AS BREAKFAST_IND
, c.DRIVETHRU_IND AS DRIVETHRU_IND
, c.BLDG_SQFT_NBR AS BUILDING_SQFT_NBR
, c.CDM_LOAD_DT AS CDM_LOAD_DATE
, c.EFFECTIVE_END_DT AS EFFECTIVE_END_DATE
, c.CURRENT_IND AS CURR_IND
, c.SOURCE_SYSTEM_NM AS SOURCE_SYSTEM_NAME
, c.LOAD_ID AS LOAD_ID
, c.LOAD_DTTM AS LOAD_DTTM
, c.UPDATE_ID AS UPDATE_ID
, c.UPDATE_DTTM AS UPDATE_DTTM
FROM IDM_DEV.COREDIM_BV.RESTAURANT_SCD_DIM_BV c;