ALTER SESSION SET QUOTED_IDENTIFIERS_IGNORE_CASE = FALSE;

CREATE TABLE IF NOT EXISTS "DK20181107" ("PROFILEID" VARCHAR(32), "FIRSTNAME" VARCHAR(30), "LASTNAME" VARCHAR(21), "EMAILADDRESS" VARCHAR(49), "ACTIVE_WEEK_1" VARCHAR(1), "ACTIVE_WEEK_2" VARCHAR(1), "ACTIVE_WEEK_3" VARCHAR(1), "ACTIVE_WEEK_4" VARCHAR(1), "ACTIVE_WEEK_5" VARCHAR(1), "ACTIVE_WEEK_6" VARCHAR(1), "ACTIVE_WEEK_7" VARCHAR(1), "ACTIVE_WEEK_8" VARCHAR(1), "ACTIVE_WEEK_9" VARCHAR(1), "GUID" VARCHAR(48));

/* <sc-table> CC_NAME_DATA </sc-table> */
CREATE TABLE IF NOT EXISTS "CC_NAME_DATA" ("DATEOFBUSINESS" DATE, "STORE" DECIMAL(10,0), "CHECK1" DECIMAL(10,0), "CARDTYPE" VARCHAR(75), "IDENT" VARCHAR(75), "AUTH" VARCHAR(75), "NAME" VARCHAR(75), "AMOUNT" DECIMAL(10,2), "TRACK" VARCHAR(75), "HOUROFDAY" DECIMAL(4,0), "MINUTEOFHOUR" DECIMAL(4,0));



/* <sc-table> PROMO_TRP </sc-table> */

CREATE TABLE IF NOT EXISTS "PROMO_TRP" ("ADI" INTEGER, "FRANID" INTEGER, "FISCAL_YEAR" VARCHAR(2000), "FISCAL_MONTH" INTEGER, "FISCAL_WEEK" INTEGER, "TRPS" INTEGER);



/* <sc-table> KANTAR_ONLINE_DIGITAL </sc-table> */

CREATE TABLE IF NOT EXISTS "KANTAR_ONLINE_DIGITAL" ("SUBCATEGORY" VARCHAR(100), "MICROCATEGORY" VARCHAR(100), "ADVERTISER" VARCHAR(100), "BRAND" VARCHAR(100), "PRODUCT" VARCHAR(1000), "TITLE" VARCHAR(1000), "ADSCOPE_ID" VARCHAR(100), "AD_SIZE" VARCHAR(100), "MEDIA" VARCHAR(100), "MARKET" VARCHAR(100), "DATE_AIRED" VARCHAR(100), "DOLS" DECIMAL(10,2), "DIGITAL_IMPRESSIONS" DECIMAL(10,2));



/* <sc-table> KANTAR_TV </sc-table> */

CREATE TABLE IF NOT EXISTS "KANTAR_TV" ("SUBCATEGORY" VARCHAR(100), "MICROCATEGORY" VARCHAR(100), "ADVERTISER" VARCHAR(100), "BRAND" VARCHAR(100), "PRODUCT" VARCHAR(1000), "TITLE" VARCHAR(1000), "ADSCOPE_ID" VARCHAR(100), "SPOT_LENGTH" VARCHAR(100), "MEDIA" VARCHAR(100), "MARKET" VARCHAR(100), "DATE_AIRED" VARCHAR(100), "DAYPART" VARCHAR(100), "TIME_OF_AIR" VARCHAR(100), "DOLS" DECIMAL(10,2));



/* <sc-table> ARBYS_LC_REPORT_store </sc-table> */

CREATE TABLE IF NOT EXISTS "ARBYS_LC_REPORT_store" ("PERIOD" VARCHAR(10), "LC" VARCHAR(11), "STORE" INTEGER, "SALES_TOT" DECIMAL(36,15), "TXNID_TOT" INTEGER, "CUSTOMERS" INTEGER, "REST_DMA_DESC" VARCHAR(30), "REST_ADDRCITY" VARCHAR(20), "REST_ADDRCOUNTY" VARCHAR(16), "REST_ADDRSTATE" VARCHAR(2), "REST_LATITUDE" DECIMAL(36,15), "REST_LONGITUDE" DECIMAL(36,15), "ARG_DISTRICT_NAME" VARCHAR(24), "ARG_SUBREGION_NAME" VARCHAR(9));



/* <sc-table> ITEM_MAPPING_MASTER_BKUP </sc-table> */

CREATE TABLE IF NOT EXISTS "ITEM_MAPPING_MASTER_BKUP" ("ITEM_NUMBER" BIGINT, "ITEM_NAME" VARCHAR(100), "AFA_PROD_DESC" VARCHAR(100), "AS_MENU_GROUPS" VARCHAR(50), "BCG_NAME" VARCHAR(100), "BCG_COUPON_NAME" VARCHAR(100), "OFFER_ITEM" VARCHAR(100), "COUPON_TYPE" VARCHAR(100), "MAIN_PROTEIN" VARCHAR(100), "MENUGROUP" VARCHAR(100), "MENU" VARCHAR(100), "TYPE" VARCHAR(100), "COMPONENT_ID" INTEGER, "AFA_PRODUCT_ID" INTEGER);



/* <sc-table> BWW_LINREG </sc-table> */

CREATE TABLE IF NOT EXISTS "BWW_LINREG" ("COEFF_NAME" VARCHAR(64), "COEFF_VALUE" DOUBLE);



/* <sc-table> KANTAR_RADIO_TEMP </sc-table> */

CREATE TABLE IF NOT EXISTS "KANTAR_RADIO_TEMP" ("SUBCATEGORY" VARCHAR(100), "MICROCATEGORY" VARCHAR(100), "ADVERTISER" VARCHAR(100), "BRAND" VARCHAR(100), "PRODUCT" VARCHAR(1000), "TITLE" VARCHAR(1000), "ADSCOPE_ID" VARCHAR(100), "SPOT_LENGTH" VARCHAR(100), "MARKET" VARCHAR(100), "DATE_AIRED" VARCHAR(100), "TIME_OF_AIR" VARCHAR(100), "DOLS" DECIMAL(10,2));



/* <sc-table> YODLEE_MARKET_DATA_BWW_DELIVERY </sc-table> */

CREATE TABLE IF NOT EXISTS "YODLEE_MARKET_DATA_BWW_DELIVERY" ("MERCHANT_NAME" VARCHAR(50), "YEAR" DOUBLE, "WEEK" DOUBLE, "OPTIMIZED_TRANSACTION_DATE" DATE, "TOTAL_BRAND_SALES" DOUBLE, "TOTAL_BRAND_TRANS" DOUBLE, "TOTAL_COMPSET_SALES" DOUBLE, "TOTAL_COMPSET_TRANS" DOUBLE);



/* <sc-table> CC_TRANS_A </sc-table> */

CREATE TABLE IF NOT EXISTS "CC_TRANS_A" ("TXNID" VARCHAR(100), "CNFOPK" INTEGER, "STORE" INTEGER, "AUTHORIZATION_CODE" VARCHAR(100), "TRANSACTION_DATE" DATE, "TRANSACTION_AMOUNT" DECIMAL(10,2), "MAPPING_DATE" DATE);



/* <sc-table> CUST_HISTORY_TEMP </sc-table> */

CREATE TABLE IF NOT EXISTS "CUST_HISTORY_TEMP" ("CNFOPK" INTEGER, "FISCAL_YEAR" DECIMAL(6,0), "FISCAL_PERIOD_NUMBER" TINYINT, "TXNS" INTEGER, "TOTALSPEND" DECIMAL(17,2));



/* <sc-table> ARGWEEKS </sc-table> */

CREATE TABLE IF NOT EXISTS "ARGWEEKS" ("FISCAL_YEAR" SMALLINT, "DAYS_DATE" DATE, "WEEKDAY" VARCHAR(10), "ARG_WEEK" TINYINT, "PERIOD" VARCHAR(3), "QUARTER" VARCHAR(3), "WEEKORDER" SMALLINT, "ADJ_COMP_DATE" DATE);



/* <sc-table> YODLEE_CHECK_DATA_TEMP </sc-table> */

CREATE TABLE IF NOT EXISTS "YODLEE_CHECK_DATA_TEMP" ("OPTIMIZED_TRANSACTION_DATE" DATE, "TOTAL_BRAND_SALES" DOUBLE, "TOTAL_BRAND_TRANS" DOUBLE, "CHECK_GROUP_1" VARCHAR(50), "MERCHANT_NAME" VARCHAR(50));



/* <sc-table> ARBYS_LC_REPORT_store_churn_5 </sc-table> */

CREATE TABLE IF NOT EXISTS "ARBYS_LC_REPORT_store_churn_5" ("PERIOD" VARCHAR(10), "TRACKED_DUM" VARCHAR(11), "PAYMENT_DESC_2" VARCHAR(16), "LC" VARCHAR(11), "STORE" INTEGER, "SALES_TOT" DECIMAL(36,15), "TXNID_TOT" INTEGER, "CUSTOMERS" INTEGER, "REST_DMA_DESC" VARCHAR(30), "REST_ADDRCITY" VARCHAR(20), "REST_ADDRCOUNTY" VARCHAR(16), "REST_ADDRSTATE" VARCHAR(2), "REST_LATITUDE" DECIMAL(36,15), "REST_LONGITUDE" DECIMAL(36,15), "REST_TYPE" VARCHAR(3), "ARG_DISTRICT_NAME" VARCHAR(24), "ARG_SUBREGION_NAME" VARCHAR(9));



/* <sc-table> CUSTOMERTRANSCC_1 </sc-table> */

CREATE TABLE IF NOT EXISTS "CUSTOMERTRANSCC_1" ("TXNID" VARCHAR(60), "CNFOPK" INTEGER, "STORE" INTEGER, "AUTHORIZATION_CODE" VARCHAR(8), "TRANSACTION_DATE" TIMESTAMP, "TRANSACTION_AMOUNT" DECIMAL(18,2), "MAPPING_DATE" TIMESTAMP);



/* <sc-table> GG_TEMP </sc-table> */

CREATE TABLE IF NOT EXISTS "GG_TEMP" ("NAME_IND" DECIMAL(1,0), "PAYMENT_DESC" VARCHAR(55), "YR" VARCHAR(4), "ORDERS" INTEGER);



/* <sc-table> CUSTOMER_TLD </sc-table> */

CREATE TABLE IF NOT EXISTS "CUSTOMER_TLD" ("CNFOPK" INTEGER, "UNIT_NUM" INTEGER, "DATETIME" TIMESTAMP, "CHECK1" INTEGER, "ITEMNUMBER" INTEGER, "ITEM_NAME" VARCHAR(255), "SALES" DECIMAL(18,2), "QUANTITY" INTEGER, "EMPLOYEE" INTEGER, "SUSPECT_DATA" INTEGER, "TXNID" VARCHAR(75), "REVENUE_CENTER" VARCHAR(27));



/* <sc-table> EMPYR_VALIDATION </sc-table> */

CREATE TABLE IF NOT EXISTS "EMPYR_VALIDATION" ("LAST4" DOUBLE, "TRANSACTION_DATE" DATE, "PROCESSED_DATE" DATE, "REVENUE" DOUBLE);



/* <sc-table> FORECAST_BWW_AH_FY_2018 </sc-table> */

CREATE TABLE IF NOT EXISTS "FORECAST_BWW_AH_FY_2018" ("REST_NUMBER" VARCHAR(10), "DAYS_DATE" DATE, "SEASON" DOUBLE, "TREND" DOUBLE, "REMAINDER" DOUBLE, "ETS_PRED" DOUBLE, "STL_PRED" DOUBLE, "SNAIVE_PRED" DOUBLE, "SALES_AFB" DOUBLE, "FCAST_KEY" DATE);
