ALTER SESSION SET QUOTED_IDENTIFIERS_IGNORE_CASE = FALSE;

/* <sc-table> EMPLOYEE </sc-table> */

CREATE TABLE IF NOT EXISTS "EMPLOYEE" ("CNFOPK" DECIMAL(20,0));



/* <sc-table> DIM_MENUITEM </sc-table> */

CREATE TABLE IF NOT EXISTS "DIM_MENUITEM" ("MENU_KEY" INTEGER, "PLU_NUMBER" VARCHAR(25), "PLU_DESC" VARCHAR(55), "ITEM_ID" INTEGER, "ITEM_DESC" VARCHAR(255), "ITEM_PRODUCT_ID" INTEGER, "ITEM_PRODUCT_DESC" VARCHAR(255), "ITEM_TYPE_CODE" VARCHAR(255), "POS_NAME" VARCHAR(10), "POS_ITEM_DESC" VARCHAR(255), "COMPONENT_ID" INTEGER, "COMPONENT_NAME" VARCHAR(255), "COUPON_NAME" VARCHAR(55), "COUPON_TYPE" VARCHAR(25), "MENU_GROUP" VARCHAR(255), "MENU_TYPE" VARCHAR(255), "MAIN_GROUP" VARCHAR(255), "MAIN_PROTEIN" VARCHAR(255), "EFFECTIVE_BEGIN_DATE" DATE, "EFFECTIVE_END_DATE" DATE, "ISCURRENT" BOOLEAN, "INFERRED_FLAG" BOOLEAN, "LOAD_ID" INTEGER, "LAST_UPDATE_DATE_TIME" TIMESTAMP);



/* <sc-table> AUTHCODE </sc-table> */

CREATE TABLE IF NOT EXISTS "AUTHCODE" ("STORE_NBR" INTEGER, "ORDER_NUMBER" INTEGER, "AUTH" VARCHAR(8), "SALES_DATE" DATE, "DSN" VARCHAR(20), "IMPORT_DATE" DATE);



/* <sc-table> ARBYS_LC_REPORT_store_churn_4 </sc-table> */

CREATE TABLE IF NOT EXISTS "ARBYS_LC_REPORT_store_churn_4" ("PERIOD" VARCHAR(10), "TRACKED_DUM" VARCHAR(11), "PAYMENT_DESC_2" VARCHAR(16), "LC" VARCHAR(11), "STORE" INTEGER, "SALES_TOT" DECIMAL(36,15), "TXNID_TOT" INTEGER, "CUSTOMERS" INTEGER, "REST_DMA_DESC" VARCHAR(30), "REST_ADDRCITY" VARCHAR(20), "REST_ADDRCOUNTY" VARCHAR(16), "REST_ADDRSTATE" VARCHAR(2), "REST_LATITUDE" DECIMAL(36,15), "REST_LONGITUDE" DECIMAL(36,15), "REST_TYPE" VARCHAR(3), "ARG_DISTRICT_NAME" VARCHAR(24), "ARG_SUBREGION_NAME" VARCHAR(9));



/* <sc-table> CUSTOMER_ORDER_RANK </sc-table> */

CREATE TABLE IF NOT EXISTS "CUSTOMER_ORDER_RANK" ("TXNID" VARCHAR(75), "CNFOPK" INTEGER, "DAYS_DATE" DATE, "TOTALSPEND" DECIMAL(6,2), "HOUROFDAY" TINYINT, "ORDERRANK" INTEGER);



/* <sc-table> ITEM_MAPPING_MASTER </sc-table> */

CREATE TABLE IF NOT EXISTS "ITEM_MAPPING_MASTER" ("ITEM_NUMBER" BIGINT, "ITEM_NAME" VARCHAR(100), "AFA_PROD_DESC" VARCHAR(100), "AS_MENU_GROUPS" VARCHAR(50), "BCG_NAME" VARCHAR(100), "BCG_COUPON_NAME" VARCHAR(100), "OFFER_ITEM" VARCHAR(100), "COUPON_TYPE" VARCHAR(100), "MAIN_PROTEIN" VARCHAR(100), "MENUGROUP" VARCHAR(100), "MENU" VARCHAR(100), "TYPE" VARCHAR(100), "COMPONENT_ID" INTEGER, "AFA_PRODUCT_ID" INTEGER);



/* <sc-table> CUSTOMER_NAME_AGE_GENDER_RACE </sc-table> */

CREATE TABLE IF NOT EXISTS "CUSTOMER_NAME_AGE_GENDER_RACE" ("CNFOPK" DECIMAL(15,0), "NAME" VARCHAR(75), "NAME_1" VARCHAR(75), "NAME_2" VARCHAR(75), "NAME_3" VARCHAR(75), "FIRST_NAME" VARCHAR(75), "LAST_NAME" VARCHAR(75), "AGE" DOUBLE, "GENDER" VARCHAR(75), "RACE" VARCHAR(75));



/* <sc-table> CUSTOMER_FREQUENCY_TEMP_B </sc-table> */

CREATE TABLE IF NOT EXISTS "CUSTOMER_FREQUENCY_TEMP_B" ("CNFOPK" DECIMAL(30,10), "TXNS" DECIMAL(30,10), "FIRSTVISIT" TIMESTAMP, "LASTVISIT" TIMESTAMP, "FIRSTSTORE" DECIMAL(30,10), "AVERAGECHECK" DECIMAL(30,10), "TOTALSPEND" DECIMAL(30,10), "FIRSTDMA_NBR" DECIMAL(30,10), "FIRSTDMA" VARCHAR(255), "FIRSTWEEKORDER" DECIMAL(30,10));



/* <sc-table> CUSTOMER_HISTORY </sc-table> */

CREATE TABLE IF NOT EXISTS "CUSTOMER_HISTORY" ("CNFOPK" INTEGER, "TRANSACTION_DATE" DATE, "TTM_TXNS" INTEGER);



/* <sc-table> BRS_RESPONSES_TEMP </sc-table> */

CREATE TABLE IF NOT EXISTS "BRS_RESPONSES_TEMP" ("CASE_ID" VARCHAR(100), "SURVEY_NAME" VARCHAR(100), "LAST_CONNECTION_DATE_KEY" INTEGER, "AGE_CONFIRM" BOOLEAN, "SERIAL" INTEGER, "STORE" INTEGER, "ERROR" VARCHAR(50), "QUESTION" VARCHAR(500), "RESPONSE" VARCHAR(8000));



/* <sc-table> COMP_FLAG_HIST_TEMP </sc-table> */

CREATE TABLE IF NOT EXISTS "COMP_FLAG_HIST_TEMP" ("MONTH_A" DECIMAL(2,0), "YEAR_A" DECIMAL(4,0), "DISCOUNT_TYPE_DESC" VARCHAR(255), "DISCOUNT_DESC" VARCHAR(255), "TXN_COUNT" INTEGER);



/* <sc-table> DIM_DATE_HOUR </sc-table> */

CREATE TABLE IF NOT EXISTS "DIM_DATE_HOUR" ("DAYS_DATE" DATE, "HOUR_OF_DAY" INTEGER);



/* <sc-table> CC_TEST </sc-table> */

CREATE TABLE IF NOT EXISTS "CC_TEST" ("DATEOFBUSINESS" DATE, "STORE" DECIMAL(10,0), "CHECKNUMBER" DECIMAL(10,0), "CARDTYPE" VARCHAR(75), "IDENT" VARCHAR(75), "NAME" VARCHAR(75), "AMOUNT" DECIMAL(10,2), "TRACK" VARCHAR(75), "HOUROFDAY" DECIMAL(4,0), "MINUTEOFHOUR" DECIMAL(4,0));



/* <sc-table> SKYHOOK_PRIOR_POST_LOCATIONS </sc-table> */

CREATE TABLE IF NOT EXISTS "SKYHOOK_PRIOR_POST_LOCATIONS" ("STORE_ID" DECIMAL(6,0), "STORE_VISIT_UTC_TS" TIMESTAMP, "USER_ID" VARCHAR(64), "DEVICE_TYPE" VARCHAR(64), "LOCATION_UTC_TS" TIMESTAMP, "LATITUDE" DECIMAL(8,4), "LONGITUDE" DECIMAL(8,4));



/* <sc-table> ARBYS_TERMS_20200101_20210831 </sc-table> */

CREATE TABLE IF NOT EXISTS "ARBYS_TERMS_20200101_20210831" ("DIVISION" VARCHAR(2000000), "DISTRICT" VARCHAR(2000000), "AREA" VARCHAR(2000000), "STORE_ID" VARCHAR(2000000), "STORE" VARCHAR(2000000), "TEAM_MEMBER_ID" VARCHAR(2000000), "SUPERVISORY_ORG" VARCHAR(2000000), "TERM_EFFECTIVE_DATE" DATE, "BUSINESS_PROCESS_REASON" VARCHAR(2000000), "TERM_CATEGORY" VARCHAR(2000000), "TERM_REASON" VARCHAR(2000000), "JOB_PROFILE" VARCHAR(2000000), "HIRE_DATE" DATE, "TERM_INITIATED_DATE" DATE, "DAYS_OF_SERVICE" INTEGER, "DATE_OF_BIRTH" DATE);



/* <sc-table> CUSTOMERPROMOTIONTABLE_TEMP1 </sc-table> */

CREATE TABLE IF NOT EXISTS "CUSTOMERPROMOTIONTABLE_TEMP1" ("TXNID" VARCHAR(75), "VISITTYPE" VARCHAR(8), "WEEK" DECIMAL(4,0), "PERIOD" VARCHAR(5), "WEEKORDER" DECIMAL(6,0), "FISCAL_YEAR" DECIMAL(6,0), "ORDERRANK" DECIMAL(5,0), "CNFOPK" INTEGER, "DAYS_DATE" DATE, "TXNS" DECIMAL(8,0), "TOTALSPEND" DECIMAL(10,2), "DMA_NBR" DECIMAL(8,0));



/* <sc-table> PROMOPRIMARY_PRICE </sc-table> */

CREATE TABLE IF NOT EXISTS "PROMOPRIMARY_PRICE" ("FISCAL_YEAR" INTEGER, "FISCAL_WEEK_NUMBER" INTEGER, "PROMO_DES1" VARCHAR(60), "PROMO_ABBR" VARCHAR(6), "PROMO_WEEK" INTEGER, "BUNDLE_PRICE" INTEGER, "FULL_PRICE" INTEGER, "VALUE_PRICE" INTEGER);



/* <sc-table> CUSTOMER_FREQUENCY_TEMP_A </sc-table> */

CREATE TABLE IF NOT EXISTS "CUSTOMER_FREQUENCY_TEMP_A" ("CNFOPK" DECIMAL(30,10), "FIRSTVISIT" TIMESTAMP, "LASTVISIT" TIMESTAMP, "TXNS" INTEGER, "TOTALSPEND" DECIMAL(30,10), "AVGCHECK" DECIMAL(30,10));



/* <sc-table> FORECAST_BWW_POLARIS </sc-table> */

CREATE TABLE IF NOT EXISTS "FORECAST_BWW_POLARIS" ("DAYS_DATE" DATE, "REST_NUMBER" VARCHAR(10), "ETS_PRED" DOUBLE, "STL_PRED" DOUBLE, "SNAIVE_PRED" DOUBLE, "SALES_AFB" DOUBLE, "FCAST_KEY" DATE);



/* <sc-table> BRS_DIM_QUESTION </sc-table> */

CREATE TABLE IF NOT EXISTS "BRS_DIM_QUESTION" ("QUESTION" VARCHAR(100), "TYPE" VARCHAR(50), "CODE" VARCHAR(50), "DESCRIPTION" VARCHAR(8000));
