ALTER SESSION SET QUOTED_IDENTIFIERS_IGNORE_CASE = FALSE;

/* <sc-table> CUSTOMERPROMOTIONTABLE </sc-table> */

CREATE TABLE IF NOT EXISTS "CUSTOMERPROMOTIONTABLE" ("CNFOPK" INTEGER, "FISCAL_YEAR" DECIMAL(6,0), "WEEK" DECIMAL(4,0), "WEEKORDER" DECIMAL(6,0), "PERIOD" VARCHAR(5), "VISITTYPE" VARCHAR(8), "TOTALSPEND" DECIMAL(10,2), "TXNS" DECIMAL(8,0), "MEDIATYPE" VARCHAR(15), "PROMOTEDPRODUCT" VARCHAR(100), "PROMOTION" VARCHAR(100), "COUPONTXN" TINYINT, "DMA_NBR" DECIMAL(8,0), "TXNID" VARCHAR(75), "DAYS_DATE" DATE, "HHTXN" TINYINT, "HOUROFDAY" TINYINT, "ORDERRANK" DECIMAL(5,0), "STORE_NBR" SMALLINT, "VISITS_TTM" DECIMAL(10,0));



/* <sc-table> BWWW_COMP_SALES_REV </sc-table> */

CREATE TABLE IF NOT EXISTS "BWWW_COMP_SALES_REV" ("OWNERSHIP" VARCHAR(75), "REST_NUMBER" DECIMAL(10,0), "FISCAL_WEEK" DECIMAL(6,0), "DAYOFWEEK" VARCHAR(75), "WEEKTYPE" VARCHAR(75), "DAYPART" VARCHAR(75), "REVENUE_CENTER" VARCHAR(75), "SALES_TY" DECIMAL(8,2), "TXNS_TY" DECIMAL(8,0), "SALES_LY" DECIMAL(8,2), "TXNS_LY" DECIMAL(8,0));



/* <sc-table> ARBYS_LC_REPORT_store_churn_3 </sc-table> */

CREATE TABLE IF NOT EXISTS "ARBYS_LC_REPORT_store_churn_3" ("PERIOD" VARCHAR(10), "TRACKED_DUM" VARCHAR(11), "PAYMENT_DESC_2" VARCHAR(16), "LC" VARCHAR(11), "STORE" INTEGER, "SALES_TOT" DECIMAL(36,15), "TXNID_TOT" INTEGER, "CUSTOMERS" INTEGER, "REST_DMA_DESC" VARCHAR(30), "REST_ADDRCITY" VARCHAR(20), "REST_ADDRCOUNTY" VARCHAR(16), "REST_ADDRSTATE" VARCHAR(2), "REST_LATITUDE" DECIMAL(36,15), "REST_LONGITUDE" DECIMAL(36,15), "REST_TYPE" VARCHAR(3), "ARG_DISTRICT_NAME" VARCHAR(24), "ARG_SUBREGION_NAME" VARCHAR(9));



/* <sc-table> YODLEE_MARKET_DATA </sc-table> */

CREATE TABLE IF NOT EXISTS "YODLEE_MARKET_DATA" ("MERCHANT_NAME" VARCHAR(50), "year" DOUBLE, "WEEK" DOUBLE, "OPTIMIZED_TRANSACTION_DATE" DATE, "TOTAL_BRAND_SALES" DOUBLE, "TOTAL_BRAND_TRANS" DOUBLE, "TOTAL_COMPSET_SALES" DOUBLE, "TOTAL_COMPSET_TRANS" DOUBLE);



/* <sc-table> BWW_DAILY_STORE_SALES </sc-table> */

CREATE TABLE IF NOT EXISTS "BWW_DAILY_STORE_SALES" ("REST_ID" VARCHAR(8), "DAYS_DATE" DATE, "NETSALES" DOUBLE);



/* <sc-table> MDM_PRODUCT_HIERARCHY </sc-table> */

CREATE TABLE IF NOT EXISTS "MDM_PRODUCT_HIERARCHY" ("HIERARCHY_ID" INTEGER, "HIERARCHY_NAME" VARCHAR(250), "HIERARCHY_DESCRIPTION" VARCHAR(250), "PRODUCT_HIERARCHY_NODE_TYPE" VARCHAR(250), "PARENT_PRODUCT_HIERARCHY_NODE" INTEGER);



/* <sc-table> SPORT_NCAAFB </sc-table> */

CREATE TABLE IF NOT EXISTS "SPORT_NCAAFB" ("SEAS_WEEK" INTEGER, "YEAR" INTEGER, "SCHEDULE_UTC_TIME" TIMESTAMP, "SCHEDULE_NAME" VARCHAR(100), "SPORT" VARCHAR(100), "HOME_NAME" VARCHAR(400), "AWAY_NAME" VARCHAR(400), "VENUE_NAME" VARCHAR(100), "VENUE_CITY" VARCHAR(100), "VENUE_STATE" VARCHAR(4), "VENUE_ZIP" VARCHAR(20));



/* <sc-table> SPORT_NFL </sc-table> */

CREATE TABLE IF NOT EXISTS "SPORT_NFL" ("SEAS_WEEK" INTEGER, "YEAR" INTEGER, "SCHEDULE_UTC_TIME" TIMESTAMP, "SCHEDULE_NAME" VARCHAR(100), "SPORT" VARCHAR(100), "HOME_NAME" VARCHAR(100), "AWAY_NAME" VARCHAR(100), "VENUE_NAME" VARCHAR(100), "VENUE_CITY" VARCHAR(100), "VENUE_STATE" VARCHAR(20));



/* <sc-table> BWW_LOYALTY_TRANSACTION </sc-table> */

CREATE TABLE IF NOT EXISTS "BWW_LOYALTY_TRANSACTION" ("CHECKSUMMARYKEY" BIGINT, "PROFILE_ID" VARCHAR(50), "MEMBER_CARDNUMBER" VARCHAR(80), "TRANSACTION_NUMBER" VARCHAR(80), "DOLLAR_NET_VALUE" DECIMAL(13,2), "ELIGIBLE_REVENUE" DECIMAL(13,2), "RESTAURANTNUMBER" DECIMAL(8,0), "DATE_OF_BUSINESS" DATE, "METHOD_OF_ATTACHMENT" VARCHAR(80), "TRANS_STATUS" VARCHAR(80), "MEMBER_PHONENUMBER" VARCHAR(80), "CHECKNUM" VARCHAR(80), "TRANSACTION_ID" VARCHAR(50));



/* <sc-table> ARBYS_LC_REPORT_store_churn_2 </sc-table> */

CREATE TABLE IF NOT EXISTS "ARBYS_LC_REPORT_store_churn_2" ("PERIOD" VARCHAR(10), "TRACKED_DUM" VARCHAR(11), "PAYMENT_DESC_2" VARCHAR(16), "LC" VARCHAR(11), "STORE" INTEGER, "SALES_TOT" DECIMAL(36,15), "TXNID_TOT" INTEGER, "CUSTOMERS" INTEGER, "REST_DMA_DESC" VARCHAR(30), "REST_ADDRCITY" VARCHAR(20), "REST_ADDRCOUNTY" VARCHAR(16), "REST_ADDRSTATE" VARCHAR(2), "REST_LATITUDE" DECIMAL(36,15), "REST_LONGITUDE" DECIMAL(36,15), "REST_TYPE" VARCHAR(3), "ARG_DISTRICT_NAME" VARCHAR(24), "ARG_SUBREGION_NAME" VARCHAR(9));



/* <sc-table> FORECAST_BWW_POLARIS2 </sc-table> */

CREATE TABLE IF NOT EXISTS "FORECAST_BWW_POLARIS2" ("REST_NUMBER" VARCHAR(10), "DAYS_DATE" DATE, "SEASON" DOUBLE, "TREND" DOUBLE, "REMAINDER" DOUBLE, "ETS_PRED" DOUBLE, "STL_PRED" DOUBLE, "SNAIVE_PRED" DOUBLE, "SALES_AFB" DOUBLE, "FCAST_KEY" DATE);



/* <sc-table> BWW_KANTAR_COMP_MEDIA_SPEND_HISTORICAL </sc-table> */

CREATE TABLE IF NOT EXISTS "BWW_KANTAR_COMP_MEDIA_SPEND_HISTORICAL" ("ADSCOPE_ID" DOUBLE, "ADVERTISER" VARCHAR(250), "BRAND" VARCHAR(250), "CATEGORY" VARCHAR(250), "DOLS" DOUBLE, "DOLS_THOUSANDS" DOUBLE, "FIRST_SEEN" DATE, "LENGTH_SIZE" VARCHAR(250), "MARKET" VARCHAR(250), "MEDIA" VARCHAR(250), "MICROCATEGORY" VARCHAR(250), "PARENT" VARCHAR(250), "PRODUCT" VARCHAR(250), "SUBCATEGORY" VARCHAR(250), "TIME_PERIOD" DATE, "TITLE" VARCHAR(250), "UNITS" DOUBLE, "FISCAL_YEAR" DOUBLE, "QUARTER" DOUBLE, "MEDIA_TYPE" VARCHAR(250));



/* <sc-table> KANTAR_MOBILE_WEB </sc-table> */

CREATE TABLE IF NOT EXISTS "KANTAR_MOBILE_WEB" ("SUBCATEGORY" VARCHAR(100), "MICROCATEGORY" VARCHAR(100), "ADVERTISER" VARCHAR(100), "BRAND" VARCHAR(100), "PRODUCT" VARCHAR(1000), "TITLE" VARCHAR(1000), "ADSCOPE_ID" VARCHAR(100), "AD_SIZE" VARCHAR(100), "MEDIA" VARCHAR(100), "MARKET" VARCHAR(100), "DATE_AIRED" VARCHAR(100), "DOLS" DECIMAL(10,2), "DIGITAL_IMPRESSIONS" DECIMAL(10,2));



/* <sc-table> COMPLEXITY_COMBO </sc-table> */

CREATE TABLE IF NOT EXISTS "COMPLEXITY_COMBO" ("FISCAL_YEAR" INTEGER, "ARG_WEEK" INTEGER, "STORE_NBR" INTEGER, "MENU" VARCHAR(50), "MENUGROUP" VARCHAR(50), "TXNS" INTEGER, "TOTALUNITS" DECIMAL(10,2), "COMPLEXITY" INTEGER, "WEIGHTED_COMPLEXITY_TXNS" DECIMAL(10,2), "OBS" DECIMAL(10,2), "ITEM_NAME" VARCHAR(100), "X1" INTEGER, "X2" INTEGER, "X3" INTEGER, "X4" INTEGER, "X5" INTEGER, "X6" INTEGER, "X7" INTEGER, "X8" INTEGER, "X9" INTEGER, "X10" INTEGER, "X11" INTEGER, "X12" INTEGER, "X13" INTEGER, "X14" INTEGER, "X15" INTEGER, "X16" INTEGER, "X17" INTEGER, "X18" INTEGER, "X19" INTEGER, "X20" INTEGER, "X21" INTEGER, "X22" INTEGER, "X23" INTEGER, "X24" INTEGER, "X25" INTEGER, "X26" INTEGER, "X27" INTEGER, "X28" INTEGER, "X29" INTEGER, "X30" INTEGER, "X31" INTEGER, "TOTALSURVEYS" INTEGER, "ACCURATE" INTEGER, "ACCURACYPERCENT" DECIMAL(10,2), "ORDERS" DECIMAL(10,2), "TOTALTIME" INTEGER, "TRANS_TOTAL" DECIMAL(10,2));



/* <sc-table> MKT_PROMO_TABLE </sc-table> */

CREATE TABLE IF NOT EXISTS "MKT_PROMO_TABLE" ("ITEM_PRODUCT_DESC" VARCHAR(250), "PRODUCT_GROUP" VARCHAR(250), "PROMOTION" VARCHAR(250), "FISCAL_YEAR" DOUBLE, "START_WEEK" DOUBLE, "END_WEEK" DOUBLE);



/* <sc-table> COMPLEXITY_COMPONENT </sc-table> */

CREATE TABLE IF NOT EXISTS "COMPLEXITY_COMPONENT" ("COMPONENT_ID" DECIMAL(10,0), "PRODUCT" VARCHAR(75), "Q1" TINYINT, "Q2" TINYINT, "Q3" TINYINT, "Q4" TINYINT, "Q5" TINYINT, "Q6" TINYINT, "Q7" TINYINT, "Q8" TINYINT, "Q9" TINYINT, "Q10" TINYINT, "Q11" TINYINT, "Q12" TINYINT, "Q13" TINYINT, "Q14" TINYINT, "Q15" TINYINT, "Q16" TINYINT, "Q17" TINYINT, "Q18" TINYINT, "Q19" TINYINT, "Q20" TINYINT, "Q21" TINYINT, "Q22" TINYINT, "Q23" TINYINT, "Q24" TINYINT, "Q25" TINYINT, "Q26" TINYINT, "Q27" TINYINT, "Q28" TINYINT, "Q29" TINYINT, "Q30" TINYINT, "Q31" TINYINT, "TOTAL" TINYINT);



/* <sc-table> DIM_UTC_OFFSET </sc-table> */

CREATE TABLE IF NOT EXISTS "DIM_UTC_OFFSET" ("STATE_NAME" VARCHAR(32), "POSTALCODE" VARCHAR(8), "TIME_OFFSET_HR" VARCHAR(32), "TIME_OFFSET_INT" SMALLINT, "TIME_OFFSET_CHAR" VARCHAR(8), "DST" SMALLINT);



/* <sc-table> PROMOTIONCALENDAR </sc-table> */

CREATE TABLE IF NOT EXISTS "PROMOTIONCALENDAR" ("ADI" DECIMAL(8,0), "PROMOSTARTDATE" DECIMAL(8,0), "PROMOENDDATE" DECIMAL(8,0), "PROMOTION" VARCHAR(75), "PROMO_ID" DECIMAL(8,0), "ONAIR" VARCHAR(75), "FISCAL_YEAR" DECIMAL(8,0), "RECORDS" DECIMAL(8,0), "COMPONENT_ID" DECIMAL(14,0));



/* <sc-table> FORECAST_ARG_PROPHET_FY </sc-table> */

CREATE TABLE IF NOT EXISTS "FORECAST_ARG_PROPHET_FY" ("REST_NUMBER" VARCHAR(10), "DAYS_DATE" DATE, "TREND" DOUBLE, "SEASONAL" DOUBLE, "SEASONAL_LOWER" DOUBLE, "SEASONAL_UPPER" DOUBLE, "SEASONALITIES" DOUBLE, "SEASONALITIES_LOWER" DOUBLE, "SEASONALITIES_UPPER" DOUBLE, "WEEKLY" DOUBLE, "WEEKLY_LOWER" DOUBLE, "WEEKLY_UPPER" DOUBLE, "YHAT_LOWER" DOUBLE, "YHAT_UPPER" DOUBLE, "TREND_LOWER" DOUBLE, "TREND_UPPER" DOUBLE, "YHAT" DOUBLE, "FCAST_KEY" VARCHAR(10));



/* <sc-table> STORELIST </sc-table> */

CREATE TABLE IF NOT EXISTS "STORELIST" ("STORE_NBR" DOUBLE, "STATUS" VARCHAR(255), "ADDR1" VARCHAR(255), "ADDR2" VARCHAR(255), "CITY_NAME" VARCHAR(255), "STATE_ABBR" VARCHAR(255), "ZIP" DOUBLE, "DMA_NAME" VARCHAR(255), "DMA_NBR" DOUBLE, "FRANCHISEE_NAME" VARCHAR(255), "ENTITY_NAME" VARCHAR(255), "DATE_OPENED" DOUBLE, "NAME_FBM" VARCHAR(255), "COUNTY_NAME" VARCHAR(255), "BLDG_TYPE_DESC" VARCHAR(255), "FACILITY_DESC" VARCHAR(255), "DRIVE_THRU" VARCHAR(255), "NO_SEATS" DOUBLE, "FRANCHISEE_NBR" DOUBLE, "FRANID" DOUBLE, "BRAND" VARCHAR(255), "REMODEL_DATE" VARCHAR(255), "STORE" DOUBLE, "AREA_NBR" DOUBLE, "AREA_NAME" VARCHAR(255), "DISTRICT_NBR" DOUBLE, "DISTRICT_NAME" VARCHAR(255), "REGION_NBR" DOUBLE, "REGION_NAME" VARCHAR(255), "DMA_NBR_MIRUS" DOUBLE, "FULL_DMA_NAME_MIRUS" VARCHAR(255), "DMA_NAME_SHORT_MIRUS" VARCHAR(255));



/* <sc-table> BWW_KANTAR_COMP_MEDIA_SPEND </sc-table> */

CREATE TABLE IF NOT EXISTS "BWW_KANTAR_COMP_MEDIA_SPEND" ("TIME_PERIOD" DATE, "BRAND" VARCHAR(250), "PRODUCT" VARCHAR(250), "TITLE" VARCHAR(250), "MEDIA" VARCHAR(250), "DOLS_THOUSANDS" DOUBLE, "ADSCOPE_ID" VARCHAR(256), "QUARTER" VARCHAR(250), "FISCAL_YEAR" INTEGER, "CATEGORY" VARCHAR(250), "SUBCATEGORY" VARCHAR(250), "MICROCATEGORY" VARCHAR(250), "PARENT" VARCHAR(250), "ADVERTISER" VARCHAR(250), "CREATIVE_ATTRIBUTES" VARCHAR(500), "LENGTH_SIZE" VARCHAR(250), "MEDIA_TYPE" VARCHAR(250), "MARKET" VARCHAR(250), "FIRST_SEEN" DATE, "UNITS" INTEGER, "DOLS" DOUBLE);



/* <sc-table> SUSPECTIDS </sc-table> */

CREATE TABLE IF NOT EXISTS "SUSPECTIDS" ("CNFOPK" INTEGER, "STORE_CT" DECIMAL(18,2), "STATE_CT" DECIMAL(18,2), "TXN_CT" DECIMAL(18,2), "DATE_RANGE" DECIMAL(18,2), "TXNS_STORE" DECIMAL(18,2), "STORE_DAYS" DECIMAL(18,2));



/* <sc-table> NAMES_AGE_GENDER </sc-table> */

CREATE TABLE IF NOT EXISTS "NAMES_AGE_GENDER" ("FIRSTNAME" VARCHAR(75), "COUNT" DOUBLE, "TOTALYEARS" DOUBLE, "TOTALNAMES" DOUBLE, "M_ALIVE" DOUBLE, "F_ALIVE" DOUBLE, "AGE" DOUBLE, "PERCENT_MALE" DOUBLE, "PERCENT_FEMALE" DOUBLE);



/* <sc-table> MKT_COMP_PRICING </sc-table> */

CREATE TABLE IF NOT EXISTS "MKT_COMP_PRICING" ("BRAND" VARCHAR(500), "NAME" VARCHAR(5000), "PRICE" DOUBLE, "SIZE" VARCHAR(500));



/* <sc-table> CC_TEST2 </sc-table> */

CREATE TABLE IF NOT EXISTS "CC_TEST2" ("DATEOFBUSINESS" VARCHAR(75), "STORE" DECIMAL(10,0), "CHECKNUMBER" DECIMAL(10,0), "CARDTYPE" VARCHAR(75), "IDENT" VARCHAR(75), "NAME" VARCHAR(75), "AMOUNT" DECIMAL(10,2), "TRACK" VARCHAR(75), "HOUROFDAY" DECIMAL(4,0), "MINUTEOFHOUR" DECIMAL(4,0));

