ALTER SESSION SET QUOTED_IDENTIFIERS_IGNORE_CASE = FALSE;

/* <sc-table> CUSTOMER_TLD_TEMP </sc-table> */

CREATE TABLE IF NOT EXISTS "CUSTOMER_TLD_TEMP" ("CNFOPK" INTEGER, "UNIT_NUM" INTEGER, "DATETIME" TIMESTAMP, "CHECK1" INTEGER, "ITEMNUMBER" INTEGER, "ITEM_NAME" VARCHAR(255), "SALES" DECIMAL(18,2), "QUANTITY" INTEGER, "EMPLOYEE" INTEGER, "SUSPECT_DATA" INTEGER, "TXNID" VARCHAR(75), "REVENUE_CENTER" VARCHAR(27));

/* <sc-table> ITEM_MAPPING_MASTER_BKUP </sc-table> */

CREATE TABLE IF NOT EXISTS "ITEM_MAPPING_MASTER_BKUP" ("ITEM_NUMBER" BIGINT, "ITEM_NAME" VARCHAR(100), "AFA_PROD_DESC" VARCHAR(100), "AS_MENU_GROUPS" VARCHAR(50), "BCG_NAME" VARCHAR(100), "BCG_COUPON_NAME" VARCHAR(100), "OFFER_ITEM" VARCHAR(100), "COUPON_TYPE" VARCHAR(100), "MAIN_PROTEIN" VARCHAR(100), "MENUGROUP" VARCHAR(100), "MENU" VARCHAR(100), "TYPE" VARCHAR(100), "COMPONENT_ID" INTEGER, "AFA_PRODUCT_ID" INTEGER);

/* <sc-table> STORELIST </sc-table> */

CREATE TABLE IF NOT EXISTS "STORELIST" ("STORE_NBR" DOUBLE, "STATUS" VARCHAR(255), "ADDR1" VARCHAR(255), "ADDR2" VARCHAR(255), "CITY_NAME" VARCHAR(255), "STATE_ABBR" VARCHAR(255), "ZIP" DOUBLE, "DMA_NAME" VARCHAR(255), "DMA_NBR" DOUBLE, "FRANCHISEE_NAME" VARCHAR(255), "ENTITY_NAME" VARCHAR(255), "DATE_OPENED" DOUBLE, "NAME_FBM" VARCHAR(255), "COUNTY_NAME" VARCHAR(255), "BLDG_TYPE_DESC" VARCHAR(255), "FACILITY_DESC" VARCHAR(255), "DRIVE_THRU" VARCHAR(255), "NO_SEATS" DOUBLE, "FRANCHISEE_NBR" DOUBLE, "FRANID" DOUBLE, "BRAND" VARCHAR(255), "REMODEL_DATE" VARCHAR(255), "STORE" DOUBLE, "AREA_NBR" DOUBLE, "AREA_NAME" VARCHAR(255), "DISTRICT_NBR" DOUBLE, "DISTRICT_NAME" VARCHAR(255), "REGION_NBR" DOUBLE, "REGION_NAME" VARCHAR(255), "DMA_NBR_MIRUS" DOUBLE, "FULL_DMA_NAME_MIRUS" VARCHAR(255), "DMA_NAME_SHORT_MIRUS" VARCHAR(255));

