ALTER SESSION SET QUOTED_IDENTIFIERS_IGNORE_CASE = FALSE;

/* <sc-table> CNFOPK_MATCH </sc-table> */

CREATE TABLE IF NOT EXISTS "CNFOPK_MATCH_DEV" ("ORDER_ID" VARCHAR(60), "CNFOPK" INTEGER, "ORDER_DATE" DATE);

/* <sc-table> CUSTOMER_TLD_TEMP </sc-table> */

CREATE TABLE IF NOT EXISTS "CUSTOMER_TLD_TEMP_DEV" ("CNFOPK" INTEGER, "UNIT_NUM" INTEGER, "DATETIME" TIMESTAMP, "CHECK1" INTEGER, "ITEMNUMBER" INTEGER, "ITEM_NAME" VARCHAR(255), "SALES" DECIMAL(18,2), "QUANTITY" INTEGER, "EMPLOYEE" INTEGER, "SUSPECT_DATA" INTEGER, "TXNID" VARCHAR(75), "REVENUE_CENTER" VARCHAR(27));

/* <sc-table> CUSTOMER_TLD_TEMP_DUPE </sc-table> */

CREATE TABLE IF NOT EXISTS "CUSTOMER_TLD_TEMP_DUPE_DEV" ("CNFOPK" DECIMAL(20,0), "TXNID" VARCHAR(75), "UNIT_NUM" DECIMAL(8,0));


/* <sc-table> CUSTOMERTRANSCC </sc-table> */

CREATE TABLE IF NOT EXISTS "CUSTOMERTRANSCC_DEV" ("TXNID" VARCHAR(60), "CNFOPK" INTEGER, "STORE" INTEGER, "AUTHORIZATION_CODE" VARCHAR(8), "TRANSACTION_DATE" TIMESTAMP, "TRANSACTION_AMOUNT" DECIMAL(18,2), "MAPPING_DATE" TIMESTAMP);

/* <sc-table> ORDER_COMP </sc-table> */

CREATE TABLE IF NOT EXISTS "ORDER_COMP_DEV" ("ORDER_ID" VARCHAR(60), "COMP" DECIMAL(2,0), "ORDER_DATE" DATE);


/* <sc-table> SUSPECTIDS </sc-table> */

CREATE TABLE IF NOT EXISTS "SUSPECTIDS_DEV" ("CNFOPK" INTEGER, "STORE_CT" DECIMAL(18,2), "STATE_CT" DECIMAL(18,2), "TXN_CT" DECIMAL(18,2), "DATE_RANGE" DECIMAL(18,2), "TXNS_STORE" DECIMAL(18,2), "STORE_DAYS" DECIMAL(18,2));



