USE WAREHOUSE {{params.warehouse}};

TRUNCATE TABLE IDS_{{params.target_env}}."INT_REF"."REV_CTR_ITEM";

INSERT INTO IDS_{{params.target_env}}."INT_REF"."REV_CTR_ITEM"
(BRAND_ID              ,   
REV_CTR_ID             ,   
SOURCE_ITEM_ID         ,    
SOURCE_SYSTEM_NAME     ,  
SOURCE_ITEM_DESC       ,  
LOAD_ID                ,
LOAD_DTTM              ,
UPDATE_ID              ,
UPDATE_DTTM     )     
SELECT BRAND_ID ,REV_CTR_ID ,SOURCE_ITEM_ID ,SOURCE_SYSTEM_NAME ,
SOURCE_ITEM_DESC ,LOAD_ID ,LOAD_DTTM ,UPDATE_ID ,UPDATE_DTTM 
FROM 
(
SELECT DISTINCT
'arbys' AS BRAND_ID,
REV_CEN.REV_CTR_ID AS REV_CTR_ID,
ITEM.ITEM_ID AS SOURCE_ITEM_ID,
'parbrinks' AS SOURCE_SYSTEM_NAME,
ITEM.ITEM_NAME AS SOURCE_ITEM_DESC,
ROW_NUMBER() OVER (PARTITION BY ITEM.ITEM_ID ORDER BY COUNT(DISTINCT SUBSTRING(ITEM.FILENAME,88,5)) DESC) AS RANK,
COUNT(DISTINCT SUBSTRING(ITEM.FILENAME,88,5)) AS STORE_COUNT,
TO_NUMBER(TO_CHAR(CURRENT_DATE, 'YYYYMMDD'))  AS LOAD_ID,
TO_TIMESTAMP_NTZ(CURRENT_TIMESTAMP)           AS LOAD_DTTM,
TO_NUMBER(TO_CHAR(CURRENT_DATE, 'YYYYMMDD'))  AS UPDATE_ID,
TO_TIMESTAMP_NTZ(CURRENT_TIMESTAMP)           AS UPDATE_DTTM
FROM "RDS_{{params.source_env}}"."ARB"."ITEM_REVENUE_CATEGORY" ITEM
JOIN "IDS_{{params.source_env}}"."INT_REF"."REV_CTR" REV_CEN
ON ITEM.REVENUE_CENTER_ID= REV_CEN.SOURCE_REV_CTR_ID
GROUP BY ITEM.ITEM_ID,REV_CEN.REV_CTR_ID ,ITEM.ITEM_NAME

)
WHERE RANK = 1;

