USE WAREHOUSE {{params.warehouse}};

TRUNCATE TABLE IDS_{{params.target_env}}."INT_REF"."REV_CTR";

INSERT INTO IDS_{{params.target_env}}."INT_REF"."REV_CTR"
(BRAND_ID               ,          
SOURCE_REV_CTR_ID       ,
REV_CTR_DESC            ,
SOURCE_SYSTEM_NAME      ,
LOAD_ID                 ,
LOAD_DTTM               ,
UPDATE_ID               ,
UPDATE_DTTM  )
SELECT DISTINCT
'arbys'                 ,
REVENUE_CENTER_ID       ,
REVENUE_CENTER_DESC     ,
'parbrinks'             ,
TO_NUMBER(TO_CHAR(CURRENT_DATE, 'YYYYMMDD'))  AS LOAD_ID   ,
TO_TIMESTAMP_NTZ(CURRENT_TIMESTAMP)           AS LOAD_DTTM ,
TO_NUMBER(TO_CHAR(CURRENT_DATE, 'YYYYMMDD'))  AS UPDATE_ID ,
TO_TIMESTAMP_NTZ(CURRENT_TIMESTAMP)           AS UPDATE_DTTM
FROM "RDS_{{params.source_env}}"."ARB"."REVENUE_CENTER"
QUALIFY ROW_NUMBER() OVER (PARTITION BY REVENUE_CENTER_ID,REVENUE_CENTER_DESC ORDER BY FILEDATE DESC, FOLDERDATE DESC,LOADDATETIME DESC ) = 1;

