spark.src.kafka.topic shp2shr-nbx-hbtb-sailor-cal-feedback-stream-history
spark.src.seconds 60
spark.streaming.kafka.maxRatePerPartition 100
spark.src.consumer spark-consumer-100
spark.kafkabrokers 10.101.220.213:9092,10.101.220.214:9092,10.101.220.216:9092
spark.ssl.enabled false     
spark.debug.flag false
spark.target.table.schema SAILORID varchar,ACTIVITYID varchar,NBXUNIQUEKEY varchar,REQUESTSOURCE varchar,SAILORSELECTION varchar,FEEDBACKLOOPCALLFLAG varchar,timestamp timestamp,rowkey varchar
spark.target.table HBTB_NBX_SAILOR_CAL_FEEDBACK_STREAM_HISTORY
spark.target.table.format org.apache.phoenix.spark
spark.target.table.mode overwrite
spark.target.zkurl 10.15.2.206:2181/hbase-unsecure

spark.target.VOYAGEOPS_table HBTB_NBX_SHIPTOSHORE_SYNC_VOYAGEOPS
spark.personcreated.offsettable HBTB_NBX_KAFKA_STREAMING_OFFSET 
spark.personcreated.format org.apache.phoenix.spark
spark.personcreated.mode overwrite
spark.personcreated.readhbasezkurl 10.15.2.206:2181/hbase-unsecure

spark.src.voyageid SC2002269NCR
spark.src.srcConfig shp2shr-nbx-hbtb-sailor-cal-feedback-stream-history-SC2002269NCR
spark.src.tgtConfig HBTB_NBX_SAILOR_CAL_FEEDBACK_STREAM_HISTORY-SC2002269NCR
spark.job.type sync

spark.passvalue SetS@!l2o2o
spark.truststore /etc/script_keystore/dxp.kafka.client.truststore.AWS.shore.jks
spark.keystore /etc/script_keystore/dxp.kafka.client.keystore.AWS.shore.jks
spark.kafka.zookeeper 10.101.220.213:2181