
create TRANSIENT TABLE IF NOT EXISTS ARB_MENU_ITEM_PRICE (
	PRODUCTS VARIANT,
	SIZE_GROUPS VARIANT,
	ITEM_GROUPS VARIANT,
	PRODUCT_GROUPS VARIANT,
	CATEGORIES VARIANT,
	STORE_ID VARCHAR(16777216),
	SOURCE_SYSTEM_NAME VARCHAR(16777216),
	FILENAME VARCHAR(16777216),
	LOAD_ID NUMBER(38,0),
	LOAD_DTTM TIMESTAMP_NTZ(9)
);
create TABLE IF NOT EXISTS AYEFREMOV_CURRENT_EMAIL_STATUS_FROM_CRM_EMAIL_STATUS_CHANGE_ARBYS (
	BRAND_CUSTOMER_ID VARCHAR(16777216),
	EMAIL_OPT_OUT_STATUS_IND BOOLEAN,
	EMAIL_ADDRESS VARCHAR(16777216),
	SOURCE_SYSTEM_NAME VARCHAR(255),
	BRAND_ID VARCHAR(20),
	LOAD_ID NUMBER(38,0),
	LOAD_DTTM TIMESTAMP_NTZ(9),
	UPDATE_ID NUMBER(38,0),
	UPDATE_DTTM TIMESTAMP_NTZ(9)
);
create TABLE IF NOT EXISTS BM_CURRENT_EMAIL_STATUS_FROM_CRM_EMAIL_STATUS_CHANGE_ARBYS (
	LOWER_BRAND_CUSTOMER_ID VARCHAR(16777216),
	LOWER_STRIPPED_EMAIL_ADRESS VARCHAR(16777216),
	EMAIL_OPT_OUT_STATUS_IND BOOLEAN,
	SOURCE_SYSTEM_NAME VARCHAR(255),
	BRAND_ID VARCHAR(20),
	LOAD_ID NUMBER(38,0),
	LOAD_DTTM TIMESTAMP_NTZ(9),
	UPDATE_ID NUMBER(38,0),
	UPDATE_DTTM TIMESTAMP_NTZ(9)
);
create TRANSIENT TABLE IF NOT EXISTS CMX_AOR_INGESTION (
	VALUE VARIANT,
	FILENAME VARCHAR(16777216),
	LOAD_ID NUMBER(38,0),
	LOAD_DTTM TIMESTAMP_NTZ(9)
);
create TRANSIENT TABLE IF NOT EXISTS CMX_LIST_ENTITIES (
	VALUE VARIANT,
	FILENAME VARCHAR(16777216),
	LOAD_ID NUMBER(38,0),
	LOAD_DTTM TIMESTAMP_NTZ(9)
);
create TABLE IF NOT EXISTS CURRENT_EMAIL_STATUS_FROM_CRM_EMAIL_STATUS_CHANGE_ARBYS (
	LOWER_BRAND_CUSTOMER_ID VARCHAR(16777216),
	LOWER_STRIPPED_EMAIL_ADDRESS VARCHAR(16777216),
	EMAIL_OPT_OUT_STATUS_IND BOOLEAN,
	SOURCE_SYSTEM_NAME VARCHAR(255),
	BRAND_ID VARCHAR(20),
	LOAD_ID NUMBER(38,0),
	LOAD_DTTM TIMESTAMP_NTZ(9),
	UPDATE_ID NUMBER(38,0),
	UPDATE_DTTM TIMESTAMP_NTZ(9)
);
create TABLE IF NOT EXISTS CURRENT_EMAIL_STATUS_FROM_CRM_EMAIL_STATUS_CHANGE_ARBYS_TEST (
	LOWER_BRAND_CUSTOMER_ID VARCHAR(16777216),
	LOWER_STRIPPED_EMAIL_ADDRESS VARCHAR(16777216),
	EMAIL_OPT_OUT_STATUS_IND BOOLEAN,
	SOURCE_SYSTEM_NAME VARCHAR(255),
	BRAND_ID VARCHAR(20),
	LOAD_ID NUMBER(38,0),
	LOAD_DTTM TIMESTAMP_NTZ(9),
	UPDATE_ID NUMBER(38,0),
	UPDATE_DTTM TIMESTAMP_NTZ(9)
);
create TABLE IF NOT EXISTS DIGITAL_ORDERS_HISTORICAL_ORDERS (
	ID NUMBER(38,0) NOT NULL,
	BRAND_ID VARCHAR(16777216),
	CUSTOMER_ID VARCHAR(16777216),
	NAME VARCHAR(16777216),
	STATUS VARCHAR(16777216),
	EXPECTED_PICKUP_TIME TIMESTAMP_TZ(9),
	CREATED TIMESTAMP_NTZ(9) NOT NULL,
	LAST_MODIFIED TIMESTAMP_NTZ(9) NOT NULL,
	POS_ID VARCHAR(16777216),
	POS_DISPLAY_ID VARCHAR(16777216),
	POS_MESSAGE VARCHAR(16777216),
	POS_RECEIPT_MESSAGE VARCHAR(16777216),
	POS_SUBMIT_CODE NUMBER(38,0),
	PRICE NUMBER(7,2),
	TAX NUMBER(7,2),
	IDEMPOTENT_ID VARCHAR(16777216),
	SELLING_CHANNEL VARCHAR(16777216),
	RETRIES NUMBER(38,0),
	PICKUP_TIME_TYPE VARCHAR(16777216),
	DISCOUNT NUMBER(7,2),
	NOTES VARCHAR(16777216),
	CERTIFICATE_DISCOUNT NUMBER(7,2),
	TIP_AMOUNT NUMBER(7,2),
	PAYMENT_STATUS VARCHAR(16777216),
	DELIVERY_FEE NUMBER(7,2),
	DRIVER_TIP NUMBER(7,2),
	CONTAINS_ALCOHOL BOOLEAN,
	BALANCE NUMBER(7,2),
	ERRORS VARCHAR(16777216),
	STORE_TIP NUMBER(7,2),
	LOYALTY_STATUS VARCHAR(16777216),
	ORDER_ID VARCHAR(16777216),
	INSP_CHANNEL VARCHAR(16777216),
	UDP_CORRELATION_ID VARCHAR(16777216)
);
create TABLE IF NOT EXISTS DIGITAL_ORDER_HISTORICAL_CUSTOMER_CONSENT (
	ID NUMBER(38,0) NOT NULL,
	ORDER_ID NUMBER(38,0) NOT NULL,
	PHONE_NUMBER VARCHAR(16777216) NOT NULL,
	CONSENT_DATE_TIME_UTC TIMESTAMP_NTZ(9) NOT NULL,
	CONSENT_GIVEN VARCHAR(16777216) NOT NULL,
	LOCATION_ID VARCHAR(16777216) NOT NULL
);
create TABLE IF NOT EXISTS DIGITAL_ORDER_HISTORICAL_CUSTOMER_REF (
	CUSTOMER_UUID VARCHAR(16777216) NOT NULL,
	BRAND VARCHAR(16777216) NOT NULL,
	EMAIL VARCHAR(16777216) NOT NULL,
	FIRST_NAME VARCHAR(16777216) NOT NULL,
	LAST_NAME VARCHAR(16777216) NOT NULL,
	DOB VARCHAR(16777216),
	FRAUD_STATUS NUMBER(38,0) NOT NULL,
	ACCOUNT_STATUS NUMBER(38,0) NOT NULL,
	PROFILE_COMPLETED BOOLEAN NOT NULL,
	EMAIL_CONFIRMED BOOLEAN NOT NULL,
	CREATED_TS TIMESTAMP_TZ(9) NOT NULL,
	UPDATED_TS TIMESTAMP_TZ(9) NOT NULL,
	DEFAULT_TNC_ACCEPTED BOOLEAN NOT NULL,
	MEMBER_SINCE TIMESTAMP_TZ(9),
	MIGRATED BOOLEAN NOT NULL,
	MIGRATION_SOURCE NUMBER(38,0),
	GENDER NUMBER(38,0),
	ID NUMBER(38,0) NOT NULL
);
create TABLE IF NOT EXISTS DIGITAL_ORDER_HISTORICAL_FULFILLMENT_DETAILS (
	ORDER_ID NUMBER(38,0) NOT NULL,
	FULFILLMENT_ID VARCHAR(16777216),
	FULFILLMENT_TIME TIMESTAMP_NTZ(9),
	FULFILLMENT_TYPE VARCHAR(16777216),
	CONTACT_PERSON VARCHAR(16777216),
	CONTACT_EMAIL VARCHAR(16777216),
	CONTACT_PHONE VARCHAR(16777216),
	LOCATION_ID VARCHAR(16777216),
	LOCATION_NAME VARCHAR(16777216),
	LOCATION_ADDRESS1 VARCHAR(16777216),
	DELIVERY_COUNTRY_CODE VARCHAR(16777216),
	DELIVERY_STATE_CODE VARCHAR(16777216),
	DELIVERY_CITY VARCHAR(16777216),
	DELIVERY_ADDRESS1 VARCHAR(16777216),
	DELIVERY_ADDRESS2 VARCHAR(16777216),
	DELIVERY_POSTAL_CODE VARCHAR(16777216),
	VEHICLE_DESCRIPTION VARCHAR(16777216),
	CONTACT_PERSON_FIRSTNAME VARCHAR(16777216),
	CONTACT_PERSON_LASTNAME VARCHAR(16777216),
	EMPLOYEE_NAME VARCHAR(16777216),
	TABLE_NUMBER VARCHAR(16777216),
	TABLE_GUESTS NUMBER(38,0),
	ORDER_PREPARATION_TIME NUMBER(38,0)
);
create TABLE IF NOT EXISTS DIGITAL_ORDER_HISTORICAL_FULFILLMENT_INSTRUCTIONS (
	FULFILLMENT_ORDER_ID NUMBER(38,0) NOT NULL,
	INSTRUCTION VARCHAR(16777216) NOT NULL
);
create TABLE IF NOT EXISTS DIGITAL_ORDER_HISTORICAL_ITEM_MODIFIERS (
	ID NUMBER(38,0) NOT NULL,
	POS_ID NUMBER(38,0),
	PRODUCT_ID VARCHAR(16777216),
	PRICE NUMBER(7,2) NOT NULL,
	MODIFIER_GROUP_ID NUMBER(38,0) NOT NULL,
	PARENT_ID NUMBER(38,0),
	DESCRIPTION VARCHAR(16777216),
	QUANTITY NUMBER(38,0) NOT NULL,
	ACTION_CODE NUMBER(38,0),
	DISPLAY_NAME VARCHAR(16777216),
	PRICE_TYPE VARCHAR(16777216),
	SIZE_GROUP_ID VARCHAR(16777216),
	SIZE_GROUP_NAME VARCHAR(16777216),
	LINE_ITEM_ID NUMBER(38,0)
);
create TABLE IF NOT EXISTS DIGITAL_ORDER_HISTORICAL_MESSAGE_METADATA (
	ID NUMBER(38,0) NOT NULL,
	CREATED TIMESTAMP_NTZ(9) NOT NULL,
	ORDER_ID NUMBER(38,0) NOT NULL,
	DESTINATION_NAME VARCHAR(16777216) NOT NULL,
	ENQUEUED_SEQUENCE_NUMBER NUMBER(38,0) NOT NULL
);
create TABLE IF NOT EXISTS DIGITAL_ORDER_HISTORICAL_MODIFIER_GROUPS (
	ID NUMBER(38,0) NOT NULL,
	POS_ID NUMBER(38,0),
	PRODUCT_ID VARCHAR(16777216),
	ORDER_ITEM_ID NUMBER(38,0),
	DESCRIPTION VARCHAR(16777216),
	MODIFIER_ID NUMBER(38,0)
);
create TABLE IF NOT EXISTS DIGITAL_ORDER_HISTORICAL_ORDERS (
	ID NUMBER(38,0) NOT NULL,
	BRAND_ID VARCHAR(16777216),
	CUSTOMER_ID VARCHAR(16777216),
	NAME VARCHAR(16777216),
	STATUS VARCHAR(16777216),
	EXPECTED_PICKUP_TIME TIMESTAMP_TZ(9),
	CREATED TIMESTAMP_NTZ(9) NOT NULL,
	LAST_MODIFIED TIMESTAMP_NTZ(9) NOT NULL,
	POS_ID VARCHAR(16777216),
	POS_DISPLAY_ID VARCHAR(16777216),
	POS_MESSAGE VARCHAR(16777216),
	POS_RECEIPT_MESSAGE VARCHAR(16777216),
	POS_SUBMIT_CODE NUMBER(38,0),
	PRICE NUMBER(7,2),
	TAX NUMBER(7,2),
	IDEMPOTENT_ID VARCHAR(16777216),
	SELLING_CHANNEL VARCHAR(16777216),
	RETRIES NUMBER(38,0),
	PICKUP_TIME_TYPE VARCHAR(16777216),
	DISCOUNT NUMBER(7,2),
	NOTES VARCHAR(16777216),
	CERTIFICATE_DISCOUNT NUMBER(7,2),
	TIP_AMOUNT NUMBER(7,2),
	PAYMENT_STATUS VARCHAR(16777216),
	DELIVERY_FEE NUMBER(7,2),
	DRIVER_TIP NUMBER(7,2),
	CONTAINS_ALCOHOL BOOLEAN,
	BALANCE NUMBER(7,2),
	ERRORS VARCHAR(16777216),
	STORE_TIP NUMBER(7,2),
	LOYALTY_STATUS VARCHAR(16777216),
	ORDER_ID VARCHAR(16777216),
	INSP_CHANNEL VARCHAR(16777216),
	UDP_CORRELATION_ID VARCHAR(16777216)
);
create TABLE IF NOT EXISTS DIGITAL_ORDER_HISTORICAL_ORDER_DISCOUNTS (
	ID NUMBER(38,0) NOT NULL,
	AMOUNT NUMBER(7,2),
	OMS_OFFER_CODE VARCHAR(16777216),
	LOYALTY_ID NUMBER(38,0),
	APPLIED_ITEMS VARCHAR(16777216),
	ORDER_ID NUMBER(38,0) NOT NULL,
	POS_DISCOUNT_ID VARCHAR(16777216),
	NAME VARCHAR(16777216),
	CERTIFICATE_ID VARCHAR(16777216)
);
create TABLE IF NOT EXISTS DIGITAL_ORDER_HISTORICAL_ORDER_ITEMS (
	ID NUMBER(38,0) NOT NULL,
	POS_ID NUMBER(38,0),
	PRODUCT_ID VARCHAR(16777216),
	DESTINATION NUMBER(38,0),
	PRICE NUMBER(7,2) NOT NULL,
	QUANTITY NUMBER(38,0) NOT NULL,
	ORDER_ID NUMBER(38,0),
	PARENT_ID NUMBER(38,0),
	DESCRIPTION VARCHAR(16777216),
	NOTE VARCHAR(16777216),
	LINE_ITEM_ID NUMBER(38,0),
	COMPONENT_ID NUMBER(38,0),
	PRODUCT_KIND VARCHAR(16777216),
	PRICE_TYPE VARCHAR(16777216),
	INVISIBLE BOOLEAN,
	UDP_RECOMMENDATION_ID VARCHAR(16777216)
);
create TABLE IF NOT EXISTS DIGITAL_ORDER_HISTORICAL_ORDER_STATUS_MAPPINGS (
	ID NUMBER(38,0) NOT NULL,
	BRAND_ID VARCHAR(16777216) NOT NULL,
	FULFILLMENT_TYPE VARCHAR(16777216) NOT NULL,
	ORDER_STATUS VARCHAR(16777216) NOT NULL,
	DISPLAY_STATUS VARCHAR(16777216) NOT NULL
);
create TABLE IF NOT EXISTS DIGITAL_ORDER_HISTORICAL_PAYMENTS (
	ORDER_ID NUMBER(38,0) NOT NULL,
	TOKEN VARCHAR(16777216),
	AMOUNT NUMBER(7,2),
	STATUS VARCHAR(16777216),
	STATUS_DETAIL VARCHAR(16777216),
	SESSION_KEY VARCHAR(16777216),
	POS_SYNC_ID VARCHAR(16777216),
	POS_SYNC_ATTEMPT_NUM NUMBER(38,0),
	REQUEST_ID VARCHAR(16777216),
	CARD_HOLDER_NAME VARCHAR(16777216),
	CARD_ISSUER VARCHAR(16777216),
	MASKED_CARD_NUMBER VARCHAR(16777216),
	DEVICE_IDENTIFIER VARCHAR(16777216)
);
create TABLE IF NOT EXISTS DIGITAL_ORDER_HISTORICAL_PAYMENT_KEYS (
	ORDER_ID NUMBER(38,0) NOT NULL,
	PAYMENT_KEY VARCHAR(16777216) NOT NULL,
	SESSION_KEY VARCHAR(16777216),
	DESCRIPTION VARCHAR(16777216),
	PAYMENT_TYPE VARCHAR(16777216) NOT NULL,
	CARD_ISSUER VARCHAR(16777216),
	MASKED_CARD_NUMBER VARCHAR(16777216),
	AMOUNT NUMBER(7,2),
	CARD_HOLDER_NAME VARCHAR(16777216),
	STATUS VARCHAR(16777216),
	PAYMENT_PROCESS_CODE VARCHAR(16777216),
	SEQUENCE NUMBER(38,0),
	CARD_TOKEN VARCHAR(16777216)
);
create TABLE IF NOT EXISTS ECOSUREAUDITEXTRACT (
	VALUE VARIANT,
	FILENAME VARCHAR(16777216),
	LOAD_ID NUMBER(38,0),
	LOAD_DTTM TIMESTAMP_NTZ(9)
);
create TABLE IF NOT EXISTS FRM_RAW (
	URL VARCHAR(16777216),
	RESPONSE VARIANT,
	TIMESTAMP NUMBER(38,0),
	EPOCH NUMBER(38,0),
	BRAND_ID VARCHAR(16777216),
	SOURCE_SYSTEM_NAME VARCHAR(16777216),
	LOAD_ID NUMBER(38,0),
	LOAD_DTTM VARCHAR(16777216),
	UPDATE_ID NUMBER(38,0),
	UPDATE_DTTM VARCHAR(16777216),
	LOAD_FILENAME VARCHAR(16777216)
);
create TABLE IF NOT EXISTS GA_ANALYTICS_EVENTS (
	EVENT_DATE VARCHAR(16777216),
	EVENT_TIMESTAMP NUMBER(38,0),
	EVENT_NAME VARCHAR(16777216),
	EVENT_PARAMS ARRAY,
	EVENT_PREVIOUS_TIMESTAMP NUMBER(38,0),
	EVENT_VALUE_IN_USD FLOAT,
	EVENT_BUNDLE_SEQUENCE_ID NUMBER(38,0),
	EVENT_SERVER_TIMESTAMP_OFFSET NUMBER(38,0),
	USER_ID VARCHAR(16777216),
	USER_PSEUDO_ID VARCHAR(16777216),
	USER_PROPERTIES ARRAY,
	USER_FIRST_TOUCH_TIMESTAMP NUMBER(38,0),
	USER_LTV OBJECT,
	DEVICE OBJECT,
	GEO OBJECT,
	APP_INFO OBJECT,
	TRAFFIC_SOURCE OBJECT,
	STREAM_ID VARCHAR(16777216),
	PLATFORM VARCHAR(16777216),
	EVENT_DIMENSIONS OBJECT,
	ECOMMERCE OBJECT,
	ITEMS ARRAY,
	LOAD_ID NUMBER(34,0),
	LOAD_DATE TIMESTAMP_NTZ(9),
	DATASET_ID VARCHAR(16777216)
);
create TABLE IF NOT EXISTS GA_SESSIONS (
	VISITORID NUMBER(38,0),
	VISITNUMBER NUMBER(38,0),
	VISITID NUMBER(38,0),
	VISITSTARTTIME NUMBER(38,0),
	DATE VARCHAR(150),
	TOTALS OBJECT,
	TRAFFICSOURCE OBJECT,
	DEVICE OBJECT,
	GEONETWORK OBJECT,
	CUSTOMDIMENSIONS ARRAY,
	HITS ARRAY,
	FULLVISITORID VARCHAR(150),
	USERID VARCHAR(150),
	CLIENTID VARCHAR(150),
	CHANNELGROUPING VARCHAR(150),
	SOCIALENGAGEMENTTYPE VARCHAR(150),
	LOAD_ID NUMBER(34,0),
	LOAD_DATE TIMESTAMP_NTZ(9),
	DATASET_ID VARCHAR(16777216)
);
create TABLE IF NOT EXISTS IDP_MENU (
	ID VARIANT,
	LOCATIONID VARIANT,
	COUNTRYCODE VARIANT,
	CHANNELID VARIANT,
	NAME VARIANT,
	METADATA VARIANT,
	TYPE VARIANT,
	VALIDITY VARIANT,
	PRODUCTGROUPS VARIANT,
	ITEMGROUPS VARIANT,
	SIZEGROUPS VARIANT,
	PRODUCTS VARIANT,
	AVAILABILITYOVERRIDES VARIANT,
	CATEGORIES VARIANT,
	BRANDID VARIANT,
	LOAD_DATE DATE,
	LOAD_ID NUMBER(38,0),
	LOAD_DTTM TIMESTAMP_NTZ(9)
);
create TABLE IF NOT EXISTS IDP_ORDER (
	ID VARCHAR(16777216),
	IDEMPOTENTID VARCHAR(16777216),
	BRANDID VARCHAR(16777216),
	SOURCECHANNEL VARCHAR(16777216),
	ORDERTYPE VARCHAR(16777216),
	ORDERSUBTYPE VARCHAR(16777216),
	STATUS VARCHAR(16777216),
	DISPLAYSTATUS VARCHAR(16777216),
	NAME VARCHAR(16777216),
	SERVER VARCHAR(16777216),
	TABLE_FIELD VARCHAR(16777216),
	NUMBEROFGUEST NUMBER(38,0),
	STORECHECKNUMBER VARCHAR(16777216),
	ORDERPLACEDDATETIME VARCHAR(16777216),
	DELIVERYTIME VARCHAR(16777216),
	EXPECTEDPICKUPTIME VARCHAR(16777216),
	POSORDERID VARCHAR(16777216),
	DISPLAYID VARCHAR(16777216),
	POSSTATUS VARCHAR(16777216),
	POSRESULTCODE VARCHAR(16777216),
	POSMESSAGE VARCHAR(16777216),
	SUBTOTAL NUMBER(18,2),
	TOTALTAX NUMBER(18,2),
	DELIVERYFEE NUMBER(18,2),
	DISCOUNT NUMBER(18,2),
	DISCOUNTEDPRICE NUMBER(18,2),
	TIP NUMBER(18,2),
	TOTALPRICE NUMBER(18,2),
	PAYMENTURL VARCHAR(16777216),
	TALLYTIME VARCHAR(16777216),
	DETAILS VARCHAR(16777216),
	ITEMS ARRAY,
	CUSTOMER VARIANT,
	FULFILLMENT VARIANT,
	LOCATION OBJECT,
	PAYMENTS ARRAY,
	METADATA VARCHAR(16777216),
	DISCOUNTS ARRAY,
	UDPCORRELATIONID VARCHAR(16777216),
	SUBSCRIPTIONNAME VARCHAR(16777216),
	TOPICNAME VARCHAR(16777216),
	EVENT_ENQUEUED_TIME VARCHAR(16777216),
	EVENT_OFFSET NUMBER(38,0),
	EVENT_PARTITION_ID VARCHAR(16777216),
	HEADER VARIANT,
	ADLS_FILE_PATH VARCHAR(16777216),
	LOAD_ID NUMBER(38,0),
	LOAD_DTTM TIMESTAMP_NTZ(9)
);
create TABLE IF NOT EXISTS IDP_SUGGESTED_SELL (
	ITEMSINCART ARRAY,
	CORRELATIONID VARCHAR(16777216),
	RECOMMENDATIONID VARCHAR(16777216),
	BASKETID VARCHAR(16777216),
	RECOMMENDEDITEMS ARRAY,
	CUSTOMERSEGMENT VARCHAR(16777216),
	RECOMMENDATIONFILENAME VARCHAR(16777216),
	LOCATIONID VARCHAR(16777216),
	SUBSCRIPTIONNAME VARCHAR(16777216),
	TOPICNAME VARCHAR(16777216),
	HEADER OBJECT,
	EVENT_ENQUEUED_TIME VARCHAR(16777216),
	EVENT_OFFSET NUMBER(38,0),
	EVENT_PARTITION_ID VARCHAR(16777216),
	ADLS_FILE_PATH VARCHAR(16777216),
	LOAD_ID NUMBER(38,0),
	LOAD_DTTM TIMESTAMP_NTZ(9)
);
create TABLE IF NOT EXISTS MENU_PRICES_TEST (
	PRODUCTS VARIANT,
	SIZE_GROUPS VARIANT,
	ITEM_GROUPS VARIANT,
	PRODUCT_GROUPS VARIANT,
	CATEGORIES VARIANT
);
create TABLE IF NOT EXISTS MENU_PRICE_RAW_TEST (
	V VARIANT
);
create TABLE IF NOT EXISTS ORDER_LINE_STG (
	ORDER_LINE_ID VARCHAR(16777216),
	ORDER_ID VARCHAR(16777216),
	BUSINESS_DT VARCHAR(16777216),
	ORDER_LINE_TYP VARCHAR(16777216),
	CHANNEL_ID VARCHAR(16777216),
	MDM_ITEM_ID VARCHAR(16777216),
	MDM_PARENT_ITEM_ID VARCHAR(16777216),
	TIME_KEY VARCHAR(16777216),
	STORE_ID VARCHAR(16777216),
	EMPLOYEE_ID VARCHAR(16777216),
	REGISTER_ID VARCHAR(16777216),
	TAX_ID VARCHAR(16777216),
	SEAT_NBR VARCHAR(16777216),
	SOURCE_GROSS_QTY NUMBER(38,0),
	PRICE_AMT FLOAT,
	SOURCE_GROSS_AMT FLOAT,
	SOURCE_DISCOUNT_AMT FLOAT,
	SOURCE_NET_AMT FLOAT,
	TAX_AMT FLOAT,
	CLEARED_IND VARCHAR(16777216),
	DELETED_IND VARCHAR(16777216),
	VOID_IND VARCHAR(16777216),
	INVENTORY_IND VARCHAR(16777216),
	MODIFIER_IND VARCHAR(16777216),
	TAX_EXEMPT_ID VARCHAR(16777216),
	MANAGER_ID VARCHAR(16777216),
	DERIVED_GROSS_QTY NUMBER(38,0),
	DERIVED_GROSS_AMT FLOAT,
	DERIVED_DISCOUNT_AMT FLOAT,
	DERIVED_NET_AMT FLOAT,
	SOURCE_ITEM_ID VARCHAR(16777216),
	SOURCE_ITEM_PLU_ID VARCHAR(16777216),
	SOURCE_ITEM_DESC VARCHAR(16777216),
	SOURCE_PARENT_ITEM_ID VARCHAR(16777216),
	DISCOUNT_CD VARCHAR(16777216),
	DISCOUNT_NM VARCHAR(16777216),
	SOURCE_DISCOUNT_TYP VARCHAR(16777216),
	ORDER_LINE_PARENT_ID VARCHAR(16777216),
	MISC_CHARGE_AMT FLOAT,
	ITEM_TYPE_CD VARCHAR(16777216),
	ALTERNATE1_ORDER_ID VARCHAR(16777216),
	BRAND_ID VARCHAR(16777216),
	SOURCE_SYSTEM_NM VARCHAR(16777216),
	LOAD_TYP VARCHAR(16777216),
	LOAD_ID VARCHAR(16777216),
	LOAD_DTTM VARCHAR(16777216),
	UPDATE_ID VARCHAR(16777216),
	UPDATE_DTTM VARCHAR(16777216)
);
create TABLE IF NOT EXISTS ORDER_STG (
	ORDER_ID VARCHAR(16777216),
	EMPLOYEE_ID VARCHAR(16777216),
	BUSINESS_DT VARCHAR(16777216),
	STORE_ID VARCHAR(16777216),
	CHECK_NBR VARCHAR(16777216),
	OPENED_TM VARCHAR(16777216),
	CLOSED_TM VARCHAR(16777216),
	ORDER_NM VARCHAR(16777216),
	ITEM_CNT NUMBER(38,0),
	TRANSACTION_CNT NUMBER(38,0),
	SOURCE_GROSS_AMT FLOAT,
	SOURCE_DISCOUNT_AMT FLOAT,
	SOURCE_NET_AMT FLOAT,
	SURCHARGE_AMT FLOAT,
	TAX_AMT FLOAT,
	SOURCE_PAYMENT_AMT FLOAT,
	GRATUITY_AMT FLOAT,
	CUSTOMER_NM VARCHAR(16777216),
	CUSTOMER_ID VARCHAR(16777216),
	LOYALTY_NBR VARCHAR(16777216),
	FIRST_SEND_TM VARCHAR(16777216),
	CLOSED_IND VARCHAR(16777216),
	FUTURE_ORDER_IND VARCHAR(16777216),
	VOID_IND VARCHAR(16777216),
	COMBO_TRANSACTION_IND VARCHAR(16777216),
	REFUND_IND VARCHAR(16777216),
	TAX_EXEMPT_IND VARCHAR(16777216),
	GUEST_CNT NUMBER(38,0),
	BRAND_ID VARCHAR(16777216),
	SOURCE_SYSTEM_NM VARCHAR(16777216),
	TIME_KEY VARCHAR(16777216),
	LOAD_TYP VARCHAR(16777216),
	DERIVED_GROSS_AMT FLOAT,
	DERIVED_DISCOUNT_AMT FLOAT,
	DERIVED_NET_AMT FLOAT,
	DERIVED_PAYMENT_AMT FLOAT,
	MISC_CHARGE_AMT FLOAT,
	CHANNEL_ID VARCHAR(16777216),
	ALTERNATE1_ORDER_ID VARCHAR(16777216),
	LOAD_ID VARCHAR(16777216),
	LOAD_DTTM VARCHAR(16777216),
	UPDATE_ID VARCHAR(16777216),
	UPDATE_DTTM VARCHAR(16777216)
);
create TABLE IF NOT EXISTS T1 (
	ID NUMBER(38,0)
);
create TABLE IF NOT EXISTS TEMP1 (
	CUSTOMER_ADDRESS_ID NUMBER(38,0),
	BRAND_ID VARCHAR(16777216),
	BRAND_CUSTOMER_ID VARCHAR(16777216),
	STATE_CODE VARCHAR(16777216),
	ZIP_CODE VARCHAR(16777216)
);
create TABLE IF NOT EXISTS TEST (
	BRAND VARCHAR(3),
	REPORTING_PERIOD DATE,
	CUSTOMER_NUMBER VARCHAR(16777216),
	CUSTOMER_NAME VARCHAR(16777216),
	UNIT VARCHAR(16777216),
	LOCAL_CURRENCY VARCHAR(3),
	LOCAL_NET_SALES FLOAT,
	TRANSACTION_COUNT NUMBER(38,0),
	LOCAL_GROSS_SALES FLOAT
);
create TABLE IF NOT EXISTS TESTING (
	ID NUMBER(38,0)
);
create TABLE IF NOT EXISTS TOKEN_ADLS (
	STORE_ID VARCHAR(16777216),
	SOURCE_DATA VARIANT
);
create TABLE IF NOT EXISTS WORKDAY_RAW (
	URL VARCHAR(16777216),
	RESPONSE VARIANT,
	TIMESTAMP NUMBER(38,0),
	EPOCH NUMBER(38,0),
	BRAND_ID VARCHAR(16777216),
	SOURCE_SYSTEM_NAME VARCHAR(16777216),
	LOAD_ID NUMBER(38,0),
	LOAD_DTTM VARCHAR(16777216),
	UPDATE_ID NUMBER(38,0),
	UPDATE_DTTM VARCHAR(16777216),
	LOAD_FILENAME VARCHAR(16777216)
);
create TABLE IF NOT EXISTS WORKDAY_RAW_AB_TEST (
	URL VARCHAR(16777216),
	RESPONSE VARIANT,
	TIMESTAMP NUMBER(38,0),
	EPOCH NUMBER(38,0),
	BRAND_ID VARCHAR(16777216),
	SOURCE_SYSTEM_NAME VARCHAR(16777216),
	LOAD_ID NUMBER(38,0),
	LOAD_DTTM VARCHAR(16777216),
	UPDATE_ID NUMBER(38,0),
	UPDATE_DTTM VARCHAR(16777216),
	LOAD_FILENAME VARCHAR(16777216)
);
create TABLE IF NOT EXISTS ZEKA_TEST_123 (
	T1 TIMESTAMP_TZ(9)
);
CREATE VIEW IF NOT EXISTS BMARSZALEK_IDM_COREDIM_CUSTOMER_V(
	BRAND_ID,
	MBR_INSPIRE_ID,
	MBR_ID,
	CLOSEST_STORE_ID,
	HOUSEHOLD_ID,
	EMAIL_ID,
	MOBILE_DEVICE_ID,
	EXPERIAN_ID,
	EXPERIAN_STATUS_TYP,
	INSPIRE_CUST_TYP,
	CUSTOMER_AUTHENTICATION_STATUS,
	MDM_ID,
	MDM_ID_DELETED_IND,
	LOYALTY_CARD_NBR,
	FIRST_NM,
	LAST_NM,
	MIDDLE_INITIAL_TXT,
	DOB_DT,
	BIRTH_MNTH_ID,
	BIRTH_YEAR_ID,
	BIRTH_DT_IMPLIED_IND,
	GENDER_TYP,
	ENROLLMENT_CHANNEL_TYP,
	MBR_STATUS_CD,
	POINT_BALANCE_QTY,
	MEMBERSHIP_STATUS_CD,
	PROFILE_COMPLETED_STATUS_IND,
	DELIVERABILITY_STATUS_IND,
	MOBILE_NBR,
	ADR_LINE_1_TXT,
	ADR_LINE_2_TXT,
	CTY_NM,
	ST_CD,
	ZIP_CD,
	CNTRY_CD,
	EMAIL_OPT_OUT_IND,
	PUSH_NOTIFICATION_OPT_IN_IND,
	SMS_OPT_IN_IND,
	PRIVACY_IND,
	UNSUBSCRIBE_DTTM,
	POINT_EXPIRE_DTTM,
	ENROLL_START_DTTM,
	LAST_LOGIN_DTTM,
	LAST_STATUS_CHANGE_DTTM,
	PROFILE_COMPLETION_DTTM,
	SUBSCRIBER_KEY,
	SUBSCRIBER_SOURCE_NM,
	LOYALTY_TIER_CHANGE_DTTM,
	LOYALTY_TIER_NM,
	LOYALTY_TIER_EXPIRATION_DT,
	LOYALTY_ELITE_VISIT_CNT,
	SOURCE_SYSTEM_NM,
	CDM_LOAD_DT,
	LOAD_ID,
	LOAD_DTTM,
	UPDATE_ID,
	UPDATE_DTTM,
	PUSH_DEVICE_ID,
	ADDRESS_OPT_IN_IND,
	IGNORE_FRAUD_SUSPEND_IND,
	EMAIL_OPT_OUT_STATUS_IND
) as
SELECT
    BC.BRAND_ID AS BRAND_ID,
    BC.BRAND_CUSTOMER_ID AS MBR_INSPIRE_ID,
    BM.BRAND_MEMBER_ID AS MBR_ID,
    BM.CLOSEST_REST_ID AS CLOSEST_STORE_ID,
    NULL AS HOUSEHOLD_ID,
    BCE.STRIPPED_EMAIL_ADDRESS AS EMAIL_ID,
    BCD.CUSTOMER_DEVICE_ID AS MOBILE_DEVICE_ID,
    NULL AS EXPERIAN_ID,
    NULL AS EXPERIAN_STATUS_TYP,
    NULL AS INSPIRE_CUST_TYP,
    BC.CUSTOMER_AUTHENTICATION_STATUS AS CUSTOMER_AUTHENTICATION_STATUS,
    NULL AS MDM_ID,
    NULL AS MDM_ID_DELETED_IND,
    BM.MEMBER_CARD_NBR AS LOYALTY_CARD_NBR,
    BC.FIRST_NAME AS FIRST_NM,
    BC.LAST_NAME AS LAST_NM,
    BC.MIDDLE_NAME AS MIDDLE_INITIAL_TXT,
    BC.DATE_OF_BIRTH AS DOB_DT,
    BC.BIRTH_MONTH AS BIRTH_MNTH_ID,
    BC.BIRTH_YR AS BIRTH_YEAR_ID,
    BC.BIRTH_IMPLIED_IND AS BIRTH_DT_IMPLIED_IND,
    BC.GENDER AS GENDER_TYP,
    BM.ENROLLMENT_CHANNEL_TYPE AS ENROLLMENT_CHANNEL_TYP,
    BM.MEMBER_STATUS_CODE AS MBR_STATUS_CD,
    BMPB.POINT_BALANCE_QTY AS POINT_BALANCE_QTY,
    NULL AS MEMBERSHIP_STATUS_CD,
    BCPS.SURVEY_COMPLETION_STATUS_IND AS PROFILE_COMPLETED_STATUS_IND,
    BCE.EMAIL_DELIVERABILITY_STATUS AS DELIVERABILITY_STATUS_IND,
    BCP.PHONE_NBR AS MOBILE_NBR,
    BCA.ADDRESS_LINE1_TXT AS ADR_LINE_1_TXT,
    BCA.ADDRESS_LINE2_TXT AS ADR_LINE_2_TXT,
    BCA.CITY AS CTY_NM,
    BCA.STATE_CODE AS ST_CD,
    BCA.ZIP_CODE AS ZIP_CD,
    BCA.COUNTRY_CODE AS CNTRY_CD,
    BCE.CUSTOMER_EMAIL_OPT_OUT_IND AS EMAIL_OPT_OUT_IND,
    NOT BCD.CUSTOMER_DEVICE_PUSH_OPT_OUT_IND AS PUSH_NOTIFICATION_OPT_IN_IND,
    NOT BCD.CUSTOMER_DEVICE_SMS_OPT_OUT_IND AS SMS_OPT_IN_IND,
    BC.PRIVACY_IND AS PRIVACY_IND,
    BM.UNSUBSCRIBE_DTTM AS UNSUBSCRIBE_DTTM,
    BMPB.POINT_EXPIRE_DATE AS POINT_EXPIRE_DTTM,
    BM.ENROLL_START_DATE AS ENROLL_START_DTTM,
    BM.LAST_LOGIN_DTTM AS LAST_LOGIN_DTTM,
    BM.LAST_STATUS_CHANGE_DTTM AS LAST_STATUS_CHANGE_DTTM,
    BCPS.SURVEY_COMPLETION_DATE AS PROFILE_COMPLETION_DTTM,
    SPLIT_PART(BM.BRAND_CUSTOMER_ID, '.',  0) as SUBSCRIBER_KEY,
    NULL AS SUBSCRIBER_SOURCE_NM,
    NULL AS LOYALTY_TIER_CHANGE_DTTM,
    NULL AS LOYALTY_TIER_NM,
    NULL AS LOYALTY_TIER_EXPIRATION_DT,
    NULL AS LOYALTY_ELITE_VISIT_CNT,
    CASE
        WHEN BC.SOURCE_SYSTEM_NAME = 'epsilon' AND BC.BRAND_ID = 'arbys' THEN 'loyalty'
        ELSE BC.SOURCE_SYSTEM_NAME
    END AS SOURCE_SYSTEM_NM,
    NULL AS CDM_LOAD_DT,
    BC.LOAD_ID AS LOAD_ID,
    BC.LOAD_DTTM AS LOAD_DTTM,
    BC.UPDATE_ID AS UPDATE_ID,
    BC.UPDATE_DTTM UPDATE_DTTM,
    BCD.DEVICE_ID AS PUSH_DEVICE_ID,
    NOT BCA.CUSTOMER_ADDRESS_OPT_OUT_IND AS ADDRESS_OPT_IN_IND,
    BC.IGNORE_FRAUD_SUSPEND_IND AS IGNORE_FRAUD_SUSPEND_IND,
    CEMSCA.EMAIL_OPT_OUT_STATUS_IND AS EMAIL_OPT_OUT_STATUS_IND
FROM
    IDS_DEV.CUST.BRAND_CUSTOMER BC
    LEFT JOIN IDS_DEV.CUST.BRAND_CUSTOMER_ADDRESS BCA ON BC.BRAND_CUSTOMER_ID = BCA.BRAND_CUSTOMER_ID
    LEFT JOIN IDS_DEV.CUST.BRAND_CUSTOMER_PHONE BCP ON BC.BRAND_CUSTOMER_ID = BCP.BRAND_CUSTOMER_ID
    LEFT JOIN IDS_DEV.CUST.BRAND_CUSTOMER_EMAIL BCE ON BC.BRAND_CUSTOMER_ID = BCE.BRAND_CUSTOMER_ID
    INNER JOIN IDS_DEV.CUST.BRAND_MEMBER BM ON BC.SOURCE_CUSTOMER_ID = BM.SOURCE_MEMBER_ID AND BC.BRAND_ID = BM.BRAND_ID
    LEFT JOIN IDS_DEV.CUST.BRAND_MEMBER_POINT_BALANCE BMPB ON BM.BRAND_MEMBER_ID = BMPB.BRAND_MEMBER_ID
    LEFT JOIN IDS_DEV.CUST.BRAND_CUSTOMER_DEVICE BCD ON BC.BRAND_CUSTOMER_ID = BCD.BRAND_CUSTOMER_ID
    LEFT JOIN IDS_DEV.CUST.BRAND_CUSTOMER_PROFILE_SURVEY BCPS ON BC.BRAND_CUSTOMER_ID = BCPS.BRAND_CUSTOMER_ID
    LEFT JOIN STG_DEV.ARB.AYEFREMOV_CURRENT_EMAIL_STATUS_FROM_CRM_EMAIL_STATUS_CHANGE_ARBYS AS CEMSCA 
    ON lower(BC.BRAND_CUSTOMER_ID) = CEMSCA.BRAND_CUSTOMER_ID --lowered in CEMSCA in the stg for performance
       and lower(BCE.STRIPPED_EMAIL_ADDRESS) = CEMSCA.EMAIL_ADDRESS --lowered in CEMSCA in stg for performance
WHERE BC.BRAND_ID = 'arbys' and SOURCE_SYSTEM_NM = 'loyalty';
CREATE VIEW IF NOT EXISTS IDM_COREDIM_CUSTOMER_TEST_V(
	BRAND_ID,
	MBR_INSPIRE_ID,
	MBR_ID,
	CLOSEST_STORE_ID,
	HOUSEHOLD_ID,
	EMAIL_ID,
	MOBILE_DEVICE_ID,
	EXPERIAN_ID,
	EXPERIAN_STATUS_TYP,
	INSPIRE_CUST_TYP,
	CUSTOMER_AUTHENTICATION_STATUS,
	MDM_ID,
	MDM_ID_DELETED_IND,
	LOYALTY_CARD_NBR,
	FIRST_NM,
	LAST_NM,
	MIDDLE_INITIAL_TXT,
	DOB_DT,
	BIRTH_MNTH_ID,
	BIRTH_YEAR_ID,
	BIRTH_DT_IMPLIED_IND,
	GENDER_TYP,
	ENROLLMENT_CHANNEL_TYP,
	MBR_STATUS_CD,
	POINT_BALANCE_QTY,
	MEMBERSHIP_STATUS_CD,
	PROFILE_COMPLETED_STATUS_IND,
	DELIVERABILITY_STATUS_IND,
	MOBILE_NBR,
	ADR_LINE_1_TXT,
	ADR_LINE_2_TXT,
	CTY_NM,
	ST_CD,
	ZIP_CD,
	CNTRY_CD,
	EMAIL_OPT_OUT_IND,
	PUSH_NOTIFICATION_OPT_IN_IND,
	SMS_OPT_IN_IND,
	PRIVACY_IND,
	UNSUBSCRIBE_DTTM,
	POINT_EXPIRE_DTTM,
	ENROLL_START_DTTM,
	LAST_LOGIN_DTTM,
	LAST_STATUS_CHANGE_DTTM,
	PROFILE_COMPLETION_DTTM,
	SUBSCRIBER_KEY,
	SUBSCRIBER_SOURCE_NM,
	LOYALTY_TIER_CHANGE_DTTM,
	LOYALTY_TIER_NM,
	LOYALTY_TIER_EXPIRATION_DT,
	LOYALTY_ELITE_VISIT_CNT,
	SOURCE_SYSTEM_NM,
	CDM_LOAD_DT,
	LOAD_ID,
	LOAD_DTTM,
	UPDATE_ID,
	UPDATE_DTTM,
	PUSH_DEVICE_ID,
	ADDRESS_OPT_IN_IND,
	IGNORE_FRAUD_SUSPEND_IND,
	EMAIL_OPT_OUT_STATUS_IND
) as
SELECT
    BC.BRAND_ID AS BRAND_ID,
    BC.BRAND_CUSTOMER_ID AS MBR_INSPIRE_ID,
    BM.BRAND_MEMBER_ID AS MBR_ID,
    BM.CLOSEST_REST_ID AS CLOSEST_STORE_ID,
    NULL AS HOUSEHOLD_ID,
    BCE.STRIPPED_EMAIL_ADDRESS AS EMAIL_ID,
    BCD.CUSTOMER_DEVICE_ID AS MOBILE_DEVICE_ID,
    NULL AS EXPERIAN_ID,
    NULL AS EXPERIAN_STATUS_TYP,
    NULL AS INSPIRE_CUST_TYP,
    BC.CUSTOMER_AUTHENTICATION_STATUS AS CUSTOMER_AUTHENTICATION_STATUS,
NULL AS MDM_ID,
NULL AS MDM_ID_DELETED_IND,
    BM.MEMBER_CARD_NBR AS LOYALTY_CARD_NBR,
    BC.FIRST_NAME AS FIRST_NM,
    BC.LAST_NAME AS LAST_NM,
    BC.MIDDLE_NAME AS MIDDLE_INITIAL_TXT,
    BC.DATE_OF_BIRTH AS DOB_DT,
    BC.BIRTH_MONTH AS BIRTH_MNTH_ID,
    BC.BIRTH_YR AS BIRTH_YEAR_ID,
    BC.BIRTH_IMPLIED_IND AS BIRTH_DT_IMPLIED_IND,
    BC.GENDER AS GENDER_TYP,
    BM.ENROLLMENT_CHANNEL_TYPE AS ENROLLMENT_CHANNEL_TYP,
    BM.MEMBER_STATUS_CODE AS MBR_STATUS_CD,
    BMPB.POINT_BALANCE_QTY AS POINT_BALANCE_QTY,
NULL AS MEMBERSHIP_STATUS_CD,
    BCPS.SURVEY_COMPLETION_STATUS_IND AS PROFILE_COMPLETED_STATUS_IND,
    BCE.EMAIL_DELIVERABILITY_STATUS AS DELIVERABILITY_STATUS_IND,
    BCP.PHONE_NBR AS MOBILE_NBR,
    BCA.ADDRESS_LINE1_TXT AS ADR_LINE_1_TXT,
    BCA.ADDRESS_LINE2_TXT AS ADR_LINE_2_TXT,
    BCA.CITY AS CTY_NM,
    BCA.STATE_CODE AS ST_CD,
    BCA.ZIP_CODE AS ZIP_CD,
    BCA.COUNTRY_CODE AS CNTRY_CD,
    BCE.CUSTOMER_EMAIL_OPT_OUT_IND AS EMAIL_OPT_OUT_IND,
    NOT BCD.CUSTOMER_DEVICE_PUSH_OPT_OUT_IND AS PUSH_NOTIFICATION_OPT_IN_IND,
    NOT BCD.CUSTOMER_DEVICE_SMS_OPT_OUT_IND AS SMS_OPT_IN_IND,
    BC.PRIVACY_IND AS PRIVACY_IND,
    BM.UNSUBSCRIBE_DTTM AS UNSUBSCRIBE_DTTM,
    BMPB.POINT_EXPIRE_DATE AS POINT_EXPIRE_DTTM,
    BM.ENROLL_START_DATE AS ENROLL_START_DTTM,
    BM.LAST_LOGIN_DTTM AS LAST_LOGIN_DTTM,
    BM.LAST_STATUS_CHANGE_DTTM AS LAST_STATUS_CHANGE_DTTM,
    BCPS.SURVEY_COMPLETION_DATE AS PROFILE_COMPLETION_DTTM,
    SPLIT_PART(BM.BRAND_CUSTOMER_ID, '.',  0) as SUBSCRIBER_KEY,
NULL AS SUBSCRIBER_SOURCE_NM,
    NULL AS LOYALTY_TIER_CHANGE_DTTM,
    NULL AS LOYALTY_TIER_NM,
    NULL AS LOYALTY_TIER_EXPIRATION_DT,
    NULL AS LOYALTY_ELITE_VISIT_CNT,
    CASE
        WHEN BC.SOURCE_SYSTEM_NAME = 'epsilon' AND BC.BRAND_ID = 'arbys' THEN 'loyalty'
        ELSE BC.SOURCE_SYSTEM_NAME
    END AS SOURCE_SYSTEM_NM,
    NULL AS CDM_LOAD_DT,
    BC.LOAD_ID AS LOAD_ID,
    BC.LOAD_DTTM AS LOAD_DTTM,
    BC.UPDATE_ID AS UPDATE_ID,
    BC.UPDATE_DTTM UPDATE_DTTM,
BCD.DEVICE_ID AS PUSH_DEVICE_ID,
    NOT BCA.CUSTOMER_ADDRESS_OPT_OUT_IND AS ADDRESS_OPT_IN_IND,
    BC.IGNORE_FRAUD_SUSPEND_IND AS IGNORE_FRAUD_SUSPEND_IND,
    CEMSCA.EMAIL_OPT_OUT_STATUS_IND AS EMAIL_OPT_OUT_STATUS_IND
FROM
    IDS_DEV.CUST.BRAND_CUSTOMER BC
    LEFT JOIN IDS_DEV.CUST.BRAND_CUSTOMER_ADDRESS BCA ON BC.BRAND_CUSTOMER_ID = BCA.BRAND_CUSTOMER_ID
    LEFT JOIN IDS_DEV.CUST.BRAND_CUSTOMER_PHONE BCP ON BC.BRAND_CUSTOMER_ID = BCP.BRAND_CUSTOMER_ID
    LEFT JOIN IDS_DEV.CUST.BRAND_CUSTOMER_EMAIL BCE ON BC.BRAND_CUSTOMER_ID = BCE.BRAND_CUSTOMER_ID
    INNER JOIN IDS_DEV.CUST.BRAND_MEMBER BM ON BC.SOURCE_CUSTOMER_ID = BM.SOURCE_MEMBER_ID AND BC.BRAND_ID = BM.BRAND_ID
    LEFT JOIN IDS_DEV.CUST.BRAND_MEMBER_POINT_BALANCE BMPB ON BM.BRAND_MEMBER_ID = BMPB.BRAND_MEMBER_ID
    LEFT JOIN IDS_DEV.CUST.BRAND_CUSTOMER_DEVICE BCD ON BC.BRAND_CUSTOMER_ID = BCD.BRAND_CUSTOMER_ID
    LEFT JOIN IDS_DEV.CUST.BRAND_CUSTOMER_PROFILE_SURVEY BCPS ON BC.BRAND_CUSTOMER_ID = BCPS.BRAND_CUSTOMER_ID
    LEFT JOIN STG_DEV.ARB.CURRENT_EMAIL_STATUS_FROM_CRM_EMAIL_STATUS_CHANGE_ARBYS AS CEMSCA
    ON LOWER(BC.BRAND_CUSTOMER_ID) = CEMSCA.LOWER_BRAND_CUSTOMER_ID
    AND LOWER(BCE.STRIPPED_EMAIL_ADDRESS) = CEMSCA.LOWER_STRIPPED_EMAIL_ADDRESS
WHERE
    BC.BRAND_ID = 'arbys' AND BC.SOURCE_SYSTEM_NAME = 'epsilon'
;
CREATE VIEW IF NOT EXISTS IDM_COREDIM_CUSTOMER_V(
	BRAND_ID,
	MBR_INSPIRE_ID,
	MBR_ID,
	CLOSEST_STORE_ID,
	HOUSEHOLD_ID,
	EMAIL_ID,
	MOBILE_DEVICE_ID,
	EXPERIAN_ID,
	EXPERIAN_STATUS_TYP,
	INSPIRE_CUST_TYP,
	CUSTOMER_AUTHENTICATION_STATUS,
	MDM_ID,
	MDM_ID_DELETED_IND,
	LOYALTY_CARD_NBR,
	FIRST_NM,
	LAST_NM,
	MIDDLE_INITIAL_TXT,
	DOB_DT,
	BIRTH_MNTH_ID,
	BIRTH_YEAR_ID,
	BIRTH_DT_IMPLIED_IND,
	GENDER_TYP,
	ENROLLMENT_CHANNEL_TYP,
	MBR_STATUS_CD,
	POINT_BALANCE_QTY,
	MEMBERSHIP_STATUS_CD,
	PROFILE_COMPLETED_STATUS_IND,
	DELIVERABILITY_STATUS_IND,
	MOBILE_NBR,
	ADR_LINE_1_TXT,
	ADR_LINE_2_TXT,
	CTY_NM,
	ST_CD,
	ZIP_CD,
	CNTRY_CD,
	EMAIL_OPT_OUT_IND,
	PUSH_NOTIFICATION_OPT_IN_IND,
	SMS_OPT_IN_IND,
	PRIVACY_IND,
	UNSUBSCRIBE_DTTM,
	POINT_EXPIRE_DTTM,
	ENROLL_START_DTTM,
	LAST_LOGIN_DTTM,
	LAST_STATUS_CHANGE_DTTM,
	PROFILE_COMPLETION_DTTM,
	SUBSCRIBER_KEY,
	SUBSCRIBER_SOURCE_NM,
	LOYALTY_TIER_CHANGE_DTTM,
	LOYALTY_TIER_NM,
	LOYALTY_TIER_EXPIRATION_DT,
	LOYALTY_ELITE_VISIT_CNT,
	SOURCE_SYSTEM_NM,
	CDM_LOAD_DT,
	LOAD_ID,
	LOAD_DTTM,
	UPDATE_ID,
	UPDATE_DTTM,
	PUSH_DEVICE_ID,
	ADDRESS_OPT_IN_IND,
	IGNORE_FRAUD_SUSPEND_IND,
	EMAIL_OPT_OUT_STATUS_IND
) as
SELECT
    BC.BRAND_ID AS BRAND_ID,
    BC.BRAND_CUSTOMER_ID AS MBR_INSPIRE_ID,
    BM.BRAND_MEMBER_ID AS MBR_ID,
    BM.CLOSEST_REST_ID AS CLOSEST_STORE_ID,
    NULL AS HOUSEHOLD_ID,
    BCE.STRIPPED_EMAIL_ADDRESS AS EMAIL_ID,
    BCD.CUSTOMER_DEVICE_ID AS MOBILE_DEVICE_ID,
    NULL AS EXPERIAN_ID,
    NULL AS EXPERIAN_STATUS_TYP,
    NULL AS INSPIRE_CUST_TYP,
    BC.CUSTOMER_AUTHENTICATION_STATUS AS CUSTOMER_AUTHENTICATION_STATUS,
NULL AS MDM_ID,
NULL AS MDM_ID_DELETED_IND,
    BM.MEMBER_CARD_NBR AS LOYALTY_CARD_NBR,
    BC.FIRST_NAME AS FIRST_NM,
    BC.LAST_NAME AS LAST_NM,
    BC.MIDDLE_NAME AS MIDDLE_INITIAL_TXT,
    BC.DATE_OF_BIRTH AS DOB_DT,
    BC.BIRTH_MONTH AS BIRTH_MNTH_ID,
    BC.BIRTH_YR AS BIRTH_YEAR_ID,
    BC.BIRTH_IMPLIED_IND AS BIRTH_DT_IMPLIED_IND,
    BC.GENDER AS GENDER_TYP,
    BM.ENROLLMENT_CHANNEL_TYPE AS ENROLLMENT_CHANNEL_TYP,
    BM.MEMBER_STATUS_CODE AS MBR_STATUS_CD,
    BMPB.POINT_BALANCE_QTY AS POINT_BALANCE_QTY,
NULL AS MEMBERSHIP_STATUS_CD,
    BCPS.SURVEY_COMPLETION_STATUS_IND AS PROFILE_COMPLETED_STATUS_IND,
    BCE.EMAIL_DELIVERABILITY_STATUS AS DELIVERABILITY_STATUS_IND,
    BCP.PHONE_NBR AS MOBILE_NBR,
    BCA.ADDRESS_LINE1_TXT AS ADR_LINE_1_TXT,
    BCA.ADDRESS_LINE2_TXT AS ADR_LINE_2_TXT,
    BCA.CITY AS CTY_NM,
    BCA.STATE_CODE AS ST_CD,
    BCA.ZIP_CODE AS ZIP_CD,
    BCA.COUNTRY_CODE AS CNTRY_CD,
    BCE.CUSTOMER_EMAIL_OPT_OUT_IND AS EMAIL_OPT_OUT_IND,
    NOT BCD.CUSTOMER_DEVICE_PUSH_OPT_OUT_IND AS PUSH_NOTIFICATION_OPT_IN_IND,
    NOT BCD.CUSTOMER_DEVICE_SMS_OPT_OUT_IND AS SMS_OPT_IN_IND,
    BC.PRIVACY_IND AS PRIVACY_IND,
    BM.UNSUBSCRIBE_DTTM AS UNSUBSCRIBE_DTTM,
    BMPB.POINT_EXPIRE_DATE AS POINT_EXPIRE_DTTM,
    BM.ENROLL_START_DATE AS ENROLL_START_DTTM,
    BM.LAST_LOGIN_DTTM AS LAST_LOGIN_DTTM,
    BM.LAST_STATUS_CHANGE_DTTM AS LAST_STATUS_CHANGE_DTTM,
    BCPS.SURVEY_COMPLETION_DATE AS PROFILE_COMPLETION_DTTM,
    SPLIT_PART(BM.BRAND_CUSTOMER_ID, '.',  0) as SUBSCRIBER_KEY,
NULL AS SUBSCRIBER_SOURCE_NM,
    NULL AS LOYALTY_TIER_CHANGE_DTTM,
    NULL AS LOYALTY_TIER_NM,
    NULL AS LOYALTY_TIER_EXPIRATION_DT,
    NULL AS LOYALTY_ELITE_VISIT_CNT,
    CASE
        WHEN BC.SOURCE_SYSTEM_NAME = 'epsilon' AND BC.BRAND_ID = 'arbys' THEN 'loyalty'
        ELSE BC.SOURCE_SYSTEM_NAME
    END AS SOURCE_SYSTEM_NM,
    NULL AS CDM_LOAD_DT,
    BC.LOAD_ID AS LOAD_ID,
    BC.LOAD_DTTM AS LOAD_DTTM,
    BC.UPDATE_ID AS UPDATE_ID,
    BC.UPDATE_DTTM UPDATE_DTTM,
BCD.DEVICE_ID AS PUSH_DEVICE_ID,
    NOT BCA.CUSTOMER_ADDRESS_OPT_OUT_IND AS ADDRESS_OPT_IN_IND,
    BC.IGNORE_FRAUD_SUSPEND_IND AS IGNORE_FRAUD_SUSPEND_IND,
    CEMSCA.EMAIL_OPT_OUT_STATUS_IND AS EMAIL_OPT_OUT_STATUS_IND
FROM
    IDS_DEV.CUST.BRAND_CUSTOMER BC
    LEFT JOIN IDS_DEV.CUST.BRAND_CUSTOMER_ADDRESS BCA ON BC.BRAND_CUSTOMER_ID = BCA.BRAND_CUSTOMER_ID
    LEFT JOIN IDS_DEV.CUST.BRAND_CUSTOMER_PHONE BCP ON BC.BRAND_CUSTOMER_ID = BCP.BRAND_CUSTOMER_ID
    LEFT JOIN IDS_DEV.CUST.BRAND_CUSTOMER_EMAIL BCE ON BC.BRAND_CUSTOMER_ID = BCE.BRAND_CUSTOMER_ID
    INNER JOIN IDS_DEV.CUST.BRAND_MEMBER BM ON BC.SOURCE_CUSTOMER_ID = BM.SOURCE_MEMBER_ID AND BC.BRAND_ID = BM.BRAND_ID
    LEFT JOIN IDS_DEV.CUST.BRAND_MEMBER_POINT_BALANCE BMPB ON BM.BRAND_MEMBER_ID = BMPB.BRAND_MEMBER_ID
    LEFT JOIN IDS_DEV.CUST.BRAND_CUSTOMER_DEVICE BCD ON BC.BRAND_CUSTOMER_ID = BCD.BRAND_CUSTOMER_ID
    LEFT JOIN IDS_DEV.CUST.BRAND_CUSTOMER_PROFILE_SURVEY BCPS ON BC.BRAND_CUSTOMER_ID = BCPS.BRAND_CUSTOMER_ID
    LEFT JOIN STG_DEV.ARB.CURRENT_EMAIL_STATUS_FROM_CRM_EMAIL_STATUS_CHANGE_ARBYS AS CEMSCA
    ON LOWER(BC.BRAND_CUSTOMER_ID) = CEMSCA.LOWER_BRAND_CUSTOMER_ID
    AND LOWER(BCE.STRIPPED_EMAIL_ADDRESS) = CEMSCA.LOWER_STRIPPED_EMAIL_ADDRESS
WHERE
    BC.BRAND_ID = 'arbys' AND BC.SOURCE_SYSTEM_NAME = 'epsilon'
;
CREATE VIEW IF NOT EXISTS IDM_COREDIM_LOYALTY_DISCOUNT_FACT_V(
	BRAND_ID,
	TRX_ID,
	TRX_DISCOUNT_ID,
	SOURCE_ITEM_ID,
	OFFER_CD,
	DISCOUNT_AMT,
	DISCOUNT_DESC,
	CDM_LOAD_DT,
	SOURCE_SYSTEM_NM,
	LOAD_ID,
	LOAD_DTTM,
	UPDATE_ID,
	UPDATE_DTTM
) as
SELECT
    BRAND_ID AS BRAND_ID,
    LOYALTY_TRANS_ID AS TRX_ID,
    TRANS_DISC_ID AS TRX_DISCOUNT_ID,
    SOURCE_ITEM_ID AS SOURCE_ITEM_ID,
    OFFER_CODE AS OFFER_CD,
    DISC_AMT AS DISCOUNT_AMT,
    DISC_DESC AS DISCOUNT_DESC,
    NULL AS CDM_LOAD_DT,
    CASE
        WHEN SOURCE_SYSTEM_NAME = 'epsilon' THEN 'loyalty'
        ELSE SOURCE_SYSTEM_NAME
    END AS SOURCE_SYSTEM_NM,
    LOAD_ID AS LOAD_ID,
    LOAD_DTTM AS LOAD_DTTM,
    UPDATE_ID AS UPDATE_ID,
    UPDATE_DTTM AS UPDATE_DTTM
FROM
    IDS_DEV.CUST.LOYALTY_DISC
WHERE
    BRAND_ID = 'arbys' AND SOURCE_SYSTEM_NAME = 'epsilon';
CREATE VIEW IF NOT EXISTS IDM_COREDIM_LOYALTY_MBR_OFFER_V(
	BRAND_ID,
	CDM_LOAD_DT,
	CREATE_DTTM,
	EXPIRATION_DTTM,
	LOAD_DTTM,
	LOAD_ID,
	MBR_ID,
	MBR_OFFER_ID,
	OFFER_CD,
	OPT_IN_DTTM,
	PRIVACY_IND,
	SOURCE_LOADED_DTTM,
	SOURCE_MODIFIED_DTTM,
	SOURCE_SYSTEM_NM,
	UPDATE_DTTM,
	UPDATE_ID
) as
    SELECT
    BRAND_ID AS BRAND_ID,
	NULL AS CDM_LOAD_DT,
	CREATE_DTTM AS CREATE_DTTM,
	EXPIRATION_DTTM AS EXPIRATION_DTTM,
	LOAD_DTTM AS LOAD_DTTM,
    LOAD_ID AS LOAD_ID,
	BRAND_MEMBER_ID AS MBR_ID,
    MBR_OFFER_ID AS MBR_OFFER_ID,
	OFFER_CODE AS OFFER_CD,
	OPT_IN_DTTM AS OPT_IN_DTTM,
	'FALSE' AS PRIVACY_IND,
    SOURCE_LOADED_DTTM AS SOURCE_LOADED_DTTM,
	SOURCE_MODIFIED_DTTM AS SOURCE_MODIFIED_DTTM,
	CASE 
		WHEN SOURCE_SYSTEM_NAME = 'epsilon' THEN 'loyalty'
		ELSE SOURCE_SYSTEM_NAME
    END AS SOURCE_SYSTEM_NM,
    UPDATE_DTTM AS UPDATE_DTTM,
    UPDATE_ID AS UPDATE_ID
FROM
    IDS_DEV.CUST.OMS_MEMBER_OFFER
WHERE
   BRAND_ID = 'arbys' AND SOURCE_SYSTEM_NAME = 'epsilon';
CREATE VIEW IF NOT EXISTS IDM_COREDIM_LOYALTY_MBR_OFFER_V_TEST(
	BRAND_ID,
	CDM_LOAD_DT,
	CREATE_DTTM,
	EXPIRATION_DTTM,
	LOAD_DTTM,
	LOAD_ID,
	MBR_ID,
	MBR_OFFER_ID,
	OFFER_CD,
	OPT_IN_DTTM,
	PRIVACY_IND,
	SOURCE_LOADED_DTTM,
	SOURCE_MODIFIED_DTTM,
	SOURCE_SYSTEM_NM,
	UPDATE_DTTM,
	UPDATE_ID
) as
    SELECT
    BRAND_ID AS BRAND_ID,
	NULL AS CDM_LOAD_DT,
	CREATE_DTTM AS CREATE_DTTM,
	EXPIRATION_DTTM AS EXPIRATION_DTTM,
	LOAD_DTTM AS LOAD_DTTM,
    LOAD_ID AS LOAD_ID,
	BRAND_MEMBER_ID AS MBR_ID,
    MBR_OFFER_ID AS MBR_OFFER_ID,
	OFFER_CODE AS OFFER_CD,
	OPT_IN_DTTM AS OPT_IN_DTTM,
	'FALSE' AS PRIVACY_IND,
    SOURCE_LOADED_DTTM AS SOURCE_LOADED_DTTM,
	SOURCE_MODIFIED_DTTM AS SOURCE_MODIFIED_DTTM,
	CASE 
		WHEN SOURCE_SYSTEM_NAME = 'epsilon' THEN 'loyalty'
		ELSE SOURCE_SYSTEM_NAME
    END AS SOURCE_SYSTEM_NM,
    UPDATE_DTTM AS UPDATE_DTTM,
    UPDATE_ID AS UPDATE_ID
FROM
    IDS_DEV.CUST.OMS_MEMBER_OFFER
WHERE
   BRAND_ID = 'arbys' AND SOURCE_SYSTEM_NAME = 'epsilon';
CREATE VIEW IF NOT EXISTS IDM_COREDIM_LOYALTY_OFFER_V(
	BRAND_ID,
	OFFER_CD,
	UNIQUE_OFFER_ID,
	VARIANT_ID,
	OFFER_SEQ_KEY,
	OFFER_NM,
	OFFER_REPORT_DESC,
	OFFER_SHORT_DESC,
	OFFER_DESC,
	OPT_IN_REQUIRED_IND,
	LOC_NM,
	EXCLUSION_TXT,
	OFFER_IMG_NM,
	TERM_AND_CONDITION_TXT,
	MOMENT_ELIGIBILITY_TXT,
	STANDARD_EXCLUSION_TXT,
	OTHER_EXCLUSION_TXT,
	POINT_AWARDED_QTY,
	LIMIT_NBR,
	STORE_LOC_LIST_NBR,
	DAY_PART_LIST_NBR,
	MBR_LIST_NEEDED_IND,
	STORE_TYP,
	ONE_TM_OFFER_IND,
	TRIVIA_NEEDED_IND,
	CHECK_IN_IND,
	OFFER_PRIORITY_NBR,
	OFFER_TYP,
	AWARD_NM,
	PRODUCT_PLUS_DESC,
	TRIVIA_QUESTION_IND,
	TRIVIA_ANSWER_IND,
	TARGET_OFFER_IND,
	PRIVACY_IND,
	VALIDITY_PERIOD_NBR,
	VALIDITY_UNIT_DT_NM,
	DNA_INCENTIVE_TYP,
	DNA_CAMPAIGN_TYP,
	DNA_DISCOUNT_PRODUCT_NM,
	DNA_PRODUCT_CATEGORY_NM,
	DNA_ACTION_REQUIRED_TXT,
	DNA_MINIMUM_SPEND_AMT,
	DNA_OFFER_WEEK_IN_CAMPAIGN_NBR,
	OFFER_VISIBLE_DTTM,
	OFFER_START_DTTM,
	OFFER_END_DTTM,
	DNA_INCENTIVE_AMT,
	SYSTEM_OFFER_ID,
	DNA_DISCOUNT_PRODUCT_LEVEL_CD,
	DNA_OFFER_REDEMPTION_CHANNEL_TYP,
	STATUS_CD,
	OFFER_IMAGE2_NM,
	SOURCE_APPLICATION_TYP,
	PARENT_OFFER_ID,
	SOURCE_SYSTEM_NM,
	LOAD_ID,
	LOAD_DTTM,
	UPDATE_ID,
	UPDATE_DTTM,
	OFFER_TAG,
	CDM_LOAD_DT
) as
SELECT
    BRAND_ID AS BRAND_ID,
    OFFER_CODE AS OFFER_CD,
    UNIQ_OFFER_ID AS UNIQUE_OFFER_ID,
    VARIANT_ID AS VARIANT_ID,
    OFFER_SEQ_KEY AS OFFER_SEQ_KEY,
    OFFER_NAME AS OFFER_NM,
    OFFER_REPORT_DESC AS OFFER_REPORT_DESC,
    OFFER_SHORT_DESC AS OFFER_SHORT_DESC,
    OFFER_DESC AS OFFER_DESC,
    OPTIN_REQUIRED_IND AS OPT_IN_REQUIRED_IND,
    LOCATION_NAME AS LOC_NM,
    EXCLUSIONS_TXT AS EXCLUSION_TXT,
    OFFER_IMAGE_NAME AS OFFER_IMG_NM,
    TERMS_AND_CONDITIONS AS TERM_AND_CONDITION_TXT,
    MOMENT_ELIGIBILITY AS MOMENT_ELIGIBILITY_TXT,
    STANDARD_EXCLUSIONS_TXT AS STANDARD_EXCLUSION_TXT,
    OTHER_EXCLUSIONS AS OTHER_EXCLUSION_TXT,
    POINTS_AWARDED_NBR AS POINT_AWARDED_QTY,
    LIMITS_NBR AS LIMIT_NBR,
    REST_LOCATION_NBR AS STORE_LOC_LIST_NBR,
    DAYPART AS DAY_PART_LIST_NBR,
    MEMBER_LIST_NEEDED AS MBR_LIST_NEEDED_IND,
    REST_TYPE AS STORE_TYP,
    ONE_TIME_OFFER_IND AS ONE_TM_OFFER_IND,
    TRIVIA_NEEDED_IND AS TRIVIA_NEEDED_IND,
    CHECK_IN_IND AS CHECK_IN_IND,
    OFFER_PRIORITY_NBR AS OFFER_PRIORITY_NBR,
    OFFER_TYPE AS OFFER_TYP,
    AWARD_NAME AS AWARD_NM,
    PRODUCT_PLU_DESC AS PRODUCT_PLUS_DESC,
    NULL AS TRIVIA_QUESTION_IND,
    NULL AS TRIVIA_ANSWER_IND,
    TARGET_OFFER_IND AS TARGET_OFFER_IND,
    FALSE AS PRIVACY_IND,
    VALIDITY_PERIOD AS VALIDITY_PERIOD_NBR,
    VALIDITY_UNIT_DATE_NAME AS VALIDITY_UNIT_DT_NM,
    DNA_INCENTIVE_TYPE AS DNA_INCENTIVE_TYP,
    DNA_CAMPAIGN_TYPE AS DNA_CAMPAIGN_TYP,
    DNA_DISCOUNT_PRODUCT_NAME AS DNA_DISCOUNT_PRODUCT_NM,
    DNA_PRODUCT_CATEGORY AS DNA_PRODUCT_CATEGORY_NM,
    DNA_ACTION_REQUIRED AS DNA_ACTION_REQUIRED_TXT,
    DNA_MINIMUM_SPEND_AMT AS DNA_MINIMUM_SPEND_AMT,
    DNA_OFFER_WEEK_IN_CAMPAIGN AS DNA_OFFER_WEEK_IN_CAMPAIGN_NBR,
    OFFER_VISIBLE_DTTM AS OFFER_VISIBLE_DTTM,
    OFFER_START_DTTM AS OFFER_START_DTTM,
    OFFER_END_DTTM AS OFFER_END_DTTM,
    DNA_INCENTIVE_VAL AS DNA_INCENTIVE_AMT,
    SYSTEM_OFFER_ID AS SYSTEM_OFFER_ID,
    DNA_DISCOUNT_PRODUCT_L_CODE AS DNA_DISCOUNT_PRODUCT_LEVEL_CD,
    DNA_OFFER_REDEMPTION_CHANNEL AS DNA_OFFER_REDEMPTION_CHANNEL_TYP,
    STATUS_CODE AS STATUS_CD,
    OFFER_IMAGE2_NAME AS OFFER_IMAGE2_NM,
    SOURCE_APPLICATION_TYPE AS SOURCE_APPLICATION_TYP,
    PARENT_OFFER_ID AS PARENT_OFFER_ID,
    CASE
        WHEN SOURCE_SYSTEM_NAME = 'epsilon' THEN 'loyalty'
        ELSE SOURCE_SYSTEM_NAME
    END AS SOURCE_SYSTEM_NM,
    LOAD_ID AS LOAD_ID,
    TO_TIMESTAMP(LOAD_DTTM) AS LOAD_DTTM,
    UPDATE_ID AS UPDATE_ID,
    UPDATE_DTTM AS UPDATE_DTTM,
    OFFER_TAG AS OFFER_TAG,
    NULL AS CDM_LOAD_DT
FROM IDS_DEV.CUST.OMS_OFFER
WHERE
    BRAND_ID = 'arbys' AND SOURCE_SYSTEM_NAME = 'epsilon';
CREATE FILE FORMAT IF NOT EXISTS DIGITAL_AVRO_FILE_FORMAT
	TYPE = AVRO
	NULL_IF = ()
;
CREATE FILE FORMAT IF NOT EXISTS DIGITAL_CMX_JSON_FORMAT
	TYPE = JSON
	NULL_IF = ()
	COMPRESSION = NONE
;
CREATE FILE FORMAT IF NOT EXISTS DIGITAL_ECOSURE_XML_FORMAT
	TYPE = XML
	COMPRESSION = NONE
	STRIP_OUTER_ELEMENT = TRUE
;
CREATE FILE FORMAT IF NOT EXISTS DIGITAL_JSON_GZIP_FILE_FORMAT
	TYPE = json
	NULL_IF = ()
	COMPRESSION = gzip
;
CREATE FILE FORMAT IF NOT EXISTS DIGITAL_JSON_NO_COMPRESSION_FILE_FORMAT
	TYPE = JSON
	NULL_IF = ()
	COMPRESSION = NONE
;
CREATE FILE FORMAT IF NOT EXISTS DIGITAL_JSON_UTF_FILE_FORMAT
	TYPE = JSON
	BINARY_FORMAT = 'UTF8'
	NULL_IF = ()
	STRIP_OUTER_ARRAY = TRUE
	REPLACE_INVALID_CHARACTERS = TRUE
;
CREATE FILE FORMAT IF NOT EXISTS E2E_JSON_FILE_FORMAT
	TYPE = JSON
	BINARY_FORMAT = 'UTF8'
	NULL_IF = ()
	STRIP_OUTER_ARRAY = TRUE
	REPLACE_INVALID_CHARACTERS = TRUE
;
CREATE FILE FORMAT IF NOT EXISTS JSON_FILE_FORMAT
	TYPE = JSON
	BINARY_FORMAT = 'UTF8'
	NULL_IF = ()
	STRIP_OUTER_ARRAY = TRUE
	REPLACE_INVALID_CHARACTERS = TRUE
;
CREATE FILE FORMAT IF NOT EXISTS JSON_GZIP_GSP_FORMAT
	TYPE = json
	NULL_IF = ()
	COMPRESSION = gzip
;
CREATE FILE FORMAT IF NOT EXISTS PAYCON_PARQUET_FILE_FORMAT
	TYPE = PARQUET
	NULL_IF = ()
;
CREATE FILE FORMAT IF NOT EXISTS PIPE_DELIMITED_FILE_FORMAT
	FIELD_DELIMITER = '|'
	SKIP_HEADER = 1
	BINARY_FORMAT = 'UTF8'
	NULL_IF = ()
	REPLACE_INVALID_CHARACTERS = TRUE
;
CREATE FILE FORMAT IF NOT EXISTS PIPE_DELIMITED_NO_ESCAPE_FILE_FORMAT
	FIELD_DELIMITER = '|'
	SKIP_HEADER = 1
	BINARY_FORMAT = 'UTF8'
	FIELD_OPTIONALLY_ENCLOSED_BY = '\"'
	NULL_IF = ()
	REPLACE_INVALID_CHARACTERS = TRUE
;
CREATE FILE FORMAT IF NOT EXISTS PIPE_DELIMITED_OPT_ESCAPE_FILE_FORMAT
	FIELD_DELIMITER = '|'
	SKIP_HEADER = 1
	BINARY_FORMAT = 'UTF8'
	ESCAPE = '\\'
	FIELD_OPTIONALLY_ENCLOSED_BY = '\"'
	NULL_IF = ()
	REPLACE_INVALID_CHARACTERS = TRUE
;
CREATE FILE FORMAT IF NOT EXISTS RM_AVRO_FILE_FORMAT
	TYPE = AVRO
	NULL_IF = ()
;
CREATE FILE FORMAT IF NOT EXISTS RM_JSON_FORMAT
	TYPE = json
	NULL_IF = ()
;
CREATE FILE FORMAT IF NOT EXISTS SIMPLE_AVRO_FILE_FORMAT
	TYPE = AVRO
	NULL_IF = ()
;
CREATE FILE FORMAT IF NOT EXISTS SIMPLE_PARQUET_FILE_FORMAT
	TYPE = PARQUET
	NULL_IF = ()
;
CREATE FUNCTION IF NOT EXISTS "EXTRACT_RELEVANT_MENU_FIELDS"("PRODUCT_STR" VARCHAR(16777216))
RETURNS ARRAY
LANGUAGE PYTHON
RUNTIME_VERSION = '3.8'
HANDLER = 'extract_fields'
AS '
def extract_fields(product_str):
    import json
    products_json = json.loads(product_str)
    prod_ids = products_json.keys()

    out_array = []

    for id in prod_ids:
        name = products_json[id][''name'']
        item_type = products_json[id][''type'']

        for item in products_json[id][''items''].keys():

            out_obj = {
              ''parent_id'': id,
              ''name'': name,
                ''type'': item_type,
                ''items_id'': products_json[id][''items''][item][''id''],
                ''items_name'': products_json[id][''items''][item][''name''],
                ''items_metadata_SOURCE_PRODUCT_ID'': products_json[id][''items''][item][''metadata''][''SOURCE_PRODUCT_ID''],
                ''items_price_currentPrice'': products_json[id][''items''][item][''price''][''currentPrice'']
            }
            
            if products_json[id][''items''][item][''price''].get(''metadata''):
                out_obj[''items_price_metadata_SOURCE_PRODUCT_ID''] = products_json[id][''items''][item][''price''][''metadata''][''SOURCE_PRODUCT_ID'']

            if products_json[id][''items''][item][''price''].get(''otherPrices''):
                out_obj[''items_price_otherPrices_Meal_price''] = products_json[id][''items''][item][''price''][''otherPrices''][''MEAL''][''price'']

            out_array.append(out_obj)
    return out_array
';
CREATE FUNCTION IF NOT EXISTS "FLAT_GA_EVENTS_UP_EP_VALUE"("A" ARRAY)
RETURNS ARRAY
LANGUAGE JAVASCRIPT
AS '
    const FLEXIBLE_KEY_NAMES = ["string_value", "int_value", "double_value", "float_value"]

    const parseInput = (input = {}) => {
        const res = {
            "key": input.key
        };
        const value = input.value;
        if (value) {
            for (const [key, value] of Object.entries(input.value)) {
                if (FLEXIBLE_KEY_NAMES.includes(key)) {
                    res.value = value;
                } else {
                    res[key] = value;
                }
            }
        }
        return res;
    }

    return A.map(parseInput)
  ';
CREATE FUNCTION IF NOT EXISTS "KV_ARRAY_TO_OBJECT"("A" ARRAY)
RETURNS OBJECT
LANGUAGE JAVASCRIPT
AS '
    let dict = {};
    A.forEach(item => {
        dict[item.key] = item.value;
    });
    return dict;
';
CREATE PROCEDURE IF NOT EXISTS "MYPROC"()
RETURNS VARCHAR(16777216)
LANGUAGE SQL
EXECUTE AS OWNER
AS 'DECLARE 
A VARCHAR;
BEGIN 
A :=0;
RETURN A;
END';
CREATE STREAM IF NOT EXISTS IDP_ORDER_FLAT_STREAM on table IDP_ORDER;
CREATE STREAM IF NOT EXISTS IDP_SUGGESTED_SELL_STREAM on table IDP_SUGGESTED_SELL;
CREATE TASK IF NOT EXISTS IDP_ORDER_TASK
	warehouse=RA_UA_WH
	schedule='1 MINUTE'
	as COPY INTO STG_DEV.ARB.IDP_ORDER
FROM (
  SELECT
      $1:body:id::varchar,
      $1:body:idempotentId::varchar,
      $1:body:brandId::varchar,
      $1:body:sourceChannel::varchar,
      $1:body:orderType::varchar,
      $1:body:orderSubType::varchar,
      $1:body:status::varchar,
      $1:body:displayStatus::varchar,
      $1:body:name::varchar,
      $1:body:server::varchar,
      $1:body:table::varchar,
      $1:body:numberOfGuest::integer,
      $1:body:storeCheckNumber::varchar,
      $1:body:orderPlacedDateTime::varchar,
      $1:body:deliveryTime::varchar,
      $1:body:expectedPickupTime::varchar,
      $1:body:posOrderId::varchar,
      $1:body:displayId::varchar,
      $1:body:posStatus::varchar,
      $1:body:posResultCode::varchar,
      $1:body:posMessage::varchar,
      $1:body:subTotal::decimal,
      $1:body:totalTax::decimal,
      $1:body:deliveryFee::decimal,
      $1:body:discount::decimal,
      $1:body:discountedPrice::decimal,
      $1:body:tip::decimal,
      $1:body:totalPrice::decimal,
      $1:body:tallyTime::varchar,
      $1:body:paymentURL::varchar,
      $1:body:details::varchar,
      $1:body:items::array,
      $1:body:customer::variant,
      $1:body:fulfillment::variant,
      $1:body:location::object,
      $1:body:payments::array,
      $1:body:metadata::varchar,
      $1:body:discounts::array,
      $1:body:udpCorrelationId::varchar,
      $1:properties:subscriptionName::varchar,
      $1:properties:topicName::varchar,
      $1:properties:event_enqueued_time::varchar,
      $1:properties:event_offset::integer,
      $1:properties:event_partition_id::varchar,
      $1:properties:header::varchar,
      METADATA$FILENAME,
      cast(to_varchar(SYSDATE(),'yyyymmddhh24missFF3') as NUMBER(38,0)),
      cast(SYSDATE() as TIMESTAMP_NTZ(9))
  FROM @STG_DEV.ARB.IDP_Order_STAGE/
  (file_format => STG_DEV.ARB.DIGITAL_JSON_UTF_FILE_FORMAT)
);
CREATE TASK IF NOT EXISTS IDP_SUGGESTED_SELL_TASK
	warehouse=RA_UA_WH
	schedule='1 minute'
	as COPY INTO STG_DEV.ARB.IDP_SUGGESTED_SELL
FROM (
    SELECT
        $1:body:itemsInCart::array,
        $1:body:correlationId::varchar,
        $1:body:recommendationId::varchar,
        $1:body:basketId::varchar,
        $1:body:recommendedItems::array,
        $1:body:customerSegment::varchar,
        $1:body:recommendationFilename::varchar,
        $1:body:locationId::varchar,
        $1:properties:subscriptionName::varchar,
        $1:properties:topicName::varchar,
        $1:properties:header::varchar,
        $1:properties:event_enqueued_time::varchar,
        $1:properties:event_offset::integer,
        $1:properties:event_partition_id::varchar,
        METADATA$FILENAME,
        cast(to_varchar(SYSDATE(),'yyyymmddhh24missFF3') as NUMBER(38,0)),
        cast(SYSDATE() as TIMESTAMP_NTZ(9))
    FROM @STG_DEV.ARB.SUGGESTED_SELL_STAGE/
    (file_format => STG_DEV.ARB.DIGITAL_JSON_UTF_FILE_FORMAT)
);