create TABLE IF NOT EXISTS FLYWAY_SCHEMA_HISTORY (
	INSTALLED_RANK NUMBER(38,0) NOT NULL,
	VERSION VARCHAR(50),
	DESCRIPTION VARCHAR(200),
	TYPE VARCHAR(20) NOT NULL,
	SCRIPT VARCHAR(1000) NOT NULL,
	CHECKSUM NUMBER(38,0),
	INSTALLED_BY VARCHAR(100) NOT NULL,
	INSTALLED_ON TIMESTAMP_LTZ(9) NOT NULL DEFAULT CURRENT_TIMESTAMP(),
	EXECUTION_TIME NUMBER(38,0) NOT NULL,
	SUCCESS BOOLEAN NOT NULL,
	primary key (INSTALLED_RANK)
);
create view IF NOT EXISTS DATE_DIM_V(
	DATE_KEY,
	CALENDAR_DT COMMENT 'Calendar Date is the actual Day, Month, and Year for a given day.',
	DATE_DISPLAY_NM COMMENT 'Current Day in date format ',
	CALENDAR_YEAR_NBR COMMENT 'Current Year in 4 digit  Number format ',
	CALENDAR_DAY_IN_YEAR_NBR COMMENT 'Day number for the calendar Year',
	CALENDAR_MONTH_NBR COMMENT 'Current Month number',
	CALENDAR_MONTH_NM COMMENT 'Name of the current Month',
	CALENDAR_DAYS_IN_YEAR_QTY COMMENT 'Total Number of days in calendar Year',
	CALENDAR_DAY_NM COMMENT 'Calendar Day Name ',
	CALENDAR_YEAR_START_DT COMMENT 'Start Date for the current Calendar',
	CALENDAR_YEAR_END_DT COMMENT 'End Date for the current Calendar',
	CALENDAR_QUARTER_NBR,
	CALENDAR_QUARTER_NM,
	CALENDAR_QUARTER_START_DT,
	CALENDAR_QUARTER_END_DT,
	CALENDAR_DAYS_IN_QUARTER_QTY COMMENT 'Number of days in Calendar quarter',
	CALENDAR_MONTH_START_DT,
	CALENDAR_MONTH_END_DT,
	CALENDAR_DAYS_IN_MONTH_QTY,
	CALENDAR_WEEK_IN_YEAR_NBR,
	CALENDAR_WEEK_START_DT,
	CALENDAR_WEEK_END_DT,
	WEEKDAY_IND COMMENT 'Weeday Indicator specifies if a calendar day is considered during the week, typically Monday thru Friday, or on the Weekend, Saturday or Sunday. True- Date is weekday,False- Date is a weekend ',
	FISCAL_YEAR_NBR,
	FISCAL_YEAR_START_DT,
	FISCAL_YEAR_END_DT,
	FISCAL_DAYS_IN_QUARTER_QTY,
	FISCAL_DAYS_IN_YEAR_QTY COMMENT 'Fiscal Days in Year Quantity',
	FISCAL_DAY_IN_PERIOD_NBR COMMENT 'Day number in Fiscal period',
	FISCAL_PERIOD_NBR COMMENT 'Fiscal Period Number ',
	FISCAL_QUARTER_NBR,
	FISCAL_QUARTER_START_DT,
	FISCAL_QUARTER_END_DT,
	FISCAL_PERIOD_START_DT,
	FISCAL_PERIOD_END_DT,
	FISCAL_DAYS_IN_PERIOD_QTY,
	FISCAL_WEEKS_IN_PERIOD_QTY,
	FISCAL_WEEKS_IN_YEAR_QTY,
	FISCAL_WEEK_NBR,
	FISCAL_WEEKS_IN_QUARTER_QTY,
	FISCAL_WEEK_START_DT,
	FISCAL_WEEK_END_DT,
	FISCAL_DAY_IN_WEEK_NBR,
	FISCAL_COMPARABLE_DT COMMENT 'Fiscal Comparable Date',
	CALENDAR_COMPARABLE_DT COMMENT 'Prior Year Calendar comp Date( the date is -364) ',
	CALENDAR_COMPARABLE_START_DT,
	CALENDAR_COMPARABLE_END_DT,
	CALENDAR_COMPARABLE_DAYS_IN_YEAR_QTY,
	CALENDAR_COMPARABLE_IN_YEAR_NBR,
	CALENDAR_COMPARABLE_DAYS_IN_PERIOD_QTY,
	CALENDAR_COMPARABLE_QUARTER_NBR,
	CALENDAR_COMPARABLE_QUARTER_START_DT COMMENT 'Comparable Calendar Quarter Start Date is the ',
	CALENDAR_COMPARABLE_QUARTER_END_DT COMMENT 'Comparable Calendar Quarter End Date',
	CALENDAR_COMPARABLE_PERIOD_START_DT,
	CALENDAR_COMPARABLE_PERIOD_END_DT,
	CALENDAR_COMPARABLE_WEEK_START_DT,
	CALENDAR_COMPARABLE_WEEK_END_DT,
	CALENDAR_COMPARABLE_DAY_IN_WEEK_NBR,
	BRAND_ID,
	SOURCE_SYSTEM_NM,
	LOAD_ID COMMENT 'This is the User Identifier of the Person or Process that Loaded the Table',
	LOAD_DTTM COMMENT 'The Date/Datetime the Record was Inserted',
	UPDATE_ID COMMENT 'This is the User Identifier of the Person or Process that Updated the Table',
	UPDATE_DTTM COMMENT 'The Date/Datetime the Record was Updated'
) as 
SELECT DATE_DIM_BV.DATE_KEY,DATE_DIM_BV.CALENDAR_DT,DATE_DIM_BV.DATE_DISPLAY_NM,DATE_DIM_BV.CALENDAR_YEAR_NBR,DATE_DIM_BV.CALENDAR_DAY_IN_YEAR_NBR,DATE_DIM_BV.CALENDAR_MONTH_NBR,DATE_DIM_BV.CALENDAR_MONTH_NM,DATE_DIM_BV.CALENDAR_DAYS_IN_YEAR_QTY,DATE_DIM_BV.CALENDAR_DAY_NM,DATE_DIM_BV.CALENDAR_YEAR_START_DT,DATE_DIM_BV.CALENDAR_YEAR_END_DT,DATE_DIM_BV.CALENDAR_QUARTER_NBR,DATE_DIM_BV.CALENDAR_QUARTER_NM,DATE_DIM_BV.CALENDAR_QUARTER_START_DT,DATE_DIM_BV.CALENDAR_QUARTER_END_DT,DATE_DIM_BV.CALENDAR_DAYS_IN_QUARTER_QTY,DATE_DIM_BV.CALENDAR_MONTH_START_DT,DATE_DIM_BV.CALENDAR_MONTH_END_DT,DATE_DIM_BV.CALENDAR_DAYS_IN_MONTH_QTY,DATE_DIM_BV.CALENDAR_WEEK_IN_YEAR_NBR,DATE_DIM_BV.CALENDAR_WEEK_START_DT,DATE_DIM_BV.CALENDAR_WEEK_END_DT,DATE_DIM_BV.WEEKDAY_IND,DATE_DIM_BV.FISCAL_YEAR_NBR,DATE_DIM_BV.FISCAL_YEAR_START_DT,DATE_DIM_BV.FISCAL_YEAR_END_DT,DATE_DIM_BV.FISCAL_DAYS_IN_QUARTER_QTY,DATE_DIM_BV.FISCAL_DAYS_IN_YEAR_QTY,DATE_DIM_BV.FISCAL_DAY_IN_PERIOD_NBR,DATE_DIM_BV.FISCAL_PERIOD_NBR,DATE_DIM_BV.FISCAL_QUARTER_NBR,DATE_DIM_BV.FISCAL_QUARTER_START_DT,DATE_DIM_BV.FISCAL_QUARTER_END_DT,DATE_DIM_BV.FISCAL_PERIOD_START_DT,DATE_DIM_BV.FISCAL_PERIOD_END_DT,DATE_DIM_BV.FISCAL_DAYS_IN_PERIOD_QTY,DATE_DIM_BV.FISCAL_WEEKS_IN_PERIOD_QTY,DATE_DIM_BV.FISCAL_WEEKS_IN_YEAR_QTY,DATE_DIM_BV.FISCAL_WEEK_NBR,DATE_DIM_BV.FISCAL_WEEKS_IN_QUARTER_QTY,DATE_DIM_BV.FISCAL_WEEK_START_DT,DATE_DIM_BV.FISCAL_WEEK_END_DT,DATE_DIM_BV.FISCAL_DAY_IN_WEEK_NBR,DATE_DIM_BV.FISCAL_COMPARABLE_DT,DATE_DIM_BV.CALENDAR_COMPARABLE_DT,DATE_DIM_BV.CALENDAR_COMPARABLE_START_DT,DATE_DIM_BV.CALENDAR_COMPARABLE_END_DT,DATE_DIM_BV.CALENDAR_COMPARABLE_DAYS_IN_YEAR_QTY,DATE_DIM_BV.CALENDAR_COMPARABLE_IN_YEAR_NBR,DATE_DIM_BV.CALENDAR_COMPARABLE_DAYS_IN_PERIOD_QTY,DATE_DIM_BV.CALENDAR_COMPARABLE_QUARTER_NBR,DATE_DIM_BV.CALENDAR_COMPARABLE_QUARTER_START_DT,DATE_DIM_BV.CALENDAR_COMPARABLE_QUARTER_END_DT,DATE_DIM_BV.CALENDAR_COMPARABLE_PERIOD_START_DT,DATE_DIM_BV.CALENDAR_COMPARABLE_PERIOD_END_DT,DATE_DIM_BV.CALENDAR_COMPARABLE_WEEK_START_DT,DATE_DIM_BV.CALENDAR_COMPARABLE_WEEK_END_DT,DATE_DIM_BV.CALENDAR_COMPARABLE_DAY_IN_WEEK_NBR,DATE_DIM_BV.BRAND_ID,DATE_DIM_BV.SOURCE_SYSTEM_NM,DATE_DIM_BV.LOAD_ID,DATE_DIM_BV.LOAD_DTTM,DATE_DIM_BV.UPDATE_ID,DATE_DIM_BV.UPDATE_DTTM
FROM IDS_DEV.INT_REF_BV.DATE_DIM_BV ;
create view IF NOT EXISTS DATE_HOLIDAY_V(
	DATE_KEY,
	CALENDAR_DT COMMENT 'Calendar Date is the actual Day, Month, and Year for a given day.',
	DATE_DISPLAY_NM COMMENT 'Current Day in date format ',
	CALENDAR_YEAR_NBR COMMENT 'Current Year in 4 digit  Number format ',
	CALENDAR_DAY_IN_YEAR_NBR COMMENT 'Day number for the calendar Year',
	CALENDAR_MONTH_NBR COMMENT 'Current Month number',
	CALENDAR_MONTH_NM COMMENT 'Name of the current Month',
	CALENDAR_DAYS_IN_YEAR_QTY COMMENT 'Total Number of days in calendar Year',
	CALENDAR_DAY_NM COMMENT 'Calendar Day Name ',
	CALENDAR_YEAR_START_DT COMMENT 'Start Date for the current Calendar',
	CALENDAR_YEAR_END_DT COMMENT 'End Date for the current Calendar',
	CALENDAR_QUARTER_NBR,
	CALENDAR_QUARTER_NM,
	CALENDAR_QUARTER_START_DT,
	CALENDAR_QUARTER_END_DT,
	CALENDAR_DAYS_IN_QUARTER_QTY COMMENT 'Number of days in Calendar quarter',
	CALENDAR_MONTH_START_DT,
	CALENDAR_MONTH_END_DT,
	CALENDAR_DAYS_IN_MONTH_QTY,
	CALENDAR_WEEK_IN_YEAR_NBR,
	CALENDAR_WEEK_START_DT,
	CALENDAR_WEEK_END_DT,
	WEEKDAY_IND COMMENT 'Weeday Indicator specifies if a calendar day is considered during the week, typically Monday thru Friday, or on the Weekend, Saturday or Sunday. True- Date is weekday,False- Date is a weekend ',
	FISCAL_YEAR_NBR,
	FISCAL_YEAR_START_DT,
	FISCAL_YEAR_END_DT,
	FISCAL_DAYS_IN_QUARTER_QTY,
	FISCAL_DAYS_IN_YEAR_QTY COMMENT 'Fiscal Days in Year Quantity',
	FISCAL_DAY_IN_PERIOD_NBR COMMENT 'Day number in Fiscal period',
	FISCAL_PERIOD_NBR COMMENT 'Fiscal Period Number ',
	FISCAL_QUARTER_NBR,
	FISCAL_QUARTER_START_DT,
	FISCAL_QUARTER_END_DT,
	FISCAL_PERIOD_START_DT,
	FISCAL_PERIOD_END_DT,
	FISCAL_DAYS_IN_PERIOD_QTY,
	FISCAL_WEEKS_IN_PERIOD_QTY,
	FISCAL_WEEKS_IN_YEAR_QTY,
	FISCAL_WEEK_NBR,
	FISCAL_WEEKS_IN_QUARTER_QTY,
	FISCAL_WEEK_START_DT,
	FISCAL_WEEK_END_DT,
	FISCAL_DAY_IN_WEEK_NBR,
	FISCAL_COMPARABLE_DT COMMENT 'Fiscal Comparable Date',
	CALENDAR_COMPARABLE_DT COMMENT 'Prior Year Calendar comp Date( the date is -364) ',
	CALENDAR_COMPARABLE_START_DT,
	CALENDAR_COMPARABLE_END_DT,
	CALENDAR_COMPARABLE_DAYS_IN_YEAR_QTY,
	CALENDAR_COMPARABLE_IN_YEAR_NBR,
	CALENDAR_COMPARABLE_DAYS_IN_PERIOD_QTY,
	CALENDAR_COMPARABLE_QUARTER_NBR,
	CALENDAR_COMPARABLE_QUARTER_START_DT COMMENT 'Comparable Calendar Quarter Start Date is the ',
	CALENDAR_COMPARABLE_QUARTER_END_DT COMMENT 'Comparable Calendar Quarter End Date',
	CALENDAR_COMPARABLE_PERIOD_START_DT,
	CALENDAR_COMPARABLE_PERIOD_END_DT,
	CALENDAR_COMPARABLE_WEEK_START_DT,
	CALENDAR_COMPARABLE_WEEK_END_DT,
	CALENDAR_COMPARABLE_DAY_IN_WEEK_NBR,
	BRAND_ID,
	SOURCE_SYSTEM_NM,
	LOAD_ID COMMENT 'This is the User Identifier of the Person or Process that Loaded the Table',
	LOAD_DTTM COMMENT 'The Date/Datetime the Record was Inserted',
	UPDATE_ID COMMENT 'This is the User Identifier of the Person or Process that Updated the Table',
	UPDATE_DTTM COMMENT 'The Date/Datetime the Record was Updated',
	HOLIDAY_IND,
	HOLIDAY_QTY,
	HOLIDAY_LIST_NM COMMENT 'Holiday List Name is a comma delimeted list of holidays for a given day. For example, Lent, Good Friday.'
) COMMENT='Date Holidays Dim View is the date dim enhanced with a concatenated list of holidays.'
 as 
SELECT Date_Dim_V_To_Date_Holidays_Dim_V.DATE_KEY,Date_Dim_V_To_Date_Holidays_Dim_V.CALENDAR_DT,Date_Dim_V_To_Date_Holidays_Dim_V.DATE_DISPLAY_NM,Date_Dim_V_To_Date_Holidays_Dim_V.CALENDAR_YEAR_NBR,Date_Dim_V_To_Date_Holidays_Dim_V.CALENDAR_DAY_IN_YEAR_NBR,Date_Dim_V_To_Date_Holidays_Dim_V.CALENDAR_MONTH_NBR,Date_Dim_V_To_Date_Holidays_Dim_V.CALENDAR_MONTH_NM,Date_Dim_V_To_Date_Holidays_Dim_V.CALENDAR_DAYS_IN_YEAR_QTY,Date_Dim_V_To_Date_Holidays_Dim_V.CALENDAR_DAY_NM,Date_Dim_V_To_Date_Holidays_Dim_V.CALENDAR_YEAR_START_DT,Date_Dim_V_To_Date_Holidays_Dim_V.CALENDAR_YEAR_END_DT,Date_Dim_V_To_Date_Holidays_Dim_V.CALENDAR_QUARTER_NBR,Date_Dim_V_To_Date_Holidays_Dim_V.CALENDAR_QUARTER_NM,Date_Dim_V_To_Date_Holidays_Dim_V.CALENDAR_QUARTER_START_DT,Date_Dim_V_To_Date_Holidays_Dim_V.CALENDAR_QUARTER_END_DT,Date_Dim_V_To_Date_Holidays_Dim_V.CALENDAR_DAYS_IN_QUARTER_QTY,Date_Dim_V_To_Date_Holidays_Dim_V.CALENDAR_MONTH_START_DT,Date_Dim_V_To_Date_Holidays_Dim_V.CALENDAR_MONTH_END_DT,Date_Dim_V_To_Date_Holidays_Dim_V.CALENDAR_DAYS_IN_MONTH_QTY,Date_Dim_V_To_Date_Holidays_Dim_V.CALENDAR_WEEK_IN_YEAR_NBR,Date_Dim_V_To_Date_Holidays_Dim_V.CALENDAR_WEEK_START_DT,Date_Dim_V_To_Date_Holidays_Dim_V.CALENDAR_WEEK_END_DT,Date_Dim_V_To_Date_Holidays_Dim_V.WEEKDAY_IND,Date_Dim_V_To_Date_Holidays_Dim_V.FISCAL_YEAR_NBR,Date_Dim_V_To_Date_Holidays_Dim_V.FISCAL_YEAR_START_DT,Date_Dim_V_To_Date_Holidays_Dim_V.FISCAL_YEAR_END_DT,Date_Dim_V_To_Date_Holidays_Dim_V.FISCAL_DAYS_IN_QUARTER_QTY,Date_Dim_V_To_Date_Holidays_Dim_V.FISCAL_DAYS_IN_YEAR_QTY,Date_Dim_V_To_Date_Holidays_Dim_V.FISCAL_DAY_IN_PERIOD_NBR,Date_Dim_V_To_Date_Holidays_Dim_V.FISCAL_PERIOD_NBR,Date_Dim_V_To_Date_Holidays_Dim_V.FISCAL_QUARTER_NBR,Date_Dim_V_To_Date_Holidays_Dim_V.FISCAL_QUARTER_START_DT,Date_Dim_V_To_Date_Holidays_Dim_V.FISCAL_QUARTER_END_DT,Date_Dim_V_To_Date_Holidays_Dim_V.FISCAL_PERIOD_START_DT,Date_Dim_V_To_Date_Holidays_Dim_V.FISCAL_PERIOD_END_DT,Date_Dim_V_To_Date_Holidays_Dim_V.FISCAL_DAYS_IN_PERIOD_QTY,Date_Dim_V_To_Date_Holidays_Dim_V.FISCAL_WEEKS_IN_PERIOD_QTY,Date_Dim_V_To_Date_Holidays_Dim_V.FISCAL_WEEKS_IN_YEAR_QTY,Date_Dim_V_To_Date_Holidays_Dim_V.FISCAL_WEEK_NBR,Date_Dim_V_To_Date_Holidays_Dim_V.FISCAL_WEEKS_IN_QUARTER_QTY,Date_Dim_V_To_Date_Holidays_Dim_V.FISCAL_WEEK_START_DT,Date_Dim_V_To_Date_Holidays_Dim_V.FISCAL_WEEK_END_DT,Date_Dim_V_To_Date_Holidays_Dim_V.FISCAL_DAY_IN_WEEK_NBR,Date_Dim_V_To_Date_Holidays_Dim_V.FISCAL_COMPARABLE_DT,Date_Dim_V_To_Date_Holidays_Dim_V.CALENDAR_COMPARABLE_DT,Date_Dim_V_To_Date_Holidays_Dim_V.CALENDAR_COMPARABLE_START_DT,Date_Dim_V_To_Date_Holidays_Dim_V.CALENDAR_COMPARABLE_END_DT,Date_Dim_V_To_Date_Holidays_Dim_V.CALENDAR_COMPARABLE_DAYS_IN_YEAR_QTY,Date_Dim_V_To_Date_Holidays_Dim_V.CALENDAR_COMPARABLE_IN_YEAR_NBR,Date_Dim_V_To_Date_Holidays_Dim_V.CALENDAR_COMPARABLE_DAYS_IN_PERIOD_QTY,Date_Dim_V_To_Date_Holidays_Dim_V.CALENDAR_COMPARABLE_QUARTER_NBR,Date_Dim_V_To_Date_Holidays_Dim_V.CALENDAR_COMPARABLE_QUARTER_START_DT,Date_Dim_V_To_Date_Holidays_Dim_V.CALENDAR_COMPARABLE_QUARTER_END_DT,Date_Dim_V_To_Date_Holidays_Dim_V.CALENDAR_COMPARABLE_PERIOD_START_DT,Date_Dim_V_To_Date_Holidays_Dim_V.CALENDAR_COMPARABLE_PERIOD_END_DT,Date_Dim_V_To_Date_Holidays_Dim_V.CALENDAR_COMPARABLE_WEEK_START_DT,Date_Dim_V_To_Date_Holidays_Dim_V.CALENDAR_COMPARABLE_WEEK_END_DT,Date_Dim_V_To_Date_Holidays_Dim_V.CALENDAR_COMPARABLE_DAY_IN_WEEK_NBR,Date_Dim_V_To_Date_Holidays_Dim_V.BRAND_ID,Date_Dim_V_To_Date_Holidays_Dim_V.SOURCE_SYSTEM_NM,Date_Dim_V_To_Date_Holidays_Dim_V.LOAD_ID,Date_Dim_V_To_Date_Holidays_Dim_V.LOAD_DTTM,Date_Dim_V_To_Date_Holidays_Dim_V.UPDATE_ID,Date_Dim_V_To_Date_Holidays_Dim_V.UPDATE_DTTM,NVL(Holiday_Names_Dim_V_To_Date_Holidays_Dim_V.HOLIDAY_IND, FALSE),NVL(Holiday_Names_Dim_V_To_Date_Holidays_Dim_V.HOLIDAY_QTY,0),Holiday_Names_Dim_V_To_Date_Holidays_Dim_V.HOLIDAY_LIST_NM
FROM IDS_DEV.INT_REF_BV.DATE_DIM_BV Date_Dim_V_To_Date_Holidays_Dim_V,HOLIDAY_LIST_V Holiday_Names_Dim_V_To_Date_Holidays_Dim_V
		WHERE Date_Dim_V_To_Date_Holidays_Dim_V.DATE_KEY = Holiday_Names_Dim_V_To_Date_Holidays_Dim_V.DATE_KEY (+);
create view IF NOT EXISTS HOLIDAY_DIM_V(
	HOLIDAY_KEY,
	DATE_KEY,
	BRAND_ID COMMENT 'campaignInspire recognized brand id. irb when applied to all brands ',
	HOLIDAY_NM COMMENT 'The Name of the Holiday',
	HOLIDAY_DESC COMMENT 'Name of the objective Holiday.',
	SOURCE_SYSTEM_NM COMMENT 'Inspire level project',
	LOAD_ID COMMENT 'This is the User Identifier of the Person or Process that Loaded the Table',
	LOAD_DTTM COMMENT 'The Date/Datetime the Record was Inserted',
	UPDATE_ID COMMENT 'This is the User Identifier of the Person or Process that Updated the Table',
	UPDATE_DTTM COMMENT 'The Date/Datetime the Record was Updated'
) as 
SELECT HOLIDAY_DIM_BV.HOLIDAY_KEY,HOLIDAY_DIM_BV.DATE_KEY,HOLIDAY_DIM_BV.BRAND_ID,HOLIDAY_DIM_BV.HOLIDAY_NM,HOLIDAY_DIM_BV.HOLIDAY_DESC,HOLIDAY_DIM_BV.SOURCE_SYSTEM_NM,HOLIDAY_DIM_BV.LOAD_ID,HOLIDAY_DIM_BV.LOAD_DTTM,HOLIDAY_DIM_BV.UPDATE_ID,HOLIDAY_DIM_BV.UPDATE_DTTM
FROM IDS_DEV.INT_REF_BV.HOLIDAY_DIM_BV ;
create view IF NOT EXISTS HOLIDAY_LIST_V(
	DATE_KEY,
	HOLIDAY_QTY COMMENT 'Holiday Quantity specifies the number of holidays for a given day.',
	HOLIDAY_IND COMMENT 'Holiday Indicator specifies that a given date has a holiday that falls on it.',
	HOLIDAY_LIST_NM COMMENT 'Holiday List Name is a comma delimeted list of holidays for a given day. For example, Lent, Good Friday.',
	HOLIDAY_LIST_LAST_UPDATE_DTTM COMMENT 'Holiday List Last Update Datetime is the latest last update datetime for a given calendar day.'
) COMMENT='Date Holiday View is a displays a concatenated list of holidays for each date.'
 as 
SELECT HOLIDAY_DIM_BV.DATE_KEY,count(Holiday_nm),MAX(iff(HOLIDAY_NM IS NOT NULL,True,False)),listagg(HOLIDAY_NM, ', '),MAX(UPDATE_DTTM)
FROM IDS_DEV.INT_REF_BV.HOLIDAY_DIM_BV 
		GROUP BY date_key;
create view IF NOT EXISTS STORE_SCD_V(
	STORE_KEY,
	STORE_ID,
	BRAND_ID,
	SITE_ID,
	OWNER_ID,
	FRANCHISEE_IND,
	STORE_NM,
	ADDRESS_1_TXT,
	ADDRESS_2_TXT,
	ADDRESS_3_TXT,
	CITY_NM,
	COUNTRY_NM,
	STATE_NM,
	PROVINCE_NM,
	ZIP_CD,
	STORE_EMAIL_TXT,
	STORE_PHONE_NBR,
	DIVISION_NBR,
	OPEN_DT,
	CLOSURE_DT,
	LEGAL_NM,
	FRANCHISEE_NM,
	DIVISION_NM,
	TEMP_CLOSED_DT,
	REOPEN_DT,
	TEMP_CLOSURE_REASON_TXT,
	REMODEL_LEVEL_TYP,
	REMODEL_ACTIVITY_TYP,
	REMODEL_PROGRAM_TYP,
	CONSTRUCTION_STATUS_CD,
	PROJECTED_UNDER_CONSTRUCTION_DT,
	UNDER_CONSTRUCTION_DT,
	COMPLETED_DT,
	CONSTRUCTION_DUE_DT,
	DMA_CD,
	DMA_NM,
	DMA_SOURCE_NM,
	TIME_ZN,
	LATITUDE_NBR,
	LONGITUDE_NBR,
	FACILITY_TYP,
	BUILDING_TYP,
	PARKING_CNT,
	SEAT_CNT,
	OWNERSHIP_TYP,
	BREAKFAST_IND,
	DRIVETHRU_IND,
	BLDG_SQFT_NBR,
	CDM_LOAD_DT,
	EFFECTIVE_BEGIN_DT,
	EFFECTIVE_END_DT,
	CURRENT_IND,
	LOAD_ID,
	LOAD_DTTM,
	UPDATE_ID,
	UPDATE_DTTM
) as 
SELECT 
	STORE_KEY,
	STORE_ID,
	BRAND_ID,
	SITE_ID,
	OWNER_ID,
	FRANCHISEE_IND,
	STORE_NM,
	ADDRESS_1_TXT,
	ADDRESS_2_TXT,
	ADDRESS_3_TXT,
	CITY_NM,
	COUNTRY_NM,
	STATE_NM,
	PROVINCE_NM,
	ZIP_CD,
	STORE_EMAIL_TXT,
	STORE_PHONE_NBR,
	DIVISION_NBR,
	OPEN_DT,
	CLOSURE_DT,
	LEGAL_NM,
	FRANCHISEE_NM,
	DIVISION_NM,
	TEMP_CLOSED_DT,
	REOPEN_DT,
	TEMP_CLOSURE_REASON_TXT,
	REMODEL_LEVEL_TYP,
	REMODEL_ACTIVITY_TYP,
	REMODEL_PROGRAM_TYP,
	CONSTRUCTION_STATUS_CD,
	PROJECTED_UNDER_CONSTRUCTION_DT,
	UNDER_CONSTRUCTION_DT,
	COMPLETED_DT,
	CONSTRUCTION_DUE_DT,
	DMA_CD,
	DMA_NM,
	DMA_SOURCE_NM,
	TM_ZONE_NM AS TIME_ZN,
	LATITUDE_NBR,
	LONGITUDE_NBR,
	FACILITY_TYP,
	BUILDING_TYP,
	PARKING_CNT,
	SEAT_CNT,
	OWNERSHIP_TYP,
	BREAKFAST_IND,
	DRIVETHRU_IND,
	BLDG_SQFT_NBR,
	CDM_LOAD_DT,
	EFFECTIVE_BEGIN_DT,
    EFFECTIVE_END_DT,
    CURRENT_IND,
	LOAD_ID,
	LOAD_DTTM,
	UPDATE_ID,
	UPDATE_DTTM
FROM IDM_DEV.COREDIM.RESTAURANT_SCD_DIM
;
create view IF NOT EXISTS STORE_V(
	STORE_KEY,
	STORE_ID,
	BRAND_ID,
	SITE_ID,
	OWNER_ID,
	FRANCHISEE_IND,
	STORE_NM,
	ADDRESS_1_TXT,
	ADDRESS_2_TXT,
	ADDRESS_3_TXT,
	CITY_NM,
	COUNTRY_NM,
	STATE_NM,
	PROVINCE_NM,
	ZIP_CD,
	STORE_EMAIL_TXT,
	STORE_PHONE_NBR,
	DIVISION_NBR,
	OPEN_DT,
	CLOSURE_DT,
	LEGAL_NAME,
	FRANCHISEE_NAME,
	DIVISION_NAME,
	TEMP_CLOSED_DT,
	REOPEN_DT,
	TEMP_CLOSURE_REASON_TXT,
	REMODEL_LEVEL_TYP,
	REMODEL_ACTIVITY_TYP,
	REMODEL_PROGRAM_TYP,
	CONSTRUCTION_STATUS_CD,
	PROJECTED_UNDER_CONSTRUCTION_DT,
	UNDER_CONSTRUCTION_DT,
	COMPLETED_DT,
	CONSTRUCTION_DUE_DT,
	DMA_CD,
	DMA_NM,
	DMA_SOURCE_NM,
	TIME_ZN,
	LATITUDE_NBR,
	LONGITUDE_NBR,
	FACILITY_TYP,
	BUILDING_TYP,
	PARKING_CNT,
	SEAT_CNT,
	OWNERSHIP_TYP,
	BREAKFAST_IND,
	DRIVETHRU_IND,
	BLDG_SQFT_NBR,
	CDM_LOAD_DT,
	LOAD_ID,
	LOAD_DTTM,
	UPDATE_ID,
	UPDATE_DTTM
) as 
SELECT 
	STORE_KEY,
	STORE_ID,
	BRAND_ID,
	SITE_ID,
	OWNER_ID,
	FRANCHISEE_IND,
	STORE_NM,
	ADDRESS_1_TXT,
	ADDRESS_2_TXT,
	ADDRESS_3_TXT,
	CITY_NM,
	COUNTRY_NM,
	STATE_NM,
	PROVINCE_NM,
	ZIP_CD,
	STORE_EMAIL_TXT,
	STORE_PHONE_NBR,
	DIVISION_NBR,
	OPEN_DT,
	CLOSURE_DT,
	LEGAL_NM,
	FRANCHISEE_NM,
	DIVISION_NM,
	TEMP_CLOSED_DT,
	REOPEN_DT,
	TEMP_CLOSURE_REASON_TXT,
	REMODEL_LEVEL_TYP,
	REMODEL_ACTIVITY_TYP,
	REMODEL_PROGRAM_TYP,
	CONSTRUCTION_STATUS_CD,
	PROJECTED_UNDER_CONSTRUCTION_DT,
	UNDER_CONSTRUCTION_DT,
	COMPLETED_DT,
	CONSTRUCTION_DUE_DT,
	DMA_CD,
	DMA_NM,
	DMA_SOURCE_NM,
	TM_ZONE_NM AS TIME_ZN,
	LATITUDE_NBR,
	LONGITUDE_NBR,
	FACILITY_TYP,
	BUILDING_TYP,
	PARKING_CNT,
	SEAT_CNT,
	OWNERSHIP_TYP,
	BREAKFAST_IND,
	DRIVETHRU_IND,
	BLDG_SQFT_NBR,
	CDM_LOAD_DT,
	LOAD_ID,
	LOAD_DTTM,
	UPDATE_ID,
	UPDATE_DTTM
FROM IDM_DEV.COREDIM.RESTAURANT_SCD_DIM
WHERE CURRENT_IND;
create view IF NOT EXISTS TEMP_TEST_MADA(
	BRAND_ID,
	STORE_ID,
	FISCAL_PERIOD_START_DT,
	FISCAL1YRCOMP_PERIOD,
	CALENDAR1YRCOMP_PERIOD,
	CALENDAR2YRCOMP_PERIOD,
	CALENDAR3YRCOMP_PERIOD,
	FISC_1Y_SALES,
	FISC_1Y_TRANS,
	CAL_1Y_SALES,
	CAL_1Y_TRANS,
	CAL_2Y_SALES,
	CAL_2Y_TRANS,
	CAL_3Y_SALES,
	CAL_3Y_TRANS,
	FISCAL_QUARTER_START_DT,
	FISCAL1YRCOMP_QUARTER,
	CALENDAR1YRCOMP_QUARTER,
	CALENDAR2YRCOMP_QUARTER,
	CALENDAR3YRCOMP_QUARTER
) as 
WITH CY_DT AS (
select DATE_ID,  
FISCAL_YEAR_START_DT,
FISCAL_QUARTER_START_DT,
FISCAL_PERIOD_START_DT,
FISCAL1YRCOMP_PERIOD,   
CALENDAR1YRCOMP_PERIOD,
CALENDAR2YRCOMP_PERIOD,
CALENDAR3YRCOMP_PERIOD 
from IDS_DEV.INT_REF.VW_COMP_CAL_DATE_3YR 
where DATE_ID = cast('2021-12-20' as date)
),
LY_DT AS (
SELECT DISTINCT 
DT.FISCAL_QUARTER_START_DT,
DT.FISCAL_PERIOD_START_DT,
DT.FISCAL1YRCOMP_QUARTER, 
DT.FISCAL1YRCOMP_PERIOD,
DT.CALENDAR1YRCOMP_QUARTER,
DT.CALENDAR1YRCOMP_PERIOD,
DT.CALENDAR2YRCOMP_QUARTER,
DT.CALENDAR2YRCOMP_PERIOD,
DT.CALENDAR3YRCOMP_QUARTER,
DT.CALENDAR3YRCOMP_PERIOD
FROM
IDS_DEV.INT_REF.VW_COMP_CAL_DATE_3YR DT
INNER JOIN CY_DT
ON DT.FISCAL_YEAR_START_DT = CY_DT.FISCAL_YEAR_START_DT
AND DT.FISCAL_PERIOD_START_DT <= CY_DT.FISCAL_PERIOD_START_DT
AND DT.FISCAL1YRCOMP_PERIOD <= CY_DT.FISCAL1YRCOMP_PERIOD
AND DT.CALENDAR1YRCOMP_PERIOD <= CY_DT.CALENDAR1YRCOMP_PERIOD
AND DT.CALENDAR2YRCOMP_PERIOD <= CY_DT.CALENDAR2YRCOMP_PERIOD
AND DT.CALENDAR3YRCOMP_PERIOD <= CY_DT.CALENDAR3YRCOMP_PERIOD
),
DT AS (
SELECT 
FISCAL_QUARTER_START_DT,
FISCAL_PERIOD_START_DT, 
FISCAL1YRCOMP_QUARTER, 
FISCAL1YRCOMP_PERIOD,
CALENDAR1YRCOMP_QUARTER,
CALENDAR1YRCOMP_PERIOD,
CALENDAR2YRCOMP_QUARTER,
CALENDAR2YRCOMP_PERIOD,
CALENDAR3YRCOMP_QUARTER,
CALENDAR3YRCOMP_PERIOD,
ROW_NUMBER() OVER (PARTITION BY FISCAL1YRCOMP_PERIOD, FISCAL1YRCOMP_QUARTER                 
                   ORDER BY FISCAL1YRCOMP_PERIOD, FISCAL1YRCOMP_QUARTER DESC) AS ROW_NUM             
from LY_DT
QUALIFY ROW_NUM = 1)

SELECT 
    CR.BRAND_ID,
    CR.STORE_ID,
    DT.FISCAL_PERIOD_START_DT,
    DT.FISCAL1YRCOMP_PERIOD,
    DT.CALENDAR1YRCOMP_PERIOD,
    DT.CALENDAR2YRCOMP_PERIOD,
    DT.CALENDAR3YRCOMP_PERIOD,
    (NVL(FISC_1Y.COMP_SALES,0)) AS FISC_1Y_SALES,
    (NVL(FISC_1Y.COMP_TRANS,0)) AS FISC_1Y_TRANS,
    (NVL(CAL_1Y.COMP_SALES,0)) AS CAL_1Y_SALES,
    (NVL(CAL_1Y.COMP_TRANS,0)) AS CAL_1Y_TRANS,
    (NVL(CAL_2Y.COMP_SALES,0)) AS CAL_2Y_SALES,
    (NVL(CAL_2Y.COMP_TRANS,0)) AS CAL_2Y_TRANS,
    (NVL(CAL_3Y.COMP_SALES,0)) AS CAL_3Y_SALES,
    (NVL(CAL_3Y.COMP_TRANS,0)) AS CAL_3Y_TRANS,
    CR.FISCAL_QUARTER_START_DT,
    DT.FISCAL1YRCOMP_QUARTER,
    DT.CALENDAR1YRCOMP_QUARTER,
    DT.CALENDAR2YRCOMP_QUARTER,
    DT.CALENDAR3YRCOMP_QUARTER
FROM 
table(IDH_DEV.SALES.FLASH_SUMMARY_COMP_PAST_PERIODS(cast('2021-12-20' as date))) CR
INNER JOIN DT
ON DT.FISCAL_PERIOD_START_DT = CR.AGG_START_DT
AND CR.STORE_ID = '07272'
LEFT OUTER JOIN 
TABLE(IDH_DEV.SALES.FLASH_SUMMARY_COMP_PAST_PERIODS((select FISCAL1YRCOMP_DATEID 
                                                        from IDS_DEV.INT_REF.VW_COMP_CAL_DATE_3YR 
                                                        where date_id = cast('2021-12-20' as date))))  FISC_1Y
                                          
ON  CR.STORE_ID = FISC_1Y.STORE_ID 
AND CR.BRAND_ID = FISC_1Y.BRAND_ID
AND DT.FISCAL1YRCOMP_PERIOD = FISC_1Y.AGG_START_DT
AND DT.FISCAL1YRCOMP_QUARTER = FISC_1Y.FISCAL_QUARTER_START_DT
LEFT OUTER JOIN 
TABLE(IDH_DEV.SALES.FLASH_SUMMARY_COMP_PAST_PERIODS((select CALENDAR1YRCOMP_DATEID 
                                                        from IDS_DEV.INT_REF.VW_COMP_CAL_DATE_3YR 
                                                        where date_id = cast('2021-12-20' as date))))  CAL_1Y
ON  CR.STORE_ID = CAL_1Y.STORE_ID 
AND CR.BRAND_ID = CAL_1Y.BRAND_ID
AND DT.CALENDAR1YRCOMP_PERIOD = CAL_1Y.AGG_START_DT
AND DT.CALENDAR1YRCOMP_QUARTER = CAL_1Y.FISCAL_QUARTER_START_DT
LEFT OUTER JOIN 
TABLE(IDH_DEV.SALES.FLASH_SUMMARY_COMP_PAST_PERIODS((select CALENDAR2YRCOMP_DATEID 
                                                        from IDS_DEV.INT_REF.VW_COMP_CAL_DATE_3YR 
                                                        where date_id = cast('2021-12-20' as date))))  CAL_2Y
ON  CR.STORE_ID = CAL_2Y.STORE_ID 
AND CR.BRAND_ID = CAL_2Y.BRAND_ID
AND DT.CALENDAR2YRCOMP_PERIOD = CAL_2Y.AGG_START_DT
AND DT.CALENDAR2YRCOMP_QUARTER = CAL_2Y.FISCAL_QUARTER_START_DT
LEFT OUTER JOIN 
TABLE(IDH_DEV.SALES.FLASH_SUMMARY_COMP_PAST_PERIODS((select CALENDAR3YRCOMP_DATEID 
                                                        from IDS_DEV.INT_REF.VW_COMP_CAL_DATE_3YR 
                                                        where date_id = cast('2021-12-20' as date))))  CAL_3Y
ON  CR.STORE_ID = CAL_3Y.STORE_ID 
AND CR.BRAND_ID = CAL_3Y.BRAND_ID
AND DT.CALENDAR3YRCOMP_PERIOD = CAL_3Y.AGG_START_DT
AND DT.CALENDAR3YRCOMP_QUARTER = CAL_3Y.FISCAL_QUARTER_START_DT

WHERE 
CR.NET_SALES IS NOT NULL
AND (CR.comp_sales IS NULL or CR.comp_sales = 0
OR CR.CLOSED_BEFORE_PERIOD_END_FLAG);
create view IF NOT EXISTS WEATHER_FORECAST_V(
	DATE_KEY,
	TIME_KEY,
	DATE_TIME_UNIX_NBR,
	CITY_ID,
	CITY_NM,
	CITY_LAT_NBR,
	CITY_LONG_NBR,
	STORE_LAT_NBR,
	STORE_LONG_NBR,
	COUNTRY_CD,
	TIME_ZN,
	DAY_TEMP_NBR,
	MIN_DAY_TEMP_NBR,
	MAX_DAY_TEMP_NBR,
	NIGHT_TEMP_NBR,
	EVENING_TEMP_NBR,
	MORNING_TEMP_NBR,
	FEELSLIKE_DAY_TEMP_NBR,
	FEELSLIKE_NIGHT_TEMP_NBR,
	FEELSLIKE_EVE_TEMP_NBR,
	FEELSLIKE_MORN_TEMP_NBR,
	PRESSURE_NBR,
	HUMIDITY_PCT,
	WEATHER_ID,
	WEATHER_ICON_ID,
	WEATHER_GROUP_NM,
	WEATHER_DESC,
	WIND_SPEED_NBR,
	WIND_DEGREE,
	CLOUDS_PCT,
	RAIN_VOL_NBR,
	SNOWL_VOL_NBR,
	BRAND_ID,
	SOURCE_SYSTEM_NM,
	CDM_LOAD_DT,
	LOAD_TYP,
	LOAD_ID,
	LOAD_DTTM
) as 
SELECT WEATHER_FORECAST_FACT.DATE_KEY,WEATHER_FORECAST_FACT.TIME_KEY,WEATHER_FORECAST_FACT.DATE_TIME_UNIX,WEATHER_FORECAST_FACT.CITY_ID,WEATHER_FORECAST_FACT.CITY_NAME,WEATHER_FORECAST_FACT.CITY_LAT,WEATHER_FORECAST_FACT.CITY_LONG,WEATHER_FORECAST_FACT.STORE_LAT,WEATHER_FORECAST_FACT.STORE_LONG,WEATHER_FORECAST_FACT.COUNTRY_CD,WEATHER_FORECAST_FACT.TIMEZONE,WEATHER_FORECAST_FACT.DAY_TEMP,WEATHER_FORECAST_FACT.MIN_DAY_TEMP,WEATHER_FORECAST_FACT.MAX_DAY_TEMP,WEATHER_FORECAST_FACT.NIGHT_TEMP,WEATHER_FORECAST_FACT.EVENING_TEMP,WEATHER_FORECAST_FACT.MORNING_TEMP,WEATHER_FORECAST_FACT.FEELSLIKE_DAY_TEMP,WEATHER_FORECAST_FACT.FEELSLIKE_NIGHT_TEMP,WEATHER_FORECAST_FACT.FEELSLIKE_EVE_TEMP,WEATHER_FORECAST_FACT.FEELSLIKE_MORN_TEMP,WEATHER_FORECAST_FACT.PRESSURE,WEATHER_FORECAST_FACT.HUMIDITY_PCT,WEATHER_FORECAST_FACT.WEATHER_ID,WEATHER_FORECAST_FACT.WEATHER_ICON_ID,WEATHER_FORECAST_FACT.WEATHER_GROUP,WEATHER_FORECAST_FACT.WEATHER_DESC,WEATHER_FORECAST_FACT.WIND_SPEED,WEATHER_FORECAST_FACT.WIND_DEGREE,WEATHER_FORECAST_FACT.CLOUDS_PCT,WEATHER_FORECAST_FACT.RAIN_VOL,WEATHER_FORECAST_FACT.SNOWL_VOL,WEATHER_FORECAST_FACT.BRAND_ID,WEATHER_FORECAST_FACT.SOURCE,WEATHER_FORECAST_FACT.CDM_LOAD_DATE,WEATHER_FORECAST_FACT.LOAD_TYPE,WEATHER_FORECAST_FACT.LOAD_ID,WEATHER_FORECAST_FACT.LOAD_DTTM
FROM POLARIS_DEV.SHDM.WEATHER_FORECAST_FACT;
create view IF NOT EXISTS WEATHER_HR_V(
	DATE_KEY,
	TIME_KEY,
	DATE_TIME_UNIX_NBR,
	CITY_ID,
	CITY_NM,
	CITY_LAT_NBR,
	CITY_LONG_NBR,
	TEMPERATURE_NBR,
	PRESSURE_NBR,
	HUMIDITY_PCT,
	WEATHER_ID,
	WEATHER_ICON_ID,
	WEATHER_GROUP_NM,
	WEATHER_DESC,
	WIND_SPEED_NBR,
	WIND_DEGREE_NBR,
	CLOUDS_PCT,
	RAIN_VOL_NBR,
	SNOWL_VOL_NBR,
	BRAND_ID,
	SOURCE_SYSTEM_NM,
	CDM_LOAD_DT,
	LOAD_TYP,
	LOAD_ID,
	LOAD_DTTM
) as 
SELECT WEATHER_HOURLY_FACT.DATE_KEY,WEATHER_HOURLY_FACT.TIME_KEY,WEATHER_HOURLY_FACT.DATE_TIME_UNIX,WEATHER_HOURLY_FACT.CITY_ID,WEATHER_HOURLY_FACT.CITY_NAME,WEATHER_HOURLY_FACT.CITY_LAT,WEATHER_HOURLY_FACT.CITY_LONG,WEATHER_HOURLY_FACT.TEMPERATURE,WEATHER_HOURLY_FACT.PRESSURE,WEATHER_HOURLY_FACT.HUMIDITY_PCT,WEATHER_HOURLY_FACT.WEATHER_ID,WEATHER_HOURLY_FACT.WEATHER_ICON_ID,WEATHER_HOURLY_FACT.WEATHER_GROUP,WEATHER_HOURLY_FACT.WEATHER_DESC,WEATHER_HOURLY_FACT.WIND_SPEED,WEATHER_HOURLY_FACT.WIND_DEGREE,WEATHER_HOURLY_FACT.CLOUDS_PCT,WEATHER_HOURLY_FACT.RAIN_VOL,WEATHER_HOURLY_FACT.SNOWL_VOL,WEATHER_HOURLY_FACT.BRAND_ID,WEATHER_HOURLY_FACT.SOURCE,WEATHER_HOURLY_FACT.CDM_LOAD_DATE,WEATHER_HOURLY_FACT.LOAD_TYPE,WEATHER_HOURLY_FACT.LOAD_ID,WEATHER_HOURLY_FACT.LOAD_DTTM
FROM POLARIS_DEV.SHDM.WEATHER_HOURLY_FACT;
CREATE FUNCTION IF NOT EXISTS CALCULATE_PERCENTAGE("X" NUMBER(38,0), "Y" NUMBER(38,0))
RETURNS NUMBER(5,1)
LANGUAGE SQL
AS '
  CASE 
    WHEN y = 0
    THEN 0
    ELSE 100 * ( x / y )
  END::DECIMAL(5,1)
';