
dag_id: "E2E_SALES_RECON_ORACLEGL_ADLS_TO_RDS"
dag_description: "Arbys Oracle GL data load from ADLS2 to RDS"
emails: ['udpfinanceengineeringpod@inspirebrands.com']
env : "DEV"
warehouse_id : "RA_PRCSSA_IRB_WH"
schema_id : "ARB"
file_format: "RDS_DEV.ARB.GENERAL_LEDGER_ARB_FILE_FORMAT"
pattern: ".*GL_SALES_JE_TO_UDP.*[.]csv"
snowflake_rds_database_name: "RDS_DEV"
stage_name: "@RDS_DEV.ARB.SALES_RECON_READ_ADLS2"