USE WAREHOUSE {{params.warehouse}};

SET ld_dt =  To_Date('{{params.load_dt}}');

COPY INTO @IDH_{{params.env}}.{{params.schema}}.stage_for_baskin_polled_sales/{{params.file_name}} 
from 
(
WITH FILTERED_REC AS (
  SELECT REST_ID
  FROM (
    SELECT "#PC_NUM" AS REST_ID,
           RANK() OVER (PARTITION BY "#PC_NUM", BRAND_CD, SALES_REPORT_FREQ ORDER BY LOAD_DTTM DESC) AS ROW_NUM
    FROM RDS_{{params.env}}.DUN.APC_SHOPINFO
    WHERE BRAND_CD = 'BR' AND SALES_REPORT_FREQ = 'Weekly'
  )
  WHERE ROW_NUM = 1
)
SELECT 
  'BRI' AS BRAND,
  TO_CHAR($ld_dt - DAYOFWEEK($ld_dt) - 8,'MM-DD-YYYY') AS REPORTING_PERIOD,
  OWNER_ID AS CUSTOMER_NUMBER, 
  FRANCHISEE_NAME AS CUSTOMER_NAME,
  LPAD(T.REST_ID,6,'0') AS UNIT,
  'USD' AS LOCAL_CURRENCY,
  SUM(DERIVED_NET_AMT) AS LOCAL_NET_SALES_RETAIL,
  SUM(TRANS_CNT) AS TRANSACTION_COUNT_RETAIL,
  SUM(DERIVED_GROSS_AMT) AS LOCAL_GROSS_SALES, 
  '' AS LOCAL_NET_SALES_WHOLESALE, 
  '' AS TRANSACTION_COUNT_WHOLESALE,
  'WEEKLY' AS REPORTING_FREQUENCY
FROM IDH_{{params.env}}.D_TRANS.TRANS T
INNER JOIN IDH_{{params.env}}.D_LOC.REST R 
ON T.REST_ID = R.REST_ID AND T.BRAND_ID = R.BRAND_ID
INNER JOIN FILTERED_REC FR
ON T.REST_ID = FR.REST_ID
WHERE T.BRAND_ID = 'bskn' 
  AND R.OWNERSHIP_TYPE = 'Franchised'
   --AND R.REST_ID = '355728'
  AND DAYOFWEEK($ld_dt) != 6
 AND 
    BUSINESS_DATE BETWEEN 
     $ld_dt - DAYOFWEEK($ld_dt) - 14       
    AND $ld_dt - DAYOFWEEK($ld_dt) - 8  
GROUP BY 
  T.BRAND_ID,
  OWNER_ID, 
  FRANCHISEE_NAME,
  T.REST_ID
UNION
SELECT 
  'BRI' AS BRAND,
  TO_CHAR($ld_dt - DAYOFWEEK($ld_dt) - 1,'MM-DD-YYYY') AS REPORTING_PERIOD,
  OWNER_ID AS CUSTOMER_NUMBER, 
  FRANCHISEE_NAME AS CUSTOMER_NAME,
  LPAD(T.REST_ID,6,'0') AS UNIT,
  'USD' AS LOCAL_CURRENCY,
  SUM(DERIVED_NET_AMT) AS LOCAL_NET_SALES_RETAIL,
  SUM(TRANS_CNT) AS TRANSACTION_COUNT_RETAIL,
  SUM(DERIVED_GROSS_AMT) AS LOCAL_GROSS_SALES, 
  '' AS LOCAL_NET_SALES_WHOLESALE, 
  '' AS TRANSACTION_COUNT_WHOLESALE,
  'WEEKLY' AS REPORTING_FREQUENCY
FROM IDH_{{params.env}}.D_TRANS.TRANS T
INNER JOIN IDH_{{params.env}}.D_LOC.REST R 
ON T.REST_ID = R.REST_ID AND T.BRAND_ID = R.BRAND_ID
INNER JOIN FILTERED_REC FR
ON T.REST_ID = FR.REST_ID
WHERE T.BRAND_ID = 'bskn'  
AND R.OWNERSHIP_TYPE = 'Franchised'
 AND 
    BUSINESS_DATE BETWEEN  $ld_dt - DAYOFWEEK($ld_dt) - 7 AND $ld_dt - DAYOFWEEK($ld_dt) - 1           
GROUP BY 
  T.BRAND_ID,
  OWNER_ID, 
  FRANCHISEE_NAME,
  T.REST_ID
ORDER BY REPORTING_PERIOD
)
OVERWRITE = TRUE 
single = true
FILE_FORMAT = (FIELD_DELIMITER = '|' TYPE = csv NULL_IF = ('NULL', 'null') EMPTY_FIELD_AS_NULL = false  compression='NONE')
HEADER=true;