# Paths
utils_path: "/opt/airflow/dags/transaction/global_utils"
airflow_path: "/opt/airflow/dags/transaction/global_utils/airflow"

# Global settings
dag_id: "E2E_SALES_RECON_BWW_ALTAMETRICS_DQ"
dag_description: "Mailing DAG for DQ framework"
emails: ['itdataservicessupport@inspirebrands.com','bwwPOSmonitoring@inspirebrands.com','bwwmenumanagement@inspirebrands.com','rajesh.patil@inspirebrands.com','saxena.ankur@inspirebrands.com','yatender.kumar@inspirebrands.com']
owner: "DQ"

snowflake_conn_irb_objowner_id: "Snowflake-IRB-PROD-OWNER"
warehouse_name: "IRB_PRCSSA_IRB_PROD_WH"
env: "PROD"

database: "IDS_PROD"
schema_name: "INT_REF"
target_schema: "Sales Recon (BOS)- BWW"
brand: "%"
table_list:
  - BOS_DAILY_SALES_MEASURE_BWW

# Paths
utils_path: "/opt/airflow/dags/transaction/global_utils"
airflow_path: "/opt/airflow/dags/transaction/global_utils/airflow"