USE WAREHOUSE {{ params.warehouse }};

DELETE FROM RDS_{{params.env}}.{{params.schema}}."ITEM_REVENUE_CATEGORY" WHERE LOADDATETIME< CURRENT_DATE() - {{params.delete_days}};

INSERT INTO  RDS_{{params.env}}.{{params.schema}}."ITEM_REVENUE_CATEGORY"
WITH SRC_XML AS
(SELECT PARSE_XML($1) AS XMLDATA,
    LOWER('arbys') || '/' || METADATA$FILENAME::STRING AS FILENAME,
    LEFT(RIGHT(METADATA$FILENAME,12),8) AS FILEDATE,
    LEFT(RIGHT(METADATA$FILENAME,45),8) AS FOLDERDATE
FROM @RDS_{{params.env}}.{{params.schema}}.ITEM_XML_READ_ADLS2/{{params.run_date}}/
(FILE_FORMAT => '{{params.file_format}}')
),
ITEM AS 
(
SELECT 
RC.PATH AS RCPATH, RC.THIS AS RCVALUE,
FILENAME,
FILEDATE,
FOLDERDATE
FROM SRC_XML
,LATERAL FLATTEN(INPUT=>SRC_XML.XMLDATA:"$", RECURSIVE=>TRUE) RC
WHERE RC.PATH = '[''$''][''$''][''$'']'
)
SELECT DISTINCT 
XMLGET(VALUE, 'a:Id'):"$"::STRING as ITEM_ID,
XMLGET(VALUE, 'a:Name'):"$"::STRING as ITEM_NAME,
XMLGET(VALUE, 'a:RevenueCenterId'):"$"::STRING as REVENUE_CENTER_ID,
XMLGET(VALUE, 'a:IsDeleted'):"$"::STRING as IS_DELETED,
XMLGET(VALUE, 'a:Active'):"$"::STRING as IS_ACTIVE,
XMLGET(VALUE, 'a:AskName'):"$"::STRING as ASK_NAME,
XMLGET(VALUE, 'a:AskPrice'):"$"::STRING as ASK_PRICE,
XMLGET(VALUE, 'a:AvailableFriday'):"$"::STRING as AVAILABLE_FRIDAY,
XMLGET(VALUE, 'a:AvailableMonday'):"$"::STRING as AVAILABLE_MONDAY,
XMLGET(VALUE, 'a:AvailableSaturday'):"$"::STRING as AVAILABLE_SATURDAY,
XMLGET(VALUE, 'a:AvailableSelectDates'):"$"::STRING as AVAILABLE_SELECT_DATES,
XMLGET(VALUE, 'a:AvailableSelectDays'):"$"::STRING as AVAILABLE_SELECT_DAYS,
XMLGET(VALUE, 'a:AvailableSunday'):"$"::STRING as AVAILABLE_SUNDAY,
XMLGET(VALUE, 'a:AvailableThursday'):"$"::STRING as AVAILABLE_THURSDAY,
XMLGET(VALUE, 'a:AvailableTuesday'):"$"::STRING as AVAILABLE_TUESDAY,
XMLGET(VALUE, 'a:AvailableWednesday'):"$"::STRING as AVAILABLE_WEDNESDAY,
XMLGET(VALUE, 'a:Cost'):"$"::STRING as COST,
XMLGET(VALUE, 'a:CreatedTime'):"$"::STRING as CREATED_TIME,
XMLGET(XMLGET(VALUE, 'a:DatesAvailable'),'b:_end'):"$"::STRING as END_TIME,
XMLGET(XMLGET(VALUE, 'a:DatesAvailable'),'b:_start'):"$"::STRING as START_TIME,
XMLGET(VALUE, 'a:GiftCardItemType'):"$"::STRING as GIFTCARD_ITEM_TYPE,
XMLGET(VALUE, 'a:IsCombo'):"$"::STRING as IS_COMBO,
XMLGET(VALUE, 'a:IsGiftCard'):"$"::STRING as IS_GIFTCARD,
XMLGET(VALUE, 'a:IsQuantityCounted'):"$"::STRING as IS_QUANTITY_COUNTED,
XMLGET(VALUE, 'a:ItemType'):"$"::STRING as ITEM_TYPE,
XMLGET(VALUE, 'a:KitchenName'):"$"::STRING as KITCHEN_NAME,
XMLGET(VALUE, 'a:LastEditedTime'):"$"::STRING as LAST_EDITED_TIME,
XMLGET(VALUE, 'a:ModifierTierId'):"$"::STRING as MODIFIER_TIER_ID,
XMLGET(VALUE, 'a:ModifierWeight'):"$"::STRING as MODIFIER_WEIGHT,
XMLGET(VALUE, 'a:NonRevenueItem'):"$"::STRING as NON_REVENUE_ITEM,
XMLGET(VALUE, 'a:PLU'):"$"::STRING as PLU,
XMLGET(VALUE, 'a:Price'):"$"::STRING as PRICE,
XMLGET(VALUE, 'a:PriceLevel'):"$"::STRING as PRICE_LEVEL,
XMLGET(VALUE, 'a:PricePer'):"$"::STRING as PRICE_PER,
XMLGET(VALUE, 'a:PrinterGroupId'):"$"::STRING as PRINTER_GROUP_ID,
XMLGET(VALUE, 'a:SortPriority'):"$"::STRING as SORT_PRIORITY,
XMLGET(VALUE, 'a:TareId'):"$"::STRING as TARE_ID,
XMLGET(XMLGET(VALUE, 'a:TaxIds'),'b:int'):"$"::STRING as TAX_ID,
XMLGET(VALUE, 'a:UnitName'):"$"::STRING as UNIT_NAME,
XMLGET(VALUE, 'a:UnitPrecision'):"$"::STRING as UNIT_PRECISION,
XMLGET(VALUE, 'a:VideoGroupId'):"$"::STRING as VIDEO_GROUP_ID,
TO_TIMESTAMP_NTZ(CURRENT_TIMESTAMP)::STRING AS LOADDATETIME,
TO_NUMBER(TO_CHAR(CURRENT_DATE, 'YYYYMMDD'))::STRING AS LOADID,
LOWER('incremental') AS LOADTYPE,
FILENAME,
FILEDATE,
FOLDERDATE
FROM ITEM
,LATERAL FLATTEN(RCVALUE:"$") AS ITEM_DATA;


