USE WAREHOUSE {{ params.warehouse }};

DELETE FROM RDS_{{params.env}}.{{params.schema}}.REVENUE_CENTER WHERE LOADDATETIME< CURRENT_DATE() - {{params.delete_days}};

INSERT INTO RDS_{{params.env}}.{{params.schema}}.REVENUE_CENTER   
WITH SRC_XML AS
(SELECT PARSE_XML($1) AS XMLDATA,
    LOWER('arbys') || '/' || METADATA$FILENAME::STRING AS FILENAME,
    LEFT(RIGHT(METADATA$FILENAME,12),8) AS FILEDATE,
    LEFT(RIGHT(METADATA$FILENAME,54),8) AS FOLDERDATE
FROM @RDS_{{params.env}}.{{params.schema}}.REVENUE_CENTER_XML_READ_ADLS2/{{params.run_date}}/ 
(FILE_FORMAT => '{{params.file_format}}')
),
REVENUECENTER AS 
(
SELECT 
RC.PATH AS RCPATH, RC.VALUE AS RCVALUE,
FILENAME,
FILEDATE,
FOLDERDATE
FROM SRC_XML
, LATERAL FLATTEN(INPUT=>SRC_XML.XMLDATA, RECURSIVE=>TRUE) RC
WHERE STARTSWITH(RC.VALUE,'<GetRevenueCentersResult')
)
SELECT DISTINCT
XMLGET(VALUE, 'a:Id'):"$"::INTEGER as REVENUE_CENTER_ID,
XMLGET(VALUE, 'a:Name'):"$"::STRING as REVENUE_CENTER_DESC,
XMLGET(VALUE, 'a:Active'):"$"::STRING as REVENUE_ACTIVE,
XMLGET(XMLGET(VALUE, 'a:TaxIds'),'b:int'):"$"::STRING as REVENUE_TAX_ID,
TO_TIMESTAMP_NTZ(CURRENT_TIMESTAMP)::STRING AS LOADDATETIME,
TO_NUMBER(TO_CHAR(CURRENT_DATE, 'YYYYMMDD'))::STRING AS LOADID,
LOWER('incremental') AS LOADTYPE,
FILENAME,
FILEDATE,
FOLDERDATE
FROM REVENUECENTER
,LATERAL FLATTEN(RCVALUE:"$") AS REVENUECENTER_DATA;



