USE WAREHOUSE {{ params.warehouse }};

COPY INTO RDS_{{params.env}}.{{params.schema}}.NBO_ST_REGISTER
FROM (
  SELECT
 $1:: STRING AS SITENUMBER,
$2:: STRING AS STOREID,
$3:: STRING AS SUBPERIOD,
$4:: STRING AS SALESDATE,
$5:: STRING AS TOTALSALES,
$6:: STRING AS CUSTOMERCOUNT,
$7:: STRING AS SALESTAX,
$8:: STRING AS OVERSHORT,
$9:: STRING AS FOODSALES,
$10:: STRING AS BEVSALES,
$11:: STRING AS OTHERSALES,
$12:: STRING AS WINELIQUORSALES,
$13:: STRING AS BEERSALES,
$14:: STRING AS GIFTCARDSOLD,
$15:: STRING AS DONATIONS,
$16:: STRING AS TAKEOUT,
$17:: STRING AS SALESDELIVERY,
$18:: STRING AS ALCOHOLCOMPSGAMING,
$19:: STRING AS FOODCOMPSGAMING,
$20:: STRING AS COMPLEMENTARYMEALS,
$21:: STRING AS DISCOUNTS,
$22:: STRING AS PAIDOUTS1,
$23:: STRING AS PAIDOUTS2,
$24:: STRING AS AMEX,
$25:: STRING AS DISCOVER,
$26:: STRING AS MASTERCARD,
$27:: STRING AS VISACARD,
$28:: STRING AS GIFTCARDREDEEMED,
$29:: STRING AS OTHERDEPOSITS,
$30:: STRING AS HOUSECHARGE,
$31:: STRING AS EMPLOYEETIPS,
$32:: STRING AS CASHDEPOSITS,
$33:: STRING AS NETSALES,
$34:: STRING AS VISACARD_CA,
to_timestamp_ntz(current_timestamp)::STRING AS LOADDATETIME,
to_number(to_char(current_date, 'YYYYMMDD'))::STRING AS LOADID,
LOWER('incremental') AS LOADTYPE,
LOWER('bww_nbo') || '/' || METADATA$FILENAME::STRING AS FILENAME,
TO_DATE(RIGHT(LEFT(METADATA$FILENAME,48),8),'YYYYMMDD') AS FILEDATE,
TO_DATE(RIGHT(LEFT(METADATA$FILENAME,48),8), 'YYYYMMDD') AS FOLDERDATE
    FROM @RDS_{{params.env}}.{{params.schema}}.SALES_RECON_BWW_NBO_CSV_ADLS2/{{params.run_date}}/
    (file_format => '{{params.file_format}}', pattern => '{{params.pattern}}')
);


