create view IF NOT EXISTS SALES_FORECAST_DAY(
	REST_ID,
	BRAND_ID,
	BUSINESS_DATE,
	SALES_AMT,
	TRANS_CNT,
	FORECAST_TYPE,
	SOURCE_SYSTEM_NAME,
	CDM_LOAD_DATE,
	LOAD_TYPE,
	LOAD_ID,
	LOAD_DTTM
) as 
SELECT
c.REST_ID AS REST_ID
,c.BRAND_ID AS BRAND_ID
,c.BUSINESS_DATE AS BUSINESS_DATE
,c.SALES_AMT AS SALES_AMT
,c.TRANS_CNT AS TRANS_CNT
,c.FORECAST_TYPE AS FORECAST_TYPE
,c.SOURCE_SYSTEM_NAME AS SOURCE_SYSTEM_NAME
,c.CDM_LOAD_DATE AS CDM_LOAD_DATE
,c.LOAD_TYPE AS LOAD_TYPE
,c.LOAD_ID AS LOAD_ID
,c.LOAD_DTTM AS LOAD_DTTM
FROM IDS_DEV.LOCN_BV.SALES_FORECAST_DAY_BV C;
create view IF NOT EXISTS SALES_FORECAST_QTR_HR(
	REST_ID,
	BRAND_ID,
	BUSINESS_DATE,
	QTR_HOUR_BEGIN_DTTM,
	QTR_HOUR_END_DTTM,
	SALES_AMT,
	TRANS_CNT,
	FORECAST_TYPE,
	LOAD_TYPE,
	SOURCE_SYSTEM_NAME,
	CDM_LOAD_DATE,
	LOAD_ID,
	LOAD_DTTM
) as 
SELECT
c.REST_ID AS REST_ID
,c.BRAND_ID AS BRAND_ID
,c.BUSINESS_DATE AS BUSINESS_DATE
,c.QTR_HOUR_BEGIN_DTTM AS QTR_HOUR_BEGIN_DTTM
,c.QTR_HOUR_END_DTTM AS QTR_HOUR_END_DTTM
,c.SALES_AMT AS SALES_AMT
,c.TRANS_CNT AS TRANS_CNT
,c.FORECAST_TYPE AS FORECAST_TYPE
,c.LOAD_TYPE AS LOAD_TYPE
,c.SOURCE_SYSTEM_NAME AS SOURCE_SYSTEM_NAME
,c.CDM_LOAD_DATE AS CDM_LOAD_DATE
,c.LOAD_ID AS LOAD_ID
,c.LOAD_DTTM AS LOAD_DTTM
FROM IDS_DEV.LOCN_BV.SALES_FORECAST_QTR_HR_BV C;