<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<groupId>com.virginvoyages.shore.dim</groupId>
	<artifactId>shore-datamart-dim</artifactId>
	<version>0.0.1-SNAPSHOT</version>
	<packaging>pom</packaging>

	<properties>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
	</properties>

	<distributionManagement>
		<snapshotRepository>
			<id>vv-nexus-snapshots</id>
			<url>http://10.3.100.215:8081/nexus/content/repositories/snapshots</url>
		</snapshotRepository>
	</distributionManagement>


	<modules>
		<module>vv-nbx-datamart-cabin-dim</module>
		<module>vv-nbx-datamart-activity-dim</module>
		<module>vv-nbx-datamart-activity-slot-dims</module>
		<module>vv-nbx-datamart-dining-menu-dim</module>
		<module>vv-nbx-datamart-dining-menu-item-dim</module>
		<module>vv-nbx-datamart-dining-reservation-preference-dim</module>
		<module>vv-nbx-datamart-invoiceitemtype-lookup</module>
		<module>vv-nbx-datamart-menu-item-dim</module>
		<module>vv-nbx-datamart-outlet-dim</module>
		<module>vv-nbx-datamart-position-dim</module>
		<module>vv-nbx-datamart-price-area-lookup</module>
		<module>vv-nbx-datamart-promotion-lookup</module>
		<module>vv-nbx-datamart-wearable-dim</module>
		<module>vv-nbx-datamart-dining-reservation-special-need-dim</module>
		<module>vv-nbx-datamart-folio-detail-dim</module>
		<module>vv-nbx-datamart-restriction-dim</module>
		<module>vv-nbx-datamart-vendor-dim</module>
		<module>vv-nbx-datamart-address-dim</module>
		<module>vv-nbx-datamart-crew-activity-detail-dim</module>
		<module>vv-nbx-datamart-crew-activity-dim</module>
		<module>vv-nbx-datamart-device-dim</module>
		<module>vv-nbx-datamart-game-dim</module>
		<module>vv-nbx-datamart-incident-detail-dim</module>
		<module>vv-nbx-datamart-venue-dim</module>
		<module>vv-nbx-datamart-virtual-detail-dim</module>
		<module>vv-nbx-datamart-voyage-dim</module>
		<module>vv-nbx-datamart-vxp-venue-dim</module>
		<module>vv-nbx-datamart-seaware-guest-rts-dim</module>
		<module>vv-nbx-datamart-booking-detail-dim</module>
		<module>vv-nbx-datamart-folio-sale-detail-dim</module>
		<module>vv-nbx-datamart-order-detail-dim</module>
		<module>vv-nbx-datamart-org-unit-dim</module>
		<module>vv-nbx-datamart-pos-sale-detail-dim</module>
		<module>vv-nbx-datamart-chatqueue-detail-dim</module>
		<module>vv-nbx-datamart-charge-dim</module>
		<module>vv-nbx-datamart-code-description-dim</module>
		<module>vv-nbx-datamart-folio-item-dim</module>
		<module>vv-nbx-datamart-location-optout-dim</module>
		<module>vv-nbx-datamart-pos-item-dim</module>
		<module>vv-nbx-datamart-special-request-dim</module>
		<module>vv-nbx-datamart-virtual-definition-dim</module>
		<module>vv-nbx-datamart-voyagewell-questionaire-dim</module>
		<module>vv-nbx-datamart-itinerary-dim</module>
		<module>vv-nbx-datamart-CRM-emailresponses-dim</module>
		<module>vv-nbx-datamart-Surveyresponses-dim</module>
		<module>vv-nbx-datamart-crmtask-dim</module>
		<module>vv-nbx-datamart-reservation-dim</module>
		<module>vv-nbx-datamart-seaware-res-addon-rel</module>
		<module>vv-nbx-datamart-Seaware-PackageReldim</module>
		<module>vv-nbx-datamart-seaware-coupon-dim</module>
		<module>vv-nbx-datamart-seware_ship_room_request_dim</module>
		<module>vv-nbx-datamart-allocation-lookup</module>
		<module>vv-nbx-datamart-dim-seaware-package</module>
		<module>vv-nbx-datamart-seaware-payment-schedule-dim</module>
		<module>vv-nbx-datamart-seaware-promotion-dim</module>
		<module>vv-nbx-datamart-survey-questions-dim</module>
		<module>vv-nbx-datamart-seaware-hotel-res-request-dim</module>
		<module>vv-nbx-datamart-crmagentmaster-dim</module>
		<module>vv-nbx-datamart-CRMUserHierarchyRel</module>
		<module>vv-nbx-datamart-go-event-dim</module>
		<module>vv-nbx-datamart-HotelLkp</module>
		<module>vv-nbx-datamart-orders-allergy-dim</module>
		<module>vv-nbx-datamart-preference-dim</module>
		<module>vv-nbx-datamart-quickcode-dim</module>
		<module>vv-nbx-datamart-Agency_Master-dim</module>
		<module>vv-nbx-datamart-seaware-plan-forecast-value-dim</module>
		<module>vv-nbx-datamart-seaware-transfer-request-poi-lookup</module>
		<module>vv-nbx-datamart-seaware-transreq-legdetails-rel</module>
		<module>VV-nbx-datamart-Transaction-Event-dim</module>
		<module>vv-nbx-datamart-hotelgroup-request-dim</module>
		<module>vv-nbx-datamart-swship-dim</module>
		<module>vv-nbx-datamart-CrmConvDefDialogue-Dim</module>
		<module>vv-nbx-datamart-seaware-plan-forecast-header-dim</module>
		<module>vv-nbx-datamart-forecast-version-lookup</module>
		<module>vv-nbx-datamart-CrmAgencyHierarchyRel</module>
		<module>vv-nbx-datamart-LiveChatTranscript-dim</module>
		<module>vv-nbx-datamart-seaware-res-guest-rel</module>
		<module>vv-nbx-datamart-Seaware-Sail-Cabin-Reservedim</module>
		<module>vv-nbx-datamart-seaware-cabin-master-dim</module>
		<module>vv-nbx-datamart-seaware-flight-dim</module>
		<module>vv-nbx-datamart-seaware-guest-dim</module>
		<module>vv-nbx-datamart-seaware-guest-flight-rel</module>
		<module>vv-nbx-datamart-seaware-ship-dining-request-dim</module>
		<module>vv-nbx-datamart-ConversationDefinitionSession-dim</module>
		<module>vv-nbx-datamart-postvoyage-survey-questions-dim</module>
		<module>vv-nbx-datamart-postvoyage-survey-questionanswer-dim</module>
		<module>vv-nbx-datamart-postvoyage-sailor-survey-rpt</module>
		<module>vv-nbx-datamart-Seaware-Booked-Cabin-Reservation-dim</module>
		<module>vv-nbx-datamart-Seaware-CommissiomTypeLkpdim</module>
		<module>vv-nbx-TransferRequest-load</module>
		<module>vv-nbx-datamart-ship-facility-dim</module>
		<module>vv-nbx-datamart-addon-lookup</module>
		<module>vv-nbx-datamart-seaware-group-dim</module>
		<module>vv-nbx-datamart-seaware-sail-dim</module>
		<module>vv-nbx-datamart-Seaware-Shiproom-dim</module>
		<module>vv-nbx-shore-datamart-seaware-charge-event-dim</module>
		<module>vv-nbx-shore-datamart-seaware-coupon-class-dim</module>
		<module>vv-nbx-cvsutil-dim</module>
		<module>vv-nbx-datamart-forecast-metric-lookup</module>
		<module>vv-nbx-datamart-gcpcsv-util</module>
		<module>vv-nbx-datamart-crmcase-dim</module>
		<module>vv-nbx-datamart-CRM-ConvdefDialog_Daily_Metric_dim</module>
		<module>vv-nbx-datamart-CRM-ConvdefDialog_Hourly_Metric_dim</module>
		<module>vv-nbx-datamart-spa-service-type-dim</module>
		<module>shore-datamart-boarding-number-dim</module>
		<module>vv-nbx-datamart-seaware-guest-vxp-rel</module>
		<module>vv-nbx-datamart-dining-table-dim</module>
		<module>vv-nbx-datamart-requestdetail-dim</module>
		<module>vv-nbx-datamart-dining-session-dim</module>
		<module>vv-nbx-datamart-venue-availability-dim</module>
		<module>vv-nbx-datamart-incident-category-dim</module>
		<module>vv-nbx-datamart-transaction-evt</module>
		<module>vv-nbx-datamart-ship-vir-incident-rpt</module>
		<module>vv-nbx-datamart-dining-reservation-detail-dim</module>
		<module>vv-nbx-datamart-person-dim</module>
		<module>vv-nbx-datamart-ship-lookup</module>
		<module>vv-nbx-datamart-person-training-dim</module>
		
	</modules>

	<dependencies>
	</dependencies>

	<build>
		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-surefire-plugin</artifactId>
				<version>2.22.0</version>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-dependency-plugin</artifactId>
				<version>3.1.1</version>
			</plugin>
		</plugins>
	</build>
</project>
