dag_id: "E2E_SALES_RECON_SDI_POS_INFOR_MICROS_IDS_TO_IDS_WEEKLY"
dag_description: "Sonic POS data load from IDS to IDS"
email: ["DataServicesHelp@inspirebrands.com","itdataservicessupport@inspirebrands.com"]
source_env : "PROD"
target_env : "PROD"
warehouse_id : "IRB_PRCSSA_IRB_PROD_WH"
snowflake_conn_id : "Snowflake-IRB-PROD-OWNER"
schema_id : "SDI"
