spark.source.cticall.table vv_db.hvtb_nbx_landing_cti_call
spark.source.cticallstate.table vv_db.hvtb_nbx_landing_cti_call_state_history
spark.target.cticall.table vv_db.hvtb_parse_cti_call
spark.target.cticallstate.table vv_db.hvtb_parse_cti_call_state_history
spark.target.cticall.fact.table vv_db.hvtb_nbx_core_cti_call_fact
spark.source.ctiskill.table vv_db.hvtb_nbx_landing_cti_skill
spark.source.ctiskill.table.query select * from vv_db.hvtb_nbx_landing_cti_skill
spark.target.ctiskill.table vv_db.hvtb_parse_cti_skill