DELETE FROM IDS_{{params.env}}.TXN.FN_SYSTEM_CATEGORY;

INSERT INTO IDS_{{params.env}}.TXN.FN_SYSTEM_CATEGORY
(FN_SYSTEM_CATEGORY_CODE,FN_SYSTEM_CATEGORY_NAME,SOURCE_SYSTEM_NAME,LOAD_ID,LOAD_DTTM,UPDATE_ID,UPDATE_DTTM)
SELECT *, 'irb' SOURCE_SYSTEM_NAME, TO_CHAR(CURRENT_DATE, 'YYYYMMDD') LOAD_ID,TO_TIMESTAMP_NTZ(CONVERT_TIMEZONE('UTC', CURRENT_TIMESTAMP)) LOAD_DTTM
, TO_CHAR(CURRENT_DATE, 'YYYYMMDD') UPDATE_ID,TO_TIMESTAMP_NTZ(CONVERT_TIMEZONE('UTC', CURRENT_TIMESTAMP)) UPDATE_DTTM
from (values 
('POS','Point of Sale'), 
('BOS','Back Office System'), 
('SS','Sales System'), 
('GL','General Ledger')
) as n(FN_SYSTEM_CATEGORY_CODE,FN_SYSTEM_CATEGORY_NAME);