WITH FILTERED_REC AS (
  SELECT REST_ID
  FROM (
    SELECT "#PC_NUM" AS REST_ID,
           RANK() OVER (PARTITION BY "#PC_NUM", BRAND_CD, SALES_REPORT_FREQ ORDER BY LOAD_DTTM DESC) AS ROW_NUM
    FROM RDS_QA.DUN.APC_SHOPINFO
    WHERE BRAND_CD = 'DD' AND SALES_REPORT_FREQ = 'Weekly'
  )
  WHERE ROW_NUM = 1
)
SELECT 
  'DKN' AS BRAND,
  TO_CHAR('2024-07-07'::date - DAYOFWEEK('2024-07-07'::date) - 1,'MM-DD-YYYY') AS REPORTING_PERIOD,
  OWNER_ID AS CUSTOMER_NUMBER, 
  FRANCHISEE_NAME AS CUSTOMER_NAME,
  LPAD(T.REST_ID,6,'0') AS UNIT,
  'USD' AS LOCAL_CURRENCY,
  SUM(DERIVED_NET_AMT) AS LOCAL_NET_SALES_RETAIL,
  SUM(TRANS_CNT) AS TRANSACTION_COUNT_RETAIL,
  SUM(DERIVED_GROSS_AMT) AS LOCAL_GROSS_SALES, 
  '' AS LOCAL_NET_SALES_WHOLESALE, 
  '' AS TRANSACTION_COUNT_WHOLESALE,
  'WEEKLY' AS REPORTING_FREQUENCY
FROM IDH_QA.D_TRANS.TRANS T
INNER JOIN IDH_QA.D_LOC.REST R 
ON T.REST_ID = R.REST_ID AND T.BRAND_ID = R.BRAND_ID
INNER JOIN FILTERED_REC FR
ON T.REST_ID = FR.REST_ID
WHERE T.BRAND_ID = 'dnkn'  
AND R.FRAN_IND = true
 AND 
    BUSINESS_DATE BETWEEN  '2024-07-07'::date - DAYOFWEEK('2024-07-07'::date) - 7 AND '2024-07-07'::date - DAYOFWEEK('2024-07-07'::date) - 1           GROUP BY 
  T.BRAND_ID,
  OWNER_ID, 
  FRANCHISEE_NAME,
  T.REST_ID
  UNION
  SELECT 
  'DKN' AS BRAND,
  TO_CHAR('2024-07-14'::date - DAYOFWEEK('2024-07-14'::date) - 1,'MM-DD-YYYY') AS REPORTING_PERIOD,
  OWNER_ID AS CUSTOMER_NUMBER, 
  FRANCHISEE_NAME AS CUSTOMER_NAME,
  LPAD(T.REST_ID,6,'0') AS UNIT,
  'USD' AS LOCAL_CURRENCY,
  SUM(DERIVED_NET_AMT) AS LOCAL_NET_SALES_RETAIL,
  SUM(TRANS_CNT) AS TRANSACTION_COUNT_RETAIL,
  SUM(DERIVED_GROSS_AMT) AS LOCAL_GROSS_SALES, 
  '' AS LOCAL_NET_SALES_WHOLESALE, 
  '' AS TRANSACTION_COUNT_WHOLESALE,
  'WEEKLY' AS REPORTING_FREQUENCY
FROM IDH_QA.D_TRANS.TRANS T
INNER JOIN IDH_QA.D_LOC.REST R 
ON T.REST_ID = R.REST_ID AND T.BRAND_ID = R.BRAND_ID
INNER JOIN FILTERED_REC FR
ON T.REST_ID = FR.REST_ID
WHERE T.BRAND_ID = 'dnkn'  
AND R.FRAN_IND = true
 AND 
    BUSINESS_DATE BETWEEN  '2024-07-14'::date - DAYOFWEEK('2024-07-14'::date) - 7 AND '2024-07-14'::date - DAYOFWEEK('2024-07-14'::date) - 1           GROUP BY 
  T.BRAND_ID,
  OWNER_ID, 
  FRANCHISEE_NAME,
  T.REST_ID
  union 
  SELECT 
  'DKN' AS BRAND,
  TO_CHAR('2024-07-21'::date - DAYOFWEEK('2024-07-21'::date) - 1,'MM-DD-YYYY') AS REPORTING_PERIOD,
  OWNER_ID AS CUSTOMER_NUMBER, 
  FRANCHISEE_NAME AS CUSTOMER_NAME,
  LPAD(T.REST_ID,6,'0') AS UNIT,
  'USD' AS LOCAL_CURRENCY,
  SUM(DERIVED_NET_AMT) AS LOCAL_NET_SALES_RETAIL,
  SUM(TRANS_CNT) AS TRANSACTION_COUNT_RETAIL,
  SUM(DERIVED_GROSS_AMT) AS LOCAL_GROSS_SALES, 
  '' AS LOCAL_NET_SALES_WHOLESALE, 
  '' AS TRANSACTION_COUNT_WHOLESALE,
  'WEEKLY' AS REPORTING_FREQUENCY
FROM IDH_QA.D_TRANS.TRANS T
INNER JOIN IDH_QA.D_LOC.REST R 
ON T.REST_ID = R.REST_ID AND T.BRAND_ID = R.BRAND_ID
INNER JOIN FILTERED_REC FR
ON T.REST_ID = FR.REST_ID
WHERE T.BRAND_ID = 'dnkn'  
AND R.FRAN_IND = true
 AND 
    BUSINESS_DATE BETWEEN  '2024-07-21'::date - DAYOFWEEK('2024-07-21'::date) - 7 AND '2024-07-21'::date - DAYOFWEEK('2024-07-21'::date) - 1           GROUP BY 
  T.BRAND_ID,
  OWNER_ID, 
  FRANCHISEE_NAME,
  T.REST_ID
  UNION
  SELECT 
  'DKN' AS BRAND,
  TO_CHAR('2024-07-28'::date - DAYOFWEEK('2024-07-28'::date) - 1,'MM-DD-YYYY') AS REPORTING_PERIOD,
  OWNER_ID AS CUSTOMER_NUMBER, 
  FRANCHISEE_NAME AS CUSTOMER_NAME,
  LPAD(T.REST_ID,6,'0') AS UNIT,
  'USD' AS LOCAL_CURRENCY,
  SUM(DERIVED_NET_AMT) AS LOCAL_NET_SALES_RETAIL,
  SUM(TRANS_CNT) AS TRANSACTION_COUNT_RETAIL,
  SUM(DERIVED_GROSS_AMT) AS LOCAL_GROSS_SALES, 
  '' AS LOCAL_NET_SALES_WHOLESALE, 
  '' AS TRANSACTION_COUNT_WHOLESALE,
  'WEEKLY' AS REPORTING_FREQUENCY
FROM IDH_QA.D_TRANS.TRANS T
INNER JOIN IDH_QA.D_LOC.REST R 
ON T.REST_ID = R.REST_ID AND T.BRAND_ID = R.BRAND_ID
INNER JOIN FILTERED_REC FR
ON T.REST_ID = FR.REST_ID
WHERE T.BRAND_ID = 'dnkn'  
AND R.FRAN_IND = true
 AND 
    BUSINESS_DATE BETWEEN  '2024-07-28'::date - DAYOFWEEK('2024-07-28'::date) - 7 AND '2024-07-28'::date - DAYOFWEEK('2024-07-28'::date) - 1           GROUP BY 
  T.BRAND_ID,
  OWNER_ID, 
  FRANCHISEE_NAME,
  T.REST_ID
  union
  SELECT 
  'DKN' AS BRAND,
  TO_CHAR('2024-08-04'::date - DAYOFWEEK('2024-08-04'::date) - 1,'MM-DD-YYYY') AS REPORTING_PERIOD,
  OWNER_ID AS CUSTOMER_NUMBER, 
  FRANCHISEE_NAME AS CUSTOMER_NAME,
  LPAD(T.REST_ID,6,'0') AS UNIT,
  'USD' AS LOCAL_CURRENCY,
  SUM(DERIVED_NET_AMT) AS LOCAL_NET_SALES_RETAIL,
  SUM(TRANS_CNT) AS TRANSACTION_COUNT_RETAIL,
  SUM(DERIVED_GROSS_AMT) AS LOCAL_GROSS_SALES, 
  '' AS LOCAL_NET_SALES_WHOLESALE, 
  '' AS TRANSACTION_COUNT_WHOLESALE,
  'WEEKLY' AS REPORTING_FREQUENCY
FROM IDH_QA.D_TRANS.TRANS T
INNER JOIN IDH_QA.D_LOC.REST R 
ON T.REST_ID = R.REST_ID AND T.BRAND_ID = R.BRAND_ID
INNER JOIN FILTERED_REC FR
ON T.REST_ID = FR.REST_ID
WHERE T.BRAND_ID = 'dnkn'  
AND R.FRAN_IND = true
 AND 
    BUSINESS_DATE BETWEEN  '2024-08-04'::date - DAYOFWEEK('2024-08-04'::date) - 7 AND '2024-08-04'::date - DAYOFWEEK('2024-08-04'::date) - 1           GROUP BY 
  T.BRAND_ID,
  OWNER_ID, 
  FRANCHISEE_NAME,
  T.REST_ID
ORDER BY REPORTING_PERIOD 