create TABLE IF NOT EXISTS CDMSYNC_RECON (
	TABLE_NAME VARCHAR(255),
	SNOWFLAKE_COUNT_VALUE VARCHAR(255),
	CDM_COUNT_VALUE VARCHAR(255),
	DAG_RUN_ID VARCHAR(255),
	DAG_NAME VARCHAR(255),
	DIFFERENCE VARCHAR(255),
	BRANDID VARCHAR(255),
	SOURCE_SYSTEM_NAME VARCHAR(255),
	LOADID VARCHAR(255)
);
create TABLE IF NOT EXISTS CDM_CDMSYNC_LOOKUP (
	TABLE_NAME VARCHAR(255),
	BRANDID VARCHAR(255),
	ISACTIVE VARCHAR(255) DEFAULT 'Y',
	LOADDTTM TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
	TABLE_CATALOG VARCHAR(255),
	TABLE_SCHEMA VARCHAR(255),
	SOURCE_SYSTEM_NAME VARCHAR(255),
	LOADID VARCHAR(255)
);
create TABLE IF NOT EXISTS CDM_CDMSYNC_LOOKUP_NEW (
	TABLE_NAME VARCHAR(255),
	BRANDID VARCHAR(255),
	ISACTIVE VARCHAR(255) DEFAULT 'Y',
	LOADDTTM TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
	TABLE_CATALOG VARCHAR(255),
	TABLE_SCHEMA VARCHAR(255),
	SOURCE_SYSTEM_NAME VARCHAR(255),
	LOADID VARCHAR(255)
);
create TABLE IF NOT EXISTS CDM_CDMSYNC_LOOKUP_STG (
	TABLE_NAME VARCHAR(255),
	BRANDID VARCHAR(255),
	ISACTIVE VARCHAR(255) DEFAULT 'Y',
	LOADDTTM TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP()
);
create TABLE IF NOT EXISTS PIPELINE_LOG (
	PIPELINE_ID VARCHAR(16777216),
	STATUS VARCHAR(16777216),
	MESSAGE VARCHAR(16777216),
	START_TIMESTAMP TIMESTAMP_NTZ(9),
	END_TIMESTAMP TIMESTAMP_NTZ(9),
	CREATED_TIMESTAMP TIMESTAMP_NTZ(9),
	CREATED_BY VARCHAR(16777216),
	LAST_MODIFIED_TIMESTAMP TIMESTAMP_NTZ(9),
	LAST_MODIFIED_BY VARCHAR(16777216)
);
create TABLE IF NOT EXISTS PIPELINE_TASK_LOG (
	PIPELINE_ID VARCHAR(16777216),
	TASK_ID VARCHAR(16777216),
	LOG_TYPE VARCHAR(16777216),
	MESSAGE_TYPE VARCHAR(16777216),
	MESSAGE VARCHAR(16777216),
	START_TIMESTAMP TIMESTAMP_NTZ(9),
	END_TIMESTAMP TIMESTAMP_NTZ(9),
	CREATED_TIMESTAMP TIMESTAMP_NTZ(9),
	CREATED_BY VARCHAR(16777216),
	LAST_MODIFIED_TIMESTAMP TIMESTAMP_NTZ(9),
	LAST_MODIFIED_BY VARCHAR(16777216)
);
create TABLE IF NOT EXISTS UDP_AUDIT_MAPPING (
	POD_NAME VARCHAR(255),
	BRAND_ID VARCHAR(255),
	IDS_TABLE VARCHAR(255),
	RDS_TABLE VARCHAR(255)
);
create TABLE IF NOT EXISTS UDP_AUDIT_RDS_IDS (
	POD_NAME VARCHAR(255),
	BRAND_ID VARCHAR(255),
	IDS_TABLE VARCHAR(255),
	IDS_COUNT VARCHAR(255),
	RDS_TABLE VARCHAR(255),
	RDS_COUNT VARCHAR(255),
	LOADID VARCHAR(255)
);
create TABLE IF NOT EXISTS UDP_AUDIT_TRANS (
	TABLE_NAME VARCHAR(255),
	SRC_SYSTEM VARCHAR(255),
	SOURCE_NAME VARCHAR(255),
	RDS_COUNT VARCHAR(255),
	ADLS_COUNT VARCHAR(255),
	LOADID VARCHAR(255),
	UPDATE_TS TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP()
);