ALTER SESSION SET QUOTED_IDENTIFIERS_IGNORE_CASE = FALSE;

/* <sc-table> FACT_PNLSUMMARY_DETAIL_PERIOD </sc-table> */

CREATE TABLE IF NOT EXISTS "FACT_PNLSUMMARY_DETAIL_PERIOD" ("PNLSUMMARY_DETAIL_PERIOD_KEY" INTEGER NOT NULL, "FISCAL_PERIOD_NUMBER" TINYINT NOT NULL, "FISCAL_YEAR" SMALLINT, "REST_NUMBER" VARCHAR(10) NOT NULL, "ACCOUNT_SORT_NUMBER" SMALLINT NOT NULL, "CHILD_ACCOUNT_NUMBER" VARCHAR(55) NOT NULL, "CHILD_ACCOUNT_TYPE" VARCHAR(20) NOT NULL, "CHILD_ACCOUNT_DESC" VARCHAR(255) NOT NULL, "PARENT_ACCOUNT_NUMBER" VARCHAR(55) NOT NULL, "PARENT_ACCOUNT_DESC" VARCHAR(255) NOT NULL, "LINE_NUMBER" INTEGER NOT NULL, "LINE_NAME" VARCHAR(100) NOT NULL, "LINE_DESCRIPTION" VARCHAR(255), "INVOICE_NUMBER" VARCHAR(55), "INVOICE_DATE" DATE, "VENDOR_NAME" VARCHAR(100), "BATCH_NAME" VARCHAR(100), "SOURCE_NAME" VARCHAR(100), "ACTUAL_PTD_AMOUNT" DECIMAL(36,2), "ISACTIVE_STORE_VIEW" BOOLEAN NOT NULL, "ISACTIVE_AREA_VIEW" BOOLEAN NOT NULL, "ISACTIVE_DISTRICT_VIEW" BOOLEAN NOT NULL, "LOAD_ID" INTEGER NOT NULL, "LAST_UPDATE_DATE_TIME" TIMESTAMP NOT NULL);


/* <sc-table> DIM_SURVEY_QUESTION </sc-table> */

CREATE TABLE IF NOT EXISTS "DIM_SURVEY_QUESTION" ("QUESTION_KEY" INTEGER NOT NULL, "QUESTION_NUMBER" INTEGER, "TYPE" VARCHAR(50), "CATEGORY" VARCHAR(500), "DESCRIPTION" VARCHAR(1000), "CHOICE_NUMBER" INTEGER, "CHOICE_TEXT" VARCHAR(250), "LIKERT_SCORE" INTEGER, "BRAND_SCORE" INTEGER, "SORT" INTEGER, "LOADID" INTEGER, "CURRENT_RECORD" BOOLEAN, "EFFECTIVE_DATE" TIMESTAMP, "EXPIRY_DATE" TIMESTAMP);


/* <sc-table> TEMP2 </sc-table> */

CREATE TABLE IF NOT EXISTS "TEMP2" ("OLDKEY" DECIMAL(6,0), "NEWKEY" DECIMAL(6,0));


/* <sc-table> DIM_PNLACCOUNT </sc-table> */

CREATE TABLE IF NOT EXISTS "DIM_PNLACCOUNT" ("PNLACCOUNT_KEY" INTEGER NOT NULL, "ACCOUNT_NUMBER" VARCHAR(55), "ACCOUNT_DESC" VARCHAR(255), "ACCOUNT_TYPE" VARCHAR(20), "ISPARENT" BOOLEAN, "ISACTIVE" BOOLEAN, "LOAD_ID" INTEGER NOT NULL, "LAST_UPDATE_DATE_TIME" TIMESTAMP NOT NULL);


/* <sc-table> DIM_MENUITEM </sc-table> */

CREATE TABLE IF NOT EXISTS "DIM_MENUITEM" (
    MENU_KEY              DECIMAL(18,0),
    PLU_NUMBER            VARCHAR(25) ,
    PLU_DESC              VARCHAR(100) ,
    PROMO_CODE            VARCHAR(25) ,
    PROMO_DESC            VARCHAR(100) ,
    POS_NAME              VARCHAR(10) ,
    POS_ITEM_DESC         VARCHAR(255) ,
    ITEM_ID               DECIMAL(18,0),
    ITEM_DESC             VARCHAR(255) ,
    ITEM_PRODUCT_ID       DECIMAL(18,0),
    ITEM_PRODUCT_DESC     VARCHAR(255) ,
    ITEM_TYPE_CODE        VARCHAR(255) ,
    COMPONENT_ID          DECIMAL(18,0),
    COMPONENT_NAME        VARCHAR(255) ,
    COUPON_NAME           VARCHAR(55) ,
    COUPON_TYPE           VARCHAR(25) ,
    OFFER_ITEM            VARCHAR(255) ,
    MENU_GROUP            VARCHAR(255) ,
    MENU_TYPE             VARCHAR(255) ,
    MAIN_GROUP            VARCHAR(255) ,
    MAIN_PROTEIN          VARCHAR(255) ,
    EFFECTIVE_BEGIN_DATE  DATE,
    EFFECTIVE_END_DATE    DATE,
    ISCURRENT             BOOLEAN,
    INFERRED_FLAG         BOOLEAN,
    LOAD_ID               DECIMAL(18,0),
    LAST_UPDATE_DATE_TIME TIMESTAMP
);



/* <sc-table> TEMP1 </sc-table> */

CREATE TABLE IF NOT EXISTS "TEMP1" ("OLDKEY" INTEGER, "NEWKEY" INTEGER);



/* <sc-table> FACT_SPEEDOFSERVICE_TEST </sc-table> */

CREATE TABLE IF NOT EXISTS "FACT_SPEEDOFSERVICE_TEST" ("FACT_SOS_KEY" INTEGER NOT NULL, "TIME_KEY" INTEGER NOT NULL, "DATE_KEY" INTEGER NOT NULL, "RESTAURANT_KEY" INTEGER NOT NULL, "TIME_ACCUMULATED" INTEGER, "ORDER_COUNT" INTEGER, "CARS_OVER_7MINS" INTEGER, "WINDOW_TIME" INTEGER, "ORDER_PAD_TIME" INTEGER, "REST_SNBR" VARCHAR(5), "LOAD_ID" INTEGER NOT NULL, "LAST_UPDATE_DATE_TIME" TIMESTAMP);



/* <sc-table> FACT_COMPSALES_DAILY </sc-table> */

CREATE TABLE IF NOT EXISTS "FACT_COMPSALES_DAILY" ("COMPSALES_DAILY_KEY" INTEGER NOT NULL, "DATE_KEY" INTEGER NOT NULL, "RESTAURANT_KEY" INTEGER NOT NULL, "REST_NUMBER" VARCHAR(10) NOT NULL, "SALESAMT_TY_TY" DECIMAL(18,2) NOT NULL, "TRANSCNT_TY_TY" INTEGER NOT NULL, "SALESAMT_LY_TY" DECIMAL(18,2) NOT NULL, "TRANSCNT_LY_TY" INTEGER NOT NULL, "SALESAMT_TY_LY" DECIMAL(18,2) NOT NULL, "TRANSCNT_TY_LY" INTEGER NOT NULL, "SALESAMT_LY_LY" DECIMAL(18,2) NOT NULL, "TRANSCNT_LY_LY" INTEGER NOT NULL, "LOAD_ID" INTEGER NOT NULL, "LAST_UPDATE_DATE_TIME" TIMESTAMP NOT NULL);



/* <sc-table> DIM_EMPLOYEE </sc-table> */

CREATE TABLE IF NOT EXISTS "DIM_EMPLOYEE" ("EMPLOYEE_KEY" INTEGER NOT NULL, "EMPLOYEE_ID" INTEGER, "EMPLOYEE_NAME" VARCHAR(255), "POS_NAME" VARCHAR(10), "ADDRESS" VARCHAR(255), "CITY" VARCHAR(255), "State" VARCHAR(255), "ZIP" VARCHAR(10), "EMAIL" VARCHAR(255), "PHONE" VARCHAR(255), "HIRE_DATE" TIMESTAMP, "JOB_TITLE" VARCHAR(255), "PAY_RATE" DECIMAL(18,2), "EFFECTIVE_BEGIN_DATE" DATE, "EFFECTIVE_END_DATE" DATE, "IS_CURRENT" BOOLEAN, "IS_TERMINATED" BOOLEAN, "TERMINATION_DATE" TIMESTAMP, "LOAD_ID" INTEGER NOT NULL, "LAST_UPDATE_DATE_TIME" TIMESTAMP NOT NULL);



/* <sc-table> FACT_AUDITEDSALES </sc-table> */

CREATE TABLE IF NOT EXISTS "FACT_AUDITEDSALES" ("FACT_SALES_KEY" INTEGER NOT NULL, "DATE_KEY" INTEGER NOT NULL, "RESTAURANT_KEY" INTEGER NOT NULL, "SALES_AMOUNT" DECIMAL(18,2), "TRANSACTION_COUNT" INTEGER, "LOAD_ID" INTEGER, "LAST_UPDATE_DATE_TIME" TIMESTAMP, "REST_SNBR" VARCHAR(5));



/* <sc-table> DIM_POINTOFSALE </sc-table> */

CREATE TABLE IF NOT EXISTS "DIM_POINTOFSALE" ("POS_KEY" INTEGER NOT NULL, "POS_NAME" VARCHAR(50), "LOAD_ID" INTEGER, "LAST_UPDATE_DATE_TIME" TIMESTAMP);



/* <sc-table> FACT_WEEKLYSALES_COMP </sc-table> */

CREATE TABLE IF NOT EXISTS "FACT_WEEKLYSALES_COMP" ("REST_NUMBER" VARCHAR(10), "FISCAL_YEAR" INTEGER, "FISCAL_WEEK_NUMBER" INTEGER, "FISCAL_PERIOD_NUMBER" INTEGER NOT NULL, "FISCAL_WEEK_IN_PERIOD_NUMBER" INTEGER, "FISCAL_WEEK_START_DATE" DATE, "FISCAL_WEEK_END_DATE" DATE, "FISCAL_QUARTER_START_DATE" DATE, "FISCAL_QUARTER_END_DATE" DATE, "FISCAL_QUARTER_NUMBER" INTEGER, "FISCAL_PERIOD_START_DATE" DATE, "FISCAL_PERIOD_END_DATE" DATE, "FISCAL_WEEKS_IN_PERIOD_QUANTITY" INTEGER, "Fiscal QTD" CHAR(3) NOT NULL, "PTD" CHAR(3) NOT NULL, "Fiscal YTD" CHAR(10) NOT NULL, "FWTD" CHAR(4) NOT NULL, "FWTD-1" CHAR(4) NOT NULL, "FISCAL_COMP_START_DATE" DATE, "FISCAL_COMP_END_DATE" DATE, "ADJUSTED_COMP_START_DATE" DATE, "ADJUSTED_COMP_END_DATE" DATE, "REST_DMA_CODE" INTEGER, "REST_DMA_DESC" CHAR(100), "Region Name" CHAR(255), "SubRegion Name" CHAR(255), "District Name" CHAR(255), "District Number" CHAR(55), "District Nbr Abbrev" CHAR(3), "Area Name" CHAR(255), "Rest Name" CHAR(255), "SVP" CHAR(255), "VPO" CHAR(255), "DO" CHAR(255), "Area Supervisor" CHAR(255), "LATITUDE" CHAR(55), "LONGITUDE" CHAR(55), "SALESDAYS" INTEGER NOT NULL, "COMP_DAYS_TY" INTEGER NOT NULL, "COMP_DAYS_LY" INTEGER NOT NULL, "COMP_DAYS_TY_ADJ" INTEGER NOT NULL, "COMP_DAYS_LY_ADJ" INTEGER NOT NULL, "COMP_DAYS_TY_TRANS" INTEGER NOT NULL, "COMP_DAYS_LY_TRANS" INTEGER NOT NULL, "COMP_DAYS_TY_ADJ_TRANS" INTEGER NOT NULL, "COMP_DAYS_LY_ADJ_TRANS" INTEGER NOT NULL, "Comp Sales TY_TY" DECIMAL(18,2), "Comp Sales LY_TY" DECIMAL(18,2), "Comp Sales TY_LY" DECIMAL(18,2), "Comp Sales LY_LY" DECIMAL(18,2), "Comp Sales TY_TYadj" DECIMAL(18,2), "Comp Sales LY_TYadj" DECIMAL(18,2), "Comp Sales TY_LYadj" DECIMAL(18,2), "Comp Sales LY_LYadj" DECIMAL(18,2), "Comp Trans TY_TY" BIGINT, "Comp Trans LY_TY" DECIMAL(18,2), "Comp Trans TY_TYadj" BIGINT, "Comp Trans LY_TYadj" DECIMAL(18,2), "Comp Trans TY_LY" DECIMAL(18,2), "Comp Trans LY_LY" BIGINT, "Comp Trans TY_LYadj" DECIMAL(18,2), "Comp Trans LY_LYadj" BIGINT, "Comp Sales for Check TY_TY" DECIMAL(18,2), "Comp Sales for Check LY_TY" DECIMAL(36,2), "Comp Sales for Check TY_TYadj" DECIMAL(18,2), "Comp Sales for Check LY_TYadj" DECIMAL(36,2), "Comp Sales for Check TY_LY" DECIMAL(18,2), "Comp Sales for Check LY_LY" DECIMAL(18,2), "Comp Sales for Check TY_LYadj" DECIMAL(18,2), "Comp Sales for Check LY_LYadj" DECIMAL(18,2), "Comp Sales TY_PY" DECIMAL(18,2), "Comp Sales LY_PY" DECIMAL(18,2), "Comp Sales TY_PYadj" DECIMAL(18,2), "Comp Sales LY_PYadj" DECIMAL(18,2), "Comp Trans TY_PY" BIGINT, "Comp Trans LY_PY" BIGINT, "Comp Trans TY_PYadj" BIGINT, "Comp Trans LY_PYadj" BIGINT, "Net Food Sales TY_TY" DECIMAL(18,2), "Net Food Sales LY_TY" DECIMAL(18,2), "Net Food Sales TY_LY" DECIMAL(18,2), "Net Food Sales LY_LY" DECIMAL(18,2), "Net Food Sales TY_LYadj" DECIMAL(18,2), "Net Food Sales LY_LYadj" DECIMAL(18,2), "Net Food Sales TY_PY" DECIMAL(18,2), "Net Food Sales LY_PY" DECIMAL(18,2), "Net Food Sales TY_PYadj" DECIMAL(18,2), "Net Food Sales LY_PYadj" DECIMAL(18,2), "Net Trans TY_TY" BIGINT, "Net Trans LY_TY" DECIMAL(18,2), "Net Trans TY_LY" DECIMAL(18,2), "Net Trans LY_LY" BIGINT, "Net Trans TY_LYadj" DECIMAL(18,2), "Net Trans LY_LYadj" BIGINT, "Net Trans TY_PY" BIGINT, "Net Trans LY_PY" BIGINT, "Net Trans TY_PYadj" BIGINT, "Net Trans LY_PYadj" BIGINT, "ADJSALESAMT_LY" DECIMAL(18,2), "ADJSALESAMT_2YAGO" DECIMAL(18,2), "ACQUISITION_FISCAL_SALES_LY" DECIMAL(36,2), "ACQUISITION_ADJUSTED_SALES_LY" DECIMAL(36,2), "ACQUISITION_DATE" TIMESTAMP, "Net CY Sales Complete Week ONLY" DECIMAL(18,2), "Net CY Trans Complete Week ONLY" DECIMAL(18,2), "DIVESTITURE_DATE" TIMESTAMP, "LOAD_ID" INTEGER, "LAST_UPDATE_DATE_TIME" TIMESTAMP);



/* <sc-table> DIM_SURVEY_XREF_SURVEY_TAG </sc-table> */

CREATE TABLE IF NOT EXISTS "DIM_SURVEY_XREF_SURVEY_TAG" ("SURVEY_TAG_KEY" INTEGER NOT NULL, "SURVEY_KEY" INTEGER NOT NULL, "LOADID" INTEGER);



/* <sc-table> FACT_SALES_ORDER_PAYMENT </sc-table> */

CREATE TABLE IF NOT EXISTS "FACT_SALES_ORDER_PAYMENT" ("SALES_PAYMENT_KEY" INTEGER NOT NULL, "DATE_KEY" INTEGER NOT NULL, "TIME_KEY" INTEGER NOT NULL, "RESTAURANT_KEY" INTEGER NOT NULL, "POS_KEY" INTEGER NOT NULL, "ORDER_ID" VARCHAR(50) NOT NULL, "ORDER_NUMBER" INTEGER, "PAYMENT_TYPE_ID" INTEGER, "PAYMENT_DESC" VARCHAR(55), "PAYMENT_AUTH_ID" VARCHAR(55), "PAYMENT_LAST4" VARCHAR(11), "PAYMENT_NAME" VARCHAR(55), "PAYMENT_AMOUNT" DECIMAL(18,2), "IS_VOID" BOOLEAN NOT NULL, "LOAD_ID" INTEGER, "LAST_UPDATE_DATE_TIME" TIMESTAMP);



/* <sc-table> DIM_RESTAURANT </sc-table> */

CREATE TABLE IF NOT EXISTS "DIM_RESTAURANT" ("RESTAURANT_KEY" INTEGER, "REST_NUMBER" VARCHAR(10), "REST_NAME" VARCHAR(255), "REST_STATUS" VARCHAR(10), "REST_TYPE" VARCHAR(10), "REST_FRAN_NUMBER" DECIMAL(19,0), "REST_FRAN_NAME" VARCHAR(255), "REST_FRANENTITY_NUMBER" DECIMAL(19,0), "REST_FRANENTITY_NAME" VARCHAR(255), "REST_COMPANY_NAME" VARCHAR(255), "REST_BRAND_NAME" VARCHAR(255), "REST_BRAND_ISACTIVE" BOOLEAN, "REST_DMA_CODE" INTEGER, "REST_DMA_DESC" VARCHAR(100), "REST_ISAIRPORT" BOOLEAN, "REST_ISVIDEOSURV" BOOLEAN, "REST_ISBREAKFAST" BOOLEAN, "REST_IS24HR" BOOLEAN, "REST_ISMALL" BOOLEAN, "REST_ISDRIVETHRU" BOOLEAN, "REST_ADDRLINE1" VARCHAR(255), "REST_ADDRLINE2" VARCHAR(255), "REST_ADDRLINE3" VARCHAR(255), "REST_ADDRCITY" VARCHAR(255), "REST_ADDRCOUNTY" VARCHAR(255), "REST_ADDRSTATE" VARCHAR(2), "REST_ADDRPROVINCE" VARCHAR(25), "REST_ADDRZIP" VARCHAR(10), "REST_COUNTRY" VARCHAR(10), "REST_ADDRPHONE" VARCHAR(25), "REST_LANDLORDPHONE" VARCHAR(25), "REST_ALERTCCEMAIL" VARCHAR(8000), "REST_DIVISION" VARCHAR(50), "REST_LATITUDE" VARCHAR(55), "REST_LONGITUDE" VARCHAR(55), "REST_BUILDINGTYPE" VARCHAR(55), "REST_REMODELPROG_NAME" VARCHAR(255), "REST_REMODELDT" INTEGER, "REST_ACQUISITIONDT" INTEGER, "REST_POSTYPE" VARCHAR(55), "REST_COMP_ISELIGIBLE" BOOLEAN, "REST_COMP_ISTEMPCLOSURE" BOOLEAN, "REST_COMP_DATE" DATE, "REST_OPENDATE" DATE, "REST_TEMP_CLOSEDATE" DATE, "REST_TEMP_OPENDATE" DATE, "REST_TEMPCLOSUREREASON" VARCHAR(100), "REST_CLOSEDATE" DATE, "REST_FACILITYTYPE" VARCHAR(55), "REST_SITETYPE" VARCHAR(20), "REST_TIMEZONE" VARCHAR(100), "REST_SYSTEM_TIMEZONE" VARCHAR(100), "REST_UNITTRADEAREA" VARCHAR(100), "REST_SEATCOUNT" INTEGER, "REST_PARKINGCOUNT" INTEGER, "REST_SQUAREFT" VARCHAR(55), "REST_CSRASSIGNED_NAME" VARCHAR(255), "REST_CSRASSIGNED_EMAIL" VARCHAR(100), "REST_CSRDEFAULT_NAME" VARCHAR(255), "REST_CSRDEFAULT_EMAIL" VARCHAR(100), "REST_DISTCENTER_NAME" VARCHAR(255), "REST_DISTACCOUNT_NUMBER" VARCHAR(255), "REST_BAKERY_NAME" VARCHAR(255), "REST_LICENSE_NUMBER" VARCHAR(55), "REST_LICENSEEXECDATE" INTEGER, "REST_LICENSEEXPDATE" INTEGER, "REST_AFA_PERC" DECIMAL(11,4), "REST_ROYALTY_PER" DECIMAL(11,4), "REST_L1EMAIL" VARCHAR(100), "REST_L2NAME" VARCHAR(255), "REST_L2EMAIL" VARCHAR(100), "REST_L2PHONE" VARCHAR(25), "REST_L3NAME" VARCHAR(255), "REST_L3EMAIL" VARCHAR(100), "REST_L3PHONE" VARCHAR(25), "REST_L4NAME" VARCHAR(255), "REST_L4EMAIL" VARCHAR(100), "REST_L4PHONE" VARCHAR(25), "REST_L5NAME" VARCHAR(255), "REST_L5EMAIL" VARCHAR(100), "REST_L5PHONE" VARCHAR(25), "REST_L6NAME" VARCHAR(255), "REST_L6EMAIL" VARCHAR(100), "REST_L6PHONE" VARCHAR(25), "ARG_AREA_NUMBER" VARCHAR(55), "ARG_AREA_DESC" VARCHAR(255), "ARG_AREA_NAME" VARCHAR(255), "ARG_AREA_NUMBER_ABBR" VARCHAR(3), "ARG_DISTRICT_NUMBER" VARCHAR(55), "ARG_DISTRICT_DESC" VARCHAR(255), "ARG_DISTRICT_NAME" VARCHAR(255), "ARG_DISTRICT_NUMBER_ABBR" VARCHAR(3), "ARG_SUBREGION_NUMBER" VARCHAR(55), "ARG_SUBREGION_DESC" VARCHAR(255), "ARG_SUBREGION_NAME" VARCHAR(255), "ARG_SUBREGION_NUMBER_ABBR" VARCHAR(3), "ARG_REGION_NUMBER" VARCHAR(55), "ARG_REGION_DESC" VARCHAR(255), "ARG_REGION_NAME" VARCHAR(255), "ARG_REGION_NUMBER_ABBR" VARCHAR(3), "ARG_AREA_SUPERVISOR" VARCHAR(255), "ARG_AREA_SUPERVISOR_EMAIL" VARCHAR(100), "ARG_AREA_SUPERVISOR_PHONE" VARCHAR(25), "ARG_DO_NAME" VARCHAR(255), "ARG_DO_EMAIL" VARCHAR(100), "ARG_DO_PHONE" VARCHAR(25), "ARG_VPO_NAME" VARCHAR(255), "ARG_VPO_EMAIL" VARCHAR(100), "ARG_VPO_PHONE" VARCHAR(25), "ARG_SVP_NAME" VARCHAR(255), "ARG_SVP_EMAIL" VARCHAR(100), "ARG_SVP_PHONE" VARCHAR(25), "FRAN_TC_NAME" VARCHAR(255), "FRAN_TC_EMAIL" VARCHAR(100), "FRAN_OC_NAME" VARCHAR(255), "FRAN_OC_EMAIL" VARCHAR(100), "FRAN_DFO_NAME" VARCHAR(255), "FRAN_DFO_EMAIL" VARCHAR(100), "FRAN_CONTACT_NAME" VARCHAR(255), "FRAN_EMAIL" VARCHAR(100), "FRAN_PHONE1" VARCHAR(25), "FRAN_PHONE2" VARCHAR(25), "FRAN_ADDRLINE1" VARCHAR(255), "FRAN_ADDRCITY" VARCHAR(255), "FRAN_ADDRSTATE" VARCHAR(2), "FRAN_ADDRZIP" VARCHAR(10), "FRAN_ADDRCOUNTRY" VARCHAR(10), "EFFECTIVE_BEGIN_DATE" DATE, "EFFECTIVE_END_DATE" DATE, "ISCURRENT" BOOLEAN, "INFERRED_FLAG" BOOLEAN, "LOAD_ID" INTEGER, "LAST_UPDATE_DATE_TIME" TIMESTAMP);



/* <sc-table> FACT_PNLSUMMARY_PERIOD </sc-table> */

CREATE TABLE IF NOT EXISTS "FACT_PNLSUMMARY_PERIOD" ("PNLSUMMARY_PERIOD_KEY" INTEGER NOT NULL, "FISCAL_PERIOD_NUMBER" TINYINT NOT NULL, "FISCAL_YEAR" SMALLINT, "REST_NUMBER" VARCHAR(10) NOT NULL, "ACCOUNT_SORT_NUMBER" SMALLINT NOT NULL, "CHILD_ACCOUNT_NUMBER" VARCHAR(55) NOT NULL, "CHILD_ACCOUNT_TYPE" VARCHAR(20) NOT NULL, "CHILD_ACCOUNT_DESC" VARCHAR(255) NOT NULL, "PARENT_ACCOUNT_NUMBER" VARCHAR(55) NOT NULL, "PARENT_ACCOUNT_DESC" VARCHAR(255) NOT NULL, "ACTUAL_PTD_AMOUNT" DECIMAL(36,2), "BUDGET_PTD_AMOUNT" DECIMAL(36,2), "ISACTIVE_STORE_VIEW" BOOLEAN NOT NULL, "ISACTIVE_AREA_VIEW" BOOLEAN NOT NULL, "ISACTIVE_DISTRICT_VIEW" BOOLEAN NOT NULL, "LOAD_ID" INTEGER NOT NULL, "LAST_UPDATE_DATE_TIME" TIMESTAMP NOT NULL);



/* <sc-table> DIM_CHECKSIZE </sc-table> */

CREATE TABLE IF NOT EXISTS "DIM_CHECKSIZE" ("CHECKSIZE_KEY" INTEGER NOT NULL, "CHECKSIZE_DESC" VARCHAR(50), "LOW_VALUE" DECIMAL(18,2), "HIGH_VALUE" DECIMAL(18,2), "LOAD_ID" INTEGER, "LAST_UPDATE_DATE_TIME" TIMESTAMP);



/* <sc-table> FACT_SALES_DAY_YOY </sc-table> */

CREATE TABLE IF NOT EXISTS "FACT_SALES_DAY_YOY" ("SALES_DAY_YOY_KEY" INTEGER NOT NULL, "DATE_KEY" INTEGER NOT NULL, "RESTAURANT_KEY" INTEGER NOT NULL, "REST_NUMBER" VARCHAR(10) NOT NULL, "SALESAMT_TY" DECIMAL(18,2) NOT NULL, "TRANSCNT_TY" INTEGER NOT NULL, "SALESAMT_LY" DECIMAL(18,2) NOT NULL, "SALESAMT_LY_ADJ" DECIMAL(18,2) NOT NULL, "TRANSCNT_LY" INTEGER NOT NULL, "TRANSCNT_LY_ADJ" INTEGER NOT NULL, "SALESAMT_PY" DECIMAL(18,2) NOT NULL, "SALESAMT_PY_ADJ" DECIMAL(18,2) NOT NULL, "TRANSCNT_PY" INTEGER NOT NULL, "TRANSCNT_PY_ADJ" INTEGER NOT NULL, "IS_AUDITED" BOOLEAN NOT NULL, "LOAD_ID" INTEGER NOT NULL, "LAST_UPDATE_DATE_TIME" TIMESTAMP NOT NULL);



/* <sc-table> FACT_SURVEY_RESULT </sc-table> */

CREATE TABLE IF NOT EXISTS "FACT_SURVEY_RESULT" ("SURVEY_RESULT_KEY" INTEGER NOT NULL, "SURVEYDT_KEY" INTEGER NOT NULL, "SURVEY_KEY" INTEGER NOT NULL, "QUESTION_KEY" INTEGER NOT NULL, "COMMENT_KEY" INTEGER NOT NULL, "EXCLUSION_KEY" INTEGER NOT NULL, "RESPONSE_TEXT" VARCHAR(100), "POINTS_POSSIBLE" INTEGER, "POINTS" INTEGER, "INMOMENT_SCORE" INTEGER, "LIKERT_SCORE" INTEGER, "ADJUSTED_SCORE" INTEGER, "LOADID" INTEGER);



/* <sc-table> FACT_SALES_ITEM_WEEK </sc-table> */

CREATE TABLE IF NOT EXISTS "FACT_SALES_ITEM_WEEK" ("ITEM_WEEK_KEY" INTEGER NOT NULL, "DATE_KEY" INTEGER NOT NULL, "RESTAURANT_KEY" INTEGER NOT NULL, "MENU_KEY" INTEGER NOT NULL, "GROSS_QUANTITY" INTEGER NOT NULL, "GROSS_ORDER_COUNT" INTEGER NOT NULL, "GROSS_AMOUNT" DECIMAL(18,2) NOT NULL, "NET_AMOUNT" DECIMAL(18,2) NOT NULL, "DISCOUNT_AMOUNT" DECIMAL(18,2) NOT NULL, "NET_ORDER_AMOUNT" DECIMAL(18,2) NOT NULL, "LOAD_ID" INTEGER, "LAST_UPDATE_DATE_TIME" TIMESTAMP);



/* <sc-table> FACT_COMPSALES_PERIOD </sc-table> */

CREATE TABLE IF NOT EXISTS "FACT_COMPSALES_PERIOD" ("COMPSALES_PERIOD_KEY" BIGINT NOT NULL, "DATE_KEY" INTEGER NOT NULL, "RESTAURANT_KEY" INTEGER NOT NULL, "REST_NUMBER" VARCHAR(10) NOT NULL, "SALES_TYPE" VARCHAR(3) NOT NULL, "SALESAMT_TY_TY" DECIMAL(18,2) NOT NULL, "SALESAMT_LCL_TY_TY" DECIMAL(18,2) NOT NULL, "TRANSCNT_TY_TY" INTEGER NOT NULL, "SALESAMT_LY_TY" DECIMAL(18,2) NOT NULL, "SALESAMT_LCL_LY_TY" DECIMAL(18,2) NOT NULL, "TRANSCNT_LY_TY" INTEGER NOT NULL, "SALESAMT_TY_LY" DECIMAL(18,2) NOT NULL, "SALESAMT_LCL_TY_LY" DECIMAL(18,2) NOT NULL, "TRANSCNT_TY_LY" INTEGER NOT NULL, "SALESAMT_LY_LY" DECIMAL(18,2) NOT NULL, "SALESAMT_LCL_LY_LY" DECIMAL(18,2) NOT NULL, "TRANSCNT_LY_LY" INTEGER NOT NULL, "LOAD_ID" INTEGER NOT NULL, "LAST_UPDATE_DATE_TIME" TIMESTAMP NOT NULL);



/* <sc-table> FACT_SALES_ORDER_HALFHR </sc-table> */

CREATE TABLE IF NOT EXISTS "FACT_SALES_ORDER_HALFHR" ("ORDER_HALFHR_KEY" INTEGER NOT NULL, "DATE_KEY" INTEGER NOT NULL, "TIME_KEY" INTEGER NOT NULL, "DAYPART_KEY" INTEGER NOT NULL, "RESTAURANT_KEY" INTEGER NOT NULL, "POS_KEY" INTEGER NOT NULL, "POP_KEY" INTEGER NOT NULL, "GUEST_COUNT" INTEGER NOT NULL, "GROSS_QUANTITY" INTEGER NOT NULL, "GROSS_AMOUNT" DECIMAL(18,2) NOT NULL, "DISCOUNT_AMOUNT" DECIMAL(18,2) NOT NULL, "NET_AMOUNT" DECIMAL(18,2) NOT NULL, "SURCHARGE_AMOUNT" DECIMAL(18,2) NOT NULL, "TAX_AMOUNT" DECIMAL(18,2) NOT NULL, "PAYMENT_AMOUNT" DECIMAL(18,2) NOT NULL, "LOAD_ID" INTEGER NOT NULL, "LAST_UPDATE_DATE_TIME" TIMESTAMP NOT NULL);



/* <sc-table> FACT_AUDIT </sc-table> */

CREATE TABLE IF NOT EXISTS "FACT_AUDIT" ("AUDIT_ORDER_KEY" BIGINT, "EVENT_KEY" INTEGER, "DATE_KEY" INTEGER, "RESTAURANT_KEY" INTEGER, "EMPLOYEE_KEY" INTEGER, "ORDER_ID" VARCHAR(255), "Value" DECIMAL(18,2), "LOAD_ID" INTEGER, "LAST_UPDATE_DATE_TIME" TIMESTAMP);



/* <sc-table> FACT_SALES_ORDER_LINE </sc-table> */

CREATE TABLE IF NOT EXISTS "FACT_SALES_ORDER_LINE" ("SALES_ORDER_ITEM_KEY" INTEGER NOT NULL, "DATE_KEY" INTEGER NOT NULL, "TIME_KEY" INTEGER NOT NULL, "RESTAURANT_KEY" INTEGER NOT NULL, "POS_KEY" INTEGER NOT NULL, "POP_KEY" INTEGER NOT NULL, "MENU_KEY" INTEGER NOT NULL, "DISCOUNT_KEY" INTEGER NOT NULL, "ORDER_ID" VARCHAR(50) NOT NULL, "ORDER_NUMBER" INTEGER, "REGISTER_ID" VARCHAR(55), "LINE_ITEM_ID" INTEGER, "PARENT_LINE_ITEM_ID" INTEGER, "PRICE" DECIMAL(18,2), "GROSS_QUANTITY" INTEGER, "NET_QUANTITY" INTEGER, "GROSS_AMOUNT" DECIMAL(18,2), "NET_AMOUNT" DECIMAL(18,2), "DISCOUNT_AMOUNT" DECIMAL(18,2), "IS_MODIFIER" BOOLEAN NOT NULL, "IS_COMBO" BOOLEAN NOT NULL, "IS_COUPON" BOOLEAN NOT NULL, "IS_CLEAR" BOOLEAN NOT NULL, "IS_VOID" BOOLEAN NOT NULL, "IS_REFUND" BOOLEAN NOT NULL, "LOAD_ID" INTEGER, "LAST_UPDATE_DATE_TIME" TIMESTAMP);



/* <sc-table> DIM_TIME </sc-table> */

CREATE TABLE IF NOT EXISTS "DIM_TIME" ("TIME_KEY" INTEGER, "TIME_OF_DAY_TIME" TIMESTAMP, "MERIDIEM_INDICATOR" VARCHAR(2), "US_TIME_TEXT" VARCHAR(11), "ISO_TIME_TEXT" VARCHAR(8), "DAY_PART_TEXT" VARCHAR(25), "HH24HRS" INTEGER, "HH12HRS" INTEGER, "MINUTES" INTEGER, "SECONDS" INTEGER, "PAST_MIDNIGHT_SECONDS" INTEGER, "PAST_MIDNIGHT_MINUTES" INTEGER, "OPERATIONS_DAY_PART_INDICATOR" VARCHAR(6), "LOAD_ID" INTEGER, "LAST_UPDATE_DATE_TIME" TIMESTAMP);



/* <sc-table> DIM_DAYPART </sc-table> */

CREATE TABLE IF NOT EXISTS "DIM_DAYPART" ("DAYPART_KEY" INTEGER, "DAYPART_DESCRIPTION" VARCHAR(100), "START_TIME" VARCHAR(16), "END_TIME" VARCHAR(16), "SORT_NUMBER" INTEGER, "EFFECTIVE_START_DATE" DATE, "EFFECTIVE_END_DATE" DATE, "ISCURRENT" BOOLEAN, "LOAD_ID" INTEGER, "LAST_UPDATE_DATE_TIME" TIMESTAMP);



/* <sc-table> FACT_SPEEDOFSERVICE_BYCAR </sc-table> */

CREATE TABLE IF NOT EXISTS "FACT_SPEEDOFSERVICE_BYCAR" ("FACT_SOS_BYCAR_KEY" BIGINT, "RESTAURANT_KEY" INTEGER, "DATE_KEY" INTEGER, "SPEAKER_ARR_DATEKEY" INTEGER, "SPEAKER_ARR_TIMEKEY" INTEGER, "SPEAKER_DEPART_DATEKEY" INTEGER, "SPEAKER_DEPART_TIMEKEY" INTEGER, "WINDOW_ARR_DATEKEY" INTEGER, "WINDOW_ARR_TIMEKEY" INTEGER, "WINDOW_DEPART_DATEKEY" INTEGER, "WINDOW_DEPART_TIMEKEY" INTEGER, "LOAD_ID" INTEGER, "LAST_UPDATE_DATE_TIME" TIMESTAMP);



/* <sc-table> FACT_COMPSALES_WEEK </sc-table> */

CREATE TABLE IF NOT EXISTS "FACT_COMPSALES_WEEK" ("COMPSALES_WEEK_KEY" BIGINT NOT NULL, "DATE_KEY" INTEGER NOT NULL, "RESTAURANT_KEY" INTEGER NOT NULL, "REST_NUMBER" VARCHAR(10), "SALESAMT_TY_TY" DECIMAL(18,2), "SALESAMT_TY_TY_ADJ" DECIMAL(18,2), "TRANSCNT_TY_TY" INTEGER, "TRANSCNT_TY_TY_ADJ" INTEGER, "SALESAMT_LY_TY" DECIMAL(18,2), "SALESAMT_LY_TY_ADJ" DECIMAL(18,2), "TRANSCNT_LY_TY" INTEGER, "TRANSCNT_LY_TY_ADJ" INTEGER, "SALESAMT_TY_LY" DECIMAL(18,2), "SALESAMT_TY_LY_ADJ" DECIMAL(18,2), "TRANSCNT_TY_LY" INTEGER, "TRANSCNT_TY_LY_ADJ" INTEGER, "SALESAMT_LY_LY" DECIMAL(18,2), "SALESAMT_LY_LY_ADJ" DECIMAL(18,2), "TRANSCNT_LY_LY" INTEGER, "TRANSCNT_LY_LY_ADJ" INTEGER, "LOADID" INTEGER NOT NULL, "LASTUPDDTTM" TIMESTAMP NOT NULL);



/* <sc-table> DIM_SURVEY_TAG </sc-table> */

CREATE TABLE IF NOT EXISTS "DIM_SURVEY_TAG" ("SURVEY_TAG_KEY" INTEGER NOT NULL, "TAG" VARCHAR(100), "EFFECTIVE_DATE" DATE, "EXPIRY_DATE" DATE, "CURRENT_RECORD" BOOLEAN, "LOADID" INTEGER);



/* <sc-table> FACT_SALES_PERIOD_YOY </sc-table> */

CREATE TABLE IF NOT EXISTS "FACT_SALES_PERIOD_YOY" ("SALES_PERIOD_YOY_KEY" INTEGER NOT NULL, "DATE_KEY" INTEGER NOT NULL, "RESTAURANT_KEY" INTEGER NOT NULL, "REST_NUMBER" VARCHAR(10) NOT NULL, "SALES_TYPE" VARCHAR(3) NOT NULL, "SALESAMT_TY" DECIMAL(18,2) NOT NULL, "SALESAMT_LCL_TY" DECIMAL(18,2) NOT NULL, "TRANSCNT_TY" INTEGER NOT NULL, "SALESAMT_LY" DECIMAL(18,2) NOT NULL, "SALESAMT_LCL_LY" DECIMAL(18,2) NOT NULL, "TRANSCNT_LY" INTEGER NOT NULL, "SALESAMT_PY" DECIMAL(18,2) NOT NULL, "SALESAMT_LCL_PY" DECIMAL(18,2) NOT NULL, "TRANSCNT_PY" INTEGER NOT NULL, "LOAD_ID" INTEGER NOT NULL, "LAST_UPDATE_DATE_TIME" TIMESTAMP NOT NULL);



/* <sc-table> DIM_POINTOFPURCHASE </sc-table> */

CREATE TABLE IF NOT EXISTS "DIM_POINTOFPURCHASE" ("POP_KEY" INTEGER NOT NULL, "POP_DESC" VARCHAR(255), "LOAD_ID" INTEGER, "LAST_UPDATE_DATE_TIME" TIMESTAMP);



/* <sc-table> DIM_DISCOUNT </sc-table> */

CREATE TABLE IF NOT EXISTS "DIM_DISCOUNT" ("DISCOUNT_KEY" INTEGER, "DISCOUNT_NUMBER" INTEGER, "DISCOUNT_DESC" VARCHAR(255), "DISCOUNT_POSSOURCE" VARCHAR(10), "DISCOUNT_TYPE" INTEGER, "DISCOUNT_TYPE_DESC" VARCHAR(255), "EFFECTIVE_BEGIN_DATE" DATE, "EFFECTIVE_END_DATE" DATE, "ISCURRENT" BOOLEAN, "INFERRED_FLAG" BOOLEAN, "LOAD_ID" INTEGER, "LAST_UPDATE_DATE_TIME" TIMESTAMP);



/* <sc-table> FACT_SALES_DAYPART_YOY </sc-table> */

CREATE TABLE IF NOT EXISTS "FACT_SALES_DAYPART_YOY" ("SALES_DAYPART_YOY_KEY" BIGINT NOT NULL, "DATE_KEY" INTEGER NOT NULL, "DAYPART_KEY" INTEGER NOT NULL, "RESTAURANT_KEY" INTEGER NOT NULL, "REST_NUMBER" VARCHAR(10) NOT NULL, "POP_KEY" INTEGER NOT NULL, "SALESAMT_TY" DECIMAL(18,2) NOT NULL, "TRANSCNT_TY" INTEGER NOT NULL, "SALESAMT_LY" DECIMAL(18,2) NOT NULL, "SALESAMT_LY_ADJ" DECIMAL(18,2) NOT NULL, "TRANSCNT_LY" INTEGER NOT NULL, "TRANSCNT_LY_ADJ" INTEGER NOT NULL, "SALESAMT_PY" DECIMAL(18,2) NOT NULL, "SALESAMT_PY_ADJ" DECIMAL(18,2) NOT NULL, "TRANSCNT_PY" INTEGER NOT NULL, "TRANSCNT_PY_ADJ" INTEGER NOT NULL, "LOAD_ID" INTEGER NOT NULL, "LAST_UPDATE_DATE_TIME" TIMESTAMP NOT NULL);



/* <sc-table> FACT_SALES_WEEK_YOY </sc-table> */

CREATE TABLE IF NOT EXISTS "FACT_SALES_WEEK_YOY" ("SALES_WEEK_YOY_KEY" INTEGER NOT NULL, "DATE_KEY" INTEGER NOT NULL, "RESTAURANT_KEY" INTEGER NOT NULL, "REST_NUMBER" VARCHAR(10) NOT NULL, "SALESAMT_TY" DECIMAL(18,2) NOT NULL, "TRANSCNT_TY" INTEGER NOT NULL, "SALESAMT_LY" DECIMAL(18,2) NOT NULL, "SALESAMT_LY_ADJ" DECIMAL(18,2) NOT NULL, "TRANSCNT_LY" INTEGER NOT NULL, "TRANSCNT_LY_ADJ" INTEGER NOT NULL, "SALESAMT_PY" DECIMAL(18,2) NOT NULL, "SALESAMT_PY_ADJ" DECIMAL(18,2) NOT NULL, "TRANSCNT_PY" INTEGER NOT NULL, "TRANSCNT_PY_ADJ" INTEGER NOT NULL, "LOAD_ID" INTEGER NOT NULL, "LAST_UPDATE_DATE_TIME" TIMESTAMP NOT NULL);



/* <sc-table> FACT_COMPSALES_DAYPART </sc-table> */

CREATE TABLE IF NOT EXISTS "FACT_COMPSALES_DAYPART" ("COMPSALES_DAYPART_KEY" BIGINT NOT NULL, "DATE_KEY" INTEGER NOT NULL, "DAYPART_KEY" INTEGER NOT NULL, "RESTAURANT_KEY" INTEGER NOT NULL, "REST_NUMBER" VARCHAR(10) NOT NULL, "POP_KEY" INTEGER NOT NULL, "SALESAMT_TY_TY" DECIMAL(18,2) NOT NULL, "SALESAMT_TY_TY_ADJ" DECIMAL(18,2) NOT NULL, "TRANSCNT_TY_TY" INTEGER NOT NULL, "TRANSCNT_TY_TY_ADJ" INTEGER NOT NULL, "SALESAMT_LY_TY" DECIMAL(18,2) NOT NULL, "SALESAMT_LY_TY_ADJ" DECIMAL(18,2) NOT NULL, "TRANSCNT_LY_TY" INTEGER NOT NULL, "TRANSCNT_LY_TY_ADJ" INTEGER NOT NULL, "SALESAMT_TY_LY" DECIMAL(18,2) NOT NULL, "SALESAMT_TY_LY_ADJ" DECIMAL(18,2) NOT NULL, "TRANSCNT_TY_LY" INTEGER NOT NULL, "TRANSCNT_TY_LY_ADJ" INTEGER NOT NULL, "SALESAMT_LY_LY" DECIMAL(18,2) NOT NULL, "SALESAMT_LY_LY_ADJ" DECIMAL(18,2) NOT NULL, "TRANSCNT_LY_LY" INTEGER NOT NULL, "TRANSCNT_LY_LY_ADJ" INTEGER NOT NULL, "LOAD_ID" INTEGER NOT NULL, "LAST_UPDATE_DATE_TIME" TIMESTAMP NOT NULL);



/* <sc-table> TESTING </sc-table> */

CREATE TABLE IF NOT EXISTS "TESTING" ("ID" INTEGER);



/* <sc-table> DIM_SURVEY_TYPE </sc-table> */

CREATE TABLE IF NOT EXISTS "DIM_SURVEY_TYPE" ("SURVEY_TYPE_KEY" INTEGER NOT NULL, "MODE" VARCHAR(10), "NAME" VARCHAR(50), "GATEWAY_NAME" VARCHAR(150), "DESCRIPTION" VARCHAR(400), "EFFECTIVE_DATE" TIMESTAMP, "EXPIRY_DATE" TIMESTAMP, "CURRENT_RECORD" BOOLEAN, "LOADID" INTEGER);



/* <sc-table> DIM_EXCLUSION_REASON </sc-table> */

CREATE TABLE IF NOT EXISTS "DIM_EXCLUSION_REASON" ("EXCLUSION_KEY" INTEGER NOT NULL, "EXCLUSION_REASON" VARCHAR(100));



/* <sc-table> FACT_AUDIT_DAY </sc-table> */

CREATE TABLE IF NOT EXISTS "FACT_AUDIT_DAY" ("AUDIT_KEY" BIGINT, "EVENT_KEY" INTEGER, "DATE_KEY" INTEGER, "RESTAURANT_KEY" INTEGER, "EMPLOYEE_KEY" INTEGER, "Value" DECIMAL(18,2), "LOAD_ID" INTEGER, "LAST_UPDATE_DATE_TIME" TIMESTAMP);



CREATE OR REPLACE TABLE "FACT_COMPSALES_WEEK_2018" (
       REST_NUMBER                     VARCHAR(10),
       FISCAL_YEAR                     DECIMAL(9,0),
       FISCAL_WEEK_NUMBER              DECIMAL(3,0),
       FISCAL_PERIOD_NUMBER            DECIMAL(3,0) NOT NULL /*** MSC-WARNING - MSCEWI3041 - CONSTRAINT STATES WERE REMOVED FROM NOT NULL INLINE CONSTRAINT ***/,
       FISCAL_WEEK_IN_PERIOD_NUMBER    DECIMAL(3,0),
       FISCAL_WEEK_START_DATE TIMESTAMP /*** MSC-WARNING - MSCEWI3060 - DEFAULT VALUE FOR SYSDATE IS CURRENT_TIMESTAMP. COLUMN WAS TRANSFORMED TO TIMESTAMP TO PRESERVE INFORMATION. ***/,
       FISCAL_WEEK_END_DATE TIMESTAMP /*** MSC-WARNING - MSCEWI3060 - DEFAULT VALUE FOR SYSDATE IS CURRENT_TIMESTAMP. COLUMN WAS TRANSFORMED TO TIMESTAMP TO PRESERVE INFORMATION. ***/,
       FISCAL_QUARTER_START_DATE TIMESTAMP /*** MSC-WARNING - MSCEWI3060 - DEFAULT VALUE FOR SYSDATE IS CURRENT_TIMESTAMP. COLUMN WAS TRANSFORMED TO TIMESTAMP TO PRESERVE INFORMATION. ***/,
       FISCAL_QUARTER_END_DATE TIMESTAMP /*** MSC-WARNING - MSCEWI3060 - DEFAULT VALUE FOR SYSDATE IS CURRENT_TIMESTAMP. COLUMN WAS TRANSFORMED TO TIMESTAMP TO PRESERVE INFORMATION. ***/,
       FISCAL_QUARTER_NUMBER           DECIMAL(3,0),
       FISCAL_PERIOD_START_DATE TIMESTAMP /*** MSC-WARNING - MSCEWI3060 - DEFAULT VALUE FOR SYSDATE IS CURRENT_TIMESTAMP. COLUMN WAS TRANSFORMED TO TIMESTAMP TO PRESERVE INFORMATION. ***/,
       FISCAL_PERIOD_END_DATE TIMESTAMP /*** MSC-WARNING - MSCEWI3060 - DEFAULT VALUE FOR SYSDATE IS CURRENT_TIMESTAMP. COLUMN WAS TRANSFORMED TO TIMESTAMP TO PRESERVE INFORMATION. ***/,
       FISCAL_WEEKS_IN_PERIOD_QUANTITY DECIMAL(3,0),
       "Fiscal QTD" VARCHAR(3),
       PTD VARCHAR(3),
       "Fiscal YTD" VARCHAR(10),
       FWTD VARCHAR(4),
       "FWTD-1" VARCHAR(4),
       FISCAL_COMP_START_DATE TIMESTAMP /*** MSC-WARNING - MSCEWI3060 - DEFAULT VALUE FOR SYSDATE IS CURRENT_TIMESTAMP. COLUMN WAS TRANSFORMED TO TIMESTAMP TO PRESERVE INFORMATION. ***/,
       FISCAL_COMP_END_DATE TIMESTAMP /*** MSC-WARNING - MSCEWI3060 - DEFAULT VALUE FOR SYSDATE IS CURRENT_TIMESTAMP. COLUMN WAS TRANSFORMED TO TIMESTAMP TO PRESERVE INFORMATION. ***/,
       ADJUSTED_COMP_START_DATE TIMESTAMP /*** MSC-WARNING - MSCEWI3060 - DEFAULT VALUE FOR SYSDATE IS CURRENT_TIMESTAMP. COLUMN WAS TRANSFORMED TO TIMESTAMP TO PRESERVE INFORMATION. ***/,
       ADJUSTED_COMP_END_DATE TIMESTAMP /*** MSC-WARNING - MSCEWI3060 - DEFAULT VALUE FOR SYSDATE IS CURRENT_TIMESTAMP. COLUMN WAS TRANSFORMED TO TIMESTAMP TO PRESERVE INFORMATION. ***/,
       REST_DMA_CODE                   DECIMAL(18,0),
       REST_DMA_DESC                   VARCHAR(30),
       "Region Name" VARCHAR(255),
       "SubRegion Name" VARCHAR(255),
       "District Name" VARCHAR(255),
       "District Number" VARCHAR(55),
       "District Nbr Abbrev" VARCHAR(3),
       "Area Name" VARCHAR(255),
       "Rest Name" VARCHAR(255),
       SVP                             VARCHAR(255),
       VPO                             VARCHAR(255),
       "DO"                              VARCHAR(255),
       "Area Supervisor" VARCHAR(255),
       LATITUDE                        VARCHAR(55),
       LONGITUDE                       VARCHAR(55),
       SALESDAYS                       DECIMAL(18,0) NOT NULL /*** MSC-WARNING - MSCEWI3041 - CONSTRAINT STATES WERE REMOVED FROM NOT NULL INLINE CONSTRAINT ***/,
       COMP_DAYS_TY                    DECIMAL(18,0) NOT NULL /*** MSC-WARNING - MSCEWI3041 - CONSTRAINT STATES WERE REMOVED FROM NOT NULL INLINE CONSTRAINT ***/,
       COMP_DAYS_LY                    DECIMAL(18,0) NOT NULL /*** MSC-WARNING - MSCEWI3041 - CONSTRAINT STATES WERE REMOVED FROM NOT NULL INLINE CONSTRAINT ***/,
       COMP_DAYS_TY_ADJ                DECIMAL(18,0) NOT NULL /*** MSC-WARNING - MSCEWI3041 - CONSTRAINT STATES WERE REMOVED FROM NOT NULL INLINE CONSTRAINT ***/,
       COMP_DAYS_LY_ADJ                DECIMAL(18,0) NOT NULL /*** MSC-WARNING - MSCEWI3041 - CONSTRAINT STATES WERE REMOVED FROM NOT NULL INLINE CONSTRAINT ***/,
       COMP_DAYS_TY_TRANS              DECIMAL(18,0) NOT NULL /*** MSC-WARNING - MSCEWI3041 - CONSTRAINT STATES WERE REMOVED FROM NOT NULL INLINE CONSTRAINT ***/,
       COMP_DAYS_LY_TRANS              DECIMAL(18,0) NOT NULL /*** MSC-WARNING - MSCEWI3041 - CONSTRAINT STATES WERE REMOVED FROM NOT NULL INLINE CONSTRAINT ***/,
       COMP_DAYS_TY_ADJ_TRANS          DECIMAL(18,0) NOT NULL /*** MSC-WARNING - MSCEWI3041 - CONSTRAINT STATES WERE REMOVED FROM NOT NULL INLINE CONSTRAINT ***/,
       COMP_DAYS_LY_ADJ_TRANS          DECIMAL(18,0) NOT NULL /*** MSC-WARNING - MSCEWI3041 - CONSTRAINT STATES WERE REMOVED FROM NOT NULL INLINE CONSTRAINT ***/,
       "Comp Sales TY_TY" DECIMAL(18,2),
       "Comp Sales LY_TY" DECIMAL(18,2),
       "Comp Sales TY_LY" DECIMAL(18,2),
       "Comp Sales LY_LY" DECIMAL(18,2),
       "Comp Sales TY_TYadj" DECIMAL(18,2),
       "Comp Sales LY_TYadj" DECIMAL(18,2),
       "Comp Sales TY_LYadj" DECIMAL(18,2),
       "Comp Sales LY_LYadj" DECIMAL(18,2),
       "Comp Trans TY_TY" DECIMAL(36,0),
       "Comp Trans LY_TY" DOUBLE PRECISION,
       "Comp Trans TY_TYadj" DECIMAL(36,0),
       "Comp Trans LY_TYadj" DOUBLE PRECISION,
       "Comp Trans TY_LY" DOUBLE PRECISION,
       "Comp Trans LY_LY" DECIMAL(36,0),
       "Comp Trans TY_LYadj" DOUBLE PRECISION,
       "Comp Trans LY_LYadj" DECIMAL(36,0),
       "Comp Sales for Check TY_TY" DECIMAL(18,2),
       "Comp Sales for Check LY_TY" DECIMAL(36,2),
       "Comp Sales for Check TY_TYadj" DECIMAL(18,2),
       "Comp Sales for Check LY_TYadj" DECIMAL(36,2),
       "Comp Sales for Check TY_LY" DECIMAL(18,2),
       "Comp Sales for Check LY_LY" DECIMAL(18,2),
       "Comp Sales for Check TY_LYadj" DECIMAL(18,2),
       "Comp Sales for Check LY_LYadj" DECIMAL(18,2),
       "Comp Sales TY_PY" DECIMAL(18,2),
       "Comp Sales LY_PY" DECIMAL(18,2),
       "Comp Sales TY_PYadj" DECIMAL(18,2),
       "Comp Sales LY_PYadj" DECIMAL(18,2),
       "Comp Trans TY_PY" DECIMAL(36,0),
       "Comp Trans LY_PY" DECIMAL(36,0),
       "Comp Trans TY_PYadj" DECIMAL(36,0),
       "Comp Trans LY_PYadj" DECIMAL(36,0),
       "Net Food Sales TY_TY" DECIMAL(18,2),
       "Net Food Sales LY_TY" DECIMAL(18,2),
       "Net Food Sales TY_LY" DECIMAL(18,2),
       "Net Food Sales LY_LY" DECIMAL(18,2),
       "Net Food Sales TY_LYadj" DECIMAL(18,2),
       "Net Food Sales LY_LYadj" DECIMAL(18,2),
       "Net Food Sales TY_PY" DECIMAL(18,2),
       "Net Food Sales LY_PY" DECIMAL(18,2),
       "Net Food Sales TY_PYadj" DECIMAL(18,2),
       "Net Food Sales LY_PYadj" DECIMAL(18,2),
       "Net Trans TY_TY" DECIMAL(36,0),
       "Net Trans LY_TY" DOUBLE PRECISION,
       "Net Trans TY_LY" DOUBLE PRECISION,
       "Net Trans LY_LY" DECIMAL(36,0),
       "Net Trans TY_LYadj" DOUBLE PRECISION,
       "Net Trans LY_LYadj" DECIMAL(36,0),
       "Net Trans TY_PY" DECIMAL(36,0),
       "Net Trans LY_PY" DECIMAL(36,0),
       "Net Trans TY_PYadj" DECIMAL(36,0),
       "Net Trans LY_PYadj" DECIMAL(36,0),
       ADJSALESAMT_LY                  DECIMAL(18,2),
       ADJSALESAMT_2YAGO               DECIMAL(18,2),
       ACQUISITION_FISCAL_SALES_LY     DECIMAL(36,2),
       ACQUISITION_ADJUSTED_SALES_LY   DECIMAL(36,2),
       ACQUISITION_DATE TIMESTAMP(6),
       "Net CY Sales Complete Week ONLY" DECIMAL(18,2),
       "Net CY Trans Complete Week ONLY" DECIMAL(18,2),
       DIVESTITURE_DATE TIMESTAMP(6),
       LOAD_ID                         DECIMAL(18,0),
       LAST_UPDATE_DATE_TIME TIMESTAMP(6)
   );



/* <sc-table> FACT_SALES_HR </sc-table> */

CREATE TABLE IF NOT EXISTS "FACT_SALES_HR" ("SALES_HR_KEY" BIGINT NOT NULL, "DATE_KEY" INTEGER NOT NULL, "DAYPART_KEY" INTEGER NOT NULL, "TIME_KEY" INTEGER NOT NULL, "RESTAURANT_KEY" INTEGER NOT NULL, "REST_NUMBER" VARCHAR(10) NOT NULL, "POP_KEY" INTEGER NOT NULL, "SALESAMT_TY" DECIMAL(18,2) NOT NULL, "TRANSCNT_TY" INTEGER NOT NULL, "LOAD_ID" INTEGER NOT NULL, "LAST_UPDATE_DATE_TIME" TIMESTAMP NOT NULL);



/* <sc-table> FACT_COMPSALES_DAY </sc-table> */

CREATE TABLE IF NOT EXISTS "FACT_COMPSALES_DAY" ("COMPSALES_DAY_KEY" BIGINT NOT NULL, "DATE_KEY" INTEGER NOT NULL, "RESTAURANT_KEY" INTEGER NOT NULL, "REST_NUMBER" VARCHAR(10) NOT NULL, "SALESAMT_TY_TY" DECIMAL(18,2) NOT NULL, "SALESAMT_TY_TY_ADJ" DECIMAL(18,2) NOT NULL, "TRANSCNT_TY_TY" INTEGER NOT NULL, "TRANSCNT_TY_TY_ADJ" INTEGER NOT NULL, "SALESAMT_LY_TY" DECIMAL(18,2) NOT NULL, "SALESAMT_LY_TY_ADJ" DECIMAL(18,2) NOT NULL, "TRANSCNT_LY_TY" INTEGER NOT NULL, "TRANSCNT_LY_TY_ADJ" INTEGER NOT NULL, "SALESAMT_TY_LY" DECIMAL(18,2) NOT NULL, "SALESAMT_TY_LY_ADJ" DECIMAL(18,2) NOT NULL, "TRANSCNT_TY_LY" INTEGER NOT NULL, "TRANSCNT_TY_LY_ADJ" INTEGER NOT NULL, "SALESAMT_LY_LY" DECIMAL(18,2) NOT NULL, "SALESAMT_LY_LY_ADJ" DECIMAL(18,2) NOT NULL, "TRANSCNT_LY_LY" INTEGER NOT NULL, "TRANSCNT_LY_LY_ADJ" INTEGER NOT NULL, "LOAD_ID" INTEGER NOT NULL, "LAST_UPDATE_DATE_TIME" TIMESTAMP NOT NULL);



/* <sc-table> DIM_SURVEY </sc-table> */

CREATE TABLE IF NOT EXISTS "DIM_SURVEY" ("SURVEY_KEY" INTEGER NOT NULL, "SURVEY_TYPE_KEY" INTEGER NOT NULL, "RESTAURANT_KEY" INTEGER NOT NULL, "SURVEY_NUMBER" INTEGER, "NAME" VARCHAR(50), "SURVEYDT_KEY" INTEGER NOT NULL, "SURVEYTM_KEY" INTEGER, "SALESDT_KEY" INTEGER NOT NULL, "COMPLETED" BOOLEAN NOT NULL, "MINUTES_TAKEN" INTEGER, "OFFER_ID" INTEGER, "OFFER_CODE" VARCHAR(10), "REDEMEPTION_CODE" VARCHAR(10), "ISCOMPLAINT" BOOLEAN, "LOADID" INTEGER);



/* <sc-table> DIM_SURVEY_COMMENT </sc-table> */

CREATE TABLE IF NOT EXISTS "DIM_SURVEY_COMMENT" ("COMMENT_KEY" INTEGER NOT NULL, "SURVEY_KEY" INTEGER NOT NULL, "QUESTION_KEY" INTEGER NOT NULL, "COMMENT_TEXT" VARCHAR(8000), "SURVEY_NUMBER" INTEGER, "QUESTION_NUMBER" INTEGER, "LOADID" INTEGER);



CREATE OR REPLACE TABLE FACT_COMPSALES_PERIOD_2018 (
    REST_NUMBER                         VARCHAR(10),
    FISCAL_YEAR                         DECIMAL(9,0),
    FISCAL_PERIOD_NUMBER                DECIMAL(3,0) NOT NULL /*** MSC-WARNING - MSCEWI3041 - CONSTRAINT STATES WERE REMOVED FROM NOT NULL INLINE CONSTRAINT ***/,
    FISCAL_PERIOD_START_DATE TIMESTAMP /*** MSC-WARNING - MSCEWI3060 - DEFAULT VALUE FOR SYSDATE IS CURRENT_TIMESTAMP. COLUMN WAS TRANSFORMED TO TIMESTAMP TO PRESERVE INFORMATION. ***/,
    FISCAL_PERIOD_END_DATE TIMESTAMP /*** MSC-WARNING - MSCEWI3060 - DEFAULT VALUE FOR SYSDATE IS CURRENT_TIMESTAMP. COLUMN WAS TRANSFORMED TO TIMESTAMP TO PRESERVE INFORMATION. ***/,
    FISCAL_QUARTER_START_DATE TIMESTAMP /*** MSC-WARNING - MSCEWI3060 - DEFAULT VALUE FOR SYSDATE IS CURRENT_TIMESTAMP. COLUMN WAS TRANSFORMED TO TIMESTAMP TO PRESERVE INFORMATION. ***/,
    FISCAL_QUARTER_END_DATE TIMESTAMP /*** MSC-WARNING - MSCEWI3060 - DEFAULT VALUE FOR SYSDATE IS CURRENT_TIMESTAMP. COLUMN WAS TRANSFORMED TO TIMESTAMP TO PRESERVE INFORMATION. ***/,
    "Fiscal QTD"                          VARCHAR(3),
    PTD                                 VARCHAR(3),
    "Fiscal YTD"                          VARCHAR(10),
    REST_DMA_CODE                       DECIMAL(18,0),
    REST_DMA_DESC                       VARCHAR(30),
    "Region Name"                         VARCHAR(255),
    "SubRegion Name"                      VARCHAR(255),
    "District Name"                       VARCHAR(255),
    "Area Name"                           VARCHAR(255),
    "Rest Name"                           VARCHAR(255),
    SVP                                 VARCHAR(255),
    VPO                                 VARCHAR(255),
    "DO"                                  VARCHAR(255),
    "Area Supervisor"                     VARCHAR(255),
    LATITUDE                            VARCHAR(55),
    LONGITUDE                           VARCHAR(55),
    DAYS_DATE TIMESTAMP /*** MSC-WARNING - MSCEWI3060 - DEFAULT VALUE FOR SYSDATE IS CURRENT_TIMESTAMP. COLUMN WAS TRANSFORMED TO TIMESTAMP TO PRESERVE INFORMATION. ***/,
    "Temp Close Start Date" TIMESTAMP /*** MSC-WARNING - MSCEWI3060 - DEFAULT VALUE FOR SYSDATE IS CURRENT_TIMESTAMP. COLUMN WAS TRANSFORMED TO TIMESTAMP TO PRESERVE INFORMATION. ***/,
    "Temp Close End Date" TIMESTAMP /*** MSC-WARNING - MSCEWI3060 - DEFAULT VALUE FOR SYSDATE IS CURRENT_TIMESTAMP. COLUMN WAS TRANSFORMED TO TIMESTAMP TO PRESERVE INFORMATION. ***/,
    "Rest Temp Closed"                    VARCHAR(1),
    "Rest Temp Closed Fiscal Comp Date"   VARCHAR(1),
    "Rest Temp Closed Adjusted Comp Date" VARCHAR(1),
    "Rest Comp Open on Date"              VARCHAR(1),
    "Rest Comp Open on Fiscal Comp Date"  VARCHAR(1),
    ACQUISITION_DATE TIMESTAMP(6),
    "Comp Sales TY_TY" DECIMAL(18,2),
    "Comp Sales LY_TY" DECIMAL(18,2),
    "Comp Sales TY_LY" DECIMAL(18,2),
    "Comp Sales LY_LY" DECIMAL(18,2),
    "Comp Trans TY_TY" DECIMAL(36,0),
    "Comp Trans LY_TY" DOUBLE PRECISION,
    "Comp Trans TY_LY" DECIMAL(36,0),
    "Comp Trans LY_LY" DOUBLE PRECISION,
    "Net Food Sales TY_TY" DECIMAL(18,2),
    "Net Food Sales LY_TY" DECIMAL(18,2),
    "Net Food Sales TY_LY" DECIMAL(18,2),
    "Net Food Sales LY_LY" DECIMAL(18,2),
    "Net Trans TY_TY" DECIMAL(36,0),
    "Net Trans LY_TY" DECIMAL(36,0),
    "Net Trans TY_LY" DECIMAL(36,0),
    "Net Trans LY_LY" DOUBLE PRECISION
);



/* <sc-table> FACT_SALES_ORDER </sc-table> */

CREATE TABLE IF NOT EXISTS "FACT_SALES_ORDER" ("SALES_ORDER_KEY" INTEGER NOT NULL, "DATE_KEY" INTEGER NOT NULL, "TIME_KEY" INTEGER NOT NULL, "RESTAURANT_KEY" INTEGER NOT NULL, "POS_KEY" INTEGER NOT NULL, "EMPLOYEE_KEY" INTEGER, "POP_KEY" INTEGER NOT NULL, "ORDER_ID" VARCHAR(50) NOT NULL, "ORDER_NUMBER" INTEGER NOT NULL, "ORDER_NAME" VARCHAR(255), "TAXEXEMPT_ID" VARCHAR(255), "GUEST_COUNT" INTEGER NOT NULL, "GROSS_QUANTITY" INTEGER NOT NULL, "GROSS_AMOUNT" DECIMAL(18,2) NOT NULL, "DISCOUNT_AMOUNT" DECIMAL(18,2) NOT NULL, "NET_AMOUNT" DECIMAL(18,2) NOT NULL, "SURCHARGE_AMOUNT" DECIMAL(18,2) NOT NULL, "TAX_AMOUNT" DECIMAL(18,2) NOT NULL, "PAYMENT_AMOUNT" DECIMAL(18,2) NOT NULL, "IS_TAXEXEMPT" BOOLEAN NOT NULL, "IS_VOID" BOOLEAN NOT NULL, "IS_REFUND" BOOLEAN NOT NULL, "LOAD_ID" INTEGER NOT NULL, "LAST_UPDATE_DATE_TIME" TIMESTAMP NOT NULL);



/* <sc-table> DIM_AUDITEVENT </sc-table> */

CREATE TABLE IF NOT EXISTS "DIM_AUDITEVENT" ("EVENT_KEY" INTEGER, "EVENT_ID" INTEGER, "EVENT_NAME" VARCHAR(255), "EVENT_DESC" VARCHAR(255), "THRESHOLD_DEFAULT" DECIMAL(18,2), "THRESHOLD_RELATIVE" DECIMAL(18,2), "LOAD_ID" INTEGER, "LAST_UPDATE_DATE_TIME" TIMESTAMP);



/* <sc-table> DIM_DATE </sc-table> */

CREATE TABLE IF NOT EXISTS "DIM_DATE" ("DATE_KEY" INTEGER NOT NULL, "DATE_ID" INTEGER NOT NULL, "DAYS_COUNT" INTEGER NOT NULL, "DAYS_DATE" DATE, "DAYS_TEXT" CHAR(8), "DAYS_NUMBER" INTEGER, "DATE_RTI" INTEGER, "FISCAL_YEAR_START_DAYS_COUNT" INTEGER NOT NULL, "FISCAL_YEAR_START_DATE" DATE, "FISCAL_YEAR_END_DAYS_COUNT" INTEGER NOT NULL, "FISCAL_YEAR_END_DATE" DATE, "FISCAL_DAYS_IN_YEAR_QUANTITY" SMALLINT, "FISCAL_DAY_IN_YEAR_NUMBER" SMALLINT, "FISCAL_DAYS_LEFT_IN_YEAR_QUANTITY" SMALLINT, "FISCAL_YEAR" SMALLINT, "FISCAL_PERIOD_NUMBER" TINYINT NOT NULL, "FISCAL_YEAR_NAME" CHAR(13), "FISCAL_YY_YEAR_NAME" CHAR(11), "FISCAL_YEAR_SHORT_NAME" CHAR(5), "FISCAL_YY_SHORT_NAME" CHAR(3), "FISCAL_QUARTER_NUMBER" TINYINT, "FISCAL_QUARTER_START_DAYS_COUNT" INTEGER, "FISCAL_QUARTER_START_DATE" DATE, "FISCAL_QUARTER_END_DAYS_COUNT" INTEGER, "FISCAL_QUARTER_END_DATE" DATE, "FISCAL_DAYS_IN_QUARTER_QUANTITY" TINYINT, "FISCAL_DAYS_IN_QUARTER_NUMBER" TINYINT, "FISCAL_DAYS_LEFT_IN_QUARTER_QUANTITY" TINYINT, "FISCAL_QUARTER_NAME" CHAR(11), "FISCAL_QUARTER_SHORT_NAME" CHAR(2), "FISCAL_PERIOD_START_DAYS_COUNT" INTEGER NOT NULL, "FISCAL_PERIOD_START_DATE" DATE, "FISCAL_PERIOD_START_DATE_INT" INTEGER, "FISCAL_PERIOD_END_DAYS_COUNT" INTEGER NOT NULL, "FISCAL_PERIOD_END_DATE" DATE, "FISCAL_DAYS_IN_PERIOD_QUANTITY" TINYINT, "FISCAL_DAY_IN_PERIOD_NUMBER" TINYINT, "FISCAL_DAYS_LEFT_IN_PERIOD_QUANTITY" TINYINT, "FISCAL_WEEKS_IN_PERIOD_QUANTITY" TINYINT, "FISCAL_WEEK_IN_PERIOD_NUMBER" TINYINT, "FISCAL_WEEK_IN_PERIOD_NAME" CHAR(6), "FISCAL_WEEK_IN_SHORT_PERIOD_NAME" CHAR(2), "FISCAL_PERIOD_NAME" CHAR(9), "FISCAL_PERIOD_SHORT_NAME" CHAR(3), "FISCAL_WEEKS_IN_YEAR_QUANTITY" TINYINT, "FISCAL_WEEK_NUMBER" TINYINT, "FISCAL_WEEKS_IN_QUARTER_QUANTITY" TINYINT, "FISCAL_WEEK_START_DAYS_COUNT" INTEGER, "FISCAL_WEEK_START_DATE" DATE, "FISCAL_WEEK_START_DATE_INT" INTEGER, "FISCAL_WEEK_END_DAYS_COUNT" INTEGER, "FISCAL_WEEK_END_DATE" DATE, "FISCAL_DAY_IN_WEEK_NUMBER" TINYINT, "FISCAL_COMPARISON_DAYS_COUNT" INTEGER, "FISCAL_COMPARISON_DATE" DATE, "CALENDAR_YEAR" SMALLINT, "CALENDAR_MONTH_NUMBER" TINYINT, "CALENDAR_MONTH_NAME" CHAR(9), "CALENDAR_SHORT_MONTH_NAME" CHAR(3), "CALENDAR_DAYS_IN_MONTH_NUMBER" TINYINT, "CALENDAR_DAYS_IN_YEAR_QUANTITY" SMALLINT, "CALENDAR_DAY_IN_YEAR_NUMBER" SMALLINT, "CALENDAR_DAYS_LEFT_IN_YEAR_QUANTITY" SMALLINT, "CALENDAR_YEAR_START_DAYS_COUNT" INTEGER, "CALENDAR_YEAR_START_DATE" DATE, "CALENDAR_YEAR_END_DAYS_COUNT" INTEGER, "CALENDAR_YEAR_END_DATE" DATE, "CALENDAR_QUARTER_NUMBER" TINYINT, "CALENDAR_QUARTER_NAME" CHAR(9), "CALENDAR_ABBREVIATED_QUARTER_NAME" CHAR(2), "CALENDAR_DAYS_IN_QUARTER_NUMBER" TINYINT, "CALENDAR_QUARTER_START_DAYS_COUNT" INTEGER, "CALENDAR_QUARTER_START_DATE" DATE, "CALENDAR_QUARTER_END_DAYS_COUNT" INTEGER, "CALENDAR_QUARTER_END_DATE" DATE, "CALENDAR_DAYS_IN_QUARTER_QUANTITY" TINYINT, "CALENDAR_DAYS_LEFT_IN_QUARTER_QUANTITY" TINYINT, "CALENDAR_MONTH_START_DAYS_COUNT" INTEGER, "CALENDAR_MONTH_START_DATE" DATE, "CALENDAR_MONTH_END_DAYS_COUNT" INTEGER, "CALENDAR_MONTH_END_DATE" DATE, "CALENDAR_DAYS_IN_MONTH_QUANTITY" TINYINT, "CALENDAR_DAYS_LEFT_IN_MONTH_QUANTITY" TINYINT, "CALENDAR_WEEK_IN_YEAR_NUMBER" TINYINT, "CALENDAR_DAY_IN_WEEK_NUMBER" TINYINT, "WEEKDAY_FLAG" BOOLEAN, "WEEKEND_FLAG" BOOLEAN, "CALENDAR_DAY_NAME" CHAR(9), "CALENDAR_SHORT_DAY_NAME" CHAR(3), "CALENDAR_WEEK_START_DAYS_COUNT" INTEGER, "CALENDAR_WEEK_START_DATE" DATE, "CALENDAR_WEEKEND_DAYS_COUNT" INTEGER, "CALENDAR_WEEKEND_DATE" DATE, "CALENDAR_WEEK_NAME" VARCHAR(7), "CALENDAR_SHORT_WEEK_NAME" CHAR(3), "ISO_WEEK_NAME" CHAR(8), "ISO_ORD_DATE_NAME" VARCHAR(8), "CALENDAR_SAME_DAY_LAST_YEAR_DAYS_COUNT" INTEGER, "CALENDAR_SAME_DAY_LAST_YEAR_DATE" DATE, "FISCAL_QUARTER_ID" VARCHAR(50), "FISCAL_PERIOD_ID" VARCHAR(50), "CALENDAR_QUARTER_ID" VARCHAR(50), "CALENDAR_MONTH_ID" VARCHAR(50), "ADJUSTED_COMPARISON_DATE" DATE, "ADJUSTED_WEEK_START_DATE" DATE, "ADJUSTED_WEEK_END_DATE" DATE, "ADJUSTED_PERIOD_START_DATE" DATE, "ADJUSTED_PERIOD_END_DATE" DATE, "ADJUSTED_QUARTER_START_DATE" DATE, "ADJUSTED_QUARTER_END_DATE" DATE, "ADJUSTED_YEAR_START_DATE" DATE, "ADJUSTED_YEAR_END_DATE" DATE, "IS_CHRISTMAS_DAY" INTEGER, "IS_FISCAL_COMP_CHRISTMAS_DAY" INTEGER, "IS_CALENDAR_COMP_CHRISTMAS_DAY" INTEGER, "THANKSGIVING_DATE" DATE, "IS_FISCAL_COMP_THANKSGIVING_DAY" INTEGER, "IS_CALENDAR_COMP_THANKSGIVING_DAY" INTEGER, "IS_NEWYEARS_DAY" INTEGER, "IS_MLKINGS_BIRTHDAY" INTEGER, "IS_VALENTINES_DAY" INTEGER, "IS_ASHWEDNESDAY" INTEGER, "IS_STPATRICKS_DAY" INTEGER, "IS_GOODFRIDAY" INTEGER, "IS_EASTER" INTEGER, "IS_CINCODEMAYO" INTEGER, "IS_MOTHERS_DAY" INTEGER, "IS_FATHERS_DAY" INTEGER, "IS_INDEPENDENCE_DAY" INTEGER, "IS_LABOR_DAY" INTEGER, "IS_THANKSGIVING_DAY" INTEGER, "IS_CYBERMONDAY" INTEGER, "IS_CHRISTMAS_EVE" INTEGER, "IS_NEWYEARS_EVE" INTEGER, "IS_LENT" INTEGER, "IS_SUPERBOWL_DAY" INTEGER, "IS_MEMORIAL_DAY" INTEGER, "LOAD_ID" INTEGER, "LAST_UPDATE_DATE_TIME" TIMESTAMP);



/* <sc-table> FACT_SPEEDOFSERVICE </sc-table> */

CREATE TABLE IF NOT EXISTS "FACT_SPEEDOFSERVICE" ("FACT_SOS_KEY" INTEGER NOT NULL, "TIME_KEY" INTEGER NOT NULL, "DATE_KEY" INTEGER NOT NULL, "RESTAURANT_KEY" INTEGER NOT NULL, "TIME_ACCUMULATED" INTEGER, "ORDER_COUNT" INTEGER, "CARS_OVER_7MINS" INTEGER, "WINDOW_TIME" INTEGER, "ORDER_PAD_TIME" INTEGER, "REST_SNBR" VARCHAR(5), "LOAD_ID" INTEGER NOT NULL, "LAST_UPDATE_DATE_TIME" TIMESTAMP);



/* <sc-table> FACT_PROJECTEDSALES_REST_DAY_AGG </sc-table> */

CREATE TABLE IF NOT EXISTS "FACT_PROJECTEDSALES_REST_DAY_AGG" ("DATE_KEY" INTEGER NOT NULL, "RESTAURANT_KEY" INTEGER NOT NULL, "PROJECTION_TYPE" INTEGER NOT NULL, "SALESAMT_TY" DECIMAL(18,2), "SALESAMT_LY" DECIMAL(18,2), "TANSACTIONCOUNT_TY" INTEGER, "TRANSACTIONCOUNT_LY" INTEGER, "REST_SNBR" VARCHAR(5), "LOAD_ID" INTEGER NOT NULL, "LAST_UPDATE_DATE_TIME" TIMESTAMP NOT NULL);



/* <sc-table> FACT_PROMOTIONS_WEEK </sc-table> */

CREATE TABLE IF NOT EXISTS "FACT_PROMOTIONS_WEEK" ("DATE_KEY" INTEGER, "ITEM_PRODUCT_ID" INTEGER, "REST_DMA_CODE" INTEGER, "PRIMARY_TV" VARCHAR(60), "SECONDARY_TV" VARCHAR(60), "INSTORE" VARCHAR(60));



/* <sc-table> DIM_AUV </sc-table> */

CREATE TABLE IF NOT EXISTS "DIM_AUV" ("AUV_KEY" INTEGER NOT NULL, "AUV_DESC" VARCHAR(50), "LOW_VALUE" DECIMAL(18,2), "HIGH_VALUE" DECIMAL(18,2), "LOAD_ID" INTEGER, "LAST_UPDATE_DATE_TIME" TIMESTAMP);
