ALTER SESSION SET QUOTED_IDENTIFIERS_IGNORE_CASE = FALSE;

/* <sc-table> FACT_PNLSUMMARY_DETAIL_PERIOD </sc-table> */

CREATE TABLE IF NOT EXISTS "FACT_PNLSUMMARY_DETAIL_PERIOD" ("PNLSUMMARY_DETAIL_PERIOD_KEY" INTEGER NOT NULL, "FISCAL_PERIOD_NUMBER" TINYINT NOT NULL, "FISCAL_YEAR" SMALLINT, "REST_NUMBER" VARCHAR(10) NOT NULL, "ACCOUNT_SORT_NUMBER" SMALLINT NOT NULL, "CHILD_ACCOUNT_NUMBER" VARCHAR(55) NOT NULL, "CHILD_ACCOUNT_TYPE" VARCHAR(20) NOT NULL, "CHILD_ACCOUNT_DESC" VARCHAR(255) NOT NULL, "PARENT_ACCOUNT_NUMBER" VARCHAR(55) NOT NULL, "PARENT_ACCOUNT_DESC" VARCHAR(255) NOT NULL, "LINE_NUMBER" INTEGER NOT NULL, "LINE_NAME" VARCHAR(100) NOT NULL, "LINE_DESCRIPTION" VARCHAR(255), "INVOICE_NUMBER" VARCHAR(55), "INVOICE_DATE" DATE, "VENDOR_NAME" VARCHAR(100), "BATCH_NAME" VARCHAR(100), "SOURCE_NAME" VARCHAR(100), "ACTUAL_PTD_AMOUNT" DECIMAL(36,2), "ISACTIVE_STORE_VIEW" BOOLEAN NOT NULL, "ISACTIVE_AREA_VIEW" BOOLEAN NOT NULL, "ISACTIVE_DISTRICT_VIEW" BOOLEAN NOT NULL, "LOAD_ID" INTEGER NOT NULL, "LAST_UPDATE_DATE_TIME" TIMESTAMP NOT NULL);



/* <sc-table> DIM_SURVEY_QUESTION </sc-table> */

CREATE TABLE IF NOT EXISTS "DIM_SURVEY_QUESTION" ("QUESTION_KEY" INTEGER NOT NULL, "QUESTION_NUMBER" INTEGER, "TYPE" VARCHAR(50), "CATEGORY" VARCHAR(500), "DESCRIPTION" VARCHAR(1000), "CHOICE_NUMBER" INTEGER, "CHOICE_TEXT" VARCHAR(250), "LIKERT_SCORE" INTEGER, "BRAND_SCORE" INTEGER, "SORT" INTEGER, "LOADID" INTEGER, "CURRENT_RECORD" BOOLEAN, "EFFECTIVE_DATE" TIMESTAMP, "EXPIRY_DATE" TIMESTAMP);



/* <sc-table> TEMP2 </sc-table> */

CREATE TABLE IF NOT EXISTS "TEMP2" ("OLDKEY" DECIMAL(6,0), "NEWKEY" DECIMAL(6,0));



/* <sc-table> DIM_PNLACCOUNT </sc-table> */

CREATE TABLE IF NOT EXISTS "DIM_PNLACCOUNT" ("PNLACCOUNT_KEY" INTEGER NOT NULL, "ACCOUNT_NUMBER" VARCHAR(55), "ACCOUNT_DESC" VARCHAR(255), "ACCOUNT_TYPE" VARCHAR(20), "ISPARENT" BOOLEAN, "ISACTIVE" BOOLEAN, "LOAD_ID" INTEGER NOT NULL, "LAST_UPDATE_DATE_TIME" TIMESTAMP NOT NULL);



/* <sc-table> DIM_MENUITEM </sc-table> */

CREATE TABLE IF NOT EXISTS "DIM_MENUITEM" (
    MENU_KEY              DECIMAL(18,0),
    PLU_NUMBER            VARCHAR(25) ,
    PLU_DESC              VARCHAR(100) ,
    PROMO_CODE            VARCHAR(25) ,
    PROMO_DESC            VARCHAR(100) ,
    POS_NAME              VARCHAR(10) ,
    POS_ITEM_DESC         VARCHAR(255) ,
    ITEM_ID               DECIMAL(18,0),
    ITEM_DESC             VARCHAR(255) ,
    ITEM_PRODUCT_ID       DECIMAL(18,0),
    ITEM_PRODUCT_DESC     VARCHAR(255) ,
    ITEM_TYPE_CODE        VARCHAR(255) ,
    COMPONENT_ID          DECIMAL(18,0),
    COMPONENT_NAME        VARCHAR(255) ,
    COUPON_NAME           VARCHAR(55) ,
    COUPON_TYPE           VARCHAR(25) ,
    OFFER_ITEM            VARCHAR(255) ,
    MENU_GROUP            VARCHAR(255) ,
    MENU_TYPE             VARCHAR(255) ,
    MAIN_GROUP            VARCHAR(255) ,
    MAIN_PROTEIN          VARCHAR(255) ,
    EFFECTIVE_BEGIN_DATE  DATE,
    EFFECTIVE_END_DATE    DATE,
    ISCURRENT             BOOLEAN,
    INFERRED_FLAG         BOOLEAN,
    LOAD_ID               DECIMAL(18,0),
    LAST_UPDATE_DATE_TIME TIMESTAMP
);



/* <sc-table> TEMP1 </sc-table> */

CREATE TABLE IF NOT EXISTS "TEMP1" ("OLDKEY" INTEGER, "NEWKEY" INTEGER);



/* <sc-table> FACT_SPEEDOFSERVICE_TEST </sc-table> */

CREATE TABLE IF NOT EXISTS "FACT_SPEEDOFSERVICE_TEST" ("FACT_SOS_KEY" INTEGER NOT NULL, "TIME_KEY" INTEGER NOT NULL, "DATE_KEY" INTEGER NOT NULL, "RESTAURANT_KEY" INTEGER NOT NULL, "TIME_ACCUMULATED" INTEGER, "ORDER_COUNT" INTEGER, "CARS_OVER_7MINS" INTEGER, "WINDOW_TIME" INTEGER, "ORDER_PAD_TIME" INTEGER, "REST_SNBR" VARCHAR(5), "LOAD_ID" INTEGER NOT NULL, "LAST_UPDATE_DATE_TIME" TIMESTAMP);



/* <sc-table> FACT_COMPSALES_DAILY </sc-table> */

CREATE TABLE IF NOT EXISTS "FACT_COMPSALES_DAILY" ("COMPSALES_DAILY_KEY" INTEGER NOT NULL, "DATE_KEY" INTEGER NOT NULL, "RESTAURANT_KEY" INTEGER NOT NULL, "REST_NUMBER" VARCHAR(10) NOT NULL, "SALESAMT_TY_TY" DECIMAL(18,2) NOT NULL, "TRANSCNT_TY_TY" INTEGER NOT NULL, "SALESAMT_LY_TY" DECIMAL(18,2) NOT NULL, "TRANSCNT_LY_TY" INTEGER NOT NULL, "SALESAMT_TY_LY" DECIMAL(18,2) NOT NULL, "TRANSCNT_TY_LY" INTEGER NOT NULL, "SALESAMT_LY_LY" DECIMAL(18,2) NOT NULL, "TRANSCNT_LY_LY" INTEGER NOT NULL, "LOAD_ID" INTEGER NOT NULL, "LAST_UPDATE_DATE_TIME" TIMESTAMP NOT NULL);



/* <sc-table> DIM_EMPLOYEE </sc-table> */

CREATE TABLE IF NOT EXISTS "DIM_EMPLOYEE" ("EMPLOYEE_KEY" INTEGER NOT NULL, "EMPLOYEE_ID" INTEGER, "EMPLOYEE_NAME" VARCHAR(255), "POS_NAME" VARCHAR(10), "ADDRESS" VARCHAR(255), "CITY" VARCHAR(255), "State" VARCHAR(255), "ZIP" VARCHAR(10), "EMAIL" VARCHAR(255), "PHONE" VARCHAR(255), "HIRE_DATE" TIMESTAMP, "JOB_TITLE" VARCHAR(255), "PAY_RATE" DECIMAL(18,2), "EFFECTIVE_BEGIN_DATE" DATE, "EFFECTIVE_END_DATE" DATE, "IS_CURRENT" BOOLEAN, "IS_TERMINATED" BOOLEAN, "TERMINATION_DATE" TIMESTAMP, "LOAD_ID" INTEGER NOT NULL, "LAST_UPDATE_DATE_TIME" TIMESTAMP NOT NULL);



/* <sc-table> FACT_AUDITEDSALES </sc-table> */

CREATE TABLE IF NOT EXISTS "FACT_AUDITEDSALES" ("FACT_SALES_KEY" INTEGER NOT NULL, "DATE_KEY" INTEGER NOT NULL, "RESTAURANT_KEY" INTEGER NOT NULL, "SALES_AMOUNT" DECIMAL(18,2), "TRANSACTION_COUNT" INTEGER, "LOAD_ID" INTEGER, "LAST_UPDATE_DATE_TIME" TIMESTAMP, "REST_SNBR" VARCHAR(5));
