ALTER SESSION SET QUOTED_IDENTIFIERS_IGNORE_CASE = FALSE;

/* <sc-table> DIM_POINTOFSALE </sc-table> */

CREATE TABLE IF NOT EXISTS "DIM_POINTOFSALE" ("POS_KEY" INTEGER NOT NULL, "POS_NAME" VARCHAR(50), "LOAD_ID" INTEGER, "LAST_UPDATE_DATE_TIME" TIMESTAMP);



/* <sc-table> FACT_WEEKLYSALES_COMP </sc-table> */

CREATE TABLE IF NOT EXISTS "FACT_WEEKLYSALES_COMP" ("REST_NUMBER" VARCHAR(10), "FISCAL_YEAR" INTEGER, "FISCAL_WEEK_NUMBER" INTEGER, "FISCAL_PERIOD_NUMBER" INTEGER NOT NULL, "FISCAL_WEEK_IN_PERIOD_NUMBER" INTEGER, "FISCAL_WEEK_START_DATE" DATE, "FISCAL_WEEK_END_DATE" DATE, "FISCAL_QUARTER_START_DATE" DATE, "FISCAL_QUARTER_END_DATE" DATE, "FISCAL_QUARTER_NUMBER" INTEGER, "FISCAL_PERIOD_START_DATE" DATE, "FISCAL_PERIOD_END_DATE" DATE, "FISCAL_WEEKS_IN_PERIOD_QUANTITY" INTEGER, "Fiscal QTD" CHAR(3) NOT NULL, "PTD" CHAR(3) NOT NULL, "Fiscal YTD" CHAR(10) NOT NULL, "FWTD" CHAR(4) NOT NULL, "FWTD-1" CHAR(4) NOT NULL, "FISCAL_COMP_START_DATE" DATE, "FISCAL_COMP_END_DATE" DATE, "ADJUSTED_COMP_START_DATE" DATE, "ADJUSTED_COMP_END_DATE" DATE, "REST_DMA_CODE" INTEGER, "REST_DMA_DESC" CHAR(100), "Region Name" CHAR(255), "SubRegion Name" CHAR(255), "District Name" CHAR(255), "District Number" CHAR(55), "District Nbr Abbrev" CHAR(3), "Area Name" CHAR(255), "Rest Name" CHAR(255), "SVP" CHAR(255), "VPO" CHAR(255), "DO" CHAR(255), "Area Supervisor" CHAR(255), "LATITUDE" CHAR(55), "LONGITUDE" CHAR(55), "SALESDAYS" INTEGER NOT NULL, "COMP_DAYS_TY" INTEGER NOT NULL, "COMP_DAYS_LY" INTEGER NOT NULL, "COMP_DAYS_TY_ADJ" INTEGER NOT NULL, "COMP_DAYS_LY_ADJ" INTEGER NOT NULL, "COMP_DAYS_TY_TRANS" INTEGER NOT NULL, "COMP_DAYS_LY_TRANS" INTEGER NOT NULL, "COMP_DAYS_TY_ADJ_TRANS" INTEGER NOT NULL, "COMP_DAYS_LY_ADJ_TRANS" INTEGER NOT NULL, "Comp Sales TY_TY" DECIMAL(18,2), "Comp Sales LY_TY" DECIMAL(18,2), "Comp Sales TY_LY" DECIMAL(18,2), "Comp Sales LY_LY" DECIMAL(18,2), "Comp Sales TY_TYadj" DECIMAL(18,2), "Comp Sales LY_TYadj" DECIMAL(18,2), "Comp Sales TY_LYadj" DECIMAL(18,2), "Comp Sales LY_LYadj" DECIMAL(18,2), "Comp Trans TY_TY" BIGINT, "Comp Trans LY_TY" DECIMAL(18,2), "Comp Trans TY_TYadj" BIGINT, "Comp Trans LY_TYadj" DECIMAL(18,2), "Comp Trans TY_LY" DECIMAL(18,2), "Comp Trans LY_LY" BIGINT, "Comp Trans TY_LYadj" DECIMAL(18,2), "Comp Trans LY_LYadj" BIGINT, "Comp Sales for Check TY_TY" DECIMAL(18,2), "Comp Sales for Check LY_TY" DECIMAL(36,2), "Comp Sales for Check TY_TYadj" DECIMAL(18,2), "Comp Sales for Check LY_TYadj" DECIMAL(36,2), "Comp Sales for Check TY_LY" DECIMAL(18,2), "Comp Sales for Check LY_LY" DECIMAL(18,2), "Comp Sales for Check TY_LYadj" DECIMAL(18,2), "Comp Sales for Check LY_LYadj" DECIMAL(18,2), "Comp Sales TY_PY" DECIMAL(18,2), "Comp Sales LY_PY" DECIMAL(18,2), "Comp Sales TY_PYadj" DECIMAL(18,2), "Comp Sales LY_PYadj" DECIMAL(18,2), "Comp Trans TY_PY" BIGINT, "Comp Trans LY_PY" BIGINT, "Comp Trans TY_PYadj" BIGINT, "Comp Trans LY_PYadj" BIGINT, "Net Food Sales TY_TY" DECIMAL(18,2), "Net Food Sales LY_TY" DECIMAL(18,2), "Net Food Sales TY_LY" DECIMAL(18,2), "Net Food Sales LY_LY" DECIMAL(18,2), "Net Food Sales TY_LYadj" DECIMAL(18,2), "Net Food Sales LY_LYadj" DECIMAL(18,2), "Net Food Sales TY_PY" DECIMAL(18,2), "Net Food Sales LY_PY" DECIMAL(18,2), "Net Food Sales TY_PYadj" DECIMAL(18,2), "Net Food Sales LY_PYadj" DECIMAL(18,2), "Net Trans TY_TY" BIGINT, "Net Trans LY_TY" DECIMAL(18,2), "Net Trans TY_LY" DECIMAL(18,2), "Net Trans LY_LY" BIGINT, "Net Trans TY_LYadj" DECIMAL(18,2), "Net Trans LY_LYadj" BIGINT, "Net Trans TY_PY" BIGINT, "Net Trans LY_PY" BIGINT, "Net Trans TY_PYadj" BIGINT, "Net Trans LY_PYadj" BIGINT, "ADJSALESAMT_LY" DECIMAL(18,2), "ADJSALESAMT_2YAGO" DECIMAL(18,2), "ACQUISITION_FISCAL_SALES_LY" DECIMAL(36,2), "ACQUISITION_ADJUSTED_SALES_LY" DECIMAL(36,2), "ACQUISITION_DATE" TIMESTAMP, "Net CY Sales Complete Week ONLY" DECIMAL(18,2), "Net CY Trans Complete Week ONLY" DECIMAL(18,2), "DIVESTITURE_DATE" TIMESTAMP, "LOAD_ID" INTEGER, "LAST_UPDATE_DATE_TIME" TIMESTAMP);



/* <sc-table> DIM_SURVEY_XREF_SURVEY_TAG </sc-table> */

CREATE TABLE IF NOT EXISTS "DIM_SURVEY_XREF_SURVEY_TAG" ("SURVEY_TAG_KEY" INTEGER NOT NULL, "SURVEY_KEY" INTEGER NOT NULL, "LOADID" INTEGER);



/* <sc-table> FACT_SALES_ORDER_PAYMENT </sc-table> */

CREATE TABLE IF NOT EXISTS "FACT_SALES_ORDER_PAYMENT" ("SALES_PAYMENT_KEY" INTEGER NOT NULL, "DATE_KEY" INTEGER NOT NULL, "TIME_KEY" INTEGER NOT NULL, "RESTAURANT_KEY" INTEGER NOT NULL, "POS_KEY" INTEGER NOT NULL, "ORDER_ID" VARCHAR(50) NOT NULL, "ORDER_NUMBER" INTEGER, "PAYMENT_TYPE_ID" INTEGER, "PAYMENT_DESC" VARCHAR(55), "PAYMENT_AUTH_ID" VARCHAR(55), "PAYMENT_LAST4" VARCHAR(11), "PAYMENT_NAME" VARCHAR(55), "PAYMENT_AMOUNT" DECIMAL(18,2), "IS_VOID" BOOLEAN NOT NULL, "LOAD_ID" INTEGER, "LAST_UPDATE_DATE_TIME" TIMESTAMP);



/* <sc-table> DIM_RESTAURANT </sc-table> */

CREATE TABLE IF NOT EXISTS "DIM_RESTAURANT" ("RESTAURANT_KEY" INTEGER, "REST_NUMBER" VARCHAR(10), "REST_NAME" VARCHAR(255), "REST_STATUS" VARCHAR(10), "REST_TYPE" VARCHAR(10), "REST_FRAN_NUMBER" DECIMAL(19,0), "REST_FRAN_NAME" VARCHAR(255), "REST_FRANENTITY_NUMBER" DECIMAL(19,0), "REST_FRANENTITY_NAME" VARCHAR(255), "REST_COMPANY_NAME" VARCHAR(255), "REST_BRAND_NAME" VARCHAR(255), "REST_BRAND_ISACTIVE" BOOLEAN, "REST_DMA_CODE" INTEGER, "REST_DMA_DESC" VARCHAR(100), "REST_ISAIRPORT" BOOLEAN, "REST_ISVIDEOSURV" BOOLEAN, "REST_ISBREAKFAST" BOOLEAN, "REST_IS24HR" BOOLEAN, "REST_ISMALL" BOOLEAN, "REST_ISDRIVETHRU" BOOLEAN, "REST_ADDRLINE1" VARCHAR(255), "REST_ADDRLINE2" VARCHAR(255), "REST_ADDRLINE3" VARCHAR(255), "REST_ADDRCITY" VARCHAR(255), "REST_ADDRCOUNTY" VARCHAR(255), "REST_ADDRSTATE" VARCHAR(2), "REST_ADDRPROVINCE" VARCHAR(25), "REST_ADDRZIP" VARCHAR(10), "REST_COUNTRY" VARCHAR(10), "REST_ADDRPHONE" VARCHAR(25), "REST_LANDLORDPHONE" VARCHAR(25), "REST_ALERTCCEMAIL" VARCHAR(8000), "REST_DIVISION" VARCHAR(50), "REST_LATITUDE" VARCHAR(55), "REST_LONGITUDE" VARCHAR(55), "REST_BUILDINGTYPE" VARCHAR(55), "REST_REMODELPROG_NAME" VARCHAR(255), "REST_REMODELDT" INTEGER, "REST_ACQUISITIONDT" INTEGER, "REST_POSTYPE" VARCHAR(55), "REST_COMP_ISELIGIBLE" BOOLEAN, "REST_COMP_ISTEMPCLOSURE" BOOLEAN, "REST_COMP_DATE" DATE, "REST_OPENDATE" DATE, "REST_TEMP_CLOSEDATE" DATE, "REST_TEMP_OPENDATE" DATE, "REST_TEMPCLOSUREREASON" VARCHAR(100), "REST_CLOSEDATE" DATE, "REST_FACILITYTYPE" VARCHAR(55), "REST_SITETYPE" VARCHAR(20), "REST_TIMEZONE" VARCHAR(100), "REST_SYSTEM_TIMEZONE" VARCHAR(100), "REST_UNITTRADEAREA" VARCHAR(100), "REST_SEATCOUNT" INTEGER, "REST_PARKINGCOUNT" INTEGER, "REST_SQUAREFT" VARCHAR(55), "REST_CSRASSIGNED_NAME" VARCHAR(255), "REST_CSRASSIGNED_EMAIL" VARCHAR(100), "REST_CSRDEFAULT_NAME" VARCHAR(255), "REST_CSRDEFAULT_EMAIL" VARCHAR(100), "REST_DISTCENTER_NAME" VARCHAR(255), "REST_DISTACCOUNT_NUMBER" VARCHAR(255), "REST_BAKERY_NAME" VARCHAR(255), "REST_LICENSE_NUMBER" VARCHAR(55), "REST_LICENSEEXECDATE" INTEGER, "REST_LICENSEEXPDATE" INTEGER, "REST_AFA_PERC" DECIMAL(11,4), "REST_ROYALTY_PER" DECIMAL(11,4), "REST_L1EMAIL" VARCHAR(100), "REST_L2NAME" VARCHAR(255), "REST_L2EMAIL" VARCHAR(100), "REST_L2PHONE" VARCHAR(25), "REST_L3NAME" VARCHAR(255), "REST_L3EMAIL" VARCHAR(100), "REST_L3PHONE" VARCHAR(25), "REST_L4NAME" VARCHAR(255), "REST_L4EMAIL" VARCHAR(100), "REST_L4PHONE" VARCHAR(25), "REST_L5NAME" VARCHAR(255), "REST_L5EMAIL" VARCHAR(100), "REST_L5PHONE" VARCHAR(25), "REST_L6NAME" VARCHAR(255), "REST_L6EMAIL" VARCHAR(100), "REST_L6PHONE" VARCHAR(25), "ARG_AREA_NUMBER" VARCHAR(55), "ARG_AREA_DESC" VARCHAR(255), "ARG_AREA_NAME" VARCHAR(255), "ARG_AREA_NUMBER_ABBR" VARCHAR(3), "ARG_DISTRICT_NUMBER" VARCHAR(55), "ARG_DISTRICT_DESC" VARCHAR(255), "ARG_DISTRICT_NAME" VARCHAR(255), "ARG_DISTRICT_NUMBER_ABBR" VARCHAR(3), "ARG_SUBREGION_NUMBER" VARCHAR(55), "ARG_SUBREGION_DESC" VARCHAR(255), "ARG_SUBREGION_NAME" VARCHAR(255), "ARG_SUBREGION_NUMBER_ABBR" VARCHAR(3), "ARG_REGION_NUMBER" VARCHAR(55), "ARG_REGION_DESC" VARCHAR(255), "ARG_REGION_NAME" VARCHAR(255), "ARG_REGION_NUMBER_ABBR" VARCHAR(3), "ARG_AREA_SUPERVISOR" VARCHAR(255), "ARG_AREA_SUPERVISOR_EMAIL" VARCHAR(100), "ARG_AREA_SUPERVISOR_PHONE" VARCHAR(25), "ARG_DO_NAME" VARCHAR(255), "ARG_DO_EMAIL" VARCHAR(100), "ARG_DO_PHONE" VARCHAR(25), "ARG_VPO_NAME" VARCHAR(255), "ARG_VPO_EMAIL" VARCHAR(100), "ARG_VPO_PHONE" VARCHAR(25), "ARG_SVP_NAME" VARCHAR(255), "ARG_SVP_EMAIL" VARCHAR(100), "ARG_SVP_PHONE" VARCHAR(25), "FRAN_TC_NAME" VARCHAR(255), "FRAN_TC_EMAIL" VARCHAR(100), "FRAN_OC_NAME" VARCHAR(255), "FRAN_OC_EMAIL" VARCHAR(100), "FRAN_DFO_NAME" VARCHAR(255), "FRAN_DFO_EMAIL" VARCHAR(100), "FRAN_CONTACT_NAME" VARCHAR(255), "FRAN_EMAIL" VARCHAR(100), "FRAN_PHONE1" VARCHAR(25), "FRAN_PHONE2" VARCHAR(25), "FRAN_ADDRLINE1" VARCHAR(255), "FRAN_ADDRCITY" VARCHAR(255), "FRAN_ADDRSTATE" VARCHAR(2), "FRAN_ADDRZIP" VARCHAR(10), "FRAN_ADDRCOUNTRY" VARCHAR(10), "EFFECTIVE_BEGIN_DATE" DATE, "EFFECTIVE_END_DATE" DATE, "ISCURRENT" BOOLEAN, "INFERRED_FLAG" BOOLEAN, "LOAD_ID" INTEGER, "LAST_UPDATE_DATE_TIME" TIMESTAMP);



/* <sc-table> FACT_PNLSUMMARY_PERIOD </sc-table> */

CREATE TABLE IF NOT EXISTS "FACT_PNLSUMMARY_PERIOD" ("PNLSUMMARY_PERIOD_KEY" INTEGER NOT NULL, "FISCAL_PERIOD_NUMBER" TINYINT NOT NULL, "FISCAL_YEAR" SMALLINT, "REST_NUMBER" VARCHAR(10) NOT NULL, "ACCOUNT_SORT_NUMBER" SMALLINT NOT NULL, "CHILD_ACCOUNT_NUMBER" VARCHAR(55) NOT NULL, "CHILD_ACCOUNT_TYPE" VARCHAR(20) NOT NULL, "CHILD_ACCOUNT_DESC" VARCHAR(255) NOT NULL, "PARENT_ACCOUNT_NUMBER" VARCHAR(55) NOT NULL, "PARENT_ACCOUNT_DESC" VARCHAR(255) NOT NULL, "ACTUAL_PTD_AMOUNT" DECIMAL(36,2), "BUDGET_PTD_AMOUNT" DECIMAL(36,2), "ISACTIVE_STORE_VIEW" BOOLEAN NOT NULL, "ISACTIVE_AREA_VIEW" BOOLEAN NOT NULL, "ISACTIVE_DISTRICT_VIEW" BOOLEAN NOT NULL, "LOAD_ID" INTEGER NOT NULL, "LAST_UPDATE_DATE_TIME" TIMESTAMP NOT NULL);



/* <sc-table> DIM_CHECKSIZE </sc-table> */

CREATE TABLE IF NOT EXISTS "DIM_CHECKSIZE" ("CHECKSIZE_KEY" INTEGER NOT NULL, "CHECKSIZE_DESC" VARCHAR(50), "LOW_VALUE" DECIMAL(18,2), "HIGH_VALUE" DECIMAL(18,2), "LOAD_ID" INTEGER, "LAST_UPDATE_DATE_TIME" TIMESTAMP);



/* <sc-table> FACT_SALES_DAY_YOY </sc-table> */

CREATE TABLE IF NOT EXISTS "FACT_SALES_DAY_YOY" ("SALES_DAY_YOY_KEY" INTEGER NOT NULL, "DATE_KEY" INTEGER NOT NULL, "RESTAURANT_KEY" INTEGER NOT NULL, "REST_NUMBER" VARCHAR(10) NOT NULL, "SALESAMT_TY" DECIMAL(18,2) NOT NULL, "TRANSCNT_TY" INTEGER NOT NULL, "SALESAMT_LY" DECIMAL(18,2) NOT NULL, "SALESAMT_LY_ADJ" DECIMAL(18,2) NOT NULL, "TRANSCNT_LY" INTEGER NOT NULL, "TRANSCNT_LY_ADJ" INTEGER NOT NULL, "SALESAMT_PY" DECIMAL(18,2) NOT NULL, "SALESAMT_PY_ADJ" DECIMAL(18,2) NOT NULL, "TRANSCNT_PY" INTEGER NOT NULL, "TRANSCNT_PY_ADJ" INTEGER NOT NULL, "IS_AUDITED" BOOLEAN NOT NULL, "LOAD_ID" INTEGER NOT NULL, "LAST_UPDATE_DATE_TIME" TIMESTAMP NOT NULL);



/* <sc-table> FACT_SURVEY_RESULT </sc-table> */

CREATE TABLE IF NOT EXISTS "FACT_SURVEY_RESULT" ("SURVEY_RESULT_KEY" INTEGER NOT NULL, "SURVEYDT_KEY" INTEGER NOT NULL, "SURVEY_KEY" INTEGER NOT NULL, "QUESTION_KEY" INTEGER NOT NULL, "COMMENT_KEY" INTEGER NOT NULL, "EXCLUSION_KEY" INTEGER NOT NULL, "RESPONSE_TEXT" VARCHAR(100), "POINTS_POSSIBLE" INTEGER, "POINTS" INTEGER, "INMOMENT_SCORE" INTEGER, "LIKERT_SCORE" INTEGER, "ADJUSTED_SCORE" INTEGER, "LOADID" INTEGER);



/* <sc-table> FACT_SALES_ITEM_WEEK </sc-table> */

CREATE TABLE IF NOT EXISTS "FACT_SALES_ITEM_WEEK" ("ITEM_WEEK_KEY" INTEGER NOT NULL, "DATE_KEY" INTEGER NOT NULL, "RESTAURANT_KEY" INTEGER NOT NULL, "MENU_KEY" INTEGER NOT NULL, "GROSS_QUANTITY" INTEGER NOT NULL, "GROSS_ORDER_COUNT" INTEGER NOT NULL, "GROSS_AMOUNT" DECIMAL(18,2) NOT NULL, "NET_AMOUNT" DECIMAL(18,2) NOT NULL, "DISCOUNT_AMOUNT" DECIMAL(18,2) NOT NULL, "NET_ORDER_AMOUNT" DECIMAL(18,2) NOT NULL, "LOAD_ID" INTEGER, "LAST_UPDATE_DATE_TIME" TIMESTAMP);



/* <sc-table> FACT_COMPSALES_PERIOD </sc-table> */

CREATE TABLE IF NOT EXISTS "FACT_COMPSALES_PERIOD" ("COMPSALES_PERIOD_KEY" BIGINT NOT NULL, "DATE_KEY" INTEGER NOT NULL, "RESTAURANT_KEY" INTEGER NOT NULL, "REST_NUMBER" VARCHAR(10) NOT NULL, "SALES_TYPE" VARCHAR(3) NOT NULL, "SALESAMT_TY_TY" DECIMAL(18,2) NOT NULL, "SALESAMT_LCL_TY_TY" DECIMAL(18,2) NOT NULL, "TRANSCNT_TY_TY" INTEGER NOT NULL, "SALESAMT_LY_TY" DECIMAL(18,2) NOT NULL, "SALESAMT_LCL_LY_TY" DECIMAL(18,2) NOT NULL, "TRANSCNT_LY_TY" INTEGER NOT NULL, "SALESAMT_TY_LY" DECIMAL(18,2) NOT NULL, "SALESAMT_LCL_TY_LY" DECIMAL(18,2) NOT NULL, "TRANSCNT_TY_LY" INTEGER NOT NULL, "SALESAMT_LY_LY" DECIMAL(18,2) NOT NULL, "SALESAMT_LCL_LY_LY" DECIMAL(18,2) NOT NULL, "TRANSCNT_LY_LY" INTEGER NOT NULL, "LOAD_ID" INTEGER NOT NULL, "LAST_UPDATE_DATE_TIME" TIMESTAMP NOT NULL);



/* <sc-table> FACT_SALES_ORDER_HALFHR </sc-table> */

CREATE TABLE IF NOT EXISTS "FACT_SALES_ORDER_HALFHR" ("ORDER_HALFHR_KEY" INTEGER NOT NULL, "DATE_KEY" INTEGER NOT NULL, "TIME_KEY" INTEGER NOT NULL, "DAYPART_KEY" INTEGER NOT NULL, "RESTAURANT_KEY" INTEGER NOT NULL, "POS_KEY" INTEGER NOT NULL, "POP_KEY" INTEGER NOT NULL, "GUEST_COUNT" INTEGER NOT NULL, "GROSS_QUANTITY" INTEGER NOT NULL, "GROSS_AMOUNT" DECIMAL(18,2) NOT NULL, "DISCOUNT_AMOUNT" DECIMAL(18,2) NOT NULL, "NET_AMOUNT" DECIMAL(18,2) NOT NULL, "SURCHARGE_AMOUNT" DECIMAL(18,2) NOT NULL, "TAX_AMOUNT" DECIMAL(18,2) NOT NULL, "PAYMENT_AMOUNT" DECIMAL(18,2) NOT NULL, "LOAD_ID" INTEGER NOT NULL, "LAST_UPDATE_DATE_TIME" TIMESTAMP NOT NULL);



/* <sc-table> FACT_AUDIT </sc-table> */

CREATE TABLE IF NOT EXISTS "FACT_AUDIT" ("AUDIT_ORDER_KEY" BIGINT, "EVENT_KEY" INTEGER, "DATE_KEY" INTEGER, "RESTAURANT_KEY" INTEGER, "EMPLOYEE_KEY" INTEGER, "ORDER_ID" VARCHAR(255), "Value" DECIMAL(18,2), "LOAD_ID" INTEGER, "LAST_UPDATE_DATE_TIME" TIMESTAMP);



/* <sc-table> FACT_SALES_ORDER_LINE </sc-table> */

CREATE TABLE IF NOT EXISTS "FACT_SALES_ORDER_LINE" ("SALES_ORDER_ITEM_KEY" INTEGER NOT NULL, "DATE_KEY" INTEGER NOT NULL, "TIME_KEY" INTEGER NOT NULL, "RESTAURANT_KEY" INTEGER NOT NULL, "POS_KEY" INTEGER NOT NULL, "POP_KEY" INTEGER NOT NULL, "MENU_KEY" INTEGER NOT NULL, "DISCOUNT_KEY" INTEGER NOT NULL, "ORDER_ID" VARCHAR(50) NOT NULL, "ORDER_NUMBER" INTEGER, "REGISTER_ID" VARCHAR(55), "LINE_ITEM_ID" INTEGER, "PARENT_LINE_ITEM_ID" INTEGER, "PRICE" DECIMAL(18,2), "GROSS_QUANTITY" INTEGER, "NET_QUANTITY" INTEGER, "GROSS_AMOUNT" DECIMAL(18,2), "NET_AMOUNT" DECIMAL(18,2), "DISCOUNT_AMOUNT" DECIMAL(18,2), "IS_MODIFIER" BOOLEAN NOT NULL, "IS_COMBO" BOOLEAN NOT NULL, "IS_COUPON" BOOLEAN NOT NULL, "IS_CLEAR" BOOLEAN NOT NULL, "IS_VOID" BOOLEAN NOT NULL, "IS_REFUND" BOOLEAN NOT NULL, "LOAD_ID" INTEGER, "LAST_UPDATE_DATE_TIME" TIMESTAMP);



/* <sc-table> DIM_TIME </sc-table> */

CREATE TABLE IF NOT EXISTS "DIM_TIME" ("TIME_KEY" INTEGER, "TIME_OF_DAY_TIME" TIMESTAMP, "MERIDIEM_INDICATOR" VARCHAR(2), "US_TIME_TEXT" VARCHAR(11), "ISO_TIME_TEXT" VARCHAR(8), "DAY_PART_TEXT" VARCHAR(25), "HH24HRS" INTEGER, "HH12HRS" INTEGER, "MINUTES" INTEGER, "SECONDS" INTEGER, "PAST_MIDNIGHT_SECONDS" INTEGER, "PAST_MIDNIGHT_MINUTES" INTEGER, "OPERATIONS_DAY_PART_INDICATOR" VARCHAR(6), "LOAD_ID" INTEGER, "LAST_UPDATE_DATE_TIME" TIMESTAMP);



/* <sc-table> DIM_DAYPART </sc-table> */

CREATE TABLE IF NOT EXISTS "DIM_DAYPART" ("DAYPART_KEY" INTEGER, "DAYPART_DESCRIPTION" VARCHAR(100), "START_TIME" VARCHAR(16), "END_TIME" VARCHAR(16), "SORT_NUMBER" INTEGER, "EFFECTIVE_START_DATE" DATE, "EFFECTIVE_END_DATE" DATE, "ISCURRENT" BOOLEAN, "LOAD_ID" INTEGER, "LAST_UPDATE_DATE_TIME" TIMESTAMP);



/* <sc-table> FACT_SPEEDOFSERVICE_BYCAR </sc-table> */

CREATE TABLE IF NOT EXISTS "FACT_SPEEDOFSERVICE_BYCAR" ("FACT_SOS_BYCAR_KEY" BIGINT, "RESTAURANT_KEY" INTEGER, "DATE_KEY" INTEGER, "SPEAKER_ARR_DATEKEY" INTEGER, "SPEAKER_ARR_TIMEKEY" INTEGER, "SPEAKER_DEPART_DATEKEY" INTEGER, "SPEAKER_DEPART_TIMEKEY" INTEGER, "WINDOW_ARR_DATEKEY" INTEGER, "WINDOW_ARR_TIMEKEY" INTEGER, "WINDOW_DEPART_DATEKEY" INTEGER, "WINDOW_DEPART_TIMEKEY" INTEGER, "LOAD_ID" INTEGER, "LAST_UPDATE_DATE_TIME" TIMESTAMP);



/* <sc-table> FACT_COMPSALES_WEEK </sc-table> */

CREATE TABLE IF NOT EXISTS "FACT_COMPSALES_WEEK" ("COMPSALES_WEEK_KEY" BIGINT NOT NULL, "DATE_KEY" INTEGER NOT NULL, "RESTAURANT_KEY" INTEGER NOT NULL, "REST_NUMBER" VARCHAR(10), "SALESAMT_TY_TY" DECIMAL(18,2), "SALESAMT_TY_TY_ADJ" DECIMAL(18,2), "TRANSCNT_TY_TY" INTEGER, "TRANSCNT_TY_TY_ADJ" INTEGER, "SALESAMT_LY_TY" DECIMAL(18,2), "SALESAMT_LY_TY_ADJ" DECIMAL(18,2), "TRANSCNT_LY_TY" INTEGER, "TRANSCNT_LY_TY_ADJ" INTEGER, "SALESAMT_TY_LY" DECIMAL(18,2), "SALESAMT_TY_LY_ADJ" DECIMAL(18,2), "TRANSCNT_TY_LY" INTEGER, "TRANSCNT_TY_LY_ADJ" INTEGER, "SALESAMT_LY_LY" DECIMAL(18,2), "SALESAMT_LY_LY_ADJ" DECIMAL(18,2), "TRANSCNT_LY_LY" INTEGER, "TRANSCNT_LY_LY_ADJ" INTEGER, "LOADID" INTEGER NOT NULL, "LASTUPDDTTM" TIMESTAMP NOT NULL);



/* <sc-table> DIM_SURVEY_TAG </sc-table> */

CREATE TABLE IF NOT EXISTS "DIM_SURVEY_TAG" ("SURVEY_TAG_KEY" INTEGER NOT NULL, "TAG" VARCHAR(100), "EFFECTIVE_DATE" DATE, "EXPIRY_DATE" DATE, "CURRENT_RECORD" BOOLEAN, "LOADID" INTEGER);



/* <sc-table> FACT_SALES_PERIOD_YOY </sc-table> */

CREATE TABLE IF NOT EXISTS "FACT_SALES_PERIOD_YOY" ("SALES_PERIOD_YOY_KEY" INTEGER NOT NULL, "DATE_KEY" INTEGER NOT NULL, "RESTAURANT_KEY" INTEGER NOT NULL, "REST_NUMBER" VARCHAR(10) NOT NULL, "SALES_TYPE" VARCHAR(3) NOT NULL, "SALESAMT_TY" DECIMAL(18,2) NOT NULL, "SALESAMT_LCL_TY" DECIMAL(18,2) NOT NULL, "TRANSCNT_TY" INTEGER NOT NULL, "SALESAMT_LY" DECIMAL(18,2) NOT NULL, "SALESAMT_LCL_LY" DECIMAL(18,2) NOT NULL, "TRANSCNT_LY" INTEGER NOT NULL, "SALESAMT_PY" DECIMAL(18,2) NOT NULL, "SALESAMT_LCL_PY" DECIMAL(18,2) NOT NULL, "TRANSCNT_PY" INTEGER NOT NULL, "LOAD_ID" INTEGER NOT NULL, "LAST_UPDATE_DATE_TIME" TIMESTAMP NOT NULL);



/* <sc-table> DIM_POINTOFPURCHASE </sc-table> */

CREATE TABLE IF NOT EXISTS "DIM_POINTOFPURCHASE" ("POP_KEY" INTEGER NOT NULL, "POP_DESC" VARCHAR(255), "LOAD_ID" INTEGER, "LAST_UPDATE_DATE_TIME" TIMESTAMP);



/* <sc-table> DIM_DISCOUNT </sc-table> */

CREATE TABLE IF NOT EXISTS "DIM_DISCOUNT" ("DISCOUNT_KEY" INTEGER, "DISCOUNT_NUMBER" INTEGER, "DISCOUNT_DESC" VARCHAR(255), "DISCOUNT_POSSOURCE" VARCHAR(10), "DISCOUNT_TYPE" INTEGER, "DISCOUNT_TYPE_DESC" VARCHAR(255), "EFFECTIVE_BEGIN_DATE" DATE, "EFFECTIVE_END_DATE" DATE, "ISCURRENT" BOOLEAN, "INFERRED_FLAG" BOOLEAN, "LOAD_ID" INTEGER, "LAST_UPDATE_DATE_TIME" TIMESTAMP);



/* <sc-table> FACT_SALES_DAYPART_YOY </sc-table> */

CREATE TABLE IF NOT EXISTS "FACT_SALES_DAYPART_YOY" ("SALES_DAYPART_YOY_KEY" BIGINT NOT NULL, "DATE_KEY" INTEGER NOT NULL, "DAYPART_KEY" INTEGER NOT NULL, "RESTAURANT_KEY" INTEGER NOT NULL, "REST_NUMBER" VARCHAR(10) NOT NULL, "POP_KEY" INTEGER NOT NULL, "SALESAMT_TY" DECIMAL(18,2) NOT NULL, "TRANSCNT_TY" INTEGER NOT NULL, "SALESAMT_LY" DECIMAL(18,2) NOT NULL, "SALESAMT_LY_ADJ" DECIMAL(18,2) NOT NULL, "TRANSCNT_LY" INTEGER NOT NULL, "TRANSCNT_LY_ADJ" INTEGER NOT NULL, "SALESAMT_PY" DECIMAL(18,2) NOT NULL, "SALESAMT_PY_ADJ" DECIMAL(18,2) NOT NULL, "TRANSCNT_PY" INTEGER NOT NULL, "TRANSCNT_PY_ADJ" INTEGER NOT NULL, "LOAD_ID" INTEGER NOT NULL, "LAST_UPDATE_DATE_TIME" TIMESTAMP NOT NULL);



/* <sc-table> FACT_SALES_WEEK_YOY </sc-table> */

CREATE TABLE IF NOT EXISTS "FACT_SALES_WEEK_YOY" ("SALES_WEEK_YOY_KEY" INTEGER NOT NULL, "DATE_KEY" INTEGER NOT NULL, "RESTAURANT_KEY" INTEGER NOT NULL, "REST_NUMBER" VARCHAR(10) NOT NULL, "SALESAMT_TY" DECIMAL(18,2) NOT NULL, "TRANSCNT_TY" INTEGER NOT NULL, "SALESAMT_LY" DECIMAL(18,2) NOT NULL, "SALESAMT_LY_ADJ" DECIMAL(18,2) NOT NULL, "TRANSCNT_LY" INTEGER NOT NULL, "TRANSCNT_LY_ADJ" INTEGER NOT NULL, "SALESAMT_PY" DECIMAL(18,2) NOT NULL, "SALESAMT_PY_ADJ" DECIMAL(18,2) NOT NULL, "TRANSCNT_PY" INTEGER NOT NULL, "TRANSCNT_PY_ADJ" INTEGER NOT NULL, "LOAD_ID" INTEGER NOT NULL, "LAST_UPDATE_DATE_TIME" TIMESTAMP NOT NULL);



/* <sc-table> FACT_COMPSALES_DAYPART </sc-table> */

CREATE TABLE IF NOT EXISTS "FACT_COMPSALES_DAYPART" ("COMPSALES_DAYPART_KEY" BIGINT NOT NULL, "DATE_KEY" INTEGER NOT NULL, "DAYPART_KEY" INTEGER NOT NULL, "RESTAURANT_KEY" INTEGER NOT NULL, "REST_NUMBER" VARCHAR(10) NOT NULL, "POP_KEY" INTEGER NOT NULL, "SALESAMT_TY_TY" DECIMAL(18,2) NOT NULL, "SALESAMT_TY_TY_ADJ" DECIMAL(18,2) NOT NULL, "TRANSCNT_TY_TY" INTEGER NOT NULL, "TRANSCNT_TY_TY_ADJ" INTEGER NOT NULL, "SALESAMT_LY_TY" DECIMAL(18,2) NOT NULL, "SALESAMT_LY_TY_ADJ" DECIMAL(18,2) NOT NULL, "TRANSCNT_LY_TY" INTEGER NOT NULL, "TRANSCNT_LY_TY_ADJ" INTEGER NOT NULL, "SALESAMT_TY_LY" DECIMAL(18,2) NOT NULL, "SALESAMT_TY_LY_ADJ" DECIMAL(18,2) NOT NULL, "TRANSCNT_TY_LY" INTEGER NOT NULL, "TRANSCNT_TY_LY_ADJ" INTEGER NOT NULL, "SALESAMT_LY_LY" DECIMAL(18,2) NOT NULL, "SALESAMT_LY_LY_ADJ" DECIMAL(18,2) NOT NULL, "TRANSCNT_LY_LY" INTEGER NOT NULL, "TRANSCNT_LY_LY_ADJ" INTEGER NOT NULL, "LOAD_ID" INTEGER NOT NULL, "LAST_UPDATE_DATE_TIME" TIMESTAMP NOT NULL);



/* <sc-table> TESTING </sc-table> */

CREATE TABLE IF NOT EXISTS "TESTING" ("ID" INTEGER);

