create TABLE IF NOT EXISTS FLYWAY_SCHEMA_HISTORY (
	INSTALLED_RANK NUMBER(38,0) NOT NULL,
	VERSION VARCHAR(50),
	DESCRIPTION VARCHAR(200),
	TYPE VARCHAR(20) NOT NULL,
	SCRIPT VARCHAR(1000) NOT NULL,
	CHECKSUM NUMBER(38,0),
	INSTALLED_BY VARCHAR(100) NOT NULL,
	INSTALLED_ON TIMESTAMP_LTZ(9) NOT NULL DEFAULT CURRENT_TIMESTAMP(),
	EXECUTION_TIME NUMBER(38,0) NOT NULL,
	SUCCESS BOOLEAN NOT NULL,
	primary key (INSTALLED_RANK)
);
create view IF NOT EXISTS CUSTOMER(
	BRAND_ID,
	MEMBER_INSPIRE_ID,
	MEMBER_ID,
	LOYALTY_PROGRAM_ID,
	CLOSEST_REST_ID,
	HOUSEHOLD_ID,
	EMAIL_ID,
	MOBILE_DEVICE_ID,
	EXPERIAN_ID,
	EXPERIAN_STATUS_TXT,
	INSPIRE_CUSTOMER_TYPE,
	MDM_ID,
	MDM_ID_DELETED_IND,
	LOYALTY_CARD_NBR,
	FIRST_NAME,
	LAST_NAME,
	MIDDLE_INITIAL_TXT,
	DATE_OF_BIRTH,
	BIRTH_MONTH,
	BIRTH_YR,
	IS_BIRTH_DATE_IMPLIED_IND,
	GENDER,
	ENROLLMENT_CHANNEL_TYPE,
	MEMBER_STATUS_CODE,
	POINT_BALANCE,
	MEMBERSHIP_STATUS_CODE,
	PROFILE_COMPLETED_STATUS_IND,
	DELIVERABILITY_STATUS,
	MOBILE_NBR,
	ADDRESS_LINE1_TXT,
	ADDRESS_LINE2_TXT,
	CITY,
	STATE_CODE,
	ZIP_CODE,
	COUNTRY_CODE,
	EMAIL_OPT_OUT_IND,
	PUSH_NOTIFICATION_OPT_IN,
	SMS_OPT_IN,
	PRIVACY_IND,
	UNSUBSCRIBE_DATE,
	POINTS_EXPIRE_DATE,
	ENROLL_START_DATE,
	LAST_LOGIN_DATE,
	LAST_STATUS_CHANGE_DATE,
	PROFILE_COMPLETION_DATE,
	SUBSCRIBER_KEY,
	SUBSCRIBER_SOURCE_NAME,
	LOYALTY_TIER_CHANGE_DTTM,
	LOYALTY_TIER_NAME,
	LOYALTY_TIER_EXPIRATION_DATE,
	LOYALTY_ELITE_VISIT_CNT,
	SOURCE_SYSTEM_NAME,
	CDM_LOAD_DATE,
	LOAD_ID,
	LOAD_DTTM,
	UPDATE_ID,
	UPDATE_DTTM,
	PUSH_DEVICE_ID,
	MEMBER_STATUS_DESC,
	ADDRESS_OPT_IN,
	IGNORE_FRAUD_SUSPEND_IND
) as 
SELECT c.BRAND_ID AS BRAND_ID
, c.MBR_INSPIRE_ID AS MEMBER_INSPIRE_ID
, c.MBR_ID AS MEMBER_ID
, c.LOYALTY_PROGRAM_ID AS LOYALTY_PROGRAM_ID
, c.CLOSEST_STORE_ID AS CLOSEST_REST_ID
, c.HOUSEHOLD_ID AS HOUSEHOLD_ID
, c.EMAIL_ID AS EMAIL_ID
, c.MOBILE_DEVICE_ID AS MOBILE_DEVICE_ID
, c.EXPERIAN_ID AS EXPERIAN_ID
, c.EXPERIAN_STATUS_TYP AS EXPERIAN_STATUS_TXT
, c.INSPIRE_CUST_TYP AS INSPIRE_CUSTOMER_TYPE
, c.MDM_ID AS MDM_ID
, c.MDM_ID_DELETED_IND AS MDM_ID_DELETED_IND
, c.LOYALTY_CARD_NBR AS LOYALTY_CARD_NBR
, c.FIRST_NM AS FIRST_NAME
, c.LAST_NM AS LAST_NAME
, c.MIDDLE_INITIAL_TXT AS MIDDLE_INITIAL_TXT
, c.DOB_DT AS DATE_OF_BIRTH
, c.BIRTH_MNTH_ID AS BIRTH_MONTH
, c.BIRTH_YEAR_ID AS BIRTH_YR
, c.BIRTH_DT_IMPLIED_IND AS IS_BIRTH_DATE_IMPLIED_IND
, c.GENDER_TYP AS GENDER
, c.ENROLLMENT_CHANNEL_TYP AS ENROLLMENT_CHANNEL_TYPE
, CASE WHEN S.SUBSCRIBER_KEY IS NOT NULL THEN S.CUSTOMER_STATUS_TYPE_CD ELSE COALESCE(CS.CUSTOMER_STATUS_TYPE_CD,c.MBR_STATUS_CD,'NA') END AS MEMBER_STATUS_CODE
, c.POINT_BALANCE_QTY AS POINT_BALANCE
, c.MEMBERSHIP_STATUS_CD AS MEMBERSHIP_STATUS_CODE
, c.PROFILE_COMPLETED_STATUS_IND AS PROFILE_COMPLETED_STATUS_IND
, c.DELIVERABILITY_STATUS_IND AS DELIVERABILITY_STATUS
, c.MOBILE_NBR AS MOBILE_NBR
, c.ADR_LINE_1_TXT AS ADDRESS_LINE1_TXT
, c.ADR_LINE_2_TXT AS ADDRESS_LINE2_TXT
, c.CTY_NM AS CITY
, c.ST_CD AS STATE_CODE
, c.ZIP_CD AS ZIP_CODE
, c.CNTRY_CD AS COUNTRY_CODE
, c.EMAIL_OPT_OUT_IND AS EMAIL_OPT_OUT_IND
, c.PUSH_NOTIFICATION_OPT_IN_IND AS PUSH_NOTIFICATION_OPT_IN
, c.SMS_OPT_IN_IND AS SMS_OPT_IN
, c.PRIVACY_IND AS PRIVACY_IND
, c.UNSUBSCRIBE_DTTM AS UNSUBSCRIBE_DATE
, c.POINT_EXPIRE_DTTM AS POINTS_EXPIRE_DATE
, c.ENROLL_START_DTTM AS ENROLL_START_DATE
, c.LAST_LOGIN_DTTM AS LAST_LOGIN_DATE
, c.LAST_STATUS_CHANGE_DTTM AS LAST_STATUS_CHANGE_DATE
, c.PROFILE_COMPLETION_DTTM AS PROFILE_COMPLETION_DATE
, c.SUBSCRIBER_KEY AS SUBSCRIBER_KEY
, c.SUBSCRIBER_SOURCE_NM AS SUBSCRIBER_SOURCE_NAME
, c.LOYALTY_TIER_CHANGE_DTTM AS LOYALTY_TIER_CHANGE_DTTM
, c.LOYALTY_TIER_NM AS LOYALTY_TIER_NAME
, c.LOYALTY_TIER_EXPIRATION_DT AS LOYALTY_TIER_EXPIRATION_DATE
, c.LOYALTY_ELITE_VISIT_CNT AS LOYALTY_ELITE_VISIT_CNT
, c.SOURCE_SYSTEM_NM AS SOURCE_SYSTEM_NAME
, c.CDM_LOAD_DT AS CDM_LOAD_DATE
, c.LOAD_ID AS LOAD_ID
, c.LOAD_DTTM AS LOAD_DTTM
, c.UPDATE_ID AS UPDATE_ID
, c.UPDATE_DTTM AS UPDATE_DTTM
, c.PUSH_DEVICE_ID AS PUSH_DEVICE_ID
, CASE WHEN S.SUBSCRIBER_KEY IS NOT NULL THEN T.CUSTOMER_STATUS_DESC ELSE COALESCE(T2.CUSTOMER_STATUS_DESC,c.MBR_STATUS_CD,'NA') END AS MEMBER_STATUS_DESC
, c.ADDRESS_OPT_IN_IND AS ADDRESS_OPT_IN
, c.IGNORE_FRAUD_SUSPEND_IND AS IGNORE_FRAUD_SUSPEND_IND
FROM IDM_DEV.COREDIM_BV.CUSTOMER_BV c
LEFT JOIN IDM_DEV.COREDIM.CUSTOMER_ARCHIVE_STATUS S ON c.SUBSCRIBER_KEY = S.SUBSCRIBER_KEY AND S.CUSTOMER_STATUS_EXPIRY_DT = '9999-12-31'
LEFT JOIN IDM_DEV.COREDIM.CUSTOMER_STATUS_TYPE_DIM T ON S.CUSTOMER_STATUS_TYPE_CD = T.CUSTOMER_STATUS_TYPE_CD
LEFT JOIN IDM_DEV.COREDIM.CUSTOMER_STATUS CS ON c.MBR_INSPIRE_ID = CS.CUSTOMER_ID AND S.CUSTOMER_STATUS_EXPIRY_DT = '9999-12-31'
LEFT JOIN IDM_DEV.COREDIM.CUSTOMER_STATUS_TYPE_DIM T2 ON CS.CUSTOMER_STATUS_TYPE_CD = T2.CUSTOMER_STATUS_TYPE_CD;
create view IF NOT EXISTS CUSTOMER_ENRICHMENT(
	BRAND_ID,
	AGENCY_ID,
	SOURCE,
	UE_SEQ_NBR,
	MATCH_LEVEL,
	MATCH_ADDRESS,
	ACT_INT_CASINO_GAMBLING_NBR,
	ACT_INT_EATS_AT_FAMILY_RESTAURANTS_NBR,
	ACT_INT_EATS_AT_FAST_FOOD_RESTAURANTS_NBR,
	ACT_INT_SNOW_SPORTS_NBR,
	ACT_INT_SPORTS_ENTHUSIAST_NBR,
	PERSON_1_FIRST_NAME,
	PERSON_1_MIDDLE_INITIAL_V2,
	PERSON_1_NAME_PREFIX,
	PERSON_1_NAME_SUFFIX,
	PERSON_1_BIRTH_YR_AND_MONTH,
	BUYER_IMPORTED_BEER_ENTHUSIAST,
	CAPE_INDUS_EMPLD_ACCOMODATION_AND_FOOD_SVCS,
	CAPE_OCCUP_EMPLD_ARTS_DSGN_ENTER_SPORTS_MEDIA,
	CAPE_OCCUP_EMPLD_FOOD_PREP_AND_SERVING,
	CONSUMER_SPEND_DINING_OUT_SCORE,
	DEMAND_20100_GROCERIES,
	DEMAND_20130_ALCOHOLIC_BEVERAGES_SERVED,
	DEMAND_20140_PACKAGED_LIQUOR_WINE_BEER,
	DEMAND_20530_SPORTING_GOODS,
	DEMAND_20800_PETS_PET_FOODS_SUPPLIES,
	DEMAND_445_FOOD_BEVERAGE_STORES,
	DEMAND_4452_SPECIALTY_FOOD_STORES,
	DEMAND_4453_BEER_WINE_LIQUOR_STORES,
	DEMAND_451_SPORTING_GOODS_HOBBY_BOOK_MUSIC,
	DEMAND_4511_SPORTING_GOODS_HOBBY_MUSIC_INSTRUM,
	DEMAND_45111_SPORTING_GOODS_STORES,
	DEMAND_722_FOOD_SERVICE_DRINKING_PLACES,
	DEMAND_7223_SPECIAL_FOOD_SERVICES,
	DEMAND_7224_DRINKING_PLACE_ALCOHOLIC_BEVERAGES,
	TRAN_EXTREME_SNOWSPORTS_DOLLAR,
	TRAN_EXTREME_SNOWSPORTS_FREQUENCY,
	TRAN_EXTREME_SNOWSPORTS_RECENCY,
	TRAN_EXTREME_SNOWSPORTS_SCORE,
	TRAN_FOOD_SNACKS_DOLLAR,
	TRAN_FOOD_SNACKS_FREQUENCY,
	TRAN_FOOD_SNACKS_RECENCY,
	TRAN_FOOD_SNACKS_SCORE,
	HOMEOWNER_PROBABILITY_MODEL,
	HOUSEHOLD_CONSUMER_EXPENDITURES_FOOD_BEV,
	LENGTH_OF_RESIDENCE,
	ONLINE_FOOD_BEVERAGES,
	RETAIL_FOOD_BEVERAGES,
	PERSON_1_SURNAME,
	PRIMARY_ADDRESS,
	SECONDARY_ADDRESS,
	CITY_ABBR,
	ZIP_CODE,
	PERSON_2_BIRTH_YR_AND_MONTH,
	PERSON_2_FIRST_NAME,
	PERSON_2_MIDDLE_INITIAL_V2,
	PERSON_2_NAME_PREFIX,
	PERSON_2_NAME_SUFFIX,
	PERSON_2_SURNAME,
	PERSON_3_BIRTH_YR_AND_MONTH,
	PERSON_3_FIRST_NAME,
	PERSON_3_MIDDLE_INITIAL_V2,
	PERSON_3_NAME_PREFIX,
	PERSON_3_NAME_SUFFIX,
	PERSON_3_SURNAME,
	PERSON_4_BIRTH_YR_AND_MONTH,
	PERSON_4_FIRST_NAME,
	PERSON_4_MIDDLE_INITIAL_V2,
	PERSON_4_NAME_PREFIX,
	PERSON_4_NAME_SUFFIX,
	PERSON_4_SURNAME,
	PERSON_5_BIRTH_YR_AND_MONTH,
	PERSON_5_FIRST_NAME,
	PERSON_5_MIDDLE_INITIAL_V2,
	PERSON_5_NAME_PREFIX,
	PERSON_5_NAME_SUFFIX,
	PERSON_5_SURNAME,
	PERSON_6_BIRTH_YR_AND_MONTH,
	PERSON_6_FIRST_NAME,
	PERSON_6_MIDDLE_INITIAL_V2,
	PERSON_6_NAME_PREFIX,
	PERSON_6_NAME_SUFFIX,
	PERSON_6_SURNAME,
	PERSON_7_BIRTH_YR_AND_MONTH,
	PERSON_7_FIRST_NAME,
	PERSON_7_MIDDLE_INITIAL_V2,
	PERSON_7_NAME_PREFIX,
	PERSON_7_NAME_SUFFIX,
	PERSON_7_SURNAME,
	PERSON_8_BIRTH_YR_AND_MONTH,
	PERSON_8_FIRST_NAME,
	PERSON_8_MIDDLE_INITIAL_V2,
	PERSON_8_NAME_PREFIX,
	PERSON_8_NAME_SUFFIX,
	PERSON_8_SURNAME,
	PERSON_1_EDUCATION_MODEL,
	PERSON_1_MARITAL_STATUS,
	MOSAIC_GLOBAL_ZIP4,
	MOSAIC_ZIP4,
	NBR_OF_ADULTS_IN_LIVING_UNIT,
	NBR_OF_CHILDREN_IN_LIVING_UNIT,
	DWELLING_TYPE,
	MOR_BANK_OPPORTUNITY_SEEKERS_CONTESTS,
	MOR_BANK_PHOTOGRAPHY,
	MOR_BANK_NEWS_AND_FINANCIAL,
	MOR_BANK_DO_IT_YOURSELFERS,
	RECIPIENT_RELIABILITY_CODE,
	HOMEOWNER_COMBINED_HOMEOWNER_RENTER,
	BEHAVIORBANK_CONTRIBUTES_TO_CHARITIES,
	BEHAVIORBANK_PET_ENTHUSIAST,
	BEHAVIORBANK_INTEREST_IN_TRAVEL,
	BEHAVIORBANK_PRESENCE_OF_CREDIT_CARD,
	BEHAVIORBANK_INTEREST_IN_GARDENING,
	BEHAVIORBANK_INTEREST_IN_SPORTS,
	BEHAVIORBANK_INTEREST_IN_GOURMET_COOKING,
	BEHAVIORBANK_INTEREST_IN_READING,
	BEHAVIORBANK_DONATES_TO_ENVIRONMENTAL_CAUSES,
	BEHAVIORBANK_DOG_ENTHUSIASTS,
	BEHAVIORBANK_CAT_ENTHUSIASTS,
	BEHAVIORBANK_INTEREST_IN_AUTOMOTIVE,
	BEHAVIORBANK_COMPUTERS_PERIPHERALS,
	BEHAVIORBANK_HOME_DECORATING_FURNISHING,
	DWELLING_UNIT_SIZE,
	CHILDREN_AGE_0_3,
	CHILDREN_AGE_4_6,
	CHILDREN_AGE_7_9,
	CHILDREN_AGE_10_12,
	CHILDREN_AGE_13_15,
	CHILDREN_AGE_16_18,
	CHILDREN_PRESENCE_OF_CHILD_0_18,
	SRVY_HH_ACTY_INT_COLLECTING_SPORTS_MEMORABILIA,
	SRVY_HH_ACTY_INT_HEALTH_FITNESS_HLTH_NAT_FOODS,
	SRVY_HH_ACTY_INT_READING_SPORTS_READING,
	SRVY_HH_ACTY_INT_SPORTS_REC_BASEBALL,
	SRVY_HH_ACTY_INT_SPORTS_REC_BASKETBALL,
	SRVY_HH_ACTY_INT_SPORTS_REC_HOCKEY,
	SRVY_HH_ACTY_INT_SPORTS_REC_CAMPING_HIKING,
	SRVY_HH_ACTY_INT_SPORTS_REC_HUNTING,
	SRVY_HH_ACTY_INT_SPORTS_REC_FISHING,
	SRVY_HH_ACTY_INT_SPORTS_REC_NASCAR,
	SRVY_HH_ACTY_INT_SPORTS_REC_PERSONAL_FITNESS_EXER,
	SRVY_HH_ACTY_INT_SPORTS_REC_SCUBA_DIVING,
	SRVY_HH_ACTY_INT_SPORTS_REC_FOOTBALL,
	SRVY_HH_ACTY_INT_SPORTS_REC_GOLF,
	SRVY_HH_ACTY_INT_SPORTS_REC_SNOW_SKIING_BOARDING,
	SRVY_HH_ACTY_INT_SPORTS_REC_BOATING_SAILING,
	SRVY_HH_ACTY_INT_SPORTS_REC_WALKING,
	SRVY_HH_ACTY_INT_SPORTS_REC_CYCLING,
	SRVY_HH_ACTY_INT_SPORTS_REC_MOTORCYCLES,
	SRVY_HH_ACTY_INT_SPORTS_REC_RUNNING_JOGGING,
	SRVY_HH_ACTY_INT_SPORTS_REC_SOCCER,
	SRVY_HH_ACTY_INT_SPORTS_REC_SWIMMING,
	SRVY_HH_ACTY_INT_SPORTS_REC_PLAY_SPORTS_IN_GENERA,
	SRVY_HH_ACTY_INT_SWEEPSTAKES_SWEEPSTAKES,
	SRVY_HH_ACTY_INT_SWEEPSTAKES_LOTTERIES,
	SRVY_HH_ACTY_INT_SWEEPSTAKES_CASINO_GAMBLING,
	SRVY_HH_ACTY_INT_MAGAZINES_FOOD_WINE_COOKING,
	SRVY_HH_ACTY_INT_MAGAZINES_SPORTS_MAGAZINES,
	SRVY_HH_LIFESTYL_BUYING_SPORTS_RELATED,
	NBR_OF_PERSONS_IN_LIVING_UNIT,
	STATE_ABBR,
	PERSON_1_BUSINESS_OWNER,
	PERSON_1_COMBINED_AGE,
	PERSON_1_ETHNIC_COUNTRY_OF_ORIGIN,
	PERSON_1_ETHNIC_ETHNIC,
	PERSON_1_ETHNIC_GROUP,
	PERSON_1_ETHNIC_RELIGION,
	PERSON_1_GENDER,
	PERSON_1_OCCUPATION_CODE,
	PERSON_1_PERSON_TYPE,
	PERSON_1_ETHNIC_LANGUAGE_PREFERENCE,
	PERSON_1_OCCUPATION_GROUP_V2,
	CONSUMER_SPEND_DINING_OUT,
	ESTIMATED_HOUSEHOLD_INCOME_RANGE_CODE_V6,
	PERSON_2_EDUCATION_MODEL,
	PERSON_2_MARITAL_STATUS,
	PERSON_2_BUSINESS_OWNER,
	PERSON_2_COMBINED_AGE,
	PERSON_2_GENDER,
	PERSON_2_OCCUPATION_CODE,
	PERSON_2_PERSON_TYPE,
	PERSON_2_OCCUPATION_GROUP_V2,
	PERSON_3_EDUCATION_MODEL,
	PERSON_3_MARITAL_STATUS,
	PERSON_3_BUSINESS_OWNER,
	PERSON_3_COMBINED_AGE,
	PERSON_3_GENDER,
	PERSON_3_OCCUPATION_CODE,
	PERSON_3_PERSON_TYPE,
	PERSON_3_OCCUPATION_GROUP_V2,
	PERSON_4_EDUCATION_MODEL,
	PERSON_4_MARITAL_STATUS,
	PERSON_4_BUSINESS_OWNER,
	PERSON_4_COMBINED_AGE,
	PERSON_4_GENDER,
	PERSON_4_OCCUPATION_CODE,
	PERSON_4_PERSON_TYPE,
	PERSON_4_OCCUPATION_GROUP_V2,
	PERSON_5_EDUCATION_MODEL,
	PERSON_5_MARITAL_STATUS,
	PERSON_5_BUSINESS_OWNER,
	PERSON_5_COMBINED_AGE,
	PERSON_5_GENDER,
	PERSON_5_OCCUPATION_CODE,
	PERSON_5_PERSON_TYPE,
	PERSON_5_OCCUPATION_GROUP_V2,
	PERSON_6_EDUCATION_MODEL,
	PERSON_6_MARITAL_STATUS,
	PERSON_6_BUSINESS_OWNER,
	PERSON_6_COMBINED_AGE,
	PERSON_6_GENDER,
	PERSON_6_OCCUPATION_CODE,
	PERSON_6_PERSON_TYPE,
	PERSON_6_OCCUPATION_GROUP_V2,
	PERSON_7_EDUCATION_MODEL,
	PERSON_7_MARITAL_STATUS,
	PERSON_7_BUSINESS_OWNER,
	PERSON_7_COMBINED_AGE,
	PERSON_7_GENDER,
	PERSON_7_OCCUPATION_CODE,
	PERSON_7_PERSON_TYPE,
	PERSON_7_OCCUPATION_GROUP_V2,
	PERSON_8_EDUCATION_MODEL,
	PERSON_8_MARITAL_STATUS,
	PERSON_8_BUSINESS_OWNER,
	PERSON_8_COMBINED_AGE,
	PERSON_8_GENDER,
	PERSON_8_OCCUPATION_CODE,
	PERSON_8_PERSON_TYPE,
	PERSON_8_OCCUPATION_GROUP_V2,
	ACT_INT_VIDEO_GAMER_NBR,
	RETURN_CODE,
	HOUSEHOLD_ID,
	ADDRESS_ID,
	CDM_LOAD_DATE,
	LOAD_ID,
	LOAD_DTTM,
	UPDATE_ID,
	UPDATE_DTTM
) as 
SELECT c.BRAND_ID AS BRAND_ID
, c.AGENCY_ID AS AGENCY_ID
, c.SOURCE_SYSTEM_NM AS SOURCE
, c.UE_SEQ_NBR AS UE_SEQ_NBR
, c.MATCH_LEVEL_CD AS MATCH_LEVEL
, c.MATCH_ADR_CD AS MATCH_ADDRESS
, c.ACTUAL_INTEREST_CASINO_GAMBLING_PERCENT AS ACT_INT_CASINO_GAMBLING_NBR
, c.ACTUAL_INTEREST_EAT_AT_FAMILY_RESTAURANT_PERCENT AS ACT_INT_EATS_AT_FAMILY_RESTAURANTS_NBR
, c.ACTUAL_INTEREST_EAT_AT_FAST_FOOD_RESTAURANT_PERCENT AS ACT_INT_EATS_AT_FAST_FOOD_RESTAURANTS_NBR
, c.ACTUAL_INTEREST_SNOW_SPORT_PERCENT AS ACT_INT_SNOW_SPORTS_NBR
, c.ACTUAL_INTEREST_SPORT_ENTHUSIAST_PERCENT AS ACT_INT_SPORTS_ENTHUSIAST_NBR
, c.PERSON_1_FIRST_NM AS PERSON_1_FIRST_NAME
, c.PERSON_1_MIDDLE_INITIAL_TXT AS PERSON_1_MIDDLE_INITIAL_V2
, c.PERSON_1_NM_PREFIX_TXT AS PERSON_1_NAME_PREFIX
, c.PERSON_1_NM_SUFFIX_TXT AS PERSON_1_NAME_SUFFIX
, c.PERSON_1_BIRTH_YEAR_MNTH_NBR AS PERSON_1_BIRTH_YR_AND_MONTH
, c.BUYER_IMPORTED_BEER_ENTHUSIAST AS BUYER_IMPORTED_BEER_ENTHUSIAST
, c.CAPE_INDUSTRY_EMPLD_ACCOMODATION_AND_FOOD_SERVICE AS CAPE_INDUS_EMPLD_ACCOMODATION_AND_FOOD_SVCS
, c.CAPE_OCCUPATION_EMPLD_ARTS_DESIGN_ENTER_SPORT_MEDIA AS CAPE_OCCUP_EMPLD_ARTS_DSGN_ENTER_SPORTS_MEDIA
, c.CAPE_OCCUPATION_EMPLD_FOOD_PREP_AND_SERVING AS CAPE_OCCUP_EMPLD_FOOD_PREP_AND_SERVING
, c.CONSUMER_SPEND_DINING_OUT_SCORE AS CONSUMER_SPEND_DINING_OUT_SCORE
, c.DEMAND_20100_GROCERIES AS DEMAND_20100_GROCERIES
, c.DEMAND_20130_ALCOHOLIC_BEVERAGE_SERVED AS DEMAND_20130_ALCOHOLIC_BEVERAGES_SERVED
, c.DEMAND_20140_PACKAGED_LIQUOR_WINE_BEER AS DEMAND_20140_PACKAGED_LIQUOR_WINE_BEER
, c.DEMAND_20530_SPORTING_GOODS AS DEMAND_20530_SPORTING_GOODS
, c.DEMAND_20800_PET_PET_FOOD_SUPPLIES AS DEMAND_20800_PETS_PET_FOODS_SUPPLIES
, c.DEMAND_445_FOOD_BEVERAGE_STORE AS DEMAND_445_FOOD_BEVERAGE_STORES
, c.DEMAND_4452_SPECIALTY_FOOD_STORE AS DEMAND_4452_SPECIALTY_FOOD_STORES
, c.DEMAND_4453_BEER_WINE_LIQUOR_STORE AS DEMAND_4453_BEER_WINE_LIQUOR_STORES
, c.DEMAND_451_SPORTING_GOODS_HOBBY_BOOK_MUSIC AS DEMAND_451_SPORTING_GOODS_HOBBY_BOOK_MUSIC
, c.DEMAND_4511_SPORTING_GOODS_HOBBY_MUSIC_INSTRUMENT AS DEMAND_4511_SPORTING_GOODS_HOBBY_MUSIC_INSTRUM
, c.DEMAND_45111_SPORTING_GOODS_STORE AS DEMAND_45111_SPORTING_GOODS_STORES
, c.DEMAND_722_FOOD_SERVICE_DRINKING_PLACE AS DEMAND_722_FOOD_SERVICE_DRINKING_PLACES
, c.DEMAND_7223_SPECIAL_FOOD_SERVICE AS DEMAND_7223_SPECIAL_FOOD_SERVICES
, c.DEMAND_7224_DRINKING_PLACE_ALCOHOLIC_BEVERAGE AS DEMAND_7224_DRINKING_PLACE_ALCOHOLIC_BEVERAGES
, c.TRAN_EXTREME_SNOWSPORT_DOLLAR AS TRAN_EXTREME_SNOWSPORTS_DOLLAR
, c.TRAN_EXTREME_SNOWSPORT_FREQUENCY AS TRAN_EXTREME_SNOWSPORTS_FREQUENCY
, c.TRAN_EXTREME_SNOWSPORT_RECENCY AS TRAN_EXTREME_SNOWSPORTS_RECENCY
, c.TRAN_EXTREME_SNOWSPORT_SCORE AS TRAN_EXTREME_SNOWSPORTS_SCORE
, c.TRAN_FOOD_SNACKS_DOLLAR AS TRAN_FOOD_SNACKS_DOLLAR
, c.TRAN_FOOD_SNACKS_FREQUENCY AS TRAN_FOOD_SNACKS_FREQUENCY
, c.TRAN_FOOD_SNACKS_RECENCY AS TRAN_FOOD_SNACKS_RECENCY
, c.TRAN_FOOD_SNACKS_SCORE AS TRAN_FOOD_SNACKS_SCORE
, c.HOMEOWNER_PROBABILITY_MODEL AS HOMEOWNER_PROBABILITY_MODEL
, c.HOUSEHOLD_CONSUMER_EXPENDITURE_FOOD_BEVERAGE AS HOUSEHOLD_CONSUMER_EXPENDITURES_FOOD_BEV
, c.LENGTH_OF_RESIDENCE_YEAR_QTY AS LENGTH_OF_RESIDENCE
, c.ONLINE_FOOD_BEVERAGE AS ONLINE_FOOD_BEVERAGES
, c.RETAIL_FOOD_BEVERAGE AS RETAIL_FOOD_BEVERAGES
, c.PERSON_1_LAST_NM AS PERSON_1_SURNAME
, c.PRIMARY_ADR_TXT AS PRIMARY_ADDRESS
, c.SECONDARY_ADR_TXT AS SECONDARY_ADDRESS
, c.CTY_ABBREVIATED_NM AS CITY_ABBR
, c.ZIP_CD AS ZIP_CODE
, c.PERSON_2_BIRTH_YEAR_MNTH_NBR AS PERSON_2_BIRTH_YR_AND_MONTH
, c.PERSON_2_FIRST_NM AS PERSON_2_FIRST_NAME
, c.PERSON_2_MIDDLE_INITIAL_TXT AS PERSON_2_MIDDLE_INITIAL_V2
, c.PERSON_2_NM_PREFIX_TXT AS PERSON_2_NAME_PREFIX
, c.PERSON_2_NM_SUFFIX_TXT AS PERSON_2_NAME_SUFFIX
, c.PERSON_2_LAST_NM AS PERSON_2_SURNAME
, c.PERSON_3_BIRTH_YEAR_MNTH_NBR AS PERSON_3_BIRTH_YR_AND_MONTH
, c.PERSON_3_FIRST_NM AS PERSON_3_FIRST_NAME
, c.PERSON_3_MIDDLE_INITIAL_TXT AS PERSON_3_MIDDLE_INITIAL_V2
, c.PERSON_3_NM_PREFIX_TXT AS PERSON_3_NAME_PREFIX
, c.PERSON_3_NM_SUFFIX_TXT AS PERSON_3_NAME_SUFFIX
, c.PERSON_3_LAST_NM AS PERSON_3_SURNAME
, c.PERSON_4_BIRTH_YEAR_MNTH_NBR AS PERSON_4_BIRTH_YR_AND_MONTH
, c.PERSON_4_FIRST_NM AS PERSON_4_FIRST_NAME
, c.PERSON_4_MIDDLE_INITIAL_TXT AS PERSON_4_MIDDLE_INITIAL_V2
, c.PERSON_4_NM_PREFIX_TXT AS PERSON_4_NAME_PREFIX
, c.PERSON_4_NM_SUFFIX_TXT AS PERSON_4_NAME_SUFFIX
, c.PERSON_4_LAST_NM AS PERSON_4_SURNAME
, c.PERSON_5_BIRTH_YEAR_MNTH_NBR AS PERSON_5_BIRTH_YR_AND_MONTH
, c.PERSON_5_FIRST_NM AS PERSON_5_FIRST_NAME
, c.PERSON_5_MIDDLE_INITIAL_TXT AS PERSON_5_MIDDLE_INITIAL_V2
, c.PERSON_5_NM_PREFIX_TXT AS PERSON_5_NAME_PREFIX
, c.PERSON_5_NM_SUFFIX_TXT AS PERSON_5_NAME_SUFFIX
, c.PERSON_5_LAST_NM AS PERSON_5_SURNAME
, c.PERSON_6_BIRTH_YEAR_MNTH_NBR AS PERSON_6_BIRTH_YR_AND_MONTH
, c.PERSON_6_FIRST_NM AS PERSON_6_FIRST_NAME
, c.PERSON_6_MIDDLE_INITIAL_TXT AS PERSON_6_MIDDLE_INITIAL_V2
, c.PERSON_6_NM_PREFIX_TXT AS PERSON_6_NAME_PREFIX
, c.PERSON_6_NM_SUFFIX_TXT AS PERSON_6_NAME_SUFFIX
, c.PERSON_6_LAST_NM AS PERSON_6_SURNAME
, c.PERSON_7_BIRTH_YEAR_MNTH_NBR AS PERSON_7_BIRTH_YR_AND_MONTH
, c.PERSON_7_FIRST_NM AS PERSON_7_FIRST_NAME
, c.PERSON_7_MIDDLE_INITIAL_TXT AS PERSON_7_MIDDLE_INITIAL_V2
, c.PERSON_7_NM_PREFIX_TXT AS PERSON_7_NAME_PREFIX
, c.PERSON_7_NM_SUFFIX_TXT AS PERSON_7_NAME_SUFFIX
, c.PERSON_7_LAST_NM AS PERSON_7_SURNAME
, c.PERSON_8_BIRTH_YEAR_MNTH_NBR AS PERSON_8_BIRTH_YR_AND_MONTH
, c.PERSON_8_FIRST_NM AS PERSON_8_FIRST_NAME
, c.PERSON_8_MIDDLE_INITIAL_TXT AS PERSON_8_MIDDLE_INITIAL_V2
, c.PERSON_8_NM_PREFIX_TXT AS PERSON_8_NAME_PREFIX
, c.PERSON_8_NM_SUFFIX_TXT AS PERSON_8_NAME_SUFFIX
, c.PERSON_8_LAST_NM AS PERSON_8_SURNAME
, c.PERSON_1_EDUCATION_MODEL_TXT AS PERSON_1_EDUCATION_MODEL
, c.PERSON_1_MARITAL_STATUS_TXT AS PERSON_1_MARITAL_STATUS
, c.MOSAIC_GLOBAL_ZIP4_TXT AS MOSAIC_GLOBAL_ZIP4
, c.MOSAIC_ZIP4_TXT AS MOSAIC_ZIP4
, c.NBR_OF_ADULT_IN_LIVING_UNIT_TXT AS NBR_OF_ADULTS_IN_LIVING_UNIT
, c.NBR_OF_CHILDREN_IN_LIVING_UNIT_TXT AS NBR_OF_CHILDREN_IN_LIVING_UNIT
, c.DWELLING_TYP AS DWELLING_TYPE
, c.MOR_BANK_OPPORTUNITY_SEEKER_CONTEST_TXT AS MOR_BANK_OPPORTUNITY_SEEKERS_CONTESTS
, c.MOR_BANK_PHOTOGRAPHY_TXT AS MOR_BANK_PHOTOGRAPHY
, c.MOR_BANK_NEWS_AND_FINANCIAL_TXT AS MOR_BANK_NEWS_AND_FINANCIAL
, c.MOR_BANK_DO_IT_YOURSELFER_TXT AS MOR_BANK_DO_IT_YOURSELFERS
, c.RECIPIENT_RELIABILITY_CD AS RECIPIENT_RELIABILITY_CODE
, c.HOMEOWNER_COMBINED_HOMEOWNER_RENTER_TXT AS HOMEOWNER_COMBINED_HOMEOWNER_RENTER
, c.BEHAVIOR_BANK_CONTRIBUTE_TO_CHARITY_TXT AS BEHAVIORBANK_CONTRIBUTES_TO_CHARITIES
, c.BEHAVIOR_BANK_PET_ENTHUSIAST_TXT AS BEHAVIORBANK_PET_ENTHUSIAST
, c.BEHAVIOR_BANK_INTEREST_IN_TRAVEL_TXT AS BEHAVIORBANK_INTEREST_IN_TRAVEL
, c.BEHAVIOR_BANK_PRESENCE_OF_CREDIT_CARD_TXT AS BEHAVIORBANK_PRESENCE_OF_CREDIT_CARD
, c.BEHAVIOR_BANK_INTEREST_IN_GARDENING_TXT AS BEHAVIORBANK_INTEREST_IN_GARDENING
, c.BEHAVIOR_BANK_INTEREST_IN_SPORT_TXT AS BEHAVIORBANK_INTEREST_IN_SPORTS
, c.BEHAVIOR_BANK_INTEREST_IN_GOURMET_COOKING_TXT AS BEHAVIORBANK_INTEREST_IN_GOURMET_COOKING
, c.BEHAVIOR_BANK_INTEREST_IN_READING_TXT AS BEHAVIORBANK_INTEREST_IN_READING
, c.BEHAVIOR_BANK_DONATE_TO_ENVIRONMENTAL_CAUSE_TXT AS BEHAVIORBANK_DONATES_TO_ENVIRONMENTAL_CAUSES
, c.BEHAVIOR_BANK_DOG_ENTHUSIASTS_TXT AS BEHAVIORBANK_DOG_ENTHUSIASTS
, c.BEHAVIOR_BANK_CATEGORY_ENTHUSIASTS_TXT AS BEHAVIORBANK_CAT_ENTHUSIASTS
, c.BEHAVIOR_BANK_INTEREST_IN_AUTOMOTIVE_TXT AS BEHAVIORBANK_INTEREST_IN_AUTOMOTIVE
, c.BEHAVIOR_BANK_COMPUTER_PERIPHERAL_TXT AS BEHAVIORBANK_COMPUTERS_PERIPHERALS
, c.BEHAVIOR_BANK_HOME_DECORATING_FURNISHING_TXT AS BEHAVIORBANK_HOME_DECORATING_FURNISHING
, c.DWELLING_UNIT_SIZE_TXT AS DWELLING_UNIT_SIZE
, c.CHILDREN_AGE_0_3_TXT AS CHILDREN_AGE_0_3
, c.CHILDREN_AGE_4_6_TXT AS CHILDREN_AGE_4_6
, c.CHILDREN_AGE_7_9_TXT AS CHILDREN_AGE_7_9
, c.CHILDREN_AGE_10_12_TXT AS CHILDREN_AGE_10_12
, c.CHILDREN_AGE_13_15_TXT AS CHILDREN_AGE_13_15
, c.CHILDREN_AGE_16_18_TXT AS CHILDREN_AGE_16_18
, c.CHILDREN_PRESENCE_OF_CHILD_0_18_TXT AS CHILDREN_PRESENCE_OF_CHILD_0_18
, c.SRVY_HH_ACTY_INT_COLLECTING_SPORTS_MEMORABILIA_TXT AS SRVY_HH_ACTY_INT_COLLECTING_SPORTS_MEMORABILIA
, c.SRVY_HH_ACTY_INT_HEALTH_FITNESS_HLTH_NAT_FOODS_TXT AS SRVY_HH_ACTY_INT_HEALTH_FITNESS_HLTH_NAT_FOODS
, c.SRVY_HH_ACTY_INT_READING_SPORTS_READING_TXT AS SRVY_HH_ACTY_INT_READING_SPORTS_READING
, c.SRVY_HH_ACTY_INT_SPORTS_REC_BASEBALL_TXT AS SRVY_HH_ACTY_INT_SPORTS_REC_BASEBALL
, c.SRVY_HH_ACTY_INT_SPORTS_REC_BASKETBALL_TXT AS SRVY_HH_ACTY_INT_SPORTS_REC_BASKETBALL
, c.SRVY_HH_ACTY_INT_SPORTS_REC_HOCKEY_TXT AS SRVY_HH_ACTY_INT_SPORTS_REC_HOCKEY
, c.SRVY_HH_ACTY_INT_SPORTS_REC_CAMPING_HIKING_TXT AS SRVY_HH_ACTY_INT_SPORTS_REC_CAMPING_HIKING
, c.SRVY_HH_ACTY_INT_SPORTS_REC_HUNTING_TXT AS SRVY_HH_ACTY_INT_SPORTS_REC_HUNTING
, c.SRVY_HH_ACTY_INT_SPORTS_REC_FISHING_TXT AS SRVY_HH_ACTY_INT_SPORTS_REC_FISHING
, c.SRVY_HH_ACTY_INT_SPORTS_REC_NASCAR_TXT AS SRVY_HH_ACTY_INT_SPORTS_REC_NASCAR
, c.SRVY_HH_ACTY_INT_SPORTS_REC_PERSONAL_FITNESS_EXER_TXT AS SRVY_HH_ACTY_INT_SPORTS_REC_PERSONAL_FITNESS_EXER
, c.SRVY_HH_ACTY_INT_SPORTS_REC_SCUBA_DIVING_TXT AS SRVY_HH_ACTY_INT_SPORTS_REC_SCUBA_DIVING
, c.SRVY_HH_ACTY_INT_SPORTS_REC_FOOTBALL_TXT AS SRVY_HH_ACTY_INT_SPORTS_REC_FOOTBALL
, c.SRVY_HH_ACTY_INT_SPORTS_REC_GOLF_TXT AS SRVY_HH_ACTY_INT_SPORTS_REC_GOLF
, c.SRVY_HH_ACTY_INT_SPORTS_REC_SNOW_SKIING_BOARDING_TXT AS SRVY_HH_ACTY_INT_SPORTS_REC_SNOW_SKIING_BOARDING
, c.SRVY_HH_ACTY_INT_SPORTS_REC_BOATING_SAILING_TXT AS SRVY_HH_ACTY_INT_SPORTS_REC_BOATING_SAILING
, c.SRVY_HH_ACTY_INT_SPORTS_REC_WALKING_TXT AS SRVY_HH_ACTY_INT_SPORTS_REC_WALKING
, c.SRVY_HH_ACTY_INT_SPORTS_REC_CYCLING_TXT AS SRVY_HH_ACTY_INT_SPORTS_REC_CYCLING
, c.SRVY_HH_ACTY_INT_SPORTS_REC_MOTORCYCLES_TXT AS SRVY_HH_ACTY_INT_SPORTS_REC_MOTORCYCLES
, c.SRVY_HH_ACTY_INT_SPORTS_REC_RUNNING_JOGGING_TXT AS SRVY_HH_ACTY_INT_SPORTS_REC_RUNNING_JOGGING
, c.SRVY_HH_ACTY_INT_SPORTS_REC_SOCCER_TXT AS SRVY_HH_ACTY_INT_SPORTS_REC_SOCCER
, c.SRVY_HH_ACTY_INT_SPORTS_REC_SWIMMING_TXT AS SRVY_HH_ACTY_INT_SPORTS_REC_SWIMMING
, c.SRVY_HH_ACTY_INT_SPORTS_REC_PLAY_SPORTS_IN_GENERAL_TXT AS SRVY_HH_ACTY_INT_SPORTS_REC_PLAY_SPORTS_IN_GENERA
, c.SRVY_HH_ACTY_INT_SWEEPSTAKES_SWEEPSTAKES_TXT AS SRVY_HH_ACTY_INT_SWEEPSTAKES_SWEEPSTAKES
, c.SRVY_HH_ACTY_INT_SWEEPSTAKES_LOTTERIES_TXT AS SRVY_HH_ACTY_INT_SWEEPSTAKES_LOTTERIES
, c.SRVY_HH_ACTY_INT_SWEEPSTAKES_CASINO_GAMBLING_TXT AS SRVY_HH_ACTY_INT_SWEEPSTAKES_CASINO_GAMBLING
, c.SRVY_HH_ACTY_INT_MAGAZINES_FOOD_WINE_COOKING_TXT AS SRVY_HH_ACTY_INT_MAGAZINES_FOOD_WINE_COOKING
, c.SRVY_HH_ACTY_INT_MAGAZINES_SPORTS_MAGAZINES_TXT AS SRVY_HH_ACTY_INT_MAGAZINES_SPORTS_MAGAZINES
, c.SRVY_HH_LIFESTYL_BUYING_SPORTS_RELATED_TXT AS SRVY_HH_LIFESTYL_BUYING_SPORTS_RELATED
, c.NBR_OF_PERSON_IN_LIVING_UNIT_TXT AS NBR_OF_PERSONS_IN_LIVING_UNIT
, c.ST_NM AS STATE_ABBR
, c.PERSON_1_BUSINESS_OWNER_TXT AS PERSON_1_BUSINESS_OWNER
, c.PERSON_1_COMBINED_AGE_TXT AS PERSON_1_COMBINED_AGE
, c.PERSON_1_ETHNIC_CNTRY_OF_ORIGIN_TXT AS PERSON_1_ETHNIC_COUNTRY_OF_ORIGIN
, c.PERSON_1_ETHNIC_ETHNIC_TXT AS PERSON_1_ETHNIC_ETHNIC
, c.PERSON_1_ETHNIC_GROUP_TXT AS PERSON_1_ETHNIC_GROUP
, c.PERSON_1_ETHNIC_RELIGION_TXT AS PERSON_1_ETHNIC_RELIGION
, c.PERSON_1_GENDER_TXT AS PERSON_1_GENDER
, c.PERSON_1_OCCUPATION_CD AS PERSON_1_OCCUPATION_CODE
, c.PERSON_1_PERSON_TYP AS PERSON_1_PERSON_TYPE
, c.PERSON_1_ETHNIC_LANGUAGE_PREFERENCE_TXT AS PERSON_1_ETHNIC_LANGUAGE_PREFERENCE
, c.PERSON_1_OCCUPATION_GROUP_TXT AS PERSON_1_OCCUPATION_GROUP_V2
, c.CONSUMER_SPEND_DINING_OUT_TXT AS CONSUMER_SPEND_DINING_OUT
, c.ESTIMATED_HOUSEHOLD_INCOME_RANGE_CD_V6_TXT AS ESTIMATED_HOUSEHOLD_INCOME_RANGE_CODE_V6
, c.PERSON_2_EDUCATION_MODEL_TXT AS PERSON_2_EDUCATION_MODEL
, c.PERSON_2_MARITAL_STATUS_TXT AS PERSON_2_MARITAL_STATUS
, c.PERSON_2_BUSINESS_OWNER_TXT AS PERSON_2_BUSINESS_OWNER
, c.PERSON_2_COMBINED_AGE_TXT AS PERSON_2_COMBINED_AGE
, c.PERSON_2_GENDER_TXT AS PERSON_2_GENDER
, c.PERSON_2_OCCUPATION_CD AS PERSON_2_OCCUPATION_CODE
, c.PERSON_2_PERSON_TYP AS PERSON_2_PERSON_TYPE
, c.PERSON_2_OCCUPATION_GROUP_TXT AS PERSON_2_OCCUPATION_GROUP_V2
, c.PERSON_3_EDUCATION_MODEL_TXT AS PERSON_3_EDUCATION_MODEL
, c.PERSON_3_MARITAL_STATUS_TXT AS PERSON_3_MARITAL_STATUS
, c.PERSON_3_BUSINESS_OWNER_TXT AS PERSON_3_BUSINESS_OWNER
, c.PERSON_3_COMBINED_AGE_TXT AS PERSON_3_COMBINED_AGE
, c.PERSON_3_GENDER_TXT AS PERSON_3_GENDER
, c.PERSON_3_OCCUPATION_CD AS PERSON_3_OCCUPATION_CODE
, c.PERSON_3_PERSON_TYP AS PERSON_3_PERSON_TYPE
, c.PERSON_3_OCCUPATION_GROUP_TXT AS PERSON_3_OCCUPATION_GROUP_V2
, c.PERSON_4_EDUCATION_MODEL_TXT AS PERSON_4_EDUCATION_MODEL
, c.PERSON_4_MARITAL_STATUS_TXT AS PERSON_4_MARITAL_STATUS
, c.PERSON_4_BUSINESS_OWNER_TXT AS PERSON_4_BUSINESS_OWNER
, c.PERSON_4_COMBINED_AGE_TXT AS PERSON_4_COMBINED_AGE
, c.PERSON_4_GENDER_TXT AS PERSON_4_GENDER
, c.PERSON_4_OCCUPATION_CD AS PERSON_4_OCCUPATION_CODE
, c.PERSON_4_PERSON_TYP AS PERSON_4_PERSON_TYPE
, c.PERSON_4_OCCUPATION_GROUP_TXT AS PERSON_4_OCCUPATION_GROUP_V2
, c.PERSON_5_EDUCATION_MODEL_TXT AS PERSON_5_EDUCATION_MODEL
, c.PERSON_5_MARITAL_STATUS_TXT AS PERSON_5_MARITAL_STATUS
, c.PERSON_5_BUSINESS_OWNER_TXT AS PERSON_5_BUSINESS_OWNER
, c.PERSON_5_COMBINED_AGE_TXT AS PERSON_5_COMBINED_AGE
, c.PERSON_5_GENDER_TXT AS PERSON_5_GENDER
, c.PERSON_5_OCCUPATION_CD AS PERSON_5_OCCUPATION_CODE
, c.PERSON_5_PERSON_TYP AS PERSON_5_PERSON_TYPE
, c.PERSON_5_OCCUPATION_GROUP_TXT AS PERSON_5_OCCUPATION_GROUP_V2
, c.PERSON_6_EDUCATION_MODEL_TXT AS PERSON_6_EDUCATION_MODEL
, c.PERSON_6_MARITAL_STATUS_TXT AS PERSON_6_MARITAL_STATUS
, c.PERSON_6_BUSINESS_OWNER_TXT AS PERSON_6_BUSINESS_OWNER
, c.PERSON_6_COMBINED_AGE_TXT AS PERSON_6_COMBINED_AGE
, c.PERSON_6_GENDER_TXT AS PERSON_6_GENDER
, c.PERSON_6_OCCUPATION_CD AS PERSON_6_OCCUPATION_CODE
, c.PERSON_6_PERSON_TYP AS PERSON_6_PERSON_TYPE
, c.PERSON_6_OCCUPATION_GROUP_TXT AS PERSON_6_OCCUPATION_GROUP_V2
, c.PERSON_7_EDUCATION_MODEL_TXT AS PERSON_7_EDUCATION_MODEL
, c.PERSON_7_MARITAL_STATUS_TXT AS PERSON_7_MARITAL_STATUS
, c.PERSON_7_BUSINESS_OWNER_TXT AS PERSON_7_BUSINESS_OWNER
, c.PERSON_7_COMBINED_AGE_TXT AS PERSON_7_COMBINED_AGE
, c.PERSON_7_GENDER_TXT AS PERSON_7_GENDER
, c.PERSON_7_OCCUPATION_CD AS PERSON_7_OCCUPATION_CODE
, c.PERSON_7_PERSON_TYP AS PERSON_7_PERSON_TYPE
, c.PERSON_7_OCCUPATION_GROUP_TXT AS PERSON_7_OCCUPATION_GROUP_V2
, c.PERSON_8_EDUCATION_MODEL_TXT AS PERSON_8_EDUCATION_MODEL
, c.PERSON_8_MARITAL_STATUS_TXT AS PERSON_8_MARITAL_STATUS
, c.PERSON_8_BUSINESS_OWNER_TXT AS PERSON_8_BUSINESS_OWNER
, c.PERSON_8_COMBINED_AGE_TXT AS PERSON_8_COMBINED_AGE
, c.PERSON_8_GENDER_TXT AS PERSON_8_GENDER
, c.PERSON_8_OCCUPATION_CD AS PERSON_8_OCCUPATION_CODE
, c.PERSON_8_PERSON_TYP AS PERSON_8_PERSON_TYPE
, c.PERSON_8_OCCUPATION_GROUP_TXT AS PERSON_8_OCCUPATION_GROUP_V2
, c.ACTUAL_INTEREST_VIDEO_GAMER_PERCENT AS ACT_INT_VIDEO_GAMER_NBR
, c.RETURN_CD AS RETURN_CODE
, c.HOUSEHOLD_ID AS HOUSEHOLD_ID
, c.ADR_ID AS ADDRESS_ID
, c.CDM_LOAD_DT AS CDM_LOAD_DATE
, c.LOAD_ID AS LOAD_ID
, c.LOAD_DTTM AS LOAD_DTTM
, c.UPDATE_ID AS UPDATE_ID
, c.UPDATE_DTTM AS UPDATE_DTTM
FROM IDM_DEV.COREDIM_BV.CUST_ENRICHMENT_DIM_BV c;