create TABLE IF NOT EXISTS ADF_LOGGING (
	ID NUMBER(38,0) NOT NULL autoincrement,
	FILENAME VARCHAR(16777216),
	DATAREAD NUMBER(38,0),
	ROWSREAD NUMBER(38,0),
	ROWSCOPIED NUMBER(38,0),
	FILESWRITTEN NUMBER(38,0),
	COPYDURATION NUMBER(38,0),
	DATESTART TIMESTAMP_NTZ(9),
	DATEEND TIMESTAMP_NTZ(9),
	STATUS VARCHAR(16777216),
	primary key (ID)
);
create TABLE IF NOT EXISTS ADF_LOGGING_CLONE (
	ID NUMBER(38,0) NOT NULL autoincrement,
	FILENAME VARCHAR(16777216),
	DATAREAD NUMBER(38,0),
	ROWSREAD NUMBER(38,0),
	ROWSCOPIED NUMBER(38,0),
	FILESWRITTEN NUMBER(38,0),
	COPYDURATION NUMBER(38,0),
	DATESTART TIMESTAMP_NTZ(9),
	DATEEND TIMESTAMP_NTZ(9),
	STATUS VARCHAR(16777216),
	primary key (ID)
);
create TABLE IF NOT EXISTS CRM_EXISTING_CLICKS (
	DEPLOYMENTID VARCHAR(16777216),
	EMAILADDRESS VARCHAR(16777216),
	LINKURL VARCHAR(16777216)
);
create TABLE IF NOT EXISTS CRM_EXISTING_OPEN (
	DEPLOYMENTID VARCHAR(16777216),
	EMAILADDRESS VARCHAR(16777216)
);
create TABLE IF NOT EXISTS EPS_CRM_ACTIVITY_RAW (
	FOLDERNAME_M VARCHAR(16777216),
	CUSTOMERKEY VARCHAR(16777216),
	EMAILADDRESS VARCHAR(16777216),
	MESSAGENAME VARCHAR(16777216),
	MESSAGEID VARCHAR(16777216),
	DEPLOYMENTID VARCHAR(16777216),
	SUBJECTLINE VARCHAR(16777216),
	AUDIENCE VARCHAR(16777216),
	ACTION VARCHAR(16777216),
	ORIGINALEVENTTIMESTAMP VARCHAR(16777216),
	LINKNAME VARCHAR(16777216),
	LINKTAG VARCHAR(16777216),
	LINKURL VARCHAR(16777216),
	BUSINESSUNITNAME VARCHAR(16777216),
	DEVICECATEGORY VARCHAR(16777216),
	DEVICETYPE VARCHAR(16777216),
	UNDELIVEREDCATEGORY VARCHAR(16777216),
	SERVICETRANSACTIONID VARCHAR(16777216),
	SERVICECOMMUNICATIONID VARCHAR(16777216),
	EVENTNAME VARCHAR(16777216),
	CONVERSIONAMOUNT VARCHAR(16777216),
	CONVERSIONQUANTITY VARCHAR(16777216),
	CONVERSIONORDERID VARCHAR(16777216),
	CONVERSIONCATEGORY VARCHAR(16777216),
	CONVERSIONSUBCATEGORY VARCHAR(16777216),
	CONVERSIONDATETIME VARCHAR(16777216),
	CONVERSIONTRANSACTIONID VARCHAR(16777216),
	SOURCE_SYSTEM_NM VARCHAR(255),
	BRAND_ID VARCHAR(255),
	LOAD_ID NUMBER(38,0),
	LOAD_DTTM TIMESTAMP_NTZ(9),
	UPDATE_ID NUMBER(38,0),
	UPDATE_DTTM TIMESTAMP_NTZ(9),
	LOAD_FILENAME VARCHAR(16777216)
);
create TABLE IF NOT EXISTS EPS_CRM_FTD_RAW (
	CUSTOMERKEY VARCHAR(16777216),
	EMAILADDRESS VARCHAR(16777216),
	EMAILADDRESSDELIVERYSTATUS VARCHAR(16777216),
	EMAILADDRESSDELIVERYSTATUSDATE VARCHAR(16777216),
	SOURCE_SYSTEM_NM VARCHAR(255),
	BRAND_ID VARCHAR(255),
	LOAD_ID NUMBER(38,0),
	LOAD_DTTM TIMESTAMP_NTZ(9),
	UPDATE_ID NUMBER(38,0),
	UPDATE_DTTM TIMESTAMP_NTZ(9),
	LOAD_FILENAME VARCHAR(16777216)
);
create TABLE IF NOT EXISTS EPS_CRM_OPTOUT_RAW (
	CUSTOMERKEY VARCHAR(16777216),
	EMAILADDRESS VARCHAR(16777216),
	EMAILCHANNELOPTOUTFLAG VARCHAR(16777216),
	EMAILCHANNELOPTSTATUSDATE VARCHAR(16777216),
	EMAILCHANNELOPTSTATUSSOURCE VARCHAR(16777216),
	SOURCE_SYSTEM_NM VARCHAR(255),
	BRAND_ID VARCHAR(255),
	LOAD_ID NUMBER(38,0),
	LOAD_DTTM TIMESTAMP_NTZ(9),
	UPDATE_ID NUMBER(38,0),
	UPDATE_DTTM TIMESTAMP_NTZ(9),
	LOAD_FILENAME VARCHAR(16777216)
);
create TABLE IF NOT EXISTS EPS_CRM_PUSH_ACTIVITY_RAW (
	CUSTOMERKEY VARCHAR(16777216),
	APPID VARCHAR(16777216),
	DEVICEID VARCHAR(16777216),
	MOBILEPUSHOSNAME VARCHAR(16777216),
	MESSAGENAME VARCHAR(16777216),
	MESSAGEID VARCHAR(16777216),
	DEPLOYMENTID VARCHAR(16777216),
	ACTION VARCHAR(16777216),
	ACTIONTIMESTAMP VARCHAR(16777216),
	BUSINESSUNITNAME VARCHAR(16777216),
	SERVICETRANSACTIONID VARCHAR(16777216),
	SOURCE_SYSTEM_NM VARCHAR(255),
	BRAND_ID VARCHAR(255),
	LOAD_ID NUMBER(38,0),
	LOAD_DTTM TIMESTAMP_NTZ(9),
	UPDATE_ID NUMBER(38,0),
	UPDATE_DTTM TIMESTAMP_NTZ(9),
	LOAD_FILENAME VARCHAR(16777216)
);
create TABLE IF NOT EXISTS EPS_DD_M_CAMPAIGN_RAW_HIST (
	BI_PROFILE_ID VARCHAR(16777216),
	EPSILON_PROFILE_ID VARCHAR(16777216),
	CAMPAIGN_NAME VARCHAR(16777216),
	CAMPAIGN_CODE VARCHAR(16777216),
	CAMPAIGN_TYPE VARCHAR(16777216),
	CAMPAIGN_DESCRIPTION VARCHAR(16777216),
	SEGMENT_CODE VARCHAR(16777216),
	OFFER_NAME VARCHAR(16777216),
	OFFER_CODE VARCHAR(16777216),
	MEMBER_OFFER_START_DATE VARCHAR(16777216),
	MEMBER_OFFER_END_DATE VARCHAR(16777216),
	COUPON_CODE VARCHAR(16777216),
	CHANNEL_ID VARCHAR(16777216),
	DELIVERY_DATE VARCHAR(16777216),
	SOURCE_SYSTEM_NM VARCHAR(255),
	BRAND_ID VARCHAR(255),
	LOAD_ID NUMBER(38,0),
	LOAD_DTTM TIMESTAMP_NTZ(9),
	UPDATE_ID NUMBER(38,0),
	UPDATE_DTTM TIMESTAMP_NTZ(9),
	LOAD_FILENAME VARCHAR(16777216)
);
create TABLE IF NOT EXISTS EPS_DD_OFFER_CODE_RAW_HIST (
	OFFER_CODE VARCHAR(16777216),
	OFFER_NAME VARCHAR(16777216),
	OFFER_DESCRIPTION VARCHAR(16777216),
	OFFER_START_DATE VARCHAR(16777216),
	OFFER_END_DATE VARCHAR(16777216),
	ACTIVE_INDICATOR VARCHAR(16777216),
	CREATE_USER VARCHAR(16777216),
	SOURCE_SYSTEM_NM VARCHAR(255),
	BRAND_ID VARCHAR(255),
	LOAD_ID NUMBER(38,0),
	LOAD_DTTM TIMESTAMP_NTZ(9),
	UPDATE_ID NUMBER(38,0),
	UPDATE_DTTM TIMESTAMP_NTZ(9),
	LOAD_FILENAME VARCHAR(16777216)
);
create TABLE IF NOT EXISTS EPS_DD_PNT_ACTIVITY_RAW_HIST (
	EPSILON_POINT_ID VARCHAR(16777216),
	EPSILON_TRANSACTION_ID VARCHAR(16777216),
	EPSILON_TRANSACTION_DETAIL_ID VARCHAR(16777216),
	EPSILON_PROFILE_ID VARCHAR(16777216),
	POINT_TRANSACTION_CODE VARCHAR(16777216),
	STORE_NUMBER VARCHAR(16777216),
	TRANSACTION_DTTM VARCHAR(16777216),
	POSTED_DTTM VARCHAR(16777216),
	DUNKIN_TRANSACTION_NUMBER VARCHAR(16777216),
	POS_NUMBER VARCHAR(16777216),
	ADJUSTMENT_CODE VARCHAR(16777216),
	OFFER_CODE VARCHAR(16777216),
	SKU VARCHAR(16777216),
	LINE_NUMBER VARCHAR(16777216),
	AWARD_CODE VARCHAR(16777216),
	MISSING_TRANSACTION_INDICATOR VARCHAR(16777216),
	POINTS VARCHAR(16777216),
	POS_INDICATOR VARCHAR(16777216),
	ADJUSTMENT_REASON VARCHAR(16777216),
	SOURCE_SYSTEM_NM VARCHAR(255),
	BRAND_ID VARCHAR(255),
	LOAD_ID NUMBER(38,0),
	LOAD_DTTM TIMESTAMP_NTZ(9),
	UPDATE_ID NUMBER(38,0),
	UPDATE_DTTM TIMESTAMP_NTZ(9),
	LOAD_FILENAME VARCHAR(16777216)
);
create TABLE IF NOT EXISTS FLYWAY_SCHEMA_HISTORY (
	INSTALLED_RANK NUMBER(38,0) NOT NULL,
	VERSION VARCHAR(50),
	DESCRIPTION VARCHAR(200),
	TYPE VARCHAR(20) NOT NULL,
	SCRIPT VARCHAR(1000) NOT NULL,
	CHECKSUM NUMBER(38,0),
	INSTALLED_BY VARCHAR(100) NOT NULL,
	INSTALLED_ON TIMESTAMP_LTZ(9) NOT NULL DEFAULT CURRENT_TIMESTAMP(),
	EXECUTION_TIME NUMBER(38,0) NOT NULL,
	SUCCESS BOOLEAN NOT NULL,
	primary key (INSTALLED_RANK)
);
create TABLE IF NOT EXISTS INSPIRE_DUNKIN_ACTIVITY_RAW_HIST (
	FOLDER_NAME_M VARCHAR(16777216),
	CUSTOMER_KEY VARCHAR(16777216),
	EMAIL_ADDRESS VARCHAR(16777216),
	MESSAGE_NAME VARCHAR(16777216),
	MESSAGE_ID VARCHAR(16777216),
	DEPLOYMENT_ID VARCHAR(16777216),
	SUBJECT_LINE VARCHAR(16777216),
	AUDIENCE VARCHAR(16777216),
	ACTION VARCHAR(16777216),
	ORIGINAL_EVENT_TIMESTAMP VARCHAR(16777216),
	LINK_NAME VARCHAR(16777216),
	LINK_TAG VARCHAR(16777216),
	LINK_URL VARCHAR(16777216),
	BUSINESS_UNIT_NAME VARCHAR(16777216),
	DEVICE_CATEGORY VARCHAR(16777216),
	DEVICE_TYPE VARCHAR(16777216),
	UNDELIVERED_CATEGORY VARCHAR(16777216),
	SERVICE_TRANSACTIONID VARCHAR(16777216),
	SERVICE_COMMUNICATION_ID VARCHAR(16777216),
	EVENT_NAME VARCHAR(16777216),
	CONVERSION_AMOUNT VARCHAR(16777216),
	CONVERSION_QUANTITY VARCHAR(16777216),
	CONVERSION_ORDER_ID VARCHAR(16777216),
	CONVERSION_CATEGORY VARCHAR(16777216),
	CONVERSION_SUBCATEGORY VARCHAR(16777216),
	CONVERSION_DATE_TIME VARCHAR(16777216),
	CONVERSION_CUSTOMER_TRANSACTION_ID VARCHAR(16777216),
	SOURCE_SYSTEM_NM VARCHAR(255),
	BRAND_ID VARCHAR(255),
	LOAD_ID NUMBER(38,0),
	LOAD_DTTM TIMESTAMP_NTZ(9),
	UPDATE_ID NUMBER(38,0),
	UPDATE_DTTM TIMESTAMP_NTZ(9),
	LOAD_FILENAME VARCHAR(16777216)
);
create TABLE IF NOT EXISTS SFMC_CRM_BOUNCE_RAW (
	CLIENTID VARCHAR(16777216),
	SENDID VARCHAR(16777216),
	SUBSCRIBERKEY VARCHAR(16777216),
	EMAILADDRESS VARCHAR(16777216),
	SUBSCRIBERID VARCHAR(16777216),
	LISTID VARCHAR(16777216),
	EVENTDATE VARCHAR(16777216),
	EVENTTYPE VARCHAR(16777216),
	BOUNCECATEGORY VARCHAR(16777216),
	SMTPCODE VARCHAR(16777216),
	BOUNCEREASON VARCHAR(16777216),
	BATCHID VARCHAR(16777216),
	TRIGGEREDSENDEXTERNALKEY VARCHAR(16777216),
	SOURCE_SYSTEM_NM VARCHAR(255),
	BRAND_ID VARCHAR(255),
	LOAD_ID NUMBER(38,0),
	LOAD_DTTM TIMESTAMP_NTZ(9),
	UPDATE_ID NUMBER(38,0),
	UPDATE_DTTM TIMESTAMP_NTZ(9),
	LOAD_FILENAME VARCHAR(16777216)
);
create TABLE IF NOT EXISTS SFMC_CRM_CLICK_RAW (
	CLIENTID VARCHAR(16777216),
	SENDID VARCHAR(16777216),
	SUBSCRIBERKEY VARCHAR(16777216),
	EMAILADDRESS VARCHAR(16777216),
	SUBSCRIBERID VARCHAR(16777216),
	LISTID VARCHAR(16777216),
	EVENTDATE VARCHAR(16777216),
	EVENTTYPE VARCHAR(16777216),
	SENDURLID VARCHAR(16777216),
	URLID VARCHAR(16777216),
	URL VARCHAR(16777216),
	ALIAS VARCHAR(16777216),
	BATCHID VARCHAR(16777216),
	TRIGGEREDSENDEXTERNALKEY VARCHAR(16777216),
	ISUNIQUE VARCHAR(16777216),
	ISUNIQUEFORURL VARCHAR(16777216),
	MESSAGE_ID VARCHAR(16777216),
	SERVICE_TRANSACTION_ID VARCHAR(16777216),
	SOURCE_SYSTEM_NM VARCHAR(255),
	BRAND_ID VARCHAR(255),
	LOAD_ID NUMBER(38,0),
	LOAD_DTTM TIMESTAMP_NTZ(9),
	UPDATE_ID NUMBER(38,0),
	UPDATE_DTTM TIMESTAMP_NTZ(9),
	LOAD_FILENAME VARCHAR(16777216)
);
create TABLE IF NOT EXISTS SFMC_CRM_COMPLAINT_RAW (
	CLIENTID VARCHAR(16777216),
	SENDID VARCHAR(16777216),
	SUBSCRIBERKEY VARCHAR(16777216),
	EMAILADDRESS VARCHAR(16777216),
	SUBSCRIBERID VARCHAR(16777216),
	LISTID VARCHAR(16777216),
	EVENTDATE VARCHAR(16777216),
	EVENTTYPE VARCHAR(16777216),
	BATCHID VARCHAR(16777216),
	TRIGGEREDSENDEXTERNALKEY VARCHAR(16777216),
	DOMAIN VARCHAR(16777216),
	SOURCE_SYSTEM_NM VARCHAR(255),
	BRAND_ID VARCHAR(255),
	LOAD_ID NUMBER(38,0),
	LOAD_DTTM TIMESTAMP_NTZ(9),
	UPDATE_ID NUMBER(38,0),
	UPDATE_DTTM TIMESTAMP_NTZ(9),
	LOAD_FILENAME VARCHAR(16777216)
);
create TABLE IF NOT EXISTS SFMC_CRM_HOLDOUT_LOG_RAW (
	JOBID VARCHAR(16777216),
	MEMBERID VARCHAR(16777216),
	DATE VARCHAR(16777216),
	SUBSCRIBERKEY VARCHAR(16777216),
	EMAILADDR VARCHAR(16777216),
	OFFER_CODE VARCHAR(16777216),
	OFFER_NAME VARCHAR(16777216),
	PARENTOFFERID VARCHAR(16777216),
	CAMPAIGN_TYPE VARCHAR(16777216),
	JOURNEYNAME VARCHAR(16777216),
	JOURNEYSTEP VARCHAR(16777216),
	SOC VARCHAR(16777216),
	USER_DEFINED_SEGMENT1 VARCHAR(16777216),
	USER_DEFINED_SEGMENT2 VARCHAR(16777216),
	USER_DEFINED_SEGMENT3 VARCHAR(16777216),
	USER_DEFINED_SEGMENT4 VARCHAR(16777216),
	USER_DEFINED_SEGMENT5 VARCHAR(16777216),
	OFFER1DECISIONLOGIC VARCHAR(16777216),
	POINTBALANCE VARCHAR(16777216),
	EMAILNAME VARCHAR(16777216),
	CAMPAIGN_ID VARCHAR(16777216),
	CAMPAIGN_NAME VARCHAR(16777216),
	CAMPAIGN_CATEGORY VARCHAR(16777216),
	CAMPAIGN_DESCRIPTION VARCHAR(16777216),
	CAMPAIGN_OBJECTIVE VARCHAR(16777216),
	CAMPAIGN_START_DATE VARCHAR(16777216),
	CAMPAIGN_END_DATE VARCHAR(16777216),
	CAMPAIGN_DURATION VARCHAR(16777216),
	CUSTOMER_ID VARCHAR(16777216),
	DATASOURCENAME VARCHAR(16777216),
	CREATIVE_VARIANT VARCHAR(16777216),
	SOURCE_SYSTEM_NM VARCHAR(255),
	BRAND_ID VARCHAR(255),
	LOAD_ID NUMBER(38,0),
	LOAD_DTTM TIMESTAMP_NTZ(9),
	UPDATE_ID NUMBER(38,0),
	UPDATE_DTTM TIMESTAMP_NTZ(9),
	LOAD_FILENAME VARCHAR(16777216)
);
create TABLE IF NOT EXISTS SFMC_CRM_JOURNEY_EMAIL_ACTIVITY_RAW (
	ACCOUNTID VARCHAR(16777216),
	OYBACCOUNTID VARCHAR(16777216),
	JOBID VARCHAR(16777216),
	VERSIONID VARCHAR(16777216),
	ACTIVITYID VARCHAR(16777216),
	ACTIVITYNAME VARCHAR(16777216),
	ACTIVITYEXTERNALKEY VARCHAR(16777216),
	JOURNEYACTIVITYOBJECTID VARCHAR(16777216),
	ACTIVITYTYPE VARCHAR(16777216),
	SOURCE_SYSTEM_NM VARCHAR(255),
	BRAND_ID VARCHAR(255),
	LOAD_ID NUMBER(38,0),
	LOAD_DTTM TIMESTAMP_NTZ(9),
	UPDATE_ID NUMBER(38,0),
	UPDATE_DTTM TIMESTAMP_NTZ(9),
	LOAD_FILENAME VARCHAR(16777216)
);
create TABLE IF NOT EXISTS SFMC_CRM_JOURNEY_RAW (
	VERSIONID VARCHAR(16777216),
	JOURNEYID VARCHAR(16777216),
	JOURNEYNAME VARCHAR(16777216),
	VERSIONNUMBER VARCHAR(16777216),
	CREATEDDATE VARCHAR(16777216),
	LASTPUBLISHEDDATE VARCHAR(16777216),
	MODIFIEDDATE VARCHAR(16777216),
	JOURNEYSTATUS VARCHAR(16777216),
	SOURCE_SYSTEM_NM VARCHAR(255),
	BRAND_ID VARCHAR(255),
	LOAD_ID NUMBER(38,0),
	LOAD_DTTM TIMESTAMP_NTZ(9),
	UPDATE_ID NUMBER(38,0),
	UPDATE_DTTM TIMESTAMP_NTZ(9),
	LOAD_FILENAME VARCHAR(16777216)
);
create TABLE IF NOT EXISTS SFMC_CRM_NOT_SENT_RAW (
	CLIENTID VARCHAR(16777216),
	SENDID VARCHAR(16777216),
	SUBSCRIBERKEY VARCHAR(16777216),
	EMAILADDRESS VARCHAR(16777216),
	SUBSCRIBERID VARCHAR(16777216),
	LISTID VARCHAR(16777216),
	EVENTDATE VARCHAR(16777216),
	EVENTTYPE VARCHAR(16777216),
	BATCHID VARCHAR(16777216),
	TRIGGEREDSENDEXTERNALKEY VARCHAR(16777216),
	REASON VARCHAR(16777216),
	SOURCE_SYSTEM_NM VARCHAR(255),
	BRAND_ID VARCHAR(255),
	LOAD_ID NUMBER(38,0),
	LOAD_DTTM TIMESTAMP_NTZ(9),
	UPDATE_ID NUMBER(38,0),
	UPDATE_DTTM TIMESTAMP_NTZ(9),
	LOAD_FILENAME VARCHAR(16777216)
);
create TABLE IF NOT EXISTS SFMC_CRM_OPEN_RAW (
	CLIENTID VARCHAR(16777216),
	SENDID VARCHAR(16777216),
	SUBSCRIBERKEY VARCHAR(16777216),
	EMAILADDRESS VARCHAR(16777216),
	SUBSCRIBERID VARCHAR(16777216),
	LISTID VARCHAR(16777216),
	EVENTDATE VARCHAR(16777216),
	EVENTTYPE VARCHAR(16777216),
	BATCHID VARCHAR(16777216),
	TRIGGEREDSENDEXTERNALKEY VARCHAR(16777216),
	ISUNIQUE VARCHAR(16777216),
	MESSAGE_ID VARCHAR(16777216),
	SERVICE_TRANSACTION_ID VARCHAR(16777216),
	BRAND_ID VARCHAR(255),
	SOURCE_SYSTEM_NM VARCHAR(255),
	LOAD_ID NUMBER(38,0),
	LOAD_DTTM TIMESTAMP_NTZ(9),
	UPDATE_ID NUMBER(38,0),
	UPDATE_DTTM TIMESTAMP_NTZ(9),
	LOAD_FILENAME VARCHAR(16777216)
);
create TABLE IF NOT EXISTS SFMC_CRM_PUSH_MESSAGE_DETAIL_RAW (
	DATE VARCHAR(16777216),
	CLIENTID VARCHAR(16777216),
	EID VARCHAR(16777216),
	APPNAME VARCHAR(16777216),
	MESSAGENAME VARCHAR(16777216),
	MESSAGEID VARCHAR(16777216),
	TEMPLATE VARCHAR(16777216),
	FORMAT VARCHAR(16777216),
	GEOFENCENAME VARCHAR(16777216),
	PAGENAME VARCHAR(16777216),
	CAMPAIGNS VARCHAR(16777216),
	DATETIMESEND VARCHAR(16777216),
	MESSAGECONTENT VARCHAR(16777216),
	MESSAGEOPENED VARCHAR(16777216),
	TIMEINAPP VARCHAR(16777216),
	PLATFORM VARCHAR(16777216),
	PLATFORMVERSION VARCHAR(16777216),
	STATUS VARCHAR(16777216),
	PUSHJOBID VARCHAR(16777216),
	SYSTEMTOKEN VARCHAR(16777216),
	INBOXDOWNLOAD VARCHAR(16777216),
	INBOXOPEN VARCHAR(16777216),
	REQUESTID VARCHAR(16777216),
	OPENDATE VARCHAR(16777216),
	SERVICERESPONSE VARCHAR(16777216),
	IOSMEDIAURL VARCHAR(16777216),
	ANDROIDMEDIAURL VARCHAR(16777216),
	MEDIAALT VARCHAR(16777216),
	DEVICEID VARCHAR(16777216),
	CONTACTKEY VARCHAR(16777216),
	SOURCE_SYSTEM_NM VARCHAR(255),
	BRAND_ID VARCHAR(255),
	LOAD_ID NUMBER(38,0),
	LOAD_DTTM TIMESTAMP_NTZ(9),
	UPDATE_ID NUMBER(38,0),
	UPDATE_DTTM TIMESTAMP_NTZ(9),
	LOAD_FILENAME VARCHAR(16777216)
);
create TABLE IF NOT EXISTS SFMC_CRM_SEND_JOB_RAW (
	CLIENTID VARCHAR(16777216),
	SENDID VARCHAR(16777216),
	FROMNAME VARCHAR(16777216),
	FROMEMAIL VARCHAR(16777216),
	SCHEDTIME TIMESTAMP_NTZ(9),
	SUBJECT VARCHAR(16777216),
	EMAILNAME VARCHAR(16777216),
	TRIGGEREDSENDEXTERNALKEY VARCHAR(16777216),
	SENDDEFINITIONEXTERNALKEY VARCHAR(16777216),
	JOBSTATUS VARCHAR(16777216),
	PREVIEWURL VARCHAR(16777216),
	ISMULTIPART VARCHAR(16777216),
	ADDITIONAL VARCHAR(16777216),
	MESSAGE_ID VARCHAR(16777216),
	SOURCE_SYSTEM_NM VARCHAR(255),
	BRAND_ID VARCHAR(255),
	LOAD_ID NUMBER(38,0),
	LOAD_DTTM TIMESTAMP_NTZ(9),
	UPDATE_ID NUMBER(38,0),
	UPDATE_DTTM TIMESTAMP_NTZ(9),
	LOAD_FILENAME VARCHAR(16777216)
);
create TABLE IF NOT EXISTS SFMC_CRM_SEND_JOB_RAW_TEMP (
	CLIENTID VARCHAR(16777216),
	SENDID VARCHAR(16777216),
	FROMNAME VARCHAR(16777216),
	FROMEMAIL VARCHAR(16777216),
	SCHEDTIME VARCHAR(16777216),
	SENTTIME VARCHAR(16777216),
	SUBJECT VARCHAR(16777216),
	EMAILNAME VARCHAR(16777216),
	TRIGGEREDSENDEXTERNALKEY VARCHAR(16777216),
	SENDDEFINITIONEXTERNALKEY VARCHAR(16777216),
	JOBSTATUS VARCHAR(16777216),
	PREVIEWURL VARCHAR(16777216),
	ISMULTIPART VARCHAR(16777216),
	ADDITIONAL VARCHAR(16777216),
	MESSAGE_ID VARCHAR(16777216),
	SOURCE_SYSTEM_NM VARCHAR(255),
	BRAND_ID VARCHAR(255),
	LOAD_ID NUMBER(38,0),
	LOAD_DTTM TIMESTAMP_NTZ(9),
	UPDATE_ID NUMBER(38,0),
	UPDATE_DTTM TIMESTAMP_NTZ(9),
	LOAD_FILENAME VARCHAR(16777216)
);
create TABLE IF NOT EXISTS SFMC_CRM_SEND_LOG_RAW (
	JOBID VARCHAR(16777216),
	LISTID VARCHAR(16777216),
	BATCHID VARCHAR(16777216),
	SUBID VARCHAR(16777216),
	TRIGGEREDSENDID VARCHAR(16777216),
	ERRORCODE_ VARCHAR(16777216),
	DATE VARCHAR(16777216),
	CUSTOMER_ID VARCHAR(16777216),
	SUBSCRIBERKEY VARCHAR(16777216),
	DATASOURCENAME VARCHAR(16777216),
	EMAILADDR VARCHAR(16777216),
	OFFER_CODE VARCHAR(16777216),
	OFFER_NAME VARCHAR(16777216),
	PARENTOFFERID VARCHAR(16777216),
	JOURNEYNAME VARCHAR(16777216),
	JOURNEYSTEP VARCHAR(16777216),
	SOC VARCHAR(16777216),
	USER_DEFINED_SEGMENT1 VARCHAR(16777216),
	USER_DEFINED_SEGMENT2 VARCHAR(16777216),
	USER_DEFINED_SEGMENT3 VARCHAR(16777216),
	USER_DEFINED_SEGMENT4 VARCHAR(16777216),
	USER_DEFINED_SEGMENT5 VARCHAR(16777216),
	OFFER1DECISIONLOGIC VARCHAR(16777216),
	EMAILNAME VARCHAR(16777216),
	CREATIVE_VARIANT VARCHAR(16777216),
	CAMPAIGN_ID VARCHAR(16777216),
	CAMPAIGN_NAME VARCHAR(16777216),
	CAMPAIGN_TYPE VARCHAR(16777216),
	CAMPAIGN_CATEGORY VARCHAR(16777216),
	CAMPAIGN_DESCRIPTION VARCHAR(16777216),
	CAMPAIGN_OBJECTIVE VARCHAR(16777216),
	CAMPAIGN_START_DATE VARCHAR(16777216),
	CAMPAIGN_END_DATE VARCHAR(16777216),
	CAMPAIGN_DURATION VARCHAR(16777216),
	POINTBALANCE VARCHAR(16777216),
	MEMBERID VARCHAR(16777216),
	SOURCE_SYSTEM_NM VARCHAR(255),
	BRAND_ID VARCHAR(255),
	LOAD_ID NUMBER(38,0),
	LOAD_DTTM TIMESTAMP_NTZ(9),
	UPDATE_ID NUMBER(38,0),
	UPDATE_DTTM TIMESTAMP_NTZ(9),
	LOAD_FILENAME VARCHAR(16777216)
);
create TABLE IF NOT EXISTS SFMC_CRM_SENT_RAW (
	CLIENTID VARCHAR(16777216),
	SENDID VARCHAR(16777216),
	SUBSCRIBERKEY VARCHAR(16777216),
	EMAILADDRESS VARCHAR(16777216),
	SUBSCRIBERID VARCHAR(16777216),
	LISTID VARCHAR(16777216),
	EVENTDATE VARCHAR(16777216),
	EVENTTYPE VARCHAR(16777216),
	BATCHID VARCHAR(16777216),
	TRIGGEREDSENDEXTERNALKEY VARCHAR(16777216),
	SOURCE_SYSTEM_NM VARCHAR(255),
	BRAND_ID VARCHAR(255),
	LOAD_ID NUMBER(38,0),
	LOAD_DTTM TIMESTAMP_NTZ(9),
	UPDATE_ID NUMBER(38,0),
	UPDATE_DTTM TIMESTAMP_NTZ(9),
	LOAD_FILENAME VARCHAR(16777216)
);
create TABLE IF NOT EXISTS SFMC_CRM_UNSUBSCRIBE_RAW (
	FOLDERNAME_M VARCHAR(16777216),
	CLIENTID VARCHAR(16777216),
	SENDID VARCHAR(16777216),
	SUBSCRIBERKEY VARCHAR(16777216),
	EMAILADDRESS VARCHAR(16777216),
	SUBSCRIBERID VARCHAR(16777216),
	LISTID VARCHAR(16777216),
	EVENTDATE VARCHAR(16777216),
	EVENTTYPE VARCHAR(16777216),
	BATCHID VARCHAR(16777216),
	TRIGGEREDSENDEXTERNALKEY VARCHAR(16777216),
	SERVICE_TRANSACTION_ID VARCHAR(16777216),
	SOURCE_SYSTEM_NM VARCHAR(255),
	BRAND_ID VARCHAR(255),
	LOAD_ID NUMBER(38,0),
	LOAD_DTTM TIMESTAMP_NTZ(9),
	UPDATE_ID NUMBER(38,0),
	UPDATE_DTTM TIMESTAMP_NTZ(9),
	LOAD_FILENAME VARCHAR(16777216)
);
create TABLE IF NOT EXISTS TEST_BATCH_AUDIT (
	LOAD_ID VARCHAR(50) NOT NULL,
	BATCH_ID NUMBER(38,0) NOT NULL,
	STATUS VARCHAR(16777216) NOT NULL,
	START_TIME TIMESTAMP_NTZ(9) NOT NULL,
	END_TIME TIMESTAMP_NTZ(9),
	FAILURE_MSG VARCHAR(16777216),
	USERNAME VARCHAR(16777216) NOT NULL,
	BUSINESS_DATE DATE
);
create TABLE IF NOT EXISTS TEST_BATCH_CONTROL_RUN (
	BATCH_CONTROL_RUN_ID NUMBER(38,0),
	BATCH_START_TS TIMESTAMP_NTZ(9),
	BATCH_END_TS TIMESTAMP_NTZ(9),
	ELAPSED_TIME VARCHAR(16777216),
	BATCH_CURR_IND VARCHAR(16777216),
	BATCH_STTS VARCHAR(16777216),
	BATCH_FAILURE_BYPASS_IND VARCHAR(16777216),
	BATCH_FAILURE_BYPASS_USER VARCHAR(16777216),
	BATCH_FAILURE_BYPASS_TS VARCHAR(16777216),
	BATCH_ERROR_MSG VARCHAR(16777216),
	BATCH_LOG_LOCN VARCHAR(16777216),
	INSERT_USER VARCHAR(16777216),
	INSERT_TS TIMESTAMP_NTZ(9),
	UPDT_USER VARCHAR(16777216),
	UPDT_TS VARCHAR(16777216)
);
create TABLE IF NOT EXISTS TEST_BATCH_CONTROL_RUN_UNUSED (
	LOAD_ID VARCHAR(50) NOT NULL,
	BATCH_ID NUMBER(38,0) NOT NULL,
	STATUS VARCHAR(16777216) NOT NULL,
	START_TIME TIMESTAMP_NTZ(9) NOT NULL,
	END_TIME TIMESTAMP_NTZ(9),
	FAILURE_MSG VARCHAR(16777216),
	USERNAME VARCHAR(16777216) NOT NULL,
	BUSINESS_DATE DATE
);
create TABLE IF NOT EXISTS TEST_BATCH_CONTROL_SEED (
	BATCH_CONTROL_ID NUMBER(38,0) autoincrement,
	BATCH_CONTROL_NM VARCHAR(16777216),
	PARENT_BATCH_CONTROL_ID NUMBER(38,0),
	INSRT_USER VARCHAR(16777216),
	INSRT_TS TIMESTAMP_NTZ(9),
	UPDT_USER VARCHAR(16777216),
	UPDT_TS TIMESTAMP_NTZ(9)
);
create TABLE IF NOT EXISTS TEST_GRANTS_PRIVELEGES (
	CUSTOMERKEY VARCHAR(16777216),
	EMAILADDRESS VARCHAR(16777216),
	EMAILCHANNELOPTOUTFLAG VARCHAR(16777216),
	EMAILCHANNELOPTSTATUSDATE VARCHAR(16777216),
	EMAILCHANNELOPTSTATUSSOURCE VARCHAR(16777216),
	SOURCE_SYSTEM_NM VARCHAR(255),
	BRAND_ID VARCHAR(255),
	LOAD_ID NUMBER(38,0),
	LOAD_DTTM TIMESTAMP_NTZ(9),
	UPDATE_ID NUMBER(38,0),
	UPDATE_DTTM TIMESTAMP_NTZ(9),
	LOAD_FILENAME VARCHAR(16777216)
);
create TABLE IF NOT EXISTS TEST_JOB_CONTROL_RUN (
	JOB_CONTROL_RUN_ID VARCHAR(16777216),
	BATCH_CONTROL_RUN_ID NUMBER(38,0),
	JOB_CONTROL_ID NUMBER(38,0),
	JOB_START_TS TIMESTAMP_NTZ(9),
	JOB_END_TS TIMESTAMP_NTZ(9),
	JOB_SELECTION_START_TS TIMESTAMP_NTZ(9),
	JOB_SELECTION_END_TS TIMESTAMP_NTZ(9),
	JOB_STTS VARCHAR(16777216),
	JOB_CURR_ID VARCHAR(16777216),
	JOB_REC_READ_CNT NUMBER(38,0),
	JOB_REC_PRCSD_CNT NUMBER(38,0),
	JOB_REC_UPDT_CNT NUMBER(38,0),
	JOB_REC_DELETE_CNT NUMBER(38,0),
	JOB_REC_ERROR_CNT NUMBER(38,0),
	JOB_ERROR_CODE VARCHAR(16777216),
	JOB_ERROR_DTLS VARCHAR(16777216),
	JOB_LOG_LOCN VARCHAR(16777216),
	INSRT_USER VARCHAR(16777216),
	INSRT_TS TIMESTAMP_NTZ(9),
	UPDT_USER VARCHAR(16777216),
	UPDT_TS TIMESTAMP_NTZ(9)
);
create TABLE IF NOT EXISTS TEST_JOB_CONTROL_SEED (
	JOB_CONTROL_ID NUMBER(38,0) autoincrement,
	JOB_CONTROL_NM VARCHAR(16777216),
	JOB_DEST_GRP_ID NUMBER(38,0),
	JOB_SRC_GRP_ID NUMBER(38,0),
	BATCH_CONTROL_ID NUMBER(38,0),
	IGNORE_1 BOOLEAN,
	IGNORE_2 BOOLEAN,
	JOB_CONTROL_DESC VARCHAR(16777216),
	JOB_TYPE VARCHAR(16777216),
	CDC_IND VARCHAR(16777216),
	INITIAL_LOAD_IND VARCHAR(16777216),
	TRUNCATE_DEST_IND VARCHAR(16777216),
	IGNORE_JOB_RUN_IND VARCHAR(16777216),
	JOB_FREQUENCY NUMBER(38,0),
	INTRADAY_FREQUENCY NUMBER(38,0),
	ROLLING_PERIOD NUMBER(38,0),
	WEEK_DAY NUMBER(38,0),
	MONTH_DAY NUMBER(38,0),
	SCHEDULE_TIME VARCHAR(16777216),
	SCHEDULE_TIME_ZONE VARCHAR(16777216),
	INSRT_USER VARCHAR(16777216),
	INSRT_TS TIMESTAMP_NTZ(9),
	UPDT_USER VARCHAR(16777216),
	UPDT_TS TIMESTAMP_NTZ(9)
);
create TABLE IF NOT EXISTS TEST_JOB_DEST_GRP_SEED (
	JOB_DEST_GRP_ID NUMBER(38,0) autoincrement,
	JOB_DEST_GRP_NM VARCHAR(16777216),
	LOC_ID VARCHAR(16777216),
	INSRT_USER VARCHAR(16777216),
	INSRT_TS TIMESTAMP_NTZ(9),
	UPDT_USER VARCHAR(16777216),
	UPDT_TS TIMESTAMP_NTZ(9)
);
create TABLE IF NOT EXISTS TEST_JOB_SRC_GRP_SEED (
	JOB_SRC_GRP_ID NUMBER(38,0) autoincrement,
	JOB_SRC_GRP_NM VARCHAR(16777216),
	LOC_ID VARCHAR(16777216),
	INSRT_USER VARCHAR(16777216),
	INSRT_TS TIMESTAMP_NTZ(9),
	UPDT_USER VARCHAR(16777216),
	UPDT_TS TIMESTAMP_NTZ(9)
);
create TABLE IF NOT EXISTS TEST_LOC_SEED (
	LOC_ID NUMBER(38,0) autoincrement,
	LOC_NM VARCHAR(16777216),
	SEG_NM VARCHAR(16777216),
	SUB_SEG_NM VARCHAR(16777216),
	LOC_TYPE VARCHAR(16777216),
	LOC_LOAD_TYPE VARCHAR(16777216),
	FILE_LOC_NM VARCHAR(16777216),
	FILE_FRMT_TYPE VARCHAR(16777216),
	DB_TYPE VARCHAR(16777216),
	INSRT_USER VARCHAR(16777216),
	INSRT_TS TIMESTAMP_NTZ(9),
	UPDT_USER VARCHAR(16777216),
	UPDT_TS TIMESTAMP_NTZ(9)
);
create TABLE IF NOT EXISTS TEST_LOGGING_RAW (
	TEST1 VARCHAR(16777216),
	TEST2 VARCHAR(16777216),
	TEST3 VARCHAR(16777216)
);
create TABLE IF NOT EXISTS TEST_PARENT_BATCH_CONTROL_RUN (
	LOAD_ID VARCHAR(50) NOT NULL,
	BATCH_ID NUMBER(38,0) NOT NULL,
	STATUS VARCHAR(16777216) NOT NULL,
	START_TIME TIMESTAMP_NTZ(9) NOT NULL,
	END_TIME TIMESTAMP_NTZ(9),
	FAILURE_MSG VARCHAR(16777216),
	USERNAME VARCHAR(16777216) NOT NULL,
	BUSINESS_DATE DATE
);
create TABLE IF NOT EXISTS TEST_PARENT_BATCH_CONTROL_SEED (
	PARENT_BATCH_CONTROL_ID NUMBER(38,0) autoincrement,
	PARENT_BATCH_CONTROL_NM VARCHAR(16777216),
	INSRT_USER VARCHAR(16777216),
	INSRT_TS TIMESTAMP_NTZ(9),
	UPDT_USER VARCHAR(16777216),
	UPDT_TS TIMESTAMP_NTZ(9)
);
create TABLE IF NOT EXISTS TEST_SNOWFLAKE_LOGGING (
	ENTITY_ID NUMBER(38,0) NOT NULL autoincrement,
	QUERY_ID VARCHAR(16777216),
	LOAD_ID VARCHAR(50) NOT NULL,
	ENTITY_NAME VARCHAR(16777216) NOT NULL,
	START_TIME TIMESTAMP_NTZ(9) NOT NULL,
	END_TIME TIMESTAMP_NTZ(9),
	BUSINESS_DATE DATE,
	ROW_INSERTED NUMBER(38,0),
	ROW_MODIFIED NUMBER(38,0),
	ROW_DELETED NUMBER(38,0),
	EXECUTION_STATUS VARCHAR(50),
	ERROR_CODE NUMBER(38,0),
	ERROR_MESSAGE VARCHAR(16777216),
	BYTES_SCANNED NUMBER(38,0),
	COMPILATION_TIME NUMBER(38,0),
	EXECUTION_TIME NUMBER(38,0),
	CREDITS_USED_CLOUD_SERVICES FLOAT,
	primary key (ENTITY_ID)
);
create view IF NOT EXISTS EPS_CRM_OPTOUT_RAW_BV(
	CUSTOMERKEY,
	EMAILADDRESS,
	LOAD_ID
) as 
SELECT CUSTOMERKEY,EMAILADDRESS,TO_VARCHAR(LOAD_ID) FROM EPS_CRM_OPTOUT_RAW LIMIT 10;
CREATE FILE FORMAT IF NOT EXISTS DNKN_CSV_FORMAT
	FIELD_DELIMITER = '|'
	SKIP_HEADER = 1
	FIELD_OPTIONALLY_ENCLOSED_BY = '\"'
;
CREATE PROCEDURE IF NOT EXISTS ADF_UPDATE_LOG("FILENAME" VARCHAR(16777216), "DATESTART" TIMESTAMP_NTZ(9), "STATUS" VARCHAR(16777216), "ID" VARCHAR(16777216), "DATAREAD" VARCHAR(16777216), "ROWSREAD" VARCHAR(16777216), "ROWSCOPIED" VARCHAR(16777216), "ROWSSKIPPED" VARCHAR(16777216), "COPYDURATION" FLOAT, "DATEEND" TIMESTAMP_NTZ(9))
RETURNS VARCHAR(16777216)
LANGUAGE JAVASCRIPT
STRICT
EXECUTE AS OWNER
AS '
    var sql_command = `MERGE INTO ADF_LOGGING target
    USING (
        SELECT id, filename, dateStart, status, dataRead, rowsRead, rowsCopied, copyDuration, dateEnd 
        FROM (VALUES (`+id + `, ` + filename + `, ` + dateStart + `, ` + status + `, ` + dataRead + `, ` + rowsRead + `, ` + rowsCopied + `, ` + copyDuration + `, ` + dateEnd + `)) t
            (id, filename, dateStart, status, dataRead, rowsRead, rowsCopied, copyDuration, dateEnd ) 
    ) source
    ON source.id = target.id
    WHEN MATCHED THEN UPDATE SET target.filename=source.filename, target.dateStart=source.dateStart, target.status=source.status, target.dataRead=source.dataRead, target.rowsRead=source.rowsRead, 
        target.rowsCopied=source.rowsCopied, target.copyDuration=source.copyDuration, target.dateEnd=source.dateEnd
    WHEN NOT MATCHED THEN INSERT (filename, dateStart, status) 
        VALUES (source.filename, source.dateStart, source.status);`;
    
    return sql_command
      
    var sql_command2 = `set qid = last_query_id();`;
    var sql_command3 = `select max(ID) as ID from ADF_LOGGING AT(statement=>$qid);`;
     
    try {
        snowflake.execute (
            {sqlText: sql_command}
            ); 
        snowflake.execute (
            {sqlText: sql_command2}
            ); 
        var resultSet = snowflake.execute (
            {sqlText: sql_command3}
            ); 
        resultSet.next(); 
        
        var last_id = parseInt(resultSet.getColumnValue(1)); 
        return last_id;
        }
    catch (err)  {
        return 0;   // Return a success/error indicator.
        }
    ';
CREATE PROCEDURE IF NOT EXISTS ADF_UPDATE_LOG("FILENAME" VARCHAR(16777216), "DATESTART" VARCHAR(16777216), "STATUS" VARCHAR(16777216), "ID" FLOAT, "DATAREAD" FLOAT, "ROWSREAD" FLOAT, "ROWSCOPIED" FLOAT, "FILESWRITTEN" FLOAT, "COPYDURATION" FLOAT, "DATEEND" VARCHAR(16777216))
RETURNS VARCHAR(16777216)
LANGUAGE JAVASCRIPT
STRICT
EXECUTE AS CALLER
AS '
    var resultSet = snowflake.createStatement( {sqlText: "SELECT ''" + DATESTART + "''::TIMESTAMP_LTZ;"} ).execute(); 
    resultSet.next(); 
    var date_start = resultSet.getColumnValue(1); 
    
    var resultSet = snowflake.createStatement( {sqlText: "SELECT ''" + DATEEND + "''::TIMESTAMP_LTZ;"} ).execute(); 
    resultSet.next(); 
    var date_end = resultSet.getColumnValue(1); 
    
    var sql_command = `MERGE INTO ADF_LOGGING target
    USING (
        SELECT id, filename, dateStart, status, dataRead, rowsRead, rowsCopied, filesWritten, copyDuration, dateEnd 
        FROM (VALUES (`+ID + `, ''` + FILENAME + `'', ''` + DATESTART + `'', ''` + STATUS + `'', ` + DATAREAD + `, ` + ROWSREAD + `, ` + ROWSCOPIED + `, ` + FILESWRITTEN + `, ` + COPYDURATION + `, ''` + DATEEND + `'')) t
            (id, filename, dateStart, status, dataRead, rowsRead, rowsCopied, filesWritten, copyDuration, dateEnd ) 
    ) source
    ON source.id = target.id
    WHEN MATCHED THEN UPDATE SET target.filename=source.filename, target.dateStart=source.dateStart, target.status=source.status, target.dataRead=source.dataRead, target.rowsRead=source.rowsRead, 
        target.rowsCopied=source.rowsCopied, target.filesWritten=source.filesWritten, target.copyDuration=source.copyDuration, target.dateEnd=source.dateEnd
    WHEN NOT MATCHED THEN INSERT (filename, dateStart, status) 
        VALUES (source.filename, source.dateStart, source.status)
    `;
    
    var sql_command2 = "set qid = last_query_id()";
    var sql_command3 = "select max(ID) as ID from ADF_LOGGING AT(statement=>$qid)";
    
    try {
    
        snowflake.execute ({sqlText: sql_command}); 
        snowflake.execute ({sqlText: sql_command2}); 
    
        resultSet = snowflake.execute (
            {sqlText: sql_command3}
            ); 
        resultSet.next(); 
        
        var last_id = parseInt(resultSet.getColumnValue(1)); 
        return last_id;
        }
    catch (err)  {
        return err;   // Return a success/error indicator.
        }
    ';
CREATE PROCEDURE IF NOT EXISTS LOGENTITYOPERATIONWRAPPER()
RETURNS VARIANT
LANGUAGE JAVASCRIPT
EXECUTE AS CALLER
AS '
  var rs = snowflake.execute( { sqlText: 
      `SELECT * FROM table(information_schema.QUERY_HISTORY_BY_SESSION());`
       } );
';
CREATE PROCEDURE IF NOT EXISTS LOGENTITYOPERATIONWRAPPER("SQLTEXT" VARCHAR(16777216))
RETURNS VARIANT
LANGUAGE JAVASCRIPT
EXECUTE AS CALLER
AS '
  var rs = snowflake.execute( { sqlText: 
      `SELECT * FROM table(information_schema.QUERY_HISTORY_BY_SESSION());`
       } );
';
CREATE PROCEDURE IF NOT EXISTS LOGENTITYOPERATIONWRAPPER("SQLTEXT" VARCHAR(16777216), "BATCH_CONTROL_RUN_ID" VARCHAR(16777216), "JOB_CONTROL_ID" VARCHAR(16777216))
RETURNS VARIANT
LANGUAGE JAVASCRIPT
EXECUTE AS CALLER
AS '
    var log_msg = "";
    var status_message = "";
    var error_dtls = "";
    var query_id = null;
    var row_read = null;
    var row_inserted = null;
    var row_deleted = null;
    var row_modified = null;

    try {
        var insert_entity_audit_statement = snowflake.createStatement({
            sqlText:
                `INSERT INTO TEST_JOB_CONTROL_RUN
                    (JOB_CONTROL_RUN_ID,BATCH_CONTROL_RUN_ID,JOB_CONTROL_ID,JOB_START_TS,JOB_END_TS,JOB_SELECTION_START_TS,
                    JOB_SELECTION_END_TS,JOB_STTS,JOB_CURR_ID,JOB_REC_READ_CNT,JOB_REC_PRCSD_CNT,JOB_REC_UPDT_CNT,
                    JOB_REC_DELETE_CNT,JOB_REC_ERROR_CNT,JOB_ERROR_CODE,JOB_ERROR_DTLS,JOB_LOG_LOCN,INSRT_USER,INSRT_TS,UPDT_USER,UPDT_TS)
                VALUES (NULL,:1,:2,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL)`,
            binds:[BATCH_CONTROL_RUN_ID,JOB_CONTROL_ID]
            });
        insert_entity_audit_statement.execute();

        // Get exact query_id of the last inserted record
        var get_last_query_id_stmt = snowflake.createStatement({
            sqlText:`select last_query_id();`,
            binds:[insert_entity_audit_statement.getQueryId()]
        });
        var entity_audit_id_result = get_last_query_id_stmt.execute();
        entity_audit_id_result.next();
        var entity_audit_id = entity_audit_id_result.getColumnValue(1);

        var update_query_id = snowflake.createStatement({
                sqlText:
                    `UPDATE TEST_JOB_CONTROL_RUN
                    SET JOB_CURR_ID= :1
                    WHERE JOB_CURR_ID is NULL`,
                binds:[entity_audit_id]
            });

            update_query_id.execute();

        try {
            var client_statement = snowflake.createStatement({
                sqlText: SQLTEXT,
            });

            log_msg += ''\\nStatement of `client_statement`'';
            log_msg += ''\\n  SqlText = '' + client_statement.getSqlText();

            var client_result = client_statement.execute();

            query_id = client_statement.getQueryId();
            row_inserted = client_statement.getNumRowsInserted();
            row_modified = client_statement.getNumRowsUpdated();
            row_deleted = client_statement.getNumRowsDeleted();
            row_read = client_statement.getNumRowsAffected();

            log_msg += ''\\n  QueryId = '' + query_id;
            log_msg += ''\\n  ColumnCount = '' + client_statement.getColumnCount();
            log_msg += ''\\n  RowCount = '' + client_statement.getRowCount();
            log_msg += ''\\n  NumDuplicateRowsUpdated = '' + client_statement.getNumDuplicateRowsUpdated();
            log_msg += ''\\n  NumRowsAffected = '' + client_statement.getNumRowsAffected();
            log_msg += ''\\n  NumRowsDeleted = '' + row_deleted;
            log_msg += ''\\n  NumRowsInserted = '' + row_inserted;
            log_msg += ''\\n  NumRowsUpdated = '' + row_modified;

            log_msg += ''\\nResultSet of `client_statement`'';
            for (let colIdx = 1; colIdx <= client_statement.getColumnCount(); colIdx++ ) {
                log_msg += ''  |  '' + client_statement.getColumnName(colIdx);
            }
            log_msg += ''  |\\n'';

            limit = 10;
            ind = 0;
            while(client_result.next() && ind < limit) {
                for (let colIdx = 1; colIdx <= client_result.getColumnCount(); colIdx++ ) {
                    log_msg += ''  |  '' + client_result.getColumnValueAsString(colIdx);
                }
                log_msg += ''  |\\n'';
            }
        } catch(err) {
            log_msg += "\\nFailed: Code: " + err.code + "\\n  State: " + err.state;
            log_msg += "\\n  Message: " + err.message;
            log_msg += "\\nStack Trace:\\n" + err.stackTraceTxt;
            
            status_message = "failed";
            error_dtls = err.message + ''\\n'' + err.stackTraceTxt;
        } finally {
            status_message = "success"

            log_msg += status_message;
            log_msg += "\\n";

            var update_entity_audit_stmt = snowflake.createStatement({
                    sqlText:
                        `UPDATE TEST_JOB_CONTROL_RUN as audit
                        SET JOB_CONTROL_RUN_ID= :6,
                            JOB_START_TS= inf.START_TIME,
                            JOB_END_TS= inf.END_TIME,
                            JOB_SELECTION_START_TS= inf.START_TIME,
                            JOB_SELECTION_END_TS= inf.END_TIME,
                            JOB_STTS= :2,
                            JOB_CURR_ID= :1,
                            JOB_REC_READ_CNT= :3,
                            JOB_REC_PRCSD_CNT= :4,
                            JOB_REC_UPDT_CNT= :5,
                            JOB_REC_DELETE_CNT= :6,
                            JOB_REC_ERROR_CNT= 000000,
                            JOB_ERROR_CODE= inf.ERROR_CODE,
                            JOB_ERROR_DTLS= :7,
                            JOB_LOG_LOCN= ''placeholder'',
                            INSRT_USER= inf.USER_NAME,
                            INSRT_TS= sysdate(),
                            UPDT_USER= inf.USER_NAME,
                            UPDT_TS= sysdate()
                        FROM table(information_schema.QUERY_HISTORY_BY_SESSION()) as inf
                        WHERE audit.job_curr_id= :8`,
                    binds:[query_id,status_message,row_read,row_inserted,row_modified,row_deleted,error_dtls,entity_audit_id]
                });

            update_entity_audit_stmt.execute();
        }

    } catch(err) {
        log_msg += "\\nFailed: Code: " + err.code + "\\n  State: " + err.state;
        log_msg += "\\n  Message: " + err.message;
        log_msg += "\\nStack Trace:\\n" + err.stackTraceTxt;
    }

    return log_msg;
';
CREATE PROCEDURE IF NOT EXISTS LOGENTITYOPERATIONWRAPPER("SQLTEXT" VARCHAR(16777216), "BINDS" ARRAY, "LOADID" VARCHAR(16777216), "ENTITYNAME" VARCHAR(16777216), "BUSINESSDATE" VARCHAR(16777216))
RETURNS VARIANT
LANGUAGE JAVASCRIPT
EXECUTE AS CALLER
AS '

    var array_or_rows = [];

var insert_entity_audit_statement = snowflake.createStatement({
        sqlText: `INSERT INTO TEST_SNOWFLAKE_LOGGING
        (QUERY_ID, LOAD_ID, ENTITY_NAME, START_TIME, END_TIME, BUSINESS_DATE,
        ROW_INSERTED, ROW_MODIFIED,ROW_DELETED, EXECUTION_STATUS, ERROR_CODE,
        ERROR_MESSAGE, BYTES_SCANNED, COMPILATION_TIME, EXECUTION_TIME,CREDITS_USED_CLOUD_SERVICES)
        VALUES (NULL,:1,:2,current_timestamp(),NULL,:3,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL)`,
        binds:[LOADID,ENTITYNAME,BUSINESSDATE]
        });
        
        insert_entity_audit_statement.execute();

        var get_entity_audit_id_stmt = snowflake.createStatement(
        {
            sqlText:`SELECT MAX(ENTITY_ID) FROM TEST_SNOWFLAKE_LOGGING \\
                    AT(STATEMENT => :1)`,
            binds:[insert_entity_audit_statement.getQueryId()]
        });

        var entity_audit_id_result = get_entity_audit_id_stmt.execute();

        entity_audit_id_result.next();

        var entity_audit_id = entity_audit_id_result.getColumnValue(1);
        
        var client_statement = snowflake.createStatement(
        {
            sqlText: SQLTEXT,
            binds:BINDS
        });

       var row_inserted = null;
       var row_deleted = null;
       var row_modified = null;

    try{
        var client_result = client_statement.execute();
        var column_count = client_statement.getColumnCount();
        while(client_result.next()){
            row_as_json={};
            for (var col_num = 1; col_num < column_count + 1; col_num = col_num + 1) {
                var col_name = client_statement.getColumnName(col_num);
                row_as_json[col_name] = client_result.getColumnValue(col_num);
                switch (col_name) {
                    case ''number of rows inserted'':
                        row_inserted = row_as_json[col_name];
                        break;
                    case ''number of rows deleted'':
                        row_deleted = row_as_json[col_name];
                        break;
                    case ''number of rows updated'':
                        row_modified = row_as_json[col_name];
                        break;
                }
            }
            array_or_rows.push(row_as_json);
        }
        return array_or_rows;
    }finally{
        var query_id = client_statement.getQueryId();
        
         var update_entity_audit_stmt = snowflake.createStatement(
            {
                sqlText: 
                `UPDATE TEST_SNOWFLAKE_LOGGING as audit
                    SET QUERY_ID= :1, START_TIME=inf.START_TIME, END_TIME=inf.END_TIME, ROW_INSERTED= :2, ROW_MODIFIED= :3,
                    ROW_DELETED= :4, EXECUTION_STATUS= inf.EXECUTION_STATUS, ERROR_CODE= inf.ERROR_CODE,
                    BYTES_SCANNED= inf.BYTES_SCANNED, COMPILATION_TIME= inf.COMPILATION_TIME,
                    EXECUTION_TIME= inf.EXECUTION_TIME, CREDITS_USED_CLOUD_SERVICES= inf.CREDITS_USED_CLOUD_SERVICES
                FROM table(information_schema.QUERY_HISTORY_BY_SESSION()) as inf
                WHERE audit.ENTITY_ID= :5 and inf.QUERY_ID= :1`,
                binds:[query_id,row_inserted,row_modified,row_deleted,entity_audit_id]
            });
        update_entity_audit_stmt.execute();
    }
';
CREATE PROCEDURE IF NOT EXISTS LOGENTITYOPERATIONWRAPPER("SQLTEXT" VARCHAR(16777216), "LOADID" VARCHAR(16777216), "ENTITYNAME" VARCHAR(16777216), "BUSINESSDATE" VARCHAR(16777216))
RETURNS VARIANT
LANGUAGE JAVASCRIPT
EXECUTE AS CALLER
AS '
    var log_msg = "";
    var query_id = null;
    var row_inserted = null;
    var row_deleted = null;
    var row_modified = null;

    try {  

        var insert_entity_audit_statement = snowflake.createStatement({
            sqlText: 
                `INSERT INTO TEST_SNOWFLAKE_LOGGING
                    (QUERY_ID, LOAD_ID, ENTITY_NAME, START_TIME, END_TIME, BUSINESS_DATE,
                    ROW_INSERTED, ROW_MODIFIED,ROW_DELETED, EXECUTION_STATUS, ERROR_CODE,
                    ERROR_MESSAGE, BYTES_SCANNED, COMPILATION_TIME, EXECUTION_TIME,CREDITS_USED_CLOUD_SERVICES)
                VALUES (NULL,:1,:2,current_timestamp(),NULL,:3,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL)`,
            binds:[LOADID,ENTITYNAME,BUSINESSDATE]
            });
        insert_entity_audit_statement.execute();

        // Get exact ENTITY_ID of the inserted record
        var get_entity_audit_id_stmt = snowflake.createStatement({
            sqlText:`SELECT MAX(ENTITY_ID) FROM TEST_SNOWFLAKE_LOGGING AT(STATEMENT => :1)`,
            binds:[insert_entity_audit_statement.getQueryId()]
        });
        var entity_audit_id_result = get_entity_audit_id_stmt.execute();
        entity_audit_id_result.next();
        var entity_audit_id = entity_audit_id_result.getColumnValue(1);

        try {
            var client_statement = snowflake.createStatement({
                sqlText: SQLTEXT,
            });

            log_msg += ''\\nStatement of `client_statement`'';
            log_msg += ''\\n  SqlText = '' + client_statement.getSqlText();

            var client_result = client_statement.execute();

            query_id = client_statement.getQueryId();
            row_inserted = client_statement.getNumRowsInserted();
            row_modified = client_statement.getNumRowsUpdated();
            row_deleted = client_statement.getNumRowsDeleted();

            
            log_msg += ''\\n  QueryId = '' + query_id;
            log_msg += ''\\n  ColumnCount = '' + client_statement.getColumnCount();
            log_msg += ''\\n  RowCount = '' + client_statement.getRowCount();
            log_msg += ''\\n  NumDuplicateRowsUpdated = '' + client_statement.getNumDuplicateRowsUpdated();
            log_msg += ''\\n  NumRowsAffected = '' + client_statement.getNumRowsAffected();
            log_msg += ''\\n  NumRowsDeleted = '' + row_deleted;
            log_msg += ''\\n  NumRowsInserted = '' + row_inserted;
            log_msg += ''\\n  NumRowsUpdated = '' + row_modified;

            log_msg += ''\\nResultSet of `client_statement`'';
            log_msg += "\\n";
            for (let colIdx = 1; colIdx <= client_statement.getColumnCount(); colIdx++ ) {
                log_msg += ''  |  '' + client_statement.getColumnName(colIdx);
            }
            log_msg += ''  |\\n'';

            limit = 10;
            ind = 0;
            while(client_result.next() && ind < limit) {
                for (let colIdx = 1; colIdx <= client_result.getColumnCount(); colIdx++ ) {
                    log_msg += ''  |  '' + client_result.getColumnValueAsString(colIdx);
                }
                log_msg += ''  |\\n'';
            }
        } catch(err) {
            log_msg += "\\nFailed: Code: " + err.code + "\\n  State: " + err.state;
            log_msg += "\\n  Message: " + err.message;
            log_msg += "\\nStack Trace:\\n" + err.stackTraceTxt; 
        } finally {
            
            var update_entity_audit_stmt = snowflake.createStatement(
                {
                    sqlText:
                        `UPDATE TEST_SNOWFLAKE_LOGGING as audit
                        SET QUERY_ID= :1, START_TIME=inf.START_TIME, END_TIME=inf.END_TIME, ROW_INSERTED= :2, ROW_MODIFIED= :3,
                            ROW_DELETED= :4, EXECUTION_STATUS= inf.EXECUTION_STATUS, ERROR_CODE= inf.ERROR_CODE,
                            BYTES_SCANNED= inf.BYTES_SCANNED, COMPILATION_TIME= inf.COMPILATION_TIME,
                            EXECUTION_TIME= inf.EXECUTION_TIME, CREDITS_USED_CLOUD_SERVICES= inf.CREDITS_USED_CLOUD_SERVICES
                        FROM table(information_schema.QUERY_HISTORY_BY_SESSION()) as inf
                        WHERE audit.ENTITY_ID= :5 and inf.QUERY_ID= :1`,
                    binds:[query_id,row_inserted,row_modified,row_deleted,entity_audit_id]
                });
        
            update_entity_audit_stmt.execute();

        }

    } catch(err) {
        log_msg += "\\nFailed: Code: " + err.code + "\\n  State: " + err.state;
        log_msg += "\\n  Message: " + err.message;
        log_msg += "\\nStack Trace:\\n" + err.stackTraceTxt; 
    }

    return log_msg;
';
CREATE PROCEDURE IF NOT EXISTS MOVE_TABLES()
RETURNS VARCHAR(16777216)
LANGUAGE JAVASCRIPT
EXECUTE AS OWNER
AS '
    snowflake.execute({sqlText: `show tables in RDS_DEV.DUN;`});
    var return_value = " ";
    var tables = snowflake.execute({sqlText: `select name from table(result_scan(last_query_id()));`});
     while (tables.next())  {
         return_value += tables.getColumnValue(1) + " ";
         }
      return return_value;
';
CREATE PROCEDURE IF NOT EXISTS TESTLOGGINGCALL()
RETURNS VARCHAR(16777216)
LANGUAGE JAVASCRIPT
STRICT
EXECUTE AS OWNER
AS '
    var sql_command = ''SELECT COUNT(*) FROM "RDS_DEV"."DNKN"."SFMC_CRM_BOUNCE_RAW";'';
    snowflake.execute (
        {sqlText: sql_command}
    );
    ';
CREATE PROCEDURE IF NOT EXISTS TESTLOGGINGCALL("QUERY_STRING" VARCHAR(16777216))
RETURNS VARCHAR(16777216)
LANGUAGE JAVASCRIPT
STRICT
EXECUTE AS OWNER
AS '
    var sql_command = QUERY_STRING;
    snowflake.execute (
        {sqlText: sql_command}
    );
    ';