dag_config:
  dag_id: 'JJ_ORACLEGL_MASTER_ALL_HI_PL'
  default_args:
    'owner': 'SALESRECON'
    'email': ["DataServicesHelp@inspirebrands.com", "itdataservicessupport@inspirebrands.com","rajesh.patil@inspirebrands.com"]
    'email_on_failure': True
    'depends_on_past': False
    'retries' : 0
  doc_md: |-
    ### Master DAG
    This DAG is responsible for triggering the other transaction DAGs for transaction data
  schedule_interval: '0 10 * * *'
  tags: ['SALESRECON_JJ', 'ORACLEGL', 'MASTERDAG']
  catchup : False  

child_dags:
  JJ_ORACLEGL_FTP_TO_ADLS_ALL_HI_PL: 'JJ_ORACLEGL_FTP_TO_ADLS_ALL_HI_PL'
  JJ_ORACLEGL_ADLS_TO_RDS_ALL_HI_PL: 'JJ_ORACLEGL_ADLS_TO_RDS_ALL_HI_PL'
  JJ_ORACLEGL_RDS_TO_IDS_DAILY__ALL_HI_PL: 'JJ_ORACLEGL_RDS_TO_IDS_DAILY__ALL_HI_PL'
  