CREATE EXTERNAL TABLE `vv_db.hvtb_nbx_core_crm_contact`(
  `accountid` string, 
  `agencyname__c` string, 
  `agency_environment__c` string, 
  `agent_status__c` string, 
  `agent_type_c` string, 
  `anniversary_date__c` timestamp, 
  `assistantname` string, 
  `assistantphone` string, 
  `birthdate` timestamp, 
  `createdbyid` string, 
  `createddate` timestamp, 
  `department` string, 
  `description` string, 
  `donotcall` boolean, 
  `email` string, 
  `emailbounceddate` timestamp, 
  `emailbouncedreason` string, 
  `et4ae5__hasoptedoutofmobile__c` boolean, 
  `et4ae5__mobile_country_code__c` string, 
  `fax` string, 
  `firstname` string, 
  `gender__c` string, 
  `hasoptedoutofemail` boolean, 
  `hasoptedoutoffax` boolean, 
  `homephone` string, 
  `iatanexpdate__c` timestamp, 
  `iatan_company_name__c` string, 
  `iatan_holder_name__c` string, 
  `iatan_number__c` double, 
  `id` string, 
  `isdeleted` boolean, 
  `ispersonaccount` boolean, 
  `is_approved__c` boolean, 
  `is_primary_contact__c` boolean, 
  `lastactivitydate` timestamp, 
  `lastcurequestdate` timestamp, 
  `lastcuupdatedate` timestamp, 
  `lastmodifiedbyid` string, 
  `lastmodifieddate` timestamp, 
  `lastname` string, 
  `leadsource` string, 
  `mailingcity` string, 
  `mailingcountry` string, 
  `mailingpostalcode` string, 
  `mailingstate` string, 
  `mailingstreet` string, 
  `mainagnecycountrycode__c` string, 
  `mainagnecyphonenumber__c` string, 
  `marital_status__c` string, 
  `masterrecordid` string, 
  `mobilephone` string, 
  `name` string, 
  `othercity` string, 
  `othercountry` string, 
  `otherphone` string, 
  `otherpostalcode` string, 
  `otherstate` string, 
  `otherstreet` string, 
  `ownerid` string, 
  `passport_exp_date__c` timestamp, 
  `passport_number__c` string, 
  `phone` string, 
  `preferred_contact_country_code__c` string, 
  `preferred_contact_method__c` string, 
  `preferred_contact_phone_number__c` string, 
  `preferred_language__c` string, 
  `recordtypeid` string, 
  `reporting_manager__c` boolean, 
  `reportstoid` string, 
  `rh2__currency_test__c` double, 
  `rh2__describe__c` string, 
  `rh2__formula_test__c` double, 
  `rh2__integer_test__c` double, 
  `role__c` string, 
  `fmdc_approver__c` string, 
  `seacity_access_key__c` string, 
  `sales_commission_amount__c` double, 
  `sales_commission__c` double, 
  `salutation` string, 
  `seaware_agency_id__c` string, 
  `seaware_agent_id__c` string, 
  `secondary_agency_country_code__c` string, 
  `secondary_agency_phone_number__c` string, 
  `status__c` boolean, 
  `suffix__c` string, 
  `systemmodstamp` timestamp, 
  `target_revenue__c` double, 
  `title` string, 
  `total_revenue__c` double, 
  `t_c_accept__c` boolean, 
  `t_c_consent_date__c` timestamp, 
  `t_c_consent_first_name__c` string, 
  `t_c_consent_last_name__c` string, 
  `user_update__c` string, 
  `vv_vq__c` double, 
  `seaware_agencyid__c` string, 
  `bulk_agency_phone_number__c` string, 
  `marketing_flag__c` boolean, 
  `vq_date_c` timestamp, 
  `contactrecordtype` string, 
  `job_id` string, 
  `load_data_timestamp` timestamp, 
  `epoc` bigint, 
  `year` int, 
  `month` int, 
  `day` int)
ROW FORMAT SERDE 
  'org.apache.hadoop.hive.ql.io.parquet.serde.ParquetHiveSerDe' 
STORED AS INPUTFORMAT 
  'org.apache.hadoop.hive.ql.io.parquet.MapredParquetInputFormat' 
OUTPUTFORMAT 
  'org.apache.hadoop.hive.ql.io.parquet.MapredParquetOutputFormat'
LOCATION
  's3://vv-prod-emr-cluster/data/core/crm/hvtb_nbx_core_crm_contact'
TBLPROPERTIES (
  'spark.sql.create.version'='2.2 or prior', 
  'spark.sql.sources.schema.numParts'='2', 
  'spark.sql.sources.schema.part.0'='{"type":"struct","fields":[{"name":"accountid","type":"string","nullable":true,"metadata":{}},{"name":"agencyname__c","type":"string","nullable":true,"metadata":{}},{"name":"agency_environment__c","type":"string","nullable":true,"metadata":{}},{"name":"agent_status__c","type":"string","nullable":true,"metadata":{}},{"name":"agent_type_c","type":"string","nullable":true,"metadata":{}},{"name":"anniversary_date__c","type":"timestamp","nullable":true,"metadata":{}},{"name":"assistantname","type":"string","nullable":true,"metadata":{}},{"name":"assistantphone","type":"string","nullable":true,"metadata":{}},{"name":"birthdate","type":"timestamp","nullable":true,"metadata":{}},{"name":"createdbyid","type":"string","nullable":true,"metadata":{}},{"name":"createddate","type":"timestamp","nullable":true,"metadata":{}},{"name":"department","type":"string","nullable":true,"metadata":{}},{"name":"description","type":"string","nullable":true,"metadata":{}},{"name":"donotcall","type":"boolean","nullable":true,"metadata":{}},{"name":"email","type":"string","nullable":true,"metadata":{}},{"name":"emailbounceddate","type":"timestamp","nullable":true,"metadata":{}},{"name":"emailbouncedreason","type":"string","nullable":true,"metadata":{}},{"name":"et4ae5__hasoptedoutofmobile__c","type":"boolean","nullable":true,"metadata":{}},{"name":"et4ae5__mobile_country_code__c","type":"string","nullable":true,"metadata":{}},{"name":"fax","type":"string","nullable":true,"metadata":{}},{"name":"firstname","type":"string","nullable":true,"metadata":{}},{"name":"gender__c","type":"string","nullable":true,"metadata":{}},{"name":"hasoptedoutofemail","type":"boolean","nullable":true,"metadata":{}},{"name":"hasoptedoutoffax","type":"boolean","nullable":true,"metadata":{}},{"name":"homephone","type":"string","nullable":true,"metadata":{}},{"name":"iatanexpdate__c","type":"timestamp","nullable":true,"metadata":{}},{"name":"iatan_company_name__c","type":"string","nullable":true,"metadata":{}},{"name":"iatan_holder_name__c","type":"string","nullable":true,"metadata":{}},{"name":"iatan_number__c","type":"double","nullable":true,"metadata":{}},{"name":"id","type":"string","nullable":true,"metadata":{}},{"name":"isdeleted","type":"boolean","nullable":true,"metadata":{}},{"name":"ispersonaccount","type":"boolean","nullable":true,"metadata":{}},{"name":"is_approved__c","type":"boolean","nullable":true,"metadata":{}},{"name":"is_primary_contact__c","type":"boolean","nullable":true,"metadata":{}},{"name":"lastactivitydate","type":"timestamp","nullable":true,"metadata":{}},{"name":"lastcurequestdate","type":"timestamp","nullable":true,"metadata":{}},{"name":"lastcuupdatedate","type":"timestamp","nullable":true,"metadata":{}},{"name":"lastmodifiedbyid","type":"string","nullable":true,"metadata":{}},{"name":"lastmodifieddate","type":"timestamp","nullable":true,"metadata":{}},{"name":"lastname","type":"string","nullable":true,"metadata":{}},{"name":"leadsource","type":"string","nullable":true,"metadata":{}},{"name":"mailingcity","type":"string","nullable":true,"metadata":{}},{"name":"mailingcountry","type":"string","nullable":true,"metadata":{}},{"name":"mailingpostalcode","type":"string","nullable":true,"metadata":{}},{"name":"mailingstate","type":"string","nullable":true,"metadata":{}},{"name":"mailingstreet","type":"string","nullable":true,"metadata":{}},{"name":"mainagnecycountrycode__c","type":"string","nullable":true,"metadata":{}},{"name":"mainagnecyphonenumber__c","type":"string","nullable":true,"metadata":{}},{"name":"marital_status__c","type":"string","nullable":true,"metadata":{}},{"name":"masterrecordid","type":"string","nullable":true,"metadata":{}},{"name":"mobilephone","type":"string","nullable":true,"metadata":{}},{"name":"name","type":"string","nullable":true,"metadata":{}},{"name":"othercity","type":"string","nullable":true,"metadata":{}},{"name":"othercountry","type":"string","nullable":true,"metadata":{}},{"name":"otherphone","type":"string","nullable":true,', 
  'spark.sql.sources.schema.part.1'='"metadata":{}},{"name":"otherpostalcode","type":"string","nullable":true,"metadata":{}},{"name":"otherstate","type":"string","nullable":true,"metadata":{}},{"name":"otherstreet","type":"string","nullable":true,"metadata":{}},{"name":"ownerid","type":"string","nullable":true,"metadata":{}},{"name":"passport_exp_date__c","type":"timestamp","nullable":true,"metadata":{}},{"name":"passport_number__c","type":"string","nullable":true,"metadata":{}},{"name":"phone","type":"string","nullable":true,"metadata":{}},{"name":"preferred_contact_country_code__c","type":"string","nullable":true,"metadata":{}},{"name":"preferred_contact_method__c","type":"string","nullable":true,"metadata":{}},{"name":"preferred_contact_phone_number__c","type":"string","nullable":true,"metadata":{}},{"name":"preferred_language__c","type":"string","nullable":true,"metadata":{}},{"name":"recordtypeid","type":"string","nullable":true,"metadata":{}},{"name":"reporting_manager__c","type":"boolean","nullable":true,"metadata":{}},{"name":"reportstoid","type":"string","nullable":true,"metadata":{}},{"name":"rh2__currency_test__c","type":"double","nullable":true,"metadata":{}},{"name":"rh2__describe__c","type":"string","nullable":true,"metadata":{}},{"name":"rh2__formula_test__c","type":"double","nullable":true,"metadata":{}},{"name":"rh2__integer_test__c","type":"double","nullable":true,"metadata":{}},{"name":"role__c","type":"string","nullable":true,"metadata":{}},{"name":"fmdc_approver__c","type":"string","nullable":true,"metadata":{}},{"name":"seacity_access_key__c","type":"string","nullable":true,"metadata":{}},{"name":"sales_commission_amount__c","type":"double","nullable":true,"metadata":{}},{"name":"sales_commission__c","type":"double","nullable":true,"metadata":{}},{"name":"salutation","type":"string","nullable":true,"metadata":{}},{"name":"seaware_agency_id__c","type":"string","nullable":true,"metadata":{}},{"name":"seaware_agent_id__c","type":"string","nullable":true,"metadata":{}},{"name":"secondary_agency_country_code__c","type":"string","nullable":true,"metadata":{}},{"name":"secondary_agency_phone_number__c","type":"string","nullable":true,"metadata":{}},{"name":"status__c","type":"boolean","nullable":true,"metadata":{}},{"name":"suffix__c","type":"string","nullable":true,"metadata":{}},{"name":"systemmodstamp","type":"timestamp","nullable":true,"metadata":{}},{"name":"target_revenue__c","type":"double","nullable":true,"metadata":{}},{"name":"title","type":"string","nullable":true,"metadata":{}},{"name":"total_revenue__c","type":"double","nullable":true,"metadata":{}},{"name":"t_c_accept__c","type":"boolean","nullable":true,"metadata":{}},{"name":"t_c_consent_date__c","type":"timestamp","nullable":true,"metadata":{}},{"name":"t_c_consent_first_name__c","type":"string","nullable":true,"metadata":{}},{"name":"t_c_consent_last_name__c","type":"string","nullable":true,"metadata":{}},{"name":"user_update__c","type":"string","nullable":true,"metadata":{}},{"name":"vv_vq__c","type":"double","nullable":true,"metadata":{}},{"name":"seaware_agencyid__c","type":"string","nullable":true,"metadata":{}},{"name":"bulk_agency_phone_number__c","type":"string","nullable":true,"metadata":{}},{"name":"marketing_flag__c","type":"boolean","nullable":true,"metadata":{}},{"name":"vq_date_c","type":"timestamp","nullable":true,"metadata":{}},{"name":"contactrecordtype","type":"string","nullable":true,"metadata":{}},{"name":"job_id","type":"string","nullable":true,"metadata":{}},{"name":"load_data_timestamp","type":"timestamp","nullable":true,"metadata":{}},{"name":"epoc","type":"long","nullable":true,"metadata":{}},{"name":"year","type":"integer","nullable":true,"metadata":{}},{"name":"month","type":"integer","nullable":true,"metadata":{}},{"name":"day","type":"integer","nullable":true,"metadata":{}}]}', 
  'transient_lastDdlTime'='1566914703');
