INSERT INTO IDS_{{params.target_env}}."INT_REF"."TRANSFORMATION_CONFIGURATION"(
DOMAIN_NAME,
BRAND_ID,
TRANSFORMATION_NAME,
CONFIGURATION_NAME,
CONFIGURATION_KEY_LABEL,
CONFIGURATION_VALUE,
CONFIGRATION_OPERATOR_TYPE,
CONFIGURATION_START_DATE,
OPERATON_RETURN_VALUE,
OPERATOR_RETURN_TYPE,
CONFIGURATION_END_DATE,
SOURCE_SYSTEM_NAME,
LOAD_ID,
LOAD_DTTM,
UPDATE_ID,
UPDATE_DTTM
)VALUES 
('FINANCE','arbys','E2E_SALES_RECON_POS_ADLS_TO_RDS','Other Sales','Revenue_Center','640221130','EQUAL',NULL,'','',NULL,'',
TO_NUMBER(TO_CHAR(CURRENT_DATE, 'YYYYMMDD')) ,
TO_TIMESTAMP_NTZ(CURRENT_TIMESTAMP)          ,
TO_NUMBER(TO_CHAR(CURRENT_DATE, 'YYYYMMDD')) ,
TO_TIMESTAMP_NTZ(CURRENT_TIMESTAMP)          ),
('FINANCE','arbys','E2E_SALES_RECON_POS_ADLS_TO_RDS','Other Sales','Revenue_Center','640221131','EQUAL',NULL,'','',NULL,'',
TO_NUMBER(TO_CHAR(CURRENT_DATE, 'YYYYMMDD')) ,
TO_TIMESTAMP_NTZ(CURRENT_TIMESTAMP)          ,
TO_NUMBER(TO_CHAR(CURRENT_DATE, 'YYYYMMDD')) ,
TO_TIMESTAMP_NTZ(CURRENT_TIMESTAMP)          );

