create view IF NOT EXISTS MEDIA_ACTIVITY_WEEK(
	CHANNEL,
	SUBCHANNEL,
	SUBCHANNEL2,
	PARTNER_NAME,
	WEEK_START_DATE,
	DMA_CODE,
	DMA_NAME,
	IMPRESSIONS_CNT,
	RATINGS_VAL,
	CLICKS_CNT,
	GRP,
	TARGET_RATING_POINT,
	BRAND_ID,
	SOURCE_SYSTEM_NAME,
	LAST_UPDATE_DTTM
) as
SELECT  ch.CHANNEL_NM AS Channel,
        ch.CHANNEL_CATEGORY_NM AS SubChannel,
        ch.CHANNEL_SUBCATEGORY_NM AS SubChannel2,
        ch.PARTNER_NM AS PARTNER_NAME,
        fct.WEEK_START_DT AS WEEK_START_DATE,
        fct.DMA_CD AS DMA_CODE,
        dma.DMAName AS DMA_NAME,
        fct.IMPRESSIONS_CNT AS IMPRESSIONS_CNT,
        fct.RATINGS_CNT AS RATINGS_VAL,
        fct.CLICKS_CNT AS CLICKS_CNT,
        fct.GRP_CNT AS GRP,
        fct.TRP_CNT AS TARGET_RATING_POINT,
        fct.BRAND_ID AS Brand_Id,
        fct.SOURCE_SYSTEM_NM AS SOURCE_SYSTEM_NAME,
        fct.LAST_UPDATED_DTTM AS LAST_UPDATE_DTTM
FROM IDM_DEV.MEDIA_BV.CHANNEL_HIERARCHY_BV ch
 INNER JOIN IDM_DEV.MEDIA_BV.MEDIA_ACTIVITY_FACT_BV fct
   ON ch.CHANNEL_HIERARCHY_KEY=fct.CHANNEL_HIERARCHY_KEY
 INNER JOIN IDS_DEV.LOCN_BV.LOC_DMA_PLR_BV dma
   ON dma.DMACODE=fct.DMA_CD;
create view IF NOT EXISTS MEDIA_ACTIVITY_WEEK_DS(
	CHANNEL,
	SUBCHANNEL,
	SUBCHANNEL2,
	PARTNER_NAME,
	WEEK_START_DATE,
	DMA_CODE,
	DMA_NAME,
	IMPRESSIONS_CNT,
	RATINGS_VAL,
	CLICKS_CNT,
	GRP,
	TARGET_RATING_POINT,
	BRAND_ID,
	SOURCE_SYSTEM_NAME,
	LAST_UPDATE_DTTM
) as
SELECT  ch.CHANNEL_NM AS Channel,
        ch.CHANNEL_CATEGORY_NM AS SubChannel,
        ch.CHANNEL_SUBCATEGORY_NM AS SubChannel2,
        ch.PARTNER_NM AS PARTNER_NAME,
        fct.WEEK_START_DT AS WEEK_START_DATE,
        fct.DMA_CD AS DMA_CODE,
        dma.DMAName AS DMA_NAME,
        fct.IMPRESSIONS_CNT AS IMPRESSIONS_CNT,
        fct.RATINGS_CNT AS RATINGS_VAL,
        fct.CLICKS_CNT AS CLICKS_CNT,
        fct.GRP_CNT AS GRP,
        fct.TRP_CNT AS TARGET_RATING_POINT,
        fct.BRAND_ID AS Brand_Id,
        fct.SOURCE_SYSTEM_NM AS SOURCE_SYSTEM_NAME,
        fct.LAST_UPDATED_DTTM AS LAST_UPDATE_DTTM
FROM IDS_DEV.DATASTORE.CHANNEL_HIERARCHY ch
 INNER JOIN IDS_DEV.DATASTORE.MEDIA_ACTIVITY_FACT fct
   ON ch.CHANNEL_HIERARCHY_KEY=fct.CHANNEL_HIERARCHY_KEY
 INNER JOIN IDS_DEV.LOCN_BV.LOC_DMA_PLR_BV dma
   ON dma.DMACODE=fct.DMA_CD;
create view IF NOT EXISTS MEDIA_SPEND_WEEK(
	CHANNEL,
	SUBCHANNEL,
	SUBCHANNEL2,
	PARTNER_NAME,
	WEEK_START_DATE,
	DMA_CODE,
	DMA_NAME,
	SPEND_TYPE_NAME,
	SPEND_AMT,
	CURRENCY_CODE,
	BRAND_ID,
	SOURCE_SYSTEM_NAME,
	LAST_UPDATE_DTTM
) as
SELECT  ch.CHANNEL_NM AS Channel,
        ch.CHANNEL_CATEGORY_NM AS SubChannel,
        ch.CHANNEL_SUBCATEGORY_NM AS SubChannel2,
        ch.PARTNER_NM AS PARTNER_NAME,
        fct.WEEK_START_DT AS Week_Start_Date,
        fct.DMA_CD AS DMA_CODE,
        dma.DMAName AS DMA_Name,
        spt.SPEND_TYP_NM AS SPEND_TYPE_NAME,
        fct.SPEND_AMT AS SPEND_AMT,
        fct.CURRENCY_CD AS Currency_Code,
        fct.BRAND_ID AS BRAND_ID,
        fct.SOURCE_SYSTEM_NM AS SOURCE_SYSTEM_NAME,
        fct.LAST_UPDATED_DTTM AS LAST_UPDATE_DTTM
FROM IDM_DEV.MEDIA_BV.CHANNEL_HIERARCHY_BV ch
 INNER JOIN IDM_DEV.MEDIA_BV.MEDIA_ACTIVITY_FACT_BV fct
   ON ch.CHANNEL_HIERARCHY_KEY=fct.CHANNEL_HIERARCHY_KEY
 INNER JOIN IDS_DEV.LOCN_BV.LOC_DMA_PLR_BV dma
   ON dma.DMACODE=fct.DMA_CD
 INNER JOIN IDM_DEV.MEDIA_BV.SPEND_TYPE_BV spt
   ON spt.SPEND_TYPE_KEY=fct.SPEND_TYPE_KEY;
create view IF NOT EXISTS MEDIA_SPEND_WEEK_DS(
	CHANNEL,
	SUBCHANNEL,
	SUBCHANNEL2,
	PARTNER_NAME,
	WEEK_START_DATE,
	DMA_CODE,
	DMA_NAME,
	SPEND_TYPE_NAME,
	SPEND_AMT,
	CURRENCY_CODE,
	BRAND_ID,
	SOURCE_SYSTEM_NAME,
	LAST_UPDATE_DTTM
) as
SELECT  ch.CHANNEL_NM AS Channel,
        ch.CHANNEL_CATEGORY_NM AS SubChannel,
        ch.CHANNEL_SUBCATEGORY_NM AS SubChannel2,
        ch.PARTNER_NM AS PARTNER_NAME,
        fct.WEEK_START_DT AS Week_Start_Date,
        fct.DMA_CD AS DMA_CODE,
        dma.DMAName AS DMA_Name,
        spt.SPEND_TYP_NM AS SPEND_TYPE_NAME,
        fct.SPEND_AMT AS SPEND_AMT,
        fct.CURRENCY_CD AS Currency_Code,
        fct.BRAND_ID AS BRAND_ID,
        fct.SOURCE_SYSTEM_NM AS SOURCE_SYSTEM_NAME,
        fct.LAST_UPDATED_DTTM AS LAST_UPDATE_DTTM
FROM IDS_DEV.DATASTORE.CHANNEL_HIERARCHY ch
 INNER JOIN IDS_DEV.DATASTORE.MEDIA_ACTIVITY_FACT fct
   ON ch.CHANNEL_HIERARCHY_KEY=fct.CHANNEL_HIERARCHY_KEY
 INNER JOIN IDS_DEV.LOCN_BV.LOC_DMA_PLR_BV dma
   ON dma.DMACODE=fct.DMA_CD
 INNER JOIN IDS_DEV.DATASTORE.SPEND_TYPE spt
   ON spt.SPEND_TYPE_KEY=fct.SPEND_TYPE_KEY;