create TABLE IF NOT EXISTS FLYWAY_SCHEMA_HISTORY (
	INSTALLED_RANK NUMBER(38,0) NOT NULL,
	VERSION VARCHAR(50),
	DESCRIPTION VARCHAR(200),
	TYPE VARCHAR(20) NOT NULL,
	SCRIPT VARCHAR(1000) NOT NULL,
	CHECKSUM NUMBER(38,0),
	INSTALLED_BY VARCHAR(100) NOT NULL,
	INSTALLED_ON TIMESTAMP_LTZ(9) NOT NULL DEFAULT CURRENT_TIMESTAMP(),
	EXECUTION_TIME NUMBER(38,0) NOT NULL,
	SUCCESS BOOLEAN NOT NULL,
	primary key (INSTALLED_RANK)
);
create view IF NOT EXISTS MENU(
	MDM_ITEM_ID,
	SOURCE_SYSTEM_ID,
	ITEM_NAME,
	MDM_ITEM_TYPE,
	MDM_PRODUCT_ID,
	PRODUCT_NAME,
	PRODUCT_DESC,
	PRODUCT_STATUS,
	TECHNICAL_SIZE,
	UNIT_OF_MEASURE,
	NON_USA_SPECIALTY,
	VEHICLE,
	IS_HOT_PRODUCT_IND,
	IS_BREAKFAST_PRODUCT_IND,
	PRODUCT_BRAND,
	MENU_TYPE,
	MENU_SECTION,
	GBB_MEASURE,
	IS_COLD_SPACE_REQUIRED_IND,
	IS_FRYER_REQUIRED_IND,
	PRODUCT_HIERARCHY_NODE,
	L1_PRODUCT_HIERARCHY,
	L2_PRODUCT_HIERARCHY,
	L3_PRODUCT_HIERARCHY,
	L4_PRODUCT_HIERARCHY,
	L5_PRODUCT_HIERARCHY,
	MDM_OFFER_ID,
	OFFER_NAME,
	OFFER_DESC,
	OFFER_CATEGORY,
	OFFER_TYPE,
	L1_OFFER_HIERARCHY,
	L2_OFFER_HIERARCHY,
	L3_OFFER_HIERARCHY,
	L4_OFFER_HIERARCHY,
	L5_OFFER_HIERARCHY,
	BRAND_ID,
	SOURCE,
	LOAD_ID,
	LAST_UPDATE_DTTM,
	UPDATE_ID,
	UPDATE_DTTM
) as 
SELECT c.MDM_ITEM_ID AS MDM_ITEM_ID
, c.SOURCE_SYSTEM_ID AS SOURCE_SYSTEM_ID
, c.ITEM_NM AS ITEM_NAME
, c.MDM_ITEM_TYP AS MDM_ITEM_TYPE
, c.MDM_PRODUCT_ID AS MDM_PRODUCT_ID
, c.PRODUCT_NM AS PRODUCT_NAME
, c.PRODUCT_DESC AS PRODUCT_DESC
, c.PRODUCT_STATUS_CD AS PRODUCT_STATUS
, c.TECHNICAL_SIZE_TXT AS TECHNICAL_SIZE
, c.UNIT_OF_MEASURE_CD AS UNIT_OF_MEASURE
, c.NON_USA_SPECIALTY_IND AS NON_USA_SPECIALTY
, c.VEHICLE_ID AS VEHICLE
, c.HOT_PRODUCT_IND AS IS_HOT_PRODUCT_IND
, c.BREAKFAST_PRODUCT_IND AS IS_BREAKFAST_PRODUCT_IND
, c.PRODUCT_BRAND_NBR AS PRODUCT_BRAND
, c.MENU_TYP AS MENU_TYPE
, c.MENU_SECTION_NBR AS MENU_SECTION
, c.GBB_MEASURE_NM AS GBB_MEASURE
, c.COLD_SPACE_REQUIRED_IND AS IS_COLD_SPACE_REQUIRED_IND
, c.FRYER_REQUIRED_IND AS IS_FRYER_REQUIRED_IND 
, c.PRODUCT_HIERARCHY_NODE_ID AS PRODUCT_HIERARCHY_NODE
, c.LEVEL1_PRODUCT_HIERARCHY_DESC AS L1_PRODUCT_HIERARCHY
, c.LEVEL2_PRODUCT_HIERARCHY_DESC AS L2_PRODUCT_HIERARCHY
, c.LEVEL3_PRODUCT_HIERARCHY_DESC AS L3_PRODUCT_HIERARCHY
, c.LEVEL4_PRODUCT_HIERARCHY_DESC AS L4_PRODUCT_HIERARCHY
, c.LEVEL5_PRODUCT_HIERARCHY_DESC AS L5_PRODUCT_HIERARCHY
, c.MDM_OFFER_ID AS MDM_OFFER_ID
, c.OFFER_NM AS OFFER_NAME
, c.OFFER_DESC AS OFFER_DESC
, c.OFFER_CATEGORY_CD AS OFFER_CATEGORY
, c.OFFER_TYP AS OFFER_TYPE
, c.LEVEL1_OFFER_HIERARCHY_DESC AS L1_OFFER_HIERARCHY
, c.LEVEL2_OFFER_HIERARCHY_DESC AS L2_OFFER_HIERARCHY
, c.LEVEL3_OFFER_HIERARCHY_DESC AS L3_OFFER_HIERARCHY
, c.LEVEL4_OFFER_HIERARCHY_DESC AS L4_OFFER_HIERARCHY
, c.LEVEL5_OFFER_HIERARCHY_DESC AS L5_OFFER_HIERARCHY
, c.BRAND_ID AS BRAND_ID
, c.SOURCE_SYSTEM_NM AS SOURCE
, c.LOAD_ID AS LOAD_ID
, c.LOAD_DTTM AS LAST_UPDATE_DTTM
, c.UPDATE_ID AS UPDATE_ID
, c.UPDATE_DTTM AS UPDATE_DTTM
FROM IDM_DEV.COREDIM_BV.MENU_DIM_BV c;