spark.landing.table vv_db.hvtb_lnd_pricing_detail
spark.custapi.url https://dev-swbiz.gcpshore.virginvoyages.com/SwBizLogic/Service.svc/ProcessRequest 
spark.maxdate.query Select sail_date_to  from vv_db.hvtb_nbx_core_sw_sail_dim sail inner join vv_db.hvtb_nbx_core_sw_ship_dim shipd on ( shipd.ship !='VC' and shipd.ship !='XE' and sail.ship_id == shipd.ship_id)
spark.maxcutoff.months 24
spark.numadults.list 1,2,3,4
spark.currency.list CAD,GBP,USD,AUD,NZD
spark.target.table vv_db.hvtb_nbx_core_pricing_detail
spark.target.temp gs://vv-dev-nbx-cluster/data/temp/hvtb_nbx_core_pricing_detail
spark.target.final gs://vv-dev-nbx-cluster/data/mart/hvtb_nbx_core_pricing_detail
spark.noofDays 7
spark.noofRecords 200
spark.hadoop.hive.execution.engine mr