USE WAREHOUSE {{ params.warehouse }};

COPY INTO RDS_{{params.env}}.{{params.schema}}.BOS_CRUNCHTIME_SALES
FROM 	
(
SELECT
$1:: STRING AS   StoreID,
$2:: STRING AS   Category,
$3:: STRING AS   Amount,
$4:: STRING AS   SalesDate,
to_timestamp_ntz(current_timestamp)::STRING AS LOADDATETIME,
to_number(to_char(current_date, 'YYYYMMDD'))::STRING AS LOADID,
LOWER('incremental') AS LOADTYPE,
LOWER('dunkin') || '/' || METADATA$FILENAME::STRING AS FILENAME,
CASE WHEN METADATA$FILENAME LIKE '%Prod/%' THEN TO_DATE(RIGHT(LEFT(TRIM(METADATA$FILENAME),51),8),'YYYYMMDD')
     WHEN METADATA$FILENAME LIKE '%QA/%' THEN TO_DATE(RIGHT(LEFT(TRIM(METADATA$FILENAME),51),8),'YYYYMMDD') 
     ELSE TO_DATE(RIGHT(LEFT(TRIM(METADATA$FILENAME),51),8),'YYYYMMDD')  END AS FILEDATE,
CASE WHEN METADATA$FILENAME LIKE '%Prod/%' THEN TO_DATE(RIGHT(LEFT(METADATA$FILENAME,51), 8),'YYYYMMDD')
     WHEN METADATA$FILENAME LIKE '%QA/%' THEN TO_DATE(RIGHT(LEFT(METADATA$FILENAME,51), 8),'YYYYMMDD')
     ELSE TO_DATE(RIGHT(LEFT(METADATA$FILENAME,51), 8),'YYYYMMDD') END AS FOLDERDATE
FROM @RDS_{{params.env}}.{{params.schema}}.SALES_RECON_READ_ADLS2/BOS/
(file_format => '{{params.file_format}}', pattern => '{{params.pattern}}')
);