jobname;"com.virginvoyages.sparkstreaming.KafkaSeawareReservation","com.virginvoyages.sparkstreaming.KafkaClientMerge","FeedbackLoop","com.virginvoyages.sparkstreaming.KafkaCalendarFeedbackConsumer","com.virginvoyages.sparkstreaming.KafkaPersonCreatedProducerConsumer","com.virginvoyages.sparkstreaming.UpdateMasterId"
resource_manager_url;
reservationemailnotifyfile;.com.virginvoyages.sparkstreaming.KafkaSeawareReservation
clientmerge;.com.virginvoyages.sparkstreaming.KafkaClientMerge
to;vv-app-alert-non-prod@virginvoyages.com,naresh.aalthi@capgemini.com,charchit.patidar@capgemini.com,umesh.sawant@capgemini.com,amit.db.kumar@capgemini.com,nitesh.f.kumar@capgemini.com
from;talendadmin-non-prod@virginvoyages.com


