USE WAREHOUSE {{params.warehouse}};

SET load_dt =  '{{params.load_dt}}';

COPY INTO @IDH_{{params.env}}.{{params.schema}}.stage_for_sonic_polled_sales/{{params.file_name}} 
from 
(
SELECT 
'SDI' AS BRAND, 
TO_CHAR(LAST_DAY(BUSINESS_DATE),'MM-DD-YYYY') AS REPORTING_PERIOD,
OWNER_ID AS CUSTOMER_NUMBER, 
FRANCHISEE_NAME AS CUSTOMER_NAME,
LPAD(T.REST_ID,6,'0') AS UNIT,
'USD' LOCAL_CURRENCY,
SUM(DERIVED_NET_AMT) LOCAL_NET_SALES_RETAIL,
SUM(TRANS_CNT) TRANSACTION_COUNT_RETAIL,
SUM(DERIVED_GROSS_AMT) LOCAL_GROSS_SALES,
'' AS LOCAL_NET_SALES_WHOLESALE, 
'' AS TRANSACTION_COUNT_WHOLESALE,
'MONTHLY' AS REPORTING_FREQUENCY
FROM IDH_{{params.env}}.{{params.schema}}.TRANS T
INNER JOIN IDH_{{params.env}}.D_LOC.REST R 
ON T.REST_ID = R.REST_ID AND T.BRAND_ID = R.BRAND_ID
WHERE T.BRAND_ID = 'sonic' 
AND R.OWNERSHIP_TYPE = 'Franchised' 
AND VOID_IND = 'FALSE'
AND
BUSINESS_DATE BETWEEN 
TO_DATE(DATE_TRUNC('MONTH',ADD_MONTHS($load_dt,-1))) AND LAST_DAY(ADD_MONTHS($load_dt,-1))
AND DAY(TO_DATE($load_dt)) < 21
GROUP BY 
T.BRAND_ID,
LAST_DAY(BUSINESS_DATE),
OWNER_ID, 
FRANCHISEE_NAME,
T.REST_ID
)
OVERWRITE = TRUE 
single = true
FILE_FORMAT = (FIELD_DELIMITER = '|' TYPE = csv NULL_IF = ('NULL', 'null') EMPTY_FIELD_AS_NULL = false  compression='NONE')
HEADER=true;