ALTER SESSION SET QUOTED_IDENTIFIERS_IGNORE_CASE = FALSE;

/* <sc-table> PROMO </sc-table> */

CREATE TABLE IF NOT EXISTS "PROMO" ("ADI" INTEGER, "FRANID" CHAR(6), "YEAR" INTEGER, "MONTH" INTEGER, "WEEK" INTEGER, "FLIGHT_YEAR" INTEGER, "FLIGHT_MONTH" INTEGER, "PROMO_ID1" INTEGER, "PROMO_ID2" INTEGER, "ONE_PRICE" DOUBLE, "ONE_TV" INTEGER, "ONE_TVP" INTEGER, "ONE_TVS" INTEGER, "ONE_TVS_DM" INTEGER, "SPOT_CABLE" INTEGER, "SPOT_CABLEP" INTEGER, "SPOT_CABLES" INTEGER, "SPOT_CABLES_DM" INTEGER, "OTHERTVP" INTEGER, "OTHERTVS" INTEGER, "ONE_CABLE_TV" INTEGER, "EQUALIZED_TRPS" INTEGER, "EQUALIZEDP" INTEGER, "EQUALIZEDS" INTEGER, "SPOTPRIMARY15" DECIMAL(18,2), "CABLEPRIMARY15" DECIMAL(18,2), "SPORTSPRIMARY15" DECIMAL(18,2), "OTHERPRIMARY15" DECIMAL(18,2), "SPOTSECONDARY15" DECIMAL(18,2), "CABLESECONDARY15" DECIMAL(18,2), "SPORTSSECONDARY15" DECIMAL(18,2), "OTHERSECONDARY15" DECIMAL(18,2), "CONVERTRATE" DECIMAL(18,2), "TV_SPILL" INTEGER, "FLIGHT_ID" CHAR(30), "RADIO_ID1" INTEGER, "RADIO_ID2" INTEGER, "ONE_RADIO" INTEGER, "ONE_RADIOP" INTEGER, "ONE_RADIOS" INTEGER, "DJ_RADIO" INTEGER, "TRAFFIC_RADIO" INTEGER, "SPORTS_RADIO" INTEGER, "RADIO_SPILL" INTEGER, "NATL_ONLINE" INTEGER, "LOCAL_ONLINE" INTEGER, "ONE_INSERT" CHAR(2), "INSERTDATETY" CHAR(25), "TEST_FLIGHT" CHAR(1), "ONE_TV_ACTUAL" INTEGER, "POST_BUY_ALL_LOCAL" INTEGER, "RADIO_FOCUS" CHAR(75), "FOCUS" CHAR(75), "VEHICLE" CHAR(75), "PRINT_PARTICIPANTS" VARCHAR(75), "DISPLAY" INTEGER, "DGTL_AUDIO" INTEGER, "OUTDOOR" CHAR(75), "OUTDOORTRP" INTEGER, "EXTRAS_EMAIL" CHAR(75), "MOBILE_OFFER" CHAR(75), "CRAVE" CHAR(75), "LSM" CHAR(75), "LSM_P" INTEGER, "ONE_RADIO_COST" INTEGER, "SUB_MKT_RADIO_PTS" INTEGER, "SPORTS" INTEGER, "SPORTSP" INTEGER, "SPORTSS" INTEGER, "LOCAL_SEASON" CHAR(5), "BOOKEND_PCT" CHAR(5), "UPDATE_DATE" TIMESTAMP, "EQUALIZEDN" INTEGER);



/* <sc-table> STORE_PURE_MIX_BLENDED_V </sc-table> */

CREATE TABLE IF NOT EXISTS "STORE_PURE_MIX_BLENDED_V" ("STORE_NBR" INTEGER, "DMA_NBR" INTEGER, "FRANID" CHAR(6), "YEAR" INTEGER, "MONTH" INTEGER, "WEEK" INTEGER, "DAYPART" CHAR(3), "PRODUCT_ID" INTEGER, "PRICE" DECIMAL(18,2), "NBR_SOLD" INTEGER, "SALES" DECIMAL(18,2), "WEEK_NBR" CHAR(12), "VALID" CHAR(1), "INPUT_TIME" TIMESTAMP);



/* <sc-table> SALES_STORE </sc-table> */

CREATE TABLE IF NOT EXISTS "SALES_STORE" ("STORE_NBR" INTEGER, "ADI" INTEGER, "FRANID" CHAR(6), "WEEK_NBR" CHAR(12), "WEEK" INTEGER, "MONTH" INTEGER, "YEAR" INTEGER, "TOTSALESTY" INTEGER, "TOTSALESLY" INTEGER, "TOTTRANSTY" INTEGER, "TOTTRANSLY" INTEGER, "COMPTY" INTEGER, "COMPLY" INTEGER, "CTRANSTY" INTEGER, "CTRANSLY" INTEGER, "TOTUNITSTY" SMALLINT, "TOTUNITSLY" SMALLINT, "COMPUNITTY" SMALLINT, "COMPUNITLY" SMALLINT, "COMPTY_13" INTEGER, "COMPLY_13" INTEGER, "CNT_COMPTY_13_TY" TINYINT, "COMPTY_52" INTEGER, "COMPLY_52" INTEGER, "CNT_COMPTY_52_TY" TINYINT, "CTRANSTY_13" INTEGER, "CTRANSLY_13" INTEGER, "CNT_CTRANSTY_13_TY" INTEGER, "CTRANSTY_52" INTEGER, "CTRANSLY_52" INTEGER, "CNT_CTRANSTY_52_TY" INTEGER, "TIMESTAMP" TIMESTAMP);



/* <sc-table> STORE_MENU_BLENDED_V_YTD </sc-table> */

CREATE TABLE IF NOT EXISTS "STORE_MENU_BLENDED_V_YTD" ("STORE_NBR" INTEGER, "DMA_NBR" INTEGER, "FRANID" CHAR(6), "YEAR" INTEGER, "MONTH" INTEGER, "WEEK" INTEGER, "DAYPART" CHAR(3), "PRODUCT_ID" INTEGER, "PRICE" DECIMAL(34,17), "NBR_SOLD" INTEGER, "SALES" DECIMAL(18,2), "SOURCE_TYPE" VARCHAR(12));



/* <sc-table> SALES </sc-table> */

CREATE TABLE IF NOT EXISTS "SALES" ("ADI" INTEGER, "MONTH" INTEGER, "YEAR" INTEGER, "COMPTY" INTEGER, "COMPLY" INTEGER, "CTRANSTY" INTEGER, "CTRANSLY" INTEGER, "TOTSALESTY" INTEGER, "TOTUNITSTY" INTEGER, "COMPUNITTY" INTEGER, "FRANID" CHAR(6), "TOTSALESLY" INTEGER, "TOTTRANSTY" INTEGER, "TOTTRANSLY" INTEGER, "WEEK" INTEGER, "TOTUNITSLY" INTEGER, "COMPUNITLY" INTEGER, "DATES" CHAR(12), "PROMDOLLS" INTEGER, "PCMBODOLLS" INTEGER, "PCMBOS" INTEGER, "CAUV" DOUBLE, "COMPCHNGE" DOUBLE, "CTCHANGE" DOUBLE, "CAVECHKTY" DOUBLE, "CAVECHKLY" DOUBLE, "CACHK_PCT_CHNG" DOUBLE, "CACHK_$_CHNG" DOUBLE, "CAUV13" DOUBLE, "CAUV52" DOUBLE, "CAUTRANS13" DOUBLE, "CAUTRANS52" DOUBLE, "CAUCHK13" DOUBLE, "CAUCHK52" DOUBLE, "NUMPROSOLTY" INTEGER, "PROCBOPRICETY" DOUBLE, "PROMOITEMPRICETY" DOUBLE, "CAUTRANSTY" DOUBLE, "CAUCHKTY" DOUBLE, "COMPTY_13" INTEGER, "COMPLY_13" INTEGER, "COMP_TREND_13" DOUBLE, "COMPTY_52" INTEGER, "COMPLY_52" INTEGER, "COMP_TREND_52" DOUBLE, "CTRANSTY_13" INTEGER, "CTRANSLY_13" INTEGER, "TRANS_TREND_13" DOUBLE, "CTRANSTY_52" INTEGER, "CTRANSLY_52" INTEGER, "TRANS_TREND_52" DOUBLE, "CAVECHKTY_13" INTEGER, "CAVECHKLY_13" INTEGER, "CHECK_TREND_13" DOUBLE, "CAVECHKTY_52" INTEGER, "CAVECHKLY_52" INTEGER, "CHECK_TREND_52" DOUBLE);



/* <sc-table> LIST_FREP </sc-table> */

CREATE TABLE IF NOT EXISTS "LIST_FREP" ("FLDREP" INTEGER, "FLDREP_FNAME" CHAR(30), "FLDREP_LNAME" CHAR(30));



/* <sc-table> AFA_MKIS.STORE_MENU_BLENDED_V_ARC </sc-table> */

CREATE TABLE IF NOT EXISTS  "STORE_MENU_BLENDED_V_ARC" ("STORE_NBR" INTEGER, "DMA_NBR" INTEGER, "FRANID" CHAR(6), "YEAR" INTEGER, "MONTH" INTEGER, "WEEK" INTEGER, "DAYPART" CHAR(3), "PRODUCT_ID" INTEGER, "PRICE" DECIMAL(34,17), "NBR_SOLD" INTEGER, "SALES" DECIMAL(18,2), "SOURCE_TYPE" VARCHAR(12));



/* <sc-table> LIST_DMA </sc-table> */

CREATE TABLE IF NOT EXISTS "LIST_DMA" ("DMA_NBR" INTEGER, "DMA_DESC" CHAR(30), "FLDREP" INTEGER, "DMA_MEDIA_STATUS" VARCHAR(20), "RPT_DMA_NAME" CHAR(30), "DMA_MEDIA_TYPE" VARCHAR(50), "REGION" CHAR(50), "TRANS" CHAR(1), "TOP_80" CHAR(1), "RANKING" INTEGER, "MARKETING_MANAGER" INTEGER, "AGENCY" CHAR(30), "MEDIA_STATUS_YR" INTEGER, "FLOWCHART_RESPONSIBLE" CHAR(30));



/* <sc-table> LIST_PROM_PROD </sc-table> */

CREATE TABLE IF NOT EXISTS "LIST_PROM_PROD" ("PROMO_ID1" INTEGER, "PROMO_DES1" CHAR(60), "PROMO_ABR1" CHAR(30), "PRODUCT_ID" INTEGER, "KEY_PRODUCT" CHAR(1), "CURRENT_PROMO" CHAR(1), "PROMO_PRICE" DOUBLE, "SORT_ORDER" INTEGER, "PRICE_LEVEL" CHAR(50));



/* <sc-table> LIST_PROD_BREAKEVEN_TEST </sc-table> */

CREATE TABLE IF NOT EXISTS "LIST_PROD_BREAKEVEN_TEST" ("SUPER_GROUP" VARCHAR(255), "SUPER_GROUP_SORT_ORDER" DOUBLE, "CONSOLIDATE" VARCHAR(255), "MAIN_GROUP" VARCHAR(255), "MAIN_SORT_ORDER" DOUBLE, "SUBGROUP1" VARCHAR(255), "PRODUCT_ID" DOUBLE, "PRODUCT" VARCHAR(255), "PRODUCT_SORT_ORDER" DOUBLE, "FOOD_PAPER_DOLLARS" DOUBLE, "FOOD_PAPER_PCT" DOUBLE, "RPT_PRODUCT" VARCHAR(255), "NBR_UNITS" INTEGER, "MENU_STATUS" VARCHAR(255), "MENU_TYPE_ORDER" DOUBLE, "MENU_TYPE" VARCHAR(255), "MENU_GROUP_ORDER" DOUBLE, "MENU_GROUP" VARCHAR(255), "ORIGINAL_NAME" VARCHAR(255), "RPT_SORT_ORDER" DOUBLE, "KEY_PRODUCT" VARCHAR(255));



/* <sc-table> LIST_FRAN </sc-table> */

CREATE TABLE IF NOT EXISTS "LIST_FRAN" ("FRANID" CHAR(6), "FNAME" CHAR(50), "COMPANY" CHAR(50), "LNAME" CHAR(50), "MKT_PRIMARY" CHAR(1));



