spark.cabinfact.insert.overwrite.query  insert overwrite table vv_db.tmp_n_cab_res_cnt
spark.cabinfact.sourcequery SELECT src_sail_id, (s.ship_id) as ship_id, to_date(sail_date_from) as sail_date_from, to_date(sail_date_to) as sail_date_to ,(sh.ship) as ship,s.is_active as is_activ from vv_db.hvtb_nbx_core_sw_sail_dim s join vv_db.hvtb_nbx_core_sw_ship_dim sh on sh.ship_id = s.ship_id where to_date(s.rec_end_dttm) = '9999-12-31'
spark.cabinfact.seaware.xml.api.url https://prod.virginvoyages.com/seaware/SwBizLogic/Service.svc/ProcessRequest
spark.cabinfact.seaware.xml.api.username  NBX_API
spark.cabinfact.seaware.xml.api.password  PRDj39fh4
