dag_id: "JJ_BOS_ADLS_TO_RDS_ALL_HI_PL"
dag_description: "JJ Altametrics data load from ADLS2 to RDS"
'email': ['yatender.kumar@inspirebrands.com','udpfinanceengineeringpod@inspirebrands.com']
env : "DEV"
warehouse_id: "RA_PRCSSA_IRB_WH"
schema_id : "JJE"
file_format: "RDS_DEV.JJE.ALTAMETRICS_JJ_FILE_FORMAT"
pattern: ".*JJ_Daily_Sales.*[.]csv"
snowflake_rds_database_name: "RDS_DEV"
stage_name: "@RDS_DEV.JJE.SALES_RECON_JJ_CSV_ADLS2"