create TABLE IF NOT EXISTS FLYWAY_SCHEMA_HISTORY (
	INSTALLED_RANK NUMBER(38,0) NOT NULL,
	VERSION VARCHAR(50),
	DESCRIPTION VARCHAR(200),
	TYPE VARCHAR(20) NOT NULL,
	SCRIPT VARCHAR(1000) NOT NULL,
	CHECKSUM NUMBER(38,0),
	INSTALLED_BY VARCHAR(100) NOT NULL,
	INSTALLED_ON TIMESTAMP_LTZ(9) NOT NULL DEFAULT CURRENT_TIMESTAMP(),
	EXECUTION_TIME NUMBER(38,0) NOT NULL,
	SUCCESS BOOLEAN NOT NULL,
	primary key (INSTALLED_RANK)
);
create view IF NOT EXISTS MENU_ITEM_PLR_BV(
	MDMITEMID,
	ITEMNAME,
	ITEMPLU,
	SOURCESYSTEMID,
	MDMPRODUCTID,
	MDMOFFERID,
	MDMITEMTYPE,
	BRANDID,
	SOURCE,
	CDMLOADDATE,
	FILENAME
) as SELECT
                               MDMITEMID, ITEMNAME, ITEMPLU, SOURCESYSTEMID, MDMPRODUCTID, MDMOFFERID, MDMITEMTYPE, BRANDID, SOURCE, CDMLOADDATE, FILENAME
                            FROM IDS_DEV.MENU_BV."MENU_ITEM_PLR_BV";
create view IF NOT EXISTS MENU_OFFER_HIERARCHY_PLR_BV(
	OFFERHIERARCHYID,
	OFFERHIERARCHYNAME,
	OFFERHIERARCHYDESC,
	OFFERHIERARCHYTYPEID,
	PARENTOFFERHIERARCHY,
	BRANDID,
	SOURCE,
	CDMLOADDATE,
	FILENAME
) as SELECT
                               OFFERHIERARCHYID, OFFERHIERARCHYNAME, OFFERHIERARCHYDESC, OFFERHIERARCHYTYPEID, PARENTOFFERHIERARCHY, BRANDID, SOURCE, CDMLOADDATE, FILENAME
                            FROM IDS_DEV.MENU_BV."MENU_OFFER_HIERARCHY_PLR_BV";
create view IF NOT EXISTS MENU_OFFER_HIERARCHY_TYPE_PLR_BV(
	OFFERHIERARCHYTYPEID,
	OFFERHIERARCHYTYPENAME,
	OFFERHIERARCHYTYPEDESC,
	PARENTOFFERHIERARCHYTYPE,
	BRANDID,
	SOURCE,
	CDMLOADDATE,
	FILENAME
) as SELECT
                               OFFERHIERARCHYTYPEID, OFFERHIERARCHYTYPENAME, OFFERHIERARCHYTYPEDESC, PARENTOFFERHIERARCHYTYPE, BRANDID, SOURCE, CDMLOADDATE, FILENAME
                            FROM IDS_DEV.MENU_BV."MENU_OFFER_HIERARCHY_TYPE_PLR_BV";
create view IF NOT EXISTS MENU_OFFER_PLR_BV(
	MDMOFFERID,
	OFFERNAME,
	OFFERDESC,
	OFFERCATEGORY,
	OFFERTYPE,
	OFFERHIERARCHYID,
	MISC1,
	MISC2,
	MISC3,
	MISC4,
	MISC5,
	MISC6,
	MISC7,
	MISC8,
	MISC9,
	MISC10,
	BRANDID,
	SOURCE,
	CDMLOADDATE,
	FILENAME
) as SELECT
                               MDMOFFERID, OFFERNAME, OFFERDESC, OFFERCATEGORY, OFFERTYPE, OFFERHIERARCHYID, MISC1, MISC2, MISC3, MISC4, MISC5, MISC6, MISC7, MISC8, MISC9, MISC10, BRANDID, SOURCE, CDMLOADDATE, FILENAME
                            FROM IDS_DEV.MENU_BV."MENU_OFFER_PLR_BV";
create view IF NOT EXISTS MENU_PRODUCT_HIERARCHY_PLR_BV(
	PRODUCTHIERARCHYID,
	PRODUCTHIERARCHYNAME,
	PRODUCTHIERARCHYDESC,
	PRODUCTHIERARCHYTYPE,
	PARENTPRODUCTHIERARCHY,
	BRANDID,
	CDMLOADDATE,
	SOURCE,
	FILENAME
) as SELECT
                               PRODUCTHIERARCHYID, PRODUCTHIERARCHYNAME, PRODUCTHIERARCHYDESC, PRODUCTHIERARCHYTYPE, PARENTPRODUCTHIERARCHY, BRANDID, CDMLOADDATE, SOURCE, FILENAME
                            FROM IDS_DEV.MENU_BV."MENU_PRODUCT_HIERARCHY_PLR_BV";
create view IF NOT EXISTS MENU_PRODUCT_HIERARCHY_TYPE_PLR_BV(
	PRODUCTHIERARCHYTYPEID,
	PRODUCTHIERARCHYTYPENAME,
	PRODUCTHIERARCHYTYPEDESC,
	PARENTPRODUCTHIERARCHYTYPE,
	BRANDID,
	CDMLOADDATE,
	SOURCE,
	FILENAME
) as SELECT
                               PRODUCTHIERARCHYTYPEID, PRODUCTHIERARCHYTYPENAME, PRODUCTHIERARCHYTYPEDESC, PARENTPRODUCTHIERARCHYTYPE, BRANDID, CDMLOADDATE, SOURCE, FILENAME
                            FROM IDS_DEV.MENU_BV."MENU_PRODUCT_HIERARCHY_TYPE_PLR_BV";
create view IF NOT EXISTS MENU_PRODUCT_PLR_BV(
	MDMPRODUCTID,
	PRODUCTNAME,
	PRODUCTDESC,
	PRODUCTHIERARCHYNODE,
	PRODUCTTYPE,
	PRODUCTSTATUS,
	TECHNICALSIZE,
	UNITOFMEASURE,
	NONUSASPECIALTY,
	VEHICLE,
	ISHOTPRODUCT,
	ISBREAKFASTPRODUCT,
	PRODUCTBRAND,
	MENUTYPE,
	MENUSECTION,
	GBBMEASURE,
	ISCOLDSPACEREQUIRED,
	ISFRYERREQUIRED,
	MISC1,
	MISC2,
	MISC3,
	MISC4,
	MISC5,
	MISC6,
	MISC7,
	MISC8,
	MISC9,
	MISC10,
	BRANDID,
	CDMLOADDATE,
	SOURCE,
	FILENAME
) as SELECT
                               MDMPRODUCTID, PRODUCTNAME, PRODUCTDESC, PRODUCTHIERARCHYNODE, PRODUCTTYPE, PRODUCTSTATUS, TECHNICALSIZE, UNITOFMEASURE, NONUSASPECIALTY, VEHICLE, ISHOTPRODUCT, ISBREAKFASTPRODUCT, PRODUCTBRAND, MENUTYPE, MENUSECTION, GBBMEASURE, ISCOLDSPACEREQUIRED, ISFRYERREQUIRED, MISC1, MISC2, MISC3, MISC4, MISC5, MISC6, MISC7, MISC8, MISC9, MISC10, BRANDID, CDMLOADDATE, SOURCE, FILENAME
                            FROM IDS_DEV.MENU_BV."MENU_PRODUCT_PLR_BV";