create view IF NOT EXISTS MEDIA_CHANNEL_CAMPAIGN(
	CHANNEL,
	SUBCHANNEL,
	SUBCHANNEL2,
	PARTNER_NAME,
	CAMPAIGN_NAME,
	STRATEGY_NAME,
	STRATEGY_TYPE_NAME,
	BRAND_ID,
	SOURCE_SYSTEM_NAME,
	LAST_UPDATE_DTTM
) as
 SELECT DISTINCT ch.CHANNEL_NM AS Channel,
        ch.CHANNEL_CATEGORY_NM AS SubChannel,
        ch.CHANNEL_SUBCATEGORY_NM AS SubChannel2,
        ch.PARTNER_NM AS PARTNER_NAME,
        cmp.CAMPAIGN_NM AS CAMPAIGN_NAME,
        str.STRATEGY_NM AS STRATEGY_NAME,
        str.STRATEGY_TYPE_NM AS STRATEGY_TYPE_NAME,
        ch.BRAND_ID AS BRAND_ID,
        ch.SOURCE_SYSTEM_NM AS SOURCE_SYSTEM_NAME,
        ch.LAST_UPDATED_DTTM AS LAST_UPDATE_DTTM
FROM IDM_DEV.MEDIA_BV.CHANNEL_HIERARCHY_BV ch
 INNER JOIN IDM_DEV.MEDIA_BV.MEDIA_ACTIVITY_FACT_BV fct
   ON ch.CHANNEL_HIERARCHY_KEY=fct.CHANNEL_HIERARCHY_KEY
 INNER JOIN IDM_DEV.MEDIA_BV.CAMPAIGN_BV cmp
   ON cmp.CAMPAIGN_KEY=fct.CAMPAIGN_KEY
 INNER JOIN IDM_DEV.MEDIA_BV.STRATEGY_BV str
   ON str.STRATEGY_KEY=fct.STRATEGY_KEY;
create view IF NOT EXISTS MEDIA_CHANNEL_CAMPAIGN_DS(
	CHANNEL,
	SUBCHANNEL,
	SUBCHANNEL2,
	PARTNER_NAME,
	CAMPAIGN_NAME,
	STRATEGY_NAME,
	STRATEGY_TYPE_NAME,
	BRAND_ID,
	SOURCE_SYSTEM_NAME,
	LAST_UPDATE_DTTM
) as
 SELECT DISTINCT ch.CHANNEL_NM AS Channel,
        ch.CHANNEL_CATEGORY_NM AS SubChannel,
        ch.CHANNEL_SUBCATEGORY_NM AS SubChannel2,
        ch.PARTNER_NM AS PARTNER_NAME,
        cmp.CAMPAIGN_NM AS CAMPAIGN_NAME,
        str.STRATEGY_NM AS STRATEGY_NAME,
        str.STRATEGY_TYPE_NM AS STRATEGY_TYPE_NAME,
        ch.BRAND_ID AS BRAND_ID,
        ch.SOURCE_SYSTEM_NM AS SOURCE_SYSTEM_NAME,
        ch.LAST_UPDATED_DTTM AS LAST_UPDATE_DTTM
FROM IDS_DEV.DATASTORE.CHANNEL_HIERARCHY ch
 INNER JOIN IDS_DEV.DATASTORE.MEDIA_ACTIVITY_FACT fct
   ON ch.CHANNEL_HIERARCHY_KEY=fct.CHANNEL_HIERARCHY_KEY
 INNER JOIN IDS_DEV.DATASTORE.CAMPAIGN cmp
   ON cmp.CAMPAIGN_KEY=fct.CAMPAIGN_KEY
 INNER JOIN IDS_DEV.DATASTORE.STRATEGY str
   ON str.STRATEGY_KEY=fct.STRATEGY_KEY;
create view IF NOT EXISTS MEDIA_CHANNEL_HIERARCHY(
	CHANNEL,
	SUBCHANNEL,
	SUBCHANNEL2,
	PARTNER_NAME,
	BRAND_ID,
	SOURCE_SYSTEM_NAME,
	LAST_UPDATE_DTTM
) as
 SELECT CHANNEL_NM AS Channel,
        CHANNEL_CATEGORY_NM AS SubChannel,
        CHANNEL_SUBCATEGORY_NM AS SubChannel2,
        PARTNER_NM AS PARTNER_NAME,
        BRAND_ID AS BRAND_ID,
        SOURCE_SYSTEM_NM AS SOURCE_SYSTEM_NAME,
        LAST_UPDATED_DTTM AS LAST_UPDATE_DTTM
 FROM IDM_DEV.MEDIA_BV.CHANNEL_HIERARCHY_BV;
create view IF NOT EXISTS MEDIA_CHANNEL_HIERARCHY_DS(
	CHANNEL,
	SUBCHANNEL,
	SUBCHANNEL2,
	PARTNER_NAME,
	BRAND_ID,
	SOURCE_SYSTEM_NAME,
	LAST_UPDATE_DTTM
) as
 SELECT CHANNEL_NM AS Channel,
        CHANNEL_CATEGORY_NM AS SubChannel,
        CHANNEL_SUBCATEGORY_NM AS SubChannel2,
        PARTNER_NM AS PARTNER_NAME,
        BRAND_ID AS BRAND_ID,
        SOURCE_SYSTEM_NM AS SOURCE_SYSTEM_NAME,
        LAST_UPDATED_DTTM AS LAST_UPDATE_DTTM
 FROM IDS_DEV.DATASTORE.CHANNEL_HIERARCHY;