spark.access.token.url https://api.incontact.com/InContactAuthorizationServer/Token
spark.auth.key basic VlZfRGF0YUxha2UxQENhcGdlbWluaTE6NDU5NzI3Mw==
spark.access.credentials {"grant_type" : "password","username" : "ashwin.john@capgemini.com","password" : "VV$Feb$022020","scope" : ""}
spark.skill.dim.sql select cti_skill_skey,src_skill_id from vv_db.hvtb_nbx_core_cti_skill_dim 
spark.agent.dim.sql select cti_agent_skey,src_agent_id from vv_db.hvtb_nbx_core_cti_agent_dim
spark.target.fact.table vv_db.hvtb_nbx_core_cti_agent_state_history_fact