spark.redshift.url jdbc:redshift://10.3.0.120:5439/qanbxpub
spark.redshift.username talenduser
spark.redshift.password	Talenduser@123

spark.cti.call.agent.dim.sql select src_agent_id as cti_agent_dim_agentId, cti_agent_skey as cti_agent_dim_cti_agent_skey from vv_db.hvtb_nbx_core_cti_agent_dim
spark.cti.call.team.dim.sql select src_team_id as cti_team_dim_teamId, cti_team_skey as cti_team_dim_cti_team_skey  from vv_db.hvtb_nbx_core_cti_team_dim
spark.cti.call.skill.dim.sql select src_skill_id as cti_skill_dim_skillId, cti_skill_skey as cti_skill_dim_cti_skill_skey from vv_db.hvtb_nbx_core_cti_skill_dim
spark.cti.call.compaign.dim.sql select src_campaign_id as cti_compaign_dim_campaignId, cti_campaign_skey as cti_compaign_dim_cti_campaign_skey from vv_db.hvtb_nbx_core_cti_campaign_dim
spark.cti.call.date.dim.sql select date as datedim_date, date_id as datedim_date_id from vv_db.hvtb_nbx_core_date_dim
spark.cti.call.time.dim.sql select time_skey as time_dim_s_key, second_of_day as time_dim_second_of_day from vv_db.hvtb_nbx_core_time_dim

spark.source.columns contactid,mastercontactid,pointofcontactname,agentid,teamid,skillid,campaignid,dateskey,timeskey,prequeueseconds,inqueueseconds,postqueueseconds,totaldurationseconds,abandonseconds,callbacktime,agentseconds,isoutbound,transferindicatorid,abandoned
spark.pond.allColumns src_contact_id as pond_src_contact_id,src_master_contact_Id as pond_src_master_contact_Id,point_of_contact_name as pond_point_of_contact_name,cti_agent_skey as pond_cti_agent_skey,cti_team_skey as pond_cti_team_skey,cti_skill_skey as pond_cti_skill_skey,cti_campaign_skey as pond_cti_campaign_skey,start_date_skey as pond_start_date_skey,start_time_skey as pond_start_time_skey,prequeue_time_in_seconds as pond_prequeue_time_in_seconds,inqueue_time_in_seconds as pond_inqueue_time_in_seconds,postqueue_time_in_seconds as pond_postqueue_time_in_seconds,total_duration_in_seconds as pond_total_duration_in_seconds,abandon_time_in_seconds as pond_abandon_time_in_seconds,callback_time as pond_callback_time,agent_seconds as pond_agent_seconds,outbound_call_flg as pond_outbound_call_flg,transferIndicator_flg as pond_transferIndicator_flg,abandoned_flg as pond_abandoned_flg,load_dt as pond_load_dt,upd_dt as pond_upd_dt,part_dt as pond_part_dt

spark.target.cticall.table vv_db.hvtb_parse_cti_call

spark.pond.database vv_db
spark.pond.table hvtb_nbx_core_cti_call_fact
spark.target.schema vv_db
spark.target.table cti_call_fact

spark.redshift.schema Hive_schema_stg
spark.redshift.tablename cti_call_fact


spark.tableType FACT
spark.frameworkEnv shore
spark.scdtype type1

spark.target.final_collist final_view.contactid as src_contact_id,final_view.mastercontactid as src_master_contact_Id,final_view.pointofcontactname as point_of_contact_name,final_view.agentid as cti_agent_skey,final_view.teamid as cti_team_skey,final_view.skillid as cti_skill_skey,final_view.campaignid as cti_campaign_skey,final_view.dateskey as start_date_skey,final_view.timeskey as start_time_skey,final_view.prequeueseconds as prequeue_time_in_seconds,final_view.inqueueseconds as inqueue_time_in_seconds,final_view.postqueueseconds as postqueue_time_in_seconds,final_view.totaldurationseconds as total_duration_in_seconds,final_view.abandonseconds as abandon_time_in_seconds,final_view.callbacktime as callback_time,final_view.agentseconds as agent_seconds,final_view.isoutbound as outbound_call_flg,final_view.transferindicatorid as transferIndicator_flg,final_view.abandoned as abandoned_flg,load_dt,upd_dt,part_dt
spark.target.temp s3://vv-staging-emr-cluster/data/core/seaware/temp/hvtb_nbx_core_cti_call_fact
spark.target.location s3://vv-staging-emr-cluster/data/core/seaware/hvtb_nbx_core_cti_call_fact