#spark.username NBX_API
#spark.password STG7cj39v
#spark.api.url https://stage.virginvoyages.com/seaware/SwBizLogic/Service.svc/ProcessRequest
#spark.source.query SELECT src_sail_id, (s.ship_id) as ship_id, to_date(sail_date_from) as sail_date_from, to_date(sail_date_to) as sail_date_to ,(sh.ship) as ship from vv_db.hvtb_nbx_core_sw_sail_dim s join vv_db.hvtb_nbx_core_sw_ship_dim sh on sh.ship_id = s.ship_id where to_date(s.rec_end_dttm) = '9999-12-31'
#spark.target.table vv_db.tmp_pricing_detail

spark.custapi.url https://prod.virginvoyages.com/seaware/SwBizLogic/Service.svc/ProcessRequest
spark.maxdate.query Select sail_date_to  from vv_db.hvtb_nbx_core_sw_sail_dim sail inner join vv_db.hvtb_nbx_core_sw_ship_dim shipd on ( shipd.ship !='VC' and shipd.ship !='XE' and sail.ship_id == shipd.ship_id)
spark.maxcutoff.months 24
spark.numadults.list 1,2,3,4
spark.currency.list CAD,GBP,USD,AUD,NZD
spark.target.table vv_db.hvtb_nbx_core_pricing_detail
spark.target.temp hdfs:///data/temp/hvtb_nbx_core_pricing_detail
spark.landing.table vv_db.hvtb_lnd_pricing_detail
spark.target.final s3://vv-staging-emr-cluster/data/hivetables/vv_db/hvtb_nbx_core_pricing_detail
spark.noofDays 7
spark.noofRecords 200