create TABLE IF NOT EXISTS ADF_LOGGING (
	ID NUMBER(38,0) NOT NULL autoincrement,
	FILENAME VARCHAR(16777216),
	DATAREAD NUMBER(38,0),
	ROWSREAD NUMBER(38,0),
	ROWSCOPIED NUMBER(38,0),
	FILESWRITTEN NUMBER(38,0),
	COPYDURATION NUMBER(38,0),
	DATESTART TIMESTAMP_NTZ(9),
	DATEEND TIMESTAMP_NTZ(9),
	STATUS VARCHAR(16777216),
	primary key (ID)
);
create TABLE IF NOT EXISTS CRM_EXISTING_CLICKS (
	DEPLOYMENTID VARCHAR(16777216),
	EMAILADDRESS VARCHAR(16777216),
	LINKURL VARCHAR(16777216)
);
create TABLE IF NOT EXISTS CRM_EXISTING_OPEN (
	DEPLOYMENTID VARCHAR(16777216),
	EMAILADDRESS VARCHAR(16777216)
);
create TABLE IF NOT EXISTS DUN_MEDALLIA_CUST_SURVEY (
	CUSTOMERSURVEY VARIANT,
	LOADDATETIME VARCHAR(16777216),
	LOADID VARCHAR(16777216),
	LOADTYPE VARCHAR(16777216),
	FILENAME VARCHAR(16777216)
);
create TABLE IF NOT EXISTS ECOSUREAUDITEXTRACT_AUDIT (
	AUDITID NUMBER(38,0),
	CONCEPTNUM VARCHAR(16777216),
	UNITNUM VARCHAR(16777216),
	ADDRESS1 VARCHAR(16777216),
	ADDRESS2 VARCHAR(16777216),
	CITY VARCHAR(16777216),
	STATE VARCHAR(16777216),
	ZIP VARCHAR(16777216),
	COUNTRY VARCHAR(16777216),
	UNITMGRFIRST VARCHAR(16777216),
	UNITMGRLAST VARCHAR(16777216),
	UNITMGRTITLE VARCHAR(16777216),
	AUDITORID NUMBER(38,0),
	AUDITSTARTED TIMESTAMP_NTZ(9),
	AUDITENDED TIMESTAMP_NTZ(9),
	CYCLE NUMBER(38,0),
	VISIT NUMBER(38,0),
	REFERENCENUM VARCHAR(16777216),
	NOTE VARCHAR(16777216),
	ECOSURESTOREID NUMBER(38,0),
	FORMNAME VARCHAR(16777216),
	AUDIT_DATE DATE,
	LOAD_ID NUMBER(38,0),
	LOAD_DTTM TIMESTAMP_NTZ(9)
);
create TABLE IF NOT EXISTS ECOSUREAUDITEXTRACT_HEADER (
	DATE DATE,
	FILENAME VARCHAR(16777216),
	TOTALRECORDS NUMBER(38,0),
	TOTALAUDITS NUMBER(38,0),
	TOTALRESPONSE NUMBER(38,0),
	TOTALISSUES NUMBER(38,0),
	AUDIT_DATE DATE,
	LOAD_ID NUMBER(38,0),
	LOAD_DTTM TIMESTAMP_NTZ(9)
);
create TABLE IF NOT EXISTS ECOSUREAUDITEXTRACT_ISSUES (
	AUDITID NUMBER(38,0),
	AUDITRESPID NUMBER(38,0),
	ISSUENUM VARCHAR(16777216),
	ISSUE VARCHAR(16777216),
	NOTE VARCHAR(16777216),
	AUDIT_DATE DATE,
	LOAD_ID NUMBER(38,0),
	LOAD_DTTM TIMESTAMP_NTZ(9)
);
create TABLE IF NOT EXISTS ECOSUREAUDITEXTRACT_RESPONSE (
	AUDITID NUMBER(38,0),
	SECTIONNUM VARCHAR(16777216),
	AUDITRESPID NUMBER(38,0),
	QUESTIONID VARCHAR(16777216),
	QUESTIONTEXT VARCHAR(16777216),
	RESPONSE VARCHAR(16777216),
	RESPONSENOTES VARCHAR(16777216),
	SCOREGROUPNUM VARCHAR(16777216),
	BOXGROUPNUM VARCHAR(16777216),
	VIOLATIONPOINTS FLOAT,
	POINTS NUMBER(38,0),
	POINTSTOTOTAL NUMBER(38,0),
	AUDIT_DATE DATE,
	LOAD_ID NUMBER(38,0),
	LOAD_DTTM TIMESTAMP_NTZ(9)
);
create TABLE IF NOT EXISTS ECOSUREAUDITEXTRACT_SCORE (
	AUDITID NUMBER(38,0),
	SCORENAME VARCHAR(16777216),
	SCORE FLOAT,
	RATING VARCHAR(16777216),
	INCOMPLIANCE NUMBER(38,0),
	OUTOFCOMPLIANCE NUMBER(38,0),
	AUDIT_DATE DATE,
	LOAD_ID NUMBER(38,0),
	LOAD_DTTM TIMESTAMP_NTZ(9)
);
create TABLE IF NOT EXISTS ECOSUREAUDITEXTRACT_SECTIONS (
	AUDITID NUMBER(38,0),
	SECTIONNUM VARCHAR(16777216),
	SECTIONNAME VARCHAR(16777216),
	NOTE VARCHAR(16777216),
	SUBSECTIONFLAG VARCHAR(16777216),
	PARENTSECTIONNUM VARCHAR(16777216),
	PARENTSECTIONNAME VARCHAR(16777216),
	AUDIT_DATE DATE,
	LOAD_ID NUMBER(38,0),
	LOAD_DTTM TIMESTAMP_NTZ(9)
);
create TABLE IF NOT EXISTS ECOSURE_AUDIT_FILE_MAPPING (
	AUDIT_ID NUMBER(38,0),
	CURRENT_FILE_DATE_IN_IDS DATE
);
create TABLE IF NOT EXISTS EPS_CRM_ACTIVITY (
	FOLDERNAME_M VARCHAR(16777216),
	CUSTOMERKEY VARCHAR(16777216),
	EMAILADDRESS VARCHAR(16777216),
	MESSAGENAME VARCHAR(16777216),
	MESSAGEID VARCHAR(16777216),
	DEPLOYMENTID VARCHAR(16777216),
	SUBJECTLINE VARCHAR(16777216),
	AUDIENCE VARCHAR(16777216),
	ACTION VARCHAR(16777216),
	ORIGINALEVENTTIMESTAMP VARCHAR(16777216),
	LINKNAME VARCHAR(16777216),
	LINKTAG VARCHAR(16777216),
	LINKURL VARCHAR(16777216),
	BUSINESSUNITNAME VARCHAR(16777216),
	DEVICECATEGORY VARCHAR(16777216),
	DEVICETYPE VARCHAR(16777216),
	UNDELIVEREDCATEGORY VARCHAR(16777216),
	SERVICETRANSACTIONID VARCHAR(16777216),
	SERVICECOMMUNICATIONID VARCHAR(16777216),
	EVENTNAME VARCHAR(16777216),
	CONVERSIONAMOUNT VARCHAR(16777216),
	CONVERSIONQUANTITY VARCHAR(16777216),
	CONVERSIONORDERID VARCHAR(16777216),
	CONVERSIONCATEGORY VARCHAR(16777216),
	CONVERSIONSUBCATEGORY VARCHAR(16777216),
	CONVERSIONDATETIME VARCHAR(16777216),
	CONVERSIONTRANSACTIONID VARCHAR(16777216),
	SOURCE_SYSTEM_NM VARCHAR(255),
	BRAND_ID VARCHAR(255),
	LOAD_ID NUMBER(38,0),
	LOAD_DTTM TIMESTAMP_NTZ(9),
	UPDATE_ID NUMBER(38,0),
	UPDATE_DTTM TIMESTAMP_NTZ(9),
	LOAD_FILENAME VARCHAR(16777216)
);
create TABLE IF NOT EXISTS EPS_CRM_ACTIVITY_RAW_BACKUP_20220315 (
	FOLDERNAME_M VARCHAR(16777216),
	CUSTOMERKEY VARCHAR(16777216),
	EMAILADDRESS VARCHAR(16777216),
	MESSAGENAME VARCHAR(16777216),
	MESSAGEID VARCHAR(16777216),
	DEPLOYMENTID VARCHAR(16777216),
	SUBJECTLINE VARCHAR(16777216),
	AUDIENCE VARCHAR(16777216),
	ACTION VARCHAR(16777216),
	ORIGINALEVENTTIMESTAMP VARCHAR(16777216),
	LINKNAME VARCHAR(16777216),
	LINKTAG VARCHAR(16777216),
	LINKURL VARCHAR(16777216),
	BUSINESSUNITNAME VARCHAR(16777216),
	DEVICECATEGORY VARCHAR(16777216),
	DEVICETYPE VARCHAR(16777216),
	UNDELIVEREDCATEGORY VARCHAR(16777216),
	SERVICETRANSACTIONID VARCHAR(16777216),
	SERVICECOMMUNICATIONID VARCHAR(16777216),
	EVENTNAME VARCHAR(16777216),
	CONVERSIONAMOUNT VARCHAR(16777216),
	CONVERSIONQUANTITY VARCHAR(16777216),
	CONVERSIONORDERID VARCHAR(16777216),
	CONVERSIONCATEGORY VARCHAR(16777216),
	CONVERSIONSUBCATEGORY VARCHAR(16777216),
	CONVERSIONDATETIME VARCHAR(16777216),
	CONVERSIONTRANSACTIONID VARCHAR(16777216),
	SOURCE_SYSTEM_NM VARCHAR(255),
	BRAND_ID VARCHAR(255),
	LOAD_ID NUMBER(38,0),
	LOAD_DTTM TIMESTAMP_NTZ(9),
	UPDATE_ID NUMBER(38,0),
	UPDATE_DTTM TIMESTAMP_NTZ(9),
	LOAD_FILENAME VARCHAR(16777216)
);
create TABLE IF NOT EXISTS EPS_CRM_FTD (
	CUSTOMERKEY VARCHAR(16777216),
	EMAILADDRESS VARCHAR(16777216),
	EMAILADDRESSDELIVERYSTATUS VARCHAR(16777216),
	EMAILADDRESSDELIVERYSTATUSDATE VARCHAR(16777216),
	SOURCE_SYSTEM_NM VARCHAR(255),
	BRAND_ID VARCHAR(255),
	LOAD_ID NUMBER(38,0),
	LOAD_DTTM TIMESTAMP_NTZ(9),
	UPDATE_ID NUMBER(38,0),
	UPDATE_DTTM TIMESTAMP_NTZ(9),
	LOAD_FILENAME VARCHAR(16777216)
);
create TABLE IF NOT EXISTS EPS_CRM_OPTOUT (
	CUSTOMERKEY VARCHAR(16777216),
	EMAILADDRESS VARCHAR(16777216),
	EMAILCHANNELOPTOUTFLAG VARCHAR(16777216),
	EMAILCHANNELOPTSTATUSDATE VARCHAR(16777216),
	EMAILCHANNELOPTSTATUSSOURCE VARCHAR(16777216),
	SOURCE_SYSTEM_NM VARCHAR(255),
	BRAND_ID VARCHAR(255),
	LOAD_ID NUMBER(38,0),
	LOAD_DTTM TIMESTAMP_NTZ(9),
	UPDATE_ID NUMBER(38,0),
	UPDATE_DTTM TIMESTAMP_NTZ(9),
	LOAD_FILENAME VARCHAR(16777216)
);
create TABLE IF NOT EXISTS EPS_CRM_PUSH_ACTIVITY (
	CUSTOMERKEY VARCHAR(16777216),
	APPID VARCHAR(16777216),
	DEVICEID VARCHAR(16777216),
	MOBILEPUSHOSNAME VARCHAR(16777216),
	MESSAGENAME VARCHAR(16777216),
	MESSAGEID VARCHAR(16777216),
	DEPLOYMENTID VARCHAR(16777216),
	ACTION VARCHAR(16777216),
	ACTIONTIMESTAMP VARCHAR(16777216),
	BUSINESSUNITNAME VARCHAR(16777216),
	SERVICETRANSACTIONID VARCHAR(16777216),
	SOURCE_SYSTEM_NM VARCHAR(255),
	BRAND_ID VARCHAR(255),
	LOAD_ID NUMBER(38,0),
	LOAD_DTTM TIMESTAMP_NTZ(9),
	UPDATE_ID NUMBER(38,0),
	UPDATE_DTTM TIMESTAMP_NTZ(9),
	LOAD_FILENAME VARCHAR(16777216)
);
create TABLE IF NOT EXISTS EPS_DD_M_CAMPAIGN_RAW_HIST (
	BI_PROFILE_ID VARCHAR(16777216),
	EPSILON_PROFILE_ID VARCHAR(16777216),
	CAMPAIGN_NAME VARCHAR(16777216),
	CAMPAIGN_CODE VARCHAR(16777216),
	CAMPAIGN_TYPE VARCHAR(16777216),
	CAMPAIGN_DESCRIPTION VARCHAR(16777216),
	SEGMENT_CODE VARCHAR(16777216),
	OFFER_NAME VARCHAR(16777216),
	OFFER_CODE VARCHAR(16777216),
	MEMBER_OFFER_START_DATE VARCHAR(16777216),
	MEMBER_OFFER_END_DATE VARCHAR(16777216),
	COUPON_CODE VARCHAR(16777216),
	CHANNEL_ID VARCHAR(16777216),
	DELIVERY_DATE VARCHAR(16777216),
	SOURCE_SYSTEM_NM VARCHAR(255),
	BRAND_ID VARCHAR(255),
	LOAD_ID NUMBER(38,0),
	LOAD_DTTM TIMESTAMP_NTZ(9),
	UPDATE_ID NUMBER(38,0),
	UPDATE_DTTM TIMESTAMP_NTZ(9),
	LOAD_FILENAME VARCHAR(16777216)
);
create TABLE IF NOT EXISTS EPS_DD_OFFER_CODE_RAW_HIST (
	OFFER_CODE VARCHAR(16777216),
	OFFER_NAME VARCHAR(16777216),
	OFFER_DESCRIPTION VARCHAR(16777216),
	OFFER_START_DATE VARCHAR(16777216),
	OFFER_END_DATE VARCHAR(16777216),
	ACTIVE_INDICATOR VARCHAR(16777216),
	CREATE_USER VARCHAR(16777216),
	SOURCE_SYSTEM_NM VARCHAR(255),
	BRAND_ID VARCHAR(255),
	LOAD_ID NUMBER(38,0),
	LOAD_DTTM TIMESTAMP_NTZ(9),
	UPDATE_ID NUMBER(38,0),
	UPDATE_DTTM TIMESTAMP_NTZ(9),
	LOAD_FILENAME VARCHAR(16777216)
);
create TABLE IF NOT EXISTS EPS_DD_PNT_ACTIVITY_RAW_HIST (
	EPSILON_POINT_ID VARCHAR(16777216),
	EPSILON_TRANSACTION_ID VARCHAR(16777216),
	EPSILON_TRANSACTION_DETAIL_ID VARCHAR(16777216),
	EPSILON_PROFILE_ID VARCHAR(16777216),
	POINT_TRANSACTION_CODE VARCHAR(16777216),
	STORE_NUMBER VARCHAR(16777216),
	TRANSACTION_DTTM VARCHAR(16777216),
	POSTED_DTTM VARCHAR(16777216),
	DUNKIN_TRANSACTION_NUMBER VARCHAR(16777216),
	POS_NUMBER VARCHAR(16777216),
	ADJUSTMENT_CODE VARCHAR(16777216),
	OFFER_CODE VARCHAR(16777216),
	SKU VARCHAR(16777216),
	LINE_NUMBER VARCHAR(16777216),
	AWARD_CODE VARCHAR(16777216),
	MISSING_TRANSACTION_INDICATOR VARCHAR(16777216),
	POINTS VARCHAR(16777216),
	POS_INDICATOR VARCHAR(16777216),
	ADJUSTMENT_REASON VARCHAR(16777216),
	SOURCE_SYSTEM_NM VARCHAR(255),
	BRAND_ID VARCHAR(255),
	LOAD_ID NUMBER(38,0),
	LOAD_DTTM TIMESTAMP_NTZ(9),
	UPDATE_ID NUMBER(38,0),
	UPDATE_DTTM TIMESTAMP_NTZ(9),
	LOAD_FILENAME VARCHAR(16777216)
);
create TABLE IF NOT EXISTS EPS_ELEV_LOYALTY_TIER (
	EPSILON_PROFILE_ID VARCHAR(16777216),
	TIER_CHANGE_DATE VARCHAR(16777216),
	TIER_NAME VARCHAR(16777216),
	TIER_STATUS_ACTION VARCHAR(16777216),
	TIER_EXPIRE_DATE VARCHAR(16777216),
	TIER_STATUS_SOURCE VARCHAR(16777216),
	TIER_REASON_DESC VARCHAR(16777216),
	SOURCE_SYSTEM_NAME VARCHAR(255),
	BRAND_ID VARCHAR(255),
	LOAD_ID NUMBER(38,0),
	LOAD_DTTM TIMESTAMP_NTZ(9),
	UPDATE_ID NUMBER(38,0),
	UPDATE_DTTM TIMESTAMP_NTZ(9),
	LOAD_FILENAME VARCHAR(16777216)
);
create TABLE IF NOT EXISTS FLYWAY_SCHEMA_HISTORY (
	INSTALLED_RANK NUMBER(38,0) NOT NULL,
	VERSION VARCHAR(50),
	DESCRIPTION VARCHAR(200),
	TYPE VARCHAR(20) NOT NULL,
	SCRIPT VARCHAR(1000) NOT NULL,
	CHECKSUM NUMBER(38,0),
	INSTALLED_BY VARCHAR(100) NOT NULL,
	INSTALLED_ON TIMESTAMP_LTZ(9) NOT NULL DEFAULT CURRENT_TIMESTAMP(),
	EXECUTION_TIME NUMBER(38,0) NOT NULL,
	SUCCESS BOOLEAN NOT NULL,
	primary key (INSTALLED_RANK)
);
create TABLE IF NOT EXISTS INSPIRE_DUNKIN_ACTIVITY_RAW_HIST (
	FOLDER_NAME_M VARCHAR(16777216),
	CUSTOMER_KEY VARCHAR(16777216),
	EMAIL_ADDRESS VARCHAR(16777216),
	MESSAGE_NAME VARCHAR(16777216),
	MESSAGE_ID VARCHAR(16777216),
	DEPLOYMENT_ID VARCHAR(16777216),
	SUBJECT_LINE VARCHAR(16777216),
	AUDIENCE VARCHAR(16777216),
	ACTION VARCHAR(16777216),
	ORIGINAL_EVENT_TIMESTAMP VARCHAR(16777216),
	LINK_NAME VARCHAR(16777216),
	LINK_TAG VARCHAR(16777216),
	LINK_URL VARCHAR(16777216),
	BUSINESS_UNIT_NAME VARCHAR(16777216),
	DEVICE_CATEGORY VARCHAR(16777216),
	DEVICE_TYPE VARCHAR(16777216),
	UNDELIVERED_CATEGORY VARCHAR(16777216),
	SERVICE_TRANSACTIONID VARCHAR(16777216),
	SERVICE_COMMUNICATION_ID VARCHAR(16777216),
	EVENT_NAME VARCHAR(16777216),
	CONVERSION_AMOUNT VARCHAR(16777216),
	CONVERSION_QUANTITY VARCHAR(16777216),
	CONVERSION_ORDER_ID VARCHAR(16777216),
	CONVERSION_CATEGORY VARCHAR(16777216),
	CONVERSION_SUBCATEGORY VARCHAR(16777216),
	CONVERSION_DATE_TIME VARCHAR(16777216),
	CONVERSION_CUSTOMER_TRANSACTION_ID VARCHAR(16777216),
	SOURCE_SYSTEM_NM VARCHAR(255),
	BRAND_ID VARCHAR(255),
	LOAD_ID NUMBER(38,0),
	LOAD_DTTM TIMESTAMP_NTZ(9),
	UPDATE_ID NUMBER(38,0),
	UPDATE_DTTM TIMESTAMP_NTZ(9),
	LOAD_FILENAME VARCHAR(16777216)
);
create TABLE IF NOT EXISTS IPW_GUEST_INFO (
	ID VARCHAR(16777216),
	FIRST_NAME VARCHAR(16777216),
	LAST_NAME VARCHAR(16777216),
	USER_NAME VARCHAR(16777216),
	FIRST_TRANSACTION_DATE VARCHAR(16777216),
	EMAIL_OPTIN VARCHAR(1),
	BRAND_ID VARCHAR(16777216),
	LOAD_DATE TIMESTAMP_NTZ(9)
);
create TABLE IF NOT EXISTS OFFERBOT_OFFER_BRIEF_RAW (
	OFFER_CODE VARCHAR(16777216),
	OFFER_NAME VARCHAR(16777216),
	OFFER_START_DATE VARCHAR(16777216),
	OFFER_END_DATE VARCHAR(16777216),
	CALC_OFFER_END_DATE VARCHAR(16777216),
	BONUS VARCHAR(16777216),
	BONUS_TYPE VARCHAR(16777216),
	OFFER_DRIVER VARCHAR(16777216),
	OFFER_CAMPAIGN VARCHAR(16777216),
	CHANNEL VARCHAR(16777216),
	OFFER_PRODUCT VARCHAR(16777216),
	MARKET VARCHAR(16777216),
	STORE_COVERAGE VARCHAR(16777216),
	OFFER_DESC VARCHAR(16777216),
	OFFER_NAME_GUEST VARCHAR(16777216),
	PLU VARCHAR(16777216),
	CUSTOM_TABLE VARCHAR(16777216),
	UPLOADED VARCHAR(16777216),
	CREATED_DATE VARCHAR(16777216),
	SOURCE_SYSTEM_NM VARCHAR(255),
	BRAND_ID VARCHAR(255),
	LOAD_ID NUMBER(38,0),
	LOAD_DTTM TIMESTAMP_NTZ(9),
	UPDATE_ID NUMBER(38,0),
	UPDATE_DTTM TIMESTAMP_NTZ(9),
	LOAD_FILENAME VARCHAR(16777216)
);
create TABLE IF NOT EXISTS OFFERBOT_OFFER_GUESTS_HISTORY_RAW (
	OFFER_CODE VARCHAR(16777216),
	"SAMPLE" VARCHAR(16777216),
	EPSILON_PROFILE_ID VARCHAR(16777216),
	TARGET_CRITERIA VARCHAR(16777216),
	TENURE VARCHAR(16777216),
	PRE_STATUS VARCHAR(16777216),
	CAMPAIGN VARCHAR(16777216),
	PRE_FREQBAND VARCHAR(16777216),
	SOURCE_SYSTEM_NM VARCHAR(255),
	BRAND_ID VARCHAR(255),
	LOAD_ID NUMBER(38,0),
	LOAD_DTTM TIMESTAMP_NTZ(9),
	UPDATE_ID NUMBER(38,0),
	UPDATE_DTTM TIMESTAMP_NTZ(9),
	LOAD_FILENAME VARCHAR(16777216)
);
create TABLE IF NOT EXISTS OFFERBOT_OFFER_GUESTS_RAW (
	OFFER_CODE VARCHAR(16777216),
	SEGMENT_NAME VARCHAR(16777216),
	START_DATE VARCHAR(16777216),
	END_DATE VARCHAR(16777216),
	DUNKIN_GUEST_ID VARCHAR(16777216),
	ENROLLMENT_ADJUSTED VARCHAR(16777216),
	TENURE VARCHAR(16777216),
	DMA VARCHAR(16777216),
	EMAIL_NAME VARCHAR(16777216),
	TEST_TYPE VARCHAR(16777216),
	RESULTS_FLAG VARCHAR(16777216),
	TEST_CHANNEL VARCHAR(16777216),
	CAMPAIGN VARCHAR(16777216),
	TARGET VARCHAR(16777216),
	TARGET_CRITERIA VARCHAR(16777216),
	"SAMPLE" VARCHAR(16777216),
	VAR1_ID VARCHAR(16777216),
	VAR1_VALUE VARCHAR(16777216),
	VAR2_ID VARCHAR(16777216),
	VAR2_VALUE VARCHAR(16777216),
	VAR3_ID VARCHAR(16777216),
	VAR3_VALUE VARCHAR(16777216),
	VAR4_ID VARCHAR(16777216),
	VAR4_VALUE VARCHAR(16777216),
	PRE_STATUS VARCHAR(16777216),
	PRE_TICKET VARCHAR(16777216),
	PRE_VISITS VARCHAR(16777216),
	PRE_QUANTITY VARCHAR(16777216),
	PRE_SPEND VARCHAR(16777216),
	PRE_FREQBAND VARCHAR(16777216),
	EPSILON_PROFILE_ID VARCHAR(16777216),
	SOURCE_SYSTEM_NM VARCHAR(255),
	BRAND_ID VARCHAR(255),
	LOAD_ID NUMBER(38,0),
	LOAD_DTTM TIMESTAMP_NTZ(9),
	UPDATE_ID NUMBER(38,0),
	UPDATE_DTTM TIMESTAMP_NTZ(9),
	LOAD_FILENAME VARCHAR(16777216)
);
create TABLE IF NOT EXISTS SALESSYSTEM_AUDITED_SALES (
	DAYPARTTYPEKEY VARCHAR(16777216),
	DAYPARTTYPENAME VARCHAR(16777216),
	UNITKEY VARCHAR(16777216),
	UNITNUMBER VARCHAR(16777216),
	STATUSKEY VARCHAR(16777216),
	BUSINESSDATEKEY VARCHAR(16777216),
	AMOUNT VARCHAR(16777216),
	COUNT VARCHAR(16777216),
	LOADDATETIME VARCHAR(16777216),
	LOADID VARCHAR(16777216),
	LOADTYPE VARCHAR(16777216),
	FILENAME VARCHAR(16777216)
);
create TABLE IF NOT EXISTS SFMC_CRM_BOUNCE (
	CLIENTID VARCHAR(16777216),
	SENDID VARCHAR(16777216),
	SUBSCRIBERKEY VARCHAR(16777216),
	EMAILADDRESS VARCHAR(16777216),
	SUBSCRIBERID VARCHAR(16777216),
	LISTID VARCHAR(16777216),
	EVENTDATE VARCHAR(16777216),
	EVENTTYPE VARCHAR(16777216),
	BOUNCECATEGORY VARCHAR(16777216),
	SMTPCODE VARCHAR(16777216),
	BOUNCEREASON VARCHAR(16777216),
	BATCHID VARCHAR(16777216),
	TRIGGEREDSENDEXTERNALKEY VARCHAR(16777216),
	SOURCE_SYSTEM_NM VARCHAR(255),
	BRAND_ID VARCHAR(255),
	LOAD_ID NUMBER(38,0),
	LOAD_DTTM TIMESTAMP_NTZ(9),
	UPDATE_ID NUMBER(38,0),
	UPDATE_DTTM TIMESTAMP_NTZ(9),
	LOAD_FILENAME VARCHAR(16777216)
);
create TABLE IF NOT EXISTS SFMC_CRM_CLICK (
	CLIENTID VARCHAR(16777216),
	SENDID VARCHAR(16777216),
	SUBSCRIBERKEY VARCHAR(16777216),
	EMAILADDRESS VARCHAR(16777216),
	SUBSCRIBERID VARCHAR(16777216),
	LISTID VARCHAR(16777216),
	EVENTDATE VARCHAR(16777216),
	EVENTTYPE VARCHAR(16777216),
	SENDURLID VARCHAR(16777216),
	URLID VARCHAR(16777216),
	URL VARCHAR(16777216),
	ALIAS VARCHAR(16777216),
	BATCHID VARCHAR(16777216),
	TRIGGEREDSENDEXTERNALKEY VARCHAR(16777216),
	ISUNIQUE VARCHAR(16777216),
	ISUNIQUEFORURL VARCHAR(16777216),
	MESSAGE_ID VARCHAR(16777216),
	SERVICE_TRANSACTION_ID VARCHAR(16777216),
	SOURCE_SYSTEM_NM VARCHAR(255),
	BRAND_ID VARCHAR(255),
	LOAD_ID NUMBER(38,0),
	LOAD_DTTM TIMESTAMP_NTZ(9),
	UPDATE_ID NUMBER(38,0),
	UPDATE_DTTM TIMESTAMP_NTZ(9),
	LOAD_FILENAME VARCHAR(16777216)
);
create TABLE IF NOT EXISTS SFMC_CRM_COMPLAINT (
	CLIENTID VARCHAR(16777216),
	SENDID VARCHAR(16777216),
	SUBSCRIBERKEY VARCHAR(16777216),
	EMAILADDRESS VARCHAR(16777216),
	SUBSCRIBERID VARCHAR(16777216),
	LISTID VARCHAR(16777216),
	EVENTDATE VARCHAR(16777216),
	EVENTTYPE VARCHAR(16777216),
	BATCHID VARCHAR(16777216),
	TRIGGEREDSENDEXTERNALKEY VARCHAR(16777216),
	DOMAIN VARCHAR(16777216),
	SOURCE_SYSTEM_NM VARCHAR(255),
	BRAND_ID VARCHAR(255),
	LOAD_ID NUMBER(38,0),
	LOAD_DTTM TIMESTAMP_NTZ(9),
	UPDATE_ID NUMBER(38,0),
	UPDATE_DTTM TIMESTAMP_NTZ(9),
	LOAD_FILENAME VARCHAR(16777216)
);
create TABLE IF NOT EXISTS SFMC_CRM_HOLDOUT_LOG (
	JOBID VARCHAR(16777216),
	MEMBERID VARCHAR(16777216),
	DATE VARCHAR(16777216),
	SUBSCRIBERKEY VARCHAR(16777216),
	EMAILADDR VARCHAR(16777216),
	OFFER_CODE VARCHAR(16777216),
	OFFER_NAME VARCHAR(16777216),
	PARENTOFFERID VARCHAR(16777216),
	CAMPAIGN_TYPE VARCHAR(16777216),
	JOURNEYNAME VARCHAR(16777216),
	JOURNEYSTEP VARCHAR(16777216),
	SOC VARCHAR(16777216),
	USER_DEFINED_SEGMENT1 VARCHAR(16777216),
	USER_DEFINED_SEGMENT2 VARCHAR(16777216),
	USER_DEFINED_SEGMENT3 VARCHAR(16777216),
	USER_DEFINED_SEGMENT4 VARCHAR(16777216),
	USER_DEFINED_SEGMENT5 VARCHAR(16777216),
	OFFER1DECISIONLOGIC VARCHAR(16777216),
	POINTBALANCE VARCHAR(16777216),
	EMAILNAME VARCHAR(16777216),
	CAMPAIGN_ID VARCHAR(16777216),
	CAMPAIGN_NAME VARCHAR(16777216),
	CAMPAIGN_CATEGORY VARCHAR(16777216),
	CAMPAIGN_DESCRIPTION VARCHAR(16777216),
	CAMPAIGN_OBJECTIVE VARCHAR(16777216),
	CAMPAIGN_START_DATE VARCHAR(16777216),
	CAMPAIGN_END_DATE VARCHAR(16777216),
	CAMPAIGN_DURATION VARCHAR(16777216),
	CUSTOMER_ID VARCHAR(16777216),
	DATASOURCENAME VARCHAR(16777216),
	CREATIVE_VARIANT VARCHAR(16777216),
	SOURCE_SYSTEM_NM VARCHAR(255),
	BRAND_ID VARCHAR(255),
	LOAD_ID NUMBER(38,0),
	LOAD_DTTM TIMESTAMP_NTZ(9),
	UPDATE_ID NUMBER(38,0),
	UPDATE_DTTM TIMESTAMP_NTZ(9),
	LOAD_FILENAME VARCHAR(16777216)
);
create TABLE IF NOT EXISTS SFMC_CRM_JOURNEY (
	VERSIONID VARCHAR(16777216),
	JOURNEYID VARCHAR(16777216),
	JOURNEYNAME VARCHAR(16777216),
	VERSIONNUMBER VARCHAR(16777216),
	CREATEDDATE VARCHAR(16777216),
	LASTPUBLISHEDDATE VARCHAR(16777216),
	MODIFIEDDATE VARCHAR(16777216),
	JOURNEYSTATUS VARCHAR(16777216),
	SOURCE_SYSTEM_NM VARCHAR(255),
	BRAND_ID VARCHAR(255),
	LOAD_ID NUMBER(38,0),
	LOAD_DTTM TIMESTAMP_NTZ(9),
	UPDATE_ID NUMBER(38,0),
	UPDATE_DTTM TIMESTAMP_NTZ(9),
	LOAD_FILENAME VARCHAR(16777216)
);
create TABLE IF NOT EXISTS SFMC_CRM_JOURNEY_EMAIL_ACTIVITY (
	ACCOUNTID VARCHAR(16777216),
	OYBACCOUNTID VARCHAR(16777216),
	JOBID VARCHAR(16777216),
	VERSIONID VARCHAR(16777216),
	ACTIVITYID VARCHAR(16777216),
	ACTIVITYNAME VARCHAR(16777216),
	ACTIVITYEXTERNALKEY VARCHAR(16777216),
	JOURNEYACTIVITYOBJECTID VARCHAR(16777216),
	ACTIVITYTYPE VARCHAR(16777216),
	SOURCE_SYSTEM_NM VARCHAR(255),
	BRAND_ID VARCHAR(255),
	LOAD_ID NUMBER(38,0),
	LOAD_DTTM TIMESTAMP_NTZ(9),
	UPDATE_ID NUMBER(38,0),
	UPDATE_DTTM TIMESTAMP_NTZ(9),
	LOAD_FILENAME VARCHAR(16777216)
);
create TABLE IF NOT EXISTS SFMC_CRM_NOT_SENT (
	CLIENTID VARCHAR(16777216),
	SENDID VARCHAR(16777216),
	SUBSCRIBERKEY VARCHAR(16777216),
	EMAILADDRESS VARCHAR(16777216),
	SUBSCRIBERID VARCHAR(16777216),
	LISTID VARCHAR(16777216),
	EVENTDATE VARCHAR(16777216),
	EVENTTYPE VARCHAR(16777216),
	BATCHID VARCHAR(16777216),
	TRIGGEREDSENDEXTERNALKEY VARCHAR(16777216),
	REASON VARCHAR(16777216),
	SOURCE_SYSTEM_NM VARCHAR(255),
	BRAND_ID VARCHAR(255),
	LOAD_ID NUMBER(38,0),
	LOAD_DTTM TIMESTAMP_NTZ(9),
	UPDATE_ID NUMBER(38,0),
	UPDATE_DTTM TIMESTAMP_NTZ(9),
	LOAD_FILENAME VARCHAR(16777216)
);
create TABLE IF NOT EXISTS SFMC_CRM_OPEN (
	CLIENTID VARCHAR(16777216),
	SENDID VARCHAR(16777216),
	SUBSCRIBERKEY VARCHAR(16777216),
	EMAILADDRESS VARCHAR(16777216),
	SUBSCRIBERID VARCHAR(16777216),
	LISTID VARCHAR(16777216),
	EVENTDATE VARCHAR(16777216),
	EVENTTYPE VARCHAR(16777216),
	BATCHID VARCHAR(16777216),
	TRIGGEREDSENDEXTERNALKEY VARCHAR(16777216),
	ISUNIQUE VARCHAR(16777216),
	MESSAGE_ID VARCHAR(16777216),
	SERVICE_TRANSACTION_ID VARCHAR(16777216),
	BRAND_ID VARCHAR(255),
	SOURCE_SYSTEM_NM VARCHAR(255),
	LOAD_ID NUMBER(38,0),
	LOAD_DTTM TIMESTAMP_NTZ(9),
	UPDATE_ID NUMBER(38,0),
	UPDATE_DTTM TIMESTAMP_NTZ(9),
	LOAD_FILENAME VARCHAR(16777216)
);
create TABLE IF NOT EXISTS SFMC_CRM_PUSH_MESSAGE_DETAIL (
	DATE VARCHAR(16777216),
	CLIENTID VARCHAR(16777216),
	EID VARCHAR(16777216),
	APPNAME VARCHAR(16777216),
	MESSAGENAME VARCHAR(16777216),
	MESSAGEID VARCHAR(16777216),
	TEMPLATE VARCHAR(16777216),
	FORMAT VARCHAR(16777216),
	GEOFENCENAME VARCHAR(16777216),
	PAGENAME VARCHAR(16777216),
	CAMPAIGNS VARCHAR(16777216),
	DATETIMESEND VARCHAR(16777216),
	MESSAGECONTENT VARCHAR(16777216),
	MESSAGEOPENED VARCHAR(16777216),
	TIMEINAPP VARCHAR(16777216),
	PLATFORM VARCHAR(16777216),
	PLATFORMVERSION VARCHAR(16777216),
	STATUS VARCHAR(16777216),
	PUSHJOBID VARCHAR(16777216),
	SYSTEMTOKEN VARCHAR(16777216),
	INBOXDOWNLOAD VARCHAR(16777216),
	INBOXOPEN VARCHAR(16777216),
	REQUESTID VARCHAR(16777216),
	OPENDATE VARCHAR(16777216),
	SERVICERESPONSE VARCHAR(16777216),
	IOSMEDIAURL VARCHAR(16777216),
	ANDROIDMEDIAURL VARCHAR(16777216),
	MEDIAALT VARCHAR(16777216),
	DEVICEID VARCHAR(16777216),
	CONTACTKEY VARCHAR(16777216),
	SOURCE_SYSTEM_NM VARCHAR(255),
	BRAND_ID VARCHAR(255),
	LOAD_ID NUMBER(38,0),
	LOAD_DTTM TIMESTAMP_NTZ(9),
	UPDATE_ID NUMBER(38,0),
	UPDATE_DTTM TIMESTAMP_NTZ(9),
	LOAD_FILENAME VARCHAR(16777216)
);
create TABLE IF NOT EXISTS SFMC_CRM_PUSH_SEND_LOG (
	PUSHJOBID VARCHAR(16777216),
	PUSHTRIGGEREDSENDREQUESTID VARCHAR(16777216),
	PUSHBATCHID VARCHAR(16777216),
	SUBID VARCHAR(16777216),
	DEVICEID VARCHAR(16777216),
	APPID VARCHAR(16777216),
	LOGDATE VARCHAR(16777216),
	SOURCE_SYSTEM_NM VARCHAR(255),
	BRAND_ID VARCHAR(255),
	LOAD_ID NUMBER(38,0),
	LOAD_DTTM TIMESTAMP_NTZ(9),
	UPDATE_ID NUMBER(38,0),
	UPDATE_DTTM TIMESTAMP_NTZ(9),
	LOAD_FILENAME VARCHAR(16777216)
);
create TABLE IF NOT EXISTS SFMC_CRM_SEND_JOB (
	CLIENTID VARCHAR(16777216),
	SENDID VARCHAR(16777216),
	FROMNAME VARCHAR(16777216),
	FROMEMAIL VARCHAR(16777216),
	SCHEDTIME TIMESTAMP_NTZ(9),
	SUBJECT VARCHAR(16777216),
	EMAILNAME VARCHAR(16777216),
	TRIGGEREDSENDEXTERNALKEY VARCHAR(16777216),
	SENDDEFINITIONEXTERNALKEY VARCHAR(16777216),
	JOBSTATUS VARCHAR(16777216),
	PREVIEWURL VARCHAR(16777216),
	ISMULTIPART VARCHAR(16777216),
	ADDITIONAL VARCHAR(16777216),
	MESSAGE_ID VARCHAR(16777216),
	SOURCE_SYSTEM_NM VARCHAR(255),
	BRAND_ID VARCHAR(255),
	LOAD_ID NUMBER(38,0),
	LOAD_DTTM TIMESTAMP_NTZ(9),
	UPDATE_ID NUMBER(38,0),
	UPDATE_DTTM TIMESTAMP_NTZ(9),
	LOAD_FILENAME VARCHAR(16777216)
);
create TABLE IF NOT EXISTS SFMC_CRM_SEND_JOB_RAW_TEMP (
	CLIENTID VARCHAR(16777216),
	SENDID VARCHAR(16777216),
	FROMNAME VARCHAR(16777216),
	FROMEMAIL VARCHAR(16777216),
	SCHEDTIME VARCHAR(16777216),
	SENTTIME VARCHAR(16777216),
	SUBJECT VARCHAR(16777216),
	EMAILNAME VARCHAR(16777216),
	TRIGGEREDSENDEXTERNALKEY VARCHAR(16777216),
	SENDDEFINITIONEXTERNALKEY VARCHAR(16777216),
	JOBSTATUS VARCHAR(16777216),
	PREVIEWURL VARCHAR(16777216),
	ISMULTIPART VARCHAR(16777216),
	ADDITIONAL VARCHAR(16777216),
	MESSAGE_ID VARCHAR(16777216),
	SOURCE_SYSTEM_NM VARCHAR(255),
	BRAND_ID VARCHAR(255),
	LOAD_ID NUMBER(38,0),
	LOAD_DTTM TIMESTAMP_NTZ(9),
	UPDATE_ID NUMBER(38,0),
	UPDATE_DTTM TIMESTAMP_NTZ(9),
	LOAD_FILENAME VARCHAR(16777216)
);
create TABLE IF NOT EXISTS SFMC_CRM_SEND_LOG (
	JOBID VARCHAR(16777216),
	LISTID VARCHAR(16777216),
	BATCHID VARCHAR(16777216),
	SUBID VARCHAR(16777216),
	TRIGGEREDSENDID VARCHAR(16777216),
	ERRORCODE_ VARCHAR(16777216),
	DATE VARCHAR(16777216),
	CUSTOMER_ID VARCHAR(16777216),
	SUBSCRIBERKEY VARCHAR(16777216),
	DATASOURCENAME VARCHAR(16777216),
	EMAILADDR VARCHAR(16777216),
	OFFER_CODE VARCHAR(16777216),
	OFFER_NAME VARCHAR(16777216),
	PARENTOFFERID VARCHAR(16777216),
	JOURNEYNAME VARCHAR(16777216),
	JOURNEYSTEP VARCHAR(16777216),
	SOC VARCHAR(16777216),
	USER_DEFINED_SEGMENT1 VARCHAR(16777216),
	USER_DEFINED_SEGMENT2 VARCHAR(16777216),
	USER_DEFINED_SEGMENT3 VARCHAR(16777216),
	USER_DEFINED_SEGMENT4 VARCHAR(16777216),
	USER_DEFINED_SEGMENT5 VARCHAR(16777216),
	OFFER1DECISIONLOGIC VARCHAR(16777216),
	EMAILNAME VARCHAR(16777216),
	CREATIVE_VARIANT VARCHAR(16777216),
	CAMPAIGN_ID VARCHAR(16777216),
	CAMPAIGN_NAME VARCHAR(16777216),
	CAMPAIGN_TYPE VARCHAR(16777216),
	CAMPAIGN_CATEGORY VARCHAR(16777216),
	CAMPAIGN_DESCRIPTION VARCHAR(16777216),
	CAMPAIGN_OBJECTIVE VARCHAR(16777216),
	CAMPAIGN_START_DATE VARCHAR(16777216),
	CAMPAIGN_END_DATE VARCHAR(16777216),
	CAMPAIGN_DURATION VARCHAR(16777216),
	POINTBALANCE VARCHAR(16777216),
	MEMBERID VARCHAR(16777216),
	SOURCE_SYSTEM_NM VARCHAR(255),
	BRAND_ID VARCHAR(255),
	LOAD_ID NUMBER(38,0),
	LOAD_DTTM TIMESTAMP_NTZ(9),
	UPDATE_ID NUMBER(38,0),
	UPDATE_DTTM TIMESTAMP_NTZ(9),
	LOAD_FILENAME VARCHAR(16777216)
);
create TABLE IF NOT EXISTS SFMC_CRM_SENT (
	CLIENTID VARCHAR(16777216),
	SENDID VARCHAR(16777216),
	SUBSCRIBERKEY VARCHAR(16777216),
	EMAILADDRESS VARCHAR(16777216),
	SUBSCRIBERID VARCHAR(16777216),
	LISTID VARCHAR(16777216),
	EVENTDATE VARCHAR(16777216),
	EVENTTYPE VARCHAR(16777216),
	BATCHID VARCHAR(16777216),
	TRIGGEREDSENDEXTERNALKEY VARCHAR(16777216),
	SOURCE_SYSTEM_NM VARCHAR(255),
	BRAND_ID VARCHAR(255),
	LOAD_ID NUMBER(38,0),
	LOAD_DTTM TIMESTAMP_NTZ(9),
	UPDATE_ID NUMBER(38,0),
	UPDATE_DTTM TIMESTAMP_NTZ(9),
	LOAD_FILENAME VARCHAR(16777216)
);
create TABLE IF NOT EXISTS SFMC_CRM_STATUSCHANGE (
	CLIENTID VARCHAR(16777216),
	SUBSCRIBERKEY VARCHAR(16777216),
	EMAILADDRESS VARCHAR(16777216),
	SUBSCRIBERID VARCHAR(16777216),
	OLDSTATUS VARCHAR(16777216),
	NEWSTATUS VARCHAR(16777216),
	DATECHANGED VARCHAR(16777216),
	SOURCE_SYSTEM_NM VARCHAR(255),
	BRAND_ID VARCHAR(255),
	LOAD_ID NUMBER(38,0),
	LOAD_DTTM TIMESTAMP_NTZ(9),
	UPDATE_ID NUMBER(38,0),
	UPDATE_DTTM TIMESTAMP_NTZ(9),
	LOAD_FILENAME VARCHAR(16777216)
);
create TABLE IF NOT EXISTS SFMC_CRM_UNSUBSCRIBE (
	FOLDERNAME_M VARCHAR(16777216),
	CLIENTID VARCHAR(16777216),
	SENDID VARCHAR(16777216),
	SUBSCRIBERKEY VARCHAR(16777216),
	EMAILADDRESS VARCHAR(16777216),
	SUBSCRIBERID VARCHAR(16777216),
	LISTID VARCHAR(16777216),
	EVENTDATE VARCHAR(16777216),
	EVENTTYPE VARCHAR(16777216),
	BATCHID VARCHAR(16777216),
	TRIGGEREDSENDEXTERNALKEY VARCHAR(16777216),
	SERVICE_TRANSACTION_ID VARCHAR(16777216),
	SOURCE_SYSTEM_NM VARCHAR(255),
	BRAND_ID VARCHAR(255),
	LOAD_ID NUMBER(38,0),
	LOAD_DTTM TIMESTAMP_NTZ(9),
	UPDATE_ID NUMBER(38,0),
	UPDATE_DTTM TIMESTAMP_NTZ(9),
	LOAD_FILENAME VARCHAR(16777216)
);
create TABLE IF NOT EXISTS TEST_BATCH_AUDIT (
	LOAD_ID VARCHAR(50) NOT NULL,
	BATCH_ID NUMBER(38,0) NOT NULL,
	STATUS VARCHAR(16777216) NOT NULL,
	START_TIME TIMESTAMP_NTZ(9) NOT NULL,
	END_TIME TIMESTAMP_NTZ(9),
	FAILURE_MSG VARCHAR(16777216),
	USERNAME VARCHAR(16777216) NOT NULL,
	BUSINESS_DATE DATE
);
create TABLE IF NOT EXISTS TEST_BATCH_CONTROL_RUN (
	BATCH_CONTROL_RUN_ID NUMBER(38,0),
	BATCH_START_TS TIMESTAMP_NTZ(9),
	BATCH_END_TS TIMESTAMP_NTZ(9),
	ELAPSED_TIME VARCHAR(16777216),
	BATCH_CURR_IND VARCHAR(16777216),
	BATCH_STTS VARCHAR(16777216),
	BATCH_FAILURE_BYPASS_IND VARCHAR(16777216),
	BATCH_FAILURE_BYPASS_USER VARCHAR(16777216),
	BATCH_FAILURE_BYPASS_TS VARCHAR(16777216),
	BATCH_ERROR_MSG VARCHAR(16777216),
	BATCH_LOG_LOCN VARCHAR(16777216),
	INSERT_USER VARCHAR(16777216),
	INSERT_TS TIMESTAMP_NTZ(9),
	UPDT_USER VARCHAR(16777216),
	UPDT_TS VARCHAR(16777216)
);
create TABLE IF NOT EXISTS TEST_BATCH_CONTROL_RUN_UNUSED (
	LOAD_ID VARCHAR(50) NOT NULL,
	BATCH_ID NUMBER(38,0) NOT NULL,
	STATUS VARCHAR(16777216) NOT NULL,
	START_TIME TIMESTAMP_NTZ(9) NOT NULL,
	END_TIME TIMESTAMP_NTZ(9),
	FAILURE_MSG VARCHAR(16777216),
	USERNAME VARCHAR(16777216) NOT NULL,
	BUSINESS_DATE DATE
);
create TABLE IF NOT EXISTS TEST_BATCH_CONTROL_SEED (
	BATCH_CONTROL_ID NUMBER(38,0) autoincrement,
	BATCH_CONTROL_NM VARCHAR(16777216),
	PARENT_BATCH_CONTROL_ID NUMBER(38,0),
	INSRT_USER VARCHAR(16777216),
	INSRT_TS TIMESTAMP_NTZ(9),
	UPDT_USER VARCHAR(16777216),
	UPDT_TS TIMESTAMP_NTZ(9)
);
create TABLE IF NOT EXISTS TEST_GRANTS_PRIVELEGES (
	CUSTOMERKEY VARCHAR(16777216),
	EMAILADDRESS VARCHAR(16777216),
	EMAILCHANNELOPTOUTFLAG VARCHAR(16777216),
	EMAILCHANNELOPTSTATUSDATE VARCHAR(16777216),
	EMAILCHANNELOPTSTATUSSOURCE VARCHAR(16777216),
	SOURCE_SYSTEM_NM VARCHAR(255),
	BRAND_ID VARCHAR(255),
	LOAD_ID NUMBER(38,0),
	LOAD_DTTM TIMESTAMP_NTZ(9),
	UPDATE_ID NUMBER(38,0),
	UPDATE_DTTM TIMESTAMP_NTZ(9),
	LOAD_FILENAME VARCHAR(16777216)
);
create TABLE IF NOT EXISTS TEST_JOB_CONTROL_RUN (
	JOB_CONTROL_RUN_ID VARCHAR(16777216),
	BATCH_CONTROL_RUN_ID NUMBER(38,0),
	JOB_CONTROL_ID NUMBER(38,0),
	JOB_START_TS TIMESTAMP_NTZ(9),
	JOB_END_TS TIMESTAMP_NTZ(9),
	JOB_SELECTION_START_TS TIMESTAMP_NTZ(9),
	JOB_SELECTION_END_TS TIMESTAMP_NTZ(9),
	JOB_STTS VARCHAR(16777216),
	JOB_CURR_ID VARCHAR(16777216),
	JOB_REC_READ_CNT NUMBER(38,0),
	JOB_REC_PRCSD_CNT NUMBER(38,0),
	JOB_REC_UPDT_CNT NUMBER(38,0),
	JOB_REC_DELETE_CNT NUMBER(38,0),
	JOB_REC_ERROR_CNT NUMBER(38,0),
	JOB_ERROR_CODE VARCHAR(16777216),
	JOB_ERROR_DTLS VARCHAR(16777216),
	JOB_LOG_LOCN VARCHAR(16777216),
	INSRT_USER VARCHAR(16777216),
	INSRT_TS TIMESTAMP_NTZ(9),
	UPDT_USER VARCHAR(16777216),
	UPDT_TS TIMESTAMP_NTZ(9)
);
create TABLE IF NOT EXISTS TEST_JOB_CONTROL_SEED (
	JOB_CONTROL_ID NUMBER(38,0) autoincrement,
	JOB_CONTROL_NM VARCHAR(16777216),
	JOB_DEST_GRP_ID NUMBER(38,0),
	JOB_SRC_GRP_ID NUMBER(38,0),
	BATCH_CONTROL_ID NUMBER(38,0),
	IGNORE_1 BOOLEAN,
	IGNORE_2 BOOLEAN,
	JOB_CONTROL_DESC VARCHAR(16777216),
	JOB_TYPE VARCHAR(16777216),
	CDC_IND VARCHAR(16777216),
	INITIAL_LOAD_IND VARCHAR(16777216),
	TRUNCATE_DEST_IND VARCHAR(16777216),
	IGNORE_JOB_RUN_IND VARCHAR(16777216),
	JOB_FREQUENCY NUMBER(38,0),
	INTRADAY_FREQUENCY NUMBER(38,0),
	ROLLING_PERIOD NUMBER(38,0),
	WEEK_DAY NUMBER(38,0),
	MONTH_DAY NUMBER(38,0),
	SCHEDULE_TIME VARCHAR(16777216),
	SCHEDULE_TIME_ZONE VARCHAR(16777216),
	INSRT_USER VARCHAR(16777216),
	INSRT_TS TIMESTAMP_NTZ(9),
	UPDT_USER VARCHAR(16777216),
	UPDT_TS TIMESTAMP_NTZ(9)
);
create TABLE IF NOT EXISTS TEST_JOB_DEST_GRP_SEED (
	JOB_DEST_GRP_ID NUMBER(38,0) autoincrement,
	JOB_DEST_GRP_NM VARCHAR(16777216),
	LOC_ID VARCHAR(16777216),
	INSRT_USER VARCHAR(16777216),
	INSRT_TS TIMESTAMP_NTZ(9),
	UPDT_USER VARCHAR(16777216),
	UPDT_TS TIMESTAMP_NTZ(9)
);
create TABLE IF NOT EXISTS TEST_JOB_SRC_GRP_SEED (
	JOB_SRC_GRP_ID NUMBER(38,0) autoincrement,
	JOB_SRC_GRP_NM VARCHAR(16777216),
	LOC_ID VARCHAR(16777216),
	INSRT_USER VARCHAR(16777216),
	INSRT_TS TIMESTAMP_NTZ(9),
	UPDT_USER VARCHAR(16777216),
	UPDT_TS TIMESTAMP_NTZ(9)
);
create TABLE IF NOT EXISTS TEST_LOC_SEED (
	LOC_ID NUMBER(38,0) autoincrement,
	LOC_NM VARCHAR(16777216),
	SEG_NM VARCHAR(16777216),
	SUB_SEG_NM VARCHAR(16777216),
	LOC_TYPE VARCHAR(16777216),
	LOC_LOAD_TYPE VARCHAR(16777216),
	FILE_LOC_NM VARCHAR(16777216),
	FILE_FRMT_TYPE VARCHAR(16777216),
	DB_TYPE VARCHAR(16777216),
	INSRT_USER VARCHAR(16777216),
	INSRT_TS TIMESTAMP_NTZ(9),
	UPDT_USER VARCHAR(16777216),
	UPDT_TS TIMESTAMP_NTZ(9)
);
create TABLE IF NOT EXISTS TEST_LOGGING_RAW (
	TEST1 VARCHAR(16777216),
	TEST2 VARCHAR(16777216),
	TEST3 VARCHAR(16777216)
);
create TABLE IF NOT EXISTS TEST_PARENT_BATCH_CONTROL_RUN (
	LOAD_ID VARCHAR(50) NOT NULL,
	BATCH_ID NUMBER(38,0) NOT NULL,
	STATUS VARCHAR(16777216) NOT NULL,
	START_TIME TIMESTAMP_NTZ(9) NOT NULL,
	END_TIME TIMESTAMP_NTZ(9),
	FAILURE_MSG VARCHAR(16777216),
	USERNAME VARCHAR(16777216) NOT NULL,
	BUSINESS_DATE DATE
);
create TABLE IF NOT EXISTS TEST_PARENT_BATCH_CONTROL_SEED (
	PARENT_BATCH_CONTROL_ID NUMBER(38,0) autoincrement,
	PARENT_BATCH_CONTROL_NM VARCHAR(16777216),
	INSRT_USER VARCHAR(16777216),
	INSRT_TS TIMESTAMP_NTZ(9),
	UPDT_USER VARCHAR(16777216),
	UPDT_TS TIMESTAMP_NTZ(9)
);
create TABLE IF NOT EXISTS TEST_SNOWFLAKE_LOGGING (
	ENTITY_ID NUMBER(38,0) NOT NULL autoincrement,
	QUERY_ID VARCHAR(16777216),
	LOAD_ID VARCHAR(50) NOT NULL,
	ENTITY_NAME VARCHAR(16777216) NOT NULL,
	START_TIME TIMESTAMP_NTZ(9) NOT NULL,
	END_TIME TIMESTAMP_NTZ(9),
	BUSINESS_DATE DATE,
	ROW_INSERTED NUMBER(38,0),
	ROW_MODIFIED NUMBER(38,0),
	ROW_DELETED NUMBER(38,0),
	EXECUTION_STATUS VARCHAR(50),
	ERROR_CODE NUMBER(38,0),
	ERROR_MESSAGE VARCHAR(16777216),
	BYTES_SCANNED NUMBER(38,0),
	COMPILATION_TIME NUMBER(38,0),
	EXECUTION_TIME NUMBER(38,0),
	CREDITS_USED_CLOUD_SERVICES FLOAT,
	primary key (ENTITY_ID)
);
create TABLE IF NOT EXISTS TEST_SNOWFLAKE_LOGGING_ADDITIONAL_COLUMNS (
	JOB_CONTROL_RUN_ID VARCHAR(16777216),
	BATCH_CONTROL_RUN_ID VARCHAR(16777216),
	JOB_CONTROL_ID VARCHAR(16777216),
	JOB_START_TS VARCHAR(16777216),
	JOB_END_TS VARCHAR(16777216),
	JOB_SELECTION_START_TS VARCHAR(16777216),
	JOB_SELECTION_END_TS VARCHAR(16777216),
	JOB_STTS VARCHAR(16777216),
	JOB_CURR_ID VARCHAR(16777216),
	JOB_REC_READ_CNT VARCHAR(16777216),
	JOB_REC_PRCSD_CNT VARCHAR(16777216),
	JOB_REC_UPDT_CNT VARCHAR(16777216),
	JOB_REC_DELETE_CNT VARCHAR(16777216),
	JOB_REC_ERROR_CNT VARCHAR(16777216),
	JOB_ERROR_CODE VARCHAR(16777216),
	JOB_ERROR_DTLS VARCHAR(16777216),
	JOB_LOG_LOCN VARCHAR(16777216),
	INSRT_USER VARCHAR(16777216),
	INSRT_TS VARCHAR(16777216),
	UPDT_USER VARCHAR(16777216),
	UPDT_TS VARCHAR(16777216)
);
create TABLE IF NOT EXISTS TEST_TABLE (
	ID NUMBER(38,0),
	NAME VARCHAR(16777216)
);
create TABLE IF NOT EXISTS XML_INGEST (
	XMLDATA VARIANT
);
create TABLE IF NOT EXISTS ZIP_TO_DMA_REF (
	BRAND_ID VARCHAR(16777216) NOT NULL,
	ZIP_CD VARCHAR(20) NOT NULL DEFAULT ' ',
	CITY_NM VARCHAR(255),
	STATE_CD VARCHAR(3),
	CNTRY_CD VARCHAR(3),
	DMA_CD VARCHAR(10),
	ZIP_DMA_NM VARCHAR(50),
	SOURCE_SYSTEM_NM VARCHAR(255) NOT NULL,
	LOAD_ID NUMBER(38,0),
	LOAD_DTTM TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
	UPDATE_ID NUMBER(38,0),
	UPDATE_DTTM TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP()
)COMMENT='ZIPCODE to DMA reference Dunkin - SCOTT MCENTIRE'
;
create view IF NOT EXISTS EPS_CRM_OPTOUT_RAW_BV(
	CUSTOMERKEY,
	EMAILADDRESS,
	LOAD_ID
) as 
SELECT CUSTOMERKEY,EMAILADDRESS,TO_VARCHAR(LOAD_ID) FROM EPS_CRM_OPTOUT_RAW LIMIT 10;
CREATE FILE FORMAT IF NOT EXISTS CSVFORMAT
	TYPE = csv
	SKIP_HEADER = 1
	REPLACE_INVALID_CHARACTERS = TRUE
;
CREATE FILE FORMAT IF NOT EXISTS DIGITAL_COMMA_DELIMITED_CSV_FILE_FORMAT
	SKIP_HEADER = 1
	TRIM_SPACE = TRUE
	SKIP_BLANK_LINES = TRUE
	REPLACE_INVALID_CHARACTERS = TRUE
;
CREATE FILE FORMAT IF NOT EXISTS DIGITAL_PIPE_DELIMITED_CSV_FILE_FORMAT
	FIELD_DELIMITER = '|'
	SKIP_HEADER = 1
	TRIM_SPACE = TRUE
	SKIP_BLANK_LINES = TRUE
	REPLACE_INVALID_CHARACTERS = TRUE
;
CREATE FILE FORMAT IF NOT EXISTS DNKN_CSV_FORMAT
	FIELD_DELIMITER = '|'
	SKIP_HEADER = 1
	FIELD_OPTIONALLY_ENCLOSED_BY = '\"'
;
CREATE FILE FORMAT IF NOT EXISTS ODI_XML_FORMAT
	TYPE = XML
	STRIP_OUTER_ELEMENT = TRUE
;
CREATE PROCEDURE IF NOT EXISTS ADF_UPDATE_LOG("FILENAME" VARCHAR(16777216), "DATESTART" VARCHAR(16777216), "STATUS" VARCHAR(16777216), "ID" FLOAT, "DATAREAD" FLOAT, "ROWSREAD" FLOAT, "ROWSCOPIED" FLOAT, "FILESWRITTEN" FLOAT, "COPYDURATION" FLOAT, "DATEEND" VARCHAR(16777216))
RETURNS VARCHAR(16777216)
LANGUAGE JAVASCRIPT
STRICT
EXECUTE AS CALLER
AS '
    var resultSet = snowflake.createStatement( {sqlText: "SELECT ''" + DATESTART + "''::TIMESTAMP_LTZ;"} ).execute(); 
    resultSet.next(); 
    var date_start = resultSet.getColumnValue(1); 
    
    var resultSet = snowflake.createStatement( {sqlText: "SELECT ''" + DATEEND + "''::TIMESTAMP_LTZ;"} ).execute(); 
    resultSet.next(); 
    var date_end = resultSet.getColumnValue(1); 
    
    var sql_command = `MERGE INTO ADF_LOGGING target
    USING (
        SELECT id, filename, dateStart, status, dataRead, rowsRead, rowsCopied, filesWritten, copyDuration, dateEnd 
        FROM (VALUES (`+ID + `, ''` + FILENAME + `'', ''` + DATESTART + `'', ''` + STATUS + `'', ` + DATAREAD + `, ` + ROWSREAD + `, ` + ROWSCOPIED + `, ` + FILESWRITTEN + `, ` + COPYDURATION + `, ''` + DATEEND + `'')) t
            (id, filename, dateStart, status, dataRead, rowsRead, rowsCopied, filesWritten, copyDuration, dateEnd ) 
    ) source
    ON source.id = target.id
    WHEN MATCHED THEN UPDATE SET target.filename=source.filename, target.dateStart=source.dateStart, target.status=source.status, target.dataRead=source.dataRead, target.rowsRead=source.rowsRead, 
        target.rowsCopied=source.rowsCopied, target.filesWritten=source.filesWritten, target.copyDuration=source.copyDuration, target.dateEnd=source.dateEnd
    WHEN NOT MATCHED THEN INSERT (filename, dateStart, status) 
        VALUES (source.filename, source.dateStart, source.status)
    `;
    
    var sql_command2 = "set qid = last_query_id()";
    var sql_command3 = "select max(ID) as ID from ADF_LOGGING AT(statement=>$qid)";
    
    try {
    
        snowflake.execute ({sqlText: sql_command}); 
        snowflake.execute ({sqlText: sql_command2}); 
    
        resultSet = snowflake.execute (
            {sqlText: sql_command3}
            ); 
        resultSet.next(); 
        
        var last_id = parseInt(resultSet.getColumnValue(1)); 
        return last_id;
        }
    catch (err)  {
        return err;   // Return a success/error indicator.
        }
';
CREATE PROCEDURE IF NOT EXISTS COPYINTOWITHREPROCESSING("STAGEDATABASE" VARCHAR(16777216), "STAGESCHEMA" VARCHAR(16777216), "STAGENAME" VARCHAR(16777216), "RAWTABLEDATABASE" VARCHAR(16777216), "RAWTABLESCHEMA" VARCHAR(16777216), "RAWTABLENAME" VARCHAR(16777216), "SOURCEFILENAME" VARCHAR(16777216), "COPYQUERY" VARCHAR(16777216), "EXECUTION_TIMESTAMP" VARCHAR(16777216))
RETURNS VARIANT
LANGUAGE JAVASCRIPT
EXECUTE AS CALLER
AS '
    var log_msg = "";

    let stage_count = 0;
    let raw_table_count = 0;

    try {  
        // execute COPY INTO
        var copy_into_statement = snowflake.createStatement({
            sqlText: COPYQUERY
            });
        copy_into_statement.execute();

        // Get stage count
        var stage_count_statement = snowflake.createStatement({
            sqlText: `SELECT count(*) FROM @${STAGEDATABASE}.${STAGESCHEMA}.${STAGENAME};`
            });
        var stage_count_result = stage_count_statement.execute();
        stage_count_result.next();
        stage_count = stage_count_result.getColumnValue(1);

        // Get raw table count
        var raw_table_count_statement = snowflake.createStatement({
            sqlText: `SELECT count(*) FROM ${RAWTABLEDATABASE}.${RAWTABLESCHEMA}.${RAWTABLENAME}
            WHERE (SPLIT_PART(LOAD_FILENAME, ''/'', -1)) = ''${SOURCEFILENAME}''
            AND LOAD_DTTM = TO_TIMESTAMP_NTZ(''${EXECUTION_TIMESTAMP}'');`
            });
        var raw_table_count_result = raw_table_count_statement.execute();
        raw_table_count_result.next();
        raw_table_count = raw_table_count_result.getColumnValue(1);

        // Log counts
        log_msg += "\\nStage count: " + stage_count;
        log_msg += "\\nRaw table count: " + raw_table_count;

        // Build COPY INTO with FORCE
        var copy_into_force_statement = snowflake.createStatement({
            sqlText: COPYQUERY.slice(0, -1) + `,\\nFORCE = TRUE;`
            });

        // Build DELETE FROM statement
        var truncate_raw_table_statement = snowflake.createStatement({
            sqlText: `DELETE FROM  ${RAWTABLEDATABASE}.${RAWTABLESCHEMA}.${RAWTABLENAME} 
            WHERE (SPLIT_PART(LOAD_FILENAME, ''/'', -1)) = ''${SOURCEFILENAME}''
            AND LOAD_DTTM = TO_TIMESTAMP_NTZ(''${EXECUTION_TIMESTAMP}'');`
            });

        // Check possible outcomes of Stage vs Raw table count comparison
        let execution_message = "Something else went wrong when comparing raw table count to stage count";
        
        if (stage_count == raw_table_count){
            execution_message = "\\nCOPY INTO completed properly, continuing...";
        }
        else if (raw_table_count == 0){
            execution_message = "\\nCounts between raw table and stage do not match, forcing COPY INTO..."

            copy_into_force_statement.execute();
        }

        try {
            log_msg += execution_message;
        }
        catch(err) {
            log_msg += "\\nFailed: Code: " + err.code + "\\n  State: " + err.state;
            log_msg += "\\nMessage: " + err.message;
            log_msg += "\\nStack Trace:\\n" + err.stackTraceTxt; 
        } finally {
            log_msg += "\\n Completed"
        }

    } 
    catch(err) {
        log_msg += "\\nFailed: Code: " + err.code + "\\n  State: " + err.state;
        log_msg += "\\n  Message: " + err.message;
        log_msg += "\\nStack Trace:\\n" + err.stackTraceTxt; 

        var current_db_query = snowflake.createStatement( {sqlText: "SELECT CURRENT_DATABASE();"}).execute();
        current_db_query.next();
        current_db = current_db_query.getColumnValue(1);
        
        var current_role_query = snowflake.createStatement( {sqlText: "SELECT current_role();"}).execute();
        current_role_query.next();
        current_role = current_role_query.getColumnValue(1);
        log_msg += "\\nRole:\\n" + current_role; 
    }

    return log_msg;
';
CREATE PROCEDURE IF NOT EXISTS GETQUERYTEXT("TABLE_NAME" VARCHAR(16777216))
RETURNS VARCHAR(16777216)
LANGUAGE JAVASCRIPT
EXECUTE AS OWNER
AS '
    var row_count = 0;
    // Dynamically compose the SQL statement to execute.
    var sqlCommand = "select count(*) as cnt from " + TABLE_NAME;
    // Prepare statement.
    var stmt = snowflake.createStatement({sqlText: sqlCommand});
	var rs = stmt.execute()
    rs.next();
	// get SQL text from Statement
	var queryText = stmt.getSqlText();
    var output = rs.getColumnValue(1);
    return output;
    ';
CREATE PROCEDURE IF NOT EXISTS LOGENTITYOPERATIONWRAPPER("SQLTEXT" VARCHAR(16777216), "BATCH_CONTROL_RUN_ID" VARCHAR(16777216), "JOB_CONTROL_ID" VARCHAR(16777216))
RETURNS VARIANT
LANGUAGE JAVASCRIPT
EXECUTE AS CALLER
AS '
    var log_msg = "";
    var status_message = "";
    var error_dtls = "";
    var query_id = null;
    var row_read = null;
    var row_inserted = null;
    var row_deleted = null;
    var row_modified = null;

    try {
        var insert_entity_audit_statement = snowflake.createStatement({
            sqlText:
                `INSERT INTO RDS_DEV.DNKN.TEST_JOB_CONTROL_RUN
                    (JOB_CONTROL_RUN_ID,BATCH_CONTROL_RUN_ID,JOB_CONTROL_ID,JOB_START_TS,JOB_END_TS,JOB_SELECTION_START_TS,
                    JOB_SELECTION_END_TS,JOB_STTS,JOB_CURR_ID,JOB_REC_READ_CNT,JOB_REC_PRCSD_CNT,JOB_REC_UPDT_CNT,
                    JOB_REC_DELETE_CNT,JOB_REC_ERROR_CNT,JOB_ERROR_CODE,JOB_ERROR_DTLS,JOB_LOG_LOCN,INSRT_USER,INSRT_TS,UPDT_USER,UPDT_TS)
                VALUES (NULL,:1,:2,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL)`,
            binds:[BATCH_CONTROL_RUN_ID,JOB_CONTROL_ID]
            });
        insert_entity_audit_statement.execute();

        // Get exact query_id of the last inserted record
        var get_last_query_id_stmt = snowflake.createStatement({
            sqlText:`select last_query_id();`,
            binds:[insert_entity_audit_statement.getQueryId()]
        });
        var entity_audit_id_result = get_last_query_id_stmt.execute();
        entity_audit_id_result.next();
        var entity_audit_id = entity_audit_id_result.getColumnValue(1);

        var update_query_id = snowflake.createStatement({
                sqlText:
                    `UPDATE RDS_DEV.DNKN.TEST_JOB_CONTROL_RUN
                    SET JOB_CURR_ID= :1
                    WHERE JOB_CURR_ID is NULL`,
                binds:[entity_audit_id]
            });

            update_query_id.execute();

        try {
            var client_statement = snowflake.createStatement({
                sqlText: SQLTEXT,
            });

            log_msg += ''\\nStatement of `client_statement`'';
            log_msg += ''\\n  SqlText = '' + client_statement.getSqlText();

            var client_result = client_statement.execute();

            query_id = client_statement.getQueryId();
            row_inserted = client_statement.getNumRowsInserted();
            row_modified = client_statement.getNumRowsUpdated();
            row_deleted = client_statement.getNumRowsDeleted();
            row_read = client_statement.getNumRowsAffected();

            log_msg += ''\\n  QueryId = '' + query_id;
            log_msg += ''\\n  ColumnCount = '' + client_statement.getColumnCount();
            log_msg += ''\\n  RowCount = '' + client_statement.getRowCount();
            log_msg += ''\\n  NumDuplicateRowsUpdated = '' + client_statement.getNumDuplicateRowsUpdated();
            log_msg += ''\\n  NumRowsAffected = '' + client_statement.getNumRowsAffected();
            log_msg += ''\\n  NumRowsDeleted = '' + row_deleted;
            log_msg += ''\\n  NumRowsInserted = '' + row_inserted;
            log_msg += ''\\n  NumRowsUpdated = '' + row_modified;

            log_msg += ''\\nResultSet of `client_statement`'';
            for (let colIdx = 1; colIdx <= client_statement.getColumnCount(); colIdx++ ) {
                log_msg += ''  |  '' + client_statement.getColumnName(colIdx);
            }
            log_msg += ''  |\\n'';

            limit = 10;
            ind = 0;
            while(client_result.next() && ind < limit) {
                for (let colIdx = 1; colIdx <= client_result.getColumnCount(); colIdx++ ) {
                    log_msg += ''  |  '' + client_result.getColumnValueAsString(colIdx);
                }
                log_msg += ''  |\\n'';
            }
        } catch(err) {
            log_msg += "\\nFailed: Code: " + err.code + "\\n  State: " + err.state;
            log_msg += "\\n  Message: " + err.message;
            log_msg += "\\nStack Trace:\\n" + err.stackTraceTxt;
            
            status_message = "failed";
            error_dtls = err.message + ''\\n'' + err.stackTraceTxt;
        } finally {
            status_message = "success"

            log_msg += status_message;
            log_msg += "\\n";

            var update_entity_audit_stmt = snowflake.createStatement({
                    sqlText:
                        `UPDATE RDS_DEV.DNKN.TEST_JOB_CONTROL_RUN as audit
                        SET JOB_CONTROL_RUN_ID= :6,
                            JOB_START_TS= inf.START_TIME,
                            JOB_END_TS= inf.END_TIME,
                            JOB_SELECTION_START_TS= inf.START_TIME,
                            JOB_SELECTION_END_TS= inf.END_TIME,
                            JOB_STTS= :2,
                            JOB_CURR_ID= :1,
                            JOB_REC_READ_CNT= :3,
                            JOB_REC_PRCSD_CNT= :4,
                            JOB_REC_UPDT_CNT= :5,
                            JOB_REC_DELETE_CNT= :6,
                            JOB_REC_ERROR_CNT= 000000,
                            JOB_ERROR_CODE= inf.ERROR_CODE,
                            JOB_ERROR_DTLS= :7,
                            JOB_LOG_LOCN= ''placeholder'',
                            INSRT_USER= inf.USER_NAME,
                            INSRT_TS= sysdate(),
                            UPDT_USER= inf.USER_NAME,
                            UPDT_TS= sysdate()
                        FROM table(information_schema.QUERY_HISTORY_BY_SESSION()) as inf
                        WHERE audit.job_curr_id= :8`,
                    binds:[query_id,status_message,row_read,row_inserted,row_modified,row_deleted,error_dtls,entity_audit_id]
                });

            update_entity_audit_stmt.execute();
        }

    } catch(err) {
        log_msg += "\\nFailed: Code: " + err.code + "\\n  State: " + err.state;
        log_msg += "\\n  Message: " + err.message;
        log_msg += "\\nStack Trace:\\n" + err.stackTraceTxt;
    }

    return log_msg;
';
CREATE PROCEDURE IF NOT EXISTS LOGENTITYOPERATIONWRAPPER("SQLTEXT" VARCHAR(16777216), "BINDS" ARRAY, "LOADID" VARCHAR(16777216), "ENTITYNAME" VARCHAR(16777216), "BUSINESSDATE" VARCHAR(16777216))
RETURNS VARIANT
LANGUAGE JAVASCRIPT
EXECUTE AS CALLER
AS '
    

    var array_or_rows = [];

var insert_entity_audit_statement = snowflake.createStatement({
        sqlText: `INSERT INTO RDS_DEV.DNKN.TEST_SNOWFLAKE_LOGGING
        (QUERY_ID, LOAD_ID, ENTITY_NAME, START_TIME, END_TIME, BUSINESS_DATE,
        ROW_INSERTED, ROW_MODIFIED,ROW_DELETED, EXECUTION_STATUS, ERROR_CODE,
        ERROR_MESSAGE, BYTES_SCANNED, COMPILATION_TIME, EXECUTION_TIME,CREDITS_USED_CLOUD_SERVICES)
        VALUES (NULL,:1,:2,current_timestamp(),NULL,:3,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL)`,
        binds:[LOADID,ENTITYNAME,BUSINESSDATE]
        });
        
        insert_entity_audit_statement.execute();

        var get_entity_audit_id_stmt = snowflake.createStatement(
        {
            sqlText:`SELECT MAX(ENTITY_ID) FROM RDS_DEV.DNKN.TEST_SNOWFLAKE_LOGGING \\
                    AT(STATEMENT => :1)`,
            binds:[insert_entity_audit_statement.getQueryId()]
        });

        var entity_audit_id_result = get_entity_audit_id_stmt.execute();

        entity_audit_id_result.next();

        var entity_audit_id = entity_audit_id_result.getColumnValue(1);
        
        var client_statement = snowflake.createStatement(
        {
            sqlText: SQLTEXT,
            binds:BINDS
        });

       var row_inserted = null;
       var row_deleted = null;
       var row_modified = null;

    try{
        var client_result = client_statement.execute();
        var column_count = client_statement.getColumnCount();
        while(client_result.next()){
            row_as_json={};
            for (var col_num = 1; col_num < column_count + 1; col_num = col_num + 1) {
                var col_name = client_statement.getColumnName(col_num);
                row_as_json[col_name] = client_result.getColumnValue(col_num);
                switch (col_name) {
                    case ''number of rows inserted'':
                        row_inserted = row_as_json[col_name];
                        break;
                    case ''number of rows deleted'':
                        row_deleted = row_as_json[col_name];
                        break;
                    case ''number of rows updated'':
                        row_modified = row_as_json[col_name];
                        break;
                }
            }
            array_or_rows.push(row_as_json);
        }
        return array_or_rows;
    }finally{
        var query_id = client_statement.getQueryId();
        
         var update_entity_audit_stmt = snowflake.createStatement(
            {
                sqlText: 
                `UPDATE RDS_DEV.DNKN.TEST_SNOWFLAKE_LOGGING as audit
                    SET QUERY_ID= :1, START_TIME=inf.START_TIME, END_TIME=inf.END_TIME, ROW_INSERTED= :2, ROW_MODIFIED= :3,
                    ROW_DELETED= :4, EXECUTION_STATUS= inf.EXECUTION_STATUS, ERROR_CODE= inf.ERROR_CODE,
                    BYTES_SCANNED= inf.BYTES_SCANNED, COMPILATION_TIME= inf.COMPILATION_TIME,
                    EXECUTION_TIME= inf.EXECUTION_TIME, CREDITS_USED_CLOUD_SERVICES= inf.CREDITS_USED_CLOUD_SERVICES
                FROM table(information_schema.QUERY_HISTORY_BY_SESSION()) as inf
                WHERE audit.ENTITY_ID= :5 and inf.QUERY_ID= :1`,
                binds:[query_id,row_inserted,row_modified,row_deleted,entity_audit_id]
            });
        update_entity_audit_stmt.execute();
    }
';
CREATE PROCEDURE IF NOT EXISTS LOGENTITYOPERATIONWRAPPER("SQLTEXT" VARCHAR(16777216), "LOADID" VARCHAR(16777216), "ENTITYNAME" VARCHAR(16777216), "BUSINESSDATE" VARCHAR(16777216))
RETURNS VARIANT
LANGUAGE JAVASCRIPT
EXECUTE AS CALLER
AS '
    var log_msg = "";
    var query_id = null;
    var row_inserted = null;
    var row_deleted = null;
    var row_modified = null;

    try {  
        var insert_entity_audit_statement = snowflake.createStatement({
            sqlText: 
                `INSERT INTO TEST_SNOWFLAKE_LOGGING
                    (QUERY_ID, LOAD_ID, ENTITY_NAME, START_TIME, END_TIME, BUSINESS_DATE,
                    ROW_INSERTED, ROW_MODIFIED,ROW_DELETED, EXECUTION_STATUS, ERROR_CODE,
                    ERROR_MESSAGE, BYTES_SCANNED, COMPILATION_TIME, EXECUTION_TIME,CREDITS_USED_CLOUD_SERVICES)
                VALUES (NULL,:1,:2,current_timestamp(),NULL,:3,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL)`,
            binds:[LOADID,ENTITYNAME,BUSINESSDATE]
            });
        insert_entity_audit_statement.execute();

        // Get exact ENTITY_ID of the inserted record
        var get_entity_audit_id_stmt = snowflake.createStatement({
            sqlText:`SELECT MAX(ENTITY_ID) FROM TEST_SNOWFLAKE_LOGGING AT(STATEMENT => :1)`,
            binds:[insert_entity_audit_statement.getQueryId()]
        });
        var entity_audit_id_result = get_entity_audit_id_stmt.execute();
        entity_audit_id_result.next();
        var entity_audit_id = entity_audit_id_result.getColumnValue(1);

        try {
            var client_statement = snowflake.createStatement({
                sqlText: SQLTEXT,
            });

            log_msg += ''\\nStatement of `client_statement`'';
            log_msg += ''\\n  SqlText = '' + client_statement.getSqlText();

            var client_result = client_statement.execute();

            query_id = client_statement.getQueryId();
            row_inserted = client_statement.getNumRowsInserted();
            row_modified = client_statement.getNumRowsUpdated();
            row_deleted = client_statement.getNumRowsDeleted();

            log_msg += ''\\n  QueryId = '' + query_id;
            log_msg += ''\\n  ColumnCount = '' + client_statement.getColumnCount();
            log_msg += ''\\n  RowCount = '' + client_statement.getRowCount();
            log_msg += ''\\n  NumDuplicateRowsUpdated = '' + client_statement.getNumDuplicateRowsUpdated();
            log_msg += ''\\n  NumRowsAffected = '' + client_statement.getNumRowsAffected();
            log_msg += ''\\n  NumRowsDeleted = '' + row_deleted;
            log_msg += ''\\n  NumRowsInserted = '' + row_inserted;
            log_msg += ''\\n  NumRowsUpdated = '' + row_modified;

            log_msg += ''\\nResultSet of `client_statement`'';
            log_msg += "\\n";
            for (let colIdx = 1; colIdx <= client_statement.getColumnCount(); colIdx++ ) {
                log_msg += ''  |  '' + client_statement.getColumnName(colIdx);
            }
            log_msg += ''  |\\n'';

            limit = 10;
            ind = 0;
            while(client_result.next() && ind < limit) {
                for (let colIdx = 1; colIdx <= client_result.getColumnCount(); colIdx++ ) {
                    log_msg += ''  |  '' + client_result.getColumnValueAsString(colIdx);
                }
                log_msg += ''  |\\n'';
            }
        } catch(err) {
            log_msg += "\\nFailed: Code: " + err.code + "\\n  State: " + err.state;
            log_msg += "\\n  Message: " + err.message;
            log_msg += "\\nStack Trace:\\n" + err.stackTraceTxt; 
        } finally {
            
            var update_entity_audit_stmt = snowflake.createStatement({
                    sqlText:
                        `UPDATE TEST_SNOWFLAKE_LOGGING as audit
                        SET QUERY_ID= :1, START_TIME=inf.START_TIME, END_TIME=inf.END_TIME, ROW_INSERTED= :2, ROW_MODIFIED= :3,
                            ROW_DELETED= :4, EXECUTION_STATUS= inf.EXECUTION_STATUS, ERROR_CODE= inf.ERROR_CODE,
                            BYTES_SCANNED= inf.BYTES_SCANNED, COMPILATION_TIME= inf.COMPILATION_TIME,
                            EXECUTION_TIME= inf.EXECUTION_TIME, CREDITS_USED_CLOUD_SERVICES= inf.CREDITS_USED_CLOUD_SERVICES
                        FROM table(information_schema.QUERY_HISTORY_BY_SESSION()) as inf
                        WHERE audit.ENTITY_ID= :5 and inf.QUERY_ID= :1`,
                    binds:[query_id,row_inserted,row_modified,row_deleted,entity_audit_id]
                });
        
            update_entity_audit_stmt.execute();
        }

    } catch(err) {
        log_msg += "\\nFailed: Code: " + err.code + "\\n  State: " + err.state;
        log_msg += "\\n  Message: " + err.message;
        log_msg += "\\nStack Trace:\\n" + err.stackTraceTxt; 
    }

    return log_msg;
';
CREATE PROCEDURE IF NOT EXISTS LOGENTITYOPERATIONWRAPPER("SQLTEXT" VARCHAR(16777216), "LOADID" VARCHAR(16777216), "ENTITYNAME" VARCHAR(16777216), "BUSINESSDATE" VARCHAR(16777216), "DATABASENAME" VARCHAR(16777216))
RETURNS VARIANT
LANGUAGE JAVASCRIPT
EXECUTE AS CALLER
AS '
    var log_msg = "";
    var query_id = null;
    var row_inserted = null;
    var row_deleted = null;
    var row_modified = null;

    try {  
        var insert_entity_audit_statement = snowflake.createStatement({
            sqlText: 
                `INSERT INTO TEST_SNOWFLAKE_LOGGING
                    (QUERY_ID, LOAD_ID, ENTITY_NAME, START_TIME, END_TIME, BUSINESS_DATE,
                    ROW_INSERTED, ROW_MODIFIED,ROW_DELETED, EXECUTION_STATUS, ERROR_CODE,
                    ERROR_MESSAGE, BYTES_SCANNED, COMPILATION_TIME, EXECUTION_TIME,CREDITS_USED_CLOUD_SERVICES)
                VALUES (NULL,:1,:2,current_timestamp(),NULL,:3,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL)`,
            binds:[LOADID,ENTITYNAME,BUSINESSDATE]
            });
        insert_entity_audit_statement.execute();

        // Get exact ENTITY_ID of the inserted record
        var get_entity_audit_id_stmt = snowflake.createStatement({
            sqlText:`SELECT MAX(ENTITY_ID) FROM TEST_SNOWFLAKE_LOGGING AT(STATEMENT => :1)`,
            binds:[insert_entity_audit_statement.getQueryId()]
        });
        var entity_audit_id_result = get_entity_audit_id_stmt.execute();
        entity_audit_id_result.next();
        var entity_audit_id = entity_audit_id_result.getColumnValue(1);

        try {
            var client_statement = snowflake.createStatement({
                sqlText: SQLTEXT,
            });

            log_msg += ''\\nStatement of `client_statement`'';
            log_msg += ''\\n  SqlText = '' + client_statement.getSqlText();

            var client_result = client_statement.execute();

            query_id = client_statement.getQueryId();
            row_inserted = client_statement.getNumRowsInserted();
            row_modified = client_statement.getNumRowsUpdated();
            row_deleted = client_statement.getNumRowsDeleted();

            log_msg += ''\\n  QueryId = '' + query_id;
            log_msg += ''\\n  ColumnCount = '' + client_statement.getColumnCount();
            log_msg += ''\\n  RowCount = '' + client_statement.getRowCount();
            log_msg += ''\\n  NumDuplicateRowsUpdated = '' + client_statement.getNumDuplicateRowsUpdated();
            log_msg += ''\\n  NumRowsAffected = '' + client_statement.getNumRowsAffected();
            log_msg += ''\\n  NumRowsDeleted = '' + row_deleted;
            log_msg += ''\\n  NumRowsInserted = '' + row_inserted;
            log_msg += ''\\n  NumRowsUpdated = '' + row_modified;

            log_msg += ''\\nResultSet of `client_statement`'';
            log_msg += "\\n";
            for (let colIdx = 1; colIdx <= client_statement.getColumnCount(); colIdx++ ) {
                log_msg += ''  |  '' + client_statement.getColumnName(colIdx);
            }
            log_msg += ''  |\\n'';

            limit = 10;
            ind = 0;
            while(client_result.next() && ind < limit) {
                for (let colIdx = 1; colIdx <= client_result.getColumnCount(); colIdx++ ) {
                    log_msg += ''  |  '' + client_result.getColumnValueAsString(colIdx);
                }
                log_msg += ''  |\\n'';
            }
        } catch(err) {
            log_msg += "\\nFailed: Code: " + err.code + "\\n  State: " + err.state;
            log_msg += "\\n  Message: " + err.message;
            log_msg += "\\nStack Trace:\\n" + err.stackTraceTxt; 
        } finally {
            
            var update_entity_audit_stmt = snowflake.createStatement({
                    sqlText:
                        `UPDATE ` +  DATABASENAME + `.DUN.TEST_SNOWFLAKE_LOGGING as audit
                        SET QUERY_ID= :1, START_TIME=inf.START_TIME, END_TIME=inf.END_TIME, ROW_INSERTED= :2, ROW_MODIFIED= :3,
                            ROW_DELETED= :4, EXECUTION_STATUS= inf.EXECUTION_STATUS, ERROR_CODE= inf.ERROR_CODE,
                            BYTES_SCANNED= inf.BYTES_SCANNED, COMPILATION_TIME= inf.COMPILATION_TIME,
                            EXECUTION_TIME= inf.EXECUTION_TIME, CREDITS_USED_CLOUD_SERVICES= inf.CREDITS_USED_CLOUD_SERVICES
                        FROM table(` + DATABASENAME + `.information_schema.QUERY_HISTORY_BY_SESSION()) as inf
                        WHERE audit.ENTITY_ID= :5 and inf.QUERY_ID= :1`,
                    binds:[query_id,row_inserted,row_modified,row_deleted,entity_audit_id]
                });
        
            update_entity_audit_stmt.execute();
        }

    } catch(err) {
        log_msg += "\\nFailed: Code: " + err.code + "\\n  State: " + err.state;
        log_msg += "\\n  Message: " + err.message;
        log_msg += "\\nStack Trace:\\n" + err.stackTraceTxt; 
    }

    return log_msg;
';
CREATE PROCEDURE IF NOT EXISTS LOGENTITYOPERATIONWRAPPER("SQLTEXT" VARCHAR(16777216), "LOADID" VARCHAR(16777216), "ENTITYNAME" VARCHAR(16777216), "BUSINESSDATE" VARCHAR(16777216), "DATABASENAME" VARCHAR(16777216), "SCHEMANAME" VARCHAR(16777216))
RETURNS VARIANT
LANGUAGE JAVASCRIPT
EXECUTE AS CALLER
AS '
    var log_msg = "";
    var query_id = null;
    var row_inserted = null;
    var row_deleted = null;
    var row_modified = null;

    try {  
        var insert_entity_audit_statement = snowflake.createStatement({
            sqlText: 
                `INSERT INTO ` +  DATABASENAME + `.` + SCHEMANAME + `.TEST_SNOWFLAKE_LOGGING(
                    QUERY_ID,
                    LOAD_ID,
                    ENTITY_NAME,
                    START_TIME,
                    END_TIME,
                    BUSINESS_DATE,
                    ROW_INSERTED,
                    ROW_MODIFIED,
                    ROW_DELETED,
                    EXECUTION_STATUS,
                    ERROR_CODE,
                    ERROR_MESSAGE,
                    BYTES_SCANNED,
                    COMPILATION_TIME,
                    EXECUTION_TIME,
                    CREDITS_USED_CLOUD_SERVICES
                )
                VALUES (
                    NULL,
                    :1,
                    :2,
                    CURRENT_TIMESTAMP(),
                    NULL,
                    :3,
                    NULL,
                    NULL,
                    NULL,
                    NULL,
                    NULL,
                    NULL,
                    NULL,
                    NULL,
                    NULL,
                    NULL
                )`,
            binds:[
                LOADID,         // :1
                ENTITYNAME,     // :2
                BUSINESSDATE    // :3
                ]
            });
        insert_entity_audit_statement.execute();

        // Get exact QUERY_ID of the last inserted record
        var get_query_id_stmt = snowflake.createStatement({sqlText:`SELECT LAST_QUERY_ID();`});
        var query_id_result = get_query_id_stmt.execute();
        query_id_result.next();
        var query_id = query_id_result.getColumnValue(1);

        // Update last inserted record with QUERY_ID
        var update_query_id = snowflake.createStatement({
            sqlText:
                `UPDATE ` +  DATABASENAME + `.` + SCHEMANAME + `.TEST_SNOWFLAKE_LOGGING
                SET QUERY_ID= :1
                WHERE QUERY_ID is NULL`,
            binds:[query_id]
        });
        update_query_id.execute();
        
        try {
            var client_statement = snowflake.createStatement({
                sqlText: SQLTEXT,
            });

            log_msg += ''\\nStatement of `client_statement`'';
            log_msg += ''\\n  SqlText = '' + client_statement.getSqlText();

            var client_result = client_statement.execute();

            //query_id = client_statement.getQueryId();
            row_inserted = client_statement.getNumRowsInserted();
            row_modified = client_statement.getNumRowsUpdated();
            row_deleted = client_statement.getNumRowsDeleted();

            log_msg += ''\\n  QueryId = '' + query_id;
            log_msg += ''\\n  ColumnCount = '' + client_statement.getColumnCount();
            log_msg += ''\\n  RowCount = '' + client_statement.getRowCount();
            log_msg += ''\\n  NumDuplicateRowsUpdated = '' + client_statement.getNumDuplicateRowsUpdated();
            log_msg += ''\\n  NumRowsAffected = '' + client_statement.getNumRowsAffected();
            log_msg += ''\\n  NumRowsDeleted = '' + row_deleted;
            log_msg += ''\\n  NumRowsInserted = '' + row_inserted;
            log_msg += ''\\n  NumRowsUpdated = '' + row_modified;

            log_msg += ''\\nResultSet of `client_statement`'';
            log_msg += "\\n";
            for (let colIdx = 1; colIdx <= client_statement.getColumnCount(); colIdx++ ) {
                log_msg += ''  |  '' + client_statement.getColumnName(colIdx);
            }
            log_msg += ''  |\\n'';

            limit = 10;
            ind = 0;
            while(client_result.next() && ind < limit) {
                for (let colIdx = 1; colIdx <= client_result.getColumnCount(); colIdx++ ) {
                    log_msg += ''  |  '' + client_result.getColumnValueAsString(colIdx);
                }
                log_msg += ''  |\\n'';
            }
        } catch(err) {
            log_msg += "\\nFailed: Code: " + err.code + "\\n  State: " + err.state;
            log_msg += "\\n  Message: " + err.message;
            log_msg += "\\nStack Trace:\\n" + err.stackTraceTxt; 
        } finally {
            var without_it_it_wont_work =  snowflake.createStatement({
                    sqlText: ''SELECT 1;''
                });
            
            without_it_it_wont_work.execute();

            var update_entity_audit_stmt = snowflake.createStatement({
                    sqlText:
                        `UPDATE ` +  DATABASENAME + `.` + SCHEMANAME + `.TEST_SNOWFLAKE_LOGGING as audit
                        SET
                            START_TIME=inf.START_TIME,
                            END_TIME=inf.END_TIME,
                            ROW_INSERTED= :2,
                            ROW_MODIFIED= :3,
                            ROW_DELETED= :4, 
                            EXECUTION_STATUS= inf.EXECUTION_STATUS, 
                            ERROR_CODE= inf.ERROR_CODE,
                            ERROR_MESSAGE= inf.ERROR_MESSAGE,      // was :5 probably shouldn''t be
                            BYTES_SCANNED= inf.BYTES_SCANNED, 
                            COMPILATION_TIME= inf.COMPILATION_TIME,
                            EXECUTION_TIME= inf.EXECUTION_TIME, 
                            CREDITS_USED_CLOUD_SERVICES= inf.CREDITS_USED_CLOUD_SERVICES
                        FROM table(` + DATABASENAME + `.information_schema.QUERY_HISTORY_BY_SESSION()) as inf
                        WHERE audit.QUERY_ID= :1 AND inf.QUERY_ID= :1`,
                    binds:[
                        query_id,       // :1
                        row_inserted,   // :2
                        row_modified,   // :3
                        row_deleted,    // :4
                        log_msg         // :5
                        ]
                });
        
            update_entity_audit_stmt.execute();
        }

    } catch(err) {
        log_msg += "\\nFailed: Code: " + err.code + "\\n  State: " + err.state;
        log_msg += "\\n  Message: " + err.message;
        log_msg += "\\nStack Trace:\\n" + err.stackTraceTxt; 
        var current_db_query = snowflake.createStatement( {sqlText: "SELECT CURRENT_DATABASE();"}).execute();
        current_db_query.next();
        current_db = current_db_query.getColumnValue(1);
        log_msg += "\\nEnvironment:\\n" + DATABASENAME + "." + SCHEMANAME + "/" + current_db; 
        var current_role_query = snowflake.createStatement( {sqlText: "SELECT current_role();"}).execute();
        current_role_query.next();
        current_role = current_role_query.getColumnValue(1);
        log_msg += "\\Role:\\n" + current_role; 
    }

    return log_msg;
';
CREATE PROCEDURE IF NOT EXISTS LOGENTITYOPERATIONWRAPPERADDITIONALARGUMENTS("SQLTEXT" VARCHAR(16777216), "BATCH_CONTROL_RUN_ID" VARCHAR(16777216), "JOB_CONTROL_ID" VARCHAR(16777216), "ADD_ARGUMENT" VARCHAR(16777216))
RETURNS VARIANT
LANGUAGE JAVASCRIPT
EXECUTE AS CALLER
AS '
    var log_msg = "";
    var status_message = "";
    var error_dtls = "";
    var query_id = null;
    var row_read = null;
    var row_inserted = null;
    var row_deleted = null;
    var row_modified = null;

    try {
        var insert_entity_audit_statement = snowflake.createStatement({
            sqlText:
                `INSERT INTO TEST_SNOWFLAKE_LOGGING_ADDITIONAL_COLUMNS
                    (JOB_CONTROL_RUN_ID,BATCH_CONTROL_RUN_ID,JOB_CONTROL_ID,JOB_START_TS,JOB_END_TS,JOB_SELECTION_START_TS,
                    JOB_SELECTION_END_TS,JOB_STTS,JOB_CURR_ID,JOB_REC_READ_CNT,JOB_REC_PRCSD_CNT,JOB_REC_UPDT_CNT,
                    JOB_REC_DELETE_CNT,JOB_REC_ERROR_CNT,JOB_ERROR_CODE,JOB_ERROR_DTLS,JOB_LOG_LOCN,INSRT_USER,INSRT_TS,UPDT_USER,UPDT_TS)
                VALUES (NULL,:1,:2,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL)`,
            binds:[BATCH_CONTROL_RUN_ID,JOB_CONTROL_ID]
            });
        insert_entity_audit_statement.execute();

        // Get exact query_id of the last inserted record
        var get_last_query_id_stmt = snowflake.createStatement({
            sqlText:`select last_query_id();`,
            binds:[insert_entity_audit_statement.getQueryId()]
        });
        var entity_audit_id_result = get_last_query_id_stmt.execute();
        entity_audit_id_result.next();
        var entity_audit_id = entity_audit_id_result.getColumnValue(1);

        var update_query_id = snowflake.createStatement({
                sqlText:
                    `UPDATE TEST_SNOWFLAKE_LOGGING_ADDITIONAL_COLUMNS
                    SET JOB_CURR_ID= :1
                    WHERE JOB_CURR_ID is NULL`,
                binds:[entity_audit_id]
            });

            update_query_id.execute();





                    

var current_db_query = snowflake.createStatement( {sqlText: "SELECT CURRENT_DATABASE();"}).execute();
current_db_query.next();
current_db=current_db_query.getColumnValue(1);




        try {
            var client_statement = snowflake.createStatement({
                sqlText: SQLTEXT,
            });

            log_msg += ''\\nStatement of `client_statement`'';
            log_msg += ''\\n  SqlText = '' + client_statement.getSqlText();

            var client_result = client_statement.execute();

            query_id = client_statement.getQueryId();
            row_inserted = client_statement.getNumRowsInserted();
            row_modified = client_statement.getNumRowsUpdated();
            row_deleted = client_statement.getNumRowsDeleted();
            row_read = client_statement.getNumRowsAffected();

            log_msg += ''\\n  QueryId = '' + query_id;
            log_msg += ''\\n  ColumnCount = '' + client_statement.getColumnCount();
            log_msg += ''\\n  RowCount = '' + client_statement.getRowCount();
            log_msg += ''\\n  NumDuplicateRowsUpdated = '' + client_statement.getNumDuplicateRowsUpdated();
            log_msg += ''\\n  NumRowsAffected = '' + client_statement.getNumRowsAffected();
            log_msg += ''\\n  NumRowsDeleted = '' + row_deleted;
            log_msg += ''\\n  NumRowsInserted = '' + row_inserted;
            log_msg += ''\\n  NumRowsUpdated = '' + row_modified;

            log_msg += ''\\nResultSet of `client_statement`'';
            for (let colIdx = 1; colIdx <= client_statement.getColumnCount(); colIdx++ ) {
                log_msg += ''  |  '' + client_statement.getColumnName(colIdx);
            }
            log_msg += ''  |\\n'';

            limit = 10;
            ind = 0;
            while(client_result.next() && ind < limit) {
                for (let colIdx = 1; colIdx <= client_result.getColumnCount(); colIdx++ ) {
                    log_msg += ''  |  '' + client_result.getColumnValueAsString(colIdx);
                }
                log_msg += ''  |\\n'';
            }
        } catch(err) {
            log_msg += "\\nFailed: Code: " + err.code + "\\n  State: " + err.state;
            log_msg += "\\n  Message: " + err.message;
            log_msg += "\\nStack Trace:\\n" + err.stackTraceTxt;
            
            status_message = "failed";
            error_dtls = err.message + ''\\n'' + err.stackTraceTxt;
        } finally {
            status_message = "success"

            log_msg += status_message;
            log_msg += "\\n";

            var update_entity_audit_stmt = snowflake.createStatement({
                    sqlText:
                        `UPDATE TEST_SNOWFLAKE_LOGGING_ADDITIONAL_COLUMNS as audit
                        SET JOB_CONTROL_RUN_ID= :6,
                            JOB_START_TS= inf.START_TIME,
                            JOB_END_TS= inf.END_TIME,
                            JOB_SELECTION_START_TS= inf.START_TIME,
                            JOB_SELECTION_END_TS= inf.END_TIME,
                            JOB_STTS= :2,
                            JOB_CURR_ID= :1,
                            JOB_REC_READ_CNT= :3,
                            JOB_REC_PRCSD_CNT= :4,
                            JOB_REC_UPDT_CNT= :5,
                            JOB_REC_DELETE_CNT= :6,
                            JOB_REC_ERROR_CNT= 000000,
                            JOB_ERROR_CODE= inf.ERROR_CODE,
                            JOB_ERROR_DTLS= :7,
                            JOB_LOG_LOCN= :9,
                            INSRT_USER= inf.USER_NAME,
                            INSRT_TS= sysdate(),
                            UPDT_USER= inf.USER_NAME,
                            UPDT_TS= sysdate()
                        FROM table(information_schema.QUERY_HISTORY_BY_SESSION()) as inf
                        WHERE audit.job_curr_id= :8`,
                    binds:[query_id,status_message,row_read,row_inserted,row_modified,row_deleted,error_dtls,entity_audit_id,current_db]
                });

            update_entity_audit_stmt.execute();
        }

    } catch(err) {
        log_msg += "\\nFailed: Code: " + err.code + "\\n  State: " + err.state;
        log_msg += "\\n  Message: " + err.message;
        log_msg += "\\nStack Trace:\\n" + err.stackTraceTxt;
    }

    return log_msg;
';
CREATE PROCEDURE IF NOT EXISTS PROC_QUERY_OFFER_CODE()
RETURNS FLOAT
LANGUAGE JAVASCRIPT
EXECUTE AS OWNER
AS '
	var total = SELECT count(1) FROM EPS_DD_OFFER_CODE_RAW_HIST

	return total  
 ';
CREATE PROCEDURE IF NOT EXISTS PROC_WHILE_TEST()
RETURNS FLOAT
LANGUAGE JAVASCRIPT
EXECUTE AS OWNER
AS '
	var total = 0
	var i = 0
	while (i < 10) {
	  total = total + i	
	  i++;
	}
	return i  
 ';