create view IF NOT EXISTS WEATHER_FORECAST(
	DATE_KEY,
	TIME_KEY,
	DATE_TIME_UNIX_NBR,
	CITY_ID,
	CITY,
	CITY_LATITUDE_NBR,
	CITY_LONGITUDE_NBR,
	REST_LATITUDE_NBR,
	REST_LONGITUDE_NBR,
	COUNTRY_CODE,
	TIME_ZONE,
	DAY_TEMPERATURE_VAL,
	MIN_DAY_TEMPERATURE,
	MAX_DAY_TEMPERATURE,
	NIGHT_TEMPERATURE,
	EVENING_TEMPERATURE_VAL,
	MORNING_TEMPERATURE,
	FEELS_LIKE_DAY_TEMPERATURE_VAL,
	FEELS_LIKE_NIGHT_TEMPERATURE_VAL,
	FEELS_LIKE_EVE_TEMPERATURE_VAL,
	FEELS_LIKE_MORNING_TEMPERATURE_VAL,
	ATMOSPHERIC_PRESSURE_VAL,
	HUMIDITY_PCT,
	WEATHER_ID,
	WEATHER_ICON_ID,
	WEATHER_GROUP_NAME,
	WEATHER_DESC,
	WIND_SPEED,
	WIND_DEGREE_VAL,
	CLOUDS_PCT,
	RAIN_VOLUME_VAL,
	SNOWL_VOL,
	BRAND_ID,
	SOURCE_SYSTEM_NAME,
	CDM_LOAD_DATE,
	LOAD_TYPE,
	LOAD_ID,
	LOAD_DTTM
) as 
SELECT
c.DATE_KEY AS DATE_KEY
,c.TIME_KEY AS TIME_KEY
,c.DATE_TIME_UNIX_NBR AS DATE_TIME_UNIX_NBR
,c.CITY_ID AS CITY_ID
,c.CITY AS CITY
,c.CITY_LATITUDE_NBR AS CITY_LATITUDE_NBR
,c.CITY_LONGITUDE_NBR AS CITY_LONGITUDE_NBR
,c.REST_LATITUDE_NBR AS REST_LATITUDE_NBR
,c.REST_LONGITUDE_NBR AS REST_LONGITUDE_NBR
,c.COUNTRY_CODE AS COUNTRY_CODE
,c.TIME_ZONE AS TIME_ZONE
,c.DAY_TEMPERATURE_VAL AS DAY_TEMPERATURE_VAL
,c.MIN_DAY_TEMPERATURE AS MIN_DAY_TEMPERATURE
,c.MAX_DAY_TEMPERATURE AS MAX_DAY_TEMPERATURE
,c.NIGHT_TEMPERATURE AS NIGHT_TEMPERATURE
,c.EVENING_TEMPERATURE_VAL AS EVENING_TEMPERATURE_VAL
,c.MORNING_TEMPERATURE AS MORNING_TEMPERATURE
,c.FEELS_LIKE_DAY_TEMPERATURE_VAL AS FEELS_LIKE_DAY_TEMPERATURE_VAL
,c.FEELS_LIKE_NIGHT_TEMPERATURE_VAL AS FEELS_LIKE_NIGHT_TEMPERATURE_VAL
,c.FEELS_LIKE_EVE_TEMPERATURE_VAL AS FEELS_LIKE_EVE_TEMPERATURE_VAL
,c.FEELS_LIKE_MORNING_TEMPERATURE_VAL AS FEELS_LIKE_MORNING_TEMPERATURE_VAL
,c.ATMOSPHERIC_PRESSURE_VAL AS ATMOSPHERIC_PRESSURE_VAL
,c.HUMIDITY_PCT AS HUMIDITY_PCT
,c.WEATHER_ID AS WEATHER_ID
,c.WEATHER_ICON_ID AS WEATHER_ICON_ID
,c.WEATHER_GROUP_NAME AS WEATHER_GROUP_NAME
,c.WEATHER_DESC AS WEATHER_DESC
,c.WIND_SPEED AS WIND_SPEED
,c.WIND_DEGREE_VAL AS WIND_DEGREE_VAL
,c.CLOUDS_PCT AS CLOUDS_PCT
,c.RAIN_VOLUME_VAL AS RAIN_VOLUME_VAL
,c.SNOWL_VOL AS SNOWL_VOL
,c.BRAND_ID AS BRAND_ID
,c.SOURCE_SYSTEM_NAME AS SOURCE_SYSTEM_NAME
,c.CDM_LOAD_DATE AS CDM_LOAD_DATE
,c.LOAD_TYPE AS LOAD_TYPE
,c.LOAD_ID AS LOAD_ID
,c.LOAD_DTTM AS LOAD_DTTM
FROM IDS_DEV.EXT_REF_BV.WEATHER_FORECAST_BV C;