create TABLE IF NOT EXISTS FLYWAY_SCHEMA_HISTORY (
	INSTALLED_RANK NUMBER(38,0) NOT NULL,
	VERSION VARCHAR(50),
	DESCRIPTION VARCHAR(200),
	TYPE VARCHAR(20) NOT NULL,
	SCRIPT VARCHAR(1000) NOT NULL,
	CHECKSUM NUMBER(38,0),
	INSTALLED_BY VARCHAR(100) NOT NULL,
	INSTALLED_ON TIMESTAMP_LTZ(9) NOT NULL DEFAULT CURRENT_TIMESTAMP(),
	EXECUTION_TIME NUMBER(38,0) NOT NULL,
	SUCCESS BOOLEAN NOT NULL,
	primary key (INSTALLED_RANK)
);
create view IF NOT EXISTS CHANNEL(
	CHANNEL_ID,
	ORDER_CHANNEL_NAME,
	FULFILLMENT_CHANNEL_NAME,
	ORDER_CHANNEL_HIERARCHY_NAME_L3,
	ORDER_CHANNEL_HIERARCHY_NAME_L2,
	ORDER_CHANNEL_HIERARCHY_NAME_L1,
	FULFILLMENT_CHANNEL_HIERARCHY_L3,
	FULFILLMENT_CHANNEL_HIERARCHY_L2,
	FULFILLMENT_CHANNEL_HIERARCHY_L1,
	SOURCE_SYSTEM_NAME,
	HIERARCHY_SOURCE_SYSTEM_NAME,
	BRAND_ID,
	CDM_LOAD_DATE,
	CDM_UPDATE_DATE,
	LOAD_ID,
	LOAD_DTTM,
	UPDATE_ID,
	UPDATE_DTTM
) as 
SELECT c.CHANNEL_ID AS CHANNEL_ID
, c.ORDER_CHANNEL_NM AS ORDER_CHANNEL_NAME
, c.FULFILLMENT_CHANNEL_NM AS FULFILLMENT_CHANNEL_NAME
, c.ORDER_CHANNEL_HIERARCHY_L3_NM AS ORDER_CHANNEL_HIERARCHY_NAME_L3
, c.ORDER_CHANNEL_HIERARCHY_L2_NM AS ORDER_CHANNEL_HIERARCHY_NAME_L2
, c.ORDER_CHANNEL_HIERARCHY_L1_NM AS ORDER_CHANNEL_HIERARCHY_NAME_L1
, c.FULFILLMENT_CHANNEL_HIERARCHY_L3_NM AS FULFILLMENT_CHANNEL_HIERARCHY_L3
, c.FULFILLMENT_CHANNEL_HIERARCHY_L2_NM AS FULFILLMENT_CHANNEL_HIERARCHY_L2
, c.FULFILLMENT_CHANNEL_HIERARCHY_L1_NM AS FULFILLMENT_CHANNEL_HIERARCHY_L1
, c.SOURCE_SYSTEM_NM AS SOURCE_SYSTEM_NAME
, c.HIERARCHY_SOURCE_SYSTEM_NM AS HIERARCHY_SOURCE_SYSTEM_NAME
, c.BRAND_ID AS BRAND_ID
, c.CDM_LOAD_DT AS CDM_LOAD_DATE
, c.CDM_UPDATE_DT AS CDM_UPDATE_DATE
, c.LOAD_ID AS LOAD_ID
, c.LOAD_DTTM AS LOAD_DTTM
, c.UPDATE_ID AS UPDATE_ID
, c.UPDATE_DTTM AS UPDATE_DTTM
FROM IDM_DEV.COREDIM_BV.CHANNEL_DIM_BV c;
create view IF NOT EXISTS DATE(
	DATE_KEY,
	CAL_DATE,
	DATE_DISPLAY_NAME,
	CAL_YR_NBR,
	CAL_DAY_IN_YR_NBR,
	CAL_MONTH_NBR,
	CAL_MONTH_NAME,
	CAL_DAYS_IN_YR_QTY,
	CAL_DAY_NAME,
	CAL_YR_START_DATE,
	CAL_YR_END_DATE,
	CAL_QTR_NBR,
	CAL_QTR_NAME,
	CAL_QTR_START_DATE,
	CAL_QTR_END_DATE,
	CAL_DAYS_IN_QTR_QTY,
	CAL_MONTH_START_DATE,
	CAL_MONTH_END_DATE,
	CAL_DAYS_IN_MONTH_QTY,
	CAL_WK_IN_YR_NBR,
	CAL_WK_START_DATE,
	CAL_WK_END_DATE,
	WEEKDAY_IND,
	FISC_YR_NBR,
	FISC_YR_START_DATE,
	FISC_YR_END_DATE,
	FISC_DAYS_IN_QTR_QTY,
	FISC_DAYS_IN_YR_QTY,
	FISC_DAY_IN_PERIOD_NBR,
	FISC_PERIOD_NBR,
	FISC_QTR_NBR,
	FISC_QTR_START_DATE,
	FISC_QTR_END_DATE,
	FISC_PERIOD_START_DATE,
	FISC_PERIOD_END_DATE,
	FISC_DAYS_IN_PERIOD_QTY,
	FISC_WKS_IN_PERIOD_QTY,
	FISC_WKS_IN_YR_QTY,
	FISC_WK_NBR,
	FISC_WKS_IN_QTR_QTY,
	FISC_WK_START_DATE,
	FISC_WK_END_DATE,
	FISC_DAY_IN_WK_NBR,
	FISC_COMP_DATE,
	CAL_COMP_DATE,
	CAL_COMP_START_DATE,
	CAL_COMP_END_DATE,
	CAL_COMP_DAYS_IN_YR_QTY,
	CAL_COMP_IN_YR_NBR,
	CAL_COMP_DAYS_IN_PERIOD_QTY,
	CAL_COMP_QTR_NBR,
	CAL_COMP_QTR_START_DATE,
	CAL_COMP_QTR_END_DATE,
	CAL_COMP_PERIOD_START_DATE,
	CAL_COMP_PERIOD_END_DATE,
	CAL_COMP_WK_START_DATE,
	CAL_COMP_WK_END_DATE,
	CAL_COMP_DAY_IN_WK_NBR,
	BRAND_ID,
	SOURCE_SYSTEM_NAME,
	LOAD_ID,
	LOAD_DTTM,
	UPDATE_ID,
	UPDATE_DTTM,
	HOLIDAY_IND,
	HOLIDAY_QTY,
	HOLIDAY_LIST_NAME
) as 
SELECT c.DATE_KEY AS DATE_KEY
, c.CALENDAR_DT AS CAL_DATE
, c.DATE_DISPLAY_NM AS DATE_DISPLAY_NAME
, c.CALENDAR_YEAR_NBR AS CAL_YR_NBR
, c.CALENDAR_DAY_IN_YEAR_NBR AS CAL_DAY_IN_YR_NBR
, c.CALENDAR_MONTH_NBR AS CAL_MONTH_NBR
, c.CALENDAR_MONTH_NM AS CAL_MONTH_NAME
, c.CALENDAR_DAYS_IN_YEAR_QTY AS CAL_DAYS_IN_YR_QTY
, c.CALENDAR_DAY_NM AS CAL_DAY_NAME
, c.CALENDAR_YEAR_START_DT AS CAL_YR_START_DATE
, c.CALENDAR_YEAR_END_DT AS CAL_YR_END_DATE
, c.CALENDAR_QUARTER_NBR AS CAL_QTR_NBR
, c.CALENDAR_QUARTER_NM AS CAL_QTR_NAME
, c.CALENDAR_QUARTER_START_DT AS CAL_QTR_START_DATE
, c.CALENDAR_QUARTER_END_DT AS CAL_QTR_END_DATE
, c.CALENDAR_DAYS_IN_QUARTER_QTY AS CAL_DAYS_IN_QTR_QTY
, c.CALENDAR_MONTH_START_DT AS CAL_MONTH_START_DATE
, c.CALENDAR_MONTH_END_DT AS CAL_MONTH_END_DATE
, c.CALENDAR_DAYS_IN_MONTH_QTY AS CAL_DAYS_IN_MONTH_QTY
, c.CALENDAR_WEEK_IN_YEAR_NBR AS CAL_WK_IN_YR_NBR
, c.CALENDAR_WEEK_START_DT AS CAL_WK_START_DATE
, c.CALENDAR_WEEK_END_DT AS CAL_WK_END_DATE
, c.WEEKDAY_IND AS WEEKDAY_IND
, c.FISCAL_YEAR_NBR AS FISC_YR_NBR
, c.FISCAL_YEAR_START_DT AS FISC_YR_START_DATE
, c.FISCAL_YEAR_END_DT AS FISC_YR_END_DATE
, c.FISCAL_DAYS_IN_QUARTER_QTY AS FISC_DAYS_IN_QTR_QTY
, c.FISCAL_DAYS_IN_YEAR_QTY AS FISC_DAYS_IN_YR_QTY
, c.FISCAL_DAY_IN_PERIOD_NBR AS FISC_DAY_IN_PERIOD_NBR
, c.FISCAL_PERIOD_NBR AS FISC_PERIOD_NBR
, c.FISCAL_QUARTER_NBR AS FISC_QTR_NBR
, c.FISCAL_QUARTER_START_DT AS FISC_QTR_START_DATE
, c.FISCAL_QUARTER_END_DT AS FISC_QTR_END_DATE
, c.FISCAL_PERIOD_START_DT AS FISC_PERIOD_START_DATE
, c.FISCAL_PERIOD_END_DT AS FISC_PERIOD_END_DATE
, c.FISCAL_DAYS_IN_PERIOD_QTY AS FISC_DAYS_IN_PERIOD_QTY
, c.FISCAL_WEEKS_IN_PERIOD_QTY AS FISC_WKS_IN_PERIOD_QTY
, c.FISCAL_WEEKS_IN_YEAR_QTY AS FISC_WKS_IN_YR_QTY
, c.FISCAL_WEEK_NBR AS FISC_WK_NBR
, c.FISCAL_WEEKS_IN_QUARTER_QTY AS FISC_WKS_IN_QTR_QTY
, c.FISCAL_WEEK_START_DT AS FISC_WK_START_DATE
, c.FISCAL_WEEK_END_DT AS FISC_WK_END_DATE
, c.FISCAL_DAY_IN_WEEK_NBR AS FISC_DAY_IN_WK_NBR
, c.FISCAL_COMPARABLE_DT AS FISC_COMP_DATE
, c.CALENDAR_COMPARABLE_DT AS CAL_COMP_DATE
, c.CALENDAR_COMPARABLE_START_DT AS CAL_COMP_START_DATE
, c.CALENDAR_COMPARABLE_END_DT AS CAL_COMP_END_DATE
, c.CALENDAR_COMPARABLE_DAYS_IN_YEAR_QTY AS CAL_COMP_DAYS_IN_YR_QTY
, c.CALENDAR_COMPARABLE_IN_YEAR_NBR AS CAL_COMP_IN_YR_NBR
, c.CALENDAR_COMPARABLE_DAYS_IN_PERIOD_QTY AS CAL_COMP_DAYS_IN_PERIOD_QTY
, c.CALENDAR_COMPARABLE_QUARTER_NBR AS CAL_COMP_QTR_NBR
, c.CALENDAR_COMPARABLE_QUARTER_START_DT AS CAL_COMP_QTR_START_DATE
, c.CALENDAR_COMPARABLE_QUARTER_END_DT AS CAL_COMP_QTR_END_DATE
, c.CALENDAR_COMPARABLE_PERIOD_START_DT AS CAL_COMP_PERIOD_START_DATE
, c.CALENDAR_COMPARABLE_PERIOD_END_DT AS CAL_COMP_PERIOD_END_DATE
, c.CALENDAR_COMPARABLE_WEEK_START_DT AS CAL_COMP_WK_START_DATE
, c.CALENDAR_COMPARABLE_WEEK_END_DT AS CAL_COMP_WK_END_DATE
, c.CALENDAR_COMPARABLE_DAY_IN_WEEK_NBR AS CAL_COMP_DAY_IN_WK_NBR
, c.BRAND_ID AS BRAND_ID
, c.SOURCE_SYSTEM_NM AS SOURCE_SYSTEM_NAME
, c.LOAD_ID AS LOAD_ID
, c.LOAD_DTTM AS LOAD_DTTM
, c.UPDATE_ID AS UPDATE_ID
, c.UPDATE_DTTM AS UPDATE_DTTM
, h.HOLIDAY_IND
, h.HOLIDAY_QTY
, h.HOLIDAY_LIST_NM HOLIDAY_LIST_NAME
FROM IDS_DEV.INT_REF_BV.DATE_DIM_BV c
LEFT OUTER JOIN (
				SELECT HOLIDAY_DIM_BV.DATE_KEY,count(Holiday_nm) HOLIDAY_QTY,MAX(iff(HOLIDAY_NM IS NOT NULL,True,False)) as HOLIDAY_IND,listagg(HOLIDAY_NM, ', ') as HOLIDAY_LIST_NM
				--,MAX(UPDATE_DTTM)
				FROM IDS_DEV.INT_REF_BV.HOLIDAY_DIM_BV 
				GROUP BY date_key) H
ON c.DATE_KEY = h.date_key
;