dag_config:
  dag_id: 'E2E_SALES_RECON_SDI_POS_INFOR_MICROS_MASTER'
  default_args:
    'owner': 'SALESRECON'
    'email': ['theja.h@inspirebrands.com','murugan.thirunavukar@inspirebrands.com']
    'email_on_failure': True
    'depends_on_past': False
    'retries' : 0
    schedule_interval: ""
  doc_md: |-
    ### Master DAG
    This DAG is responsible for triggering the other transaction DAGs for procesing data
  tags: ['SALESRECON_SONIC', 'SDI', 'POS_INFOR_MICROS', 'MASTERDAG']
  catchup : False

child_dags:
  E2E_SALES_RECON_SDI_POS_INFOR_MICROS_IDS_TO_IDS_DAILY: 'E2E_SALES_RECON_SDI_POS_INFOR_MICROS_IDS_TO_IDS_DAILY'
  E2E_SALES_RECON_SDI_POS_INFOR_MICROS_IDS_TO_IDS_WEEKLY: 'E2E_SALES_RECON_SDI_POS_INFOR_MICROS_IDS_TO_IDS_WEEKLY'
  E2E_SALES_RECON_SDI_POS_INFOR_MICROS_DQ: 'E2E_SALES_RECON_SDI_POS_INFOR_MICROS_DQ'