dag_id: "E2E_SALES_RECON_BWW_ALOHA_IDS_TO_IDS_WEEKLY"
dag_description: "BWW Aloha data load from IDS to IDS"
email: ["itdataservicessupport@inspirebrands.com", "bwwhelp@service-now.com"]
source_env : "PROD"
target_env : "PROD"
warehouse_id : "IRB_PRCSSA_IRB_PROD_WH"
snowflake_conn_id : "Snowflake-IRB-PROD-OWNER"
schema_id : "BWW"