dag_id: "ARBYS_POS_REVENUE_CENTER_RDS_TO_IDS_DAILY"
dag_description: "Arbys Parbrinks data load from RDS to IDS"
emails: ['udpfinanceengineeringpod@inspirebrands.com']
email: ['udpfinanceengineeringpod@inspirebrands.com']
source_env : "DEV"
target_env : "DEV"
warehouse_id : "IRB_PRCSSA_IRB_WH"
schema_id : "ARB"

