dag_id: "E2E_SALES_RECON_SDI_ORACLEGL_ADLS_TO_RDS"
dag_description: "SDI Oracle GL data load from ADLS2 to RDS"
email: ['udpfinanceengineeringpod@inspirebrands.com']
env : "DEV"
warehouse_id : "RA_PRCSSA_IRB_WH"
schema_id : "SDI"
file_format: "RDS_DEV.SDI.GENERAL_LEDGER_SDI_FILE_FORMAT"
pattern: ".*GL_SALES_JE_TO_UDP.*[.]csv"
rds_env: "RDS_DEV"
stage_name: "@RDS_DEV.SDI.SALES_RECON_READ_SDI_ADLS2"