create TABLE IF NOT EXISTS FLYWAY_SCHEMA_HISTORY (
	INSTALLED_RANK NUMBER(38,0) NOT NULL,
	VERSION VARCHAR(50),
	DESCRIPTION VARCHAR(200),
	TYPE VARCHAR(20) NOT NULL,
	SCRIPT VARCHAR(1000) NOT NULL,
	CHECKSUM NUMBER(38,0),
	INSTALLED_BY VARCHAR(100) NOT NULL,
	INSTALLED_ON TIMESTAMP_LTZ(9) NOT NULL DEFAULT CURRENT_TIMESTAMP(),
	EXECUTION_TIME NUMBER(38,0) NOT NULL,
	SUCCESS BOOLEAN NOT NULL,
	primary key (INSTALLED_RANK)
);
create view IF NOT EXISTS CMX_RESTAURANT_AUDIT_REPORT_TAG_AGG_BV(
	BRAND_ID COMMENT 'Brand Identifier specifies the code which represents an organization. The identifier should be in all capital letters. Sample codes are irb (Inspire Recognized Brands), bww(Buffalo Wild Wing), arbys (Arbys),  dnkn  (Dunkin), etc.',
	CMX_ID COMMENT 'CMX Identifier appears to uniquely identify the attribute combinations of group_name, report_tag, core_audit_service_service_name, and parent_item_id from the raw table. Sample values a7d51eab-f91e-4c98-91b3-510abf4b8bb0 and 7dbbab8a-484a-45a1-9fab-e8e4d070a202.',
	CMX_AUDIT_ID COMMENT 'CMX Audit Identifier  Sample values str-65f32bfe45b148cd9b541450fa2349a7 and str-ccf32239a76247a48231c223a00c9382.',
	STORE_ID COMMENT 'Store Identifier is an integer that uniquely identifies the store.',
	AUDIT_DT COMMENT 'Audit Date is the day of the audit.',
	CMX_AUDIT_SERVICE_NM COMMENT 'CMX Audit Service Name is a label for a type of audit. Sample values CTR PRE-Certification Audit, EcoSure (Self Assessment) 2021, and NCTR Certification Audit.',
	CMX_AUDIT_SERVICE_VERSION_NBR COMMENT 'CMX Audit Service Version Number is the version of an audit.',
	CMX_GROUP_NM COMMENT 'CMX Group Name is a high level categorization of questions. Sample values ARBY''S STANDARDS, FOOD SAFETY, and GUEST EXPERIENCE.',
	CMX_GROUP_POINT_QTY COMMENT 'CMX Group Point Quantity is the number of points for an audit that a restaraunt recieved at the Group Level.',
	CMX_GROUP_MAXIMUM_POINT_QTY COMMENT 'CMX Group Maximum Point Quantity is the maximum number of points for an audit that a restaraunt may receive at the Group Level.',
	CMX_GROUP_VAL COMMENT 'CMX Group Value  is a calculated value fromGroup Point Quantity and Group Maximum Point Quantity and store the percentage calculation. Examples of values are 93.32 and 87.65.',
	CMX_REPORT_TAG_NM COMMENT 'CMX Report Tag is a further categorization of audit question within a Group. NameSample values Building/Equipment/OSM Standards, Menu/Marketing, Equipment, Team Practices, Accuracy, and Cleanliness- Guest View.',
	CMX_REPORT_TAG_POINT_QTY COMMENT 'CMX Report Tag Point Quantity is the number of points for an audit that a restaraunt recieved at the Group/Report Tag Level.',
	CMX_REPORT_TAG_MAXIMUM_POINT_QTY COMMENT 'CMX Report Tag Maximum Point Quantity is the maximum number of points for an audit that a restaraunt may receive at the Group/Report Tag  Level.',
	CMX_REPORT_TAG_VAL COMMENT 'CMX Report Tag Value is a calculated value from Report Tag Point Quantity and Report Tag Maximum Point Quantity and store the percentage calculation. Examples of values are 93.32 and 87.65.',
	SOURCE_SYSTEM_NM COMMENT 'Source System Name specifies the origin of the data. For example, Salesforce Marketing App or Netsuite. Some systems will have a reference table where sources are identified by integers such as 1,2,3, etc.',
	LOAD_ID COMMENT 'Load Identifier specifies the Batch that inserted the record into the table.',
	LOAD_DTTM COMMENT 'Load Datetime is the date and time in UTC when the record was created. For example, 2021-08-11T15:02:24Z.',
	UPDATE_ID COMMENT 'Update Identifier specifies the batch id used for the update of the record.',
	UPDATE_DTTM COMMENT 'Update Datetime is the date and time in UTC when the record was last updated. For example, 2021-08-11T15:02:24Z.'
) COMMENT='CMX Restaurant Audit Report Tag Agg  is CMX audit aggregated data at the Group/Report Tag level.'
 as 
SELECT CMX_RESTAURANT_AUDIT_REPORT_TAG_AGG.BRAND_ID,CMX_RESTAURANT_AUDIT_REPORT_TAG_AGG.CMX_ID,CMX_RESTAURANT_AUDIT_REPORT_TAG_AGG.CMX_AUDIT_ID,CMX_RESTAURANT_AUDIT_REPORT_TAG_AGG.STORE_ID,CMX_RESTAURANT_AUDIT_REPORT_TAG_AGG.AUDIT_DT,CMX_RESTAURANT_AUDIT_REPORT_TAG_AGG.CMX_AUDIT_SERVICE_NM,CMX_RESTAURANT_AUDIT_REPORT_TAG_AGG.CMX_AUDIT_SERVICE_VERSION_NBR,CMX_RESTAURANT_AUDIT_REPORT_TAG_AGG.CMX_GROUP_NM,CMX_RESTAURANT_AUDIT_REPORT_TAG_AGG.CMX_GROUP_POINT_QTY,CMX_RESTAURANT_AUDIT_REPORT_TAG_AGG.CMX_GROUP_MAXIMUM_POINT_QTY,CMX_RESTAURANT_AUDIT_REPORT_TAG_AGG.CMX_GROUP_VAL,CMX_RESTAURANT_AUDIT_REPORT_TAG_AGG.CMX_REPORT_TAG_NM,CMX_RESTAURANT_AUDIT_REPORT_TAG_AGG.CMX_REPORT_TAG_POINT_QTY,CMX_RESTAURANT_AUDIT_REPORT_TAG_AGG.CMX_REPORT_TAG_MAXIMUM_POINT_QTY,CMX_RESTAURANT_AUDIT_REPORT_TAG_AGG.CMX_REPORT_TAG_VAL,CMX_RESTAURANT_AUDIT_REPORT_TAG_AGG.SOURCE_SYSTEM_NM,CMX_RESTAURANT_AUDIT_REPORT_TAG_AGG.LOAD_ID,CMX_RESTAURANT_AUDIT_REPORT_TAG_AGG.LOAD_DTTM,CMX_RESTAURANT_AUDIT_REPORT_TAG_AGG.UPDATE_ID,CMX_RESTAURANT_AUDIT_REPORT_TAG_AGG.UPDATE_DTTM
FROM IDS_DEV.LOCN.CMX_RESTAURANT_AUDIT_REPORT_TAG_AGG ;
create view IF NOT EXISTS DEV_SITEDEVELOPMENT_PLR_BV(
	STOREID,
	STATUS,
	EFFECTIVEDATE,
	LATITUDE,
	LONGITUDE,
	ADDRESS,
	CITY,
	STATE,
	ZIP,
	VENUE,
	MODEL,
	IMAGE,
	FACILITYTYPE,
	BUILDINGTYPE,
	SEATCOUNT,
	PARKINGCOUNT,
	HANDICAPPARKING,
	BREAKFAST,
	BLDGSQFT,
	DRIVETHRU,
	BRANDID,
	CDMLOADDATE,
	FILENAME
) as SELECT
                               "STOREID", "STATUS", "EFFECTIVEDATE", "LATITUDE", "LONGITUDE", "ADDRESS", "CITY", "STATE", "ZIP", "VENUE", "MODEL", "IMAGE", "FACILITYTYPE", "BUILDINGTYPE", "SEATCOUNT", "PARKINGCOUNT", "HANDICAPPARKING", "BREAKFAST", "BLDGSQFT", "DRIVETHRU", "BRANDID", "CDMLOADDATE", "FILENAME"
                            FROM CDMSYNC_DEV.IRB."DEV_SITEDEVELOPMENT_PLR";
create view IF NOT EXISTS DIM_RESTAURANT_BV(
	RESTAURANT_KEY,
	REST_NUMBER,
	REST_NAME,
	REST_STATUS,
	REST_TYPE,
	REST_FRAN_NUMBER,
	REST_FRAN_NAME,
	REST_FRANENTITY_NUMBER,
	REST_FRANENTITY_NAME,
	REST_COMPANY_NAME,
	REST_BRAND_NAME,
	REST_BRAND_ISACTIVE,
	REST_DMA_CODE,
	REST_DMA_DESC,
	REST_ISAIRPORT,
	REST_ISVIDEOSURV,
	REST_ISBREAKFAST,
	REST_IS24HR,
	REST_ISMALL,
	REST_ISDRIVETHRU,
	REST_ADDRLINE1,
	REST_ADDRLINE2,
	REST_ADDRLINE3,
	REST_ADDRCITY,
	REST_ADDRCOUNTY,
	REST_ADDRSTATE,
	REST_ADDRPROVINCE,
	REST_ADDRZIP,
	REST_COUNTRY,
	REST_ADDRPHONE,
	REST_LANDLORDPHONE,
	REST_ALERTCCEMAIL,
	REST_DIVISION,
	REST_LATITUDE,
	REST_LONGITUDE,
	REST_BUILDINGTYPE,
	REST_REMODELPROG_NAME,
	REST_REMODELDT,
	REST_ACQUISITIONDT,
	REST_POSTYPE,
	REST_COMP_ISELIGIBLE,
	REST_COMP_ISTEMPCLOSURE,
	REST_COMP_DATE,
	REST_OPENDATE,
	REST_TEMP_CLOSEDATE,
	REST_TEMP_OPENDATE,
	REST_TEMPCLOSUREREASON,
	REST_CLOSEDATE,
	REST_FACILITYTYPE,
	REST_SITETYPE,
	REST_TIMEZONE,
	REST_SYSTEM_TIMEZONE,
	REST_UNITTRADEAREA,
	REST_SEATCOUNT,
	REST_PARKINGCOUNT,
	REST_SQUAREFT,
	REST_CSRASSIGNED_NAME,
	REST_CSRASSIGNED_EMAIL,
	REST_CSRDEFAULT_NAME,
	REST_CSRDEFAULT_EMAIL,
	REST_DISTCENTER_NAME,
	REST_DISTACCOUNT_NUMBER,
	REST_BAKERY_NAME,
	REST_LICENSE_NUMBER,
	REST_LICENSEEXECDATE,
	REST_LICENSEEXPDATE,
	REST_AFA_PERC,
	REST_ROYALTY_PER,
	REST_L1EMAIL,
	REST_L2NAME,
	REST_L2EMAIL,
	REST_L2PHONE,
	REST_L3NAME,
	REST_L3EMAIL,
	REST_L3PHONE,
	REST_L4NAME,
	REST_L4EMAIL,
	REST_L4PHONE,
	REST_L5NAME,
	REST_L5EMAIL,
	REST_L5PHONE,
	REST_L6NAME,
	REST_L6EMAIL,
	REST_L6PHONE,
	ARG_AREA_NUMBER,
	ARG_AREA_DESC,
	ARG_AREA_NAME,
	ARG_AREA_NUMBER_ABBR,
	ARG_DISTRICT_NUMBER,
	ARG_DISTRICT_DESC,
	ARG_DISTRICT_NAME,
	ARG_DISTRICT_NUMBER_ABBR,
	ARG_SUBREGION_NUMBER,
	ARG_SUBREGION_DESC,
	ARG_SUBREGION_NAME,
	ARG_SUBREGION_NUMBER_ABBR,
	ARG_REGION_NUMBER,
	ARG_REGION_DESC,
	ARG_REGION_NAME,
	ARG_REGION_NUMBER_ABBR,
	ARG_AREA_SUPERVISOR,
	ARG_AREA_SUPERVISOR_EMAIL,
	ARG_AREA_SUPERVISOR_PHONE,
	ARG_DO_NAME,
	ARG_DO_EMAIL,
	ARG_DO_PHONE,
	ARG_VPO_NAME,
	ARG_VPO_EMAIL,
	ARG_VPO_PHONE,
	ARG_SVP_NAME,
	ARG_SVP_EMAIL,
	ARG_SVP_PHONE,
	FRAN_TC_NAME,
	FRAN_TC_EMAIL,
	FRAN_OC_NAME,
	FRAN_OC_EMAIL,
	FRAN_DFO_NAME,
	FRAN_DFO_EMAIL,
	FRAN_CONTACT_NAME,
	FRAN_EMAIL,
	FRAN_PHONE1,
	FRAN_PHONE2,
	FRAN_ADDRLINE1,
	FRAN_ADDRCITY,
	FRAN_ADDRSTATE,
	FRAN_ADDRZIP,
	FRAN_ADDRCOUNTRY,
	EFFECTIVE_BEGIN_DATE,
	EFFECTIVE_END_DATE,
	ISCURRENT,
	INFERRED_FLAG,
	SOURCE_LOAD_ID COMMENT 'SOURCE_LOAD_ID is the LOAD_ID from the source system.',
	SOURCE_LAST_UPDATE_DATE_TIME COMMENT 'SOURCE_LAST_UPDATE_DATE_TIME is the LAST_UPDATE_DATE_TIME from the source system.',
	SOURCE_SYSTEM_NM COMMENT 'Source System Name specifies the origin of the data. For example, Salesforce Marketing App or Netsuite. Some systems will have a reference table where sources are identified by integers such as 1,2,3, etc.',
	BRAND_ID COMMENT 'Brand Identifier specifies the code which represents an organization. The identifier should be in all capital letters. Sample codes are irb (Inspire Recognized Brands), bww(Buffalo Wild Wing), arbys (Arbys),  dnkn  (Dunkin), etc.',
	LOAD_ID COMMENT 'Load Identifier specifies the Batch that inserted the record into the table.',
	LOAD_DTTM COMMENT 'Load Datetime is the date and time in UTC when the record was created. For example, 2021-08-11T15:02:24Z.',
	UPDATE_ID COMMENT 'Update Identifier specifies the batch id used for the update of the record.',
	UPDATE_DTTM COMMENT 'Update Datetime is the date and time in UTC when the record was last updated. For example, 2021-08-11T15:02:24Z.'
) COMMENT='DIM_RESTAURANT is short term solution in order to provide certain restaurant attributes until they can be incorporat6ed into long term tables.'
 as 
SELECT DIM_RESTAURANT.RESTAURANT_KEY,DIM_RESTAURANT.REST_NUMBER,DIM_RESTAURANT.REST_NAME,DIM_RESTAURANT.REST_STATUS,DIM_RESTAURANT.REST_TYPE,DIM_RESTAURANT.REST_FRAN_NUMBER,DIM_RESTAURANT.REST_FRAN_NAME,DIM_RESTAURANT.REST_FRANENTITY_NUMBER,DIM_RESTAURANT.REST_FRANENTITY_NAME,DIM_RESTAURANT.REST_COMPANY_NAME,DIM_RESTAURANT.REST_BRAND_NAME,DIM_RESTAURANT.REST_BRAND_ISACTIVE,DIM_RESTAURANT.REST_DMA_CODE,DIM_RESTAURANT.REST_DMA_DESC,DIM_RESTAURANT.REST_ISAIRPORT,DIM_RESTAURANT.REST_ISVIDEOSURV,DIM_RESTAURANT.REST_ISBREAKFAST,DIM_RESTAURANT.REST_IS24HR,DIM_RESTAURANT.REST_ISMALL,DIM_RESTAURANT.REST_ISDRIVETHRU,DIM_RESTAURANT.REST_ADDRLINE1,DIM_RESTAURANT.REST_ADDRLINE2,DIM_RESTAURANT.REST_ADDRLINE3,DIM_RESTAURANT.REST_ADDRCITY,DIM_RESTAURANT.REST_ADDRCOUNTY,DIM_RESTAURANT.REST_ADDRSTATE,DIM_RESTAURANT.REST_ADDRPROVINCE,DIM_RESTAURANT.REST_ADDRZIP,DIM_RESTAURANT.REST_COUNTRY,DIM_RESTAURANT.REST_ADDRPHONE,DIM_RESTAURANT.REST_LANDLORDPHONE,DIM_RESTAURANT.REST_ALERTCCEMAIL,DIM_RESTAURANT.REST_DIVISION,DIM_RESTAURANT.REST_LATITUDE,DIM_RESTAURANT.REST_LONGITUDE,DIM_RESTAURANT.REST_BUILDINGTYPE,DIM_RESTAURANT.REST_REMODELPROG_NAME,DIM_RESTAURANT.REST_REMODELDT,DIM_RESTAURANT.REST_ACQUISITIONDT,DIM_RESTAURANT.REST_POSTYPE,DIM_RESTAURANT.REST_COMP_ISELIGIBLE,DIM_RESTAURANT.REST_COMP_ISTEMPCLOSURE,DIM_RESTAURANT.REST_COMP_DATE,DIM_RESTAURANT.REST_OPENDATE,DIM_RESTAURANT.REST_TEMP_CLOSEDATE,DIM_RESTAURANT.REST_TEMP_OPENDATE,DIM_RESTAURANT.REST_TEMPCLOSUREREASON,DIM_RESTAURANT.REST_CLOSEDATE,DIM_RESTAURANT.REST_FACILITYTYPE,DIM_RESTAURANT.REST_SITETYPE,DIM_RESTAURANT.REST_TIMEZONE,DIM_RESTAURANT.REST_SYSTEM_TIMEZONE,DIM_RESTAURANT.REST_UNITTRADEAREA,DIM_RESTAURANT.REST_SEATCOUNT,DIM_RESTAURANT.REST_PARKINGCOUNT,DIM_RESTAURANT.REST_SQUAREFT,DIM_RESTAURANT.REST_CSRASSIGNED_NAME,DIM_RESTAURANT.REST_CSRASSIGNED_EMAIL,DIM_RESTAURANT.REST_CSRDEFAULT_NAME,DIM_RESTAURANT.REST_CSRDEFAULT_EMAIL,DIM_RESTAURANT.REST_DISTCENTER_NAME,DIM_RESTAURANT.REST_DISTACCOUNT_NUMBER,DIM_RESTAURANT.REST_BAKERY_NAME,DIM_RESTAURANT.REST_LICENSE_NUMBER,DIM_RESTAURANT.REST_LICENSEEXECDATE,DIM_RESTAURANT.REST_LICENSEEXPDATE,DIM_RESTAURANT.REST_AFA_PERC,DIM_RESTAURANT.REST_ROYALTY_PER,DIM_RESTAURANT.REST_L1EMAIL,DIM_RESTAURANT.REST_L2NAME,DIM_RESTAURANT.REST_L2EMAIL,DIM_RESTAURANT.REST_L2PHONE,DIM_RESTAURANT.REST_L3NAME,DIM_RESTAURANT.REST_L3EMAIL,DIM_RESTAURANT.REST_L3PHONE,DIM_RESTAURANT.REST_L4NAME,DIM_RESTAURANT.REST_L4EMAIL,DIM_RESTAURANT.REST_L4PHONE,DIM_RESTAURANT.REST_L5NAME,DIM_RESTAURANT.REST_L5EMAIL,DIM_RESTAURANT.REST_L5PHONE,DIM_RESTAURANT.REST_L6NAME,DIM_RESTAURANT.REST_L6EMAIL,DIM_RESTAURANT.REST_L6PHONE,DIM_RESTAURANT.ARG_AREA_NUMBER,DIM_RESTAURANT.ARG_AREA_DESC,DIM_RESTAURANT.ARG_AREA_NAME,DIM_RESTAURANT.ARG_AREA_NUMBER_ABBR,DIM_RESTAURANT.ARG_DISTRICT_NUMBER,DIM_RESTAURANT.ARG_DISTRICT_DESC,DIM_RESTAURANT.ARG_DISTRICT_NAME,DIM_RESTAURANT.ARG_DISTRICT_NUMBER_ABBR,DIM_RESTAURANT.ARG_SUBREGION_NUMBER,DIM_RESTAURANT.ARG_SUBREGION_DESC,DIM_RESTAURANT.ARG_SUBREGION_NAME,DIM_RESTAURANT.ARG_SUBREGION_NUMBER_ABBR,DIM_RESTAURANT.ARG_REGION_NUMBER,DIM_RESTAURANT.ARG_REGION_DESC,DIM_RESTAURANT.ARG_REGION_NAME,DIM_RESTAURANT.ARG_REGION_NUMBER_ABBR,DIM_RESTAURANT.ARG_AREA_SUPERVISOR,DIM_RESTAURANT.ARG_AREA_SUPERVISOR_EMAIL,DIM_RESTAURANT.ARG_AREA_SUPERVISOR_PHONE,DIM_RESTAURANT.ARG_DO_NAME,DIM_RESTAURANT.ARG_DO_EMAIL,DIM_RESTAURANT.ARG_DO_PHONE,DIM_RESTAURANT.ARG_VPO_NAME,DIM_RESTAURANT.ARG_VPO_EMAIL,DIM_RESTAURANT.ARG_VPO_PHONE,DIM_RESTAURANT.ARG_SVP_NAME,DIM_RESTAURANT.ARG_SVP_EMAIL,DIM_RESTAURANT.ARG_SVP_PHONE,DIM_RESTAURANT.FRAN_TC_NAME,DIM_RESTAURANT.FRAN_TC_EMAIL,DIM_RESTAURANT.FRAN_OC_NAME,DIM_RESTAURANT.FRAN_OC_EMAIL,DIM_RESTAURANT.FRAN_DFO_NAME,DIM_RESTAURANT.FRAN_DFO_EMAIL,DIM_RESTAURANT.FRAN_CONTACT_NAME,DIM_RESTAURANT.FRAN_EMAIL,DIM_RESTAURANT.FRAN_PHONE1,DIM_RESTAURANT.FRAN_PHONE2,DIM_RESTAURANT.FRAN_ADDRLINE1,DIM_RESTAURANT.FRAN_ADDRCITY,DIM_RESTAURANT.FRAN_ADDRSTATE,DIM_RESTAURANT.FRAN_ADDRZIP,DIM_RESTAURANT.FRAN_ADDRCOUNTRY,DIM_RESTAURANT.EFFECTIVE_BEGIN_DATE,DIM_RESTAURANT.EFFECTIVE_END_DATE,DIM_RESTAURANT.ISCURRENT,DIM_RESTAURANT.INFERRED_FLAG,DIM_RESTAURANT.SOURCE_LOAD_ID,DIM_RESTAURANT.SOURCE_LAST_UPDATE_DATE_TIME,DIM_RESTAURANT.SOURCE_SYSTEM_NM,DIM_RESTAURANT.BRAND_ID,DIM_RESTAURANT.LOAD_ID,DIM_RESTAURANT.LOAD_DTTM,DIM_RESTAURANT.UPDATE_ID,DIM_RESTAURANT.UPDATE_DTTM
FROM IDS_DEV.LOCN.DIM_RESTAURANT ;
create view IF NOT EXISTS ECOSURE_RESTAURANT_AUDIT_BV(
	BRAND_ID COMMENT 'Brand Identifier specifies the code which represents an organization. The identifier should be in all capital letters. Sample codes are irb (Inspire Recognized Brands), bww(Buffalo Wild Wing), arbys (Arbys),  dnkn  (Dunkin), etc.',
	ECOSURE_AUDIT_ID COMMENT 'Ecosure Audit Identifier is a unique integer value to identify an audit.',
	AUDIT_DT COMMENT 'Audit Date is the day of the audit.',
	ECOSURE_CONCEPT_NBR COMMENT 'ECOSURE CONCEPT NUMBER is a location attribute. Sample value ARB.',
	STORE_ID COMMENT 'Store Identifier is an integer that uniquely identifies the store.',
	ECOSURE_AUDITOR_ID COMMENT 'ECOSURE AUDITOR IDENTIFIER uniquely identifies an indvidual auditor.',
	ECOSURE_CYCLE_QTY COMMENT 'ECOSURE CYCLE QUANTITY is the number of rounds of an audit.',
	ECOSURE_VISIT_QTY COMMENT 'ECOSURE VISIT QUANTITY is the count of visits within a cycle.',
	ECOSURE_REFERENCE_NBR COMMENT 'ECOSURE REFERENCE NUMBER is the Internal EcoSure program number. Sample value AY2018.',
	ECOSURE_NOTE_TXT COMMENT 'ECOSURE NOTE TEXT are audit level notes.',
	ECOSURE_STORE_ID COMMENT 'ECOSURE STORE IDENTIFIER si the unique EcoSure location id.',
	ECOSURE_FORM_NM COMMENT 'ECOSURE FORM NAME is the program audit form name. Sample value Arby''s Safety First (S).',
	SOURCE_SYSTEM_NM COMMENT 'Source System Name specifies the origin of the data. For example, Salesforce Marketing App or Netsuite. Some systems will have a reference table where sources are identified by integers such as 1,2,3, etc.',
	LOAD_ID COMMENT 'Load Identifier specifies the Batch that inserted the record into the table.',
	LOAD_DTTM COMMENT 'Load Datetime is the date and time in UTC when the record was created. For example, 2021-08-11T15:02:24Z.',
	UPDATE_ID COMMENT 'Update Identifier specifies the batch id used for the update of the record.',
	UPDATE_DTTM COMMENT 'Update Datetime is the date and time in UTC when the record was last updated. For example, 2021-08-11T15:02:24Z.'
) COMMENT='ECOSURE_RESTAURANT_AUDIT identifies the audit level information for a particular store that is sourced from ECOSURE.'
 as 
SELECT ECOSURE_RESTAURANT_AUDIT.BRAND_ID,ECOSURE_RESTAURANT_AUDIT.ECOSURE_AUDIT_ID,ECOSURE_RESTAURANT_AUDIT.AUDIT_DT,ECOSURE_RESTAURANT_AUDIT.ECOSURE_CONCEPT_NBR,ECOSURE_RESTAURANT_AUDIT.STORE_ID,ECOSURE_RESTAURANT_AUDIT.ECOSURE_AUDITOR_ID,ECOSURE_RESTAURANT_AUDIT.ECOSURE_CYCLE_QTY,ECOSURE_RESTAURANT_AUDIT.ECOSURE_VISIT_QTY,ECOSURE_RESTAURANT_AUDIT.ECOSURE_REFERENCE_NBR,ECOSURE_RESTAURANT_AUDIT.ECOSURE_NOTE_TXT,ECOSURE_RESTAURANT_AUDIT.ECOSURE_STORE_ID,ECOSURE_RESTAURANT_AUDIT.ECOSURE_FORM_NM,ECOSURE_RESTAURANT_AUDIT.SOURCE_SYSTEM_NM,ECOSURE_RESTAURANT_AUDIT.LOAD_ID,ECOSURE_RESTAURANT_AUDIT.LOAD_DTTM,ECOSURE_RESTAURANT_AUDIT.UPDATE_ID,ECOSURE_RESTAURANT_AUDIT.UPDATE_DTTM
FROM IDS_DEV.LOCN.ECOSURE_RESTAURANT_AUDIT ;
create view IF NOT EXISTS ECOSURE_RESTAURANT_AUDIT_SCORE_BV(
	BRAND_ID COMMENT 'Brand Identifier specifies the code which represents an organization. The identifier should be in all capital letters. Sample codes are irb (Inspire Recognized Brands), bww(Buffalo Wild Wing), arbys (Arbys),  dnkn  (Dunkin), etc.',
	ECOSURE_AUDIT_ID COMMENT 'Ecosure Audit Identifier is a unique integer value to identify an audit.',
	ECOSURE_SCORE_NM COMMENT 'ECOSURE SCORE NAME is the label for the score. Sample value: Overall Score.',
	ECOSURE_SCORE_AMT COMMENT 'ECOSURE SCORE AMOUNT is a decimal value from 0 to 100. Sample Values 93.4, 82, and 62.8.',
	ECOSURE_RATING_VAL COMMENT 'ECOSURE RATING VALUE a single letter value denoting the score. Sample Values A, B, C, and F.',
	ECOSURE_IN_COMPLIANCE_QTY COMMENT 'ECOSURE IN COMPLIANCE QUANTITY is the count of items in compliance.',
	ECOSURE_OUT_OF_COMPLIANCE_QTY COMMENT 'ECOSURE OUT OF COMPLIANCE QUANTITY  is the count of items in out of compliance.',
	SOURCE_SYSTEM_NM COMMENT 'Source System Name specifies the origin of the data. For example, Salesforce Marketing App or Netsuite. Some systems will have a reference table where sources are identified by integers such as 1,2,3, etc.',
	LOAD_ID COMMENT 'Load Identifier specifies the Batch that inserted the record into the table.',
	LOAD_DTTM COMMENT 'Load Datetime is the date and time in UTC when the record was created. For example, 2021-08-11T15:02:24Z.',
	UPDATE_ID COMMENT 'Update Identifier specifies the batch id used for the update of the record.',
	UPDATE_DTTM COMMENT 'Update Datetime is the date and time in UTC when the record was last updated. For example, 2021-08-11T15:02:24Z.'
) COMMENT='ECOSURE_RESTAURANT_AUDIT SCORE contains the scores at an audit aggregate level for a store that is sourced from ECOSURE.'
 as 
SELECT ECOSURE_RESTAURANT_AUDIT_SCORE.BRAND_ID,ECOSURE_RESTAURANT_AUDIT_SCORE.ECOSURE_AUDIT_ID,ECOSURE_RESTAURANT_AUDIT_SCORE.ECOSURE_SCORE_NM,ECOSURE_RESTAURANT_AUDIT_SCORE.ECOSURE_SCORE_AMT,ECOSURE_RESTAURANT_AUDIT_SCORE.ECOSURE_RATING_VAL,ECOSURE_RESTAURANT_AUDIT_SCORE.ECOSURE_IN_COMPLIANCE_QTY,ECOSURE_RESTAURANT_AUDIT_SCORE.ECOSURE_OUT_OF_COMPLIANCE_QTY,ECOSURE_RESTAURANT_AUDIT_SCORE.SOURCE_SYSTEM_NM,ECOSURE_RESTAURANT_AUDIT_SCORE.LOAD_ID,ECOSURE_RESTAURANT_AUDIT_SCORE.LOAD_DTTM,ECOSURE_RESTAURANT_AUDIT_SCORE.UPDATE_ID,ECOSURE_RESTAURANT_AUDIT_SCORE.UPDATE_DTTM
FROM IDS_DEV.LOCN.ECOSURE_RESTAURANT_AUDIT_SCORE ;
create view IF NOT EXISTS LOCATION_HIERARCHY_PLR_BV(
	LOCATIONID,
	L1ID,
	L1NAME,
	L1MANAGERID,
	L1MANAGER,
	L2ID,
	L2NAME,
	L2MANAGERID,
	L2MANAGER,
	L3ID,
	L3NAME,
	L3MANAGERID,
	L3MANAGER,
	L4ID,
	L4NAME,
	L4MANAGERID,
	L4MANAGER,
	L5ID,
	L5NAME,
	L5MANAGERID,
	L5MANAGER,
	BRANDID,
	SOURCE,
	CDMLOADDATE,
	LOADTYPE,
	FILENAME
) as SELECT
                               LOCATIONID, L1ID, L1NAME, L1MANAGERID, L1MANAGER, L2ID, L2NAME, L2MANAGERID, L2MANAGER, L3ID, L3NAME, L3MANAGERID, L3MANAGER, L4ID, L4NAME, L4MANAGERID, L4MANAGER, L5ID, L5NAME, L5MANAGERID, L5MANAGER, BRANDID, SOURCE, CDMLOADDATE, LOADTYPE, FILENAME
                            FROM CDMSYNC_DEV.IRB."LOCATION_HIERARCHY_PLR";
create view IF NOT EXISTS LOC_DIVISION_PLR_BV(
	DIVISIONNUMBER,
	DIVISIONNAME,
	BRANDID,
	CDMLOADDATE,
	FILENAME
) as SELECT
                               DIVISIONNUMBER, DIVISIONNAME, BRANDID, CDMLOADDATE, FILENAME
                            FROM CDMSYNC_DEV.IRB."LOC_DIVISION_PLR";
create view IF NOT EXISTS LOC_DMA_PLR_BV(
	DMACODE,
	DMASOURCENAME,
	DMANAME,
	BRANDID,
	SOURCE,
	CDMLOADDATE,
	FILENAME
) as SELECT
                               DMACODE, DMASOURCENAME, DMANAME, BRANDID, SOURCE, CDMLOADDATE, FILENAME
                            FROM CDMSYNC_DEV.IRB."LOC_DMA_PLR";
create view IF NOT EXISTS LOC_HIERARCHY_PLR_BV(
	STOREID,
	L1ID,
	L1NAME,
	L1MANAGERID,
	L1MANAGER,
	L2ID,
	L2NAME,
	L2MANAGERID,
	L2MANAGER,
	L3ID,
	L3NAME,
	L3MANAGERID,
	L3MANAGER,
	L4ID,
	L4NAME,
	L4MANAGERID,
	L4MANAGER,
	L5ID,
	L5NAME,
	L5MANAGERID,
	L5MANAGER,
	BRANDID,
	SOURCE,
	CDMLOADDATE,
	LOADTYPE,
	FILENAME
) as SELECT
                               STOREID, L1ID, L1NAME, L1MANAGERID, L1MANAGER, L2ID, L2NAME, L2MANAGERID, L2MANAGER, L3ID, L3NAME, L3MANAGERID, L3MANAGER, L4ID, L4NAME, L4MANAGERID, L4MANAGER, L5ID, L5NAME, L5MANAGERID, L5MANAGER, BRANDID, SOURCE, CDMLOADDATE, LOADTYPE, FILENAME
                            FROM CDMSYNC_DEV.IRB."LOC_HIERARCHY_PLR";
create view IF NOT EXISTS LOC_OWNERSHIP_STATUS_PLR_BV(
	STOREID,
	OWNERID,
	ISFRANCHISEE,
	EFFECTIVEDATE,
	ROYALTYRATE,
	COOPRATE,
	MARKETINGRATE,
	RATECHANGEEFFECTIVEDATE,
	LEASEAGMTTYPE,
	LEASEEXPIRATIONDATE,
	LEASEEXECUTIONDATE,
	SOURCE,
	BRANDID,
	CDMLOADDATE,
	FILENAME
) as SELECT
                               STOREID, OWNERID, ISFRANCHISEE, EFFECTIVEDATE, ROYALTYRATE, COOPRATE, MARKETINGRATE, RATECHANGEEFFECTIVEDATE, LEASEAGMTTYPE, LEASEEXPIRATIONDATE, LEASEEXECUTIONDATE, SOURCE, BRANDID, CDMLOADDATE, FILENAME
                            FROM CDMSYNC_DEV.IRB."LOC_OWNERSHIP_STATUS_PLR";
create view IF NOT EXISTS LOC_OWNER_PLR_BV(
	OWNERNAME,
	OWNERID,
	EMAIL,
	PHONE,
	ADDRESS1,
	ADDRESS2,
	ADDRESS3,
	CITY,
	STATE,
	ZIP,
	COUNTRY,
	FAX,
	DATEENTERED,
	DATELEFT,
	SOURCE,
	BRANDID,
	CDMLOADDATE,
	FILENAME
) as SELECT
                               OWNERNAME, OWNERID, EMAIL, PHONE, ADDRESS1, ADDRESS2, ADDRESS3, CITY, STATE, ZIP, COUNTRY, FAX, DATEENTERED, DATELEFT, SOURCE, BRANDID, CDMLOADDATE, FILENAME
                            FROM CDMSYNC_DEV.IRB."LOC_OWNER_PLR";
create view IF NOT EXISTS LOC_REMODEL_PLR_BV(
	REMODELID,
	STOREID,
	EFFECTIVEDATE,
	REMODELLEVEL,
	REMODELACTIVITYTYPE,
	REMODELPROGRAM,
	CONSTRUCTIONSTATUS,
	PROJECTEDUNDERCONSTRUCTIONDATE,
	UNDERCONSTRUCTIONDATE,
	COMPLETEDDATE,
	CONSTRUCTIONDUEDATE,
	SOURCE,
	BRANDID,
	CDMLOADDATE,
	FILENAME
) as SELECT
                               REMODELID, STOREID, EFFECTIVEDATE, REMODELLEVEL, REMODELACTIVITYTYPE, REMODELPROGRAM, CONSTRUCTIONSTATUS, PROJECTEDUNDERCONSTRUCTIONDATE, UNDERCONSTRUCTIONDATE, COMPLETEDDATE, CONSTRUCTIONDUEDATE, SOURCE, BRANDID, CDMLOADDATE, FILENAME
                            FROM CDMSYNC_DEV.IRB."LOC_REMODEL_PLR";
create view IF NOT EXISTS LOC_STORE_PLR_BV(
	STOREID,
	BRANDID,
	SITEID,
	NAME,
	ADDRESS1,
	ADDRESS2,
	ADDRESS3,
	CITY,
	COUNTRY,
	STATE,
	PROVINCE,
	ZIP,
	STOREEMAIL,
	STOREPHONE,
	DIVISIONNUMBER,
	OPENDATE,
	CLOSUREDATE,
	DMACODE,
	TIMEZONE,
	LATITUDE,
	LONGITUDE,
	FACILITYTYPE,
	BUILDINGTYPE,
	PARKINGCOUNT,
	SEATCOUNT,
	BLDGSQFT,
	ISBREAKFAST,
	ISDRIVETHRU,
	OWNERSHIPTYPE,
	STORESTATUS,
	SOURCE,
	CDMLOADDATE,
	FILENAME
) as SELECT
                               STOREID, BRANDID, SITEID, NAME, ADDRESS1, ADDRESS2, ADDRESS3, CITY, COUNTRY, STATE, PROVINCE, ZIP, STOREEMAIL, STOREPHONE, DIVISIONNUMBER, OPENDATE, CLOSUREDATE, DMACODE, TIMEZONE, LATITUDE, LONGITUDE, FACILITYTYPE, BUILDINGTYPE, PARKINGCOUNT, SEATCOUNT, BLDGSQFT, ISBREAKFAST, ISDRIVETHRU, OWNERSHIPTYPE, STORESTATUS, SOURCE, CDMLOADDATE, FILENAME
                            FROM CDMSYNC_DEV.IRB."LOC_STORE_PLR";
create view IF NOT EXISTS LOC_TEMP_CLOSURE_PLR_BV(
	STOREID,
	TEMPCLOSED,
	REOPEN,
	TEMPCLOSUREREASON,
	SOURCE,
	BRANDID,
	CDMLOADDATE,
	FILENAME
) as SELECT
                               STOREID, TEMPCLOSED, REOPEN, TEMPCLOSUREREASON, SOURCE, BRANDID, CDMLOADDATE, FILENAME
                            FROM CDMSYNC_DEV.IRB."LOC_TEMP_CLOSURE_PLR";
create view IF NOT EXISTS SALES_FORECAST_DAY_BV(
	REST_ID,
	BRAND_ID,
	BUSINESS_DATE,
	SALES_AMT,
	TRANS_CNT,
	FORECAST_TYPE,
	SOURCE_SYSTEM_NAME,
	CDM_LOAD_DATE,
	LOAD_TYPE,
	LOAD_ID,
	LOAD_DTTM
) as 
SELECT c.STOREID AS REST_ID
,c.BRANDID AS BRAND_ID
,TRY_TO_DATE(c.BUSINESSDATE,'YYYYMMDD') AS BUSINESS_DATE
,TRY_TO_NUMBER(c.SALESAMOUNT,38,3) AS SALES_AMT
,TRY_TO_NUMBER(c.NUMBEROFTRANSACTIONS) AS TRANS_CNT
,c.FORECASTTYPE AS FORECAST_TYPE
,c.SOURCE AS SOURCE_SYSTEM_NAME
,TRY_TO_DATE(c.CDMLOADDATE,'YYYYMMDD') AS CDM_LOAD_DATE
,c.LOADTYPE AS LOAD_TYPE
, TRY_TO_NUMBER(c.CDMLOADDATE) AS LOAD_ID
, TRY_TO_TIMESTAMP(c.CDMLOADDATE,'YYYYMMDD') AS LOAD_DTTM
FROM CDMSYNC_DEV.IRB.STR_OPS_SALESFORECAST_DAY_PLR c;
create view IF NOT EXISTS SALES_FORECAST_QTR_HR_BV(
	REST_ID,
	BRAND_ID,
	BUSINESS_DATE,
	QTR_HOUR_BEGIN_DTTM,
	QTR_HOUR_END_DTTM,
	SALES_AMT,
	TRANS_CNT,
	FORECAST_TYPE,
	LOAD_TYPE,
	SOURCE_SYSTEM_NAME,
	CDM_LOAD_DATE,
	LOAD_ID,
	LOAD_DTTM
) as 
SELECT c.STOREID AS REST_ID
,c.BRANDID AS BRAND_ID
,try_to_date(c.BUSINESSDATE,'YYYYMMDD')  AS BUSINESS_DATE  -- cast added 2022-07-14
,try_to_timestamp(c.QUARTERHOURBEGIN) AS QTR_HOUR_BEGIN_DTTM -- cast added 2022-07-14
,try_to_timestamp(c.QUARTERHOUREND) AS QTR_HOUR_END_DTTM -- cast added 2022-07-14
,c.SALESAMOUNT AS SALES_AMT
,c.NUMBEROFTRANSACTIONS AS TRANS_CNT
,c.FORECASTTYPE AS FORECAST_TYPE
,c.LOADTYPE AS LOAD_TYPE
,c.SOURCE AS SOURCE_SYSTEM_NAME
,try_to_date(c.CDMLOADDATE,'YYYYMMDD') AS CDM_LOAD_DATE -- cast added 2022-07-14
,try_to_number(c.CDMLOADDATE) AS LOAD_ID -- cast added 2022-07-14
,try_to_timestamp(c.CDMLOADDATE,'YYYYMMDD') AS LOAD_DTTM -- cast added 2022-07-14
FROM CDMSYNC_DEV.IRB.STR_OPS_SALESFORECAST_QTRHR_PLR c;
create view IF NOT EXISTS SCHEDULED_AND_ACTUAL_HRS_BV(
	EMPLOYEE_PUNCHES_KEY,
	REST_ID,
	DATE,
	CLOCK_IN_DATE,
	CLOCK_IN_TIME,
	CLOCK_OUT_DATE,
	CLOCK_OUT_TIME,
	PUNCH_TYPE,
	ACTIVITY_TYPE,
	HOURS,
	JOB_CODE,
	BRAND_ID,
	LAST_NAME,
	FIRST_NAME,
	LOAD_TYPE,
	SOURCE_SYSTEM_NAME,
	CDM_LOAD_DATE,
	LOAD_ID,
	LOAD_DTTM
) as 
SELECT c.EMPLOYEEPUNCHESKEY AS EMPLOYEE_PUNCHES_KEY
,c.STOREID AS REST_ID
,TRY_TO_DATE(c.BUSINESSDATE,'YYYYMMDD') AS DATE
,TRY_TO_DATE(c.CLOCKINDATE,'YYYYMMDD') AS CLOCK_IN_DATE
,TRY_TO_TIME(c.CLOCKINTIME) AS CLOCK_IN_TIME
,TRY_TO_DATE(c.CLOCKOUTDATE,'YYYYMMDD') AS CLOCK_OUT_DATE
,TRY_TO_TIME(c.CLOCKOUTTIME) AS CLOCK_OUT_TIME
,c.PUNCHTYPE AS PUNCH_TYPE
,c.ACTIVITYTYPE AS ACTIVITY_TYPE
,c.HOURS AS HOURS
,c.JOBCODE AS JOB_CODE
,c.BRANDID AS BRAND_ID
,c.LASTNAME AS LAST_NAME
,c.FIRSTNAME AS FIRST_NAME
,c.LOADTYPE AS LOAD_TYPE
,c.SOURCE AS SOURCE_SYSTEM_NAME
,TRY_TO_DATE(c.CDMLOADDATE,'YYYYMMDD') AS CDM_LOAD_DATE
,TRY_TO_NUMBER(c.CDMLOADDATE) AS LOAD_ID
,TRY_TO_TIMESTAMP(c.CDMLOADDATE,'YYYYMMDD') AS LOAD_DTTM
FROM CDMSYNC_DEV.IRB.STR_OPS_SCHEDULEDANDACTUALHOURS_PLR c;
create view IF NOT EXISTS SPEED_OF_SERVICE_BV(
	REST_ID,
	BUSINESS_DATE,
	CAR_ID,
	DAYPART,
	ARRIVAL_DTTM,
	DEPARTURE_DTTM,
	GOAL_NAME,
	REPORTING_NAME,
	GOAL_SECONDS_NBR,
	SERVICE_POINT_NBR,
	DISCARD_IND,
	DISCARD_CODE,
	BRAND_ID,
	SOURCE_SYSTEM_NAME,
	CDM_LOAD_DATE,
	LOAD_TYPE,
	LOAD_ID,
	LOAD_DTTM
) as 
SELECT c.STOREID AS REST_ID
,try_to_date(c.BUSINESSDATE,'YYYYMMDD') AS BUSINESS_DATE
,c.CARID AS CAR_ID
,c.DAYPARTNAME AS DAYPART
,try_to_timestamp(c.ARRIVAL) AS ARRIVAL_DTTM
,try_to_timestamp(c.DEPARTURE) AS DEPARTURE_DTTM
,c.GOALNAME AS GOAL_NAME
,c.REPORTINGNAME AS REPORTING_NAME
,try_to_number(c.GOALSECONDS) AS GOAL_SECONDS_NBR
,try_to_number(c.SERVICEPOINTTIME) AS SERVICE_POINT_NBR
,TRY_TO_BOOLEAN(c.DISCARD) AS DISCARD_IND
,c.DISCARDCODE AS DISCARD_CODE
,c.BRANDID AS BRAND_ID
,c.SOURCE AS SOURCE_SYSTEM_NAME
,try_to_date(c.CDMLOADDATE,'YYYYMMDD') AS CDM_LOAD_DATE
,c.LOADTYPE AS LOAD_TYPE
,try_to_number(c.CDMLOADDATE) AS LOAD_ID
,try_to_timestamp(c.CDMLOADDATE,'YYYYMMDD') AS LOAD_DTTM
FROM CDMSYNC_DEV.IRB.STR_OPS_SPEEDOFSERVICE_PLR c;
create view IF NOT EXISTS STR_OPS_SALESFORECAST_DAY_PLR_BV(
	STOREID,
	BRANDID,
	BUSINESSDATE,
	SALESAMOUNT,
	NUMBEROFTRANSACTIONS,
	FORECASTTYPE,
	SOURCE,
	CDMLOADDATE,
	LOADTYPE,
	FILENAME
) as SELECT
                               "STOREID", "BRANDID", "BUSINESSDATE", "SALESAMOUNT", "NUMBEROFTRANSACTIONS", "FORECASTTYPE", "SOURCE", "CDMLOADDATE", "LOADTYPE", "FILENAME"
                            FROM CDMSYNC_DEV.IRB."STR_OPS_SALESFORECAST_DAY_PLR";
create view IF NOT EXISTS STR_OPS_SALESFORECAST_QTRHR_PLR_BV(
	STOREID,
	BRANDID,
	BUSINESSDATE,
	QUARTERHOURBEGIN,
	QUARTERHOUREND,
	SALESAMOUNT,
	NUMBEROFTRANSACTIONS,
	FORECASTTYPE,
	LOADTYPE,
	SOURCE,
	CDMLOADDATE,
	FILENAME
) as SELECT
                               "STOREID", "BRANDID", "BUSINESSDATE", "QUARTERHOURBEGIN", "QUARTERHOUREND", "SALESAMOUNT", "NUMBEROFTRANSACTIONS", "FORECASTTYPE", "LOADTYPE", "SOURCE", "CDMLOADDATE", "FILENAME"
                            FROM CDMSYNC_DEV.IRB."STR_OPS_SALESFORECAST_QTRHR_PLR";
create view IF NOT EXISTS STR_OPS_SCHEDULEDANDACTUALHOURS_PLR_BV(
	EMPLOYEEPUNCHESKEY,
	STOREID,
	BUSINESSDATE,
	CLOCKINDATE,
	CLOCKINTIME,
	CLOCKOUTDATE,
	CLOCKOUTTIME,
	PUNCHTYPE,
	ACTIVITYTYPE,
	HOURS,
	JOBCODE,
	BRANDID,
	LASTNAME,
	FIRSTNAME,
	LOADTYPE,
	SOURCE,
	CDMLOADDATE,
	FILENAME
) as SELECT
                               "EMPLOYEEPUNCHESKEY", "STOREID", "BUSINESSDATE", "CLOCKINDATE", "CLOCKINTIME", "CLOCKOUTDATE", "CLOCKOUTTIME", "PUNCHTYPE", "ACTIVITYTYPE", "HOURS", "JOBCODE", "BRANDID", "LASTNAME", "FIRSTNAME", "LOADTYPE", "SOURCE", "CDMLOADDATE", "FILENAME"
                            FROM CDMSYNC_DEV.IRB."STR_OPS_SCHEDULEDANDACTUALHOURS_PLR";
create view IF NOT EXISTS STR_OPS_SPEEDOFSERVICE_PLR_BV(
	STOREID,
	BUSINESSDATE,
	CARID,
	DAYPARTNAME,
	ARRIVAL,
	DEPARTURE,
	GOALNAME,
	REPORTINGNAME,
	GOALSECONDS,
	SERVICEPOINTTIME,
	DISCARD,
	DISCARDCODE,
	BRANDID,
	SOURCE,
	CDMLOADDATE,
	LOADTYPE,
	FILENAME
) as SELECT
                               "STOREID", "BUSINESSDATE", "CARID", "DAYPARTNAME", "ARRIVAL", "DEPARTURE", "GOALNAME", "REPORTINGNAME", "GOALSECONDS", "SERVICEPOINTTIME", "DISCARD", "DISCARDCODE", "BRANDID", "SOURCE", "CDMLOADDATE", "LOADTYPE", "FILENAME"
                            FROM CDMSYNC_DEV.IRB."STR_OPS_SPEEDOFSERVICE_PLR";
create view IF NOT EXISTS STR_OPS_STOREHOURS_PLR_BV(
	STOREID,
	DAYOFWEEK,
	OPENTIME,
	CLOSETIME,
	BRANDID,
	CDMLOADDATE,
	SOURCE,
	FILENAME
) as SELECT
                               "STOREID", "DAYOFWEEK", "OPENTIME", "CLOSETIME", "BRANDID", "CDMLOADDATE", "SOURCE", "FILENAME"
                            FROM CDMSYNC_DEV.IRB."STR_OPS_STOREHOURS_PLR";
create view IF NOT EXISTS STR_OPS_VISITSURVEY_PLR_BV(
	SURVEYID,
	STOREID,
	SURVEYDATE,
	QUESTIONID,
	QUESTIONLABEL,
	QUESTIONTEXT,
	RESPONSETEXT,
	POINTSPOSSIBLE,
	BRANDID,
	CDMLOADDATE,
	FILENAME
) as SELECT
                               "SURVEYID", "STOREID", "SURVEYDATE", "QUESTIONID", "QUESTIONLABEL", "QUESTIONTEXT", "RESPONSETEXT", "POINTSPOSSIBLE", "BRANDID", "CDMLOADDATE", "FILENAME"
                            FROM CDMSYNC_DEV.IRB."STR_OPS_VISITSURVEY_PLR";
create view IF NOT EXISTS VISIT_SURVEY_BV(
	SURVEY_ID,
	REST_ID,
	SURVEY_DATE,
	QUESTION_ID,
	QUESTION_LABEL_TXT,
	QUESTION_TXT,
	RESPONSE_TXT,
	POINTS_POSSIBLE_NBR,
	BRAND_ID,
	CDM_LOAD_DATE,
	LOAD_ID,
	LOAD_DTTM
) as 
SELECT c.SURVEYID AS SURVEY_ID
,c.STOREID AS REST_ID
,try_to_timestamp(c.SURVEYDATE) AS SURVEY_DATE
,c.QUESTIONID AS QUESTION_ID
,c.QUESTIONLABEL AS QUESTION_LABEL_TXT
,c.QUESTIONTEXT AS QUESTION_TXT
,c.RESPONSETEXT AS RESPONSE_TXT
,c.POINTSPOSSIBLE AS POINTS_POSSIBLE_NBR
,c.BRANDID AS BRAND_ID
,try_to_date(c.CDMLOADDATE,'YYYYMMDD')  AS CDM_LOAD_DATE
,try_to_number(c.CDMLOADDATE) AS LOAD_ID
,try_to_timestamp(c.CDMLOADDATE,'YYYYMMDD')  AS LOAD_DTTM
FROM CDMSYNC_DEV.IRB.STR_OPS_VISITSURVEY_PLR c;
CREATE PROCEDURE IF NOT EXISTS SP_BASE_VIEW_CREATION_IMPLEMENTATION("SRC_DB_PARAM" VARCHAR(16777216), "SRC_SCHEMA_PARAM" VARCHAR(16777216), "DST_DB_PARAM" VARCHAR(16777216), "DST_SCHEMA_PARAM" VARCHAR(16777216), "SRC_TB_PREFIXES_PARAM" VARCHAR(16777216))
RETURNS VARCHAR(16777216)
LANGUAGE JAVASCRIPT
EXECUTE AS CALLER
AS '
    function prepareSelectTableNames(src_tb_prefixes) {

      var where_table_name_stmt = "";

      if (src_tb_prefixes) {
         var src_db_prefixes_array = src_tb_prefixes.split('','')

         if (src_db_prefixes_array.length > 1){
             where_table_name_stmt += ` AND TABLE_NAME LIKE ''${src_db_prefixes_array.shift()}%''`
             for (const prefix of src_db_prefixes_array) {
                 where_table_name_stmt += ` OR table_name LIKE ''${prefix}%''`;
             }
         } else {
             where_table_name_stmt += ` AND TABLE_NAME LIKE ''${SRC_TB_PREFIXES_PARAM}%''`;
         }
      }
      return `SELECT table_name FROM ` + SRC_DB_PARAM + `.INFORMATION_SCHEMA.TABLES where TABLE_CATALOG = :1 AND Table_schema = :2 and TABLE_TYPE = ''BASE TABLE'' ${where_table_name_stmt};`;
    }

    var select_table_names = prepareSelectTableNames(SRC_TB_PREFIXES_PARAM);

    var select_column_names = `SELECT column_name FROM ` + SRC_DB_PARAM + `.INFORMATION_SCHEMA.COLUMNS where TABLE_CATALOG = :1 AND Table_schema = :2 and TABLE_NAME = :3 order by ordinal_position;`

    var select_table_names_stmt = snowflake.createStatement(
                {
                sqlText: select_table_names,
                binds: [SRC_DB_PARAM, SRC_SCHEMA_PARAM]
                }
        );

    var table_names = select_table_names_stmt.execute();

    var table_name_array=[];
    while(table_names.next())
    {
        table_name_array.push(table_names.getColumnValue(1));
    }

    for (const table_name of table_name_array) {

        var select_column_names_stmt = snowflake.createStatement(
                {
                sqlText: select_column_names,
                binds: [SRC_DB_PARAM, SRC_SCHEMA_PARAM, table_name]
                }
        );

        var column_names = select_column_names_stmt.execute();
        var column_name_array=[];
        while(column_names.next())
        {
            column_name_array.push(column_names.getColumnValue(1));
        }
        var column_name_array = column_name_array.map(x => `${x} AS ${x}`);

        var source_tb_columns = column_name_array.join('', '');

        var view_template = `CREATE VIEW IF NOT EXISTS ` + DST_DB_PARAM + `.` + DST_SCHEMA_PARAM + `.${table_name}_BV COPY GRANTS
                            AS SELECT
                               ${source_tb_columns}
                            FROM ` + SRC_DB_PARAM + `.` + SRC_SCHEMA_PARAM + `."${table_name}";`
//        var execute_base_view_stmt = snowflake.createStatement(
//        {
//            sqlText: view_template
//        });
//        execute_base_view_stmt.execute();
    }
    try {

        return view_template;
        }
    catch (err)  {
        throw err;
        }
    ';
CREATE PROCEDURE IF NOT EXISTS SP_BASE_VIEW_CREATION_IMPLEMENTATION_WITH_COMMENTS("SRC_DB_PARAM" VARCHAR(16777216), "SRC_SCHEMA_PARAM" VARCHAR(16777216), "DST_DB_PARAM" VARCHAR(16777216), "DST_SCHEMA_PARAM" VARCHAR(16777216), "SRC_TB_PREFIXES_PARAM" VARCHAR(16777216))
RETURNS VARCHAR(16777216)
LANGUAGE JAVASCRIPT
EXECUTE AS CALLER
AS '
    function prepareSelectTableNames(src_tb_prefixes) {

      var where_table_name_stmt = "";

      if (src_tb_prefixes) {
         var src_db_prefixes_array = src_tb_prefixes.split('','')

         if (src_db_prefixes_array.length > 1){
             where_table_name_stmt += ` AND TABLE_NAME LIKE ''${src_db_prefixes_array.shift()}%''`
             for (const prefix of src_db_prefixes_array) {
                 where_table_name_stmt += ` OR table_name LIKE ''${prefix}%''`;
             }
         } else {
             where_table_name_stmt += ` AND TABLE_NAME LIKE ''${SRC_TB_PREFIXES_PARAM}%''`;
         }
      }
      return `SELECT table_name FROM ` + SRC_DB_PARAM + `.INFORMATION_SCHEMA.TABLES where TABLE_CATALOG = :1 AND Table_schema = :2 and TABLE_TYPE = ''BASE TABLE'' ${where_table_name_stmt};`;
    }

    var select_table_names = prepareSelectTableNames(SRC_TB_PREFIXES_PARAM);

    var select_column_names = `SELECT column_name, comment FROM ` + SRC_DB_PARAM + `.INFORMATION_SCHEMA.COLUMNS where TABLE_CATALOG = :1 AND Table_schema = :2 and TABLE_NAME = :3 order by ordinal_position;`

    var select_table_names_stmt = snowflake.createStatement(
                {
                sqlText: select_table_names,
                binds: [SRC_DB_PARAM, SRC_SCHEMA_PARAM]
                }
        );

    var table_names = select_table_names_stmt.execute();

    var table_name_array=[];
    while(table_names.next())
    {
        table_name_array.push(table_names.getColumnValue(1));
    }

    for (const table_name of table_name_array) {

        var select_column_names_stmt = snowflake.createStatement(
                {
                sqlText: select_column_names,
                binds: [SRC_DB_PARAM, SRC_SCHEMA_PARAM, table_name]
                }
        );

        var column_names = select_column_names_stmt.execute();
        var colum_name_obj = {};

        while(column_names.next())
        {
            var column_name = column_names.getColumnValue(1);
            var comment = column_names.getColumnValue(2);
            colum_name_obj[column_names.getColumnValue(1)] = comment ? ` comment ''${comment}''`: "";
        }

        var source_tb_columns = Object.keys(colum_name_obj).join('', '');
        var column_name_with_comment = Object.entries(colum_name_obj).map(x => `${x[0]}${x[1]}`).join('', '');


        var view_template = `CREATE VIEW IF NOT EXISTS ` + DST_DB_PARAM + `.` + DST_SCHEMA_PARAM + `.${table_name}_BV COPY GRANTS (${column_name_with_comment})
                            AS SELECT
                               ${source_tb_columns}
                            FROM ` + SRC_DB_PARAM + `.` + SRC_SCHEMA_PARAM + `."${table_name}";`
        var execute_base_view_stmt = snowflake.createStatement(
        {
            sqlText: view_template
        });
        execute_base_view_stmt.execute();
    }
    
    var view_names = table_name_array.map(x => `${x}_BV`).join('', '')
    try {

        return `The following base views are created: ${view_names} in the database: ${DST_DB_PARAM} and schema: ${DST_SCHEMA_PARAM}`;
        }
    catch (err)  {
        throw err;
        }
    ';