create TABLE IF NOT EXISTS DAILY_FLASH_SALES_FACT_ALL (
	STORE_ID VARCHAR(16777216),
	BUSINESS_DT DATE,
	STORE_KEY NUMBER(38,0),
	BUSINESS_DATE_KEY NUMBER(38,0),
	BRAND_ID VARCHAR(16777216),
	TRANSACTION_CNT NUMBER(18,2),
	NET_SALES_AMT NUMBER(38,2),
	LOAD_TYP VARCHAR(16777216),
	SOURCE_SYSTEM_NM VARCHAR(16777216),
	LOAD_ID NUMBER(38,0),
	LOAD_DTTM TIMESTAMP_NTZ(9),
	UPDATE_ID VARCHAR(16777216),
	UPDATE_DTTM TIMESTAMP_NTZ(9)
);
create TABLE IF NOT EXISTS FLYWAY_SCHEMA_HISTORY (
	INSTALLED_RANK NUMBER(38,0) NOT NULL,
	VERSION VARCHAR(50),
	DESCRIPTION VARCHAR(200),
	TYPE VARCHAR(20) NOT NULL,
	SCRIPT VARCHAR(1000) NOT NULL,
	CHECKSUM NUMBER(38,0),
	INSTALLED_BY VARCHAR(100) NOT NULL,
	INSTALLED_ON TIMESTAMP_LTZ(9) NOT NULL DEFAULT CURRENT_TIMESTAMP(),
	EXECUTION_TIME NUMBER(38,0) NOT NULL,
	SUCCESS BOOLEAN NOT NULL,
	primary key (INSTALLED_RANK)
);
create view IF NOT EXISTS VW_COMP_CAL_DATE_3YR(
	DATE_KEY,
	DATE_ID,
	CALENDAR1YRCOMP_DATEID,
	CALENDAR2YRCOMP_DATEID,
	CALENDAR3YRCOMP_DATEID,
	FISCAL1YRCOMP_DATEID,
	FISCAL2YRCOMP_DATEID,
	FISCAL3YRCOMP_DATEID
) as (       SELECT
            Current_Year.DATE_KEY                  AS Date_Key,
            Current_Year.CALENDAR_DT               AS DATE_ID,
            Calendar1yrComp.CALENDAR_DT            AS CALENDAR1YRCOMP_DATEID,
            Calendar2yrComp.CALENDAR_DT            AS CALENDAR2YRCOMP_DATEID,
            Calendar2yrComp.CALENDAR_COMPARABLE_DT AS CALENDAR3YRCOMP_DATEID,
            Fiscal1yrComp.CALENDAR_DT              AS FISCAL1YRCOMP_DATEID,
            Fiscal2yrComp.CALENDAR_DT              AS FISCAL2YRCOMP_DATEID,
            Fiscal2yrComp.FISCAL_COMPARABLE_DT     AS FISCAL3YRCOMP_DATEID
        FROM
            IDS_DEV.DATASTORE.DATE_DIM Current_Year
        LEFT OUTER JOIN
            IDS_DEV.DATASTORE.DATE_DIM Calendar1yrComp
        ON 
            Current_Year.CALENDAR_COMPARABLE_DT = Calendar1yrComp.CALENDAR_DT
        LEFT OUTER JOIN
            IDS_DEV.DATASTORE.DATE_DIM Calendar2yrComp
        ON
            Calendar1yrComp.CALENDAR_COMPARABLE_DT = Calendar2yrComp.CALENDAR_DT
    
        LEFT OUTER JOIN 
            IDS_DEV.DATASTORE.DATE_DIM Fiscal1yrComp
        ON 
            Current_Year.FISCAL_COMPARABLE_DT = Fiscal1yrComp.CALENDAR_DT
        LEFT OUTER JOIN
            IDS_DEV.DATASTORE.DATE_DIM Fiscal2yrComp
        ON
            Fiscal1yrComp.FISCAL_COMPARABLE_DT = Fiscal2yrComp.CALENDAR_DT
    );
CREATE FUNCTION IF NOT EXISTS DAILY_SALES("BUSINESS_DATE" DATE)
RETURNS TABLE ("BRAND_ID" VARCHAR(16777216), "STORE_ID" VARCHAR(16777216), "BUSINESS_DT" DATE, "CY_NET_SALES_DAY" NUMBER(38,0), "CY_NET_TRANS_CNT_DAY" NUMBER(38,0), "CY_CAL_COMP_SALES_DAY" NUMBER(38,0), "CY_CAL_TRANS_CNT_DAY" NUMBER(38,0), "CY_COMP_ELIGIBLE_DAY" VARCHAR(16777216), "DMA_NAME" VARCHAR(16777216), "OWNERSHIP_TYPE" VARCHAR(16777216), "STATE" VARCHAR(16777216), "COUNTRY" VARCHAR(16777216))
LANGUAGE SQL
AS '

SELECT
    CASE    WHEN UPPER(dfsf.BRAND_ID) = ''ARG'' THEN ''Arbys'' 
            WHEN UPPER(dfsf.BRAND_ID) = ''BWW'' THEN ''BWW''
            WHEN UPPER(dfsf.BRAND_ID) = ''SDI'' THEN ''Sonic''
            ELSE ''UNKNOWN''
            END AS BRAND_ID
    , dfsf.STORE_ID
    , dfsf.BUSINESS_DT
    , SUM(dfsf.NET_SALES_AMT) OVER(PARTITION BY dfsf.BRAND_ID, dfsf.STORE_ID, dfsf.BUSINESS_DT) AS CY_Net_Sales_Day
    , SUM(dfsf.TRANSACTION_CNT) OVER(PARTITION BY dfsf.BRAND_ID, dfsf.STORE_ID, dfsf.BUSINESS_DT) AS CY_Net_Trans_Cnt_Day
    , SUM(dfsf.NET_SALES_AMT) OVER(PARTITION BY dfsf.BRAND_ID, dfsf.STORE_ID, dfsf.BUSINESS_DT) AS CY_Cal_Comp_Sales_Day
    , SUM(dfsf.TRANSACTION_CNT) OVER(PARTITION BY dfsf.BRAND_ID, dfsf.STORE_ID, dfsf.BUSINESS_DT) AS CY_Cal_Trans_Cnt_Day  
    , ''Y'' AS CY_Comp_Eligible_Day
    , IFNULL(st.DMA_NAME, ''UNKNOWN'') AS DMA_NAME
    , IFNULL(st.OWNERSHIP_TYPE, ''UNKNOWN'') AS OWNERSHIP_TYPE
    , IFNULL(st.STATE, ''UNKNOWN'') AS STATE
    , IFNULL(st.COUNTRY, ''UNKNOWN'') AS COUNTRY
FROM 
    IDS_DEV.DATASTORE.DAILY_FLASH_SALES_FACT dfsf
LEFT OUTER JOIN
    IDH_DEV.SHARED.STORE_V st
ON  dfsf.STORE_ID = st.STORE_ID
AND dfsf.BRAND_ID = st.BRAND_ID
INNER JOIN
    IDH_DEV.SHARED.DATE_DIM_V d
ON  dfsf.BUSINESS_DT = d.CALENDAR_DT
INNER JOIN
    IDH_DEV.SHARED.DATE_DIM_V d1c
ON  d1c.CALENDAR_DT = d.CALENDAR_COMPARABLE_DT
INNER JOIN
    IDH_DEV.SHARED.DATE_DIM_V d2c
ON  d2c.CALENDAR_DT = d1c.CALENDAR_COMPARABLE_DT
INNER JOIN
    IDH_DEV.SHARED.DATE_DIM_V d3c
ON  d3c.CALENDAR_DT = d2c.CALENDAR_COMPARABLE_DT
WHERE
    dfsf.BRAND_ID = ''ARG''
AND dfsf.SOURCE_SYSTEM_NM = ''RTI''
AND NOT (dfsf.BRAND_ID = ''ARG'' AND dfsf.SOURCE_SYSTEM_NM <> ''RTI'')
AND IFNULL(st.COUNTRY, ''US'') = ''US''
AND IFNULL(st.IS_CURRENT, 1) = 1 /*Replace IFNULL when st will be filled*/

';
CREATE FUNCTION IF NOT EXISTS DAILY_SALES("BUSINESS_DATE" VARCHAR(16777216))
RETURNS TABLE ("BRAND_ID" VARCHAR(16777216), "STORE_ID" VARCHAR(16777216), "BUSINESS_DT" DATE, "CY_NET_SALES_DAY" NUMBER(38,0), "CY_NET_TRANS_CNT_DAY" NUMBER(38,0), "CY_CAL_COMP_SALES_DAY" NUMBER(38,0), "CY_CAL_TRANS_CNT_DAY" NUMBER(38,0), "CY_COMP_ELIGIBLE_DAY" VARCHAR(16777216), "DMA_NAME" VARCHAR(16777216), "OWNERSHIP_TYPE" VARCHAR(16777216), "STATE" VARCHAR(16777216), "COUNTRY" VARCHAR(16777216))
LANGUAGE SQL
AS '

SELECT
    CASE    WHEN UPPER(dfsf.BRAND_ID) = ''ARG'' THEN ''Arbys'' 
            WHEN UPPER(dfsf.BRAND_ID) = ''BWW'' THEN ''BWW''
            WHEN UPPER(dfsf.BRAND_ID) = ''SDI'' THEN ''Sonic''
            ELSE ''UNKNOWN''
            END AS BRAND_ID
    , dfsf.STORE_ID
    , dfsf.BUSINESS_DT
    , SUM(dfsf.NET_SALES_AMT) OVER(PARTITION BY dfsf.BRAND_ID, dfsf.STORE_ID, dfsf.BUSINESS_DT) AS CY_Net_Sales_Day
    , SUM(dfsf.TRANSACTION_CNT) OVER(PARTITION BY dfsf.BRAND_ID, dfsf.STORE_ID, dfsf.BUSINESS_DT) AS CY_Net_Trans_Cnt_Day
    , SUM(dfsf.NET_SALES_AMT) OVER(PARTITION BY dfsf.BRAND_ID, dfsf.STORE_ID, dfsf.BUSINESS_DT) AS CY_Cal_Comp_Sales_Day
    , SUM(dfsf.TRANSACTION_CNT) OVER(PARTITION BY dfsf.BRAND_ID, dfsf.STORE_ID, dfsf.BUSINESS_DT) AS CY_Cal_Trans_Cnt_Day  
    , ''Y'' AS CY_Comp_Eligible_Day
    , IFNULL(st.DMA_NAME, ''UNKNOWN'') AS DMA_NAME
    , IFNULL(st.OWNERSHIP_TYPE, ''UNKNOWN'') AS OWNERSHIP_TYPE
    , IFNULL(st.STATE, ''UNKNOWN'') AS STATE
    , IFNULL(st.COUNTRY, ''UNKNOWN'') AS COUNTRY
FROM 
    IDS_DEV.DATASTORE.DAILY_FLASH_SALES_FACT dfsf
LEFT OUTER JOIN
    IDH_DEV.SHARED.STORE_V st
ON  dfsf.STORE_ID = st.STORE_ID
AND dfsf.BRAND_ID = st.BRAND_ID
INNER JOIN
    IDH_DEV.SHARED.DATE_DIM_V d
ON  dfsf.BUSINESS_DT = d.CALENDAR_DT
INNER JOIN
    IDH_DEV.SHARED.DATE_DIM_V d1c
ON  d1c.CALENDAR_DT = d.CALENDAR_COMPARABLE_DT
INNER JOIN
    IDH_DEV.SHARED.DATE_DIM_V d2c
ON  d2c.CALENDAR_DT = d1c.CALENDAR_COMPARABLE_DT
INNER JOIN
    IDH_DEV.SHARED.DATE_DIM_V d3c
ON  d3c.CALENDAR_DT = d2c.CALENDAR_COMPARABLE_DT
WHERE
    dfsf.BRAND_ID = ''ARG''
AND dfsf.SOURCE_SYSTEM_NM = ''RTI''
AND NOT (dfsf.BRAND_ID = ''ARG'' AND dfsf.SOURCE_SYSTEM_NM <> ''RTI'')
AND IFNULL(st.COUNTRY, ''US'') = ''US''
AND IFNULL(st.IS_CURRENT, 1) = 1 /*Replace IFNULL when st will be filled*/

';
CREATE FUNCTION IF NOT EXISTS FLASH_SUMMARY_NO_COMP("BUSINESS_DATE" DATE)
RETURNS TABLE ("AGG_LEVEL" VARCHAR(16777216), "BUSINESS_DT" DATE, "BRAND_ID" VARCHAR(16777216), "STORE_ID" VARCHAR(16777216), "DMA_NAME" VARCHAR(16777216), "L1NAME" VARCHAR(16777216), "L2NAME" VARCHAR(16777216), "L3NAME" VARCHAR(16777216), "L4NAME" VARCHAR(16777216), "L5NAME" VARCHAR(16777216), "OWNERSHIP_TYPE" VARCHAR(16777216), "STATE" VARCHAR(16777216), "COUNTRY" VARCHAR(16777216), "NET_SALES_CY" NUMBER(38,0), "TRANS_CY" NUMBER(38,0), "COMP_SALES_CY" NUMBER(38,0), "COMP_TRANS_CY" NUMBER(38,0), "FC_DT_LY" DATE, "FC_NET_SALES_LY" NUMBER(38,0), "FC_TRANS_LY" NUMBER(38,0), "FC_COMP_SALES_LY" NUMBER(38,0), "FC_COMP_TRANS_LY" NUMBER(38,0), "CALCOMP_DT_LY" DATE, "CAL_NET_SALES_LY" NUMBER(38,0), "CAL_TRANS_LY" NUMBER(38,0), "CAL_COMP_SALES_LY" NUMBER(38,0), "CAL_COMP_TRANS_LY" NUMBER(38,0), "CALCOMP_DT_2Y" DATE, "CAL_NET_SALES_2Y" NUMBER(38,0), "CAL_TRANS_2Y" NUMBER(38,0), "CAL_COMP_SALES_2Y" NUMBER(38,0), "CAL_COMP_TRANS_2Y" NUMBER(38,0), "CALCOMP_DT_3Y" DATE, "CAL_NET_SALES_3Y" NUMBER(38,0), "CAL_TRANS_3Y" NUMBER(38,0), "CAL_COMP_SALES_3Y" NUMBER(38,0), "CAL_COMP_TRANS_3Y" NUMBER(38,0))
LANGUAGE SQL
AS '

  select 
  fiscal_curr_year.AGG_LEVEL, 
  fiscal_curr_year.BUSINESS_DT,
  fiscal_curr_year.BRAND_ID,
  fiscal_curr_year.STORE_ID,
  fiscal_curr_year.DMA_NAME,
  fiscal_curr_year.L1Name,
  fiscal_curr_year.L2Name,
  fiscal_curr_year.L3Name,
  fiscal_curr_year.L4Name,
  fiscal_curr_year.L5Name,
  fiscal_curr_year.OWNERSHIP_TYPE,
  fiscal_curr_year.STATE,
  fiscal_curr_year.COUNTRY,
  fiscal_curr_year.FY_Net_Sales_Day as Net_Sales_CY,
  fiscal_curr_year.FY_Net_Trans_Cnt_Day as Trans_CY,
  fiscal_curr_year.FY_Comp_Sales_Day as Comp_Sales_CY,
  fiscal_curr_year.FY_Comp_Trans_Cnt_Day as Comp_Trans_CY,
  fiscal_last_year.AGG_START_DT,
  fiscal_last_year.FY_Net_Sales_Day as Fc_Net_Sales_LY,
  fiscal_last_year.FY_Net_Trans_Cnt_Day as Fc_Trans_LY,
  fiscal_last_year.FY_Comp_Sales_Day as Fc_Comp_Sales_LY,
  fiscal_last_year.FY_Comp_Trans_Cnt_Day as Fc_Comp_Trans_LY,
  calendar_last_year.AGG_START_DT,
  calendar_last_year.FY_Net_Sales_Day as Cal_Net_Sales_LY,
  calendar_last_year.FY_Net_Trans_Cnt_Day as Cal_Trans_LY,
  calendar_last_year.FY_Comp_Sales_Day as Cal_Comp_Sales_LY,
  calendar_last_year.FY_Comp_Trans_Cnt_Day as Cal_Comp_Trans_LY,
  calendar_two_years.AGG_START_DT,
  calendar_two_years.FY_Net_Sales_Day as Cal_Net_Sales_2Y,
  calendar_two_years.FY_Net_Trans_Cnt_Day as Cal_Trans_2Y,
  calendar_two_years.FY_Comp_Sales_Day as Cal_Comp_Sales_2Y,
  calendar_two_years.FY_Comp_Trans_Cnt_Day as Cal_Comp_Trans_2Y,
  calendar_three_years.AGG_START_DT,
  calendar_three_years.FY_Net_Sales_Day as Cal_Net_Sales_3Y,
  calendar_three_years.FY_Net_Trans_Cnt_Day as Cal_Trans_3Y,
  calendar_three_years.FY_Comp_Sales_Day as Cal_Comp_Sales_3Y,
  calendar_three_years.FY_Comp_Trans_Cnt_Day as Cal_Comp_Trans_3Y
  FROM 
  table(FLASH_SUMMARY_NO_COMP_FISCAL(BUSINESS_DATE)) as fiscal_curr_year
  inner join VW_COMP_CAL_DATE_3YR dt
  on dt.date_id = fiscal_curr_year.business_dt
  left outer join 
  table(FLASH_SUMMARY_NO_COMP_FISCAL(select FISCAL1YRCOMP_DATEID from VW_COMP_CAL_DATE_3YR where date_id = BUSINESS_DATE)) as fiscal_last_year
  on dt.FISCAL1YRCOMP_DATEID = fiscal_last_year.business_dt
  and fiscal_curr_year.store_id = fiscal_last_year.store_id
  and fiscal_curr_year.brand_id = fiscal_last_year.brand_id
  and fiscal_curr_year.AGG_LEVEL = fiscal_last_year.AGG_LEVEL
  left outer join 
  table(FLASH_SUMMARY_NO_COMP_FISCAL(select CALENDAR1YRCOMP_DATEID from VW_COMP_CAL_DATE_3YR where date_id = BUSINESS_DATE)) as calendar_last_year
  on dt.CALENDAR1YRCOMP_DATEID = calendar_last_year.business_dt
  and fiscal_curr_year.store_id = calendar_last_year.store_id
  and fiscal_curr_year.brand_id = calendar_last_year.brand_id
  and fiscal_curr_year.AGG_LEVEL = calendar_last_year.AGG_LEVEL
  left outer join 
  table(FLASH_SUMMARY_NO_COMP_FISCAL(select CALENDAR2YRCOMP_DATEID from VW_COMP_CAL_DATE_3YR where date_id = BUSINESS_DATE)) as calendar_two_years
  on dt.CALENDAR2YRCOMP_DATEID = calendar_two_years.business_dt
  and fiscal_curr_year.store_id = calendar_two_years.store_id
  and fiscal_curr_year.brand_id = calendar_two_years.brand_id
  and fiscal_curr_year.AGG_LEVEL = calendar_two_years.AGG_LEVEL
  left outer join 
  table(FLASH_SUMMARY_NO_COMP_FISCAL(select CALENDAR3YRCOMP_DATEID from VW_COMP_CAL_DATE_3YR where date_id = BUSINESS_DATE)) as calendar_three_years
  on dt.CALENDAR3YRCOMP_DATEID = calendar_three_years.business_dt
  and fiscal_curr_year.store_id = calendar_three_years.store_id
  and fiscal_curr_year.brand_id = calendar_three_years.brand_id
  and fiscal_curr_year.AGG_LEVEL = calendar_three_years.AGG_LEVEL
  order by 
  fiscal_curr_year.brand_id ASC, 
  fiscal_curr_year.store_id ASC,
  (case when fiscal_curr_year.AGG_LEVEL = ''DY'' then 1
    when fiscal_curr_year.AGG_LEVEL = ''WTD'' then 2
    when fiscal_curr_year.AGG_LEVEL = ''PTD'' then 3
    when fiscal_curr_year.AGG_LEVEL = ''QTD'' then 4
    when fiscal_curr_year.AGG_LEVEL = ''YTD'' then 5 END) ASC,
  fiscal_last_year.business_dt DESC
  ';
CREATE FUNCTION IF NOT EXISTS FLASH_SUMMARY_NO_COMP_CALENDAR("BUSINESS_DATE" DATE)
RETURNS TABLE ("BRAND_ID" VARCHAR(16777216), "STORE_ID" VARCHAR(16777216), "BUSINESS_DT" DATE, "CY_NET_TRANS_CNT_DAY" NUMBER(38,0), "CY_NET_SALES_DAY" NUMBER(38,0), "CY_COMP_TRANS_CNT_DAY" NUMBER(38,0), "CY_CAL_COMP_SALES_DAY" NUMBER(38,0), "AGG_START_DT" DATE, "AGG_LEVEL" VARCHAR(16777216), "CY_COMP_ELIGIBLE_DAY" VARCHAR(16777216), "DMA_NAME" VARCHAR(16777216), "OWNERSHIP_TYPE" VARCHAR(16777216), "STATE" VARCHAR(16777216), "COUNTRY" VARCHAR(16777216), "L1NAME" VARCHAR(16777216), "L2NAME" VARCHAR(16777216), "L3NAME" VARCHAR(16777216), "L4NAME" VARCHAR(16777216), "L5NAME" VARCHAR(16777216), "OPEN_15P_FLAG" BOOLEAN, "CLOSED_BEFORE_PERIOD_END_FLAG" BOOLEAN, "OPEN_AFTER_HONEYMOON_FLAG" BOOLEAN)
LANGUAGE SQL
AS '

WITH COMP_DATE AS 
(
SELECT  
    BUSINESS_DATE AS calendar_dt -- comparison date
    , opendt.calendar_dt as MAX_OPEN_DT -- ODI-53 maximum open date for which the store will be comp when reporting at BUSINESS_DATE
    , opendthoney.calendar_dt as MAX_HONEY_DT -- ODI-199 maximum open date for which the store will be out of honeymoon period (3 full fiscal periods) at BUSINESS_DATE
FROM "IDS_DEV"."DATASTORE"."DATE_DIM" as opendt
INNER JOIN "IDS_DEV"."DATASTORE"."DATE_DIM" as busdt
on
    iff (opendt.FISCAL_PERIOD_START_DT = opendt.CALENDAR_DT
        , (opendt.FISCAL_PERIOD_NBR+15)%12
        , (opendt.FISCAL_PERIOD_NBR+16)%12
    ) = busdt.FISCAL_PERIOD_NBR
and iff (opendt.FISCAL_PERIOD_START_DT = opendt.CALENDAR_DT
        , opendt.FISCAL_YEAR_NBR + trunc((opendt.FISCAL_PERIOD_NBR+15)/12)
        , opendt.FISCAL_YEAR_NBR + trunc((opendt.FISCAL_PERIOD_NBR+16)/12)
    ) = busdt.FISCAL_YEAR_NBR
INNER JOIN "IDS_DEV"."DATASTORE"."DATE_DIM" as opendthoney --ODI-199
on
    (opendthoney.FISCAL_PERIOD_NBR +
            iff(opendthoney.FISCAL_PERIOD_START_DT = opendthoney.CALENDAR_DT, 3, 4)
    ) % 12 = busdt.FISCAL_PERIOD_NBR
and 
    opendthoney.FISCAL_YEAR_NBR + trunc(
        (opendthoney.FISCAL_PERIOD_NBR +
                iff(opendthoney.FISCAL_PERIOD_START_DT = opendthoney.CALENDAR_DT, 3, 4)
        ) / 12
    ) = busdt.FISCAL_YEAR_NBR
where opendt.calendar_dt = opendt.FISCAL_PERIOD_START_DT
and opendthoney.calendar_dt = opendthoney.FISCAL_PERIOD_START_DT
and busdt.calendar_dt = BUSINESS_DATE
)
--CDTD AS   --ODI-2289 + ODI-906
 
SELECT 
    BRAND_ID
    , STORE_ID
    , BUSINESS_DT
    , SUM(CY_Net_Trans_Cnt_Day)
    , SUM(CY_Net_Sales_Day)
    , SUM(CY_Net_Trans_Cnt_Day) as CY_Comp_Trans_Cnt_Day
    , SUM(CY_Net_Sales_Day) as CY_Cal_Comp_Sales_Day
    , BUSINESS_DT as AGG_START_DT
    , ''DY'' AS AGG_LEVEL
    , CY_Comp_Eligible_Day
    , DMA_NAME 
    , OWNERSHIP_TYPE
    , STATE
    , COUNTRY
    , L1Name
    , L2Name
    , L3Name
    , L4Name
    , L5Name
    , MAX(nvl(OPEN_DATE, MAX_OPEN_DT)) <= MAX(MAX_OPEN_DT) as OPEN_15P_FLAG -- ODI-53
    , NULL as CLOSED_BEFORE_PERIOD_END_FLAG --ODI-55
    , MAX(nvl(SLS.OPEN_DATE, COMP_DATE.MAX_HONEY_DT)) <= MAX(COMP_DATE.MAX_HONEY_DT) as OPEN_AFTER_HONEYMOON_FLAG -- ODI-199
FROM 
    IDH_DEV.SALES.DAILY_FLASH_SALES_V SLS
INNER JOIN 
    COMP_DATE 
ON  SLS.BUSINESS_DT BETWEEN COMP_DATE.CALENDAR_DT -9 AND COMP_DATE.CALENDAR_DT
GROUP BY    
      BRAND_ID
    , STORE_ID
    , BUSINESS_DT
    , ''DY'' 
    , CY_Comp_Eligible_Day
    , DMA_NAME 
    , OWNERSHIP_TYPE
    , STATE
    , COUNTRY
    , COMP_DATE.CALENDAR_DT
    , L1Name
    , L2Name
    , L3Name
    , L4Name
    , L5Name

UNION 

--ODI-2233

SELECT 
      SLS.BRAND_ID
    , STORE_ID
    , COMP_DATE.CALENDAR_DT 
    , SUM(CY_Net_Trans_Cnt_Day)
    , SUM(CY_Net_Sales_Day)
    , SUM(CY_Net_Trans_Cnt_Day) as CY_Comp_Trans_Cnt_Day
    , SUM(CY_Net_Sales_Day) as CY_Cal_Comp_Sales_Day
    , CALENDAR_YEAR_START_DT AGG_START_DT
    , ''YTD'' AS Agg_Level
    , CY_Comp_Eligible_Day
    , DMA_NAME 
    , OWNERSHIP_TYPE
    , STATE
    , COUNTRY
    , L1Name
    , L2Name
    , L3Name
    , L4Name
    , L5Name
    , MAX(nvl(OPEN_DATE, MAX_OPEN_DT)) <= MAX(MAX_OPEN_DT) as OPEN_15P_FLAG -- ODI-53
    , NULL as CLOSED_BEFORE_PERIOD_END_FLAG --ODI-55
    , MAX(nvl(SLS.OPEN_DATE, COMP_DATE.MAX_HONEY_DT)) <= MAX(COMP_DATE.MAX_HONEY_DT) as OPEN_AFTER_HONEYMOON_FLAG -- ODI-199
FROM 
    IDH_DEV.SALES.DAILY_FLASH_SALES_V SLS
INNER JOIN 
    COMP_DATE
ON  SLS.BUSINESS_DT <= COMP_DATE.CALENDAR_DT
INNER JOIN 
    IDS_DEV.DATASTORE.DATE_DIM DT
ON  COMP_DATE.CALENDAR_DT = DT.CALENDAR_DT
WHERE 
    SLS.BUSINESS_DT >= DT.CALENDAR_YEAR_START_DT
GROUP BY    
      SLS.BRAND_ID
    , STORE_ID
    , COMP_DATE.CALENDAR_DT
    , ''YTD'' 
    , CY_Comp_Eligible_Day
    , DMA_NAME 
    , OWNERSHIP_TYPE
    , STATE
    , COUNTRY
    , CALENDAR_YEAR_START_DT
    , L1Name
    , L2Name
    , L3Name
    , L4Name
    , L5Name

UNION 

--ODI-2178

SELECT    
    SLS.BRAND_ID
    , STORE_ID
    , COMP_DATE.CALENDAR_DT 
    , SUM(CY_Net_Trans_Cnt_Day)
    , SUM(CY_Net_Sales_Day)
    , SUM(CY_Net_Trans_Cnt_Day) as CY_Comp_Trans_Cnt_Day
    , SUM(CY_Net_Sales_Day) as CY_Cal_Comp_Sales_Day
    , CALENDAR_QUARTER_START_DT AGG_START_DT
    , ''QTD'' AS Agg_Level
    , CY_Comp_Eligible_Day
    , DMA_NAME 
    , OWNERSHIP_TYPE
    , STATE
    , COUNTRY
    , L1Name
    , L2Name
    , L3Name
    , L4Name
    , L5Name
    , MAX(nvl(OPEN_DATE, MAX_OPEN_DT)) <= MAX(MAX_OPEN_DT) as OPEN_15P_FLAG -- ODI-53
    , NULL as CLOSED_BEFORE_PERIOD_END_FLAG --ODI-55
    , MAX(nvl(SLS.OPEN_DATE, COMP_DATE.MAX_HONEY_DT)) <= MAX(COMP_DATE.MAX_HONEY_DT) as OPEN_AFTER_HONEYMOON_FLAG -- ODI-199
FROM 
    IDH_DEV.SALES.DAILY_FLASH_SALES_V SLS
INNER JOIN 
    COMP_DATE
ON  SLS.BUSINESS_DT <= COMP_DATE.CALENDAR_DT
INNER JOIN 
    IDS_DEV.DATASTORE.DATE_DIM DT
ON  COMP_DATE.CALENDAR_DT = DT.CALENDAR_DT
WHERE 
    SLS.BUSINESS_DT >= DT.CALENDAR_QUARTER_START_DT
GROUP BY    
      SLS.BRAND_ID
    , STORE_ID
    , COMP_DATE.CALENDAR_DT
    , ''QTD'' 
    , CY_Comp_Eligible_Day
    , DMA_NAME 
    , OWNERSHIP_TYPE
    , STATE
    , COUNTRY
    , CALENDAR_QUARTER_START_DT
    , L1Name
    , L2Name
    , L3Name
    , L4Name
    , L5Name


UNION

SELECT  --ODI-2675 
    SLS.BRAND_ID
    , STORE_ID
    , COMP_DATE.CALENDAR_DT 
    , SUM(CY_Net_Trans_Cnt_Day)
    , SUM(CY_Net_Sales_Day)
    , SUM(CY_Net_Trans_Cnt_Day) as CY_Comp_Trans_Cnt_Day
    , SUM(CY_Net_Sales_Day) as CY_Cal_Comp_Sales_Day
    , CALENDAR_MONTH_START_DT AGG_START_DT
    , ''PTD'' AS Agg_Level
    , CY_Comp_Eligible_Day
    , DMA_NAME 
    , OWNERSHIP_TYPE
    , STATE
    , COUNTRY
    , L1Name
    , L2Name
    , L3Name
    , L4Name
    , L5Name
    , MAX(nvl(OPEN_DATE, MAX_OPEN_DT)) <= MAX(MAX_OPEN_DT) as OPEN_15P_FLAG -- ODI-53
    , MAX(NVL(SLS.CLOSURE_DATE, DT.FISCAL_PERIOD_END_DT)) < MAX(DT.FISCAL_PERIOD_END_DT) as CLOSED_BEFORE_PERIOD_END_FLAG --ODI-55
    , MAX(nvl(SLS.OPEN_DATE, COMP_DATE.MAX_HONEY_DT)) <= MAX(COMP_DATE.MAX_HONEY_DT) as OPEN_AFTER_HONEYMOON_FLAG -- ODI-199
FROM 
    IDH_DEV.SALES.DAILY_FLASH_SALES_V SLS
INNER JOIN 
    COMP_DATE
ON SLS.BUSINESS_DT <= COMP_DATE.CALENDAR_DT
INNER JOIN 
    IDS_DEV.DATASTORE.DATE_DIM DT
ON COMP_DATE.CALENDAR_DT = DT.CALENDAR_DT
WHERE SLS.BUSINESS_DT >= DT.CALENDAR_MONTH_START_DT
GROUP BY    
      SLS.BRAND_ID
    , STORE_ID
    , COMP_DATE.CALENDAR_DT
    , ''PTD'' 
    , CY_Comp_Eligible_Day
    , DMA_NAME 
    , OWNERSHIP_TYPE
    , STATE
    , COUNTRY
    , CALENDAR_MONTH_START_DT
    , L1Name
    , L2Name
    , L3Name
    , L4Name
    , L5Name


UNION
   
SELECT   --ODI-2078 
   SLS.BRAND_ID
    , STORE_ID
    , COMP_DATE.CALENDAR_DT 
    , SUM(CY_Net_Trans_Cnt_Day)
    , SUM(CY_Net_Sales_Day)
    , SUM(CY_Net_Trans_Cnt_Day) as CY_Comp_Trans_Cnt_Day
    , SUM(CY_Net_Sales_Day) as CY_Cal_Comp_Sales_Day
    , CALENDAR_WEEK_START_DT AGG_START_DT
    , ''WTD'' AS Agg_Level
    , CY_Comp_Eligible_Day
    , DMA_NAME 
    , OWNERSHIP_TYPE
    , STATE
    , COUNTRY
    , L1Name
    , L2Name
    , L3Name
    , L4Name
    , L5Name
    , MAX(nvl(OPEN_DATE, MAX_OPEN_DT)) <= MAX(MAX_OPEN_DT) as OPEN_15P_FLAG -- ODI-53
    , NULL as CLOSED_BEFORE_PERIOD_END_FLAG --ODI-55
    , MAX(nvl(SLS.OPEN_DATE, COMP_DATE.MAX_HONEY_DT)) <= MAX(COMP_DATE.MAX_HONEY_DT) as OPEN_AFTER_HONEYMOON_FLAG -- ODI-199
FROM 
    IDH_DEV.SALES.DAILY_FLASH_SALES_V SLS
INNER JOIN 
    COMP_DATE
ON SLS.BUSINESS_DT <= COMP_DATE.CALENDAR_DT
INNER JOIN 
    IDS_DEV.DATASTORE.DATE_DIM DT
ON  COMP_DATE.CALENDAR_DT = DT.CALENDAR_DT
WHERE 
    SLS.BUSINESS_DT >= DT.CALENDAR_WEEK_START_DT
GROUP BY    
      SLS.BRAND_ID
    , STORE_ID
    , COMP_DATE.CALENDAR_DT
    , ''WTD'' 
    , CY_Comp_Eligible_Day
    , DMA_NAME 
    , OWNERSHIP_TYPE
    , STATE
    , COUNTRY
    , CALENDAR_WEEK_START_DT
    , L1Name
    , L2Name
    , L3Name
    , L4Name
    , L5Name

';
CREATE FUNCTION IF NOT EXISTS FLASH_SUMMARY_NO_COMP_FISCAL("BUSINESS_DATE" DATE)
RETURNS TABLE ("BRAND_ID" VARCHAR(16777216), "STORE_ID" VARCHAR(16777216), "BUSINESS_DT" DATE, "FY_NET_TRANS_CNT_DAY" NUMBER(38,0), "FY_NET_SALES_DAY" NUMBER(38,0), "FY_COMP_TRANS_CNT_DAY" NUMBER(38,0), "FY_COMP_SALES_DAY" NUMBER(38,0), "AGG_START_DT" DATE, "AGG_LEVEL" VARCHAR(16777216), "CY_FISCAL_COMP_ELIGIBLE_DAY" VARCHAR(16777216), "DMA_NAME" VARCHAR(16777216), "OWNERSHIP_TYPE" VARCHAR(16777216), "STATE" VARCHAR(16777216), "COUNTRY" VARCHAR(16777216), "L1NAME" VARCHAR(16777216), "L2NAME" VARCHAR(16777216), "L3NAME" VARCHAR(16777216), "L4NAME" VARCHAR(16777216), "L5NAME" VARCHAR(16777216))
LANGUAGE SQL
AS '

WITH COMP_DATE AS 
(
SELECT  
    BUSINESS_DATE AS calendar_dt  -- comparison date
FROM 
    dual
)
--CDTD AS   --ODI-2289 + ODI-906
 
SELECT 
    BRAND_ID
    , STORE_ID
    , BUSINESS_DT
    , SUM(CY_Net_Trans_Cnt_Day)
    , SUM(CY_Net_Sales_Day)
    , SUM(CY_Net_Trans_Cnt_Day) as CY_Comp_Trans_Cnt_Day
    , SUM(CY_Net_Sales_Day) as CY_Cal_Comp_Sales_Day
    , BUSINESS_DT as AGG_START_DT
    , ''DY'' AS AGG_LEVEL
    , CY_Comp_Eligible_Day
    , DMA_NAME 
    , OWNERSHIP_TYPE
    , STATE
    , COUNTRY
    , L1Name
    , L2Name
    , L3Name
    , L4Name
    , L5Name
FROM 
    IDH_DEV.SALES.DAILY_FLASH_SALES_V
INNER JOIN 
    COMP_DATE 
ON  IDH_DEV.SALES.DAILY_FLASH_SALES_V.BUSINESS_DT BETWEEN COMP_DATE.CALENDAR_DT -9 AND COMP_DATE.CALENDAR_DT
GROUP BY    
      BRAND_ID
    , STORE_ID
    , BUSINESS_DT
    , ''DY'' 
    , CY_Comp_Eligible_Day
    , DMA_NAME 
    , OWNERSHIP_TYPE
    , STATE
    , COUNTRY
    , COMP_DATE.CALENDAR_DT
    , L1Name
    , L2Name
    , L3Name
    , L4Name
    , L5Name

UNION 



SELECT --ODI-2480
      SLS.BRAND_ID
    , STORE_ID
    , COMP_DATE.CALENDAR_DT 
    , SUM(CY_Net_Trans_Cnt_Day)
    , SUM(CY_Net_Sales_Day)
    , SUM(CY_Net_Trans_Cnt_Day) as FY_Comp_Trans_Cnt_Day
    , SUM(CY_Net_Sales_Day) as FY_Comp_Sales_Day
    , FISCAL_YEAR_START_DT AGG_START_DT
    , ''YTD'' AS Agg_Level
    , CY_Comp_Eligible_Day
    , DMA_NAME 
    , OWNERSHIP_TYPE
    , STATE
    , COUNTRY
    , L1Name
    , L2Name
    , L3Name
    , L4Name
    , L5Name
FROM 
    IDH_DEV.SALES.DAILY_FLASH_SALES_V SLS
INNER JOIN 
    COMP_DATE
ON  SLS.BUSINESS_DT <= COMP_DATE.CALENDAR_DT
INNER JOIN 
    IDS_DEV.DATASTORE.DATE_DIM DT
ON  COMP_DATE.CALENDAR_DT = DT.CALENDAR_DT
WHERE 
    SLS.BUSINESS_DT >= DT.FISCAL_YEAR_START_DT
GROUP BY    
      SLS.BRAND_ID
    , STORE_ID
    , COMP_DATE.CALENDAR_DT
    , ''YTD'' 
    , CY_Comp_Eligible_Day
    , DMA_NAME 
    , OWNERSHIP_TYPE
    , STATE
    , COUNTRY
    , FISCAL_YEAR_START_DT
    , L1Name
    , L2Name
    , L3Name
    , L4Name
    , L5Name

UNION 


SELECT   --ODI-2392 
    SLS.BRAND_ID
    , STORE_ID
    , COMP_DATE.CALENDAR_DT 
    , SUM(CY_Net_Trans_Cnt_Day)
    , SUM(CY_Net_Sales_Day)
    , SUM(CY_Net_Trans_Cnt_Day) as FY_Comp_Trans_Cnt_Day
    , SUM(CY_Net_Sales_Day) as FY_Comp_Sales_Day
    , FISCAL_QUARTER_START_DT AGG_START_DT
    , ''QTD'' AS Agg_Level
    , CY_Comp_Eligible_Day
    , DMA_NAME 
    , OWNERSHIP_TYPE
    , STATE
    , COUNTRY
    , L1Name
    , L2Name
    , L3Name
    , L4Name
    , L5Name
FROM 
    IDH_DEV.SALES.DAILY_FLASH_SALES_V SLS
INNER JOIN 
    COMP_DATE
ON  SLS.BUSINESS_DT <= COMP_DATE.CALENDAR_DT
INNER JOIN 
    IDS_DEV.DATASTORE.DATE_DIM DT
ON  COMP_DATE.CALENDAR_DT = DT.CALENDAR_DT
WHERE 
    SLS.BUSINESS_DT >= DT.FISCAL_QUARTER_START_DT
GROUP BY    
      SLS.BRAND_ID
    , STORE_ID
    , COMP_DATE.CALENDAR_DT
    , ''QTD'' 
    , CY_Comp_Eligible_Day
    , DMA_NAME 
    , OWNERSHIP_TYPE
    , STATE
    , COUNTRY
    , FISCAL_QUARTER_START_DT
    , L1Name
    , L2Name
    , L3Name
    , L4Name
    , L5Name


UNION

SELECT  --ODI-2123
    SLS.BRAND_ID
    , STORE_ID
    , COMP_DATE.CALENDAR_DT 
    , SUM(CY_Net_Trans_Cnt_Day)
    , SUM(CY_Net_Sales_Day)
    , SUM(CY_Net_Trans_Cnt_Day) as FY_Comp_Trans_Cnt_Day
    , SUM(CY_Net_Sales_Day) as FY_Comp_Sales_Day
    , FISCAL_PERIOD_START_DT AGG_START_DT
    , ''PTD'' AS Agg_Level
    , CY_Comp_Eligible_Day
    , DMA_NAME 
    , OWNERSHIP_TYPE
    , STATE
    , COUNTRY
    , L1Name
    , L2Name
    , L3Name
    , L4Name
    , L5Name
FROM 
    IDH_DEV.SALES.DAILY_FLASH_SALES_V SLS
INNER JOIN 
    COMP_DATE
ON SLS.BUSINESS_DT <= COMP_DATE.CALENDAR_DT
INNER JOIN 
    IDS_DEV.DATASTORE.DATE_DIM DT
ON COMP_DATE.CALENDAR_DT = DT.CALENDAR_DT
WHERE SLS.BUSINESS_DT >= DT.FISCAL_PERIOD_START_DT
GROUP BY    
      SLS.BRAND_ID
    , STORE_ID
    , COMP_DATE.CALENDAR_DT
    , ''PTD'' 
    , CY_Comp_Eligible_Day
    , DMA_NAME 
    , OWNERSHIP_TYPE
    , STATE
    , COUNTRY
    , FISCAL_PERIOD_START_DT
    , L1Name
    , L2Name
    , L3Name
    , L4Name
    , L5Name


UNION
   
SELECT   --ODI-2403 
   SLS.BRAND_ID
    , STORE_ID
    , COMP_DATE.CALENDAR_DT 
    , SUM(CY_Net_Trans_Cnt_Day)
    , SUM(CY_Net_Sales_Day)
    , SUM(CY_Net_Trans_Cnt_Day) as FY_Comp_Trans_Cnt_Day
    , SUM(CY_Net_Sales_Day) as FY_Comp_Sales_Day
    , FISCAL_WEEK_START_DT AGG_START_DT
    , ''WTD'' AS Agg_Level
    , CY_Comp_Eligible_Day
    , DMA_NAME 
    , OWNERSHIP_TYPE
    , STATE
    , COUNTRY
    , L1Name
    , L2Name
    , L3Name
    , L4Name
    , L5Name
FROM 
    IDH_DEV.SALES.DAILY_FLASH_SALES_V SLS
INNER JOIN 
    COMP_DATE
ON SLS.BUSINESS_DT <= COMP_DATE.CALENDAR_DT
INNER JOIN 
    IDS_DEV.DATASTORE.DATE_DIM DT
ON  COMP_DATE.CALENDAR_DT = DT.CALENDAR_DT
WHERE 
    SLS.BUSINESS_DT >= DT.FISCAL_WEEK_START_DT
GROUP BY    
      SLS.BRAND_ID
    , STORE_ID
    , COMP_DATE.CALENDAR_DT
    , ''WTD'' 
    , CY_Comp_Eligible_Day
    , DMA_NAME 
    , OWNERSHIP_TYPE
    , STATE
    , COUNTRY
    , FISCAL_WEEK_START_DT
    , L1Name
    , L2Name
    , L3Name
    , L4Name
    , L5Name

';
CREATE FUNCTION IF NOT EXISTS SUMMARY_SALES("BUSINESS_DATE" VARCHAR(16777216))
RETURNS TABLE ("STORE_ID" VARCHAR(16777216), "NET_SALES_AMT" NUMBER(12,2), "TRANSACTION_CNT" NUMBER(38,0), "CALCULATIONTYPE" VARCHAR(16777216))
LANGUAGE SQL
AS '

SELECT
    dfsf.STORE_ID
    , SUM(dfsf.NET_SALES_AMT) AS NET_SALES_AMT
    , SUM(dfsf.TRANSACTION_CNT) AS TRANSACTION_CNT
    , ''WTD'' AS CalculationType
FROM
    IDS_DEV.DATASTORE.DAILY_FLASH_SALES_FACT dfsf
INNER JOIN
    IDH_DEV.SHARED.DATE_DIM_V d
ON  dfsf.BUSINESS_DT = d.CALENDAR_DT
WHERE
    dfsf.BRAND_ID = ''ARG''
AND dfsf.SOURCE_SYSTEM_NM = ''RTI''
AND NOT (dfsf.BRAND_ID = ''ARG'' AND dfsf.SOURCE_SYSTEM_NM <> ''RTI'')
AND BUSINESS_DATE BETWEEN d.CALENDAR_WEEK_START_DT AND d.CALENDAR_DT
GROUP BY
    dfsf.STORE_ID

';
CREATE FUNCTION IF NOT EXISTS SUMMARY_SALES_2YR("BUSINESS_DATE" DATE)
RETURNS TABLE ("STORE_ID" VARCHAR(16777216), "NET_SALES_AMT" NUMBER(12,2), "TRANSACTION_CNT" NUMBER(38,0), "BUSINESS_DATE" DATE, "CALCULATIONTYPE" VARCHAR(16777216))
LANGUAGE SQL
AS '

SELECT
    dfsf.STORE_ID
    , SUM(dfsf.NET_SALES_AMT) AS NET_SALES_AMT
    , SUM(dfsf.TRANSACTION_CNT) AS TRANSACTION_CNT
    , dfsf.BUSINESS_DT AS BUSINESS_DATE
    , ''WTD'' AS CalculationType
FROM
    IDS_DEV.DATASTORE.DAILY_FLASH_SALES_FACT dfsf
INNER JOIN
    IDH_DEV.SHARED.DATE_DIM_V d
ON  dfsf.BUSINESS_DT = d.CALENDAR_DT
INNER JOIN
    IDH_DEV.SHARED.DATE_DIM_V d1c
ON  d1c.CALENDAR_DT = d.CALENDAR_COMPARABLE_DT
INNER JOIN
    IDH_DEV.SHARED.DATE_DIM_V d2c
ON  d2c.CALENDAR_DT = d1c.CALENDAR_COMPARABLE_DT
WHERE
    dfsf.BRAND_ID = ''ARG''
AND dfsf.SOURCE_SYSTEM_NM = ''RTI''
AND NOT (dfsf.BRAND_ID = ''ARG'' AND dfsf.SOURCE_SYSTEM_NM <> ''RTI'')
AND BUSINESS_DATE BETWEEN d2c.CALENDAR_WEEK_START_DT AND d2c.CALENDAR_DT
GROUP BY
    dfsf.STORE_ID
    , dfsf.BUSINESS_DT

';
CREATE FUNCTION IF NOT EXISTS SUMMARY_SALES_2YR("BUSINESS_DATE" VARCHAR(12))
RETURNS TABLE ("STORE_ID" VARCHAR(16777216), "NET_SALES_AMT" NUMBER(12,2), "TRANSACTION_CNT" NUMBER(38,0), "BUSINESS_DATE" DATE, "CALCULATIONTYPE" VARCHAR(16777216))
LANGUAGE SQL
AS '

SELECT
    dfsf.STORE_ID
    , SUM(dfsf.NET_SALES_AMT) AS NET_SALES_AMT
    , SUM(dfsf.TRANSACTION_CNT) AS TRANSACTION_CNT
    , dfsf.BUSINESS_DT AS BUSINESS_DATE
    , ''WTD'' AS CalculationType
FROM
    IDS_DEV.DATASTORE.DAILY_FLASH_SALES_FACT dfsf
INNER JOIN
    IDH_DEV.SHARED.DATE_DIM_V d
ON  dfsf.BUSINESS_DT = d.CALENDAR_DT
INNER JOIN
    IDH_DEV.SHARED.DATE_DIM_V d1c
ON  d1c.CALENDAR_DT = d.CALENDAR_COMPARABLE_DT
INNER JOIN
    IDH_DEV.SHARED.DATE_DIM_V d2c
ON  d2c.CALENDAR_DT = d1c.CALENDAR_COMPARABLE_DT
WHERE
    dfsf.BRAND_ID = ''ARG''
AND dfsf.SOURCE_SYSTEM_NM = ''RTI''
AND NOT (dfsf.BRAND_ID = ''ARG'' AND dfsf.SOURCE_SYSTEM_NM <> ''RTI'')
AND BUSINESS_DATE BETWEEN d2c.CALENDAR_WEEK_START_DT AND d2c.CALENDAR_DT
--AND dfsf.STORE_ID = STOREID
GROUP BY
    dfsf.STORE_ID
    , dfsf.BUSINESS_DT

';
CREATE FUNCTION IF NOT EXISTS SUMMARY_SALES_2YR("STOREID" NUMBER(38,0), "BUSINESS_DATE" VARCHAR(12))
RETURNS TABLE ("STORE_ID" VARCHAR(16777216), "NET_SALES_AMT" NUMBER(12,2), "TRANSACTION_CNT" NUMBER(38,0), "BUSINESS_DATE" DATE, "CALCULATIONTYPE" VARCHAR(16777216))
LANGUAGE SQL
AS '

SELECT
    dfsf.STORE_ID
    , SUM(dfsf.NET_SALES_AMT) AS NET_SALES_AMT
    , SUM(dfsf.TRANSACTION_CNT) AS TRANSACTION_CNT
    , dfsf.BUSINESS_DT AS BUSINESS_DATE
    , ''WTD'' AS CalculationType
FROM
    IDS_DEV.DATASTORE.DAILY_FLASH_SALES_FACT dfsf
INNER JOIN
    IDH_DEV.SHARED.DATE_DIM_V d
ON  dfsf.BUSINESS_DT = d.CALENDAR_DT
INNER JOIN
    IDH_DEV.SHARED.DATE_DIM_V d1c
ON  d1c.CALENDAR_DT = d.CALENDAR_COMPARABLE_DT
INNER JOIN
    IDH_DEV.SHARED.DATE_DIM_V d2c
ON  d2c.CALENDAR_DT = d1c.CALENDAR_COMPARABLE_DT
WHERE
    dfsf.BRAND_ID = ''ARG''
AND dfsf.SOURCE_SYSTEM_NM = ''RTI''
AND NOT (dfsf.BRAND_ID = ''ARG'' AND dfsf.SOURCE_SYSTEM_NM <> ''RTI'')
AND BUSINESS_DATE BETWEEN d2c.CALENDAR_WEEK_START_DT AND d2c.CALENDAR_DT
AND dfsf.STORE_ID = STOREID
GROUP BY
    dfsf.STORE_ID
    , dfsf.BUSINESS_DT

';
CREATE FUNCTION IF NOT EXISTS SUMMARY_SALES_2YR("STOREID" VARCHAR(100), "BUSINESS_DATE" DATE)
RETURNS TABLE ("STORE_ID" VARCHAR(16777216), "NET_SALES_AMT" NUMBER(12,2), "TRANSACTION_CNT" NUMBER(38,0), "BUSINESS_DATE" DATE, "CALCULATIONTYPE" VARCHAR(16777216))
LANGUAGE SQL
AS '

SELECT
    dfsf.STORE_ID
    , SUM(dfsf.NET_SALES_AMT) AS NET_SALES_AMT
    , SUM(dfsf.TRANSACTION_CNT) AS TRANSACTION_CNT
    , d.CALENDAR_DT AS BUSINESS_DATE
    , ''WTD'' AS CalculationType
FROM
    IDH_DEV.SHARED.DATE_DIM_V d
INNER JOIN
    IDH_DEV.SHARED.DATE_DIM_V d1c
ON  d1c.CALENDAR_DT = d.CALENDAR_COMPARABLE_DT
INNER JOIN
    IDH_DEV.SHARED.DATE_DIM_V d2c
ON  d2c.CALENDAR_DT = d1c.CALENDAR_COMPARABLE_DT
INNER JOIN
    IDS_DEV.DATASTORE.DAILY_FLASH_SALES_FACT dfsf
ON  dfsf.BUSINESS_DT = d2c.CALENDAR_DT
WHERE
    dfsf.BRAND_ID = ''ARG''
AND dfsf.SOURCE_SYSTEM_NM = ''RTI''
AND NOT (dfsf.BRAND_ID = ''ARG'' AND dfsf.SOURCE_SYSTEM_NM <> ''RTI'')
AND BUSINESS_DATE BETWEEN d2c.CALENDAR_WEEK_START_DT AND d2c.CALENDAR_DT
AND dfsf.STORE_ID = STOREID
GROUP BY
    dfsf.STORE_ID
    , d.CALENDAR_DT

';
CREATE FUNCTION IF NOT EXISTS SUMMARY_SALES_2YR("STOREID" VARCHAR(100), "BUSINESS_DATE" VARCHAR(12))
RETURNS TABLE ("STORE_ID" VARCHAR(16777216), "NET_SALES_AMT" NUMBER(12,2), "TRANSACTION_CNT" NUMBER(38,0), "BUSINESS_DATE" DATE, "CALCULATIONTYPE" VARCHAR(16777216))
LANGUAGE SQL
AS '

SELECT
    dfsf.STORE_ID
    , SUM(dfsf.NET_SALES_AMT) AS NET_SALES_AMT
    , SUM(dfsf.TRANSACTION_CNT) AS TRANSACTION_CNT
    , dfsf.BUSINESS_DT AS BUSINESS_DATE
    , ''WTD'' AS CalculationType
FROM
    IDS_DEV.DATASTORE.DAILY_FLASH_SALES_FACT dfsf
INNER JOIN
    IDH_DEV.SHARED.DATE_DIM_V d
ON  dfsf.BUSINESS_DT = d.CALENDAR_DT
INNER JOIN
    IDH_DEV.SHARED.DATE_DIM_V d1c
ON  d1c.CALENDAR_DT = d.CALENDAR_COMPARABLE_DT
INNER JOIN
    IDH_DEV.SHARED.DATE_DIM_V d2c
ON  d2c.CALENDAR_DT = d1c.CALENDAR_COMPARABLE_DT
WHERE
    dfsf.BRAND_ID = ''ARG''
AND dfsf.SOURCE_SYSTEM_NM = ''RTI''
AND NOT (dfsf.BRAND_ID = ''ARG'' AND dfsf.SOURCE_SYSTEM_NM <> ''RTI'')
AND BUSINESS_DATE BETWEEN d2c.CALENDAR_WEEK_START_DT AND d2c.CALENDAR_DT
AND dfsf.STORE_ID = STOREID
GROUP BY
    dfsf.STORE_ID
    , dfsf.BUSINESS_DT

';
CREATE FUNCTION IF NOT EXISTS SUMMARY_SALES_3YR("STOREID" VARCHAR(100), "BUSINESS_DATE" DATE)
RETURNS TABLE ("STORE_ID" VARCHAR(16777216), "NET_SALES_AMT" NUMBER(12,2), "TRANSACTION_CNT" NUMBER(38,0), "BUSINESS_DATE" DATE, "CALCULATIONTYPE" VARCHAR(16777216))
LANGUAGE SQL
AS '

SELECT
    dfsf.STORE_ID
    , SUM(dfsf.NET_SALES_AMT) AS NET_SALES_AMT
    , SUM(dfsf.TRANSACTION_CNT) AS TRANSACTION_CNT
    , d.CALENDAR_DT AS BUSINESS_DATE
    , ''MTD'' AS CalculationType
FROM
    IDH_DEV.SHARED.DATE_DIM_V d
INNER JOIN
    IDH_DEV.SHARED.DATE_DIM_V d1c
ON  d1c.CALENDAR_DT = d.CALENDAR_COMPARABLE_DT
INNER JOIN
    IDH_DEV.SHARED.DATE_DIM_V d2c
ON  d2c.CALENDAR_DT = d1c.CALENDAR_COMPARABLE_DT
INNER JOIN
    IDH_DEV.SHARED.DATE_DIM_V d3c
ON  d3c.CALENDAR_DT = d2c.CALENDAR_COMPARABLE_DT
INNER JOIN
    IDS_DEV.DATASTORE.DAILY_FLASH_SALES_FACT dfsf
ON  dfsf.BUSINESS_DT = d3c.CALENDAR_DT
WHERE
    dfsf.BRAND_ID = ''ARG''
AND dfsf.SOURCE_SYSTEM_NM = ''RTI''
AND NOT (dfsf.BRAND_ID = ''ARG'' AND dfsf.SOURCE_SYSTEM_NM <> ''RTI'')
AND BUSINESS_DATE BETWEEN d2c.CALENDAR_MONTH_START_DT AND d2c.CALENDAR_DT
AND dfsf.STORE_ID = STOREID
GROUP BY
    dfsf.STORE_ID
    , d.CALENDAR_DT

';
CREATE FUNCTION IF NOT EXISTS SUMMARY_SALES_COMP_2YR("BUSINESS_DATE" VARCHAR(16777216))
RETURNS TABLE ("STORE_ID" VARCHAR(16777216), "NET_SALES_AMT" NUMBER(12,2), "TRANSACTION_CNT" NUMBER(38,0), "CALCULATIONTYPE" VARCHAR(16777216))
LANGUAGE SQL
AS '

SELECT
    dfsf.STORE_ID
    , SUM(dfsf.NET_SALES_AMT) AS NET_SALES_AMT
    , SUM(dfsf.TRANSACTION_CNT) AS TRANSACTION_CNT
    , ''WTD'' AS CalculationType
FROM
    IDS_DEV.DATASTORE.DAILY_FLASH_SALES_FACT dfsf
INNER JOIN
    IDH_DEV.SHARED.DATE_DIM_V d
ON  dfsf.BUSINESS_DT = d.CALENDAR_DT
WHERE
    dfsf.BRAND_ID = ''ARG''
AND dfsf.SOURCE_SYSTEM_NM = ''RTI''
AND NOT (dfsf.BRAND_ID = ''ARG'' AND dfsf.SOURCE_SYSTEM_NM <> ''RTI'')
AND BUSINESS_DATE BETWEEN d.CALENDAR_WEEK_START_DT AND d.CALENDAR_DT
GROUP BY
    dfsf.STORE_ID

';