spark.source.columns F&B Bar,F&B Minibar,F&B Cabanas (Onboard),F&B Cabanas (Beach Club),F&B Treat Yoself Food,F&B Food Delivery,F&B Private Functions,Casino Tables,Casino Slots,Casino VIP,Shore Things,Overland Excursions,Retail FJ Stores,Retail Watch,Retail Vbrand,Retail W-Lifestyle,Retail Leather/Accessories,Retail Beauty,Retail Fashion Jewelry,Retail Liquor,Retail M-Lifestyle,Retail Pop-Up 1,Retail Pop-Up 2,Retail Vice,Retail Essential,Retail Resort,Retail Record,Entertainment The Manor Dinner Show,Entertainment Risque Bingo,Entertainment Karaoke/Little Cinema,Entertainment Grog Walk,Entertainment Drag Brunch,Entertainment Wellness Day with Alex,Entertainment Rock Star Access Tour,Entertainment Mix It Up,Entertainment Picture Perfect,Entertainment Cooking Classes,Tech Premium Wifi,Tech Photo Pkg,Tech Movies Pkg,Tech Cell Phone,Spa Spa Services,Spa Medi Spa,Spa Acupuncture,Spa Retail,Spa Thermal Suite,Bundles,Tattoo & Piercings,In Room Gifts,Laundry,Hospital,Intimacy Kit
spark.pond.database shipdw
spark.pond.table hvtb_mart_voyage_obr_target_lkp
spark.target.final_collist voyage_number,target_revenue_stream,net_apd_target_amount,gross_apd_target_amount,NVL(plan_load_factor_pct, 0) as plan_load_factor_pct,NVL(plan_sailors, 0) as plan_sailors,load_dt,upd_dt,part_dt
spark.target.temp /data/apps/nbx/temp/hvtb_mart_voyage_obr_target_lkp
spark.target.location /data/apps/nbx/mart/hvtb_mart_voyage_obr_target_lkp
spark.postgresql.schema Hive_schema_stg
spark.postgresql.tablename voyage_obr_target_lkp
spark.tableType FACT
spark.frameworkEnv ship
spark.postgresql.user nifiusr
spark.postgresql.password finiPRO@123
spark.postgresql.url jdbc:postgresql://10.102.209.154:5432/
spark.postgresql.database prodnbx
spark.target.zkurl P-VAL-DLK-ADA1.ahoy.virginvoyages.com:2181/hbase-secure
spark.source.location /tmp/OBR.xlsx

