CREATE OR REPLACE VIEW RDS_{{params.env}}.ARB_BV.DEPOSITS_BV AS SELECT * FROM RDS_PROD.ARB.DEPOSITS;
CREATE OR REPLACE VIEW RDS_{{params.env}}.ARB_BV.CASH_VARIANCE_BV AS SELECT * FROM RDS_PROD.ARB.CASH_VARIANCE;
CREATE OR REPLACE VIEW RDS_{{params.env}}.ARB_BV.PAID_IN_OUT_BV AS SELECT * FROM RDS_PROD.ARB.PAID_IN_OUT;
CREATE OR REPLACE VIEW RDS_{{params.env}}.ARB_BV.CASH_ITEM_SALES_AND_COUNTS_BV AS SELECT * FROM RDS_PROD.ARB.CASH_ITEM_SALES_AND_COUNTS;
CREATE OR REPLACE VIEW RDS_{{params.env}}.ARB_BV.REPORTING_ITEM_SALES_AND_COUNTS_BV AS SELECT * FROM RDS_PROD.ARB.REPORTING_ITEM_SALES_AND_COUNTS;
CREATE OR REPLACE VIEW RDS_{{params.env}}.ARB_BV.ORACLE_GL_BV AS SELECT * FROM RDS_PROD.ARB.ORACLE_GL;