CREATE OR REPLACE VIEW RDS_{{params.env}}.BWW_BV.BOS_ALTAMETRICS_SALES_BV AS SELECT * FROM RDS_{{params.env}}.BWW.BOS_ALTAMETRICS_SALES;
CREATE OR REPLACE VIEW RDS_{{params.env}}.BWW_BV.NBO_ST_REGISTER_BV AS SELECT * FROM RDS_{{params.env}}.BWW.NBO_ST_REGISTER;
CREATE OR REPLACE VIEW RDS_{{params.env}}.BWW_BV.DPVHSTCHECKSUMMARY_BV AS SELECT * FROM RDS_{{params.env}}.BWW.DPVHSTCHECKSUMMARY;
CREATE OR REPLACE VIEW RDS_{{params.env}}.BWW_BV.DPVHSTGNDTENDER_BV AS SELECT * FROM RDS_{{params.env}}.BWW.DPVHSTGNDTENDER;
CREATE OR REPLACE VIEW RDS_{{params.env}}.BWW_BV.DPVHSTSALESBYINTERVAL_BV AS SELECT * FROM RDS_{{params.env}}.BWW.DPVHSTSALESBYINTERVAL;
CREATE OR REPLACE VIEW RDS_{{params.env}}.BWW_BV.ITEMCATEGORYCUSTOM_BV AS SELECT * FROM RDS_{{params.env}}.BWW.ITEMCATEGORYCUSTOM;
CREATE OR REPLACE VIEW RDS_{{params.env}}.BWW_BV.DPVHSTGNDITEM_BV AS SELECT * FROM RDS_{{params.env}}.BWW.DPVHSTGNDITEM;