CREATE OR REPLACE VIEW RDS_{{params.env}}.JJE_BV.BOS_ALTAMETRICS_SALES_BV AS SELECT * FROM RDS_{{params.env}}.JJE.BOS_ALTAMETRICS_SALES;
CREATE OR REPLACE VIEW RDS_{{params.env}}.JJE_BV.ORACLE_GL_BV AS SELECT * FROM RDS_{{params.env}}.JJE.ORACLE_GL;
