CREATE OR REPLACE VIEW RDS_{{params.env}}.SDI_BV.BOS_INFOR_SALES_BV AS SELECT * FROM RDS_{{params.env}}.SDI.BOS_INFOR_SALES;
CREATE OR REPLACE VIEW RDS_{{params.env}}.SDI_BV.BOS_MICROS_SALES_BV AS SELECT * FROM RDS_{{params.env}}.SDI.BOS_MICROS_SALES;
CREATE OR REPLACE VIEW RDS_{{params.env}}.SDI_BV.ORACLE_GL_BV AS SELECT * FROM RDS_{{params.env}}.SDI.ORACLE_GL;