dag_id: "DUNKIN_POS_IDS_TO_IDS_DAILY_ALL_HI_PL"
dag_description: "DUNKIN data load from IDS to IDS"
email: ['vagicharla.sudana@inspirebrands.com']
source_env : "GOLD"
target_env : "DEV"
warehouse_id : "IRB_PRCSSA_IRB_WH"
schema_id : "DUN"