# Paths
utils_path: "/opt/airflow/dags/transaction/global_utils"
airflow_path: "/opt/airflow/dags/transaction/global_utils/airflow"

# Global settings
dag_id: "E2E_SALES_RECON_SDI_POS_INFOR_MICROS_DQ"
dag_description: "Mailing DAG for DQ framework"
emails: ['itdataservicessupport@inspirebrands.com','sedwards@inspirebrands.com','ejorgensen@inspirebrands.com','PFischer@inspirebrands.com','rajesh.patil@inspirebrands.com','saxena.ankur@inspirebrands.com','yatender.kumar@inspirebrands.com']
owner: "DQ"

snowflake_conn_irb_objowner_id: "Snowflake-IRB-PROD-OWNER"
warehouse_name: "IRB_PRCSSA_IRB_PROD_WH"
env: "PROD"

database: "IDS_PROD"
schema_name: "INT_REF"
target_schema: "Sales Recon (POS)"
brand: "%"
table_list:
  - POS_DAILY_SALES_MEASURE_SONIC


# Paths
utils_path: "/opt/airflow/dags/transaction/global_utils"
airflow_path: "/opt/airflow/dags/transaction/global_utils/airflow"
