# Global settings
dag_id: "JJ_BOS_DQ_ALL_HI_PL_TEST"
dag_description: "Mailing DAG for DQ framework"
emails: ['ravi.voleti@inspirebrands.com']
owner: "DQ"

snowflake_conn_irb_objowner_id: "Snowflake-IRB-PROD-OWNER"
warehouse_name: "IRB_PRCSSA_IRB_PROD_WH"
env: "PROD"

database: "IDS_PROD"
schema_name: "INT_REF"
target_schema: "Sales Recon (BOS) - JJ"
brand: "%"
table_list:
  - emp_ravi

# Paths
utils_path: "/opt/airflow/dags/transaction/global_utils"
airflow_path: "/opt/airflow/dags/transaction/global_utils/airflow"