CREATE FILE FORMAT IF NOT EXISTS "RDS_PROD"."ARB".GENERAL_LEDGER_ARB_FILE_FORMAT 
  COMPRESSION = 'AUTO' 
  FIELD_DELIMITER = '|' 
  RECORD_DELIMITER = '\n' 
  SKIP_HEADER = 1 
  FIELD_OPTIONALLY_ENCLOSED_BY = '\042' 
  TRIM_SPACE = FALSE 
  ERROR_ON_COLUMN_COUNT_MISMATCH = TRUE 
  ESCAPE = 'NONE' 
  ESCAPE_UNENCLOSED_FIELD = '\134' 
  DATE_FORMAT = 'AUTO' 
  TIMESTAMP_FORMAT = 'AUTO' 
  NULL_IF = ('\\N');
   
CREATE FILE FORMAT IF NOT EXISTS "RDS_PROD"."ARB".ALTAMETRICS_ARB_FILE_FORMAT 
  COMPRESSION = 'AUTO' 
  FIELD_DELIMITER = ',' 
  RECORD_DELIMITER = '\n' 
  SKIP_HEADER = 1 
  FIELD_OPTIONALLY_ENCLOSED_BY = 'NONE' 
  TRIM_SPACE = FALSE 
  ERROR_ON_COLUMN_COUNT_MISMATCH = TRUE 
  ESCAPE = 'NONE' 
  ESCAPE_UNENCLOSED_FIELD = '\134' 
  DATE_FORMAT = 'AUTO' 
  TIMESTAMP_FORMAT = 'AUTO' 
  NULL_IF = ('\\N');

CREATE FILE FORMAT IF NOT EXISTS "RDS_QA"."ARB".POS_REVENUE_CENTER_FILE_FORMAT 
  TYPE= XML
  COMPRESSION='AUTO';

CREATE FILE FORMAT IF NOT EXISTS "RDS_QA"."ARB".POS_ITEM_FILE_FORMAT 
  TYPE= XML
  COMPRESSION='AUTO';
