insert into vv_db.processdriver values('CDC_crm_account','main_table_query','select * from bd_db.stg_crm_account');
insert into vv_db.processdriver values('CDC_crm_account','incr_table_query','select * from bd_db.stg_crm_account_cdc');
insert into vv_db.processdriver values('CDC_crm_account','subtract_query','SELECT a.id, a.isdeleted, a.masterrecordid, a.name, a.lastname, a.firstname, a.salutation, a.middlename, a.suffix, a.type, a.recordtypeid, a.parentid, a.billingstreet, a.billingcity, a.billingstate, a.billingpostalcode, a.billingcountry, a.billingstatecode, a.billingcountrycode, a.billinglatitude, a.billinglongitude, a.billinggeocodeaccuracy, a.billingaddress, a.shippingstreet, a.shippingcity, a.shippingstate, a.shippingpostalcode, a.shippingcountry, a.shippingstatecode, a.shippingcountrycode, a.shippinglatitude, a.shippinglongitude, a.shippinggeocodeaccuracy, a.shippingaddress, a.phone, a.website, a.photourl, a.industry, a.numberofemployees, a.description, a.currencyisocode, a.ownerid, a.createddate, a.createdbyid, a.lastmodifieddate, a.lastmodifiedbyid, a.systemmodstamp, a.lastactivitydate, a.lastvieweddate, a.lastreferenceddate, a.ispartner, a.iscustomerportal, a.personcontactid, a.ispersonaccount, a.personmailingstreet, a.personmailingcity, a.personmailingstate, a.personmailingpostalcode, a.personmailingcountry, a.personmailingstatecode, a.personmailingcountrycode, a.personmailinglatitude, a.personmailinglongitude, a.personmailinggeocodeaccuracy, a.personmailingaddress, a.personmobilephone, a.personemail, a.persontitle, a.persondepartment, a.personbirthdate, a.personlastcurequestdate, a.personlastcuupdatedate, a.personemailbouncedreason, a.personemailbounceddate, a.jigsaw, a.jigsawcompanyid, a.accountsource, a.sicdesc, a.arc_number__c, a.agency_code__c, a.primary_contact_email__c, a.instagram__c, a.sailorid__c, a.sfssdupecatcher__override_dupecatcher__c, a.clia_number__c, a.citizenship_country__c, a.client_id__c, a.country_of_residence__c, a.magnoliapassword__c, a.household_id__c, a.iata_number__c, a.inbound__c, a.pseudocitycode__c, a.age__c, a.tribe__c, a.number_of_active_agents__c, a.occupation__c, a.office_code__c, a.outbound_email__c, a.outbound__c, a.preferred_name__c, a.seaware_agency_id__c, a.status__c, a.taxpayer_id__c, a.taxpayer_type__c, a.total_lifetime_cruise_nights__c, a.consortium__c, a.total_revenue__c, a.web_address__c, a.abta_number__c, a.preferred_gender__c, a.yelp__c, a.facebook__c, a.twitter__c, a.snapchat__c, a.subtribe__c, a.no_social_contact__c, a.state_of_the_sailor__c, a.data_source__c, a.w9_form_received__c, a.cover_letter_received__c, a.business_license__c, a.business_license_type__c, a.gdloyallevel__c, a.average_lifetime_spend_per_night__c, a.average_spend_per_night_for_last_cruise__c, a.total_lifetime_spend__c, a.registered_for_web__c, a.downloaded_mobile_app__c, a.vxp_id__c, a.gdloyallevelcode__c, a.consortium_type__c, a.floating_deposit__c, a.secured_fax_email__c, a.isgsa__c, a.isinternal__c, a.iswhitelabel__c, a.taxowner__c, a.snprefix__c, a.inactivereason__c, a.asta_number__c, a.ismasterxref__c, a.t_c_consent_date__c, a.t_c_consent_first_name__c, a.t_c_consent_last_name__c, a.groupname__c, a.groupleader__c, a.is_primary_contact__pc, a.sfssdupecatcher__override_dupecatcher__pc, a.gender__pc, a.iatan_company_name__pc, a.iatan_holder_name__pc, a.iatan_number__pc, a.agent_type__pc, a.preferred_language__pc, a.seaware_agent_id__pc, a.status__pc, a.suffix__pc, a.target_revenue__pc, a.total_revenue__pc, a.agent_status__pc, a.alternate_name__pc, a.anniversary_date__pc, a.et4ae5__hasoptedoutofmobile__pc, a.et4ae5__mobile_country_code__pc, a.iatanexpdate__pc, a.marital_status__pc, a.t_c_consent_first_name__pc, a.t_c_consent_last_name__pc, a.passport_exp_date__pc, a.passport_number__pc, a.t_c_consent_date__pc, a.sales_commission__pc, a.sales_commission_amount__pc, a.job_id, a.load_data_timestamp, a.epoc, a.year, a.month, a.day FROM bd_db.stg_crm_account a left join bd_db.stg_crm_account_cdc b on a.id=b.id where b.id is null');
insert into vv_db.processdriver values('CDC_crm_account','temp_file_path','s3a://vv-qa-emr-cluster/data/landing/crm/stg_crm_account');
insert into vv_db.processdriver values('CDC_crm_account','original_file_path','s3a://vv-qa-emr-cluster/data/staging/crm/stg_crm_account');

insert into vv_db.processdriver values('CDC_crm_address','main_table_query','select * from bd_db.stg_crm_address');
insert into vv_db.processdriver values('CDC_crm_address','incr_table_query','select * from bd_db.stg_crm_address_cdc');
insert into vv_db.processdriver values('CDC_crm_address','subtract_query','SELECT a.id, a.ownerid, a.isdeleted, a.name, a.currencyisocode, a.createddate, a.createdbyid, a.lastmodifieddate, a.lastmodifiedbyid, a.systemmodstamp, a.primary__c, a.streetnmbr__c, a.addline__c, a.cityname__c, a.postalcode__c, a.county__c, a.statecode__c, a.countrycode__c, a.sailor__c, a.addressuniqueid__c, a.job_id, a.load_data_timestamp, a.epoc, a.year, a.month, a.day FROM bd_db.stg_crm_address a left join bd_db.stg_crm_address_cdc b on a.id=b.id where b.id is null');
insert into vv_db.processdriver values('CDC_crm_address','temp_file_path','s3a://vv-qa-emr-cluster/data/landing/crm/stg_crm_address');
insert into vv_db.processdriver values('CDC_crm_address','original_file_path','s3a://vv-qa-emr-cluster/data/staging/crm/stg_crm_address');

insert into vv_db.processdriver values('CDC_crm_bookable_activities','incr_table_query','select * from bd_db.stg_crm_bookable_activities_cdc');
insert into vv_db.processdriver values('CDC_crm_bookable_activities','main_table_query','select * from bd_db.stg_crm_bookable_activities');
insert into vv_db.processdriver values('CDC_crm_bookable_activities','subtract_query','SELECT a.id, a.isdeleted, a.name, a.currencyisocode, a.createddate, a.createdbyid, a.lastmodifieddate, a.lastmodifiedbyid, a.systemmodstamp, a.booking_id__c, a.edate__c, a.duration__c, a.bookable_activity_id__c, a.description__c, a.travel_party_member__c, a.activity_date__c, a.category__c, a.cruisepackagecode__c, a.bkuniqueid__c, a.location__c, a.internal_code__c, a.packagesubtype__c, a.packagetypecode__c, a.sdate__c, a.job_id, a.load_data_timestamp, a.epoc, a.year, a.month, a.day FROM bd_db.stg_crm_bookable_activities a left join bd_db.stg_crm_bookable_activities_cdc b on a.id=b.id where b.id is null');
insert into vv_db.processdriver values('CDC_crm_bookable_activities','temp_file_path','s3a://vv-qa-emr-cluster/data/landing/crm/stg_crm_bookable_activities');
insert into vv_db.processdriver values('CDC_crm_bookable_activities','original_file_path','s3a://vv-qa-emr-cluster/data/staging/crm/stg_crm_bookable_activities');

insert into vv_db.processdriver values('CDC_crm_booking_payments','temp_file_path','s3a://vv-qa-emr-cluster/data/landing/crm/stg_crm_booking_payments');
insert into vv_db.processdriver values('CDC_crm_booking_payments','original_file_path','s3a://vv-qa-emr-cluster/data/staging/crm/stg_crm_booking_payments');
insert into vv_db.processdriver values('CDC_crm_booking_payments','incr_table_query','select * from bd_db.stg_crm_booking_payments_cdc ');
insert into vv_db.processdriver values('CDC_crm_booking_payments','main_table_query','select * from bd_db.stg_crm_booking_payments');
insert into vv_db.processdriver values('CDC_crm_booking_payments','subtract_query','SELECT a.id, a.isdeleted, a.name, a.currencyisocode, a.createddate, a.createdbyid, a.lastmodifieddate, a.lastmodifiedbyid, a.systemmodstamp, a.lastvieweddate, a.lastreferenceddate, a.booking_id__c, a.payment_amount__c, a.paymentcode__c, a.payment_type__c, a.quote_id__c, a.payment_date__c, a.preferred_currency__c, a.preferred_currency_amount__c, a.job_id, a.load_data_timestamp, a.epoc, a.year, a.month, a.day FROM bd_db.stg_crm_booking_payments a left join bd_db.stg_crm_booking_payments_cdc b on a.id=b.id where b.id is null');

insert into vv_db.processdriver values('CDC_crm_campaign','original_file_path','s3a://vv-qa-emr-cluster/data/staging/crm/stg_crm_campaign');
insert into vv_db.processdriver values('CDC_crm_campaign','temp_file_path','s3a://vv-qa-emr-cluster/data/landing/crm/stg_crm_campaign');
insert into vv_db.processdriver values('CDC_crm_campaign','incr_table_query','select * from bd_db.stg_crm_campaign_cdc ');
insert into vv_db.processdriver values('CDC_crm_campaign','main_table_query','select * from bd_db.stg_crm_campaign');
insert into vv_db.processdriver values('CDC_crm_campaign','subtract_query','select a.id,a.isdeleted,a.name,a.parentid,a.type,a.status,a.startdate,a.enddate,a.currencyisocode,a.expectedrevenue,a.budgetedcost,a.actualcost,a.expectedresponse,a.numbersent,a.isactive,a.description,a.numberofleads,a.numberofconvertedleads,a.numberofcontacts,a.numberofresponses,a.numberofopportunities,a.numberofwonopportunities,a.amountallopportunities,a.amountwonopportunities,a.hierarchynumberofleads,a.hierarchynumberofconvertedleads,a.hierarchynumberofcontacts,a.hierarchynumberofresponses,a.hierarchynumberofwonopportunities,a.hierarchynumbersent,a.hierarchyexpectedrevenue,a.hierarchyactualcost,a.ownerid,a.createddate,a.createdbyid,a.lastmodifieddate,a.lastmodifiedbyid,a.systemmodstamp,a.lastactivitydate,a.lastvieweddate,a.lastreferenceddate,a.campaignmemberrecordtypeid,a.campaign_channel__c,a.campaign_country__c,a.campaign_office__c,a.campaign_region__c,a.coupon_code__c,a.coupon_description__c,a.coupon_name__c,a.plan_code__c,a.segment_code__c,a.variation_code__c,a.plan_name__c,a.campaign_brand__c,a.campaign_code__c,a.coupon_activation_date__c,a.coupon_expiration_date__c,a.program_code__c,a.program_name__c,a.sub_plan_code__c,a.sub_plan_name__c,a.treatment_activation_date__c,a.treatment_code__c,a.treatment_description__c,a.treatment_expiration_date__c,a.treatment_name__c,a.treatment_type__c,a.wave_code__c,a.opportunity__c,a.voyagespecific__c,a.voyage__c,a.campaignid__c,a.db_campaign_tactic__c,a.job_id,a.load_data_timestamp,a.epoc,a.year,a.month,a.day from bd_db.stg_crm_campaign a left join bd_db.stg_crm_campaign_cdc b on a.id=b.id where b.id is null');

insert into vv_db.processdriver values('CDC_crm_case','main_table_query','select * from bd_db.stg_crm_case');
insert into vv_db.processdriver values('CDC_crm_case','incr_table_query','select * from bd_db.stg_crm_case_cdc');
Insert into vv_db.processdriver(processname, variablename, value) values ('CDC_crm_case','subtract_query','SELECT a.id, a.isdeleted, a.casenumber, a.contactid, a.accountid, a.entitlementid, a.sourceid, a.parentid, a.suppliedname, a.suppliedemail, a.suppliedphone, a.suppliedcompany, a.type, a.recordtypeid, a.status, a.reason, a.origin, a.subject, a.priority, a.description, a.isclosed, a.closeddate, a.isescalated, a.currencyisocode, a.ownerid, a.createddate, a.createdbyid, a.lastmodifieddate, a.lastmodifiedbyid, a.systemmodstamp, a.contactphone, a.contactmobile, a.contactemail, a.contactfax, a.lastvieweddate, a.lastreferenceddate, a.opportunity__c, a.booked_activities__c, a.booking_payments__c, a.category__c, a.sub_category__c, a.casesubreason__c, a.link__c, a.voyage__c, a.transferred_to__c, a.escalation_reason__c, a.description__c, a.webfname__c, a.last_interaction_date__c, a.weblname__c, a.case_resolution__c, a.sailor_email__c, a.sailor_name__c, a.job_id, a.load_data_timestamp, a.epoc, a.year, a.month, a.day FROM bd_db.stg_crm_case a left join bd_db.stg_crm_case_cdc b on a.id=b.id where b.id is null');
insert into vv_db.processdriver values('CDC_crm_case','temp_file_path','s3a://vv-qa-emr-cluster/data/landing/crm/stg_crm_case');
insert into vv_db.processdriver values('CDC_crm_case','original_file_path','s3a://vv-qa-emr-cluster/data/staging/crm/stg_crm_case');

insert into vv_db.processdriver values('CDC_crm_contact','original_file_path','s3a://vv-qa-emr-cluster/data/staging/crm/stg_crm_contact');
insert into vv_db.processdriver values('CDC_crm_contact','temp_file_path','s3a://vv-qa-emr-cluster/data/landing/crm/stg_crm_contact');
insert into vv_db.processdriver values('CDC_crm_contact','main_table_query','select * from bd_db.stg_crm_contact');
insert into vv_db.processdriver values('CDC_crm_contact','incr_table_query','select * from bd_db.stg_crm_contact_cdc');
insert into vv_db.processdriver values('CDC_crm_contact','subtract_query','SELECT a.id, a.isdeleted, a.masterrecordid, a.accountid, a.ispersonaccount, a.lastname, a.firstname, a.salutation, a.middlename, a.suffix, a.name, a.recordtypeid, a.mailingstreet, a.mailingcity, a.mailingstate, a.mailingpostalcode, a.mailingcountry, a.mailingstatecode, a.mailingcountrycode, a.mailinglatitude, a.mailinglongitude, a.mailinggeocodeaccuracy, a.mailingaddress, a.phone, a.fax, a.mobilephone, a.reportstoid, a.email, a.title, a.department, a.birthdate, a.currencyisocode, a.ownerid, a.createddate, a.createdbyid, a.lastmodifieddate, a.lastmodifiedbyid, a.systemmodstamp, a.lastactivitydate, a.lastcurequestdate, a.lastcuupdatedate, a.lastvieweddate, a.lastreferenceddate, a.emailbouncedreason, a.emailbounceddate, a.isemailbounced, a.photourl, a.jigsaw, a.jigsawcontactid, a.is_primary_contact__c, a.sfssdupecatcher__override_dupecatcher__c, a.gender__c, a.iatan_company_name__c, a.iatan_holder_name__c, a.iatan_number__c, a.agent_type__c, a.preferred_language__c, a.seaware_agent_id__c, a.status__c, a.suffix__c, a.target_revenue__c, a.total_revenue__c, a.agent_status__c, a.alternate_name__c, a.anniversary_date__c, a.et4ae5__hasoptedoutofmobile__c, a.et4ae5__mobile_country_code__c, a.iatanexpdate__c, a.marital_status__c, a.t_c_consent_first_name__c, a.t_c_consent_last_name__c, a.passport_exp_date__c, a.passport_number__c, a.t_c_consent_date__c, a.sales_commission__c, a.sales_commission_amount__c, a.job_id, a.load_data_timestamp, a.epoc, a.year, a.month, a.day FROM bd_db.stg_crm_contact a left join bd_db.stg_crm_contact_cdc b on a.id=b.id where b.id is null');

insert into vv_db.processdriver values('CDC_crm_contact_details','temp_file_path','s3a://vv-qa-emr-cluster/data/landing/crm/stg_crm_contact_details');
insert into vv_db.processdriver values('CDC_crm_contact_details','incr_table_query','select * from bd_db.stg_crm_contact_details_cdc');
insert into vv_db.processdriver values('CDC_crm_contact_details','main_table_query','select * from bd_db.stg_crm_contact_details');
insert into vv_db.processdriver values('CDC_crm_contact_details','subtract_query','SELECT a.id, a.ownerid, a.isdeleted, a.name, a.currencyisocode, a.createddate, a.createdbyid, a.lastmodifieddate, a.lastmodifiedbyid, a.systemmodstamp, a.primary__c, a.plocationtype__c, a.countrycode__c, a.areacitycode__c, a.phonenumber__c, a.extension__c, a.sailor__c, a.condetailuniqueid__c, a.emergencyflag__c, a.job_id, a.load_data_timestamp, a.epoc, a.year, a.month, a.day FROM bd_db.stg_crm_contact_details a left join bd_db.stg_crm_contact_details_cdc b on a.id=b.id where b.id is null');
insert into vv_db.processdriver values('CDC_crm_contact_details','original_file_path','s3a://vv-qa-emr-cluster/data/staging/crm/stg_crm_contact_details');

insert into vv_db.processdriver values('CDC_crm_household','temp_file_path','s3a://vv-qa-emr-cluster/data/landing/crm/stg_crm_household');
insert into vv_db.processdriver values('CDC_crm_household','incr_table_query','select * from bd_db.stg_crm_household_cdc');
insert into vv_db.processdriver values('CDC_crm_household','main_table_query','select * from bd_db.stg_crm_household');
insert into vv_db.processdriver values('CDC_crm_household','subtract_query','SELECT a.id, a.ownerid, a.isdeleted, a.name, a.currencyisocode, a.createddate, a.createdbyid, a.lastmodifieddate, a.lastmodifiedbyid, a.systemmodstamp, a.lastvieweddate, a.lastreferenceddate, a.number_of_household_members__c, a.household_address_postal_code__c, a.household_address_state__c, a.primary_sailor__c, a.seaware_household_id__c, a.status__c, a.total_lifetime_cruise_nights__c, a.household_address_line_2__c, a.total_obs_amount__c, a.household_address_city__c, a.average_lifetime_spend_per_night__c, a.average_spend_per_night_for_last_cruise__c, a.total_lifetime_spend__c, a.household_address_line_1__c, a.job_id, a.load_data_timestamp, a.epoc, a.year, a.month, a.day FROM bd_db.stg_crm_household a left join bd_db.stg_crm_household_cdc b on a.id=b.id where b.id is null');
insert into vv_db.processdriver values('CDC_crm_household','original_file_path','s3a://vv-qa-emr-cluster/data/staging/crm/stg_crm_household');

insert into vv_db.processdriver values('CDC_crm_opportunity','temp_file_path','s3a://vv-qa-emr-cluster/data/landing/crm/stg_crm_opportunity');
insert into vv_db.processdriver values('CDC_crm_opportunity','incr_table_query','select * from bd_db.stg_crm_opportunity_cdc');
insert into vv_db.processdriver values('CDC_crm_opportunity','main_table_query','select * from bd_db.stg_crm_opportunity');
insert into vv_db.processdriver values('CDC_crm_opportunity','subtract_query','SELECT a.id, a.isdeleted, a.accountid, a.recordtypeid, a.name, a.description, a.stagename, a.amount, a.probability, a.closedate, a.type, a.nextstep, a.leadsource, a.isclosed, a.iswon, a.forecastcategory, a.forecastcategoryname, a.currencyisocode, a.campaignid, a.hasopportunitylineitem, a.pricebook2id, a.ownerid, a.createddate, a.createdbyid, a.lastmodifieddate, a.lastmodifiedbyid, a.systemmodstamp, a.lastactivitydate, a.fiscalquarter, a.fiscalyear, a.fiscal, a.lastvieweddate, a.lastreferenceddate, a.syncedquoteid, a.contractid, a.hasopenactivity, a.hasoverduetask, a.budget_confirmed__c, a.discovery_completed__c, a.roi_analysis_completed__c, a.loss_reason__c, a.agentname__c, a.ssstart__c, a.ssend__c, a.booking_id__c, a.voyageid__c, a.currency__c, a.ssduration__c, a.ssportsofcallquality__c, a.display_tab__c, a.next_payment_date__c, a.flight_purchase__c, a.group_id__c, a.sslosdescriptioncode__c, a.number_of_guests__c, a.number_of_stateroom__c, a.clshipname__c, a.package_type__c, a.parent_res_id__c, a.port_name__c, a.post_cruise_transfer__c, a.clvendorcode__c, a.prepaid_gratuities__c, a.regioncode__c, a.reservation_number__c, a.cruisepackagecode__c, a.sailing_package__c, a.ship_code__c, a.currencycode__c, a.status__c, a.vacation_protection__c, a.booking_payments_total__c, a.seaware_reservation_status__c, a.opportunity_amount__c, a.opportunityrevenueowner__c, a.vacation_start_date__c, a.record_type__c, a.parentbookingid__c, a.decimalplaces__c, a.bookeddate__c, a.cabin_category__c, a.disembarkation_date__c, a.embarkation_date__c, a.checked_in__c, a.offerdate__c, a.seaware_agentid__c, a.init_date__c, a.booking_channel__c, a.agencyid__c, a.voyage_status__c, a.preferred_currency__c, a.db_competitor__c, a.vacationenddate__c, a.self__c, a.guesttype__c, a.agencyname__c, a.preferred_currency_amount__c, a.grouptype__c, a.groupdate__c, a.groupshell__c, a.groupname__c, a.job_id, a.load_data_timestamp, a.epoc, a.year, a.month, a.day FROM bd_db.stg_crm_opportunity a left join bd_db.stg_crm_opportunity_cdc b on a.id=b.id where b.id is null');
insert into vv_db.processdriver values('CDC_crm_opportunity','original_file_path','s3a://vv-qa-emr-cluster/data/staging/crm/stg_crm_opportunity');

insert into vv_db.processdriver values('CDC_crm_selected_category','temp_file_path','s3a://vv-qa-emr-cluster/data/landing/crm/stg_crm_selected_category');
insert into vv_db.processdriver values('CDC_crm_selected_category','incr_table_query','select * from bd_db.stg_crm_selected_category_cdc');
insert into vv_db.processdriver values('CDC_crm_selected_category','main_table_query','select * from bd_db.stg_crm_selected_category');
Insert into vv_db.processdriver(processname, variablename, value) values ('CDC_crm_selected_category','subtract_query','SELECT a.id, a.isdeleted, a.name, a.currencyisocode, a.createddate, a.createdbyid, a.lastmodifieddate, a.lastmodifiedbyid, a.systemmodstamp, a.lastactivitydate, a.reservation__c, a.scberthedcatcode__c, a.scpricedcatcode__c, a.scdecknumber__c, a.scabinnumber__c, a.scmaxoccupancy__c, a.job_id, a.load_data_timestamp, a.epoc, a.year, a.month, a.day FROM bd_db.stg_crm_selected_category a left join bd_db.stg_crm_selected_category_cdc b on a.id=b.id where b.id is null');
insert into vv_db.processdriver values('CDC_crm_selected_category','original_file_path','s3a://vv-qa-emr-cluster/data/staging/crm/stg_crm_selected_category');

insert into vv_db.processdriver values('CDC_crm_travel_party_member','temp_file_path','s3a://vv-qa-emr-cluster/data/landing/crm/stg_crm_travel_party_member');
insert into vv_db.processdriver values('CDC_crm_travel_party_member','main_table_query','select * from bd_db.stg_crm_travel_party_member');
insert into vv_db.processdriver values('CDC_crm_travel_party_member','incr_table_query','select * from bd_db.stg_crm_travel_party_member_cdc');
insert into vv_db.processdriver values('CDC_crm_travel_party_member','subtract_query','SELECT a.id, a.isdeleted, a.name, a.currencyisocode, a.createddate, a.createdbyid, a.lastmodifieddate, a.lastmodifiedbyid, a.systemmodstamp, a.lastactivitydate, a.booking_id__c, a.sailor_id__c, a.sequence_number__c, a.quote_id__c, a.isprimary__c, a.parent_reservation__c, a.sailorstatus__c, a.voyageid__c, a.gdrepeatgindicator__c, a.gdsfarecode__c, a.gdgroupcode__c, a.insurancecode__c, a.spackagetypecode__c, a.scruisepackagecode__c, a.check_in_status_flag__c, a.checkedin__c, a.guesttype__c, a.job_id, a.load_data_timestamp, a.epoc, a.year, a.month, a.day FROM bd_db.stg_crm_travel_party_member a left join bd_db.stg_crm_travel_party_member_cdc b on a.id=b.id where b.id is null');
insert into vv_db.processdriver values('CDC_crm_travel_party_member','original_file_path','s3a://vv-qa-emr-cluster/data/staging/crm/stg_crm_travel_party_member');

insert into vv_db.processdriver values('CDC_crm_travel_with','temp_file_path','s3a://vv-qa-emr-cluster/data/landing/crm/stg_crm_travel_with');
insert into vv_db.processdriver values('CDC_crm_travel_with','incr_table_query','select * from bd_db.stg_crm_travel_with_cdc');
insert into vv_db.processdriver values('CDC_crm_travel_with','main_table_query','select * from bd_db.stg_crm_travel_with');
insert into vv_db.processdriver values('CDC_crm_travel_with','subtract_query','SELECT a.id, a.isdeleted, a.name, a.currencyisocode, a.createddate, a.createdbyid, a.lastmodifieddate, a.lastmodifiedbyid, a.systemmodstamp, a.lastvieweddate, a.lastreferenceddate, a.linktypecode__c, a.relation__c, a.masterreservation__c, a.reservationid__c, a.type__c, a.reservationnumber__c, a.primarysailor__c, a.job_id, a.load_data_timestamp, a.epoc, a.year, a.month, a.day FROM bd_db.stg_crm_travel_with a left join bd_db.stg_crm_travel_with_cdc b on a.id=b.id where b.id is null');
insert into vv_db.processdriver values('CDC_crm_travel_with','original_file_path','s3a://vv-qa-emr-cluster/data/staging/crm/stg_crm_travel_with');

insert into vv_db.processdriver values('CDC_crm_voyage','temp_file_path','s3a://vv-qa-emr-cluster/data/landing/crm/stg_crm_voyage');
insert into vv_db.processdriver values('CDC_crm_voyage','incr_table_query','select * from bd_db.stg_crm_voyage_cdc');
insert into vv_db.processdriver values('CDC_crm_voyage','main_table_query','select * from bd_db.stg_crm_voyage');
insert into vv_db.processdriver values('CDC_crm_voyage','subtract_query','SELECT a.id, a.ownerid, a.isdeleted, a.name, a.currencyisocode, a.createddate, a.createdbyid, a.lastmodifieddate, a.lastmodifiedbyid, a.systemmodstamp, a.lastvieweddate, a.lastreferenceddate, a.voyageid__c, a.nameofvoyage__c, a.onlinecheckindate__c, a.dport__c, a.aport__c, a.description__c, a.activityopendate__c, a.edate__c, a.sdate__c, a.activevoyagemessages__c, a.job_id, a.load_data_timestamp, a.epoc, a.year, a.month, a.day FROM bd_db.stg_crm_voyage a left join bd_db.stg_crm_voyage_cdc b on a.id=b.id where b.id is null');
insert into vv_db.processdriver values('CDC_crm_voyage','original_file_path','s3a://vv-qa-emr-cluster/data/staging/crm/stg_crm_voyage');

insert into vv_db.processdriver values('CDC_crm_voyage_message','temp_file_path','s3a://vv-qa-emr-cluster/data/landing/crm/stg_crm_voyage_message');
insert into vv_db.processdriver values('CDC_crm_voyage_message','incr_table_query','select * from bd_db.stg_crm_voyage_message_cdc');
insert into vv_db.processdriver values('CDC_crm_voyage_message','main_table_query','select * from bd_db.stg_crm_voyage_message');
insert into vv_db.processdriver values('CDC_crm_voyage_message','subtract_query','SELECT a.id, a.isdeleted, a.name, a.currencyisocode, a.createddate, a.createdbyid, a.lastmodifieddate, a.lastmodifiedbyid, a.systemmodstamp, a.message__c, a.active__c, a.voyage__c, a.title__c, a.job_id, a.load_data_timestamp, a.epoc, a.year, a.month, a.day FROM bd_db.stg_crm_voyage_message a left join bd_db.stg_crm_voyage_message_cdc b on a.id=b.id where b.id is null');
insert into vv_db.processdriver values('CDC_crm_voyage_message','original_file_path','s3a://vv-qa-emr-cluster/data/staging/crm/stg_crm_voyage_message');

insert into vv_db.processdriver values('CDC_crm_lead','temp_file_path','s3a://vv-qa-emr-cluster/data/landing/crm/stg_crm_lead');
insert into vv_db.processdriver values('CDC_crm_lead','main_table_query','select * from bd_db.stg_crm_lead');
insert into vv_db.processdriver values('CDC_crm_lead','incr_table_query','select * from bd_db.stg_crm_lead_cdc');
insert into vv_db.processdriver values('CDC_crm_lead','subtract_query','SELECT a.id, a.isdeleted, a.masterrecordid, a.lastname, a.firstname, a.salutation, a.middlename, a.suffix, a.name, a.title, a.company, a.street, a.city, a.state, a.postalcode, a.country, a.statecode, a.countrycode, a.latitude, a.longitude, a.geocodeaccuracy, a.address, a.phone, a.mobilephone, a.email, a.website, a.photourl, a.leadsource, a.status, a.industry, a.rating, a.currencyisocode, a.numberofemployees, a.ownerid, a.hasoptedoutofemail, a.isconverted, a.converteddate, a.convertedaccountid, a.convertedcontactid, a.convertedopportunityid, a.isunreadbyowner, a.createddate, a.createdbyid, a.lastmodifieddate, a.lastmodifiedbyid, a.systemmodstamp, a.lastactivitydate, a.lastvieweddate, a.lastreferenceddate, a.jigsaw, a.jigsawcontactid, a.emailbouncedreason, a.emailbounceddate, a.et4ae5__hasoptedoutofmobile__c, a.et4ae5__mobile_country_code__c, a.sfssdupecatcher__override_dupecatcher__c, a.db_created_date_without_time__c, a.db_lead_age__c, a.job_id, a.load_data_timestamp, a.epoc, a.year, a.month, a.day FROM bd_db.stg_crm_lead a left join bd_db.stg_crm_lead_cdc b on a.id=b.id where b.id is null');
insert into vv_db.processdriver values('CDC_crm_lead','original_file_path','s3a://vv-qa-emr-cluster/data/staging/crm/stg_crm_lead');

insert into vv_db.processdriver values('CDC_crm_user','temp_file_path','s3a://vv-qa-emr-cluster/data/landing/crm/stg_crm_user');
insert into vv_db.processdriver values('CDC_crm_user','incr_table_query','select * from bd_db.stg_crm_user_cdc');
insert into vv_db.processdriver values('CDC_crm_user','subtract_query','SELECT a.id, a.username, a.lastname, a.firstname, a.middlename, a.suffix, a.name, a.companyname, a.division, a.department, a.title, a.street, a.city, a.state, a.postalcode, a.country, a.statecode, a.countrycode, a.latitude, a.longitude, a.geocodeaccuracy, a.address, a.email, a.emailpreferencesautobcc, a.emailpreferencesautobccstayintouch, a.emailpreferencesstayintouchreminder, a.senderemail, a.sendername, a.signature, a.stayintouchsubject, a.stayintouchsignature, a.stayintouchnote, a.phone, a.fax, a.mobilephone, a.alias, a.communitynickname, a.badgetext, a.isactive, a.timezonesidkey, a.userroleid, a.localesidkey, a.receivesinfoemails, a.receivesadmininfoemails, a.emailencodingkey, a.defaultcurrencyisocode, a.currencyisocode, a.profileid, a.usertype, a.languagelocalekey, a.employeenumber, a.delegatedapproverid, a.managerid, a.lastlogindate, a.lastpasswordchangedate, a.createddate, a.createdbyid, a.lastmodifieddate, a.lastmodifiedbyid, a.systemmodstamp, a.offlinetrialexpirationdate, a.offlinepdatrialexpirationdate, a.userpermissionsmarketinguser, a.userpermissionsofflineuser, a.userpermissionsavantgouser, a.userpermissionscallcenterautologin, a.userpermissionsmobileuser, a.userpermissionssfcontentuser, a.userpermissionsknowledgeuser, a.userpermissionsinteractionuser, a.userpermissionssupportuser, a.userpermissionsliveagentuser, a.forecastenabled, a.userpreferencesactivityreminderspopup, a.userpreferenceseventreminderscheckboxdefault, a.userpreferencestaskreminderscheckboxdefault, a.userpreferencesremindersoundoff, a.userpreferencesdisableallfeedsemail, a.userpreferencesdisablefollowersemail, a.userpreferencesdisableprofilepostemail, a.userpreferencesdisablechangecommentemail, a.userpreferencesdisablelatercommentemail, a.userpreferencesdisprofpostcommentemail, a.userpreferencesapexpagesdevelopermode, a.userpreferenceshidecsngetchattermobiletask, a.userpreferencesdisablementionspostemail, a.userpreferencesdismentionscommentemail, a.userpreferenceshidecsndesktoptask, a.userpreferenceshidechatteronboardingsplash, a.userpreferenceshidesecondchatteronboardingsplash, a.userpreferencesdiscommentafterlikeemail, a.userpreferencesdisablelikeemail, a.userpreferencessortfeedbycomment, a.userpreferencesdisablemessageemail, a.userpreferencesdisablebookmarkemail, a.userpreferencesdisablesharepostemail, a.userpreferencesenableautosubforfeeds, a.userpreferencesdisablefilesharenotificationsforapi, a.userpreferencesshowtitletoexternalusers, a.userpreferencesshowmanagertoexternalusers, a.userpreferencesshowemailtoexternalusers, a.userpreferencesshowworkphonetoexternalusers, a.userpreferencesshowmobilephonetoexternalusers, a.userpreferencesshowfaxtoexternalusers, a.userpreferencesshowstreetaddresstoexternalusers, a.userpreferencesshowcitytoexternalusers, a.userpreferencesshowstatetoexternalusers, a.userpreferencesshowpostalcodetoexternalusers, a.userpreferencesshowcountrytoexternalusers, a.userpreferencesshowprofilepictoguestusers, a.userpreferencesshowtitletoguestusers, a.userpreferencesshowcitytoguestusers, a.userpreferencesshowstatetoguestusers, a.userpreferencesshowpostalcodetoguestusers, a.userpreferencesshowcountrytoguestusers, a.userpreferenceshides1browserui, a.userpreferencesdisableendorsementemail, a.userpreferencespathassistantcollapsed, a.userpreferencescachediagnostics, a.userpreferencesshowemailtoguestusers, a.userpreferencesshowmanagertoguestusers, a.userpreferencesshowworkphonetoguestusers, a.userpreferencesshowmobilephonetoguestusers, a.userpreferencesshowfaxtoguestusers, a.userpreferencesshowstreetaddresstoguestusers, a.userpreferenceslightningexperiencepreferred, a.userpreferencespreviewlightning, a.userpreferenceshideenduseronboardingassistantmodal, a.userpreferenceshidelightningmigrationmodal, a.userpreferenceshidesfxwelcomemat, a.userpreferenceshidebiggerphotocallout, a.userpreferencesglobalnavbarwtshown, a.userpreferencesglobalnavgridmenuwtshown, a.userpreferencescreatelexappswtshown, a.userpreferencesfavoriteswtshown, a.contactid, a.accountid, a.callcenterid, a.extension, a.portalrole, a.isportalenabled, a.federationidentifier, a.aboutme, a.fullphotourl, a.smallphotourl, a.mediumphotourl, a.digestfrequency, a.defaultgroupnotificationfrequency, a.lastvieweddate, a.lastreferenceddate, a.bannerphotourl, a.smallbannerphotourl, a.mediumbannerphotourl, a.isprofilephotoactive, a.actual_sales_to_date__c, a.difference__c, a.sales_target__c, a.is_manager__c, a.et4ae5__default_et_page__c, a.et4ae5__default_mid__c, a.et4ae5__exacttargetforappexchangeadmin__c, a.et4ae5__exacttargetforappexchangeuser__c, a.et4ae5__exacttargetusername__c, a.et4ae5__exacttarget_oauth_token__c, a.et4ae5__validexacttargetadmin__c, a.et4ae5__validexacttargetuser__c, a.icagentconsole__inccustomscreenpop__c, a.db_region__c, a.facebook_email__c, a.facebook_id__c, a.job_id, a.load_data_timestamp, a.epoc, a.year, a.month, a.day FROM bd_db.stg_crm_user a left join bd_db.stg_crm_user_cdc b on a.id=b.id where b.id is null');
insert into vv_db.processdriver values('CDC_crm_user','main_table_query','select * from bd_db.stg_crm_user');
insert into vv_db.processdriver values('CDC_crm_user','original_file_path','s3a://vv-qa-emr-cluster/data/staging/crm/stg_crm_user');

create database bd_db;
CREATE EXTERNAL TABLE bd_db.stg_crm_address(
Id string,
OwnerId string ,
IsDeleted boolean ,
Name string ,
CurrencyIsoCode string ,
CreatedDate TIMESTAMP,
CreatedById string ,
LastModifiedDate  TIMESTAMP,
LastModifiedById string ,
SystemModstamp TIMESTAMP,
Primary__c boolean ,
StreetNmbr__c string ,
AddLine__c string ,
CityName__c string ,
PostalCode__c string ,
County__c string,
StateCode__c string ,
CountryCode__c string ,
Sailor__c string,
AddressUniqueID__c string, 
job_id   string,
load_data_timestamp   timestamp,
epoc      bigint,
year int, 
month int,
day int
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY '\t'
LINES TERMINATED BY '\n'
stored as TEXTFILE
Location "s3://vv-qa-emr-cluster/data/staging/crm/stg_crm_address"
;

CREATE EXTERNAL TABLE bd_db.stg_crm_travel_with(
Id string,
IsDeleted boolean,
Name string,
CurrencyIsoCode string ,
CreatedDate timestamp ,
CreatedById string,
LastModifiedDate timestamp ,
LastModifiedById string,
SystemModstamp timestamp ,
LastViewedDate timestamp ,
LastReferencedDate timestamp ,
LinkTypeCode__c double ,
Relation__c double ,
MasterReservation__c string,
ReservationID__c string ,
Type__c double ,
ReservationNumber__c string ,
PrimarySailor__c string ,
job_id   string,
load_data_timestamp   timestamp,
epoc      bigint,
year int, 
month int,
day int
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY '\t'
LINES TERMINATED BY '\n'
stored as TEXTFILE
Location "s3://vv-qa-emr-cluster/data/staging/crm/stg_crm_travel_with"
; 

CREATE EXTERNAL TABLE bd_db.stg_crm_voyage (
Id string,
OwnerId string,
IsDeleted boolean,
Name string,
CurrencyIsoCode string,
CreatedDate timestamp,
CreatedById string,
LastModifiedDate timestamp ,
LastModifiedById string,
SystemModstamp timestamp ,
LastViewedDate timestamp ,
LastReferencedDate timestamp ,
VoyageID__c string,
NameOfVoyage__c string,
OnlineCheckInDate__c timestamp ,
dPort__c string,
aPort__c string,
Description__c string,
ActivityOpenDate__c timestamp ,
eDate__c timestamp ,
sDate__c timestamp ,
ActiveVoyageMessages__c double ,
job_id   string,
load_data_timestamp   timestamp,
epoc      bigint,
year int, 
month int,
day int
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY '\t'
LINES TERMINATED BY '\n'
stored as TEXTFILE
Location "s3://vv-qa-emr-cluster/data/staging/crm/stg_crm_voyage"
;

CREATE EXTERNAL TABLE bd_db.stg_crm_selected_category (
Id string ,
IsDeleted boolean ,
Name string,
CurrencyIsoCode string,
CreatedDate timestamp ,
CreatedById string ,
LastModifiedDate timestamp ,
LastModifiedById string ,
SystemModstamp timestamp ,
LastActivityDate timestamp ,
Reservation__c string ,
SCBerthedCatCode__c string,
SCPricedCatCode__c string,
SCDeckNumber__c string,
SCabinNumber__c string,
SCMaxOccupancy__c string ,
job_id   string,
load_data_timestamp   timestamp,
epoc      bigint,
year int, 
month int,
day int
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY '\t'
LINES TERMINATED BY '\n'
stored as TEXTFILE
Location "s3://vv-qa-emr-cluster/data/staging/crm/stg_crm_selected_category"
; 

CREATE EXTERNAL TABLE bd_db.stg_crm_voyage_message (
Id string,
IsDeleted boolean,
Name string,
CurrencyIsoCode string,
CreatedDate timestamp,
CreatedById string,
LastModifiedDate timestamp,
LastModifiedById string,
SystemModstamp timestamp,
Message__c string,
Active__c boolean,
Voyage__c string,
Title__c string,
job_id   string,
load_data_timestamp   timestamp,
epoc      bigint,
year int, 
month int,
day int
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY '\t'
LINES TERMINATED BY '\n'
stored as TEXTFILE
Location "s3://vv-qa-emr-cluster/data/staging/crm/stg_crm_voyage_message"
; 

CREATE  EXTERNAL TABLE bd_db.stg_crm_contact_details (
Id string,
OwnerId string,
IsDeleted boolean ,
Name string,
CurrencyIsoCode string,
CreatedDate timestamp ,
CreatedById string,
LastModifiedDate timestamp ,
LastModifiedById string,
SystemModstamp timestamp ,
Primary__c boolean ,
PLocationType__c double,
CountryCode__c string,
AreaCityCode__c string,
PhoneNumber__c string,
Extension__c string,
Sailor__c string,
ConDetailUniqueID__c string,
EmergencyFlag__c boolean ,
job_id   string,
load_data_timestamp   timestamp,
epoc      bigint,
year int, 
month int,
day int
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY '\t'
LINES TERMINATED BY '\n'
stored as TEXTFILE
Location "s3://vv-qa-emr-cluster/data/staging/crm/stg_crm_contact_details"
;

CREATE EXTERNAL TABLE bd_db.stg_crm_campaign (
Id string,
IsDeleted boolean ,
Name string,
ParentId string,
Type string,
Status string,
StartDate timestamp,
EndDate timestamp,
CurrencyIsoCode string,
ExpectedRevenue decimal(18,0) ,
BudgetedCost decimal(18,0) ,
ActualCost decimal(18,0) ,
ExpectedResponse double,
NumberSent double,
IsActive boolean ,
Description string,
NumberOfLeads int,
NumberOfConvertedLeads int ,
NumberOfContacts int ,
NumberOfResponses int ,
NumberOfOpportunities int ,
NumberOfWonOpportunities int ,
AmountAllOpportunities decimal(18,0) ,
AmountWonOpportunities decimal(18,0) ,
HierarchyNumberOfLeads int ,
HierarchyNumberOfConvertedLeads int ,
HierarchyNumberOfContacts int ,
HierarchyNumberOfResponses int ,
HierarchyNumberOfWonOpportunities int ,
HierarchyNumberSent double,
HierarchyExpectedRevenue decimal(18,0) ,
HierarchyActualCost decimal(18,0) ,
OwnerId string,
CreatedDate timestamp ,
CreatedById string,
LastModifiedDate timestamp ,
LastModifiedById string,
SystemModstamp timestamp ,
LastActivityDate timestamp ,
LastViewedDate timestamp ,
LastReferencedDate timestamp ,
CampaignMemberRecordTypeId string,
Campaign_Channel__c string,
Campaign_Country__c string,
Campaign_Office__c string ,
Campaign_Region__c string ,
Coupon_Code__c string ,
Coupon_Description__c string,
Coupon_Name__c string ,
Plan_Code__c string ,
Segment_Code__c string ,
Variation_Code__c string ,
Plan_Name__c string ,
Campaign_Brand__c string,
Campaign_Code__c string ,
Coupon_Activation_Date__c timestamp ,
Coupon_Expiration_Date__c timestamp ,
Program_Code__c string ,
Program_Name__c string ,
Sub_Plan_Code__c string ,
Sub_Plan_Name__c string ,
Treatment_Activation_Date__c timestamp ,
Treatment_Code__c string ,
Treatment_Description__c string,
Treatment_Expiration_Date__c timestamp ,
Treatment_Name__c string ,
Treatment_Type__c string,
Wave_Code__c string ,
Opportunity__c string,
VoyageSpecific__c boolean ,
Voyage__c string,
CampaignId__c string,
DB_Campaign_Tactic__c string,
job_id   string,
load_data_timestamp   timestamp,
epoc      bigint,
year int, 
month int,
day int
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY '\t'
LINES TERMINATED BY '\n'
stored as TEXTFILE
Location "s3://vv-qa-emr-cluster/data/staging/crm/stg_crm_campaign"
;

CREATE EXTERNAL TABLE bd_db.stg_crm_lead (
Id string ,
IsDeleted boolean ,
MasterRecordId string ,
LastName string ,
FirstName string ,
Salutation string ,
MiddleName string ,
Suffix string ,
Name string ,
Title string ,
Company string ,
Street string ,
City string ,
State string ,
PostalCode string ,
Country string ,
StateCode string ,
CountryCode string ,
Latitude double ,
Longitude double ,
GeocodeAccuracy string ,
Address string ,
Phone string ,
MobilePhone string ,
Email string ,
Website string ,
PhotoUrl string ,
LeadSource string ,
Status string ,
Industry string ,
Rating string ,
CurrencyIsoCode string ,
NumberOfEmployees int ,
OwnerId string ,
HasOptedOutOfEmail boolean,
IsConverted boolean ,
ConvertedDate timestamp ,
ConvertedAccountId string ,
ConvertedContactId string ,
ConvertedOpportunityId string ,
IsUnreadByOwner boolean ,
CreatedDate timestamp ,
CreatedById string ,
LastModifiedDate timestamp ,
LastModifiedById string ,
SystemModstamp timestamp ,
LastActivityDate timestamp ,
LastViewedDate timestamp ,
LastReferencedDate timestamp ,
Jigsaw string ,
JigsawContactId string ,
EmailBouncedReason string ,
EmailBouncedDate timestamp ,
et4ae5__HasOptedOutOfMobile__c boolean,
et4ae5__Mobile_Country_Code__c string ,
SFSSDupeCatcher__Override_DupeCatcher__c boolean ,
DB_Created_Date_without_Time__c timestamp ,
DB_Lead_Age__c double,
job_id   string,
load_data_timestamp   timestamp,
epoc      bigint,
year int, 
month int,
day int
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY '\t'
LINES TERMINATED BY '\n'
stored as TEXTFILE
Location "s3://vv-qa-emr-cluster/data/staging/crm/stg_crm_lead"
;

CREATE EXTERNAL TABLE bd_db.stg_crm_booking_payments (
Id string,
IsDeleted boolean,
Name string,
CurrencyIsoCode string,
CreatedDate timestamp ,
CreatedById string,
LastModifiedDate timestamp ,
LastModifiedById string ,
SystemModstamp timestamp ,
LastViewedDate timestamp ,
LastReferencedDate timestamp ,
Booking_ID__c string ,
Payment_Amount__c decimal(18,2) ,
PaymentCode__c double,
Payment_Type__c string,
Quote_ID__c string ,
Payment_Date__c timestamp ,
Preferred_Currency__c string,
Preferred_Currency_Amount__c decimal(18,0) ,
job_id   string,
load_data_timestamp   timestamp,
epoc      bigint,
year int, 
month int,
day int
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY '\t'
LINES TERMINATED BY '\n'
stored as TEXTFILE
Location "s3://vv-qa-emr-cluster/data/staging/crm/stg_crm_booking_payments"
;

CREATE EXTERNAL TABLE bd_db.stg_crm_bookable_activities (
Id string ,
IsDeleted boolean ,
Name string,
CurrencyIsoCode string ,
CreatedDate timestamp ,
CreatedById string ,
LastModifiedDate timestamp ,
LastModifiedById string ,
SystemModstamp timestamp ,
Booking_ID__c string ,
eDate__c timestamp ,
Duration__c string ,
Bookable_Activity_ID__c string,
Description__c string ,
Travel_Party_Member__c string ,
Activity_Date__c timestamp ,
Category__c string ,
CruisePackageCode__c string,
BKUniqueID__c string,
Location__c string,
Internal_Code__c string,
PackageSubType__c string,
PackageTypeCode__c string,
sDate__c timestamp ,
job_id   string,
load_data_timestamp   timestamp,
epoc      bigint,
year int, 
month int,
day int
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY '\t'
LINES TERMINATED BY '\n'
stored as TEXTFILE
Location "s3://vv-qa-emr-cluster/data/staging/crm/stg_crm_bookable_activities"
;
CREATE EXTERNAL TABLE bd_db.stg_crm_household (
Id string,
OwnerId string,
IsDeleted boolean ,
Name string ,
CurrencyIsoCode string ,
CreatedDate timestamp ,
CreatedById string,
LastModifiedDate timestamp ,
LastModifiedById string,
SystemModstamp timestamp ,
LastViewedDate timestamp ,
LastReferencedDate timestamp ,
Number_of_Household_Members__c double,
Household_Address_Postal_Code__c string,
Household_Address_State__c string,
Primary_Sailor__c string,
Seaware_Household_ID__c string ,
Status__c string,
Total_Lifetime_Cruise_Nights__c double,
Household_Address_Line_2__c string,
Total_OBS_Amount__c decimal(18,2) ,
Household_Address_City__c string,
Average_Lifetime_Spend_Per_Night__c decimal(18,2) ,
Average_Spend_Per_Night_for_Last_Cruise__c decimal(18,2) ,
Total_Lifetime_Spend__c decimal(18,2) ,
Household_Address_Line_1__c string ,
job_id   string,
load_data_timestamp   timestamp,
epoc      bigint,
year int, 
month int,
day int
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY '\t'
LINES TERMINATED BY '\n'
stored as TEXTFILE
Location "s3://vv-qa-emr-cluster/data/staging/crm/stg_crm_household"
;
CREATE EXTERNAL TABLE bd_db.stg_crm_case (
Id string,
IsDeleted boolean ,
CaseNumber string,
ContactId string,
AccountId string ,
EntitlementId string ,
SourceId string ,
ParentId string ,
SuppliedName string ,
SuppliedEmail string ,
SuppliedPhone string ,
SuppliedCompany string ,
Type string ,
RecordTypeId string ,
Status string ,
Reason string ,
Origin string ,
Subject string ,
Priority string ,
Description string ,
IsClosed boolean ,
ClosedDate timestamp ,
IsEscalated boolean ,
CurrencyIsoCode string ,
OwnerId string ,
CreatedDate timestamp ,
CreatedById string ,
LastModifiedDate timestamp ,
LastModifiedById string ,
SystemModstamp timestamp ,
ContactPhone string ,
ContactMobile string ,
ContactEmail string ,
ContactFax string ,
LastViewedDate timestamp ,
LastReferencedDate timestamp ,
Opportunity__c string ,
Booked_Activities__c string ,
Booking_Payments__c string ,
Category__c string ,
Sub_Category__c string ,
CaseSubReason__c string ,
Link__c string ,
Voyage__c string ,
Transferred_to__c string ,
Escalation_Reason__c string ,
Description__c string ,
WebFName__c string ,
Last_Interaction_Date__c timestamp ,
WebLName__c string ,
Case_Resolution__c string ,
Sailor_Email__c string ,
Sailor_Name__c string ,
job_id string,
load_data_timestamp timestamp,
epoc    bigint,
year int, 
month int,
day int
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY '\t'
LINES TERMINATED BY '\n'
stored as TEXTFILE
Location "s3://vv-qa-emr-cluster/data/staging/crm/stg_crm_case"
;
CREATE EXTERNAL TABLE bd_db.stg_crm_contact (
Id string ,
IsDeleted boolean ,
MasterRecordId string ,
AccountId string ,
IsPersonAccount boolean ,
LastName string ,
FirstName string ,
Salutation string ,
MiddleName string ,
Suffix string ,
Name string ,
RecordTypeId string ,
MailingStreet string ,
MailingCity string ,
MailingState string ,
MailingPostalCode string ,
MailingCountry string ,
MailingStateCode string ,
MailingCountryCode string ,
MailingLatitude double ,
MailingLongitude double ,
MailingGeocodeAccuracy string ,
MailingAddress string ,
Phone string ,
Fax string ,
MobilePhone string ,
ReportsToId string ,
Email string ,
Title string ,
Department string ,
Birthdate timestamp ,
CurrencyIsoCode string ,
OwnerId string ,
CreatedDate timestamp ,
CreatedById string ,
LastModifiedDate timestamp ,
LastModifiedById string ,
SystemModstamp timestamp ,
LastActivityDate timestamp ,
LastCURequestDate timestamp ,
LastCUUpdateDate timestamp ,
LastViewedDate timestamp ,
LastReferencedDate timestamp ,
EmailBouncedReason string ,
EmailBouncedDate timestamp ,
IsEmailBounced boolean ,
PhotoUrl string ,
Jigsaw string ,
JigsawContactId string ,
Is_Primary_Contact__c boolean ,
SFSSDupeCatcher__Override_DupeCatcher__c boolean ,
Gender__c string ,
IATAN_Company_Name__c string ,
IATAN_Holder_Name__c string ,
IATAN_Number__c double,
Agent_Type__c string ,
Preferred_Language__c string ,
Seaware_Agent_ID__c string ,
Status__c boolean ,
Suffix__c string ,
Target_Revenue__c decimal,
Total_Revenue__c decimal,
Agent_Status__c string ,
Alternate_Name__c string,
Anniversary_Date__c timestamp ,
et4ae5__HasOptedOutOfMobile__c boolean ,
et4ae5__Mobile_Country_Code__c string ,
IATANExpDate__c timestamp ,
Marital_Status__c string ,
T_C_Consent_First_Name__c string,
T_C_Consent_Last_Name__c string,
Passport_Exp_Date__c timestamp ,
Passport_Number__c string ,
T_C_Consent_Date__c timestamp ,
Sales_Commission__c double,
Sales_Commission_Amount__c decimal,
job_id   string,
load_data_timestamp   timestamp,
epoc      bigint,
year int, 
month int,
day int
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY '\t'
LINES TERMINATED BY '\n'
stored as TEXTFILE
Location "s3://vv-qa-emr-cluster/data/staging/crm/stg_crm_contact"
;

CREATE EXTERNAL TABLE bd_db.stg_crm_travel_party_member (
Id string,
IsDeleted string,
Name string,
CurrencyIsoCode string,
CreatedDate timestamp,
CreatedById string,
LastModifiedDate timestamp,
LastModifiedById string,
SystemModstamp timestamp,
LastActivityDate timestamp,
Booking_ID__c string,
Sailor_ID__c string,
Sequence_Number__c string,
Quote_ID__c string,
IsPrimary__c string,
Parent_Reservation__c string,
SailorStatus__c string,
VoyageID__c string,
GDRepeatGIndicator__c string,
GDSFareCode__c string,
GDGroupCode__c string,
InsuranceCode__c string,
SPackageTypeCode__c string,
SCruisePackageCode__c string,
Check_In_Status_Flag__c string,
CheckedIn__c string,
GuestType__c string,
job_id string,
load_data_timestamp timestamp,
epoc bigint,
year int, 
month int,
day int
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY '\t'
LINES TERMINATED BY '\n'
stored as TEXTFILE
Location "s3://vv-qa-emr-cluster/data/staging/crm/stg_crm_travel_party_member"
;

CREATE EXTERNAL TABLE bd_db.stg_crm_account (
Id string,
IsDeleted boolean,
MasterRecordId string,
Name string,
LastName string,
FirstName string,
Salutation string,
MiddleName string,
Suffix string,
Type string,
RecordTypeId string,
ParentId string,
BillingStreet string,
BillingCity string,
BillingState string,
BillingPostalCode string,
BillingCountry string,
BillingStateCode string,
BillingCountryCode string,
BillingLatitude double,
BillingLongitude double,
BillingGeocodeAccuracy string,
BillingAddress string,
ShippingStreet string,
ShippingCity string,
ShippingState string,
ShippingPostalCode string,
ShippingCountry string,
ShippingStateCode string,
ShippingCountryCode string,
ShippingLatitude double,
ShippingLongitude double,
ShippingGeocodeAccuracy string,
ShippingAddress string,
Phone string,
Website string,
PhotoUrl string,
Industry string,
NumberOfEmployees int,
Description string,
CurrencyIsoCode string,
OwnerId string,
CreatedDate timestamp,
CreatedById string,
LastModifiedDate timestamp,
LastModifiedById string,
SystemModstamp timestamp,
LastActivityDate timestamp,
LastViewedDate timestamp,
LastReferencedDate timestamp,
IsPartner boolean,
IsCustomerPortal boolean,
PersonContactId string,
IsPersonAccount boolean,
PersonMailingStreet string,
PersonMailingCity string,
PersonMailingState string,
PersonMailingPostalCode string,
PersonMailingCountry string,
PersonMailingStateCode string,
PersonMailingCountryCode string,
PersonMailingLatitude double,
PersonMailingLongitude double,
PersonMailingGeocodeAccuracy string,
PersonMailingAddress string,
PersonMobilePhone string,
PersonEmail string,
PersonTitle string,
PersonDepartment string,
PersonBirthdate timestamp,
PersonLastCURequestDate timestamp,
PersonLastCUUpdateDate timestamp,
PersonEmailBouncedReason string,
PersonEmailBouncedDate timestamp,
Jigsaw string,
JigsawCompanyId string,
AccountSource string,
SicDesc string,
ARC_Number__c string,
Agency_Code__c string,
Primary_Contact_Email__c string,
Instagram__c string,
SailorID__c string,
SFSSDupeCatcher__Override_DupeCatcher__c boolean,
CLIA_Number__c string,
Citizenship_Country__c string,
Client_ID__c string,
Country_of_Residence__c string,
MagnoliaPassword__c string,
Household_ID__c string,
IATA_Number__c string,
Inbound__c boolean,
PseudoCityCode__c string,
Age__c double,
Tribe__c string,
Number_of_Active_Agents__c double,
Occupation__c string,
Office_Code__c string,
Outbound_Email__c boolean,
Outbound__c boolean,
Preferred_Name__c string,
Seaware_Agency_ID__c string,
Status__c string,
Taxpayer_ID__c string,
Taxpayer_Type__c string,
Total_Lifetime_Cruise_Nights__c double,
Consortium__c boolean,
Total_Revenue__c decimal,
Web_Address__c string,
Abta_Number__c string,
Preferred_Gender__c string,
Yelp__c string,
Facebook__c string,
Twitter__c string,
Snapchat__c string,
Subtribe__c string,
No_Social_Contact__c boolean,
State_of_the_Sailor__c string,
Data_Source__c string,
W9_Form_Received__c boolean,
Cover_Letter_Received__c boolean,
Business_License__c boolean,
Business_License_Type__c string,
GDLoyalLevel__c string,
Average_Lifetime_Spend_Per_Night__c decimal,
Average_Spend_Per_Night_for_Last_Cruise__c decimal,
Total_Lifetime_Spend__c decimal,
Registered_for_Web__c boolean,
Downloaded_Mobile_App__c boolean,
VXP_ID__c string,
GDLoyalLevelCode__c string,
Consortium_Type__c string,
Floating_Deposit__c boolean,
Secured_Fax_Email__c boolean,
IsGSA__c boolean,
IsInternal__c boolean,
IsWhiteLabel__c boolean,
TaxOwner__c string,
SNPrefix__c string,
InactiveReason__c string,
Asta_Number__c string,
isMasterXref__c boolean,
T_C_Consent_Date__c timestamp,
T_C_Consent_First_Name__c string,
T_C_Consent_Last_Name__c string,
GroupName__c string,
GroupLeader__c string,
Is_Primary_Contact__pc boolean,
SFSSDupeCatcher__Override_DupeCatcher__pc boolean,
Gender__pc string,
IATAN_Company_Name__pc string,
IATAN_Holder_Name__pc string,
IATAN_Number__pc double,
Agent_Type__pc string,
Preferred_Language__pc string,
Seaware_Agent_ID__pc string,
Status__pc boolean,
Suffix__pc string,
Target_Revenue__pc decimal,
Total_Revenue__pc decimal,
Agent_Status__pc string,
Alternate_Name__pc string,
Anniversary_Date__pc timestamp,
et4ae5__HasOptedOutOfMobile__pc boolean,
et4ae5__Mobile_Country_Code__pc string,
IATANExpDate__pc timestamp,
Marital_Status__pc string,
T_C_Consent_First_Name__pc string,
T_C_Consent_Last_Name__pc string,
Passport_Exp_Date__pc timestamp,
Passport_Number__pc string,
T_C_Consent_Date__pc timestamp,
Sales_Commission__pc double,
Sales_Commission_Amount__pc decimal, 
job_id string,
load_data_timestamp timestamp,
epoc bigint,
year int, 
month int,
day int
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY '\t'
LINES TERMINATED BY '\n'
stored as TEXTFILE
Location "s3://vv-qa-emr-cluster/data/staging/crm/stg_crm_account"
;
CREATE EXTERNAL TABLE bd_db.stg_crm_opportunity (
Id string,
IsDeleted boolean,
AccountId string,
RecordTypeId string,
Name string ,
Description string ,
StageName string ,
Amount decimal ,
Probability double ,
CloseDate timestamp ,
Type string ,
NextStep string ,
LeadSource string ,
IsClosed boolean,
IsWon boolean,
ForecastCategory string ,
ForecastCategoryName string ,
CurrencyIsoCode string ,
CampaignId string,
HasOpportunityLineItem boolean,
Pricebook2Id string,
OwnerId string,
CreatedDate timestamp ,
CreatedById string,
LastModifiedDate timestamp ,
LastModifiedById string,
SystemModstamp timestamp ,
LastActivityDate timestamp ,
FiscalQuarter int ,
FiscalYear int ,
Fiscal string ,
LastViewedDate timestamp ,
LastReferencedDate timestamp ,
SyncedQuoteId string,
ContractId string,
HasOpenActivity boolean,
HasOverdueTask boolean,
Budget_Confirmed__c boolean,
Discovery_Completed__c boolean,
ROI_Analysis_Completed__c boolean,
Loss_Reason__c string ,
AgentName__c string,
SSStart__c timestamp ,
SSEnd__c timestamp ,
Booking_ID__c string ,
VoyageID__c string,
Currency__c decimal ,
SSDuration__c string ,
SSPortsofCallQuality__c string ,
Display_Tab__c string ,
Next_Payment_Date__c timestamp ,
Flight_Purchase__c string ,
Group_Id__c string ,
SSLOSDescriptionCode__c string ,
Number_of_Guests__c double ,
Number_of_Stateroom__c double ,
CLShipName__c string ,
Package_Type__c string ,
Parent_Res_ID__c string ,
Port_Name__c string ,
Post_Cruise_Transfer__c string ,
CLVendorCode__c string ,
Prepaid_Gratuities__c string ,
RegionCode__c string ,
Reservation_Number__c string ,
CruisePackageCode__c string ,
Sailing_Package__c string ,
Ship_Code__c string ,
CurrencyCode__c string ,
Status__c string ,
Vacation_Protection__c string ,
Booking_Payments_Total__c decimal ,
Seaware_Reservation_Status__c string ,
Opportunity_Amount__c decimal ,
OpportunityRevenueOwner__c string ,
Vacation_Start_Date__c timestamp ,
Record_Type__c string ,
ParentBookingId__c string,
DecimalPlaces__c string ,
BookedDate__c timestamp ,
Cabin_Category__c string ,
Disembarkation_Date__c timestamp ,
Embarkation_Date__c timestamp ,
Checked_In__c boolean,
OfferDate__c timestamp ,
Seaware_AgentID__c string ,
Init_Date__c timestamp ,
Booking_Channel__c string ,
AgencyID__c string ,
Voyage_Status__c string ,
Preferred_Currency__c string ,
DB_Competitor__c string ,
VacationEndDate__c timestamp ,
Self__c boolean,
GuestType__c string ,
AgencyName__c string,
Preferred_Currency_Amount__c decimal ,
GroupType__c string ,
GroupDate__c timestamp ,
GroupShell__c string,
GroupName__c string,
job_id string,
load_data_timestamp timestamp,
epoc bigint,
year int, 
month int,
day int
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY '\t'
LINES TERMINATED BY '\n'
stored as TEXTFILE
Location "s3://vv-qa-emr-cluster/data/staging/crm/stg_crm_opportunity"
;
CREATE EXTERNAL TABLE bd_db.stg_crm_user (
Id string ,
Username string ,
LastName string ,
FirstName string ,
MiddleName string ,
Suffix string ,
Name string ,
CompanyName string ,
Division string ,
Department string ,
Title string ,
Street string ,
City string ,
State string ,
PostalCode string ,
Country string ,
StateCode string ,
CountryCode string ,
Latitude double ,
Longitude double ,
GeocodeAccuracy string ,
Address string ,
Email string ,
EmailPreferencesAutoBcc boolean ,
EmailPreferencesAutoBccStayInTouch boolean ,
EmailPreferencesStayInTouchReminder boolean ,
SenderEmail string ,
SenderName string ,
Signature string ,
StayInTouchSubject string ,
StayInTouchSignature string ,
StayInTouchNote string ,
Phone string ,
Fax string ,
MobilePhone string ,
Alias string ,
CommunityNickname string ,
BadgeText string ,
IsActive boolean ,
TimeZoneSidKey string ,
UserRoleId string ,
LocaleSidKey string ,
ReceivesInfoEmails boolean ,
ReceivesAdminInfoEmails boolean ,
EmailEncodingKey string ,
DefaultCurrencyIsoCode string ,
CurrencyIsoCode string ,
ProfileId string ,
UserType string ,
LanguageLocaleKey string ,
EmployeeNumber string ,
DelegatedApproverId string ,
ManagerId string ,
LastLoginDate timestamp ,
LastPasswordChangeDate timestamp ,
CreatedDate timestamp ,
CreatedById string ,
LastModifiedDate timestamp ,
LastModifiedById string ,
SystemModstamp timestamp ,
OfflineTrialExpirationDate timestamp ,
OfflinePdaTrialExpirationDate timestamp ,
UserPermissionsMarketingUser boolean ,
UserPermissionsOfflineUser boolean ,
UserPermissionsAvantgoUser boolean ,
UserPermissionsCallCenterAutoLogin boolean ,
UserPermissionsMobileUser boolean ,
UserPermissionsSFContentUser boolean ,
UserPermissionsKnowledgeUser boolean ,
UserPermissionsInteractionUser boolean ,
UserPermissionsSupportUser boolean ,
UserPermissionsLiveAgentUser boolean ,
ForecastEnabled boolean ,
UserPreferencesActivityRemindersPopup boolean ,
UserPreferencesEventRemindersCheckboxDefault boolean ,
UserPreferencesTaskRemindersCheckboxDefault boolean ,
UserPreferencesReminderSoundOff boolean ,
UserPreferencesDisableAllFeedsEmail boolean ,
UserPreferencesDisableFollowersEmail boolean ,
UserPreferencesDisableProfilePostEmail boolean ,
UserPreferencesDisableChangeCommentEmail boolean ,
UserPreferencesDisableLaterCommentEmail boolean ,
UserPreferencesDisProfPostCommentEmail boolean ,
UserPreferencesApexPagesDeveloperMode boolean ,
UserPreferencesHideCSNGetChatterMobileTask boolean ,
UserPreferencesDisableMentionsPostEmail boolean ,
UserPreferencesDisMentionsCommentEmail boolean ,
UserPreferencesHideCSNDesktopTask boolean ,
UserPreferencesHideChatterOnboardingSplash boolean ,
UserPreferencesHideSecondChatterOnboardingSplash boolean ,
UserPreferencesDisCommentAfterLikeEmail boolean ,
UserPreferencesDisableLikeEmail boolean ,
UserPreferencesSortFeedByComment boolean ,
UserPreferencesDisableMessageEmail boolean ,
UserPreferencesDisableBookmarkEmail boolean ,
UserPreferencesDisableSharePostEmail boolean ,
UserPreferencesEnableAutoSubForFeeds boolean ,
UserPreferencesDisableFileShareNotificationsForApi boolean ,
UserPreferencesShowTitleToExternalUsers boolean ,
UserPreferencesShowManagerToExternalUsers boolean ,
UserPreferencesShowEmailToExternalUsers boolean ,
UserPreferencesShowWorkPhoneToExternalUsers boolean ,
UserPreferencesShowMobilePhoneToExternalUsers boolean ,
UserPreferencesShowFaxToExternalUsers boolean ,
UserPreferencesShowStreetAddressToExternalUsers boolean ,
UserPreferencesShowCityToExternalUsers boolean ,
UserPreferencesShowStateToExternalUsers boolean ,
UserPreferencesShowPostalCodeToExternalUsers boolean ,
UserPreferencesShowCountryToExternalUsers boolean ,
UserPreferencesShowProfilePicToGuestUsers boolean ,
UserPreferencesShowTitleToGuestUsers boolean ,
UserPreferencesShowCityToGuestUsers boolean ,
UserPreferencesShowStateToGuestUsers boolean ,
UserPreferencesShowPostalCodeToGuestUsers boolean ,
UserPreferencesShowCountryToGuestUsers boolean ,
UserPreferencesHideS1BrowserUI boolean ,
UserPreferencesDisableEndorsementEmail boolean ,
UserPreferencesPathAssistantCollapsed boolean ,
UserPreferencesCacheDiagnostics boolean ,
UserPreferencesShowEmailToGuestUsers boolean ,
UserPreferencesShowManagerToGuestUsers boolean ,
UserPreferencesShowWorkPhoneToGuestUsers boolean ,
UserPreferencesShowMobilePhoneToGuestUsers boolean ,
UserPreferencesShowFaxToGuestUsers boolean ,
UserPreferencesShowStreetAddressToGuestUsers boolean ,
UserPreferencesLightningExperiencePreferred boolean ,
UserPreferencesPreviewLightning boolean ,
UserPreferencesHideEndUserOnboardingAssistantModal boolean ,
UserPreferencesHideLightningMigrationModal boolean ,
UserPreferencesHideSfxWelcomeMat boolean ,
UserPreferencesHideBiggerPhotoCallout boolean ,
UserPreferencesGlobalNavBarWTShown boolean ,
UserPreferencesGlobalNavGridMenuWTShown boolean ,
UserPreferencesCreateLEXAppsWTShown boolean ,
UserPreferencesFavoritesWTShown boolean ,
ContactId string ,
AccountId string ,
CallCenterId string ,
Extension string ,
PortalRole string ,
IsPortalEnabled boolean ,
FederationIdentifier string ,
AboutMe string ,
FullPhotoUrl string ,
SmallPhotoUrl string ,
MediumPhotoUrl string ,
DigestFrequency string ,
DefaultGroupNotificationFrequency string ,
LastViewedDate timestamp ,
LastReferencedDate timestamp ,
BannerPhotoUrl string ,
SmallBannerPhotoUrl string ,
MediumBannerPhotoUrl string ,
IsProfilePhotoActive boolean ,
Actual_Sales_To_Date__c decimal,
Difference__c decimal ,
Sales_Target__c decimal,
Is_Manager__c double ,
et4ae5__Default_ET_Page__c string ,
et4ae5__Default_MID__c string ,
et4ae5__ExactTargetForAppExchangeAdmin__c boolean ,
et4ae5__ExactTargetForAppExchangeUser__c boolean ,
et4ae5__ExactTargetUsername__c string ,
et4ae5__ExactTarget_OAuth_Token__c string ,
et4ae5__ValidExactTargetAdmin__c boolean ,
et4ae5__ValidExactTargetUser__c boolean ,
icAgentConsole__incCustomScreenpop__c string ,
DB_Region__c string ,
Facebook_Email__c string ,
Facebook_ID__c string ,
job_id string,
load_data_timestamp timestamp,
epoc bigint,
year int, 
month int,
day int
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY '\t'
LINES TERMINATED BY '\n'
stored as TEXTFILE
Location "s3://vv-qa-emr-cluster/data/staging/crm/stg_crm_user"
;

CREATE EXTERNAL TABLE bd_db.stg_crm_account_cdc (
Id string,
IsDeleted boolean,
MasterRecordId string,
Name string,
LastName string,
FirstName string,
Salutation string,
MiddleName string,
Suffix string,
Type string,
RecordTypeId string,
ParentId string,
BillingStreet string,
BillingCity string,
BillingState string,
BillingPostalCode string,
BillingCountry string,
BillingStateCode string,
BillingCountryCode string,
BillingLatitude double,
BillingLongitude double,
BillingGeocodeAccuracy string,
BillingAddress string,
ShippingStreet string,
ShippingCity string,
ShippingState string,
ShippingPostalCode string,
ShippingCountry string,
ShippingStateCode string,
ShippingCountryCode string,
ShippingLatitude double,
ShippingLongitude double,
ShippingGeocodeAccuracy string,
ShippingAddress string,
Phone string,
Website string,
PhotoUrl string,
Industry string,
NumberOfEmployees int,
Description string,
CurrencyIsoCode string,
OwnerId string,
CreatedDate timestamp,
CreatedById string,
LastModifiedDate timestamp,
LastModifiedById string,
SystemModstamp timestamp,
LastActivityDate timestamp,
LastViewedDate timestamp,
LastReferencedDate timestamp,
IsPartner boolean,
IsCustomerPortal boolean,
PersonContactId string,
IsPersonAccount boolean,
PersonMailingStreet string,
PersonMailingCity string,
PersonMailingState string,
PersonMailingPostalCode string,
PersonMailingCountry string,
PersonMailingStateCode string,
PersonMailingCountryCode string,
PersonMailingLatitude double,
PersonMailingLongitude double,
PersonMailingGeocodeAccuracy string,
PersonMailingAddress string,
PersonMobilePhone string,
PersonEmail string,
PersonTitle string,
PersonDepartment string,
PersonBirthdate timestamp,
PersonLastCURequestDate timestamp,
PersonLastCUUpdateDate timestamp,
PersonEmailBouncedReason string,
PersonEmailBouncedDate timestamp,
Jigsaw string,
JigsawCompanyId string,
AccountSource string,
SicDesc string,
ARC_Number__c string,
Agency_Code__c string,
Primary_Contact_Email__c string,
Instagram__c string,
SailorID__c string,
SFSSDupeCatcher__Override_DupeCatcher__c boolean,
CLIA_Number__c string,
Citizenship_Country__c string,
Client_ID__c string,
Country_of_Residence__c string,
MagnoliaPassword__c string,
Household_ID__c string,
IATA_Number__c string,
Inbound__c boolean,
PseudoCityCode__c string,
Age__c double,
Tribe__c string,
Number_of_Active_Agents__c double,
Occupation__c string,
Office_Code__c string,
Outbound_Email__c boolean,
Outbound__c boolean,
Preferred_Name__c string,
Seaware_Agency_ID__c string,
Status__c string,
Taxpayer_ID__c string,
Taxpayer_Type__c string,
Total_Lifetime_Cruise_Nights__c double,
Consortium__c boolean,
Total_Revenue__c decimal,
Web_Address__c string,
Abta_Number__c string,
Preferred_Gender__c string,
Yelp__c string,
Facebook__c string,
Twitter__c string,
Snapchat__c string,
Subtribe__c string,
No_Social_Contact__c boolean,
State_of_the_Sailor__c string,
Data_Source__c string,
W9_Form_Received__c boolean,
Cover_Letter_Received__c boolean,
Business_License__c boolean,
Business_License_Type__c string,
GDLoyalLevel__c string,
Average_Lifetime_Spend_Per_Night__c decimal,
Average_Spend_Per_Night_for_Last_Cruise__c decimal,
Total_Lifetime_Spend__c decimal,
Registered_for_Web__c boolean,
Downloaded_Mobile_App__c boolean,
VXP_ID__c string,
GDLoyalLevelCode__c string,
Consortium_Type__c string,
Floating_Deposit__c boolean,
Secured_Fax_Email__c boolean,
IsGSA__c boolean,
IsInternal__c boolean,
IsWhiteLabel__c boolean,
TaxOwner__c string,
SNPrefix__c string,
InactiveReason__c string,
Asta_Number__c string,
isMasterXref__c boolean,
T_C_Consent_Date__c timestamp,
T_C_Consent_First_Name__c string,
T_C_Consent_Last_Name__c string,
GroupName__c string,
GroupLeader__c string,
Is_Primary_Contact__pc boolean,
SFSSDupeCatcher__Override_DupeCatcher__pc boolean,
Gender__pc string,
IATAN_Company_Name__pc string,
IATAN_Holder_Name__pc string,
IATAN_Number__pc double,
Agent_Type__pc string,
Preferred_Language__pc string,
Seaware_Agent_ID__pc string,
Status__pc boolean,
Suffix__pc string,
Target_Revenue__pc decimal,
Total_Revenue__pc decimal,
Agent_Status__pc string,
Alternate_Name__pc string,
Anniversary_Date__pc timestamp,
et4ae5__HasOptedOutOfMobile__pc boolean,
et4ae5__Mobile_Country_Code__pc string,
IATANExpDate__pc timestamp,
Marital_Status__pc string,
T_C_Consent_First_Name__pc string,
T_C_Consent_Last_Name__pc string,
Passport_Exp_Date__pc timestamp,
Passport_Number__pc string,
T_C_Consent_Date__pc timestamp,
Sales_Commission__pc double,
Sales_Commission_Amount__pc decimal, 
job_id string,
load_data_timestamp timestamp,
epoc bigint,
year int, 
month int,
day int
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY '\t'
LINES TERMINATED BY '\n'
stored as TEXTFILE
Location "s3://vv-qa-emr-cluster/data/staging/crm/stg_crm_account_cdc"
;
CREATE EXTERNAL TABLE bd_db.stg_crm_address_cdc(
Id string,
OwnerId string ,
IsDeleted boolean ,
Name string ,
CurrencyIsoCode string ,
CreatedDate TIMESTAMP,
CreatedById string ,
LastModifiedDate  TIMESTAMP,
LastModifiedById string ,
SystemModstamp TIMESTAMP,
Primary__c boolean ,
StreetNmbr__c string ,
AddLine__c string ,
CityName__c string ,
PostalCode__c string ,
County__c string,
StateCode__c string ,
CountryCode__c string ,
Sailor__c string,
AddressUniqueID__c string, 
job_id   string,
load_data_timestamp   timestamp,
epoc      bigint,
year int, 
month int,
day int
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY '\t'
LINES TERMINATED BY '\n'
stored as TEXTFILE
Location "s3://vv-qa-emr-cluster/data/staging/crm/stg_crm_address_cdc"
;

CREATE EXTERNAL TABLE bd_db.stg_crm_travel_with_cdc(
Id string,
IsDeleted boolean,
Name string,
CurrencyIsoCode string ,
CreatedDate timestamp ,
CreatedById string,
LastModifiedDate timestamp ,
LastModifiedById string,
SystemModstamp timestamp ,
LastViewedDate timestamp ,
LastReferencedDate timestamp ,
LinkTypeCode__c double ,
Relation__c double ,
MasterReservation__c string,
ReservationID__c string ,
Type__c double ,
ReservationNumber__c string ,
PrimarySailor__c string ,
job_id   string,
load_data_timestamp   timestamp,
epoc      bigint,
year int, 
month int,
day int
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY '\t'
LINES TERMINATED BY '\n'
stored as TEXTFILE
Location "s3://vv-qa-emr-cluster/data/staging/crm/stg_crm_travel_with_cdc"
; 

CREATE EXTERNAL TABLE bd_db.stg_crm_voyage_cdc (
Id string,
OwnerId string,
IsDeleted boolean,
Name string,
CurrencyIsoCode string,
CreatedDate timestamp,
CreatedById string,
LastModifiedDate timestamp ,
LastModifiedById string,
SystemModstamp timestamp ,
LastViewedDate timestamp ,
LastReferencedDate timestamp ,
VoyageID__c string,
NameOfVoyage__c string,
OnlineCheckInDate__c timestamp ,
dPort__c string,
aPort__c string,
Description__c string,
ActivityOpenDate__c timestamp ,
eDate__c timestamp ,
sDate__c timestamp ,
ActiveVoyageMessages__c double ,
job_id   string,
load_data_timestamp   timestamp,
epoc      bigint,
year int, 
month int,
day int
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY '\t'
LINES TERMINATED BY '\n'
stored as TEXTFILE
Location "s3://vv-qa-emr-cluster/data/staging/crm/stg_crm_voyage_cdc"
;

CREATE EXTERNAL TABLE bd_db.stg_crm_selected_category_cdc (
Id string ,
IsDeleted boolean ,
Name string,
CurrencyIsoCode string,
CreatedDate timestamp ,
CreatedById string ,
LastModifiedDate timestamp ,
LastModifiedById string ,
SystemModstamp timestamp ,
LastActivityDate timestamp ,
Reservation__c string ,
SCBerthedCatCode__c string,
SCPricedCatCode__c string,
SCDeckNumber__c string,
SCabinNumber__c string,
SCMaxOccupancy__c string ,
job_id   string,
load_data_timestamp   timestamp,
epoc      bigint,
year int, 
month int,
day int
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY '\t'
LINES TERMINATED BY '\n'
stored as TEXTFILE
Location "s3://vv-qa-emr-cluster/data/staging/crm/stg_crm_selected_category_cdc"
; 

CREATE EXTERNAL TABLE bd_db.stg_crm_voyage_message_cdc (
Id string,
IsDeleted boolean,
Name string,
CurrencyIsoCode string,
CreatedDate timestamp,
CreatedById string,
LastModifiedDate timestamp,
LastModifiedById string,
SystemModstamp timestamp,
Message__c string,
Active__c boolean,
Voyage__c string,
Title__c string,
job_id   string,
load_data_timestamp   timestamp,
epoc      bigint,
year int, 
month int,
day int
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY '\t'
LINES TERMINATED BY '\n'
stored as TEXTFILE
Location "s3://vv-qa-emr-cluster/data/staging/crm/stg_crm_voyage_message_cdc"
; 

CREATE  EXTERNAL TABLE bd_db.stg_crm_contact_details_cdc (
Id string,
OwnerId string,
IsDeleted boolean ,
Name string,
CurrencyIsoCode string,
CreatedDate timestamp ,
CreatedById string,
LastModifiedDate timestamp ,
LastModifiedById string,
SystemModstamp timestamp ,
Primary__c boolean ,
PLocationType__c double,
CountryCode__c string,
AreaCityCode__c string,
PhoneNumber__c string,
Extension__c string,
Sailor__c string,
ConDetailUniqueID__c string,
EmergencyFlag__c boolean ,
job_id   string,
load_data_timestamp   timestamp,
epoc      bigint,
year int, 
month int,
day int
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY '\t'
LINES TERMINATED BY '\n'
stored as TEXTFILE
Location "s3://vv-qa-emr-cluster/data/staging/crm/stg_crm_contact_details_cdc"
;

CREATE EXTERNAL TABLE bd_db.stg_crm_campaign_cdc (
Id string,
IsDeleted boolean ,
Name string,
ParentId string,
Type string,
Status string,
StartDate timestamp,
EndDate timestamp,
CurrencyIsoCode string,
ExpectedRevenue decimal(18,0) ,
BudgetedCost decimal(18,0) ,
ActualCost decimal(18,0) ,
ExpectedResponse double,
NumberSent double,
IsActive boolean ,
Description string,
NumberOfLeads int,
NumberOfConvertedLeads int ,
NumberOfContacts int ,
NumberOfResponses int ,
NumberOfOpportunities int ,
NumberOfWonOpportunities int ,
AmountAllOpportunities decimal(18,0) ,
AmountWonOpportunities decimal(18,0) ,
HierarchyNumberOfLeads int ,
HierarchyNumberOfConvertedLeads int ,
HierarchyNumberOfContacts int ,
HierarchyNumberOfResponses int ,
HierarchyNumberOfWonOpportunities int ,
HierarchyNumberSent double,
HierarchyExpectedRevenue decimal(18,0) ,
HierarchyActualCost decimal(18,0) ,
OwnerId string,
CreatedDate timestamp ,
CreatedById string,
LastModifiedDate timestamp ,
LastModifiedById string,
SystemModstamp timestamp ,
LastActivityDate timestamp ,
LastViewedDate timestamp ,
LastReferencedDate timestamp ,
CampaignMemberRecordTypeId string,
Campaign_Channel__c string,
Campaign_Country__c string,
Campaign_Office__c string ,
Campaign_Region__c string ,
Coupon_Code__c string ,
Coupon_Description__c string,
Coupon_Name__c string ,
Plan_Code__c string ,
Segment_Code__c string ,
Variation_Code__c string ,
Plan_Name__c string ,
Campaign_Brand__c string,
Campaign_Code__c string ,
Coupon_Activation_Date__c timestamp ,
Coupon_Expiration_Date__c timestamp ,
Program_Code__c string ,
Program_Name__c string ,
Sub_Plan_Code__c string ,
Sub_Plan_Name__c string ,
Treatment_Activation_Date__c timestamp ,
Treatment_Code__c string ,
Treatment_Description__c string,
Treatment_Expiration_Date__c timestamp ,
Treatment_Name__c string ,
Treatment_Type__c string,
Wave_Code__c string ,
Opportunity__c string,
VoyageSpecific__c boolean ,
Voyage__c string,
CampaignId__c string,
DB_Campaign_Tactic__c string,
job_id   string,
load_data_timestamp   timestamp,
epoc      bigint,
year int, 
month int,
day int
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY '\t'
LINES TERMINATED BY '\n'
stored as TEXTFILE
Location "s3://vv-qa-emr-cluster/data/staging/crm/stg_crm_campaign_cdc"
;

CREATE EXTERNAL TABLE bd_db.stg_crm_lead_cdc (
Id string ,
IsDeleted boolean ,
MasterRecordId string ,
LastName string ,
FirstName string ,
Salutation string ,
MiddleName string ,
Suffix string ,
Name string ,
Title string ,
Company string ,
Street string ,
City string ,
State string ,
PostalCode string ,
Country string ,
StateCode string ,
CountryCode string ,
Latitude double ,
Longitude double ,
GeocodeAccuracy string ,
Address string ,
Phone string ,
MobilePhone string ,
Email string ,
Website string ,
PhotoUrl string ,
LeadSource string ,
Status string ,
Industry string ,
Rating string ,
CurrencyIsoCode string ,
NumberOfEmployees int ,
OwnerId string ,
HasOptedOutOfEmail boolean,
IsConverted boolean ,
ConvertedDate timestamp ,
ConvertedAccountId string ,
ConvertedContactId string ,
ConvertedOpportunityId string ,
IsUnreadByOwner boolean ,
CreatedDate timestamp ,
CreatedById string ,
LastModifiedDate timestamp ,
LastModifiedById string ,
SystemModstamp timestamp ,
LastActivityDate timestamp ,
LastViewedDate timestamp ,
LastReferencedDate timestamp ,
Jigsaw string ,
JigsawContactId string ,
EmailBouncedReason string ,
EmailBouncedDate timestamp ,
et4ae5__HasOptedOutOfMobile__c boolean,
et4ae5__Mobile_Country_Code__c string ,
SFSSDupeCatcher__Override_DupeCatcher__c boolean ,
DB_Created_Date_without_Time__c timestamp ,
DB_Lead_Age__c double,
job_id   string,
load_data_timestamp   timestamp,
epoc      bigint,
year int, 
month int,
day int
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY '\t'
LINES TERMINATED BY '\n'
stored as TEXTFILE
Location "s3://vv-qa-emr-cluster/data/staging/crm/stg_crm_lead_cdc"
;

CREATE EXTERNAL TABLE bd_db.stg_crm_booking_payments_cdc (
Id string,
IsDeleted boolean,
Name string,
CurrencyIsoCode string,
CreatedDate timestamp ,
CreatedById string,
LastModifiedDate timestamp ,
LastModifiedById string ,
SystemModstamp timestamp ,
LastViewedDate timestamp ,
LastReferencedDate timestamp ,
Booking_ID__c string ,
Payment_Amount__c decimal(18,2) ,
PaymentCode__c double,
Payment_Type__c string,
Quote_ID__c string ,
Payment_Date__c timestamp ,
Preferred_Currency__c string,
Preferred_Currency_Amount__c decimal(18,0) ,
job_id   string,
load_data_timestamp   timestamp,
epoc      bigint,
year int, 
month int,
day int
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY '\t'
LINES TERMINATED BY '\n'
stored as TEXTFILE
Location "s3://vv-qa-emr-cluster/data/staging/crm/stg_crm_booking_payments_cdc"
;

CREATE EXTERNAL TABLE bd_db.stg_crm_bookable_activities_cdc (
Id string ,
IsDeleted boolean ,
Name string,
CurrencyIsoCode string ,
CreatedDate timestamp ,
CreatedById string ,
LastModifiedDate timestamp ,
LastModifiedById string ,
SystemModstamp timestamp ,
Booking_ID__c string ,
eDate__c timestamp ,
Duration__c string ,
Bookable_Activity_ID__c string,
Description__c string ,
Travel_Party_Member__c string ,
Activity_Date__c timestamp ,
Category__c string ,
CruisePackageCode__c string,
BKUniqueID__c string,
Location__c string,
Internal_Code__c string,
PackageSubType__c string,
PackageTypeCode__c string,
sDate__c timestamp ,
job_id   string,
load_data_timestamp   timestamp,
epoc      bigint,
year int, 
month int,
day int
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY '\t'
LINES TERMINATED BY '\n'
stored as TEXTFILE
Location "s3://vv-qa-emr-cluster/data/staging/crm/stg_crm_bookable_activities_cdc"
;
CREATE EXTERNAL TABLE bd_db.stg_crm_household_cdc (
Id string,
OwnerId string,
IsDeleted boolean ,
Name string ,
CurrencyIsoCode string ,
CreatedDate timestamp ,
CreatedById string,
LastModifiedDate timestamp ,
LastModifiedById string,
SystemModstamp timestamp ,
LastViewedDate timestamp ,
LastReferencedDate timestamp ,
Number_of_Household_Members__c double,
Household_Address_Postal_Code__c string,
Household_Address_State__c string,
Primary_Sailor__c string,
Seaware_Household_ID__c string ,
Status__c string,
Total_Lifetime_Cruise_Nights__c double,
Household_Address_Line_2__c string,
Total_OBS_Amount__c decimal(18,2) ,
Household_Address_City__c string,
Average_Lifetime_Spend_Per_Night__c decimal(18,2) ,
Average_Spend_Per_Night_for_Last_Cruise__c decimal(18,2) ,
Total_Lifetime_Spend__c decimal(18,2) ,
Household_Address_Line_1__c string ,
job_id   string,
load_data_timestamp   timestamp,
epoc      bigint,
year int, 
month int,
day int
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY '\t'
LINES TERMINATED BY '\n'
stored as TEXTFILE
Location "s3://vv-qa-emr-cluster/data/staging/crm/stg_crm_household_cdc"
;
CREATE EXTERNAL TABLE bd_db.stg_crm_case_cdc (
Id string,
IsDeleted boolean ,
CaseNumber string,
ContactId string,
AccountId string ,
EntitlementId string ,
SourceId string ,
ParentId string ,
SuppliedName string ,
SuppliedEmail string ,
SuppliedPhone string ,
SuppliedCompany string ,
Type string ,
RecordTypeId string ,
Status string ,
Reason string ,
Origin string ,
Subject string ,
Priority string ,
Description string ,
IsClosed boolean ,
ClosedDate timestamp ,
IsEscalated boolean ,
CurrencyIsoCode string ,
OwnerId string ,
CreatedDate timestamp ,
CreatedById string ,
LastModifiedDate timestamp ,
LastModifiedById string ,
SystemModstamp timestamp ,
ContactPhone string ,
ContactMobile string ,
ContactEmail string ,
ContactFax string ,
LastViewedDate timestamp ,
LastReferencedDate timestamp ,
Opportunity__c string ,
Booked_Activities__c string ,
Booking_Payments__c string ,
Category__c string ,
Sub_Category__c string ,
CaseSubReason__c string ,
Link__c string ,
Voyage__c string ,
Transferred_to__c string ,
Escalation_Reason__c string ,
Description__c string ,
WebFName__c string ,
Last_Interaction_Date__c timestamp ,
WebLName__c string ,
Case_Resolution__c string ,
Sailor_Email__c string ,
Sailor_Name__c string ,
job_id string,
load_data_timestamp timestamp,
epoc    bigint,
year int, 
month int,
day int
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY '\t'
LINES TERMINATED BY '\n'
stored as TEXTFILE
Location "s3://vv-qa-emr-cluster/data/staging/crm/stg_crm_case_cdc"
;
CREATE EXTERNAL TABLE bd_db.stg_crm_contact_cdc (
Id string ,
IsDeleted boolean ,
MasterRecordId string ,
AccountId string ,
IsPersonAccount boolean ,
LastName string ,
FirstName string ,
Salutation string ,
MiddleName string ,
Suffix string ,
Name string ,
RecordTypeId string ,
MailingStreet string ,
MailingCity string ,
MailingState string ,
MailingPostalCode string ,
MailingCountry string ,
MailingStateCode string ,
MailingCountryCode string ,
MailingLatitude double ,
MailingLongitude double ,
MailingGeocodeAccuracy string ,
MailingAddress string ,
Phone string ,
Fax string ,
MobilePhone string ,
ReportsToId string ,
Email string ,
Title string ,
Department string ,
Birthdate timestamp ,
CurrencyIsoCode string ,
OwnerId string ,
CreatedDate timestamp ,
CreatedById string ,
LastModifiedDate timestamp ,
LastModifiedById string ,
SystemModstamp timestamp ,
LastActivityDate timestamp ,
LastCURequestDate timestamp ,
LastCUUpdateDate timestamp ,
LastViewedDate timestamp ,
LastReferencedDate timestamp ,
EmailBouncedReason string ,
EmailBouncedDate timestamp ,
IsEmailBounced boolean ,
PhotoUrl string ,
Jigsaw string ,
JigsawContactId string ,
Is_Primary_Contact__c boolean ,
SFSSDupeCatcher__Override_DupeCatcher__c boolean ,
Gender__c string ,
IATAN_Company_Name__c string ,
IATAN_Holder_Name__c string ,
IATAN_Number__c double,
Agent_Type__c string ,
Preferred_Language__c string ,
Seaware_Agent_ID__c string ,
Status__c boolean ,
Suffix__c string ,
Target_Revenue__c decimal,
Total_Revenue__c decimal,
Agent_Status__c string ,
Alternate_Name__c string,
Anniversary_Date__c timestamp ,
et4ae5__HasOptedOutOfMobile__c boolean ,
et4ae5__Mobile_Country_Code__c string ,
IATANExpDate__c timestamp ,
Marital_Status__c string ,
T_C_Consent_First_Name__c string,
T_C_Consent_Last_Name__c string,
Passport_Exp_Date__c timestamp ,
Passport_Number__c string ,
T_C_Consent_Date__c timestamp ,
Sales_Commission__c double,
Sales_Commission_Amount__c decimal,
job_id   string,
load_data_timestamp   timestamp,
epoc      bigint,
year int, 
month int,
day int
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY '\t'
LINES TERMINATED BY '\n'
stored as TEXTFILE
Location "s3://vv-qa-emr-cluster/data/staging/crm/stg_crm_contact_cdc"
;

CREATE EXTERNAL TABLE bd_db.stg_crm_travel_party_member_cdc (
Id string,
IsDeleted string,
Name string,
CurrencyIsoCode string,
CreatedDate timestamp,
CreatedById string,
LastModifiedDate timestamp,
LastModifiedById string,
SystemModstamp timestamp,
LastActivityDate timestamp,
Booking_ID__c string,
Sailor_ID__c string,
Sequence_Number__c string,
Quote_ID__c string,
IsPrimary__c string,
Parent_Reservation__c string,
SailorStatus__c string,
VoyageID__c string,
GDRepeatGIndicator__c string,
GDSFareCode__c string,
GDGroupCode__c string,
InsuranceCode__c string,
SPackageTypeCode__c string,
SCruisePackageCode__c string,
Check_In_Status_Flag__c string,
CheckedIn__c string,
GuestType__c string,
job_id string,
load_data_timestamp timestamp,
epoc bigint,
year int, 
month int,
day int
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY '\t'
LINES TERMINATED BY '\n'
stored as TEXTFILE
Location "s3://vv-qa-emr-cluster/data/staging/crm/stg_crm_travel_party_member_cdc"
;

CREATE EXTERNAL TABLE bd_db.stg_crm_opportunity_cdc (
Id string,
IsDeleted boolean,
AccountId string,
RecordTypeId string,
Name string ,
Description string ,
StageName string ,
Amount decimal ,
Probability double ,
CloseDate timestamp ,
Type string ,
NextStep string ,
LeadSource string ,
IsClosed boolean,
IsWon boolean,
ForecastCategory string ,
ForecastCategoryName string ,
CurrencyIsoCode string ,
CampaignId string,
HasOpportunityLineItem boolean,
Pricebook2Id string,
OwnerId string,
CreatedDate timestamp ,
CreatedById string,
LastModifiedDate timestamp ,
LastModifiedById string,
SystemModstamp timestamp ,
LastActivityDate timestamp ,
FiscalQuarter int ,
FiscalYear int ,
Fiscal string ,
LastViewedDate timestamp ,
LastReferencedDate timestamp ,
SyncedQuoteId string,
ContractId string,
HasOpenActivity boolean,
HasOverdueTask boolean,
Budget_Confirmed__c boolean,
Discovery_Completed__c boolean,
ROI_Analysis_Completed__c boolean,
Loss_Reason__c string ,
AgentName__c string,
SSStart__c timestamp ,
SSEnd__c timestamp ,
Booking_ID__c string ,
VoyageID__c string,
Currency__c decimal ,
SSDuration__c string ,
SSPortsofCallQuality__c string ,
Display_Tab__c string ,
Next_Payment_Date__c timestamp ,
Flight_Purchase__c string ,
Group_Id__c string ,
SSLOSDescriptionCode__c string ,
Number_of_Guests__c double ,
Number_of_Stateroom__c double ,
CLShipName__c string ,
Package_Type__c string ,
Parent_Res_ID__c string ,
Port_Name__c string ,
Post_Cruise_Transfer__c string ,
CLVendorCode__c string ,
Prepaid_Gratuities__c string ,
RegionCode__c string ,
Reservation_Number__c string ,
CruisePackageCode__c string ,
Sailing_Package__c string ,
Ship_Code__c string ,
CurrencyCode__c string ,
Status__c string ,
Vacation_Protection__c string ,
Booking_Payments_Total__c decimal ,
Seaware_Reservation_Status__c string ,
Opportunity_Amount__c decimal ,
OpportunityRevenueOwner__c string ,
Vacation_Start_Date__c timestamp ,
Record_Type__c string ,
ParentBookingId__c string,
DecimalPlaces__c string ,
BookedDate__c timestamp ,
Cabin_Category__c string ,
Disembarkation_Date__c timestamp ,
Embarkation_Date__c timestamp ,
Checked_In__c boolean,
OfferDate__c timestamp ,
Seaware_AgentID__c string ,
Init_Date__c timestamp ,
Booking_Channel__c string ,
AgencyID__c string ,
Voyage_Status__c string ,
Preferred_Currency__c string ,
DB_Competitor__c string ,
VacationEndDate__c timestamp ,
Self__c boolean,
GuestType__c string ,
AgencyName__c string,
Preferred_Currency_Amount__c decimal ,
GroupType__c string ,
GroupDate__c timestamp ,
GroupShell__c string,
GroupName__c string,
job_id string,
load_data_timestamp timestamp,
epoc bigint,
year int, 
month int,
day int
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY '\t'
LINES TERMINATED BY '\n'
stored as TEXTFILE
Location "s3://vv-qa-emr-cluster/data/staging/crm/stg_crm_opportunity_cdc"
;
CREATE EXTERNAL TABLE bd_db.stg_crm_user_cdc (
Id string ,
Username string ,
LastName string ,
FirstName string ,
MiddleName string ,
Suffix string ,
Name string ,
CompanyName string ,
Division string ,
Department string ,
Title string ,
Street string ,
City string ,
State string ,
PostalCode string ,
Country string ,
StateCode string ,
CountryCode string ,
Latitude double ,
Longitude double ,
GeocodeAccuracy string ,
Address string ,
Email string ,
EmailPreferencesAutoBcc boolean ,
EmailPreferencesAutoBccStayInTouch boolean ,
EmailPreferencesStayInTouchReminder boolean ,
SenderEmail string ,
SenderName string ,
Signature string ,
StayInTouchSubject string ,
StayInTouchSignature string ,
StayInTouchNote string ,
Phone string ,
Fax string ,
MobilePhone string ,
Alias string ,
CommunityNickname string ,
BadgeText string ,
IsActive boolean ,
TimeZoneSidKey string ,
UserRoleId string ,
LocaleSidKey string ,
ReceivesInfoEmails boolean ,
ReceivesAdminInfoEmails boolean ,
EmailEncodingKey string ,
DefaultCurrencyIsoCode string ,
CurrencyIsoCode string ,
ProfileId string ,
UserType string ,
LanguageLocaleKey string ,
EmployeeNumber string ,
DelegatedApproverId string ,
ManagerId string ,
LastLoginDate timestamp ,
LastPasswordChangeDate timestamp ,
CreatedDate timestamp ,
CreatedById string ,
LastModifiedDate timestamp ,
LastModifiedById string ,
SystemModstamp timestamp ,
OfflineTrialExpirationDate timestamp ,
OfflinePdaTrialExpirationDate timestamp ,
UserPermissionsMarketingUser boolean ,
UserPermissionsOfflineUser boolean ,
UserPermissionsAvantgoUser boolean ,
UserPermissionsCallCenterAutoLogin boolean ,
UserPermissionsMobileUser boolean ,
UserPermissionsSFContentUser boolean ,
UserPermissionsKnowledgeUser boolean ,
UserPermissionsInteractionUser boolean ,
UserPermissionsSupportUser boolean ,
UserPermissionsLiveAgentUser boolean ,
ForecastEnabled boolean ,
UserPreferencesActivityRemindersPopup boolean ,
UserPreferencesEventRemindersCheckboxDefault boolean ,
UserPreferencesTaskRemindersCheckboxDefault boolean ,
UserPreferencesReminderSoundOff boolean ,
UserPreferencesDisableAllFeedsEmail boolean ,
UserPreferencesDisableFollowersEmail boolean ,
UserPreferencesDisableProfilePostEmail boolean ,
UserPreferencesDisableChangeCommentEmail boolean ,
UserPreferencesDisableLaterCommentEmail boolean ,
UserPreferencesDisProfPostCommentEmail boolean ,
UserPreferencesApexPagesDeveloperMode boolean ,
UserPreferencesHideCSNGetChatterMobileTask boolean ,
UserPreferencesDisableMentionsPostEmail boolean ,
UserPreferencesDisMentionsCommentEmail boolean ,
UserPreferencesHideCSNDesktopTask boolean ,
UserPreferencesHideChatterOnboardingSplash boolean ,
UserPreferencesHideSecondChatterOnboardingSplash boolean ,
UserPreferencesDisCommentAfterLikeEmail boolean ,
UserPreferencesDisableLikeEmail boolean ,
UserPreferencesSortFeedByComment boolean ,
UserPreferencesDisableMessageEmail boolean ,
UserPreferencesDisableBookmarkEmail boolean ,
UserPreferencesDisableSharePostEmail boolean ,
UserPreferencesEnableAutoSubForFeeds boolean ,
UserPreferencesDisableFileShareNotificationsForApi boolean ,
UserPreferencesShowTitleToEXTERNALUsers boolean ,
UserPreferencesShowManagerToEXTERNALUsers boolean ,
UserPreferencesShowEmailToEXTERNALUsers boolean ,
UserPreferencesShowWorkPhoneToEXTERNALUsers boolean ,
UserPreferencesShowMobilePhoneToEXTERNALUsers boolean ,
UserPreferencesShowFaxToEXTERNALUsers boolean ,
UserPreferencesShowStreetAddressToEXTERNALUsers boolean ,
UserPreferencesShowCityToEXTERNALUsers boolean ,
UserPreferencesShowStateToEXTERNALUsers boolean ,
UserPreferencesShowPostalCodeToEXTERNALUsers boolean ,
UserPreferencesShowCountryToEXTERNALUsers boolean ,
UserPreferencesShowProfilePicToGuestUsers boolean ,
UserPreferencesShowTitleToGuestUsers boolean ,
UserPreferencesShowCityToGuestUsers boolean ,
UserPreferencesShowStateToGuestUsers boolean ,
UserPreferencesShowPostalCodeToGuestUsers boolean ,
UserPreferencesShowCountryToGuestUsers boolean ,
UserPreferencesHideS1BrowserUI boolean ,
UserPreferencesDisableEndorsementEmail boolean ,
UserPreferencesPathAssistantCollapsed boolean ,
UserPreferencesCacheDiagnostics boolean ,
UserPreferencesShowEmailToGuestUsers boolean ,
UserPreferencesShowManagerToGuestUsers boolean ,
UserPreferencesShowWorkPhoneToGuestUsers boolean ,
UserPreferencesShowMobilePhoneToGuestUsers boolean ,
UserPreferencesShowFaxToGuestUsers boolean ,
UserPreferencesShowStreetAddressToGuestUsers boolean ,
UserPreferencesLightningExperiencePreferred boolean ,
UserPreferencesPreviewLightning boolean ,
UserPreferencesHideEndUserOnboardingAssistantModal boolean ,
UserPreferencesHideLightningMigrationModal boolean ,
UserPreferencesHideSfxWelcomeMat boolean ,
UserPreferencesHideBiggerPhotoCallout boolean ,
UserPreferencesGlobalNavBarWTShown boolean ,
UserPreferencesGlobalNavGridMenuWTShown boolean ,
UserPreferencesCreateLEXAppsWTShown boolean ,
UserPreferencesFavoritesWTShown boolean ,
ContactId string ,
AccountId string ,
CallCenterId string ,
Extension string ,
PortalRole string ,
IsPortalEnabled boolean ,
FederationIdentifier string ,
AboutMe string ,
FullPhotoUrl string ,
SmallPhotoUrl string ,
MediumPhotoUrl string ,
DigestFrequency string ,
DefaultGroupNotificationFrequency string ,
LastViewedDate timestamp ,
LastReferencedDate timestamp ,
BannerPhotoUrl string ,
SmallBannerPhotoUrl string ,
MediumBannerPhotoUrl string ,
IsProfilePhotoActive boolean ,
Actual_Sales_To_Date__c decimal,
Difference__c decimal ,
Sales_Target__c decimal,
Is_Manager__c double ,
et4ae5__Default_ET_Page__c string ,
et4ae5__Default_MID__c string ,
et4ae5__ExactTargetForAppExchangeAdmin__c boolean ,
et4ae5__ExactTargetForAppExchangeUser__c boolean ,
et4ae5__ExactTargetUsername__c string ,
et4ae5__ExactTarget_OAuth_Token__c string ,
et4ae5__ValidExactTargetAdmin__c boolean ,
et4ae5__ValidExactTargetUser__c boolean ,
icAgentConsole__incCustomScreenpop__c string ,
DB_Region__c string ,
Facebook_Email__c string ,
Facebook_ID__c string ,
job_id string,
load_data_timestamp timestamp,
epoc bigint,
year int, 
month int,
day int
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY '\t'
LINES TERMINATED BY '\n'
stored as TEXTFILE
Location "s3://vv-qa-emr-cluster/data/staging/crm/stg_crm_user_cdc"
;
