spark.src.kafka.topic shp2shr-dev-hbtb-nbx-calendar-recommendations
spark.src.seconds 60
spark.streaming.kafka.maxRatePerPartition 10000
spark.src.consumer spark-consumer-100
spark.kafkabrokers 10.2.52.146:9092,10.2.52.148:9092,10.2.52.162:9092
spark.ssl.enabled false     
spark.debug.flag false
spark.target.table.schema NBXUNIQUEKEY varchar,SAILORID varchar,ACTIVITYID varchar,CATEGORY varchar,DESCRIPTION varchar,RANKING varchar,START_DATETIME varchar,END_DATETIME varchar,ISACTIVE varchar,ISRECOMMENDED varchar,CORRELATIONID varchar,VOYAGEID varchar,TIMESTAMP timestamp,EXTERNALID varchar
spark.target.table HBTB_NBX_CALENDAR_RECOMMENDATIONS
spark.target.table.format org.apache.phoenix.spark
spark.target.table.mode overwrite
spark.target.zkurl ip-10-3-100-222.seatrials.virginvoyages.com:2181/hbase-unsecure

spark.target.VOYAGEOPS_table HBTB_NBX_SHIPTOSHORE_SYNC_VOYAGEOPS
spark.personcreated.offsettable HBTB_NBX_KAFKA_STREAMING_OFFSET 
spark.personcreated.format org.apache.phoenix.spark
spark.personcreated.mode overwrite
spark.personcreated.readhbasezkurl ip-10-3-100-222.seatrials.virginvoyages.com:2181/hbase-unsecure

spark.src.voyageid SC2002269NCR
spark.src.srcConfig shr2shp-nbx-hbtb-calendar-recommendations-SC2002269NCR
spark.src.tgtConfig HBTB_NBX_CALENDAR_RECOMMENDATIONS-SC2002269NCR
spark.job.type sync

spark.passvalue SetS@!l2o2o
spark.truststore /etc/script_keystore/dxp.kafka.client.truststore.AWS.shore.jks
spark.keystore /etc/script_keystore/dxp.kafka.client.keystore.AWS.shore.jks
spark.kafka.zookeeper 10.2.52.146:2181