dag_id: "E2E_SALES_RECON_SDI_ORACLEGL_RDS_TO_IDS"
dag_description: "Sonic Oracle GL data load from RDS to IDS"
email: ['udpfinanceengineeringpod@inspirebrands.com']
source_env : "DEV"
target_env : "DEV"
warehouse_id : "IRB_PRCSSA_IRB_WH"
schema_id : "SDI"