create TABLE IF NOT EXISTS FLYWAY_SCHEMA_HISTORY (
	INSTALLED_RANK NUMBER(38,0) NOT NULL,
	VERSION VARCHAR(50),
	DESCRIPTION VARCHAR(200),
	TYPE VARCHAR(20) NOT NULL,
	SCRIPT VARCHAR(1000) NOT NULL,
	CHECKSUM NUMBER(38,0),
	INSTALLED_BY VARCHAR(100) NOT NULL,
	INSTALLED_ON TIMESTAMP_LTZ(9) NOT NULL DEFAULT CURRENT_TIMESTAMP(),
	EXECUTION_TIME NUMBER(38,0) NOT NULL,
	SUCCESS BOOLEAN NOT NULL,
	primary key (INSTALLED_RANK)
);
create view IF NOT EXISTS BROWSER_DIM_BV(
	BROWSER_SIZE_VAL,
	FLASH_VER_NBR,
	BROWSER_TYP,
	BROWSER_KEY,
	UPDATE_DTTM,
	UPDATE_ID,
	BROWSER_VERSION_NM,
	LOAD_DTTM,
	JAVA_ENABLED_IND,
	LOAD_TYP,
	LOAD_ID
) as SELECT
                               BROWSER_SIZE_VAL, FLASH_VER_NBR, BROWSER_TYP, BROWSER_KEY, UPDATE_DTTM, UPDATE_ID, BROWSER_VERSION_NM, LOAD_DTTM, JAVA_ENABLED_IND, LOAD_TYP, LOAD_ID
                            FROM IDM_DEV.CBA."BROWSER_DIM";
create view IF NOT EXISTS DEVICE_DIM_BV(
	SCREEN_COLOR_TXT,
	LOAD_TYP,
	OS_TYP,
	UPDATE_ID,
	DEVICE_SCRN_RESOL_NM,
	UPDATE_DTTM,
	DEVICE_LANG_NM,
	LOAD_ID,
	OS_VER_NBR,
	DEVICE_CAT,
	LOAD_DTTM,
	DEVICE_KEY
) as SELECT
                               SCREEN_COLOR_TXT, LOAD_TYP, OS_TYP, UPDATE_ID, DEVICE_SCRN_RESOL_NM, UPDATE_DTTM, DEVICE_LANG_NM, LOAD_ID, OS_VER_NBR, DEVICE_CAT, LOAD_DTTM, DEVICE_KEY
                            FROM IDM_DEV.CBA."DEVICE_DIM";
create view IF NOT EXISTS DEVOPS_TEST(
	DEVICE_KEY,
	DEVICE_SCRN_RESOL_NM,
	DEVICE_LANG_NM,
	DEVICE_CAT,
	OS_TYP,
	OS_VER_NBR,
	SCREEN_COLOR_TXT,
	LOAD_TYP,
	LOAD_ID,
	LOAD_DTTM,
	UPDATE_ID,
	UPDATE_DTTM
) as
SELECT * FROM IDM_DEV.CBA.DEVICE_DIM;
create view IF NOT EXISTS LOYALTY_ORDER_FACT_BV(
	CHECK_NBR,
	TRANSACTION_STATUS_TYP,
	STORE_KEY,
	ATTACHMENT_METHOD_TYP,
	MIN_DAY_PART_ID,
	ORDER_ID,
	BRAND_ID,
	TRANSACTION_ID,
	UPDATE_ID,
	DOLLAR_NET_VALUE_AMT,
	EMPLOYEE_KEY,
	MEMBER_PHONE_NBR,
	EMPLOYEE_NM,
	LOAD_DTTM,
	SUSPENDED_TRANSACTION_STATUS_IND,
	LOAD_ID,
	MEMBER_CARD_NBR,
	MAX_DAY_PART_ID,
	LOAD_TYP,
	REASON_CD,
	STORE_ID,
	SUSPENDED_TRANSACTION_ID,
	ELIGIBLE_REVENUE_AMT,
	MEMBER_ID,
	BUSINESS_DT,
	UPDATE_DTTM,
	SOURCE_SYSTEM_NM,
	EMPLOYEE_ID,
	BUSINESS_DATE_KEY,
	CUSTOMER_KEY
) as SELECT
                               CHECK_NBR, TRANSACTION_STATUS_TYP, STORE_KEY, ATTACHMENT_METHOD_TYP, MIN_DAY_PART_ID, ORDER_ID, BRAND_ID, TRANSACTION_ID, UPDATE_ID, DOLLAR_NET_VALUE_AMT, EMPLOYEE_KEY, MEMBER_PHONE_NBR, EMPLOYEE_NM, LOAD_DTTM, SUSPENDED_TRANSACTION_STATUS_IND, LOAD_ID, MEMBER_CARD_NBR, MAX_DAY_PART_ID, LOAD_TYP, REASON_CD, STORE_ID, SUSPENDED_TRANSACTION_ID, ELIGIBLE_REVENUE_AMT, MEMBER_ID, BUSINESS_DT, UPDATE_DTTM, SOURCE_SYSTEM_NM, EMPLOYEE_ID, BUSINESS_DATE_KEY, CUSTOMER_KEY
                            FROM IDM_DEV.CBA."LOYALTY_ORDER_FACT";
create view IF NOT EXISTS MOBILE_DIM_BV(
	LOAD_ID,
	MOBILE_DEVICE_INFO_NM,
	MOBILE_DEVICE_MODEL_NBR,
	LOAD_TYP,
	UPDATE_DTTM,
	MOBILE_INPUT_SELECTOR_NM,
	MOBILE_DEVICE_BRANDING_NM,
	MOBILE_KEY,
	MOBILE_DEVICE_MKT_NM,
	LOAD_DTTM,
	UPDATE_ID
) as SELECT
                               LOAD_ID, MOBILE_DEVICE_INFO_NM, MOBILE_DEVICE_MODEL_NBR, LOAD_TYP, UPDATE_DTTM, MOBILE_INPUT_SELECTOR_NM, MOBILE_DEVICE_BRANDING_NM, MOBILE_KEY, MOBILE_DEVICE_MKT_NM, LOAD_DTTM, UPDATE_ID
                            FROM IDM_DEV.CBA."MOBILE_DIM";
create view IF NOT EXISTS SESSION_SUMMARY_FACT_BV(
	BRAND_ID,
	BUSINESS_DT_KEY,
	LOAD_ID,
	LOAD_TYP,
	SOURCE_TOTAL_SCRN_VIEW_CNT,
	CUSTOMER_KEY,
	DEVICE_KEY,
	USER_GEO_NTWK_LOC_KEY,
	CUSTOMER_ID,
	LOAD_DTTM,
	MOBILE_KEY,
	SOURCE_TRX_REVENUE_CNT,
	BROWSER_KEY,
	LAT_NBR,
	SOURCE_TOTAL_NEW_VISIT_CNT,
	SOURCE_TOTAL_HIT_CNT,
	VISIT_NBR,
	CITY_ID,
	FULL_VISITOR_ID,
	SOURCE_TOTAL_VISIT_CNT,
	CAMPAIGN_CD,
	DATASET_ID,
	STORE_KEY,
	SOURCE_TOTAL_PAGE_VIEW_CNT,
	SOURCE_TOTAL_SESSION_QTY_DIM_CNT,
	SOURCE_TOTAL_TM_ONSITE_CNT,
	USER_KEY,
	TRAFFIC_SOURCE_DETAIL_KEY,
	LONG_NBR,
	SOCIAL_ENGMT_TYP,
	TRAFFIC_SOURCE_KEY,
	SOURCE_TOTAL_TM_ON_SCRN_CNT,
	SOURCE_TOTAL_TRX_CNT,
	CLIENT_ID,
	VISIT_ID,
	SOURCE_TOTAL_UNIQUE_SCRN_VIEW_CNT,
	VISIT_START_TM,
	VISIT_START_TS,
	UPDATE_DTTM,
	SOURCE_TOTAL_BOUNCE_CNT,
	UPDATE_ID
) as SELECT
                               BRAND_ID, BUSINESS_DT_KEY, LOAD_ID, LOAD_TYP, SOURCE_TOTAL_SCRN_VIEW_CNT, CUSTOMER_KEY, DEVICE_KEY, USER_GEO_NTWK_LOC_KEY, CUSTOMER_ID, LOAD_DTTM, MOBILE_KEY, SOURCE_TRX_REVENUE_CNT, BROWSER_KEY, LAT_NBR, SOURCE_TOTAL_NEW_VISIT_CNT, SOURCE_TOTAL_HIT_CNT, VISIT_NBR, CITY_ID, FULL_VISITOR_ID, SOURCE_TOTAL_VISIT_CNT, CAMPAIGN_CD, DATASET_ID, STORE_KEY, SOURCE_TOTAL_PAGE_VIEW_CNT, SOURCE_TOTAL_SESSION_QTY_DIM_CNT, SOURCE_TOTAL_TM_ONSITE_CNT, USER_KEY, TRAFFIC_SOURCE_DETAIL_KEY, LONG_NBR, SOCIAL_ENGMT_TYP, TRAFFIC_SOURCE_KEY, SOURCE_TOTAL_TM_ON_SCRN_CNT, SOURCE_TOTAL_TRX_CNT, CLIENT_ID, VISIT_ID, SOURCE_TOTAL_UNIQUE_SCRN_VIEW_CNT, VISIT_START_TM,VISIT_START_TS, UPDATE_DTTM, SOURCE_TOTAL_BOUNCE_CNT, UPDATE_ID
                            FROM IDM_DEV.CBA."SESSION_SUMMARY_FACT";
create view IF NOT EXISTS TRAFFIC_SOURCE_DETAIL_DIM_BV(
	AD_CONTENT_NM,
	IS_TRUE_DIRECT_IND,
	INFO_TGTNG_CRITERIA_BOOM_USER_LIST_ID,
	LOAD_DTTM,
	INFO_CRITERIA_ID,
	INFO_CAMPAIGN_ID,
	INFO_PAGE_NBR,
	INFO_SLOT_NBR,
	INFO_CRITERIA_PARAM_VAL,
	INFO_IS_VIDEO_AD_IND,
	INFO_AD_GROUP_ID,
	UPDATE_DTTM,
	UPDATE_ID,
	INFO_CREATIVE_ID,
	KEYWORD_VAL,
	INFO_AD_NTWK_TYP,
	INFO_GCL_ID,
	LOAD_ID,
	TRAFFIC_SOURCE_DETAIL_KEY,
	INFO_CUST_ID,
	LOAD_TYP,
	REFERRAL_PATH_TXT
) as SELECT
                               AD_CONTENT_NM, IS_TRUE_DIRECT_IND, INFO_TGTNG_CRITERIA_BOOM_USER_LIST_ID, LOAD_DTTM, INFO_CRITERIA_ID, INFO_CAMPAIGN_ID, INFO_PAGE_NBR, INFO_SLOT_NBR, INFO_CRITERIA_PARAM_VAL, INFO_IS_VIDEO_AD_IND, INFO_AD_GROUP_ID, UPDATE_DTTM, UPDATE_ID, INFO_CREATIVE_ID, KEYWORD_VAL, INFO_AD_NTWK_TYP, INFO_GCL_ID, LOAD_ID, TRAFFIC_SOURCE_DETAIL_KEY, INFO_CUST_ID, LOAD_TYP, REFERRAL_PATH_TXT
                            FROM IDM_DEV.CBA."TRAFFIC_SOURCE_DETAIL_DIM";
create view IF NOT EXISTS TRAFFIC_SOURCE_DIM_BV(
	TRAFFIC_SOURCE_KEY,
	UPDATE_DTTM,
	LOAD_ID,
	SOURCE_NM,
	CHANNEL_GROUP_TYP,
	LOAD_TYP,
	MEDIUM_NM,
	LOAD_DTTM,
	CAMPAIGN_NM,
	UPDATE_ID
) as SELECT
                               TRAFFIC_SOURCE_KEY, UPDATE_DTTM, LOAD_ID, SOURCE_NM, CHANNEL_GROUP_TYP, LOAD_TYP, MEDIUM_NM, LOAD_DTTM, CAMPAIGN_NM, UPDATE_ID
                            FROM IDM_DEV.CBA."TRAFFIC_SOURCE_DIM";
create view IF NOT EXISTS USER_DIM_BV(
	USER_KEY,
	LOAD_DTTM,
	UPDATE_DTTM,
	LOAD_TYP,
	USER_ID,
	LOAD_ID,
	UPDATE_ID
) as SELECT
                               USER_KEY, LOAD_DTTM, UPDATE_DTTM, LOAD_TYP, USER_ID, LOAD_ID, UPDATE_ID
                            FROM IDM_DEV.CBA."USER_DIM";
create view IF NOT EXISTS USER_GEO_NTWK_LOC_DIM_BV(
	CONT_NM,
	SUBCONT_NM,
	CNTRY_NM,
	UPDATE_ID,
	REGION_NM,
	LOAD_ID,
	USER_GEO_NTWK_LOC_KEY,
	CITY_NM,
	METRO_NM,
	UPDATE_DTTM,
	LOAD_TYP,
	LOAD_DTTM
) as SELECT
                               CONT_NM, SUBCONT_NM, CNTRY_NM, UPDATE_ID, REGION_NM, LOAD_ID, USER_GEO_NTWK_LOC_KEY, CITY_NM, METRO_NM, UPDATE_DTTM, LOAD_TYP, LOAD_DTTM
                            FROM IDM_DEV.CBA."USER_GEO_NTWK_LOC_DIM";