# General Parameters

spark.kafkabrokers 10.9.100.157:9092,10.9.100.142:9092,10.9.100.37:9092 

#spark.kafkabrokers 10.9.100.157:9097,10.9.100.142:9097,10.9.100.37:9097 
spark.truststore /etc/script_keystore/dxp.kafka.client.truststore.AWS.shore.jks
spark.keystore /etc/script_keystore/dxp.kafka.client.keystore.AWS.shore.jks
spark.passvalue SetS@!l2o2o
spark.debug.option TRUE
spark.mpx.consumer spark-consumer-100
spark.src.kafkatopic qa-ship-pos-mxp.pos-items
spark.src.personOffSet earliest

spark.src.config.id PITEMSSRC111
spark.voyage.id VOYAGE100
spark.tgt.env QA
spark.target.config.id PITEMSTGT222

#hive
spark.target.location  s3a://vv-qa-emr-cluster/data/nbx/hive/landing/hvtb_lnd_mxp_qa_ship_pos_mxp_pos_items
spark.target.hive.table shipdw.hvtb_lnd_mxp_qa_ship_pos_mxp_sales_stream_mxp

#Hbase
spark.target.table.format org.apache.phoenix.spark
spark.target.offset.mode overwrite 
spark.target.offset.table HBTB_STREAMING_NBX_INGESTION_OFFSET
spark.target.ops.table.format org.apache.phoenix.spark
spark.target.ops.table.mode overwrite
spark.target.enablerops_table HBTB_NBX_OPS_METADATA 
spark.target.zkurl q-lab-hdp-ada1.virginvoyages.qa.dev:2181/hbase-secure:nbx.service@VIRGINVOYAGES.QA.DEV:/home/nbx.service/nbx.keytab
spark.kafka.zookeeper 10.9.100.157:2181
  