# General Parameters
spark.kafkabrokers 10.9.100.157:9092,10.9.100.142:9092,10.9.100.37:9092 
spark.debug.option TRUE
spark.mpx.consumer spark-consumer-100
spark.src.kafkatopic dev-ship-pos-mxp.sales-stream
spark.src.personOffSet earliest

spark.src.config.id PSALESSRC222
spark.voyage.id VOYAGE100
spark.tgt.env QA
spark.target.config.id PSALESTGT222

#hive

spark.target.location s3a://vv-dev-emr-cluster/data/core/nbx/hive/landing/hvtb_lnd_mxp_ship_pos_mxp_sales_stream_mxp
spark.target.hive.table shipdw.hvtb_lnd_mxp_ship_pos_mxp_sales_stream_mxp


#Hbase
spark.target.table.format org.apache.phoenix.spark
spark.target.offset.mode overwrite 
spark.target.offset.table HBTB_STREAMING_NBX_INGESTION_OFFSET
spark.target.ops.table.format org.apache.phoenix.spark
spark.target.ops.table.mode overwrite
spark.target.enablerops_table HBTB_NBX_OPS_METADATA 
spark.target.zkurl ip-10-4-100-118.seatrials.virginvoyages.com:2181
spark.kafka.zookeeper 10.9.100.157:2181
  