create sequence IF NOT EXISTS CMX_RESTAURANT_AUDIT_REPORT_TAG_AGG_SEQ start with 1 increment by 1;
create TABLE IF NOT EXISTS CMX_RESTAURANT_AUDIT_REPORT_TAG_AGG (
	BRAND_ID VARCHAR(16777216) NOT NULL COMMENT 'Brand Identifier specifies the code which represents an organization. The identifier should be in all capital letters. Sample codes are irb (Inspire Recognized Brands), bww(Buffalo Wild Wing), arbys (Arbys),  dnkn  (Dunkin), etc.',
	CMX_ID VARCHAR(16777216) NOT NULL COMMENT 'CMX Identifier appears to uniquely identify the attribute combinations of group_name, report_tag, core_audit_service_service_name, and parent_item_id from the raw table. Sample values a7d51eab-f91e-4c98-91b3-510abf4b8bb0 and 7dbbab8a-484a-45a1-9fab-e8e4d070a202.',
	CMX_AUDIT_ID VARCHAR(16777216) NOT NULL COMMENT 'CMX Audit Identifier  Sample values str-65f32bfe45b148cd9b541450fa2349a7 and str-ccf32239a76247a48231c223a00c9382.',
	STORE_ID VARCHAR(16777216) COMMENT 'Store Identifier is an integer that uniquely identifies the store.',
	AUDIT_DT DATE COMMENT 'Audit Date is the day of the audit.',
	CMX_AUDIT_SERVICE_NM VARCHAR(16777216) COMMENT 'CMX Audit Service Name is a label for a type of audit. Sample values CTR PRE-Certification Audit, EcoSure (Self Assessment) 2021, and NCTR Certification Audit.',
	CMX_AUDIT_SERVICE_VERSION_NBR NUMBER(38,0) COMMENT 'CMX Audit Service Version Number is the version of an audit.',
	CMX_GROUP_NM VARCHAR(16777216) COMMENT 'CMX Group Name is a high level categorization of questions. Sample values ARBY''S STANDARDS, FOOD SAFETY, and GUEST EXPERIENCE.',
	CMX_GROUP_POINT_QTY NUMBER(38,0) COMMENT 'CMX Group Point Quantity is the number of points for an audit that a restaraunt recieved at the Group Level.',
	CMX_GROUP_MAXIMUM_POINT_QTY NUMBER(38,0) COMMENT 'CMX Group Maximum Point Quantity is the maximum number of points for an audit that a restaraunt may receive at the Group Level.',
	CMX_GROUP_VAL FLOAT COMMENT 'CMX Group Value  is a calculated value fromGroup Point Quantity and Group Maximum Point Quantity and store the percentage calculation. Examples of values are 93.32 and 87.65.',
	CMX_REPORT_TAG_NM VARCHAR(16777216) COMMENT 'CMX Report Tag is a further categorization of audit question within a Group. NameSample values Building/Equipment/OSM Standards, Menu/Marketing, Equipment, Team Practices, Accuracy, and Cleanliness- Guest View.',
	CMX_REPORT_TAG_POINT_QTY NUMBER(38,0) COMMENT 'CMX Report Tag Point Quantity is the number of points for an audit that a restaraunt recieved at the Group/Report Tag Level.',
	CMX_REPORT_TAG_MAXIMUM_POINT_QTY NUMBER(38,0) COMMENT 'CMX Report Tag Maximum Point Quantity is the maximum number of points for an audit that a restaraunt may receive at the Group/Report Tag  Level.',
	CMX_REPORT_TAG_VAL FLOAT COMMENT 'CMX Report Tag Value is a calculated value from Report Tag Point Quantity and Report Tag Maximum Point Quantity and store the percentage calculation. Examples of values are 93.32 and 87.65.',
	SOURCE_SYSTEM_NM VARCHAR(255) NOT NULL COMMENT 'Source System Name specifies the origin of the data. For example, Salesforce Marketing App or Netsuite. Some systems will have a reference table where sources are identified by integers such as 1,2,3, etc.',
	LOAD_ID NUMBER(38,0) COMMENT 'Load Identifier specifies the Batch that inserted the record into the table.',
	LOAD_DTTM TIMESTAMP_NTZ(9) COMMENT 'Load Datetime is the date and time in UTC when the record was created. For example, 2021-08-11T15:02:24Z.',
	UPDATE_ID NUMBER(38,0) COMMENT 'Update Identifier specifies the batch id used for the update of the record.',
	UPDATE_DTTM TIMESTAMP_NTZ(9) COMMENT 'Update Datetime is the date and time in UTC when the record was last updated. For example, 2021-08-11T15:02:24Z.',
	constraint XPKCMX_RESTAURANT_AUDIT_REPORT_TAG_AGG primary key (BRAND_ID, CMX_ID, CMX_AUDIT_ID)
)COMMENT='CMX Restaurant Audit Report Tag Agg is CMX audit aggregated data at the Group/Report Tag level.'
;
create TABLE IF NOT EXISTS DIM_RESTAURANT (
	RESTAURANT_KEY NUMBER(38,0) NOT NULL,
	REST_NUMBER VARCHAR(10),
	REST_NAME VARCHAR(255),
	REST_STATUS VARCHAR(10),
	REST_TYPE VARCHAR(10),
	REST_FRAN_NUMBER NUMBER(18,0),
	REST_FRAN_NAME VARCHAR(255),
	REST_FRANENTITY_NUMBER NUMBER(18,0),
	REST_FRANENTITY_NAME VARCHAR(255),
	REST_COMPANY_NAME VARCHAR(255),
	REST_BRAND_NAME VARCHAR(255),
	REST_BRAND_ISACTIVE BOOLEAN,
	REST_DMA_CODE NUMBER(38,0),
	REST_DMA_DESC VARCHAR(100),
	REST_ISAIRPORT BOOLEAN,
	REST_ISVIDEOSURV BOOLEAN,
	REST_ISBREAKFAST BOOLEAN,
	REST_IS24HR BOOLEAN,
	REST_ISMALL BOOLEAN,
	REST_ISDRIVETHRU BOOLEAN,
	REST_ADDRLINE1 VARCHAR(255),
	REST_ADDRLINE2 VARCHAR(255),
	REST_ADDRLINE3 VARCHAR(255),
	REST_ADDRCITY VARCHAR(255),
	REST_ADDRCOUNTY VARCHAR(255),
	REST_ADDRSTATE VARCHAR(2),
	REST_ADDRPROVINCE VARCHAR(25),
	REST_ADDRZIP VARCHAR(10),
	REST_COUNTRY VARCHAR(10),
	REST_ADDRPHONE VARCHAR(25),
	REST_LANDLORDPHONE VARCHAR(25),
	REST_ALERTCCEMAIL VARCHAR(8000),
	REST_DIVISION VARCHAR(50),
	REST_LATITUDE VARCHAR(55),
	REST_LONGITUDE VARCHAR(55),
	REST_BUILDINGTYPE VARCHAR(55),
	REST_REMODELPROG_NAME VARCHAR(255),
	REST_REMODELDT NUMBER(38,0),
	REST_ACQUISITIONDT NUMBER(38,0),
	REST_POSTYPE VARCHAR(55),
	REST_COMP_ISELIGIBLE BOOLEAN,
	REST_COMP_ISTEMPCLOSURE BOOLEAN,
	REST_COMP_DATE DATE,
	REST_OPENDATE DATE,
	REST_TEMP_CLOSEDATE DATE,
	REST_TEMP_OPENDATE DATE,
	REST_TEMPCLOSUREREASON VARCHAR(255),
	REST_CLOSEDATE DATE,
	REST_FACILITYTYPE VARCHAR(55),
	REST_SITETYPE VARCHAR(20),
	REST_TIMEZONE VARCHAR(100),
	REST_SYSTEM_TIMEZONE VARCHAR(100),
	REST_UNITTRADEAREA VARCHAR(100),
	REST_SEATCOUNT NUMBER(38,0),
	REST_PARKINGCOUNT NUMBER(38,0),
	REST_SQUAREFT VARCHAR(55),
	REST_CSRASSIGNED_NAME VARCHAR(255),
	REST_CSRASSIGNED_EMAIL VARCHAR(100),
	REST_CSRDEFAULT_NAME VARCHAR(255),
	REST_CSRDEFAULT_EMAIL VARCHAR(100),
	REST_DISTCENTER_NAME VARCHAR(255),
	REST_DISTACCOUNT_NUMBER VARCHAR(25),
	REST_BAKERY_NAME VARCHAR(255),
	REST_LICENSE_NUMBER VARCHAR(55),
	REST_LICENSEEXECDATE NUMBER(38,0),
	REST_LICENSEEXPDATE NUMBER(38,0),
	REST_AFA_PERC NUMBER(10,4),
	REST_ROYALTY_PER NUMBER(10,4),
	REST_L1EMAIL VARCHAR(100),
	REST_L2NAME VARCHAR(255),
	REST_L2EMAIL VARCHAR(100),
	REST_L2PHONE VARCHAR(25),
	REST_L3NAME VARCHAR(255),
	REST_L3EMAIL VARCHAR(100),
	REST_L3PHONE VARCHAR(25),
	REST_L4NAME VARCHAR(255),
	REST_L4EMAIL VARCHAR(100),
	REST_L4PHONE VARCHAR(25),
	REST_L5NAME VARCHAR(255),
	REST_L5EMAIL VARCHAR(100),
	REST_L5PHONE VARCHAR(25),
	REST_L6NAME VARCHAR(255),
	REST_L6EMAIL VARCHAR(100),
	REST_L6PHONE VARCHAR(25),
	ARG_AREA_NUMBER VARCHAR(55),
	ARG_AREA_DESC VARCHAR(255),
	ARG_AREA_NAME VARCHAR(255),
	ARG_AREA_NUMBER_ABBR VARCHAR(3),
	ARG_DISTRICT_NUMBER VARCHAR(55),
	ARG_DISTRICT_DESC VARCHAR(255),
	ARG_DISTRICT_NAME VARCHAR(255),
	ARG_DISTRICT_NUMBER_ABBR VARCHAR(3),
	ARG_SUBREGION_NUMBER VARCHAR(55),
	ARG_SUBREGION_DESC VARCHAR(255),
	ARG_SUBREGION_NAME VARCHAR(255),
	ARG_SUBREGION_NUMBER_ABBR VARCHAR(3),
	ARG_REGION_NUMBER VARCHAR(55),
	ARG_REGION_DESC VARCHAR(255),
	ARG_REGION_NAME VARCHAR(255),
	ARG_REGION_NUMBER_ABBR VARCHAR(3),
	ARG_AREA_SUPERVISOR VARCHAR(255),
	ARG_AREA_SUPERVISOR_EMAIL VARCHAR(100),
	ARG_AREA_SUPERVISOR_PHONE VARCHAR(25),
	ARG_DO_NAME VARCHAR(255),
	ARG_DO_EMAIL VARCHAR(100),
	ARG_DO_PHONE VARCHAR(25),
	ARG_VPO_NAME VARCHAR(255),
	ARG_VPO_EMAIL VARCHAR(100),
	ARG_VPO_PHONE VARCHAR(25),
	ARG_SVP_NAME VARCHAR(255),
	ARG_SVP_EMAIL VARCHAR(100),
	ARG_SVP_PHONE VARCHAR(25),
	FRAN_TC_NAME VARCHAR(255),
	FRAN_TC_EMAIL VARCHAR(100),
	FRAN_OC_NAME VARCHAR(255),
	FRAN_OC_EMAIL VARCHAR(100),
	FRAN_DFO_NAME VARCHAR(255),
	FRAN_DFO_EMAIL VARCHAR(100),
	FRAN_CONTACT_NAME VARCHAR(255),
	FRAN_EMAIL VARCHAR(100),
	FRAN_PHONE1 VARCHAR(25),
	FRAN_PHONE2 VARCHAR(25),
	FRAN_ADDRLINE1 VARCHAR(255),
	FRAN_ADDRCITY VARCHAR(255),
	FRAN_ADDRSTATE VARCHAR(2),
	FRAN_ADDRZIP VARCHAR(10),
	FRAN_ADDRCOUNTRY VARCHAR(10),
	EFFECTIVE_BEGIN_DATE DATE NOT NULL,
	EFFECTIVE_END_DATE DATE NOT NULL,
	ISCURRENT BOOLEAN NOT NULL,
	INFERRED_FLAG BOOLEAN,
	SOURCE_LOAD_ID NUMBER(38,0) NOT NULL COMMENT 'SOURCE_LOAD_ID is the LOAD_ID from the source system.',
	SOURCE_LAST_UPDATE_DATE_TIME TIMESTAMP_NTZ(9) NOT NULL COMMENT 'SOURCE_LAST_UPDATE_DATE_TIME is the LAST_UPDATE_DATE_TIME from the source system.',
	SOURCE_SYSTEM_NM VARCHAR(255) NOT NULL COMMENT 'Source System Name specifies the origin of the data. For example, Salesforce Marketing App or Netsuite. Some systems will have a reference table where sources are identified by integers such as 1,2,3, etc.',
	BRAND_ID VARCHAR(16777216) NOT NULL COMMENT 'Brand Identifier specifies the code which represents an organization. The identifier should be in all capital letters. Sample codes are irb (Inspire Recognized Brands), bww(Buffalo Wild Wing), arbys (Arbys),  dnkn  (Dunkin), etc.',
	LOAD_ID NUMBER(38,0) COMMENT 'Load Identifier specifies the Batch that inserted the record into the table.',
	LOAD_DTTM TIMESTAMP_NTZ(9) COMMENT 'Load Datetime is the date and time in UTC when the record was created. For example, 2021-08-11T15:02:24Z.',
	UPDATE_ID NUMBER(38,0) COMMENT 'Update Identifier specifies the batch id used for the update of the record.',
	UPDATE_DTTM TIMESTAMP_NTZ(9) COMMENT 'Update Datetime is the date and time in UTC when the record was last updated. For example, 2021-08-11T15:02:24Z.',
	constraint XPKDIM_RESTAURANT primary key (RESTAURANT_KEY)
)COMMENT='DIM_RESTAURANT is short term solution in order to provide certain restaurant attributes until they can be incorporat6ed into long term tables.'
;
create TABLE IF NOT EXISTS ECOSURE_RESTAURANT_AUDIT (
	BRAND_ID VARCHAR(16777216) NOT NULL COMMENT 'Brand Identifier specifies the code which represents an organization. The identifier should be in all capital letters. Sample codes are irb (Inspire Recognized Brands), bww(Buffalo Wild Wing), arbys (Arbys),  dnkn  (Dunkin), etc.',
	ECOSURE_AUDIT_ID NUMBER(38,0) NOT NULL COMMENT 'Ecosure Audit Identifier is a unique integer value to identify an audit.',
	AUDIT_DT DATE NOT NULL COMMENT 'Audit Date is the day of the audit.',
	ECOSURE_CONCEPT_NBR VARCHAR(16777216) COMMENT 'ECOSURE CONCEPT NUMBER is a location attribute. Sample value ARB.',
	STORE_ID VARCHAR(16777216) COMMENT 'Store Identifier is an integer that uniquely identifies the store.',
	ECOSURE_AUDITOR_ID NUMBER(38,0) COMMENT 'ECOSURE AUDITOR IDENTIFIER uniquely identifies an indvidual auditor.',
	ECOSURE_CYCLE_QTY NUMBER(38,0) COMMENT 'ECOSURE CYCLE QUANTITY is the number of rounds of an audit.',
	ECOSURE_VISIT_QTY NUMBER(38,0) COMMENT 'ECOSURE VISIT QUANTITY is the count of visits within a cycle.',
	ECOSURE_REFERENCE_NBR VARCHAR(16777216) COMMENT 'ECOSURE REFERENCE NUMBER is the Internal EcoSure program number. Sample value AY2018.',
	ECOSURE_NOTE_TXT VARCHAR(16777216) COMMENT 'ECOSURE NOTE TEXT are audit level notes.',
	ECOSURE_STORE_ID NUMBER(38,0) COMMENT 'ECOSURE STORE IDENTIFIER si the unique EcoSure location id.',
	ECOSURE_FORM_NM VARCHAR(16777216) COMMENT 'ECOSURE FORM NAME is the program audit form name. Sample value Arby''s Safety First (S).',
	SOURCE_SYSTEM_NM VARCHAR(255) NOT NULL COMMENT 'Source System Name specifies the origin of the data. For example, Salesforce Marketing App or Netsuite. Some systems will have a reference table where sources are identified by integers such as 1,2,3, etc.',
	LOAD_ID NUMBER(38,0) COMMENT 'Load Identifier specifies the Batch that inserted the record into the table.',
	LOAD_DTTM TIMESTAMP_NTZ(9) COMMENT 'Load Datetime is the date and time in UTC when the record was created. For example, 2021-08-11T15:02:24Z.',
	UPDATE_ID NUMBER(38,0) COMMENT 'Update Identifier specifies the batch id used for the update of the record.',
	UPDATE_DTTM TIMESTAMP_NTZ(9) COMMENT 'Update Datetime is the date and time in UTC when the record was last updated. For example, 2021-08-11T15:02:24Z.',
	constraint XPKECOSURE_RESTAURANT_AUDIT primary key (BRAND_ID, ECOSURE_AUDIT_ID)
)COMMENT='ECOSURE_RESTAURANT_AUDIT identifies the audit level information for a particular store that is sourced from ECOSURE.'
;
create TABLE IF NOT EXISTS ECOSURE_RESTAURANT_AUDIT_SCORE (
	BRAND_ID VARCHAR(16777216) NOT NULL COMMENT 'Brand Identifier specifies the code which represents an organization. The identifier should be in all capital letters. Sample codes are irb (Inspire Recognized Brands), bww(Buffalo Wild Wing), arbys (Arbys),  dnkn  (Dunkin), etc.',
	ECOSURE_AUDIT_ID NUMBER(38,0) NOT NULL COMMENT 'Ecosure Audit Identifier is a unique integer value to identify an audit.',
	ECOSURE_SCORE_NM VARCHAR(16777216) NOT NULL COMMENT 'ECOSURE SCORE NAME is the label for the score. Sample value: Overall Score.',
	ECOSURE_SCORE_AMT FLOAT COMMENT 'ECOSURE SCORE AMOUNT is a decimal value from 0 to 100. Sample Values 93.4, 82, and 62.8.',
	ECOSURE_RATING_VAL VARCHAR(16777216) COMMENT 'ECOSURE RATING VALUE a single letter value denoting the score. Sample Values A, B, C, and F.',
	ECOSURE_IN_COMPLIANCE_QTY NUMBER(38,0) COMMENT 'ECOSURE IN COMPLIANCE QUANTITY is the count of items in compliance.',
	ECOSURE_OUT_OF_COMPLIANCE_QTY NUMBER(38,0) COMMENT 'ECOSURE OUT OF COMPLIANCE QUANTITY  is the count of items in out of compliance.',
	SOURCE_SYSTEM_NM VARCHAR(255) NOT NULL COMMENT 'Source System Name specifies the origin of the data. For example, Salesforce Marketing App or Netsuite. Some systems will have a reference table where sources are identified by integers such as 1,2,3, etc.',
	LOAD_ID NUMBER(38,0) COMMENT 'Load Identifier specifies the Batch that inserted the record into the table.',
	LOAD_DTTM TIMESTAMP_NTZ(9) COMMENT 'Load Datetime is the date and time in UTC when the record was created. For example, 2021-08-11T15:02:24Z.',
	UPDATE_ID NUMBER(38,0) COMMENT 'Update Identifier specifies the batch id used for the update of the record.',
	UPDATE_DTTM TIMESTAMP_NTZ(9) COMMENT 'Update Datetime is the date and time in UTC when the record was last updated. For example, 2021-08-11T15:02:24Z.',
	constraint XPKECOSURE_RESTAURANT_AUDIT_SCORE primary key (BRAND_ID, ECOSURE_AUDIT_ID, ECOSURE_SCORE_NM),
	constraint ECOSURE_RESTAURANT_AUDIT_TO_SCORE foreign key (BRAND_ID, ECOSURE_AUDIT_ID) references ECOSURE_RESTAURANT_AUDIT(BRAND_ID,ECOSURE_AUDIT_ID)
)COMMENT='ECOSURE_RESTAURANT_AUDIT SCORE contains the scores at an audit aggregate level for a store that is sourced from ECOSURE.'
;
create TABLE IF NOT EXISTS FLYWAY_SCHEMA_HISTORY (
	INSTALLED_RANK NUMBER(38,0) NOT NULL,
	VERSION VARCHAR(50),
	DESCRIPTION VARCHAR(200),
	TYPE VARCHAR(20) NOT NULL,
	SCRIPT VARCHAR(1000) NOT NULL,
	CHECKSUM NUMBER(38,0),
	INSTALLED_BY VARCHAR(100) NOT NULL,
	INSTALLED_ON TIMESTAMP_LTZ(9) NOT NULL DEFAULT CURRENT_TIMESTAMP(),
	EXECUTION_TIME NUMBER(38,0) NOT NULL,
	SUCCESS BOOLEAN NOT NULL,
	primary key (INSTALLED_RANK)
);