dag_config:
  dag_id: 'E2E_SALES_RECON_SDI_BOS_INFOR_MICROS_MASTER'
  default_args:
    'owner': 'SALESRECON'
    'email': ['theja.h@inspirebrands.com','murugan.thirunavukar@inspirebrands.com']
    'email_on_failure': True
    'depends_on_past': False
    'retries' : 0
    schedule_interval: '15 9 * * *'
  doc_md: |-
    ### Master DAG
    This DAG is responsible for triggering the other transaction DAGs for procesing  data
  tags: ['SALESRECON_SONIC', 'SDI', 'BOS', 'MASTERDAG']
  catchup : False
  
child_dags:
  E2E_SALES_RECON_SDI_BOS_INFOR_MICROS_ADLS_TO_RDS: 'E2E_SALES_RECON_SDI_BOS_INFOR_MICROS_ADLS_TO_RDS'
  E2E_SALES_RECON_SDI_BOS_INFOR_MICROS_RDS_TO_IDS_DAILY: 'E2E_SALES_RECON_SDI_BOS_INFOR_MICROS_RDS_TO_IDS_DAILY'
  E2E_SALES_RECON_SDI_BOS_INFOR_MICROS_IDS_TO_IDS_WEEKLY: 'E2E_SALES_RECON_SDI_BOS_INFOR_MICROS_IDS_TO_IDS_WEEKLY'
  E2E_SALES_RECON_SDI_POS_PAID_IN_OUT_IDS_TO_IDS_DAILY_WEEKLY: 'E2E_SALES_RECON_SDI_POS_PAID_IN_OUT_IDS_TO_IDS_DAILY_WEEKLY'
  E2E_SALES_RECON_SDI_BOS_INFOR_MICROS_DQ: 'E2E_SALES_RECON_SDI_BOS_INFOR_MICROS_DQ'