create sequence IF NOT EXISTS BROWSER_SEQ start with 1 increment by 1;
create sequence IF NOT EXISTS DEVICE_SEQ start with 1 increment by 1;
create sequence IF NOT EXISTS GEO_NETWORK_LOC_SEQ start with 1 increment by 1;
create sequence IF NOT EXISTS MOBILE_SEQ start with 1 increment by 1;
create sequence IF NOT EXISTS TRAFFIC_SOURCE_DETAIL_SEQ start with 1 increment by 1;
create sequence IF NOT EXISTS TRAFFIC_SOURCE_SEQ start with 1 increment by 1;
create sequence IF NOT EXISTS USER_SEQ start with 1 increment by 1;
create TABLE IF NOT EXISTS BROWSER_DIM (
	BROWSER_KEY NUMBER(38,0) NOT NULL COMMENT 'This is unique Identifier for a Browser, This is a sorrogate Key',
	BROWSER_TYP VARCHAR(16777216) COMMENT 'The browser used (e.g., \"Chrome\" or \"Firefox\").\n',
	BROWSER_VERSION_NM VARCHAR(16777216) COMMENT 'The version of the browser used.\n',
	FLASH_VER_NBR VARCHAR(16777216) COMMENT 'The version of the Adobe Flash plugin that is installed on the browser.\n',
	BROWSER_SIZE_VAL VARCHAR(16777216) COMMENT 'The viewport size of users'' browsers. This captures the initial dimensions of the viewport in pixels and is formatted as width x height, for example, 1920x960.\n',
	JAVA_ENABLED_IND BOOLEAN COMMENT 'Whether or not Java is enabled in the browser.\n',
	LOAD_TYP VARCHAR(16777216) COMMENT 'Indicates whether data is part of a large historical data pull or was added from a smaller data pull (daily, weekly etc.) \n',
	LOAD_ID NUMBER(38,0) COMMENT ' Indicates whether data is part of a large historical data pull or was added from a smaller data pull (daily, weekly etc.) \n',
	LOAD_DTTM TIMESTAMP_NTZ(9) COMMENT '\nThe Date/Datetime the Record was Inserted',
	UPDATE_ID NUMBER(38,0) COMMENT 'This is the User Identifier of the Person or Process that Updated the Table',
	UPDATE_DTTM TIMESTAMP_NTZ(9) COMMENT 'The Date/Datetime the Record was Updated',
	constraint XPKBROWSER_DIMENSION primary key (BROWSER_KEY),
	constraint XAK1BROWSER_DIMENSION unique (BROWSER_TYP, BROWSER_VERSION_NM, BROWSER_SIZE_VAL, JAVA_ENABLED_IND, FLASH_VER_NBR)
)COMMENT='This section contains information about the User device browser information.'
;
create TABLE IF NOT EXISTS DEVICE_DIM (
	DEVICE_KEY NUMBER(38,0) NOT NULL COMMENT 'This is unique Identifier for a Device, This is a sorrogate Key',
	DEVICE_SCRN_RESOL_NM VARCHAR(16777216) NOT NULL COMMENT 'The resolution of the device''s screen, expressed in pixel width x height (e.g., \"800x600\").\n',
	DEVICE_LANG_NM VARCHAR(16777216) NOT NULL COMMENT 'The language the device is set to use. Expressed as the IETF language code.\n',
	DEVICE_CAT VARCHAR(16777216) NOT NULL COMMENT 'The type of device (Mobile, Tablet, Desktop).\n',
	OS_TYP VARCHAR(16777216) COMMENT 'The operating system of the device (e.g., \"Macintosh\" or \"Windows\").\n',
	OS_VER_NBR VARCHAR(16777216) COMMENT 'The version of the operating system.\n\n',
	SCREEN_COLOR_TXT VARCHAR(16777216) COMMENT 'Number of colors supported by the display, expressed as the bit-depth (e.g., \"8-bit\", \"24-bit\", etc.).\n',
	LOAD_TYP VARCHAR(16777216) COMMENT 'Indicates whether data is part of a large historical data pull or was added from a smaller data pull (daily, weekly etc.) \n',
	LOAD_ID NUMBER(38,0) COMMENT ' Indicates whether data is part of a large historical data pull or was added from a smaller data pull (daily, weekly etc.) \n',
	LOAD_DTTM TIMESTAMP_NTZ(9) COMMENT '\nThe Date/Datetime the Record was Inserted',
	UPDATE_ID NUMBER(38,0) COMMENT 'This is the User Identifier of the Person or Process that Updated the Table',
	UPDATE_DTTM TIMESTAMP_NTZ(9) COMMENT 'The Date/Datetime the Record was Updated',
	constraint XPKDEVICE_DIMENSION primary key (DEVICE_KEY)
)COMMENT='This section contains information about the user devices.\n'
;
create TABLE IF NOT EXISTS FLYWAY_SCHEMA_HISTORY (
	INSTALLED_RANK NUMBER(38,0) NOT NULL,
	VERSION VARCHAR(50),
	DESCRIPTION VARCHAR(200),
	TYPE VARCHAR(20) NOT NULL,
	SCRIPT VARCHAR(1000) NOT NULL,
	CHECKSUM NUMBER(38,0),
	INSTALLED_BY VARCHAR(100) NOT NULL,
	INSTALLED_ON TIMESTAMP_LTZ(9) NOT NULL DEFAULT CURRENT_TIMESTAMP(),
	EXECUTION_TIME NUMBER(38,0) NOT NULL,
	SUCCESS BOOLEAN NOT NULL,
	primary key (INSTALLED_RANK)
);
create TABLE IF NOT EXISTS LOYALTY_ORDER_FACT (
	TRANSACTION_ID VARCHAR(16777216) NOT NULL COMMENT 'Unique ID for loyalty transaction',
	CUSTOMER_KEY NUMBER(38,0) COMMENT 'This is a sorrogate key for the Customer Dimension',
	STORE_KEY NUMBER(38,0),
	BUSINESS_DATE_KEY NUMBER(38,0),
	EMPLOYEE_KEY NUMBER(38,0),
	ORDER_ID VARCHAR(16777216) COMMENT 'OrderID uniquely defines each order for each brand',
	EMPLOYEE_ID VARCHAR(16777216) COMMENT 'ID of the employee who is serving a customer or who took the order',
	MEMBER_ID VARCHAR(16777216) COMMENT 'A unique ID that is internally generated any time a customer joins the loyalty program/system.',
	STORE_ID VARCHAR(16777216) COMMENT 'Store Number that uniquely identifies the store ( from FRM)',
	BRAND_ID VARCHAR(16777216) COMMENT 'Brand associated with the transaction ',
	BUSINESS_DT DATE COMMENT 'The Date of the Transaction',
	EMPLOYEE_NM VARCHAR(16777216) COMMENT 'Name of the staff Member serving the customer',
	CHECK_NBR VARCHAR(16777216) COMMENT 'This is an incremental number that starts at one each business day to record customer order. Number restarts from one each day.',
	MEMBER_CARD_NBR VARCHAR(16777216) COMMENT 'A loyalty number that is used to link a transaction to a customer’s loyalty profile',
	DOLLAR_NET_VALUE_AMT NUMBER(18,2) COMMENT 'Net Amount in dollar paid by the customer',
	ELIGIBLE_REVENUE_AMT NUMBER(18,2) COMMENT 'Amount that is eligible for loyalty rewards. There could be certain items within a transaction that don’t qualify for loyalty rewards.',
	ATTACHMENT_METHOD_TYP VARCHAR(16777216) COMMENT 'Channel through which loyalty rewards were linked to a profile. Ex: At store, POS or through customer service for missing transaction.',
	TRANSACTION_STATUS_TYP VARCHAR(16777216) COMMENT 'Transaction status, if the transaction is pending or closed',
	MEMBER_PHONE_NBR VARCHAR(16777216) COMMENT 'Phone number of the member collected during transaction',
	REASON_CD VARCHAR(16777216) COMMENT 'Reason why certain items disqualified from earning loyalty rewards.',
	MIN_DAY_PART_ID VARCHAR(16777216) COMMENT 'Breakfast, Lunch, Dinner are different Dayparts for restaurants. If an item is part of multiple dayparts, then the earliest daypart is considered for this field',
	MAX_DAY_PART_ID VARCHAR(16777216) COMMENT 'Breakfast ,Lunch, Dinner are different Dayparts for restaurants. If an item is part of multiple dayparts, then the latest daypart is considered for this field',
	SUSPENDED_TRANSACTION_ID VARCHAR(16777216) COMMENT 'A ID generated when a Loyalty transaction is suspended.\n\nMostly valid for BWWs',
	SUSPENDED_TRANSACTION_STATUS_IND BOOLEAN COMMENT 'The Status to indicate if the suspension is active or not.\n\nMostly valid for BWWs',
	SOURCE_SYSTEM_NM VARCHAR(16777216) COMMENT 'The POS System used to load the transaction  information\n',
	LOAD_TYP VARCHAR(16777216) COMMENT 'Indicates whether data is part of a large historical data pull or was added from a smaller data pull (daily, weekly etc.) \n',
	LOAD_ID VARCHAR(16777216) COMMENT ' Indicates whether data is part of a large historical data pull or was added from a smaller data pull (daily, weekly etc.) \n',
	LOAD_DTTM TIMESTAMP_NTZ(9) COMMENT '\nThe Date/Datetime the Record was Inserted',
	UPDATE_ID VARCHAR(16777216) COMMENT 'This is the User Identifier of the Person or Process that Updated the Table',
	UPDATE_DTTM TIMESTAMP_NTZ(9) COMMENT 'The Date/Datetime the Record was Updated',
	constraint XPKLOYALTY_ORDER_FACT primary key (TRANSACTION_ID)
);
create TABLE IF NOT EXISTS MOBILE_DIM (
	MOBILE_KEY NUMBER(38,0) NOT NULL COMMENT 'This is unique Identifier for a Mobile device, This is a sorrogate Key',
	MOBILE_DEVICE_MODEL_NBR VARCHAR(16777216) COMMENT 'The mobile device model.\n',
	MOBILE_DEVICE_INFO_NM VARCHAR(16777216) NOT NULL COMMENT 'The branding, model, and marketing name used to identify the mobile device.\n',
	MOBILE_DEVICE_MKT_NM VARCHAR(16777216) COMMENT 'The marketing name used for the mobile device.\n',
	MOBILE_DEVICE_BRANDING_NM VARCHAR(16777216) COMMENT 'The brand or manufacturer of the device.\n',
	MOBILE_INPUT_SELECTOR_NM VARCHAR(16777216) COMMENT 'Selector (e.g., touchscreen, joystick, clickwheel, stylus) used on the mobile device.\n',
	LOAD_TYP VARCHAR(16777216) COMMENT 'Indicates whether data is part of a large historical data pull or was added from a smaller data pull (daily, weekly etc.) \n',
	LOAD_ID NUMBER(38,0) COMMENT ' Indicates whether data is part of a large historical data pull or was added from a smaller data pull (daily, weekly etc.) \n',
	LOAD_DTTM TIMESTAMP_NTZ(9) COMMENT '\nThe Date/Datetime the Record was Inserted',
	UPDATE_ID NUMBER(38,0) COMMENT 'This is the User Identifier of the Person or Process that Updated the Table',
	UPDATE_DTTM TIMESTAMP_NTZ(9) COMMENT 'The Date/Datetime the Record was Updated',
	constraint XPKMOBILE_DIMENSION primary key (MOBILE_KEY),
	constraint XAK1MOBILE_DIMENSION unique (MOBILE_DEVICE_BRANDING_NM, MOBILE_INPUT_SELECTOR_NM, MOBILE_DEVICE_MKT_NM, MOBILE_DEVICE_MODEL_NBR, MOBILE_DEVICE_INFO_NM)
)COMMENT='This section contains information about the Mobile devices Information for a User.'
;
create TABLE IF NOT EXISTS SESSION_SUMMARY_FACT (
	BUSINESS_DT_KEY NUMBER(38,0) NOT NULL,
	TRAFFIC_SOURCE_KEY NUMBER(38,0) NOT NULL COMMENT 'This is unique Identifier for a Traffic Source, This is a sorrogate Key',
	DEVICE_KEY NUMBER(38,0) NOT NULL COMMENT 'This is unique Identifier for a Device, This is a sorrogate Key',
	USER_GEO_NTWK_LOC_KEY NUMBER(38,0) NOT NULL COMMENT 'This is the Sorrogate Key for the Network Location Dimension Junk Table',
	TRAFFIC_SOURCE_DETAIL_KEY NUMBER(38,0) NOT NULL COMMENT 'This is unique Identifier for a Traffic Source Detail, This is a sorrogate Key',
	USER_KEY NUMBER(38,0) NOT NULL COMMENT 'This is unique Identifier for a User, This is a sorrogate Key',
	BROWSER_KEY NUMBER(38,0) NOT NULL COMMENT 'This is unique Identifier for a Browser, This is a sorrogate Key',
	MOBILE_KEY NUMBER(38,0) NOT NULL COMMENT 'This is unique Identifier for a Mobile device, This is a sorrogate Key',
	BRAND_ID VARCHAR(16777216) NOT NULL COMMENT 'Brand Identifier specifies the code which represents an organization. The identifier should be in all capital letters. Sample codes are IRB (Inspire Recognized Brands), BWW (Buffalo Wild Wing), DNKN  (Dunkin), etc.',
	DATASET_ID VARCHAR(16777216) COMMENT 'This is the Dataset Identifier from Google Analytics',
	CUSTOMER_KEY NUMBER(38,0) COMMENT 'This is a sorrogate key for the Customer Dimension',
	STORE_KEY NUMBER(38,0) NOT NULL,
	FULL_VISITOR_ID VARCHAR(150) NOT NULL COMMENT 'The unique visitor ID (also known as client ID).\n',
	VISIT_ID NUMBER(38,0) NOT NULL COMMENT 'An identifier for this session. This is part of the value usually stored as the _utmb cookie. This is only unique to the user. For a completely unique ID, you should use a combination of fullVisitorId and visitId.\n',
	CUSTOMER_ID VARCHAR(16777216) COMMENT 'This is the Business Key for Customer Dimension. This is the Unique Customer Identifier from the Source\n',
	CLIENT_ID VARCHAR(150) COMMENT 'Unhashed version of the Client ID for a given user associated with any given visit/session.\n',
	VISIT_NBR NUMBER(38,0) NOT NULL COMMENT 'The session number for this user. If this is the first session, then this is set to 1.\n',
	CITY_ID VARCHAR(16777216) COMMENT 'Users'' city ID, derived from their IP addresses or Geographical IDs. The city IDs are the same as the Criteria IDs found at https://developers.google.com/         analytics/devguides/collection/         protocol/v1/geoid.\n',
	VISIT_START_TM TIME(9) NOT NULL COMMENT 'The timestamp (expressed as POSIX time).\n',
	VISIT_START_TS TIMESTAMP_NTZ(9) COMMENT 'The timestamp (expressed as POSIX time).\n',
	SOCIAL_ENGMT_TYP VARCHAR(150) COMMENT 'Engagement type, either \"Socially Engaged\" or \"Not Socially Engaged\".\n',
	CAMPAIGN_CD VARCHAR(16777216) COMMENT 'Value of the utm_id campaign tracking parameter, used for manual campaign tracking.\n',
	SOURCE_TOTAL_VISIT_CNT NUMBER(38,0) COMMENT 'Total number of new users in session (for convenience). If this is the first visit, this value is 1, otherwise it is null.\n',
	SOURCE_TOTAL_HIT_CNT NUMBER(38,0) COMMENT 'Total number of hits within the session.\n',
	SOURCE_TOTAL_PAGE_VIEW_CNT NUMBER(38,0) COMMENT 'Total number of pageviews within the session.\n',
	SOURCE_TOTAL_TM_ONSITE_CNT NUMBER(38,0) COMMENT 'Total time of the session expressed in seconds.\n',
	SOURCE_TOTAL_BOUNCE_CNT NUMBER(38,0) COMMENT 'Total bounces (for convenience). For a bounced session, the value is 1, otherwise it is null.\n',
	SOURCE_TOTAL_TRX_CNT NUMBER(38,0) COMMENT 'Total number of ecommerce transactions within the session.\n',
	SOURCE_TOTAL_NEW_VISIT_CNT NUMBER(38,0) COMMENT 'The number of sessions (for convenience). This value is 1 for sessions with interaction events. The value is null if there are no interaction events in the session.\n',
	SOURCE_TOTAL_SCRN_VIEW_CNT NUMBER(38,0) COMMENT 'Total number of screenviews within the session.\n',
	SOURCE_TOTAL_UNIQUE_SCRN_VIEW_CNT NUMBER(38,0) COMMENT 'Total number of unique screenviews within the session.\n',
	SOURCE_TOTAL_TM_ON_SCRN_CNT NUMBER(38,0) COMMENT 'The total time on screen in seconds.\n',
	SOURCE_TRX_REVENUE_CNT NUMBER(38,0) COMMENT 'Total transaction revenue, expressed as the value passed to Analytics multiplied by 10^6 (e.g., 2.40 would be given as 2400000).\n',
	SOURCE_TOTAL_SESSION_QTY_DIM_CNT NUMBER(38,0) COMMENT 'An estimate of how close a particular session was to transacting, ranging from 1 to 100, calculated for each session. A value closer to 1 indicates a low session quality, or far from transacting, while a value closer to 100 indicates a high session quality, or very close to transacting. A value of 0 indicates that Session Quality is not calculated for the selected time range.\n',
	LAT_NBR VARCHAR(16777216) COMMENT 'The approximate latitude of users'' city, derived from their IP addresses or Geographical IDs. Locations north of the equator have positive latitudes and locations south of the equator have negative latitudes.\n',
	LONG_NBR VARCHAR(16777216) COMMENT 'The approximate longitude of users'' city, derived from their IP addresses or Geographical IDs. Locations east of the prime meridian have positive longitudes and locations west of the prime meridian have negative longitudes.\n',
	LOAD_TYP VARCHAR(16777216) COMMENT 'Indicates whether data is part of a large historical data pull or was added from a smaller data pull (daily, weekly etc.) \n',
	LOAD_ID NUMBER(38,0) COMMENT ' Indicates whether data is part of a large historical data pull or was added from a smaller data pull (daily, weekly etc.) \n',
	LOAD_DTTM TIMESTAMP_NTZ(9) COMMENT '\nThe Date/Datetime the Record was Inserted',
	UPDATE_ID NUMBER(38,0) COMMENT 'This is the User Identifier of the Person or Process that Updated the Table',
	UPDATE_DTTM TIMESTAMP_NTZ(9) COMMENT 'The Date/Datetime the Record was Updated',
	constraint XPKSESSION_SUMMARY_FACT primary key (BUSINESS_DT_KEY, TRAFFIC_SOURCE_KEY, DEVICE_KEY, USER_GEO_NTWK_LOC_KEY, BROWSER_KEY, MOBILE_KEY, TRAFFIC_SOURCE_DETAIL_KEY, USER_KEY),
	constraint UD_SSF foreign key (USER_KEY) references USER_DIM(USER_KEY),
	constraint TSD_SSF foreign key (TRAFFIC_SOURCE_KEY) references TRAFFIC_SOURCE_DIM(TRAFFIC_SOURCE_KEY),
	constraint DTD_SSF foreign key (DEVICE_KEY) references DEVICE_DIM(DEVICE_KEY),
	constraint UGNLD_SSF foreign key (USER_GEO_NTWK_LOC_KEY) references USER_GEO_NTWK_LOC_DIM(USER_GEO_NTWK_LOC_KEY),
	constraint TSDD_SSF foreign key (TRAFFIC_SOURCE_DETAIL_KEY) references TRAFFIC_SOURCE_DETAIL_DIM(TRAFFIC_SOURCE_DETAIL_KEY),
	constraint BD_SSF foreign key (BROWSER_KEY) references BROWSER_DIM(BROWSER_KEY),
	constraint MD_SSF foreign key (MOBILE_KEY) references MOBILE_DIM(MOBILE_KEY)
)COMMENT='This section contains aggregate values across the session.\n'
;
create TABLE IF NOT EXISTS TRAFFIC_SOURCE_DETAIL_DIM (
	TRAFFIC_SOURCE_DETAIL_KEY NUMBER(38,0) NOT NULL COMMENT 'This is unique Identifier for a Traffic Source Detail, This is a sorrogate Key',
	INFO_CAMPAIGN_ID VARCHAR(16777216) NOT NULL COMMENT 'The Google Ads campaign ID.\n',
	INFO_CUST_ID VARCHAR(16777216) NOT NULL COMMENT 'The Google ad ID.\n',
	REFERRAL_PATH_TXT VARCHAR(16777216) COMMENT 'If trafficSource.medium is \"referral\", then this is set to the path of the referrer. (The host name of the referrer is in trafficSource.source.)\n',
	KEYWORD_VAL VARCHAR(16777216) COMMENT 'The keyword of the traffic source, usually set when the trafficSource.medium is \"organic\" or \"cpc\". Can be set by the utm_term URL parameter.\n',
	AD_CONTENT_NM VARCHAR(16777216) COMMENT 'The ad content of the traffic source. Can be set by the utm_content URL parameter.\n',
	IS_TRUE_DIRECT_IND BOOLEAN COMMENT 'True if the source of the session was Direct (meaning the user typed the name of your website URL into the browser or came to your site via a bookmark), This field will also be true if 2 successive but distinct sessions have exactly the same campaign details. Otherwise NULL.\n',
	INFO_AD_GROUP_ID VARCHAR(16777216) COMMENT 'The Google ad-group ID.\n',
	INFO_CREATIVE_ID VARCHAR(16777216) COMMENT 'The Google ad ID.\n',
	INFO_CRITERIA_ID VARCHAR(16777216) COMMENT 'The ID for the targeting criterion.\n',
	INFO_PAGE_NBR VARCHAR(16777216) COMMENT 'Page number in search results where the ad was shown.\n',
	INFO_SLOT_NBR VARCHAR(16777216) COMMENT 'Position of the Ad. Takes one of the following values:{“RHS\", \"Top\"}\n',
	INFO_CRITERIA_PARAM_VAL VARCHAR(16777216) COMMENT 'Descriptive string for the targeting criterion.\n',
	INFO_GCL_ID VARCHAR(16777216) COMMENT 'The Google Click ID.\n\n',
	INFO_AD_NTWK_TYP VARCHAR(16777216) COMMENT 'Network Type. Takes one of the following values: {“Google Search\", \"Content\", \"Search partners\", \"Ad Exchange\", \"Yahoo Japan Search\", \"Yahoo Japan AFS\", “unknown”}\n',
	INFO_TGTNG_CRITERIA_BOOM_USER_LIST_ID VARIANT COMMENT 'Remarketing list ID (if any) in Google Ads, derived from matching_criteria in click record.\n',
	INFO_IS_VIDEO_AD_IND VARCHAR(16777216) COMMENT 'True if it is a Trueview video ad.\n',
	LOAD_TYP VARCHAR(16777216) COMMENT 'Indicates whether data is part of a large historical data pull or was added from a smaller data pull (daily, weekly etc.) \n',
	LOAD_ID NUMBER(38,0) COMMENT ' Indicates whether data is part of a large historical data pull or was added from a smaller data pull (daily, weekly etc.) \n',
	LOAD_DTTM TIMESTAMP_NTZ(9) COMMENT '\nThe Date/Datetime the Record was Inserted',
	UPDATE_ID NUMBER(38,0) COMMENT 'This is the User Identifier of the Person or Process that Updated the Table',
	UPDATE_DTTM TIMESTAMP_NTZ(9) COMMENT 'The Date/Datetime the Record was Updated',
	constraint XPKUSER_TRAFFIC_SOURCE_DETAIL_DIMENSION primary key (TRAFFIC_SOURCE_DETAIL_KEY),
	constraint XAK1USER_TRAFFIC_SOURCE_DETAIL_DIMENSION unique (KEYWORD_VAL, IS_TRUE_DIRECT_IND, INFO_SLOT_NBR, INFO_TGTNG_CRITERIA_BOOM_USER_LIST_ID, INFO_IS_VIDEO_AD_IND, INFO_PAGE_NBR, INFO_GCL_ID, INFO_CUST_ID, INFO_CRITERIA_PARAM_VAL, INFO_CRITERIA_ID, INFO_CREATIVE_ID, INFO_CAMPAIGN_ID, INFO_AD_NTWK_TYP, INFO_AD_GROUP_ID, AD_CONTENT_NM, REFERRAL_PATH_TXT)
);
create TABLE IF NOT EXISTS TRAFFIC_SOURCE_DIM (
	TRAFFIC_SOURCE_KEY NUMBER(38,0) NOT NULL COMMENT 'This is unique Identifier for a Traffic Source, This is a sorrogate Key',
	CHANNEL_GROUP_TYP VARCHAR(150) NOT NULL COMMENT 'The Default Channel Group associated with an end user''s session for this View.\n',
	CAMPAIGN_NM VARCHAR(16777216) NOT NULL COMMENT 'The campaign value. Usually set by the utm_campaign URL parameter.\n',
	MEDIUM_NM VARCHAR(16777216) COMMENT 'The medium of the traffic source. Could be \"organic\", \"cpc\", \"referral\", or the value of the utm_medium URL parameter.\n',
	SOURCE_NM VARCHAR(16777216) COMMENT 'The source of the traffic source. Could be the name of the search engine, the referring hostname, or a value of the utm_source URL parameter.\n',
	LOAD_TYP VARCHAR(16777216) COMMENT 'Indicates whether data is part of a large historical data pull or was added from a smaller data pull (daily, weekly etc.) \n',
	LOAD_ID NUMBER(38,0) COMMENT ' Indicates whether data is part of a large historical data pull or was added from a smaller data pull (daily, weekly etc.) \n',
	LOAD_DTTM TIMESTAMP_NTZ(9) COMMENT '\nThe Date/Datetime the Record was Inserted',
	UPDATE_ID NUMBER(38,0) COMMENT 'This is the User Identifier of the Person or Process that Updated the Table',
	UPDATE_DTTM TIMESTAMP_NTZ(9) COMMENT 'The Date/Datetime the Record was Updated',
	constraint XPKTRAFFIC_SOURCE_DIMENSION primary key (TRAFFIC_SOURCE_KEY),
	constraint XAK1TRAFFIC_SOURCE_DIMENSION unique (MEDIUM_NM, SOURCE_NM, CAMPAIGN_NM, CHANNEL_GROUP_TYP)
);
create TABLE IF NOT EXISTS USER_DIM (
	USER_KEY NUMBER(38,0) NOT NULL COMMENT 'This is unique Identifier for a User, This is a sorrogate Key',
	USER_ID VARCHAR(150) NOT NULL COMMENT 'Overridden User ID sent to Analytics.\n',
	LOAD_TYP VARCHAR(16777216) COMMENT 'Indicates whether data is part of a large historical data pull or was added from a smaller data pull (daily, weekly etc.) \n',
	LOAD_ID NUMBER(38,0) COMMENT ' Indicates whether data is part of a large historical data pull or was added from a smaller data pull (daily, weekly etc.) \n',
	LOAD_DTTM TIMESTAMP_NTZ(9) COMMENT '\nThe Date/Datetime the Record was Inserted',
	UPDATE_ID NUMBER(38,0) COMMENT 'This is the User Identifier of the Person or Process that Updated the Table',
	UPDATE_DTTM TIMESTAMP_NTZ(9) COMMENT 'The Date/Datetime the Record was Updated',
	constraint XPKUSER_DIMENSION primary key (USER_KEY),
	constraint XAK1USER_DIMENSION unique (USER_ID)
);
create TABLE IF NOT EXISTS USER_GEO_NTWK_LOC_DIM (
	USER_GEO_NTWK_LOC_KEY NUMBER(38,0) NOT NULL COMMENT 'This is the Sorrogate Key for the Network Location Dimension Junk Table',
	CONT_NM VARCHAR(16777216) COMMENT 'The continent from which sessions originated, based on IP address.\n',
	SUBCONT_NM VARCHAR(16777216) COMMENT 'The sub-continent from which sessions originated, based on IP address of the visitor.\n',
	CNTRY_NM VARCHAR(16777216) COMMENT 'The country from which sessions originated, based on IP address.\n',
	REGION_NM VARCHAR(16777216) COMMENT 'The region from which sessions originate, derived from IP addresses. In the U.S., a region is a state, such as New York.\n',
	METRO_NM VARCHAR(16777216) COMMENT 'The Designated Market Area (DMA) from which sessions originate.\n',
	CITY_NM VARCHAR(16777216) COMMENT 'Users'' city, derived from their IP addresses or Geographical IDs.\n',
	LOAD_TYP VARCHAR(16777216) COMMENT 'Indicates whether data is part of a large historical data pull or was added from a smaller data pull (daily, weekly etc.) \n',
	LOAD_ID NUMBER(38,0) COMMENT ' Indicates whether data is part of a large historical data pull or was added from a smaller data pull (daily, weekly etc.) \n',
	LOAD_DTTM TIMESTAMP_NTZ(9) COMMENT '\nThe Date/Datetime the Record was Inserted',
	UPDATE_ID NUMBER(38,0) COMMENT 'This is the User Identifier of the Person or Process that Updated the Table',
	UPDATE_DTTM TIMESTAMP_NTZ(9) COMMENT 'The Date/Datetime the Record was Updated',
	constraint XPKUSER_GEOGRAPHY_NETWORK_LOCATION_DIMENSION primary key (USER_GEO_NTWK_LOC_KEY),
	constraint XAK1USER_GEOGRAPHY_NETWORK_LOCATION_DIMENSION unique (CONT_NM, REGION_NM, SUBCONT_NM, CITY_NM, CNTRY_NM, METRO_NM)
);