create TABLE IF NOT EXISTS FLYWAY_SCHEMA_HISTORY (
	INSTALLED_RANK NUMBER(38,0) NOT NULL,
	VERSION VARCHAR(50),
	DESCRIPTION VARCHAR(200),
	TYPE VARCHAR(20) NOT NULL,
	SCRIPT VARCHAR(1000) NOT NULL,
	CHECKSUM NUMBER(38,0),
	INSTALLED_BY VARCHAR(100) NOT NULL,
	INSTALLED_ON TIMESTAMP_LTZ(9) NOT NULL DEFAULT CURRENT_TIMESTAMP(),
	EXECUTION_TIME NUMBER(38,0) NOT NULL,
	SUCCESS BOOLEAN NOT NULL,
	primary key (INSTALLED_RANK)
);
create view IF NOT EXISTS CHANNEL_CAMPAIGN_LINK_V(
	CHANNEL,
	SUBCHANNEL,
	SUBCHANNEL2,
	PARTNER,
	CAMPAIGNNAME,
	STANDARDCAMPAIGNNAME,
	STANDARDCAMPAIGNDESCRIPTION,
	STANDARDOBJECTIVETYPE,
	STRATEGYNAME,
	STRATEGYTYPENAME,
	BRANDID,
	SOURCE,
	LASTUPDATEDATETIME
) as
 SELECT DISTINCT ch.CHANNEL_NM AS Channel,
        ch.CHANNEL_CATEGORY_NM AS SubChannel,
        ch.CHANNEL_SUBCATEGORY_NM AS SubChannel2,
        ch.PARTNER_NM AS Partner,
        cmp.CAMPAIGN_NM AS CampaignName,
    cmp.Standard_Campaign_Nm as StandardCampaignName,
        cmp.Standard_Campaign_Desc as StandardCampaignDescription,
        cmp.Standard_Objective_Typ as StandardObjectiveType,
        str.STRATEGY_NM AS StrategyName,
        str.STRATEGY_TYPE_NM AS StrategyTypeName,
        ch.BRAND_ID AS BrandId,
        ch.SOURCE_SYSTEM_NM AS Source,
        ch.LAST_UPDATED_DTTM AS LastUpdateDateTime
 FROM IDM_DEV.MEDIA.CHANNEL_HIERARCHY ch
  INNER JOIN IDM_DEV.MEDIA.MEDIA_ACTIVITY_FACT fct
   ON ch.CHANNEL_HIERARCHY_KEY=fct.CHANNEL_HIERARCHY_KEY
  INNER JOIN IDM_DEV.MEDIA.CAMPAIGN cmp
   ON cmp.CAMPAIGN_KEY=fct.CAMPAIGN_KEY
  INNER JOIN IDM_DEV.MEDIA.STRATEGY str
   ON str.STRATEGY_KEY=fct.STRATEGY_KEY;
create view IF NOT EXISTS CHANNEL_HIERARCHY_V(
	CHANNEL,
	SUBCHANNEL,
	SUBCHANNEL2,
	PARTNER,
	BRANDID,
	SOURCE,
	LASTUPDATEDATETIME
) as
 SELECT CHANNEL_NM AS Channel,
        CHANNEL_CATEGORY_NM AS SubChannel,
        CHANNEL_SUBCATEGORY_NM AS SubChannel2,
        PARTNER_NM AS Partner,
        BRAND_ID AS BrandId,
        SOURCE_SYSTEM_NM AS Source,
        LAST_UPDATED_DTTM AS LastUpdateDateTime
 FROM IDM_DEV.MEDIA.CHANNEL_HIERARCHY;
create view IF NOT EXISTS MEDIA_ACTIVITY_UPLIFT_V(
	DMACODE,
	WEEKSTARTDATE,
	CHANNEL,
	SUBCHANNEL,
	SUBCHANNEL2,
	PARTNER,
	SPENDAMOUNT,
	ACTIVITY,
	TRANSUPLIFT,
	TRANSEFFICIENCY,
	TRANSMARGINAL
) as SELECT 
DMACODE AS DMACODE,
WEEKSTARTDATE AS WEEKSTARTDATE,
CHANNEL AS CHANNEL,
SUBCHANNEL AS SUBCHANNEL,
SUBCHANNEL2 AS SUBCHANNEL2,
PARTNER AS PARTNER,
SPENDAMOUNT AS SPENDAMOUNT,
ACTIVITY AS ACTIVITY,
TRANSUPLIFT AS TRANSUPLIFT,
TRANSEFFICIENCY AS TRANSEFFICIENCY,
TRANSMARGINAL AS TRANSMARGINAL
FROM IDS_DEV.DATASTORE.MEDIA_ACTIVITY_UPLIFT;
create view IF NOT EXISTS MEDIA_ACTIVITY_WEEK_V(
	CHANNEL,
	SUBCHANNEL,
	SUBCHANNEL2,
	PARTNER,
	WEEKSTARTDATE,
	DMACODE,
	DMANAME,
	IMPRESSIONS,
	RATINGS,
	CLICKS,
	GRP,
	TRP,
	BRANDID,
	SOURCE,
	LASTUPDATEDATETIME
) as
 SELECT  ch.CHANNEL_NM AS Channel,
        ch.CHANNEL_CATEGORY_NM AS SubChannel,
        ch.CHANNEL_SUBCATEGORY_NM AS SubChannel2,
        ch.PARTNER_NM AS Partner,
        fct.WEEK_START_DT AS WeekStartDate,
        fct.DMA_CD AS DMACode,
        dma.DMAName AS DMAName,
        fct.IMPRESSIONS_CNT AS Impressions,
        fct.RATINGS_CNT AS Ratings,
        fct.CLICKS_CNT AS Clicks,
        fct.GRP_CNT AS GRP,
        fct.TRP_CNT AS TRP,
        fct.BRAND_ID AS BrandId,
        fct.SOURCE_SYSTEM_NM AS Source,
        fct.LAST_UPDATED_DTTM AS LastUpdateDateTime
 FROM IDM_DEV.MEDIA.CHANNEL_HIERARCHY ch
  INNER JOIN IDM_DEV.MEDIA.MEDIA_ACTIVITY_FACT fct
   ON ch.CHANNEL_HIERARCHY_KEY=fct.CHANNEL_HIERARCHY_KEY
  INNER JOIN CDM_DEV.STAGING.LOC_DMA_PLR dma
   ON dma.DMACODE=fct.DMA_CD;
create view IF NOT EXISTS MEDIA_SPEND_WEEK_V(
	CHANNEL,
	SUBCHANNEL,
	SUBCHANNEL2,
	PARTNER,
	WEEKSTARTDATE,
	DMACODE,
	DMANAME,
	SPENDTYPENAME,
	SPENDAMOUNT,
	CURRENCYCODE,
	BRANDID,
	SOURCE,
	LASTUPDATEDATETIME
) as
  SELECT  ch.CHANNEL_NM AS Channel,
        ch.CHANNEL_CATEGORY_NM AS SubChannel,
        ch.CHANNEL_SUBCATEGORY_NM AS SubChannel2,
        ch.PARTNER_NM AS Partner,
        fct.WEEK_START_DT AS WeekStartDate,
        fct.DMA_CD AS DMACode,
        dma.DMAName AS DMAName,
        spt.SPEND_TYP_NM AS SpendTypeName,
        fct.SPEND_AMT AS SpendAmount,
        fct.CURRENCY_CD AS CurrencyCode,
        fct.BRAND_ID AS BrandId,
        fct.SOURCE_SYSTEM_NM AS Source,
        fct.LAST_UPDATED_DTTM AS LastUpdateDateTime
 FROM IDM_DEV.MEDIA.CHANNEL_HIERARCHY ch
  INNER JOIN IDM_DEV.MEDIA.MEDIA_ACTIVITY_FACT fct
   ON ch.CHANNEL_HIERARCHY_KEY=fct.CHANNEL_HIERARCHY_KEY
  INNER JOIN CDM_DEV.STAGING.LOC_DMA_PLR dma
   ON dma.DMACODE=fct.DMA_CD
  INNER JOIN IDM_DEV.MEDIA.SPEND_TYPE spt
   ON spt.SPEND_TYPE_KEY=fct.SPEND_TYPE_KEY;
create view IF NOT EXISTS MMO_TOTAL_ACTIVITY_UPLIFT_V(
	DMACODE,
	WEEKSTARTDATE,
	GROUP1,
	GROUP2,
	GROUP3,
	GROUP4,
	GROUP5,
	TRANSUPLIFT
) as SELECT 
	DMACODE       AS DMACODE,
	WEEKSTARTDATE AS WEEKSTARTDATE,
	GROUP1        AS GROUP1,
	GROUP2        AS GROUP2,
	GROUP3        AS GROUP3,
	GROUP4        AS GROUP4,
	GROUP5        AS GROUP5,
	TRANSUPLIFT   AS TRANSUPLIFT
FROM IDS_DEV.DATASTORE.MMO_TOTAL_ACTIVITY_UPLIFT;