CREATE TABLE IF NOT EXISTS EPSILON_MEMBEROFFER (
    CREATEDATE STRING,
    EXPIRATIONDATE STRING,
    OFFERCODE STRING,
    OPTINDATE STRING,
    PROFILEID STRING,
    PROFILEOFFERID STRING,
    BRAND_ID STRING,
    SOURCE_SYSTEM_NAME STRING,
    LOAD_ID STRING,
    LOAD_DTTM STRING,
    UPDATE_ID STRING,
    UPDATE_DTTM STRING,
    LOAD_FILENAME STRING
);