create TABLE IF NOT EXISTS CRM_PUSH_MESSAGE_DETAIL (
	BRAND_ID VARCHAR(20) COMMENT 'Brand Identifier specifies the code which represents an organization. The identifier should be in all capital letters. Sample codes are irb (Inspire Recognized Brands), bww(Buffalo Wild Wing), arbys (Arbys),  dnkn  (Dunkin), etc.',
	SOURCE_SYSTEM_NM VARCHAR(255) COMMENT 'Source System Name specifies the origin of the data. For example, Salesforce Marketing App or Netsuite. Some systems will have a reference table where sources are identified by integers such as 1,2,3, etc.',
	ACCOUNT_ID NUMBER(38,0) COMMENT 'Account Identifier represents the On-Your-Behalf (OYB)  Account number is the client/account ID number for any related On-Your-Behalf (OYB) accounts. This field applies to enterprise accounts only.  Sample values for Client ID - BWW is 100040982 and Arbys is 100039504.',
	EID NUMBER(38,0) COMMENT 'Eid is ',
	APP_NAME VARCHAR(16777216) COMMENT 'App Name is Name of the mobile app message was sent to; configured in MobilePush Administration',
	MESSAGE_NAME VARCHAR(16777216) COMMENT 'Message Name is Name of the sent message; populated by the name of the Push Activity in Journey Builder',
	MESSAGE_ID VARCHAR(16777216) COMMENT 'Message Identifier is a unique identifier for a message. The initial population of this field is for data being integrated from Epsilon Agility Harmony. A message may have multiple service transactions.',
	CAMPAIGNS VARCHAR(16777216) COMMENT 'Campaigns is Name of the campaign associated with the sent message',
	DEVICE_ID VARCHAR(16777216) COMMENT 'Device Id is ID of the device that received the message. The Device ID is a unique identifier assigned to a specific mobile device owned by a contact',
	DATE_TIME_SEND TIMESTAMP_NTZ(9) COMMENT 'Date Time Send is Date and time, in UTC-6, that the message was sen',
	MESSAGE_CONTENT VARCHAR(16777216) COMMENT 'Message Content is Content of the message. This field shows AMPscript, if used',
	MESSAGE_OPENED VARCHAR(16777216) COMMENT 'Message Opened is Whether the message was opened on the device corresponding to the Device ID',
	OPEN_DATE TIMESTAMP_NTZ(9) COMMENT 'Open Date is When the message was opened',
	TIME_IN_APP VARCHAR(16777216) COMMENT 'Time In App is How long the user spent in the app after opening the message. Measured from the time the subscriber opens the app to the time the app goes into the background',
	PLATFORM VARCHAR(16777216) COMMENT 'Platform is Operating system of the device',
	PLATFORM_VERSION VARCHAR(16777216) COMMENT 'Platform Version is Version of the operating system',
	STATUS VARCHAR(16777216) COMMENT 'Status is Status of the send job at the device level. This field tells you whether the job succeeded or failed for the device. * Expected values are Success, Failed, and Blank only if theres no returned data on the send.',
	SERVICE_RESPONSE VARCHAR(16777216) COMMENT 'Service Response is ',
	GEOFENCE_NAME VARCHAR(16777216) COMMENT 'Geofence Name is Name of the geofence that triggered the message',
	TEMPLATE VARCHAR(16777216) COMMENT 'Template is Template of the sent message: Outbound, Location Entry, Location Exit, or Beacon',
	FORMAT VARCHAR(16777216) COMMENT 'Format is Format of the sent message: Application Alert or Application Alert & Landing Page',
	PAGE_NAME VARCHAR(16777216) COMMENT 'Page Name is Subject field of the cloud page that is associated with the message',
	PUSH_JOB_ID VARCHAR(16777216) COMMENT 'Push Job Id is ID of the job to use when troubleshooting with support',
	SYSTEM_TOKEN VARCHAR(16777216) COMMENT 'System Token is Unique key that is used by Google or Apple to identify the device for sending',
	INBOX_DOWNLOAD VARCHAR(16777216) COMMENT 'Inbox Download is Date and time the message was downloaded',
	INBOX_OPEN VARCHAR(16777216) COMMENT 'Inbox Open is Date and time Inbox was opened',
	IOS_MEDIA_URL VARCHAR(16777216) COMMENT 'Ios Media Url is ',
	ANDROID_MEDIA_URL VARCHAR(16777216) COMMENT 'Android Media Url is ',
	MEDIA_ALT VARCHAR(16777216) COMMENT 'Media Alt is ',
	CONTACT_KEY VARCHAR(16777216) COMMENT 'Contact Key is ID of the contact that owns the device that received the message but not the ID of the device; one contact could have multiple devices. The ContactKey matches the Contacts and Devices ID. The ContactKey indicates the subscriber associated with the device when the report is run',
	REQUEST_ID VARCHAR(16777216) COMMENT 'Request Id is Marketing Clouds unique identifier for every request',
	SERVICE_TRANSACTION_ID VARCHAR(16777216) COMMENT 'Service Transaction Identifier per each activity event for a message. The initial population of this field is for data being integrated from Epsilon Agility Harmony. There can be multiple service transactions per message.',
	LOAD_ID NUMBER(38,0) COMMENT 'Load Identifier specifies the Batch that inserted the record into the table.',
	LOAD_DTTM TIMESTAMP_NTZ(9) COMMENT 'Load Datetime is the date and time in UTC when the record was created. For example, 2021-08-11T15:02:24Z.',
	UPDATE_ID NUMBER(38,0) COMMENT 'Update Identifier specifies the batch id used for the update of the record.',
	UPDATE_DTTM TIMESTAMP_NTZ(9) COMMENT 'Update Datetime is the date and time in UTC when the record was last updated. For example, 2021-08-11T15:02:24Z.',
	LOAD_FILENAME VARCHAR(16777216) COMMENT 'Load Filename is the name of the file that was used to create the data.',
	constraint XAK1CRM_PUSH_MESSAGE_DETAIL_EPSILON unique (BRAND_ID, SOURCE_SYSTEM_NM, ACCOUNT_ID, CONTACT_KEY, MESSAGE_ID, PUSH_JOB_ID, DEVICE_ID, SERVICE_TRANSACTION_ID)
)COMMENT='CRM Push Message Detail contains information about push notification interactions. For SFMC data there does not appear to be a Primary Key. For Epsilon data the �Unique Key: Contact_key + message_id + push_job_id + device_id.';

create TABLE IF NOT EXISTS CRM_PUSH_SEND_LOG (
	BRAND_ID VARCHAR(20) COMMENT 'Brand Identifier specifies the code which represents an organization. The identifier should be in all capital letters. Sample codes are irb (Inspire Recognized Brands), bww(Buffalo Wild Wing), arbys (Arbys),  dnkn  (Dunkin), etc.',
	SOURCE_SYSTEM_NM VARCHAR(255) COMMENT 'Source System Name specifies the origin of the data. For example, Salesforce Marketing App or Netsuite. Some systems will have a reference table where sources are identified by integers such as 1,2,3, etc.',
	PUSH_JOB_ID VARCHAR(16777216) COMMENT 'Push Job Id is the ID of the job, or bundle of send, that included the push notification ',
	PUSH_TRIGGERED_SEND_REQUEST_ID VARCHAR(16777216) COMMENT 'Push Triggered Send Request Id is TokenID that is returned from the API call. When you use list and data extension sends, is the same as the PushJobID ',
	PUSH_BATCH_ID NUMBER(38,0) COMMENT 'Push Batch Id is The ID of the batch, or bundle of jobs, for batched sends',
	SUB_ID NUMBER(38,0) COMMENT 'Sub Id is the ID of the subscriber to whom the message was sent',
	DEVICE_ID VARCHAR(16777216) COMMENT 'Device Id is the ID of the device that received the push notification',
	APP_ID VARCHAR(16777216) COMMENT 'App Id is The ID of the app that received the push notification ',
	LOG_DATE TIMESTAMP_NTZ(9) COMMENT 'Log Date is The date that this data was written to the send log ',
	LOAD_ID NUMBER(38,0) COMMENT 'Load Identifier specifies the Batch that inserted the record into the table.',
	LOAD_DTTM TIMESTAMP_NTZ(9) COMMENT 'Load Datetime is the date and time in UTC when the record was created. For example, 2021-08-11T15:02:24Z.',
	UPDATE_ID NUMBER(38,0) COMMENT 'Update Identifier specifies the batch id used for the update of the record.',
	UPDATE_DTTM TIMESTAMP_NTZ(9) COMMENT 'Update Datetime is the date and time in UTC when the record was last updated. For example, 2021-08-11T15:02:24Z.',
	LOAD_FILENAME VARCHAR(16777216) COMMENT 'Load Filename is the name of the file that was used to create the data.',
	constraint XAK1CRM_PUSH_SEND_LOG unique (PUSH_JOB_ID, PUSH_TRIGGERED_SEND_REQUEST_ID, PUSH_BATCH_ID, SUB_ID, DEVICE_ID, APP_ID, BRAND_ID, SOURCE_SYSTEM_NM)
)COMMENT='CRM Push Send Log lists all the push notifications that occur to customers by day.'
;