create TABLE IF NOT EXISTS FLYWAY_SCHEMA_HISTORY (
	INSTALLED_RANK NUMBER(38,0) NOT NULL,
	VERSION VARCHAR(50),
	DESCRIPTION VARCHAR(200),
	TYPE VARCHAR(20) NOT NULL,
	SCRIPT VARCHAR(1000) NOT NULL,
	CHECKSUM NUMBER(38,0),
	INSTALLED_BY VARCHAR(100) NOT NULL,
	INSTALLED_ON TIMESTAMP_LTZ(9) NOT NULL DEFAULT CURRENT_TIMESTAMP(),
	EXECUTION_TIME NUMBER(38,0) NOT NULL,
	SUCCESS BOOLEAN NOT NULL,
	primary key (INSTALLED_RANK)
);
create view IF NOT EXISTS COMPETITOR_MEDIA_SPEND_WEEK_BV(
	COMPETITOR_MEDIA_SPEND_ID COMMENT 'Primary Key of the table.',
	WEEK_START_DT COMMENT 'Week start date. This should always be Monday''s date.',
	ADVERTISER_NM COMMENT 'Inspire brands competitor advertiser. Ex: Burger King, Wendys.',
	PRODUCT_NM COMMENT 'Name of the product.',
	MEDIA_TYP COMMENT 'Type of media. Ex: TV, Radio, Print etc.',
	DMA_CD COMMENT 'Market Area Code',
	SPEND_AMT COMMENT 'Amount spent on media for a specific week',
	BRAND_ID COMMENT 'Brand of the advertiser.',
	SOURCE_SYSTEM_NM COMMENT 'Data collected from source',
	LOAD_ID COMMENT 'Job Id.',
	LOAD_DTTM COMMENT 'Date when data is loaded into the table.',
	UPDATE_ID COMMENT 'Updated By.',
	UPDATE_DTTM COMMENT 'Date when data is updated in the table.'
) as 
SELECT COMPETITOR_MEDIA_SPEND_WEEK.COMPETITOR_MEDIA_SPEND_ID,COMPETITOR_MEDIA_SPEND_WEEK.WEEK_START_DT,COMPETITOR_MEDIA_SPEND_WEEK.ADVERTISER_NM,COMPETITOR_MEDIA_SPEND_WEEK.PRODUCT_NM,COMPETITOR_MEDIA_SPEND_WEEK.MEDIA_TYP,COMPETITOR_MEDIA_SPEND_WEEK.DMA_CD,COMPETITOR_MEDIA_SPEND_WEEK.SPEND_AMT,COMPETITOR_MEDIA_SPEND_WEEK.BRAND_ID,COMPETITOR_MEDIA_SPEND_WEEK.SOURCE_SYSTEM_NM,COMPETITOR_MEDIA_SPEND_WEEK.LOAD_ID,COMPETITOR_MEDIA_SPEND_WEEK.LOAD_DTTM,COMPETITOR_MEDIA_SPEND_WEEK.UPDATE_ID,COMPETITOR_MEDIA_SPEND_WEEK.UPDATE_DTTM
FROM IDS_DEV.MEDIA.COMPETITOR_MEDIA_SPEND_WEEK ;
create view IF NOT EXISTS MEDIA_CAMPAIGNDETAIL_PLR_BV(
	CAMPAIGNDETAILID,
	CAMPAIGNID,
	CHANNELID,
	PARTNERID,
	STRATEGYID,
	LOADTYPE,
	BRANDID,
	SOURCE,
	CDMLOADDATE,
	CDMUPDATEDATE,
	FILENAME
) as SELECT
                               "CAMPAIGNDETAILID", "CAMPAIGNID", "CHANNELID", "PARTNERID", "STRATEGYID", "LOADTYPE", "BRANDID", "SOURCE", "CDMLOADDATE", "CDMUPDATEDATE", "FILENAME"
                            FROM CDMSYNC_DEV.IRB."MEDIA_CAMPAIGNDETAIL_PLR";
create view IF NOT EXISTS MEDIA_CAMPAIGN_BV(
	CAMPAIGN_ID,
	CAMPAIGN_NM,
	CAMPAIGN_DESC,
	STANDARD_CAMPAIGN_NM,
	STANDARD_CAMPAIGN_DESC,
	STANDARD_OBJECTIVE_TYP,
	MEDIA_TYP,
	LOAD_TYP,
	BRAND_ID,
	SOURCE_SYSTEM_NM,
	LOAD_ID,
	LOAD_DTTM,
	UPDATE_ID,
	UPDATE_DTTM
) as 
SELECT MEDIA_CAMPAIGN.CAMPAIGN_ID,MEDIA_CAMPAIGN.CAMPAIGN_NM,MEDIA_CAMPAIGN.CAMPAIGN_DESC,MEDIA_CAMPAIGN.STANDARD_CAMPAIGN_NM,MEDIA_CAMPAIGN.STANDARD_CAMPAIGN_DESC,MEDIA_CAMPAIGN.STANDARD_OBJECTIVE_TYP,MEDIA_CAMPAIGN.MEDIA_TYP,MEDIA_CAMPAIGN.LOAD_TYP,MEDIA_CAMPAIGN.BRAND_ID,MEDIA_CAMPAIGN.SOURCE_SYSTEM_NM,MEDIA_CAMPAIGN.LOAD_ID,MEDIA_CAMPAIGN.LOAD_DTTM,MEDIA_CAMPAIGN.UPDATE_ID,MEDIA_CAMPAIGN.UPDATE_DTTM
FROM IDS_DEV.MEDIA.MEDIA_CAMPAIGN ;
create view IF NOT EXISTS MEDIA_CAMPAIGN_DETAIL_BV(
	CAMPAIGN_DETAIL_ID,
	CHANNEL_ID,
	CAMPAIGN_ID,
	PARTNER_ID,
	STRATEGY_ID,
	LOAD_TYP,
	BRAND_ID,
	SOURCE_SYSTEM_NM,
	LOAD_ID,
	LOAD_DTTM,
	UPDATE_ID,
	UPDATE_DTTM
) as 
SELECT MEDIA_CAMPAIGN_DETAIL.CAMPAIGN_DETAIL_ID,MEDIA_CAMPAIGN_DETAIL.CHANNEL_ID,MEDIA_CAMPAIGN_DETAIL.CAMPAIGN_ID,MEDIA_CAMPAIGN_DETAIL.PARTNER_ID,MEDIA_CAMPAIGN_DETAIL.STRATEGY_ID,MEDIA_CAMPAIGN_DETAIL.LOAD_TYP,MEDIA_CAMPAIGN_DETAIL.BRAND_ID,MEDIA_CAMPAIGN_DETAIL.SOURCE_SYSTEM_NM,MEDIA_CAMPAIGN_DETAIL.LOAD_ID,MEDIA_CAMPAIGN_DETAIL.LOAD_DTTM,MEDIA_CAMPAIGN_DETAIL.UPDATE_ID,MEDIA_CAMPAIGN_DETAIL.UPDATE_DTTM
FROM IDS_DEV.MEDIA.MEDIA_CAMPAIGN_DETAIL ;
create view IF NOT EXISTS MEDIA_CAMPAIGN_PLR_BV(
	CAMPAIGNID,
	CAMPAIGNNAME,
	CAMPAIGNDESC,
	LOADTYPE,
	BRANDID,
	SOURCE,
	CDMLOADDATE,
	CDMUPDATEDATE,
	FILENAME
) as SELECT
                               "CAMPAIGNID", "CAMPAIGNNAME", "CAMPAIGNDESC", "LOADTYPE", "BRANDID", "SOURCE", "CDMLOADDATE", "CDMUPDATEDATE", "FILENAME"
                            FROM CDMSYNC_DEV.IRB."MEDIA_CAMPAIGN_PLR";
create view IF NOT EXISTS MEDIA_CHANNELTYPE_PLR_BV(
	CHANNELTYPEID,
	CHANNELTYPENAME,
	CHANNELTYPEDESC,
	LOADTYPE,
	BRANDID,
	SOURCE,
	CDMLOADDATE,
	CDMUPDATEDATE,
	FILENAME
) as SELECT
                               "CHANNELTYPEID", "CHANNELTYPENAME", "CHANNELTYPEDESC", "LOADTYPE", "BRANDID", "SOURCE", "CDMLOADDATE", "CDMUPDATEDATE", "FILENAME"
                            FROM CDMSYNC_DEV.IRB."MEDIA_CHANNELTYPE_PLR";
create view IF NOT EXISTS MEDIA_CHANNEL_BV(
	CHANNEL_ID,
	CHANNEL_TYPE_ID,
	CHANNEL_NM,
	CHANNEL_DESC,
	PARENT_CHANNEL_ID,
	LOAD_TYP,
	BRAND_ID,
	SOURCE_SYSTEM_NM,
	LOAD_ID,
	LOAD_DTTM,
	UPDATE_ID,
	UPDATE_DTTM
) as 
SELECT MEDIA_CHANNEL.CHANNEL_ID,MEDIA_CHANNEL.CHANNEL_TYPE_ID,MEDIA_CHANNEL.CHANNEL_NM,MEDIA_CHANNEL.CHANNEL_DESC,MEDIA_CHANNEL.PARENT_CHANNEL_ID,MEDIA_CHANNEL.LOAD_TYP,MEDIA_CHANNEL.BRAND_ID,MEDIA_CHANNEL.SOURCE_SYSTEM_NM,MEDIA_CHANNEL.LOAD_ID,MEDIA_CHANNEL.LOAD_DTTM,MEDIA_CHANNEL.UPDATE_ID,MEDIA_CHANNEL.UPDATE_DTTM
FROM IDS_DEV.MEDIA.MEDIA_CHANNEL ;
create view IF NOT EXISTS MEDIA_CHANNEL_HIERARCHY_REF_BV(
	CHANNEL_HIERARCHY_ID,
	SOURCE_CHANNEL_NM,
	SOURCE_SUBCHANNEL_NM,
	SOURCE_SUBCHANNEL2_NM,
	SOURCE_PARTNER_NM,
	INSPIRE_CHANNEL_NM,
	INSPIRE_SUBCHANNEL_NM,
	INSPIRESUBCHANNEL2_NM,
	INSPIRE_PARTNER_NM,
	BRAND_ID,
	SOURCE_SYSTEM_NM,
	LOAD_ID,
	LOAD_DTTM,
	UPDATE_ID,
	UPDATE_DTTM
) as 
SELECT MEDIA_CHANNEL_HIERARCHY_REF.CHANNEL_HIERARCHY_ID,MEDIA_CHANNEL_HIERARCHY_REF.SOURCE_CHANNEL_NM,MEDIA_CHANNEL_HIERARCHY_REF.SOURCE_SUBCHANNEL_NM,MEDIA_CHANNEL_HIERARCHY_REF.SOURCE_SUBCHANNEL2_NM,MEDIA_CHANNEL_HIERARCHY_REF.SOURCE_PARTNER_NM,MEDIA_CHANNEL_HIERARCHY_REF.INSPIRE_CHANNEL_NM,MEDIA_CHANNEL_HIERARCHY_REF.INSPIRE_SUBCHANNEL_NM,MEDIA_CHANNEL_HIERARCHY_REF.INSPIRESUBCHANNEL2_NM,MEDIA_CHANNEL_HIERARCHY_REF.INSPIRE_PARTNER_NM,MEDIA_CHANNEL_HIERARCHY_REF.BRAND_ID,MEDIA_CHANNEL_HIERARCHY_REF.SOURCE_SYSTEM_NM,MEDIA_CHANNEL_HIERARCHY_REF.LOAD_ID,MEDIA_CHANNEL_HIERARCHY_REF.LOAD_DTTM,MEDIA_CHANNEL_HIERARCHY_REF.UPDATE_ID,MEDIA_CHANNEL_HIERARCHY_REF.UPDATE_DTTM
FROM IDS_DEV.MEDIA.MEDIA_CHANNEL_HIERARCHY_REF ;
create view IF NOT EXISTS MEDIA_CHANNEL_PLR_BV(
	CHANNELTYPEID,
	CHANNELID,
	CHANNELNAME,
	CHANNELDESC,
	PARENTCHANNELID,
	LOADTYPE,
	BRANDID,
	SOURCE,
	CDMLOADDATE,
	CDMUPDATEDATE,
	FILENAME
) as SELECT
                               "CHANNELTYPEID", "CHANNELID", "CHANNELNAME", "CHANNELDESC", "PARENTCHANNELID", "LOADTYPE", "BRANDID", "SOURCE", "CDMLOADDATE", "CDMUPDATEDATE", "FILENAME"
                            FROM CDMSYNC_DEV.IRB."MEDIA_CHANNEL_PLR";
create view IF NOT EXISTS MEDIA_CHANNEL_TYPE_BV(
	CHANNEL_TYPE_ID,
	CHANNEL_TYPE_NM,
	CHANNEL_TYPE_DESC,
	LOAD_TYP,
	BRAND_ID,
	SOURCE_SYSTEM_NM,
	LOAD_ID,
	LOAD_DTTM,
	UPDATE_ID,
	UPDATE_DTTM
) as 
SELECT MEDIA_CHANNEL_TYPE.CHANNEL_TYPE_ID,MEDIA_CHANNEL_TYPE.CHANNEL_TYPE_NM,MEDIA_CHANNEL_TYPE.CHANNEL_TYPE_DESC,MEDIA_CHANNEL_TYPE.LOAD_TYP,MEDIA_CHANNEL_TYPE.BRAND_ID,MEDIA_CHANNEL_TYPE.SOURCE_SYSTEM_NM,MEDIA_CHANNEL_TYPE.LOAD_ID,MEDIA_CHANNEL_TYPE.LOAD_DTTM,MEDIA_CHANNEL_TYPE.UPDATE_ID,MEDIA_CHANNEL_TYPE.UPDATE_DTTM
FROM IDS_DEV.MEDIA.MEDIA_CHANNEL_TYPE ;
create view IF NOT EXISTS MEDIA_DMA_REF_BV(
	DMA_CROSSWALK_ID,
	SOURCE_DMA_CD,
	SOURCE_DMA_NM,
	INSPIRE_DMA_CD,
	INSPIRE_DMA_NM,
	BRAND_ID,
	SOURCE_SYSTEM_NM,
	LOAD_ID,
	LOAD_DTTM,
	UPDATE_ID,
	UPDATE_DTTM
) as 
SELECT MEDIA_DMA_REF.DMA_CROSSWALK_ID,MEDIA_DMA_REF.SOURCE_DMA_CD,MEDIA_DMA_REF.SOURCE_DMA_NM,MEDIA_DMA_REF.INSPIRE_DMA_CD,MEDIA_DMA_REF.INSPIRE_DMA_NM,MEDIA_DMA_REF.BRAND_ID,MEDIA_DMA_REF.SOURCE_SYSTEM_NM,MEDIA_DMA_REF.LOAD_ID,MEDIA_DMA_REF.LOAD_DTTM,MEDIA_DMA_REF.UPDATE_ID,MEDIA_DMA_REF.UPDATE_DTTM
FROM IDS_DEV.MEDIA.MEDIA_DMA_REF ;
create view IF NOT EXISTS MEDIA_MENU_PLR_BV(
	PLU_NBR,
	PLU_DESCRIPTION,
	AFA_PRODUCT_ID,
	AFA_PROD_DESC,
	PRICE,
	NBR_UNITS,
	MAIN_GROUP,
	MAIN_SORT_ORDER,
	BOGO,
	TYPE,
	STORE_NBR,
	PURE_MIX,
	COMPONENT_ID,
	COMPONENT,
	PURE_MIX_NBR_UNITS,
	HARD_CODE_PURE_MIX,
	ADD_DATE,
	SOURCE,
	BRANDID,
	CDMLOADDATE,
	FILENAME
) as SELECT
                               "PLU_NBR", "PLU_DESCRIPTION", "AFA_PRODUCT_ID", "AFA_PROD_DESC", "PRICE", "NBR_UNITS", "MAIN_GROUP", "MAIN_SORT_ORDER", "BOGO", "TYPE", "STORE_NBR", "PURE_MIX", "COMPONENT_ID", "COMPONENT", "PURE_MIX_NBR_UNITS", "HARD_CODE_PURE_MIX", "ADD_DATE", "SOURCE", "BRANDID", "CDMLOADDATE", "FILENAME"
                            FROM CDMSYNC_DEV.IRB."MEDIA_MENU_PLR";
create view IF NOT EXISTS MEDIA_PARTNER_BV(
	PARTNER_ID,
	CHANNEL_TYPE_ID,
	PARTNER_NM,
	PARTNER_DESC,
	LOAD_TYP,
	BRAND_ID,
	SOURCE_SYSTEM_NM,
	LOAD_ID,
	LOAD_DTTM,
	UPDATE_ID,
	UPDATE_DTTM
) as 
SELECT MEDIA_PARTNER.PARTNER_ID,MEDIA_PARTNER.CHANNEL_TYPE_ID,MEDIA_PARTNER.PARTNER_NM,MEDIA_PARTNER.PARTNER_DESC,MEDIA_PARTNER.LOAD_TYP,MEDIA_PARTNER.BRAND_ID,MEDIA_PARTNER.SOURCE_SYSTEM_NM,MEDIA_PARTNER.LOAD_ID,MEDIA_PARTNER.LOAD_DTTM,MEDIA_PARTNER.UPDATE_ID,MEDIA_PARTNER.UPDATE_DTTM
FROM IDS_DEV.MEDIA.MEDIA_PARTNER ;
create view IF NOT EXISTS MEDIA_PARTNER_PLR_BV(
	CHANNELTYPEID,
	PARTNERID,
	PARTNERNAME,
	PARTNERDESC,
	LOADTYPE,
	BRANDID,
	SOURCE,
	CDMLOADDATE,
	CDMUPDATEDATE,
	FILENAME
) as SELECT
                               "CHANNELTYPEID", "PARTNERID", "PARTNERNAME", "PARTNERDESC", "LOADTYPE", "BRANDID", "SOURCE", "CDMLOADDATE", "CDMUPDATEDATE", "FILENAME"
                            FROM CDMSYNC_DEV.IRB."MEDIA_PARTNER_PLR";
create view IF NOT EXISTS MEDIA_PRODUCT_PLR_BV(
	SUPER_GROUP,
	SUPER_GROUP_SORT_ORDER,
	CONSOLIDATE,
	MAIN_GROUP,
	MAIN_SORT_ORDER,
	SUBGROUP1,
	PRODUCT_ID,
	PRODUCT,
	PRODUCT_SORT_ORDER,
	FOOD_PAPER_DOLLARS,
	FOOD_PAPER_PCT,
	RPT_PRODUCT,
	NBR_UNITS,
	MENU_STATUS,
	MENU_TYPE_ORDER,
	MENU_TYPE,
	MENU_GROUP_ORDER,
	MENU_GROUP,
	ORIGINAL_NAME,
	RPT_SORT_ORDER,
	KEY_PRODUCT,
	SOURCE,
	BRANDID,
	CDMLOADDATE,
	FILENAME
) as SELECT
                               "SUPER_GROUP", "SUPER_GROUP_SORT_ORDER", "CONSOLIDATE", "MAIN_GROUP", "MAIN_SORT_ORDER", "SUBGROUP1", "PRODUCT_ID", "PRODUCT", "PRODUCT_SORT_ORDER", "FOOD_PAPER_DOLLARS", "FOOD_PAPER_PCT", "RPT_PRODUCT", "NBR_UNITS", "MENU_STATUS", "MENU_TYPE_ORDER", "MENU_TYPE", "MENU_GROUP_ORDER", "MENU_GROUP", "ORIGINAL_NAME", "RPT_SORT_ORDER", "KEY_PRODUCT", "SOURCE", "BRANDID", "CDMLOADDATE", "FILENAME"
                            FROM CDMSYNC_DEV.IRB."MEDIA_PRODUCT_PLR";
create view IF NOT EXISTS MEDIA_PROMOTION_PLR_BV(
	PROMO_ID1,
	PROMO_DES1,
	PROMO_ABR1,
	PRODUCT_ID,
	KEY_PRODUCT,
	CURRENT_PROMO,
	PROMO_PRICE,
	SORT_ORDER,
	PRICE_LEVEL,
	SOURCE,
	BRANDID,
	CDMLOADDATE,
	FILENAME
) as SELECT
                               "PROMO_ID1", "PROMO_DES1", "PROMO_ABR1", "PRODUCT_ID", "KEY_PRODUCT", "CURRENT_PROMO", "PROMO_PRICE", "SORT_ORDER", "PRICE_LEVEL", "SOURCE", "BRANDID", "CDMLOADDATE", "FILENAME"
                            FROM CDMSYNC_DEV.IRB."MEDIA_PROMOTION_PLR";
create view IF NOT EXISTS MEDIA_PROMOTION_WEEK_PLR_BV(
	ADI,
	FRANID,
	YEAR,
	MONTH,
	WEEK,
	FLIGHT_YEAR,
	FLIGHT_MONTH,
	PROMO_ID1,
	PROMO_ID2,
	ONE_PRICE,
	ONE_TV,
	ONE_TVP,
	ONE_TVS,
	ONE_TVS_DM,
	SPOT_CABLE,
	SPOT_CABLEP,
	SPOT_CABLES,
	SPOT_CABLES_DM,
	OTHERTVP,
	OTHERTVS,
	ONE_CABLE_TV,
	EQUALIZED_TRPS,
	EQUALIZEDP,
	EQUALIZEDS,
	SPOTPRIMARY15,
	CABLEPRIMARY15,
	SPORTSPRIMARY15,
	OTHERPRIMARY15,
	SPOTSECONDARY15,
	CABLESECONDARY15,
	SPORTSSECONDARY15,
	OTHERSECONDARY15,
	CONVERTRATE,
	TV_SPILL,
	FLIGHT_ID,
	RADIO_ID1,
	RADIO_ID2,
	ONE_RADIO,
	ONE_RADIOP,
	ONE_RADIOS,
	DJ_RADIO,
	TRAFFIC_RADIO,
	SPORTS_RADIO,
	RADIO_SPILL,
	NATL_ONLINE,
	LOCAL_ONLINE,
	ONE_INSERT,
	INSERTDATETY,
	TEST_FLIGHT,
	ONE_TV_ACTUAL,
	POST_BUY_ALL_LOCAL,
	RADIO_FOCUS,
	FOCUS,
	VEHICLE,
	PRINT_PARTICIPANTS,
	DISPLAY,
	DGTL_AUDIO,
	OUTDOOR,
	OUTDOORTRP,
	EXTRAS_EMAIL,
	MOBILE_OFFER,
	CRAVE,
	LSM,
	LSM_P,
	ONE_RADIO_COST,
	SUB_MKT_RADIO_PTS,
	SPORTS,
	SPORTSP,
	SPORTSS,
	LOCAL_SEASON,
	BOOKEND_PCT,
	UPDATE_DATE,
	EQUALIZEDN,
	SOURCE,
	BRANDID,
	CDMLOADDATE,
	FILENAME
) as SELECT
                               "ADI", "FRANID", "YEAR", "MONTH", "WEEK", "FLIGHT_YEAR", "FLIGHT_MONTH", "PROMO_ID1", "PROMO_ID2", "ONE_PRICE", "ONE_TV", "ONE_TVP", "ONE_TVS", "ONE_TVS_DM", "SPOT_CABLE", "SPOT_CABLEP", "SPOT_CABLES", "SPOT_CABLES_DM", "OTHERTVP", "OTHERTVS", "ONE_CABLE_TV", "EQUALIZED_TRPS", "EQUALIZEDP", "EQUALIZEDS", "SPOTPRIMARY15", "CABLEPRIMARY15", "SPORTSPRIMARY15", "OTHERPRIMARY15", "SPOTSECONDARY15", "CABLESECONDARY15", "SPORTSSECONDARY15", "OTHERSECONDARY15", "CONVERTRATE", "TV_SPILL", "FLIGHT_ID", "RADIO_ID1", "RADIO_ID2", "ONE_RADIO", "ONE_RADIOP", "ONE_RADIOS", "DJ_RADIO", "TRAFFIC_RADIO", "SPORTS_RADIO", "RADIO_SPILL", "NATL_ONLINE", "LOCAL_ONLINE", "ONE_INSERT", "INSERTDATETY", "TEST_FLIGHT", "ONE_TV_ACTUAL", "POST_BUY_ALL_LOCAL", "RADIO_FOCUS", "FOCUS", "VEHICLE", "PRINT_PARTICIPANTS", "DISPLAY", "DGTL_AUDIO", "OUTDOOR", "OUTDOORTRP", "EXTRAS_EMAIL", "MOBILE_OFFER", "CRAVE", "LSM", "LSM_P", "ONE_RADIO_COST", "SUB_MKT_RADIO_PTS", "SPORTS", "SPORTSP", "SPORTSS", "LOCAL_SEASON", "BOOKEND_PCT", "UPDATE_DATE", "EQUALIZEDN", "SOURCE", "BRANDID", "CDMLOADDATE", "FILENAME"
                            FROM CDMSYNC_DEV.IRB."MEDIA_PROMOTION_WEEK_PLR";
create view IF NOT EXISTS MEDIA_SPENDTYPE_PLR_BV(
	SPENDTYPEID,
	SPENDTYPENAME,
	SPENDTYPEDESC,
	LOADTYPE,
	BRANDID,
	SOURCE,
	CDMLOADDATE,
	CDMUPDATEDATE,
	FILENAME
) as SELECT
                               "SPENDTYPEID", "SPENDTYPENAME", "SPENDTYPEDESC", "LOADTYPE", "BRANDID", "SOURCE", "CDMLOADDATE", "CDMUPDATEDATE", "FILENAME"
                            FROM CDMSYNC_DEV.IRB."MEDIA_SPENDTYPE_PLR";
create view IF NOT EXISTS MEDIA_SPEND_TYPE_BV(
	SPEND_TYPE_ID,
	SPEND_TYPE_NM,
	SPEND_TYPE_DESC,
	LOAD_TYP,
	BRAND_ID,
	SOURCE_SYSTEM_NM,
	LOAD_ID,
	LOAD_DTTM,
	UPDATE_ID,
	UPDATE_DTTM
) as 
SELECT MEDIA_SPEND_TYPE.SPEND_TYPE_ID,MEDIA_SPEND_TYPE.SPEND_TYPE_NM,MEDIA_SPEND_TYPE.SPEND_TYPE_DESC,MEDIA_SPEND_TYPE.LOAD_TYP,MEDIA_SPEND_TYPE.BRAND_ID,MEDIA_SPEND_TYPE.SOURCE_SYSTEM_NM,MEDIA_SPEND_TYPE.LOAD_ID,MEDIA_SPEND_TYPE.LOAD_DTTM,MEDIA_SPEND_TYPE.UPDATE_ID,MEDIA_SPEND_TYPE.UPDATE_DTTM
FROM IDS_DEV.MEDIA.MEDIA_SPEND_TYPE ;
create view IF NOT EXISTS MEDIA_SPEND_WEEK_BV(
	SPEND_ID,
	WEEK_START_DT,
	DMA_CD,
	CAMPAIGN_DETAIL_ID,
	SPEND_TYPE_ID,
	SPEND_AMT,
	CURRENCY_CD,
	LOAD_TYP,
	BRAND_ID,
	SOURCE_SYSTEM_NM,
	LOAD_ID,
	LOAD_DTTM,
	UPDATE_ID,
	UPDATE_DTTM
) as 
SELECT MEDIA_SPEND_WEEK.SPEND_ID,MEDIA_SPEND_WEEK.WEEK_START_DT,MEDIA_SPEND_WEEK.DMA_CD,MEDIA_SPEND_WEEK.CAMPAIGN_DETAIL_ID,MEDIA_SPEND_WEEK.SPEND_TYPE_ID,MEDIA_SPEND_WEEK.SPEND_AMT,MEDIA_SPEND_WEEK.CURRENCY_CD,MEDIA_SPEND_WEEK.LOAD_TYP,MEDIA_SPEND_WEEK.BRAND_ID,MEDIA_SPEND_WEEK.SOURCE_SYSTEM_NM,MEDIA_SPEND_WEEK.LOAD_ID,MEDIA_SPEND_WEEK.LOAD_DTTM,MEDIA_SPEND_WEEK.UPDATE_ID,MEDIA_SPEND_WEEK.UPDATE_DTTM
FROM IDS_DEV.MEDIA.MEDIA_SPEND_WEEK ;
create view IF NOT EXISTS MEDIA_SPEND_WEEK_PLR_BV(
	SPENDID,
	WEEKSTARTDATE,
	DMACODE,
	CAMPAIGNDETAILID,
	SPENDTYPEID,
	SPENDAMOUNT,
	CURRENCYCODE,
	LOADTYPE,
	BRANDID,
	SOURCE,
	CDMLOADDATE,
	CDMUPDATEDATE,
	FILENAME
) as SELECT
                               "SPENDID", "WEEKSTARTDATE", "DMACODE", "CAMPAIGNDETAILID", "SPENDTYPEID", "SPENDAMOUNT", "CURRENCYCODE", "LOADTYPE", "BRANDID", "SOURCE", "CDMLOADDATE", "CDMUPDATEDATE", "FILENAME"
                            FROM CDMSYNC_DEV.IRB."MEDIA_SPEND_WEEK_PLR";
create view IF NOT EXISTS MEDIA_SPEND_WEEK_PLR_MV_BV(
	SPENDID,
	WEEKSTARTDATE,
	DMACODE,
	CAMPAIGNDETAILID,
	SPENDTYPEID,
	SPENDAMOUNT,
	CURRENCYCODE,
	LOADTYPE,
	BRANDID,
	SOURCE,
	CDMLOADDATE,
	CDMUPDATEDATE
) as SELECT
                               "SPENDID", "WEEKSTARTDATE", "DMACODE", "CAMPAIGNDETAILID", "SPENDTYPEID", "SPENDAMOUNT", "CURRENCYCODE", "LOADTYPE", "BRANDID", "SOURCE", "CDMLOADDATE", "CDMUPDATEDATE"
                            FROM CDMSYNC_DEV.IRB."MEDIA_SPEND_WEEK_PLR_MV";
create view IF NOT EXISTS MEDIA_STRATEGYTYPE_PLR_BV(
	STRATEGYTYPEID,
	STRATEGYTYPENAME,
	STRATEGYTYPEDESC,
	LOADTYPE,
	BRANDID,
	SOURCE,
	CDMLOADDATE,
	CDMUPDATEDATE,
	FILENAME
) as SELECT
                               "STRATEGYTYPEID", "STRATEGYTYPENAME", "STRATEGYTYPEDESC", "LOADTYPE", "BRANDID", "SOURCE", "CDMLOADDATE", "CDMUPDATEDATE", "FILENAME"
                            FROM CDMSYNC_DEV.IRB."MEDIA_STRATEGYTYPE_PLR";
create view IF NOT EXISTS MEDIA_STRATEGY_BV(
	STRATEGY_ID,
	STRATEGY_TYPE_ID,
	STRATEGY_NM,
	LOAD_TYP,
	BRAND_ID,
	SOURCE_SYSTEM_NM,
	LOAD_ID,
	LOAD_DTTM,
	UPDATE_ID,
	UPDATE_DTTM
) as 
SELECT MEDIA_STRATEGY.STRATEGY_ID,MEDIA_STRATEGY.STRATEGY_TYPE_ID,MEDIA_STRATEGY.STRATEGY_NM,MEDIA_STRATEGY.LOAD_TYP,MEDIA_STRATEGY.BRAND_ID,MEDIA_STRATEGY.SOURCE_SYSTEM_NM,MEDIA_STRATEGY.LOAD_ID,MEDIA_STRATEGY.LOAD_DTTM,MEDIA_STRATEGY.UPDATE_ID,MEDIA_STRATEGY.UPDATE_DTTM
FROM IDS_DEV.MEDIA.MEDIA_STRATEGY ;
create view IF NOT EXISTS MEDIA_STRATEGY_PLR_BV(
	STRATEGYTYPEID,
	STRATEGYID,
	STRATEGYNAME,
	LOADTYPE,
	BRANDID,
	SOURCE,
	CDMLOADDATE,
	CDMUPDATEDATE,
	FILENAME
) as SELECT
                               "STRATEGYTYPEID", "STRATEGYID", "STRATEGYNAME", "LOADTYPE", "BRANDID", "SOURCE", "CDMLOADDATE", "CDMUPDATEDATE", "FILENAME"
                            FROM CDMSYNC_DEV.IRB."MEDIA_STRATEGY_PLR";
create view IF NOT EXISTS MEDIA_STRATEGY_TYPE_BV(
	STRATEGY_TYPE_ID,
	STRATEGY_TYPE_NM,
	STRATEGY_TYPE_DESC,
	LOAD_TYP,
	BRAND_ID,
	SOURCE_SYSTEM_NM,
	LOAD_ID,
	LOAD_DTTM,
	UPDATE_ID,
	UPDATE_DTTM
) as 
SELECT MEDIA_STRATEGY_TYPE.STRATEGY_TYPE_ID,MEDIA_STRATEGY_TYPE.STRATEGY_TYPE_NM,MEDIA_STRATEGY_TYPE.STRATEGY_TYPE_DESC,MEDIA_STRATEGY_TYPE.LOAD_TYP,MEDIA_STRATEGY_TYPE.BRAND_ID,MEDIA_STRATEGY_TYPE.SOURCE_SYSTEM_NM,MEDIA_STRATEGY_TYPE.LOAD_ID,MEDIA_STRATEGY_TYPE.LOAD_DTTM,MEDIA_STRATEGY_TYPE.UPDATE_ID,MEDIA_STRATEGY_TYPE.UPDATE_DTTM
FROM IDS_DEV.MEDIA.MEDIA_STRATEGY_TYPE ;
create view IF NOT EXISTS MEDIA_SUB_CHANNEL2_HIERARCHY_BV(
	CHANNEL_ID,
	CHANNEL_TYPE_ID,
	CHANNEL_NAME,
	CHANNEL_DESC,
	PARENT_CHANNEL_ID,
	SUB_CHANNEL_ID,
	SUB_CHANNEL_TYPE_ID,
	SUB_CHANNEL_NAME,
	SUB_CHANNEL_DESC,
	SUB_CHANNEL2_PARENT_CHANNEL_ID,
	SUB_CHANNEL2_ID,
	SUB_CHANNEL2_TYPE_ID,
	SUB_CHANNEL2_NAME,
	SUB_CHANNEL2_DESC,
	SOURCE_SYSTEM_NAME,
	BRAND_ID,
	UPDATE_DTTM
) as
select 
chan.channel_id
,chan.channel_type_id
,chan.channel_nm AS CHANNEL_NAME
,chan.channel_desc
,chan.parent_channel_id AS PARENT_CHANNEL_ID
,suB_chan.channel_id AS SUB_CHANNEL_ID
,sub_chan.channel_type_id AS SUB_CHANNEL_TYPE_ID
,sub_chan.channel_nm AS SUB_CHANNEL_NAME
,sub_chan.channel_desc AS SUB_CHANNEL_DESC
,sub_chan.parent_channel_id AS SUB_CHANNEL2_PARENT_CHANNEL_ID
,sub_chan2.channel_id AS SUB_CHANNEL2_ID
,sub_chan2.channel_type_id AS SUB_CHANNEL2_TYPE_ID
,sub_chan2.channel_nm AS SUB_CHANNEL2_NAME
,sub_chan2.channel_desc  AS SUB_CHANNEL2_DESC
,sub_chan2.source_system_nm as source_system_name
,sub_chan2.brand_id
,sub_chan2.update_dttm
from MEDIA_CHANNEL_BV sub_chan2
inner join  MEDIA_CHANNEL_BV sub_chan
ON sub_chan2.parent_channel_id = sub_chan.channel_id 
AND sub_chan.channel_type_id = 2
inner join MEDIA_CHANNEL_BV chan
ON  sub_chan.parent_channel_id = chan.channel_id
AND chan.channel_type_id = 1
WHERE sub_chan2.channel_type_id =  3
and chan.channel_id = 1
;
create view IF NOT EXISTS MEDIA_TRACKER_WEEK_BV(
	TRACKER_ID,
	WEEK_START_DT,
	DMA_CD,
	CAMPAIGN_DETAIL_ID,
	IMPRESSIONS_CNT,
	RATINGS_CNT,
	CLICKS_CNT,
	GRP_CNT,
	TRP_CNT,
	LOAD_TYP,
	BRAND_ID,
	SOURCE_SYSTEM_NM,
	LOAD_ID,
	LOAD_DTTM,
	UPDATE_ID,
	UPDATE_DTTM
) as 
SELECT MEDIA_TRACKER_WEEK.TRACKER_ID,MEDIA_TRACKER_WEEK.WEEK_START_DT,MEDIA_TRACKER_WEEK.DMA_CD,MEDIA_TRACKER_WEEK.CAMPAIGN_DETAIL_ID,MEDIA_TRACKER_WEEK.IMPRESSIONS_CNT,MEDIA_TRACKER_WEEK.RATINGS_CNT,MEDIA_TRACKER_WEEK.CLICKS_CNT,MEDIA_TRACKER_WEEK.GRP_CNT,MEDIA_TRACKER_WEEK.TRP_CNT,MEDIA_TRACKER_WEEK.LOAD_TYP,MEDIA_TRACKER_WEEK.BRAND_ID,MEDIA_TRACKER_WEEK.SOURCE_SYSTEM_NM,MEDIA_TRACKER_WEEK.LOAD_ID,MEDIA_TRACKER_WEEK.LOAD_DTTM,MEDIA_TRACKER_WEEK.UPDATE_ID,MEDIA_TRACKER_WEEK.UPDATE_DTTM
FROM IDS_DEV.MEDIA.MEDIA_TRACKER_WEEK ;
create view IF NOT EXISTS MEDIA_TRACKER_WEEK_PLR_BV(
	TRACKERID,
	WEEKSTARTDATE,
	DMACODE,
	CAMPAIGNDETAILID,
	IMPRESSIONS,
	RATINGS,
	CLICKS,
	GRP,
	TRP,
	LOADTYPE,
	BRANDID,
	SOURCE,
	CDMLOADDATE,
	CDMUPDATEDATE,
	FILENAME
) as SELECT
                               "TRACKERID", "WEEKSTARTDATE", "DMACODE", "CAMPAIGNDETAILID", "IMPRESSIONS", "RATINGS", "CLICKS", "GRP", "TRP", "LOADTYPE", "BRANDID", "SOURCE", "CDMLOADDATE", "CDMUPDATEDATE", "FILENAME"
                            FROM CDMSYNC_DEV.IRB."MEDIA_TRACKER_WEEK_PLR";
create view IF NOT EXISTS TOTAL_MEDIA_UPLIFT_BV(
	BRAND_ID,
	WK_START_DATE,
	DMA_CODE,
	CHANNEL,
	SUBCHANNEL,
	SUBCHANNEL2,
	PARTNER,
	SPEND_AMOUNT,
	ACTIVITY_VALUE,
	TRANS_UPLIFT,
	TRANS_EFFICIENCY,
	TRANS_MARGINAL,
	WEEKLY_TRANS_AMOUNT,
	SOURCE_SYSTEM_NAME COMMENT 'Source System Name specifies the origin of the data. For example, Salesforce Marketing App or Netsuite. Some systems will have a reference table where sources are identified by integers such as 1,2,3, etc.',
	LOAD_ID COMMENT 'Load Identifier specifies the Batch that inserted the record into the table.',
	LOAD_DTTM COMMENT 'Load Datetime is the date and time in UTC when the record was created. For example, 2021-08-11T15:02:24Z.'
) as 
SELECT TOTAL_MEDIA_UPLIFT.BRAND_ID,TOTAL_MEDIA_UPLIFT.WK_START_DATE,TOTAL_MEDIA_UPLIFT.DMA_CODE,TOTAL_MEDIA_UPLIFT.CHANNEL,TOTAL_MEDIA_UPLIFT.SUBCHANNEL,TOTAL_MEDIA_UPLIFT.SUBCHANNEL2,TOTAL_MEDIA_UPLIFT.PARTNER,TOTAL_MEDIA_UPLIFT.SPEND_AMOUNT,TOTAL_MEDIA_UPLIFT.ACTIVITY_VALUE,TOTAL_MEDIA_UPLIFT.TRANS_UPLIFT,TOTAL_MEDIA_UPLIFT.TRANS_EFFICIENCY,TOTAL_MEDIA_UPLIFT.TRANS_MARGINAL,TOTAL_MEDIA_UPLIFT.WEEKLY_TRANS_AMOUNT,TOTAL_MEDIA_UPLIFT.SOURCE_SYSTEM_NAME,TOTAL_MEDIA_UPLIFT.LOAD_ID,TOTAL_MEDIA_UPLIFT.LOAD_DTTM
FROM IDS_DEV.MEDIA.TOTAL_MEDIA_UPLIFT ;
create view IF NOT EXISTS TOTAL_MODEL_UPLIFT_BV(
	BRAND_ID,
	WK_START_DATE,
	DMA_CODE,
	GROUP_1_TEXT,
	GROUP_2_TEXT,
	GROUP_3_TEXT,
	GROUP_4_TEXT,
	GROUP_5_TEXT,
	TRANS_UPLIFT,
	SOURCE_SYSTEM_NAME COMMENT 'Source System Name specifies the origin of the data. For example, Salesforce Marketing App or Netsuite. Some systems will have a reference table where sources are identified by integers such as 1,2,3, etc.',
	LOAD_ID COMMENT 'Load Identifier specifies the Batch that inserted the record into the table.',
	LOAD_DTTM COMMENT 'Load Datetime is the date and time in UTC when the record was created. For example, 2021-08-11T15:02:24Z.'
) as 
SELECT TOTAL_MODEL_UPLIFT.BRAND_ID,TOTAL_MODEL_UPLIFT.WK_START_DATE,TOTAL_MODEL_UPLIFT.DMA_CODE,TOTAL_MODEL_UPLIFT.GROUP_1_TEXT,TOTAL_MODEL_UPLIFT.GROUP_2_TEXT,TOTAL_MODEL_UPLIFT.GROUP_3_TEXT,TOTAL_MODEL_UPLIFT.GROUP_4_TEXT,TOTAL_MODEL_UPLIFT.GROUP_5_TEXT,TOTAL_MODEL_UPLIFT.TRANS_UPLIFT,TOTAL_MODEL_UPLIFT.SOURCE_SYSTEM_NAME,TOTAL_MODEL_UPLIFT.LOAD_ID,TOTAL_MODEL_UPLIFT.LOAD_DTTM
FROM IDS_DEV.MEDIA.TOTAL_MODEL_UPLIFT ;