drop table if exists hive_schema_stg.hvtb_nbx_core_crm_opportunity;
CREATE EXTERNAL TABLE hive_schema_stg.hvtb_nbx_core_crm_opportunity
(
   accountid                      varchar(100)   ,
   agencyid__c                    varchar(100)   ,
   agencyname__c                  varchar(100)   ,
   agentname__c                   varchar(100)   ,
   amount                         float         ,
   bookeddate__c                  timestamp      ,
   bookingsource__c               varchar(100)   ,
   booking_channel__c             varchar(100)   ,
   booking_id__c                  varchar(100)   ,
   booking_payments_total__c      float         ,
   cabin_category__c              varchar(100)   ,
   campaignid                     varchar(100)   ,
   checked_in__c                  boolean        ,
   closedate                      timestamp      ,
   clshipname__c                  varchar(100)   ,
   clvendorcode__c                varchar(100)   ,
   createdbyid                    varchar(100)   ,
   createddate                    timestamp      ,
   cruisepackagecode__c           varchar(100)   ,
   currency__c                    float         ,
   currencycode__c                varchar(100)   ,
   decimalplaces__c               varchar(100)   ,
   description                    varchar(500)   ,
   disembarkation_date__c         timestamp      ,
   display_tab__c                 varchar(100)   ,
   embarkation_date__c            timestamp      ,
   expectedrevenue                float         ,
   fiscal                         varchar(100)   ,
   fiscalquarter                  int            ,
   fiscalyear                     int            ,
   flight_purchase__c             varchar(500)   ,
   forecastcategory               varchar(100)   ,
   forecastcategoryname           varchar(100)   ,
   group_id__c                    varchar(100)   ,
   guesttype__c                   varchar(100)   ,
   hasopportunitylineitem         boolean        ,
   id                             varchar(100)   ,
   isclosed                       boolean        ,
   isdeleted                      boolean        ,
   isprivate                      boolean        ,
   iswon                          boolean        ,
   lastactivitydate               timestamp      ,
   lastmodifiedbyid               varchar(100)   ,
   lastmodifieddate               timestamp      ,
   leadsource                     varchar(100)   ,
   name                           varchar(100)   ,
   next_payment_date__c           timestamp      ,
   nextstep                       varchar(100)   ,
   number_of_guests__c            float         ,
   number_of_stateroom__c         float         ,
   offerdate__c                   timestamp      ,
   opportunity_amount__c          float         ,
   opportunityrevenueowner__c     varchar(100)   ,
   ownerid                        varchar(100)   ,
   package_type__c                varchar(100)   ,
   parent_res_id__c               varchar(100)   ,
   partneraccountid               varchar(100)   ,
   pendingpayment__c              float         ,
   port_name__c                   varchar(100)   ,
   preferred_currency__c          varchar(100)   ,
   pricebook2id                   varchar(100)   ,
   probability                    float         ,
   recordtypeid                   varchar(100)   ,
   regioncode__c                  varchar(100)   ,
   reservation_number__c          varchar(100)   ,
   sailing_package__c             varchar(100)   ,
   seaware_agentid__c             varchar(100)   ,
   seaware_reservation_status__c  varchar(100)   ,
   self__c                        boolean        ,
   ship_code__c                   varchar(100)   ,
   ssduration__c                  varchar(100)   ,
   ssend__c                       timestamp      ,
   sslosdescriptioncode__c        varchar(100)   ,
   ssportsofcallquality__c        varchar(100)   ,
   ssstart__c                     timestamp      ,
   stagename                      varchar(100)   ,
   status__c                      varchar(100)   ,
   syncedquoteid                  varchar(100)   ,
   systemmodstamp                 timestamp      ,
   totalopportunityquantity       float         ,
   type                           varchar(100)   ,
   vacation_start_date__c         timestamp      ,
   vacationenddate__c             timestamp      ,
   voyage_status__c               varchar(100)   ,
   voyageid__c                    varchar(100)   ,
   vip_status__c                  varchar(100)   ,
   vip_c                          boolean        ,
   reservationnetamount__c        varchar(100)   ,
   reservationcommissiontotal__c  float         ,
   depositsailor__c               boolean        ,
   promo_code__c varchar(100), 
   access_key__c varchar(100),
   job_id                         varchar(100)   ,
   load_data_timestamp            timestamp      ,
   epoc                           bigint         ,
   year                           int            ,
   month                          int            ,
   day                            int            
)
STORED AS PARQUET  
LOCATION
  's3://vv-prod-emr-cluster/data/core/crm/hvtb_nbx_core_crm_opportunity'
;

create or replace view crm.core_crm_opportunity_vw as select * from hive_schema_stg.hvtb_nbx_core_crm_opportunity with no schema binding;

GRANT USAGE ON SCHEMA crm TO  group Tableau_poweruser_group;

grant select on all tables in schema crm to group Tableau_poweruser_group ;

