create or replace view marketing.paidmedia_kpis as 
select social.channel as channel, social.date as date, social.platform as platform, null as subplatform, social.campaign as campaign,
social.objective as objective, social.audience_tactics as tactic, social.audience_tactic2 as target, social.updated_audience_tactics as tactic_updated, social.ad_name as ad_name, null as earned_paid, social.impressions as impressions, 0 as impressions_measurable, 0 as impressions_viewable, social.link_clicks as clicks, social.leads as leads, social.bookings as bookings, social.amount_spent_usd as spend, social.post_engagement as post_engagement, social.ad_format as ad_format, null as engine, null as geo, null as brand_nb, null as nb_relaunch, social.post_comments as post_comments, social.post_reactions as post_reactions, social.post_saves as post_saves, social.post_shares as post_shares, 0 as ctr, 0 as avg_cpc, 0 as avg_cpm, 0 as search_impr_share, 0 as search_lost_is_budget, 0 as vv_initiate_booking, 0 as total_conversions, 0 as video_completions, 0 as homepage, 0 as all_pages 
from hive_schema_stg.hvtb_nbx_landing_paidmedia_social social 
UNION 
select 'Search' as channel, search.day as date, search.account as platform, null as subplatform, search.campaign as campaign,
null as objective, null as tactic, null as target, null as tactic_updated, null as ad_name, null as earned_paid, search.impr as impressions, 0 as impressions_measurable, 0 as impressions_viewable, search.clicks as clicks, 0 as leads, search.vv_bookings as bookings, search.cost as spend, 0 as post_engagement, null as ad_format, search.engine engine, search.geo as geo, search.brand_nb brand_nb, search.nb_re_launch as nb_relaunch, 0 as post_comments, 0 as post_reactions, 0 as post_saves, 0 as post_shares, search.ctr as ctr, search.avg_cpc as avg_cpc, search.avg_cpm as avg_cpm, search.search_impr_share as search_impr_share, search.search_lost_is as search_lost_is_budget, search.vv_initiate_booking as vv_initiate_booking, 0 as total_conversions, 0 as video_completions, 0 as homepage, 0 as all_pages 
from hive_schema_stg.hvtb_nbx_landing_paidmedia_search search 
UNION 
select programmatic.channel as channel, programmatic.date as date, programmatic.platform as platform, null as subplatform, programmatic.campaign as campaign,
programmatic.objective as objective, programmatic.tactic as tactic, programmatic.audience as target, null as tactic_updated, programmatic.adname as ad_name, null as earned_paid, programmatic.impressions as impressions, programmatic.measurableimpressions as impressions_measurable, programmatic.viewableimpressions as impressions_viewable, programmatic.clicks as clicks, 0 as leads, programmatic.bookings as bookings, programmatic.spend as spend, 0 as post_engagement, programmatic.format as ad_format, null as engine, null as geo, null as brand_nb, null as nb_relaunch, 0 as post_comments, 0 as post_reactions, 0 as post_saves, 0 as post_shares, 0 as ctr, 0 as avg_cpc, 0 as avg_cpm, 0 as search_impr_share, 0 as search_lost_is_budget, 0 as vv_initiate_booking, programmatic.total_conversions as total_conversions, programmatic.video_completions as video_completions, programmatic.homepage as homepage, programmatic.all_pages as all_pages 
from hive_schema_stg.hvtb_nbx_landing_paidmedia_programmatic programmatic 
with no schema binding
; 

