create TABLE IF NOT EXISTS CAMPAIGN (
	CAMPAIGN_KEY NUMBER(38,0) NOT NULL COMMENT 'Incremental value and primary key of the table.',
	CAMPAIGN_NM VARCHAR(16777216) NOT NULL COMMENT '\t\nThe entire advertising effort conducted within a predetermined time frame, usually driven by a set of advertising goals. A campaign includes criteria such as media vehicle, markets, demos, dayparts, flight dates and spot lengths.',
	CAMPAIGN_DESC VARCHAR(16777216) COMMENT 'The entire advertising effort conducted within a predetermined time frame, usually driven by a set of advertising goals. A campaign includes criteria such as media vehicle, markets, demos, dayparts, flight dates and spot lengths.This provides more details.',
	STANDARD_CAMPAIGN_NM VARCHAR(16777216) COMMENT 'Brand level standard Campaign Name',
	STANDARD_CAMPAIGN_DESC VARCHAR(16777216) COMMENT 'Brand level standard Campaign Description',
	STANDARD_OBJECTIVE_TYP VARCHAR(16777216) COMMENT 'Standard Objective of the Campaign',
	MEDIA_TYP VARCHAR(16777216) COMMENT 'Type of Media like TV, Digital, Social/Search etc.',
	BRAND_ID VARCHAR(16777216) NOT NULL COMMENT 'Brand ',
	SOURCE_SYSTEM_NM VARCHAR(16777216) NOT NULL COMMENT 'Source system name.',
	EFFECTIVE_BEGIN_DT DATE NOT NULL COMMENT 'This is the date the Record Became Active',
	EFFECTIVE_END_DT DATE NOT NULL COMMENT 'This is the date the Record Expires. Default is 12/31/2099',
	LOAD_ID NUMBER(38,0) NOT NULL COMMENT 'This is the User Identifier of the Person or Process that Loaded the Table',
	LAST_UPDATED_DTTM TIMESTAMP_NTZ(9) NOT NULL COMMENT 'The Date/Datetime the Record was Inserted',
	CURRENT_IND NUMBER(1,0),
	primary key (CAMPAIGN_KEY)
)COMMENT='This table contains media campaign Information.'
;
create TABLE IF NOT EXISTS CHANNEL_HIERARCHY (
	CHANNEL_HIERARCHY_KEY NUMBER(38,0) NOT NULL COMMENT 'Incremental value and primary key of the table.',
	BRAND_ID VARCHAR(16777216) NOT NULL COMMENT 'Brand',
	CHANNEL_NM VARCHAR(16777216) NOT NULL COMMENT 'Type of Media or Network/ Station names.Values of Channel, Sub Channel, Sub Channel 2',
	CHANNEL_CATEGORY_NM VARCHAR(16777216) NOT NULL COMMENT 'Type of Media or Network/ Station names.Values of Channel, Sub Channel, Sub Channel 2',
	CHANNEL_SUBCATEGORY_NM VARCHAR(16777216) NOT NULL COMMENT 'Type of Media or Network/ Station names.Values of Channel, Sub Channel, Sub Channel 2',
	PARTNER_NM VARCHAR(16777216) NOT NULL COMMENT 'Partner Name, Level 4 data.Values of Partner.',
	SOURCE_SYSTEM_NM VARCHAR(16777216) NOT NULL COMMENT 'Source system name.',
	EFFECTIVE_BEGIN_DT DATE NOT NULL COMMENT 'This is the date the Record Became Active',
	EFFECTIVE_END_DT DATE NOT NULL COMMENT 'This is the date the Record Expires. Default is 12/31/2099',
	CURRENT_IND NUMBER(1,0),
	LOAD_ID NUMBER(38,0) NOT NULL COMMENT 'This is the User Identifier of the Person or Process that Loaded the Table',
	LAST_UPDATED_DTTM TIMESTAMP_NTZ(9) NOT NULL COMMENT 'The Date/Datetime the Record was Inserted',
	primary key (CHANNEL_HIERARCHY_KEY)
)COMMENT='This table contains Channel hierarchy details.'
;
create TABLE IF NOT EXISTS DAILY_DAY_PART_FLASH_SALES_FACT (
	STORE_ID VARCHAR(16777216) NOT NULL COMMENT 'Number that uniquely identifies the Store',
	BUSINESS_DT DATE NOT NULL COMMENT 'Date of the Flash Sales',
	BRAND_DAY_PART_NM VARCHAR(16777216) NOT NULL COMMENT 'This is the Name of the Date Part',
	BRAND_ID VARCHAR(16777216) NOT NULL COMMENT 'Brand for the Order\n',
	STORE_KEY NUMBER(38,0) COMMENT 'The Sorrogate Key from the Store Dimension',
	BUSINESS_DT_KEY NUMBER(38,0) COMMENT 'The Sorrogate Key representing the Business Date',
	CHANNEL_KEY NUMBER(38,0) COMMENT 'This is a sorrogate key for the Channel Dimension',
	CHANNEL_ID VARCHAR(16777216) NOT NULL COMMENT 'This is a unique Channel Identifier',
	IRB_DAY_PART_NM VARCHAR(16777216) COMMENT 'The Inspire Brands Daypart',
	CLOSED_HR TIME(9) COMMENT 'time the ticket was closed\n',
	TRX_CNT NUMBER(38,0) COMMENT 'Records whether order has been voided or not. (previously called GrossQuantity)',
	NET_SALES_AMT NUMBER(18,2) COMMENT 'Net Amount for the sales',
	SOURCE_SYSTEM_NM VARCHAR(16777216) COMMENT 'The POS System used to load the transaction  information',
	LOAD_TYP VARCHAR(16777216) COMMENT 'Indicates whether data is part of a large historical data pull or was added from a smaller data pull (daily, weekly etc.)',
	LOAD_ID NUMBER(38,0) COMMENT 'Indicates whether data is part of a large historical data pull or was added from a smaller data pull (daily, weekly etc.) \n',
	LOAD_DTTM TIMESTAMP_NTZ(9) COMMENT 'The Date/Datetime the Record was Inserted',
	UPDATE_ID VARCHAR(16777216) COMMENT 'This is the User Identifier of the Person or Process that Updated the Table',
	UPDATE_DTTM TIMESTAMP_NTZ(9) COMMENT 'The Date/Datetime the Record was Inserted',
	constraint XPKDAILY_DAY_PART_FLASH_SALES_FACT primary key (STORE_ID, BUSINESS_DT, BRAND_DAY_PART_NM, BRAND_ID),
	constraint DP_DDPFSF foreign key (BRAND_DAY_PART_NM, BRAND_ID) references DAY_PART(DAY_PART_NM,BRAND_ID)
);
create TABLE IF NOT EXISTS DAILY_FLASH_SALES_FACT cluster by (BUSINESS_DATE_KEY, STORE_ID, BRAND_ID)(
	STORE_ID VARCHAR(16777216) NOT NULL COMMENT 'Number that uniquely identifies the Store',
	BUSINESS_DT DATE NOT NULL COMMENT 'Date of the Flash Sales',
	STORE_KEY NUMBER(38,0) COMMENT 'This is a sorrogate key for the Store Dimension',
	BUSINESS_DATE_KEY NUMBER(38,0) COMMENT 'This is a sorrogate Key that represent the Business Date Key',
	BRAND_ID VARCHAR(16777216) COMMENT 'Brand for the Order',
	TRANSACTION_CNT NUMBER(38,0) COMMENT 'Records whether order has been voided or not. (previously called GrossQuantity)',
	NET_SALES_AMT NUMBER(18,2) COMMENT 'Net Amount for the sales',
	LOAD_TYP VARCHAR(16777216) COMMENT 'Indicates whether data is part of a large historical data pull or was added from a smaller data pull (daily, weekly etc.)',
	SOURCE_SYSTEM_NM VARCHAR(16777216) COMMENT 'The POS System used to load the transaction  information',
	LOAD_ID NUMBER(38,0) COMMENT 'Indicates whether data is part of a large historical data pull or was added from a smaller data pull (daily, weekly etc.) \n',
	LOAD_DTTM TIMESTAMP_NTZ(9) COMMENT 'The Date/Datetime the Record was Inserted',
	UPDATE_ID VARCHAR(16777216) COMMENT 'This is the User Identifier of the Person or Process that Updated the Table',
	UPDATE_DTTM TIMESTAMP_NTZ(9) COMMENT 'The Date/Datetime the Record was Inserted',
	constraint XPKDAILYFLASHSALES_FACT primary key (STORE_ID, BUSINESS_DT)
);
create TABLE IF NOT EXISTS DAILY_FLASH_SALES_FACT_BKP_20211018 (
	STORE_ID VARCHAR(16777216) NOT NULL COMMENT 'Number that uniquely identifies the Store',
	BUSINESS_DT DATE NOT NULL COMMENT 'Date of the Flash Sales',
	STORE_KEY NUMBER(38,0) COMMENT 'This is a sorrogate key for the Store Dimension',
	BUSINESS_DATE_KEY NUMBER(38,0) COMMENT 'This is a sorrogate Key that represent the Business Date Key',
	BRAND_ID VARCHAR(16777216) COMMENT 'Brand for the Order',
	TRANSACTION_CNT NUMBER(38,0) COMMENT 'Records whether order has been voided or not. (previously called GrossQuantity)',
	NET_SALES_AMT NUMBER(18,2) COMMENT 'Net Amount for the sales',
	LOAD_TYP VARCHAR(16777216) COMMENT 'Indicates whether data is part of a large historical data pull or was added from a smaller data pull (daily, weekly etc.)',
	SOURCE_SYSTEM_NM VARCHAR(16777216) COMMENT 'The POS System used to load the transaction  information',
	LOAD_ID NUMBER(38,0) COMMENT 'Indicates whether data is part of a large historical data pull or was added from a smaller data pull (daily, weekly etc.) \n',
	LOAD_DTTM TIMESTAMP_NTZ(9) COMMENT 'The Date/Datetime the Record was Inserted',
	UPDATE_ID VARCHAR(16777216) COMMENT 'This is the User Identifier of the Person or Process that Updated the Table',
	UPDATE_DTTM TIMESTAMP_NTZ(9) COMMENT 'The Date/Datetime the Record was Inserted',
	constraint XPKDAILYFLASHSALES_FACT primary key (STORE_ID, BUSINESS_DT)
);
create TABLE IF NOT EXISTS DAILY_FLASH_SALES_FACT_DEBUG (
	STORE_ID VARCHAR(16777216),
	BUSINESS_DT DATE,
	STORE_KEY NUMBER(38,0),
	BUSINESS_DATE_KEY NUMBER(38,0),
	BRAND_ID VARCHAR(16777216),
	TRANSACTION_CNT NUMBER(38,0),
	NET_SALES_AMT NUMBER(18,2),
	LOAD_TYP VARCHAR(16777216),
	SOURCE_SYSTEM_NM VARCHAR(16777216),
	LOAD_ID NUMBER(38,0),
	LOAD_DTTM TIMESTAMP_NTZ(9),
	UPDATE_ID VARCHAR(16777216),
	UPDATE_DTTM TIMESTAMP_NTZ(9)
);
create TABLE IF NOT EXISTS DAILY_FLASH_SALES_FACT_TST (
	STORE_ID VARCHAR(16777216) NOT NULL COMMENT 'Number that uniquely identifies the Store',
	BUSINESS_DT DATE NOT NULL COMMENT 'Date of the Flash Sales',
	STORE_KEY NUMBER(38,0) COMMENT 'This is a sorrogate key for the Store Dimension',
	BUSINESS_DATE_KEY NUMBER(38,0) COMMENT 'This is a sorrogate Key that represent the Business Date Key',
	BRAND_ID VARCHAR(16777216) COMMENT 'Brand for the Order',
	TRANSACTION_CNT NUMBER(18,2) COMMENT 'Records whether order has been voided or not. (previously called GrossQuantity)',
	NET_SALES_AMT NUMBER(38,2) COMMENT 'Net Amount for the sales',
	LOAD_TYP VARCHAR(16777216) COMMENT 'Indicates whether data is part of a large historical data pull or was added from a smaller data pull (daily, weekly etc.)',
	SOURCE_SYSTEM_NM VARCHAR(16777216) COMMENT 'The POS System used to load the transaction  information',
	LOAD_ID NUMBER(38,0) COMMENT 'Indicates whether data is part of a large historical data pull or was added from a smaller data pull (daily, weekly etc.) \n',
	LOAD_DTTM TIMESTAMP_NTZ(9) COMMENT 'The Date/Datetime the Record was Inserted',
	UPDATE_ID VARCHAR(16777216) COMMENT 'This is the User Identifier of the Person or Process that Updated the Table',
	UPDATE_DTTM TIMESTAMP_NTZ(9) COMMENT 'The Date/Datetime the Record was Inserted',
	constraint XPKDAILYFLASHSALES_FACT primary key (STORE_ID, BUSINESS_DT)
);
create TABLE IF NOT EXISTS DAILY_FLASH_SALES_FACT_TST1 (
	STORE_ID VARCHAR(16777216) NOT NULL COMMENT 'Number that uniquely identifies the Store',
	BUSINESS_DT DATE NOT NULL COMMENT 'Date of the Flash Sales',
	STORE_KEY NUMBER(38,0) COMMENT 'This is a sorrogate key for the Store Dimension',
	BUSINESS_DATE_KEY NUMBER(38,0) COMMENT 'This is a sorrogate Key that represent the Business Date Key',
	BRAND_ID VARCHAR(16777216) COMMENT 'Brand for the Order',
	TRANSACTION_CNT NUMBER(18,2) COMMENT 'Records whether order has been voided or not. (previously called GrossQuantity)',
	NET_SALES_AMT NUMBER(38,2) COMMENT 'Net Amount for the sales',
	LOAD_TYP VARCHAR(16777216) COMMENT 'Indicates whether data is part of a large historical data pull or was added from a smaller data pull (daily, weekly etc.)',
	SOURCE_SYSTEM_NM VARCHAR(16777216) COMMENT 'The POS System used to load the transaction  information',
	LOAD_ID NUMBER(38,0) COMMENT 'Indicates whether data is part of a large historical data pull or was added from a smaller data pull (daily, weekly etc.) \n',
	LOAD_DTTM TIMESTAMP_NTZ(9) COMMENT 'The Date/Datetime the Record was Inserted',
	UPDATE_ID VARCHAR(16777216) COMMENT 'This is the User Identifier of the Person or Process that Updated the Table',
	UPDATE_DTTM TIMESTAMP_NTZ(9) COMMENT 'The Date/Datetime the Record was Inserted',
	constraint XPKDAILYFLASHSALES_FACT primary key (STORE_ID, BUSINESS_DT)
);
create TABLE IF NOT EXISTS DAILY_FLASH_SALES_FACT_TST2 (
	STORE_ID VARCHAR(16777216) NOT NULL COMMENT 'Number that uniquely identifies the Store',
	BUSINESS_DT DATE NOT NULL COMMENT 'Date of the Flash Sales',
	STORE_KEY NUMBER(38,0) COMMENT 'This is a sorrogate key for the Store Dimension',
	BUSINESS_DATE_KEY NUMBER(38,0) COMMENT 'This is a sorrogate Key that represent the Business Date Key',
	BRAND_ID VARCHAR(16777216) COMMENT 'Brand for the Order',
	TRANSACTION_CNT NUMBER(38,0) COMMENT 'Records whether order has been voided or not. (previously called GrossQuantity)',
	NET_SALES_AMT NUMBER(18,2) COMMENT 'Net Amount for the sales',
	LOAD_TYP VARCHAR(16777216) COMMENT 'Indicates whether data is part of a large historical data pull or was added from a smaller data pull (daily, weekly etc.)',
	SOURCE_SYSTEM_NM VARCHAR(16777216) COMMENT 'The POS System used to load the transaction  information',
	LOAD_ID NUMBER(38,0) COMMENT 'Indicates whether data is part of a large historical data pull or was added from a smaller data pull (daily, weekly etc.) \n',
	LOAD_DTTM TIMESTAMP_NTZ(9) COMMENT 'The Date/Datetime the Record was Inserted',
	UPDATE_ID VARCHAR(16777216) COMMENT 'This is the User Identifier of the Person or Process that Updated the Table',
	UPDATE_DTTM TIMESTAMP_NTZ(9) COMMENT 'The Date/Datetime the Record was Inserted',
	constraint XPKDAILYFLASHSALES_FACT primary key (STORE_ID, BUSINESS_DT)
);
create TABLE IF NOT EXISTS DAILY_FLASH_SALES_STG (
	SESSION_NO VARCHAR(16777216),
	TIME_INTERVAL VARCHAR(16777216),
	BRAND_ID VARCHAR(16777216),
	STORE_ID VARCHAR(16777216),
	BUSINESS_DT DATE,
	FISCAL_WEEK_NBR NUMBER(38,0),
	NET_SALES NUMBER(38,2),
	TRANS_CNT NUMBER(38,0),
	COMP_SALES NUMBER(38,2),
	COMP_TRANS NUMBER(38,0),
	DMA_NAME VARCHAR(16777216),
	DMA_CODE VARCHAR(16777216),
	OWNERSHIP_TYPE VARCHAR(16777216),
	STATE VARCHAR(16777216),
	COUNTRY VARCHAR(16777216),
	OPEN_DATE DATE,
	CLOSURE_DATE DATE,
	TEMP_CLOSED_DATE DATE,
	REOPEN_DATE DATE,
	THRESHOLD_FLAG BOOLEAN
);
create TABLE IF NOT EXISTS DAY_PART (
	DAY_PART_NM VARCHAR(16777216) NOT NULL COMMENT 'This is the Name of the Date Part',
	BRAND_ID VARCHAR(16777216) NOT NULL COMMENT 'Brand for the Order\n',
	DAY_PART_START_TM TIME(9) COMMENT 'This is the Start time for the Day part',
	DAY_PART_END_TM TIME(9) COMMENT 'This is the Start time for the Day part',
	SOURCE_SYSTEM_NM VARCHAR(16777216) COMMENT 'The POS System used to load the transaction  information\n',
	LOAD_ID NUMBER(38,0) COMMENT ' Indicates whether data is part of a large historical data pull or was added from a smaller data pull (daily, weekly etc.) \n',
	LOAD_DTTM TIMESTAMP_NTZ(9) COMMENT '\nThe Date/Datetime the Record was Inserted',
	UPDATE_ID NUMBER(38,0) COMMENT 'This is the User Identifier of the Person or Process that Updated the Table',
	UPDATE_DTTM TIMESTAMP_NTZ(9) COMMENT 'The Date/Datetime the Record was Updated',
	constraint XPKDAY_PART primary key (DAY_PART_NM, BRAND_ID)
);
create TABLE IF NOT EXISTS DAY_PART_OLD (
	DAY_PART_NM VARCHAR(16777216),
	BRAND_ID VARCHAR(16777216),
	DAY_PART_START_TM TIME(9),
	DAY_PART_END_TM TIME(9),
	SOURCE_SYSTEM_NM VARCHAR(16777216),
	LOAD_ID NUMBER(38,0),
	LOAD_DTTM TIMESTAMP_NTZ(9),
	UPDATE_ID NUMBER(38,0),
	UPDATE_DTTM TIMESTAMP_NTZ(9)
);
create TABLE IF NOT EXISTS DEVICE_TYP_DIM (
	DEVICE_TYP_KEY NUMBER(38,0) NOT NULL COMMENT 'This is unique Identifier for a Device, This is a sorrogate Key',
	DEVICE_SCRN_RESOL_NM VARCHAR(16777216) NOT NULL COMMENT 'The resolution of the device''s screen, expressed in pixel width x height (e.g., \"800x600\").\n',
	DEVICE_LANG_NM VARCHAR(16777216) NOT NULL COMMENT 'The language the device is set to use. Expressed as the IETF language code.\n',
	DEVICE_CAT VARCHAR(16777216) NOT NULL COMMENT 'The type of device (Mobile, Tablet, Desktop).\n',
	MOBILE_DEVICE_INFO_NM VARCHAR(16777216) NOT NULL COMMENT 'The branding, model, and marketing name used to identify the mobile device.\n',
	BROWSER_TYP VARCHAR(16777216) COMMENT 'The browser used (e.g., \"Chrome\" or \"Firefox\").\n',
	BROWSER_VERSION_NM VARCHAR(16777216) COMMENT 'The version of the browser used.\n',
	BROWSER_SIZE_NM VARCHAR(16777216) COMMENT 'The viewport size of users'' browsers. This captures the initial dimensions of the viewport in pixels and is formatted as width x height, for example, 1920x960.\n',
	OS_TYP VARCHAR(16777216) COMMENT 'The operating system of the device (e.g., \"Macintosh\" or \"Windows\").\n',
	OS_VER_NBR VARCHAR(16777216) COMMENT 'The version of the operating system.\n\n',
	MOBILE_DEVICE_BRANDING_NM VARCHAR(16777216) COMMENT 'The brand or manufacturer of the device.\n',
	MOBILE_DEVICE_MODEL_NBR VARCHAR(16777216) COMMENT 'The mobile device model.\n',
	MOBILE_INPUT_SELECTOR_NM VARCHAR(16777216) COMMENT 'Selector (e.g., touchscreen, joystick, clickwheel, stylus) used on the mobile device.\n',
	MOBILE_DEVICE_MKT_NM VARCHAR(16777216) COMMENT 'The marketing name used for the mobile device.\n',
	FLASH_VER_NBR VARCHAR(16777216) COMMENT 'The version of the Adobe Flash plugin that is installed on the browser.\n',
	JAVA_ENABLED_IND BOOLEAN COMMENT 'Whether or not Java is enabled in the browser.\n',
	SCREEN_COLOR_TXT VARCHAR(16777216) COMMENT 'Number of colors supported by the display, expressed as the bit-depth (e.g., \"8-bit\", \"24-bit\", etc.).\n',
	SOURCE_SYSTEM_NM VARCHAR(16777216) COMMENT 'The POS System used to load the transaction  information\n',
	LOAD_TYP VARCHAR(16777216) COMMENT 'Indicates whether data is part of a large historical data pull or was added from a smaller data pull (daily, weekly etc.) \n',
	LOAD_ID NUMBER(38,0) COMMENT ' Indicates whether data is part of a large historical data pull or was added from a smaller data pull (daily, weekly etc.) \n',
	LOAD_DTTM TIMESTAMP_NTZ(9) COMMENT '\nThe Date/Datetime the Record was Inserted',
	UPDATE_ID NUMBER(38,0) COMMENT 'This is the User Identifier of the Person or Process that Updated the Table',
	UPDATE_DTTM TIMESTAMP_NTZ(9) COMMENT 'The Date/Datetime the Record was Updated',
	constraint XPKDEVICE_TYPE_DIMENSION primary key (DEVICE_TYP_KEY)
)COMMENT='This section contains information about the user devices.\n'
;
create TABLE IF NOT EXISTS FLYWAY_SCHEMA_HISTORY (
	INSTALLED_RANK NUMBER(38,0) NOT NULL,
	VERSION VARCHAR(50),
	DESCRIPTION VARCHAR(200),
	TYPE VARCHAR(20) NOT NULL,
	SCRIPT VARCHAR(1000) NOT NULL,
	CHECKSUM NUMBER(38,0),
	INSTALLED_BY VARCHAR(100) NOT NULL,
	INSTALLED_ON TIMESTAMP_LTZ(9) NOT NULL DEFAULT CURRENT_TIMESTAMP(),
	EXECUTION_TIME NUMBER(38,0) NOT NULL,
	SUCCESS BOOLEAN NOT NULL,
	primary key (INSTALLED_RANK)
);
create TABLE IF NOT EXISTS GEO_NTWK_LOC_DIM (
	GEO_NTWK_LOC_KEY NUMBER(38,0) NOT NULL COMMENT 'This is the Sorrogate Key for the Network Location Dimension Junk Table',
	CONT_NM VARCHAR(16777216) COMMENT 'The continent from which sessions originated, based on IP address.\n',
	SUBCONT_NM VARCHAR(16777216) COMMENT 'The sub-continent from which sessions originated, based on IP address of the visitor.\n',
	CNTRY_NM VARCHAR(16777216) COMMENT 'The country from which sessions originated, based on IP address.\n',
	REGION_NM VARCHAR(16777216) COMMENT 'The region from which sessions originate, derived from IP addresses. In the U.S., a region is a state, such as New York.\n',
	METRO_NM VARCHAR(16777216) COMMENT 'The Designated Market Area (DMA) from which sessions originate.\n',
	CITY_ID VARCHAR(16777216) COMMENT 'Users'' city ID, derived from their IP addresses or Geographical IDs. The city IDs are the same as the Criteria IDs found at https://developers.google.com/         analytics/devguides/collection/         protocol/v1/geoid.\n',
	CITY_NM VARCHAR(16777216) COMMENT 'Users'' city, derived from their IP addresses or Geographical IDs.\n',
	SOURCE_SYSTEM_NM VARCHAR(16777216) COMMENT 'The POS System used to load the transaction  information\n',
	LOAD_TYP VARCHAR(16777216) COMMENT 'Indicates whether data is part of a large historical data pull or was added from a smaller data pull (daily, weekly etc.) \n',
	LOAD_ID NUMBER(38,0) COMMENT ' Indicates whether data is part of a large historical data pull or was added from a smaller data pull (daily, weekly etc.) \n',
	LOAD_DTTM TIMESTAMP_NTZ(9) COMMENT '\nThe Date/Datetime the Record was Inserted',
	UPDATE_ID NUMBER(38,0) COMMENT 'This is the User Identifier of the Person or Process that Updated the Table',
	UPDATE_DTTM TIMESTAMP_NTZ(9) COMMENT 'The Date/Datetime the Record was Updated',
	constraint XAK1GEOGRAPHY_NETWORK_LOCATION_DIMENSION unique (CONT_NM, REGION_NM, SUBCONT_NM, CITY_ID, CITY_NM, CNTRY_NM, METRO_NM, SOURCE_SYSTEM_NM),
	constraint XPKGEOGRAPHY_NETWORK_LOCATION_DIMENSION primary key (GEO_NTWK_LOC_KEY)
);
create TABLE IF NOT EXISTS INSPIRE_DAILY_OFFER_SALES_TEST (
	BUSINESS_DT DATE,
	BRAND VARCHAR(16777216),
	STORE_NBR VARCHAR(16777216),
	DMA_CD VARCHAR(16777216),
	DMA_NM VARCHAR(16777216),
	L1NAME VARCHAR(16777216),
	L2NAME VARCHAR(16777216),
	L3NAME VARCHAR(16777216),
	L4NAME VARCHAR(16777216),
	L5NAME VARCHAR(16777216),
	OWNERSHIP_TYP VARCHAR(16777216),
	STATE VARCHAR(16777216),
	COUNTRY VARCHAR(16777216),
	FISC_YEAR_NBR NUMBER(38,0),
	FISC_QUARTER_NBR NUMBER(38,0),
	FISC_PERIOD_NBR NUMBER(38,0),
	FISC_WEEK_NBR NUMBER(38,0),
	DAY_OF_WEEK VARCHAR(16777216),
	HOLIDAY_IND_CY VARCHAR(16777216),
	HOLIDAY_NM_CY VARCHAR(16777216),
	MDM_OFFER_ID NUMBER(38,0),
	MDM_OFFER_NM VARCHAR(16777216),
	DISCOUNT_AMT_CY NUMBER(38,2),
	OFFER_CNT_CY NUMBER(38,2),
	CHECK_SALES_CY NUMBER(38,2),
	CHECK_CNT_CY NUMBER(38,2),
	REST_SALES_CY NUMBER(38,2),
	REST_TRANS_CY NUMBER(38,2),
	FISC_DATE_LY DATE,
	FISC_HOLIDAY_IND_LY VARCHAR(16777216),
	FISC_HOLIDAY_NM_LY VARCHAR(16777216),
	FISC_DISCOUNT_AMT_LY NUMBER(38,2),
	FISC_OFFER_CNT_LY NUMBER(38,2),
	FISC_CHECK_SALES_LY NUMBER(38,2),
	FISC_CHECK_CNT_LY NUMBER(38,2),
	FISC_REST_SALES_LY NUMBER(38,2),
	FISC_REST_TRANS_LY NUMBER(38,2),
	CAL_COMP_DATE_LY DATE,
	CAL_HOLIDAY_IND_LY VARCHAR(16777216),
	CAL_HOLIDAY_NM_LY VARCHAR(16777216),
	CAL_DISCOUNT_AMT_LY NUMBER(38,2),
	CAL_OFFER_CNT_LY NUMBER(38,2),
	CAL_CHECK_SALES_LY NUMBER(38,2),
	CAL_CHECK_CNT_LY NUMBER(38,2),
	CAL_REST_SALES_LY NUMBER(38,2),
	CAL_REST_TRANS_LY NUMBER(38,2),
	OFFER_HIERARCHY_ID VARCHAR(16777216),
	LEVEL5_OFFER_HIERARCHY_NM VARCHAR(16777216),
	LEVEL4_OFFER_HIERARCHY_NM VARCHAR(16777216),
	LEVEL3_OFFER_HIERARCHY_NM VARCHAR(16777216),
	LEVEL2_OFFER_HIERARCHY_NM VARCHAR(16777216),
	LEVEL1_OFFER_HIERARCHY_NM VARCHAR(16777216),
	OFFER_MISC1 VARCHAR(16777216),
	OFFER_MISC2 VARCHAR(16777216),
	OFFER_MISC3 VARCHAR(16777216),
	OFFER_MISC4 VARCHAR(16777216),
	OFFER_MISC5 VARCHAR(16777216),
	OFFER_MISC6 VARCHAR(16777216),
	OFFER_MISC7 VARCHAR(16777216),
	OFFER_MISC8 VARCHAR(16777216),
	OFFER_MISC9 VARCHAR(16777216),
	OFFER_MISC10 VARCHAR(16777216)
);
create TABLE IF NOT EXISTS LOYALTY_ORDER_FACT (
	TRANSACTION_ID VARCHAR(16777216) NOT NULL COMMENT 'Unique ID for loyalty transaction',
	CUSTOMER_KEY NUMBER(38,0) COMMENT 'This is a sorrogate key for the Customer Dimension',
	STORE_KEY NUMBER(38,0),
	BUSINESS_DATE_KEY NUMBER(38,0),
	EMPLOYEE_KEY NUMBER(38,0),
	ORDER_ID VARCHAR(16777216) COMMENT 'OrderID uniquely defines each order for each brand',
	EMPLOYEE_ID VARCHAR(16777216) COMMENT 'ID of the employee who is serving a customer or who took the order',
	MEMBER_ID VARCHAR(16777216) COMMENT 'A unique ID that is internally generated any time a customer joins the loyalty program/system.',
	STORE_ID VARCHAR(16777216) COMMENT 'Store Number that uniquely identifies the store ( from FRM)',
	BRAND_ID VARCHAR(16777216) COMMENT 'Brand associated with the transaction ',
	BUSINESS_DT DATE COMMENT 'The Date of the Transaction',
	EMPLOYEE_NM VARCHAR(16777216) COMMENT 'Name of the staff Member serving the customer',
	CHECK_NBR VARCHAR(16777216) COMMENT 'This is an incremental number that starts at one each business day to record customer order. Number restarts from one each day.',
	MEMBER_CARD_NBR VARCHAR(16777216) COMMENT 'A loyalty number that is used to link a transaction to a customer’s loyalty profile',
	DOLLAR_NET_VALUE_AMT NUMBER(18,2) COMMENT 'Net Amount in dollar paid by the customer',
	ELIGIBLE_REVENUE_AMT NUMBER(18,2) COMMENT 'Amount that is eligible for loyalty rewards. There could be certain items within a transaction that don’t qualify for loyalty rewards.',
	ATTACHMENT_METHOD_TYP VARCHAR(16777216) COMMENT 'Channel through which loyalty rewards were linked to a profile. Ex: At store, POS or through customer service for missing transaction.',
	TRANSACTION_STATUS_TYP VARCHAR(16777216) COMMENT 'Transaction status, if the transaction is pending or closed',
	MEMBER_PHONE_NBR VARCHAR(16777216) COMMENT 'Phone number of the member collected during transaction',
	REASON_CD VARCHAR(16777216) COMMENT 'Reason why certain items disqualified from earning loyalty rewards.',
	MIN_DAY_PART_ID VARCHAR(16777216) COMMENT 'Breakfast, Lunch, Dinner are different Dayparts for restaurants. If an item is part of multiple dayparts, then the earliest daypart is considered for this field',
	MAX_DAY_PART_ID VARCHAR(16777216) COMMENT 'Breakfast ,Lunch, Dinner are different Dayparts for restaurants. If an item is part of multiple dayparts, then the latest daypart is considered for this field',
	SUSPENDED_TRANSACTION_ID VARCHAR(16777216) COMMENT 'A ID generated when a Loyalty transaction is suspended.\n\nMostly valid for BWWs',
	SUSPENDED_TRANSACTION_STATUS_IND BOOLEAN COMMENT 'The Status to indicate if the suspension is active or not.\n\nMostly valid for BWWs',
	SOURCE_SYSTEM_NM VARCHAR(16777216) COMMENT 'The POS System used to load the transaction  information\n',
	LOAD_TYP VARCHAR(16777216) COMMENT 'Indicates whether data is part of a large historical data pull or was added from a smaller data pull (daily, weekly etc.) \n',
	LOAD_ID VARCHAR(16777216) COMMENT ' Indicates whether data is part of a large historical data pull or was added from a smaller data pull (daily, weekly etc.) \n',
	LOAD_DTTM TIMESTAMP_NTZ(9) COMMENT '\nThe Date/Datetime the Record was Inserted',
	UPDATE_ID VARCHAR(16777216) COMMENT 'This is the User Identifier of the Person or Process that Updated the Table',
	UPDATE_DTTM TIMESTAMP_NTZ(9) COMMENT 'The Date/Datetime the Record was Updated',
	constraint XPKLOYALTY_ORDER_FACT primary key (TRANSACTION_ID)
);
create TABLE IF NOT EXISTS MEDIA_ACTIVITY_FACT (
	CHANNEL_HIERARCHY_KEY NUMBER(38,0) NOT NULL COMMENT 'Incremental value and primary key of the table.',
	WEEK_START_DT DATE NOT NULL COMMENT 'Start of the Week',
	SPEND_AMT NUMBER(38,6) COMMENT 'Amount Spent.',
	CURRENCY_CD VARCHAR(10) COMMENT 'Currency Code',
	BRAND_ID VARCHAR(16777216) NOT NULL,
	DMA_CD VARCHAR(16777216) NOT NULL COMMENT 'DMA Code provided by Nielsen',
	IMPRESSIONS_CNT NUMBER(38,2) COMMENT 'Number of views',
	RATINGS_CNT NUMBER(38,2) COMMENT 'Rating of a program',
	CLICKS_CNT NUMBER(38,0) COMMENT 'Number of Clicks',
	GRP_CNT NUMBER(38,2) COMMENT 'This is the Gross Rating Point of the Program or Advert',
	TRP_CNT NUMBER(38,2) COMMENT 'This is the Target Rating Point of the Program or Advert',
	LOAD_ID NUMBER(38,0) NOT NULL COMMENT 'This is the User Identifier of the Person or Process that Loaded the Table',
	LAST_UPDATED_DTTM TIMESTAMP_NTZ(9) NOT NULL COMMENT 'The Date/Datetime the Record was Inserted',
	SOURCE_SYSTEM_NM VARCHAR(16777216) NOT NULL COMMENT 'Source system name.',
	SPEND_TYPE_KEY NUMBER(38,0) COMMENT 'Auto-Incremental',
	STRATEGY_KEY NUMBER(38,0) NOT NULL COMMENT 'Incremental value and primary key of the table.',
	CAMPAIGN_KEY NUMBER(38,0) NOT NULL COMMENT 'Incremental value and primary key of the table.',
	primary key (CAMPAIGN_KEY, STRATEGY_KEY, CHANNEL_HIERARCHY_KEY, DMA_CD, WEEK_START_DT),
	foreign key (SPEND_TYPE_KEY) references SPEND_TYPE(SPEND_TYPE_KEY),
	foreign key (CAMPAIGN_KEY) references CAMPAIGN(CAMPAIGN_KEY),
	foreign key (CHANNEL_HIERARCHY_KEY) references CHANNEL_HIERARCHY(CHANNEL_HIERARCHY_KEY),
	foreign key (STRATEGY_KEY) references STRATEGY(STRATEGY_KEY)
);
create TABLE IF NOT EXISTS MEDIA_ACTIVITY_UPLIFT (
	DMACODE VARCHAR(16777216),
	WEEKSTARTDATE TIMESTAMP_NTZ(9),
	CHANNEL VARCHAR(16777216),
	SUBCHANNEL VARCHAR(16777216),
	SUBCHANNEL2 VARCHAR(16777216),
	PARTNER VARCHAR(16777216),
	SPENDAMOUNT FLOAT,
	ACTIVITY FLOAT,
	TRANSUPLIFT FLOAT,
	TRANSEFFICIENCY FLOAT,
	TRANSMARGINAL FLOAT
);
create TABLE IF NOT EXISTS MMO_TOTAL_ACTIVITY_UPLIFT (
	DMACODE VARCHAR(16777216),
	WEEKSTARTDATE TIMESTAMP_NTZ(9),
	GROUP1 VARCHAR(16777216),
	GROUP2 VARCHAR(16777216),
	GROUP3 VARCHAR(16777216),
	GROUP4 VARCHAR(16777216),
	GROUP5 VARCHAR(16777216),
	TRANSUPLIFT FLOAT
);
create TABLE IF NOT EXISTS ODI (
	ID NUMBER(38,0)
);
create TABLE IF NOT EXISTS ODITEST (
	ID NUMBER(38,0)
);
create TABLE IF NOT EXISTS ORDER_DETAIL_SUBSET_TBL (
	ORDER_ID VARCHAR(16777216),
	ORDERLINE_ID VARCHAR(16777216),
	ORDER_DT VARCHAR(16777216),
	ORDER_DT_KEY VARCHAR(16777216),
	ORDER_TM VARCHAR(16777216),
	STORE_ID VARCHAR(16777216),
	DMA_CD VARCHAR(16777216),
	DMA_NM VARCHAR(16777216),
	CHANNEL_ID VARCHAR(16777216),
	ORDER_CHANNEL_NM VARCHAR(16777216),
	LEVEL3_ORDER_CHANNEL_HIERARCHY_NM VARCHAR(16777216),
	LEVEL2_ORDER_CHANNEL_HIERARCHY_NM VARCHAR(16777216),
	LEVEL1_ORDER_CHANNEL_HIERARCHY_NM VARCHAR(16777216),
	FULFILLMENT_CHANNEL_NM VARCHAR(16777216),
	LEVEL3_FULFILLMENT_CHANNEL_HIERARCHY_NM VARCHAR(16777216),
	LEVEL2_FULFILLMENT_CHANNEL_HIERARCHY_NM VARCHAR(16777216),
	LEVEL1_FULFILLMENT_CHANNEL_HIERARCHY_NM VARCHAR(16777216),
	EMPLOYEE_ID VARCHAR(16777216),
	MANAGER_ID VARCHAR(16777216),
	REGISTER_ID VARCHAR(16777216),
	TAX_ID VARCHAR(16777216),
	MODIFIER_IND VARCHAR(16777216),
	TAXEXEMPT_ID VARCHAR(16777216),
	SEAT_NBR VARCHAR(16777216),
	MDM_ITEM_ID VARCHAR(16777216),
	SOURCE_SYSTEM_ID NUMBER(38,0),
	ITEM_NM VARCHAR(16777216),
	MDM_ITEM_TYP VARCHAR(16777216),
	MDM_PRODUCT_ID NUMBER(38,0),
	PRODUCT_NM VARCHAR(16777216),
	PRODUCT_DESC VARCHAR(16777216),
	PRODUCT_STATUS_CD VARCHAR(16777216),
	TECHNICAL_SIZE_NBR VARCHAR(16777216),
	UNIT_OF_MEASURE_VAL VARCHAR(16777216),
	NON_USA_SPECIALTY_IND VARCHAR(16777216),
	VEHICLE_NBR VARCHAR(16777216),
	HOT_PRODUCT_IND BOOLEAN,
	BREAKFAST_PRODUCT_IND BOOLEAN,
	PRODUCT_BRAND_NM VARCHAR(16777216),
	MENU_TYP VARCHAR(16777216),
	MENU_SECTION_TYP VARCHAR(16777216),
	GBB_MEASURE_VAL VARCHAR(16777216),
	COLD_SPACE_REQUIRED_IND BOOLEAN,
	FRYER_REQUIRED_IND BOOLEAN,
	PRODUCT_HIERARCHY_ID NUMBER(38,0),
	LEVEL5_PRODUCT_HIERARCHY_NM VARCHAR(16777216),
	LEVEL4_PRODUCT_HIERARCHY_NM VARCHAR(16777216),
	LEVEL3_PRODUCT_HIERARCHY_NM VARCHAR(16777216),
	LEVEL2_PRODUCT_HIERARCHY_NM VARCHAR(16777216),
	LEVEL1_PRODUCT_HIERARCHY_NM VARCHAR(16777216),
	MDM_OFFER_ID NUMBER(38,0),
	OFFER_NM VARCHAR(16777216),
	OFFER_DESC VARCHAR(16777216),
	OFFER_CAT VARCHAR(16777216),
	OFFER_TYP VARCHAR(16777216),
	LEVEL5_OFFER_HIERARCHY_NM VARCHAR(16777216),
	LEVEL4_OFFER_HIERARCHY_NM VARCHAR(16777216),
	LEVEL3_OFFER_HIERARCHY_NM VARCHAR(16777216),
	LEVEL2_OFFER_HIERARCHY_NM VARCHAR(16777216),
	LEVEL1_OFFER_HIERARCHY_NM VARCHAR(16777216),
	MDM_PARENT_ITEM_ID VARCHAR(16777216),
	PARENT_SOURCE_SYSTEM_ID NUMBER(38,0),
	PARENT_ITEM_NM VARCHAR(16777216),
	MDM_PARENT_ITEM_TYP VARCHAR(16777216),
	SOURCE_GROSS_QTY NUMBER(38,0),
	SOURCE_GROSS_AMT FLOAT,
	DISCOUNT_CD VARCHAR(16777216),
	DISCOUNT_NM VARCHAR(16777216),
	SOURCE_DISCOUNT_TYP VARCHAR(16777216),
	SOURCE_DISCOUNT_AMT FLOAT,
	SOURCE_NET_AMT FLOAT,
	DERIVED_GROSS_QTY NUMBER(38,0),
	RETAIL_PRICE_AMT FLOAT,
	DERIVED_GROSS_AMT FLOAT,
	DERIVED_NET_AMT FLOAT,
	DERIVED_DISCOUNT_AMT FLOAT,
	TAX_AMT FLOAT,
	CLEARED_IND VARCHAR(16777216),
	DELETED_IND VARCHAR(16777216),
	VOIDED_IND VARCHAR(16777216),
	INVENTORY_IND VARCHAR(16777216),
	ALTERNATE1_ORDER_ID VARCHAR(16777216),
	SOURCE_NM VARCHAR(16777216),
	BRAND_ID VARCHAR(16777216),
	LOAD_DT VARCHAR(16777216),
	LAST_UPDATED_DTTM VARCHAR(16777216),
	OFFER_MISC1 VARCHAR(16777216),
	OFFER_MISC2 VARCHAR(16777216),
	OFFER_MISC3 VARCHAR(16777216),
	OFFER_MISC4 VARCHAR(16777216),
	OFFER_MISC5 VARCHAR(16777216),
	OFFER_MISC6 VARCHAR(16777216),
	OFFER_MISC7 VARCHAR(16777216),
	OFFER_MISC8 VARCHAR(16777216),
	OFFER_MISC9 VARCHAR(16777216),
	OFFER_MISC10 VARCHAR(16777216),
	PRODUCT_MISC1 VARCHAR(16777216),
	PRODUCT_MISC2 VARCHAR(16777216),
	PRODUCT_MISC3 VARCHAR(16777216),
	PRODUCT_MISC4 VARCHAR(16777216),
	PRODUCT_MISC5 VARCHAR(16777216),
	PRODUCT_MISC6 VARCHAR(16777216),
	PRODUCT_MISC7 VARCHAR(16777216),
	PRODUCT_MISC8 VARCHAR(16777216),
	PRODUCT_MISC9 VARCHAR(16777216),
	PRODUCT_MISC10 VARCHAR(16777216),
	OFFER_HIERARCHY_ID VARCHAR(16777216)
);
create TABLE IF NOT EXISTS ORDER_DETAIL_TEST (
	ORDER_ID VARCHAR(16777216),
	ORDERLINE_ID VARCHAR(16777216),
	ORDER_DT DATE,
	ORDER_TM NUMBER(38,0),
	STORE_ID VARCHAR(16777216),
	DMA_CD VARCHAR(16777216),
	DMA_NM VARCHAR(16777216),
	CHANNEL_ID VARCHAR(16777216),
	ORDER_CHANNEL_NM VARCHAR(16777216),
	LEVEL3_ORDER_CHANNEL_HIERARCHY_NM VARCHAR(16777216),
	LEVEL2_ORDER_CHANNEL_HIERARCHY_NM VARCHAR(16777216),
	LEVEL1_ORDER_CHANNEL_HIERARCHY_NM VARCHAR(16777216),
	FULFILLMENT_CHANNEL_NM VARCHAR(16777216),
	LEVEL3_FULFILLMENT_CHANNEL_HIERARCHY_NM VARCHAR(16777216),
	LEVEL2_FULFILLMENT_CHANNEL_HIERARCHY_NM VARCHAR(16777216),
	LEVEL1_FULFILLMENT_CHANNEL_HIERARCHY_NM VARCHAR(16777216),
	EMPLOYEE_ID VARCHAR(16777216),
	MANAGER_ID VARCHAR(16777216),
	REGISTER_ID VARCHAR(16777216),
	TAX_ID VARCHAR(16777216),
	MODIFIER_IND BOOLEAN,
	TAXEXEMPT_ID VARCHAR(16777216),
	SEAT_NBR VARCHAR(16777216),
	MDM_ITEM_ID NUMBER(38,0),
	SOURCE_SYSTEM_ID NUMBER(38,0),
	ITEM_NM VARCHAR(16777216),
	MDM_ITEM_TYP VARCHAR(16777216),
	MDM_PRODUCT_ID NUMBER(38,0),
	PRODUCT_NM VARCHAR(16777216),
	PRODUCT_DESC VARCHAR(16777216),
	PRODUCT_STATUS_CD VARCHAR(16777216),
	TECHNICAL_SIZE_NBR VARCHAR(16777216),
	UNIT_OF_MEASURE_VAL VARCHAR(16777216),
	NON_USA_SPECIALTY_IND VARCHAR(16777216),
	VEHICLE_NBR VARCHAR(16777216),
	HOT_PRODUCT_IND BOOLEAN,
	BREAKFAST_PRODUCT_IND BOOLEAN,
	PRODUCT_BRAND_NM VARCHAR(16777216),
	MENU_TYP VARCHAR(16777216),
	MENU_SECTION_TYP VARCHAR(16777216),
	GBB_MEASURE_VAL VARCHAR(16777216),
	COLD_SPACE_REQUIRED_IND BOOLEAN,
	FRYER_REQUIRED_IND BOOLEAN,
	PRODUCT_HIERARCHY_ID NUMBER(38,0),
	LEVEL5_PRODUCT_HIERARCHY_NM VARCHAR(16777216),
	LEVEL4_PRODUCT_HIERARCHY_NM VARCHAR(16777216),
	LEVEL3_PRODUCT_HIERARCHY_NM VARCHAR(16777216),
	LEVEL2_PRODUCT_HIERARCHY_NM VARCHAR(16777216),
	LEVEL1_PRODUCT_HIERARCHY_NM VARCHAR(16777216),
	MDM_OFFER_ID NUMBER(38,0),
	OFFER_NM VARCHAR(16777216),
	OFFER_DESC VARCHAR(16777216),
	OFFER_CAT VARCHAR(16777216),
	OFFER_TYP VARCHAR(16777216),
	LEVEL5_OFFER_HIERARCHY_NM VARCHAR(16777216),
	LEVEL4_OFFER_HIERARCHY_NM VARCHAR(16777216),
	LEVEL3_OFFER_HIERARCHY_NM VARCHAR(16777216),
	LEVEL2_OFFER_HIERARCHY_NM VARCHAR(16777216),
	LEVEL1_OFFER_HIERARCHY_NM VARCHAR(16777216),
	MDM_PARENT_ITEM_ID NUMBER(38,0),
	PARENT_SOURCE_SYSTEM_ID NUMBER(38,0),
	PARENT_ITEM_NM VARCHAR(16777216),
	MDM_PARENT_ITEM_TYP VARCHAR(16777216),
	SOURCE_GROSS_QTY NUMBER(38,0),
	SOURCE_GROSS_AMT NUMBER(18,2),
	DISCOUNT_CD VARCHAR(16777216),
	DISCOUNT_NM VARCHAR(16777216),
	SOURCE_DISCOUNT_TYP VARCHAR(16777216),
	SOURCE_DISCOUNT_AMT NUMBER(18,2),
	SOURCE_NET_AMT NUMBER(18,2),
	DERIVED_GROSS_QTY NUMBER(38,0),
	RETAIL_PRICE_AMT NUMBER(18,2),
	DERIVED_GROSS_AMT NUMBER(18,2),
	DERIVED_NET_AMT NUMBER(18,2),
	DERIVED_DISCOUNT_AMT NUMBER(18,2),
	TAX_AMT NUMBER(18,2),
	CLEARED_IND BOOLEAN,
	DELETED_IND BOOLEAN,
	VOIDED_IND BOOLEAN,
	INVENTORY_IND BOOLEAN,
	ALTERNATE1_ORDER_ID VARCHAR(16777216),
	SOURCE_NM VARCHAR(16777216),
	BRAND_ID VARCHAR(16777216),
	LOAD_DT NUMBER(38,0),
	LAST_UPDATED_DTTM TIMESTAMP_NTZ(9),
	OFFER_MISC1 VARCHAR(16777216),
	OFFER_MISC2 VARCHAR(16777216),
	OFFER_MISC3 VARCHAR(16777216),
	OFFER_MISC4 VARCHAR(16777216),
	OFFER_MISC5 VARCHAR(16777216),
	OFFER_MISC6 VARCHAR(16777216),
	OFFER_MISC7 VARCHAR(16777216),
	OFFER_MISC8 VARCHAR(16777216),
	OFFER_MISC9 VARCHAR(16777216),
	OFFER_MISC10 VARCHAR(16777216),
	PRODUCT_MISC1 VARCHAR(16777216),
	PRODUCT_MISC2 VARCHAR(16777216),
	PRODUCT_MISC3 VARCHAR(16777216),
	PRODUCT_MISC4 VARCHAR(16777216),
	PRODUCT_MISC5 VARCHAR(16777216),
	PRODUCT_MISC6 VARCHAR(16777216),
	PRODUCT_MISC7 VARCHAR(16777216),
	PRODUCT_MISC8 VARCHAR(16777216),
	PRODUCT_MISC9 VARCHAR(16777216),
	PRODUCT_MISC10 VARCHAR(16777216),
	OFFER_HIERARCHY_ID VARCHAR(16777216)
);
create TABLE IF NOT EXISTS ORDER_FACT (
	ORDER_ID VARCHAR(16777216) NOT NULL COMMENT 'OrderID uniquely defines each order\n',
	STORE_KEY NUMBER(38,0) COMMENT 'This is a sorrogate key for the Store Dimension',
	BUSINESS_DATE_KEY NUMBER(38,0),
	CUSTOMER_KEY NUMBER(38,0) COMMENT 'This is a sorrogate key for the Customer Dimension',
	CHANNEL_KEY NUMBER(38,0) COMMENT 'This is a sorrogate key for the Channel Dimension',
	EMPLOYEE_ID VARCHAR(16777216) COMMENT 'Employee responsible for order\n',
	BUSINESS_DT DATE COMMENT 'Date of the Order \n',
	STORE_ID VARCHAR(16777216) COMMENT 'Number that uniquely identifies the Store\n',
	CHECK_NBR VARCHAR(16777216) COMMENT 'Daily incremental ticket number\n',
	OPENED_TM TIMESTAMP_NTZ(9) COMMENT 'time the ticket was opened\n',
	CLOSED_TM TIMESTAMP_NTZ(9) COMMENT 'time the ticket was closed\n',
	ORDER_NM VARCHAR(16777216) COMMENT 'Name on the order\n',
	ITEM_CNT NUMBER(38,0) COMMENT 'Count of DerivedGrossQuantity from Orderline table where orderlinetype=''item''\n',
	TRANSACTION_CNT NUMBER(38,0) COMMENT 'Records whether order has been voided or not. (previously called GrossQuantity)\n',
	SOURCE_GROSS_AMT NUMBER(18,2) COMMENT 'Gross Amount for an order provided by source\n',
	SOURCE_DISCOUNT_AMT NUMBER(18,2) COMMENT 'Discount Amount for an order provided by source\n',
	SOURCE_NET_AMT NUMBER(18,2) COMMENT 'Net Amount for an order provided by source\n',
	SURCHARGE_AMT NUMBER(18,2) COMMENT 'Delivery fee for the order\n',
	TAX_AMT NUMBER(18,2) COMMENT 'Total amount of taxes charged for the order\n',
	SOURCE_PAYMENT_AMT NUMBER(18,2) COMMENT 'Total amount that customer paid for their order (a.k.a. subticket a.k.a. orderid)',
	GRATUITY_AMT NUMBER(18,2) COMMENT 'This would be the tip paid via credit card to the carhop.\n',
	CUSTOMER_NM VARCHAR(16777216) COMMENT 'This would be the customer’s name that an online order was placed under.\n',
	CUSTOMER_ID VARCHAR(16777216) COMMENT 'This would be the customer id that an online order was placed under.\n',
	LOYALTY_NBR VARCHAR(16777216) COMMENT 'This would be the number assigned to a customer for loyalty purposes.\n',
	FIRST_SEND_TM TIMESTAMP_NTZ(9) COMMENT 'This would be approximately the time when the ticket was opened.\n',
	CLOSED_IND BOOLEAN COMMENT 'Indicates whether the existing ticket has been closed or not.\n',
	FUTURE_ORDER_IND BOOLEAN COMMENT 'This would indicate whether the customer had requested a specific time to pick up an online order.\n',
	VOID_IND BOOLEAN COMMENT 'Indicates whether the order was cancelled \n',
	REFUND_IND BOOLEAN COMMENT 'Indicate if the Customer order was refunded for their order\n',
	TAX_EXEMPT_IND BOOLEAN COMMENT 'Indicates whether the customer has the tax exempt status \n',
	GUEST_CNT NUMBER(38,0) COMMENT 'Number of customer per ticket \n',
	BRAND_ID VARCHAR(16777216) COMMENT 'Brand for the Order\n',
	SOURCE_SYSTEM_NM VARCHAR(16777216) COMMENT 'The POS System used to load the transaction  information\n',
	TIME_KEY NUMBER(38,0) COMMENT 'Time sec  at which an order was created.\n',
	LOAD_TYP VARCHAR(16777216) COMMENT 'Indicates whether data is part of a large historical data pull or was added from a smaller data pull (daily, weekly etc.) \n',
	DERIVED_GROSS_AMT NUMBER(18,2) COMMENT 'Pre tax and pre discounted amount.\n',
	DERIVED_DISCOUNT_AMT NUMBER(18,2) COMMENT 'This is total amount of discounts that were applied to an order.\n',
	DERIVED_NET_AMT NUMBER(18,2) COMMENT 'Gross Amount - Discount Amount +Delivery Fee\n',
	MISC_CHARGE_AMT NUMBER(18,2) COMMENT 'sum of any amount not directly linked to Net sales from orderline\n',
	CHANNEL_ID VARCHAR(16777216) COMMENT 'Unique channel id to identify order and fulfullmint mode\n',
	ALTERNATE1_ORDER_ID VARCHAR(16777216) COMMENT 'Captures any other unique id that is provided by source and could be used for estabilishing links to other systems.\n',
	LOAD_ID NUMBER(38,0) COMMENT ' Indicates whether data is part of a large historical data pull or was added from a smaller data pull (daily, weekly etc.) \n',
	LOAD_DTTM TIMESTAMP_NTZ(9) COMMENT '\nThe Date/Datetime the Record was Inserted',
	UPDATE_ID NUMBER(38,0) COMMENT 'This is the User Identifier of the Person or Process that Updated the Table',
	UPDATE_DTTM TIMESTAMP_NTZ(9) COMMENT 'The Date/Datetime the Record was Updated',
	DERIVED_PAYMENT_AMT NUMBER(18,2) COMMENT 'Total amount that customer paid for their order (a.k.a. subticket a.k.a. orderid),Derived Payment Amount = Net Amount +  Taxes+ Gratuity + Misc Charge Amt',
	constraint XPKORDER_FACT primary key (ORDER_ID)
)COMMENT='This entity refers to a particular order placed by a customer. \n\ndate key : The date in which the order was sold. \ntime key : It refers to the time of the order.\nrestaurant key : It is essentially a combination of restaurant number and a particular version.\npos key : It refers to a pos name\nemployee key : Employee who sold the order.\npop key : This is point of purchase key.Point of Purchase could be a channel as well. E.g, Drive thru,Mobile,Online etc.\norder id : This is a surrogate key from ParBrink side \norder number : actual Order number (System generated)\norder name : It''s essentially a customer name\ntaxexempt id : This is applicable for an organization which has tax exempt such as non-profit,govt etc.\nguest count : always 1\ngross quantity : Each item gets added to the header\ngross amount : It does not include tax.\npayment amount : Net amount - (discount + promo) + surcharge + tax\n\n '
;
create TABLE IF NOT EXISTS ORDER_LINE_FACT (
	ORDER_LINE_ID VARCHAR(16777216) NOT NULL COMMENT 'Unique ID for each line item in an order',
	CUSTOMER_KEY NUMBER(38,0) COMMENT 'This is a sorrogate key for the Customer Dimension',
	STORE_KEY NUMBER(38,0) COMMENT 'This is a sorrogate key for the Store Dimension',
	BUSINESS_DATE_KEY NUMBER(38,0),
	CHANNEL_KEY NUMBER(38,0) COMMENT 'This is a sorrogate key for the Channel Dimension',
	PARENT_MENU_KEY NUMBER(38,0) COMMENT 'This is a sorrogate key for the Menu Dimension',
	MENU_KEY NUMBER(38,0) COMMENT 'This is a sorrogate key for the Menu Dimension',
	REGISTER_KEY NUMBER(38,0) COMMENT 'This is a sorrogate key for the Register Dimension',
	ORDER_ID VARCHAR(16777216) COMMENT 'OrderID uniquely defines each order\n',
	ORDER_LINE_TYP VARCHAR(16777216) COMMENT 'Indicates if the line is linked to an item sale, discount or other type.\n',
	CHANNEL_ID VARCHAR(16777216) COMMENT 'Unique channel id to identify order and fulfullmint mode',
	MDM_ITEM_ID NUMBER(38,0) COMMENT 'MDM item ID for the item ordered',
	MDM_PARENT_ITEM_ID NUMBER(38,0) COMMENT 'MDM item ID for the parent item',
	BUSINESS_DT DATE COMMENT 'Date of the Order',
	TIME_KEY NUMBER(38,0) COMMENT 'Time sec  at which an order was created.',
	STORE_ID VARCHAR(16777216) COMMENT 'Store id at which the order was placed',
	EMPLOYEE_ID VARCHAR(16777216) COMMENT 'Employee responsible for taking the order',
	REGISTER_ID VARCHAR(16777216) COMMENT 'The register that received payment for the order',
	TAX_ID VARCHAR(16777216) COMMENT 'Rate at which customer is taxed for an item.',
	SEAT_NBR VARCHAR(16777216) COMMENT 'Table/seat number where the customer is seated',
	SOURCE_GROSS_QTY NUMBER(38,0) COMMENT 'Quantity of an item placed in an order provided by the source',
	PRICE_AMT NUMBER(18,2) COMMENT 'Price of the item',
	SOURCE_GROSS_AMT NUMBER(18,2) COMMENT 'Gross Amount of the Line Item provided by source',
	SOURCE_NET_AMT NUMBER(18,2) COMMENT 'Net Amount of the Line Item provided by source',
	TAX_AMT NUMBER(18,2) COMMENT 'Tax Amount for the line item',
	CLEARED_IND BOOLEAN COMMENT 'Indicates if the item was removed before subtotal or payment\n',
	DELETED_IND BOOLEAN COMMENT 'Deleting an item occurs if it is removed after the cashier “subtotals” the order but before payment is made.\n',
	VOID_IND BOOLEAN COMMENT 'Indicates whether the order was cancelled \n',
	INVENTORY_IND BOOLEAN COMMENT '”IsInventory” essentially means does the item have to be thrown in the trash once it’s voided (food) or can it be re-sold (coffee mug).\n',
	MODIFIER_IND BOOLEAN COMMENT 'Indicates if the items was a modifier for a given order \n',
	TAX_EXEMPT_ID VARCHAR(16777216) COMMENT 'This is the customer Tax Exempt Identifier\n',
	MANAGER_ID VARCHAR(16777216) COMMENT 'The ID number of the manager authorizing a void, refund etc.\n',
	DERIVED_GROSS_QTY NUMBER(38,0) COMMENT 'Quantity for Pre tax and pre discounted amount.\n',
	DERIVED_GROSS_AMT NUMBER(18,2) COMMENT 'Pre tax and pre discounted amount.\n',
	DERIVED_DISCOUNT_AMT NUMBER(18,2) COMMENT 'Amount of discount applied to a line item.\n',
	DERIVED_NET_AMT NUMBER(18,2) COMMENT 'Pre tax and after discount amount \n',
	SOURCE_ITEM_ID VARCHAR(16777216) COMMENT 'Unique Id for an item name \n',
	SOURCE_ITEM_PLU_ID VARCHAR(16777216) COMMENT 'This is the PLU number from the POS \n',
	SOURCE_ITEM_DESC VARCHAR(16777216) COMMENT 'Name of the item \n',
	SOURCE_PARENT_ITEM_ID VARCHAR(16777216) COMMENT 'This is used to establish Parent - child relation for the items \n',
	DISCOUNT_CD VARCHAR(16777216) COMMENT 'A key/code linked to the discount\n',
	DISCOUNT_NM VARCHAR(16777216) COMMENT 'Name of the discount that is applied\n',
	SOURCE_DISCOUNT_AMT NUMBER(18,2) COMMENT 'Discount Amount for an order provided by source\n',
	SOURCE_DISCOUNT_TYP VARCHAR(16777216) COMMENT 'Captures the type of discount provided by source.\n',
	ORDER_LINE_PARENT_ID VARCHAR(16777216) COMMENT 'Parent Line Id for the item that was discounted.\n',
	MISC_CHARGE_AMT NUMBER(18,2) COMMENT 'Amount linked to purchase of items that don’t contribute to net sales\n',
	ITEM_TYPE_CD VARCHAR(16777216) COMMENT 'The type code to indicate the type of miscellaneous charge. Will be referencing lookup table\n',
	ALTERNATE1_ORDER_ID VARCHAR(16777216) COMMENT 'Captures any other unique id that is provided by source and could be used for estabilishing links to other systems.\n',
	BRAND_ID VARCHAR(16777216) COMMENT 'Brand for the Order\n',
	SOURCE_SYSTEM_NM VARCHAR(16777216) COMMENT 'The POS System used to load the transaction  information\n',
	LOAD_TYP VARCHAR(16777216) COMMENT 'Indicates whether data is part of a large historical data pull or was added from a smaller data pull (daily, weekly etc.) \n',
	LOAD_ID NUMBER(38,0) COMMENT 'This is the User Identifier of the Person or Process that Loaded the Table',
	LOAD_DTTM TIMESTAMP_NTZ(9) COMMENT 'The Date/Datetime the Record was Inserted',
	UPDATE_ID NUMBER(38,0) COMMENT 'This is the User Identifier of the Person or Process that Updated the Table',
	UPDATE_DTTM TIMESTAMP_NTZ(9) COMMENT 'The Date/Datetime the Record was Updated',
	constraint XPKORDER_LINE_FACT primary key (ORDER_LINE_ID)
)COMMENT='\n\nregister id : this is generated from the terminal\nline item id :\nparent line item id :\n'
;
create TABLE IF NOT EXISTS ORDER_PAYMENT_FACT (
	PAYMENT_ID VARCHAR(16777216) NOT NULL COMMENT 'This column creates a unique payment record',
	ORDER_ID VARCHAR(16777216) NOT NULL COMMENT 'OrderID associates each unique paymentID record with the order that it paid for',
	STORE_KEY NUMBER(38,0) COMMENT 'This is the Sorrogate Key for the Store Dimension',
	CUSTOMER_KEY NUMBER(38,0) COMMENT 'This is a sorrogate key for the Customer Dimension',
	BUSINESS_DT_KEY NUMBER(38,0),
	PAYMENT_TYP_KEY NUMBER(38,0) COMMENT 'This is the Soorgate Key for the Order Payment Type Dimension',
	EMPLOYEE_ID VARCHAR(16777216) COMMENT 'The ID of Employee taking the customer’s order',
	PAYMENT_TYP VARCHAR(16777216) COMMENT 'Card issuer, exactly as reported by the source system. May be full name e.g. “Visa” or abbreviation e.g. “VS”',
	BRAND_ID VARCHAR(16777216) COMMENT 'Brand for the Order',
	STORE_ID VARCHAR(16777216) COMMENT 'Unique identifier for the store where the purchase was made',
	BUSINESS_DT DATE COMMENT 'BusinessDate is the date when the order was taken. The exception is for 24-hour stores that may define the beginning of a new “business day” as being at 2:00AM. So an order at 1:30AM on 11/11/20 would be counted towards the sales of BusinessDate 11/10/20.\n\n',
	VOID_IND BOOLEAN COMMENT 'Indicates whether the order was cancelled \n',
	INSPIRE_ID VARCHAR(16777216) COMMENT 'Masked card number used to pay for order. Concatenates first six card digits, six “x”''s, last four card digits, and cardholder name.',
	ACCOUNT_NM VARCHAR(16777216) COMMENT 'Cardholder’s name',
	CARD_TYP VARCHAR(16777216) COMMENT 'Specifies whether payment was by credit card, cash, debit card, Sonic gift card, EBT card or delivery service (e.g. Door Dash, GrubHub etc.). Card Issuer (e.g. Visa, Mastercard etc.) is not specified.',
	CARD_ISSUER_NM VARCHAR(16777216) COMMENT 'Name of card issuer or delivery service.',
	PAYMENT_FIRST6_NBR VARCHAR(16777216) COMMENT 'First six digits of the payment card for the order.',
	PAYMENT_LAST4_NBR VARCHAR(16777216) COMMENT 'Last four digits of the payment card for the order.',
	PAYMENT_AUTH_CD VARCHAR(16777216) COMMENT 'This is the 6-character authorization code provided by the card issuer',
	EXPIRATION_DT VARCHAR(16777216) COMMENT 'Expiration date of the payment card used to purchase the order.',
	PAYMENT_AMT NUMBER(18,2) COMMENT 'Payment Amount reported by the credit card processor. Includes tip and delivery charge.',
	AMT NUMBER(18,2) COMMENT 'Payment Amount as reported by the Point Of Sale system. Includes everything but the tip (Includes delivery charge)',
	TRANSACTION_TM TIME(9) COMMENT 'Time when the card transaction was made.',
	SOURCE_SYSTEM_NM VARCHAR(16777216) COMMENT 'The POS System used to load the transaction  information\n',
	LOAD_TYP VARCHAR(16777216) COMMENT 'Indicates whether data is part of a large historical data pull or was added from a smaller data pull (daily, weekly etc.) \n',
	LOAD_ID VARCHAR(16777216) COMMENT ' Indicates whether data is part of a large historical data pull or was added from a smaller data pull (daily, weekly etc.) \n',
	LOAD_DTTM TIMESTAMP_NTZ(9) COMMENT '\nThe Date/Datetime the Record was Inserted',
	UPDATE_ID VARCHAR(16777216) COMMENT 'This is the User Identifier of the Person or Process that Updated the Table',
	UPDATE_DTTM TIMESTAMP_NTZ(9) COMMENT 'The Date/Datetime the Record was Updated',
	constraint XPKORDER_PAYMENT primary key (PAYMENT_ID, ORDER_ID)
)COMMENT='This entity referes to the payment made towards a particular order.\n\npayment type id : \npayment desc : This describes method of payment being used such as mastercard,visa,gift card etc.\npayment auth id : It refers to the authentication id after transaction is approved.\npayment name : same as customer name'
;
create TABLE IF NOT EXISTS POLARIS_PROD_COLUMNS (
	TABLE_CATALOG VARCHAR(16777216),
	TABLE_SCHEMA VARCHAR(16777216),
	TABLE_NAME VARCHAR(16777216),
	COLUMN_NAME VARCHAR(16777216),
	DATA_TYPE VARCHAR(16777216),
	CHARACTER_MAXIMUM_LENGTH VARCHAR(16777216),
	NUMERIC_PRECISION VARCHAR(16777216),
	NUMERIC_SCALE VARCHAR(16777216),
	DATETIME_PRECISION VARCHAR(16777216)
);
create TABLE IF NOT EXISTS SESSION_DIM (
	SESSION_KEY NUMBER(38,0) NOT NULL COMMENT 'This is unique Identifier for a Session, This is a sorrogate Key',
	VISIT_NBR NUMBER(38,0) NOT NULL COMMENT 'The session number for this user. If this is the first session, then this is set to 1.\n',
	VISIT_ID NUMBER(38,0) NOT NULL COMMENT 'An identifier for this session. This is part of the value usually stored as the _utmb cookie. This is only unique to the user. For a completely unique ID, you should use a combination of fullVisitorId and visitId.\n',
	VISIT_START_TM TIME(9) NOT NULL COMMENT 'The timestamp (expressed as POSIX time).\n',
	SOCIAL_ENGMT_TYP VARCHAR(150) COMMENT 'Engagement type, either \"Socially Engaged\" or \"Not Socially Engaged\".\n',
	CUSTOM_DIM_VAL VARCHAR(16777216) COMMENT 'The value of the custom dimension.\n',
	CUSTOM_DIM_INDEX_NBR NUMBER(38,0) COMMENT 'The index of the custom dimension.\n',
	SOURCE_SYSTEM_NM VARCHAR(16777216) COMMENT 'The POS System used to load the transaction  information\n',
	LOAD_TYP VARCHAR(16777216) COMMENT 'Indicates whether data is part of a large historical data pull or was added from a smaller data pull (daily, weekly etc.) \n',
	LOAD_ID NUMBER(38,0) COMMENT ' Indicates whether data is part of a large historical data pull or was added from a smaller data pull (daily, weekly etc.) \n',
	LOAD_DTTM TIMESTAMP_NTZ(9) COMMENT '\nThe Date/Datetime the Record was Inserted',
	UPDATE_ID NUMBER(38,0) COMMENT 'This is the User Identifier of the Person or Process that Updated the Table',
	UPDATE_DTTM TIMESTAMP_NTZ(9) COMMENT 'The Date/Datetime the Record was Updated',
	constraint XAK1SESSION_DIMENSION unique (VISIT_ID, VISIT_NBR),
	constraint XPKSESSION_DIMENSION primary key (SESSION_KEY)
);
create TABLE IF NOT EXISTS SESSION_SUMMARY_FACT (
	SESSION_KEY NUMBER(38,0) NOT NULL COMMENT 'This is unique Identifier for a Session, This is a sorrogate Key',
	BUSINESS_DT_KEY NUMBER(38,0) NOT NULL,
	TRAFFIC_SOURCE_KEY NUMBER(38,0) NOT NULL COMMENT 'This is unique Identifier for a Traffic Source, This is a sorrogate Key',
	DEVICE_TYP_KEY NUMBER(38,0) NOT NULL COMMENT 'This is unique Identifier for a Device, This is a sorrogate Key',
	GEO_NTWK_LOC_KEY NUMBER(38,0) NOT NULL COMMENT 'This is the Sorrogate Key for the Network Location Dimension Junk Table',
	TRAFFIC_SOURCE_DETAIL_KEY NUMBER(38,0) NOT NULL COMMENT 'This is unique Identifier for a Traffic Source Detail, This is a sorrogate Key',
	USER_KEY NUMBER(38,0) NOT NULL COMMENT 'This is unique Identifier for a User, This is a sorrogate Key',
	BRAND_ID VARCHAR(16777216) NOT NULL COMMENT 'Brand Identifier specifies the code which represents an organization. The identifier should be in all capital letters. Sample codes are IRB (Inspire Recognized Brands), BWW (Buffalo Wild Wing), DNKN  (Dunkin), etc.',
	CUSTOMER_KEY NUMBER(38,0) COMMENT 'This is a sorrogate key for the Customer Dimension',
	STORE_KEY NUMBER(38,0) NOT NULL,
	VISIT_CNT NUMBER(38,0) COMMENT 'Total number of new users in session (for convenience). If this is the first visit, this value is 1, otherwise it is null.\n',
	HIT_CNT NUMBER(38,0) COMMENT 'Total number of hits within the session.\n',
	PAGE_VIEW_CNT NUMBER(38,0) COMMENT 'Total number of pageviews within the session.\n',
	TM_ONSITE_CNT NUMBER(38,0) COMMENT 'Total time of the session expressed in seconds.\n',
	BOUNCE_CNT NUMBER(38,0) COMMENT 'Total bounces (for convenience). For a bounced session, the value is 1, otherwise it is null.\n',
	TRX_CNT NUMBER(38,0) COMMENT 'Total number of ecommerce transactions within the session.\n',
	NEW_VISIT_CNT NUMBER(38,0) COMMENT 'The number of sessions (for convenience). This value is 1 for sessions with interaction events. The value is null if there are no interaction events in the session.\n',
	SCRN_VIEW_CNT NUMBER(38,0) COMMENT 'Total number of screenviews within the session.\n',
	UNIQUE_SCRN_VIEW_CNT NUMBER(38,0) COMMENT 'Total number of unique screenviews within the session.\n',
	TM_ON_SCRN_CNT NUMBER(38,0) COMMENT 'The total time on screen in seconds.\n',
	TRX_REVENUE_CNT NUMBER(38,0) COMMENT 'Total transaction revenue, expressed as the value passed to Analytics multiplied by 10^6 (e.g., 2.40 would be given as 2400000).\n',
	SESSION_QTY_DIM_CNT NUMBER(38,0) COMMENT 'An estimate of how close a particular session was to transacting, ranging from 1 to 100, calculated for each session. A value closer to 1 indicates a low session quality, or far from transacting, while a value closer to 100 indicates a high session quality, or very close to transacting. A value of 0 indicates that Session Quality is not calculated for the selected time range.\n',
	LAT_NBR VARCHAR(16777216) COMMENT 'The approximate latitude of users'' city, derived from their IP addresses or Geographical IDs. Locations north of the equator have positive latitudes and locations south of the equator have negative latitudes.\n',
	LONG_NBR VARCHAR(16777216) COMMENT 'The approximate longitude of users'' city, derived from their IP addresses or Geographical IDs. Locations east of the prime meridian have positive longitudes and locations west of the prime meridian have negative longitudes.\n',
	SOURCE_SYSTEM_NM VARCHAR(16777216) COMMENT 'The POS System used to load the transaction  information\n',
	LOAD_TYP VARCHAR(16777216) COMMENT 'Indicates whether data is part of a large historical data pull or was added from a smaller data pull (daily, weekly etc.) \n',
	LOAD_ID NUMBER(38,0) COMMENT ' Indicates whether data is part of a large historical data pull or was added from a smaller data pull (daily, weekly etc.) \n',
	LOAD_DTTM TIMESTAMP_NTZ(9) COMMENT '\nThe Date/Datetime the Record was Inserted',
	UPDATE_ID NUMBER(38,0) COMMENT 'This is the User Identifier of the Person or Process that Updated the Table',
	UPDATE_DTTM TIMESTAMP_NTZ(9) COMMENT 'The Date/Datetime the Record was Updated',
	constraint XPKSESSION_SUMMARY_FACT primary key (SESSION_KEY, BUSINESS_DT_KEY, TRAFFIC_SOURCE_KEY, DEVICE_TYP_KEY, GEO_NTWK_LOC_KEY, TRAFFIC_SOURCE_DETAIL_KEY, USER_KEY),
	constraint SD_SSF foreign key (SESSION_KEY) references SESSION_DIM(SESSION_KEY),
	constraint UD_SSF foreign key (USER_KEY) references USER_DIM(USER_KEY),
	constraint TSD_SSF foreign key (TRAFFIC_SOURCE_KEY) references TRAFFIC_SOURCE_DIM(TRAFFIC_SOURCE_KEY),
	constraint DTD_SSF foreign key (DEVICE_TYP_KEY) references DEVICE_TYP_DIM(DEVICE_TYP_KEY),
	constraint GNLD_SSF foreign key (GEO_NTWK_LOC_KEY) references GEO_NTWK_LOC_DIM(GEO_NTWK_LOC_KEY),
	constraint TSDD_SSF foreign key (TRAFFIC_SOURCE_DETAIL_KEY) references TRAFFIC_SOURCE_DETAIL_DIM(TRAFFIC_SOURCE_DETAIL_KEY)
)COMMENT='This section contains aggregate values across the session.\n'
;
create TABLE IF NOT EXISTS SPEND_TYPE (
	SPEND_TYPE_KEY NUMBER(38,0) NOT NULL COMMENT 'Auto-Incremental',
	SPEND_TYP_NM VARCHAR(16777216) NOT NULL COMMENT 'Auto-Incremental',
	SPEND_TYPE_DESC VARCHAR(16777216) COMMENT 'Spend Type Description',
	BRAND_ID VARCHAR(16777216) NOT NULL,
	EFFECTIVE_BEGIN_DT DATE NOT NULL COMMENT 'This is the date the Record Became Active',
	EFFECTIVE_END_DT DATE NOT NULL COMMENT 'This is the date the Record Expires. Default is 12/31/2099',
	SOURCE_SYSTEM_NM VARCHAR(16777216) NOT NULL COMMENT 'Source system name.',
	LOAD_ID NUMBER(38,0) NOT NULL COMMENT 'This is the User Identifier of the Person or Process that Loaded the Table',
	LAST_UPDATED_DTTM TIMESTAMP_NTZ(9) NOT NULL COMMENT 'The Date/Datetime the Record was Inserted',
	CURRENT_IND NUMBER(1,0),
	primary key (SPEND_TYPE_KEY)
)COMMENT='This table contains Media Spend typeinformation.'
;
create TABLE IF NOT EXISTS STEVE (
	STATUS_KEY NUMBER(38,0) NOT NULL autoincrement,
	BRAND_ID VARCHAR(16777216)
);
create TABLE IF NOT EXISTS STRATEGY (
	STRATEGY_KEY NUMBER(38,0) NOT NULL COMMENT 'Incremental value and primary key of the table.',
	STRATEGY_NM VARCHAR(16777216) NOT NULL COMMENT 'Contains Objective, Message, Ad information.',
	STRATEGY_TYPE_ID VARCHAR(16777216) COMMENT 'Defines if the strategy is Objective/Message/Ad type.',
	BRAND_ID VARCHAR(16777216) COMMENT 'Brand ',
	SOURCE_SYSTEM_NM VARCHAR(16777216) COMMENT 'Source system name.',
	STRATEGY_TYPE_NM VARCHAR(16777216) NOT NULL COMMENT 'Type of Strategy : Objective / Message / Ad / Objective+Message',
	STRATEGY_TYPE_DESC VARCHAR(16777216) COMMENT 'Type of Strategy : Objective / Message / Ad / Objective+Message. This Provides more details.',
	EFFECTIVE_BEGIN_DT DATE NOT NULL COMMENT 'This is the date the Record Became Active',
	EFFECTIVE_END_DT DATE NOT NULL COMMENT 'This is the date the Record Expires. Default is 12/31/2099',
	LOAD_ID NUMBER(38,0) NOT NULL COMMENT 'This is the User Identifier of the Person or Process that Loaded the Table',
	LAST_UPDATED_DTTM TIMESTAMP_NTZ(9) NOT NULL COMMENT 'The Date/Datetime the Record was Inserted',
	CURRENT_IND NUMBER(1,0),
	primary key (STRATEGY_KEY)
)COMMENT='This table contains Objective/ad information'
;
create TABLE IF NOT EXISTS TEMP_REST (
	REST_ID VARCHAR(16777216),
	FRAN_IND BOOLEAN
);
create TABLE IF NOT EXISTS TEST_FACT cluster by (BUSINESS_DATE_KEY, STORE_ID, BRAND_ID)(
	STORE_ID VARCHAR(16777216) NOT NULL COMMENT 'Number that uniquely identifies the Store',
	BRAND_ID VARCHAR(16777216) COMMENT 'Brand for the Order',
	TRANSACTION_CNT NUMBER(38,0) COMMENT 'Records whether order has been voided or not. (previously called GrossQuantity)',
	BUSINESS_DT DATE NOT NULL COMMENT 'Date of the Flash Sales',
	NET_SALES_AMT NUMBER(18,2) COMMENT 'Net Amount for the sales',
	LOAD_TYP VARCHAR(16777216) COMMENT 'Indicates whether data is part of a large historical data pull or was added from a smaller data pull (daily, weekly etc.)',
	SOURCE_SYSYEM_NM VARCHAR(16777216) COMMENT 'The POS System used to load the transaction  information',
	LOAD_ID NUMBER(38,0) COMMENT 'Indicates whether data is part of a large historical data pull or was added from a smaller data pull (daily, weekly etc.) \n',
	LOAD_DTTM TIMESTAMP_NTZ(9) COMMENT 'The Date/Datetime the Record was Inserted',
	UPDATE_DTTM TIMESTAMP_NTZ(9) COMMENT 'The Date/Datetime the Record was Inserted',
	UPDATE_ID VARCHAR(16777216) COMMENT 'This is the User Identifier of the Person or Process that Updated the Table',
	STORE_KEY NUMBER(38,0) COMMENT 'This is a sorrogate key for the Store Dimension',
	BUSINESS_DATE_KEY NUMBER(38,0) COMMENT 'This is a sorrogate Key that represent the Business Date Key'
);
create TABLE IF NOT EXISTS TMP_DATE_DIM (
	DATE_KEY DATE,
	DATE_ID VARCHAR(16777216),
	CALENDER_YEAR_NBR NUMBER(38,0),
	CALENDER_DAY_IN_YEAR_NBR NUMBER(38,0),
	CALENDER_MONTH_NBR VARCHAR(16777216),
	CALENDER_MONTH_NM VARCHAR(16777216),
	CALENDER_DAYS_IN_YEAR_QTY NUMBER(18,0),
	CALENDAR_DAY_NM VARCHAR(16777216),
	CALENDER_YEAR_START_DT DATE,
	CALENDER_YEAR_END_DT DATE,
	CALENDER_QUARTER_NBR NUMBER(38,0),
	CALENDER_QUARTER_NM VARCHAR(16777216),
	CALENDER_QUARTER_START_DT DATE,
	CALENDAR_QUARTER_END_DT DATE,
	CALENDAR_DAYS_IN_QUARTER_QTY NUMBER(38,0),
	CALENDAR_MONTH_START_DT DATE,
	CALENDAR_MONTH_END_DT DATE,
	CALENDAR_DAYS_IN_MONTH_QTY NUMBER(38,0),
	CALENDAR_WEEK_IN_YEAR_NBR NUMBER(2,0),
	CALENDAR_WEEK_START_DT DATE,
	CALENDAR_WEEK_END_DT DATE,
	WEEKDAY_IND VARCHAR(1),
	CALENDER_DAY_IN_WEEK_NBR NUMBER(38,0),
	CALENDER_SAMEDAY_LAST_YEAR_DT DATE,
	FISCAL_YEAR_NBR NUMBER(38,0),
	FISCAL_YEAR_START_DT DATE,
	FISCAL_YEAR_END_DT DATE,
	FISCAL_DAYS_IN_YEAR_NBR NUMBER(18,0),
	FISCAL_DAY_NUMBER_IN_YEAR NUMBER(18,0),
	FISCAL_DAYS_LEFT_IN_YEAR_QTY NUMBER(19,0),
	FISCAL_QUARTER_NBR NUMBER(27,0),
	FISCAL_DAY_IN_QTR_NBR NUMBER(18,0),
	FISCAL_QUARTER_START_DT DATE,
	FISCAL_QUARTER_END_DT DATE,
	FISCAL_DAYS_IN_QUARTER_NBR NUMBER(18,0),
	FISCAL_PERIOD_NBR NUMBER(28,0),
	FISCAL_PERIOD_START_DT DATE,
	FISCAL_PERIOD_END_DT DATE,
	FISCAL_DAYS_IN_PERIOD_QTY NUMBER(18,0),
	FISCAL_DAY_IN_PERIOD_NBR NUMBER(18,0),
	FISCAL_WEEKS_IN_YEAR_QTY NUMBER(18,0),
	FISCAL_WEEKS_IN_QUARTER_QTY NUMBER(18,0),
	FISCAL_WEEKS_IN_PERIOD_QTY NUMBER(18,0),
	FISCAL_WEEK_NBR NUMBER(18,0),
	FISCAL_WEEK_START_DT DATE,
	FISCAL_WEEK_END_DT DATE,
	FISCAL_DAY_IN_WEEK_NBR NUMBER(18,0),
	FISCAL_COMPARABLE_DT DATE,
	CALENDER_COMPARABLE_DT DATE,
	CALENDER_COMPARABLE_START_DT DATE,
	CALENDER_COMPARABLE_END_DT DATE,
	CALENDER_COMPARABLE_DAYS_IN_YEAR_QTY NUMBER(38,0),
	CALENDER_COMPARABLE_IN_YEAR_NBR NUMBER(38,0),
	CALENDER_COMPARABLE_WEEK_START_DT DATE,
	CALENDER_COMPARABLE_WEEK_END_DT DATE,
	CALENDAR_COMPARABLE_WEEK_IN_YEAR_NBR NUMBER(2,0),
	CALENDER_COMPARABLE_PERIOD_START_DT DATE,
	CALENDER_COMPARABLE_PERIOD_END_DT DATE,
	CALENDER_COMPARABLE_DAYS_IN_PERIOD_QTY NUMBER(18,0),
	CALENDER_COMPARABLE_QUARTER_START_DT DATE,
	CALENDAR_COMPARABLE_QUARTER_END_DT DATE,
	IS_NEWYEARS_DAY NUMBER(1,0),
	IS_MLKINGS_BIRTHDAY NUMBER(1,0),
	IS_MLK_WEEKEND NUMBER(1,0),
	IS_SUPERBOWL_DAY NUMBER(1,0),
	IS_VALENTINES_DAY NUMBER(1,0),
	IS_ASHWEDNESDAY NUMBER(1,0),
	IS_STPATRICKS_DAY NUMBER(1,0),
	IS_LENT NUMBER(1,0),
	IS_MARCH_MADNESS NUMBER(1,0),
	IS_GOODFRIDAY NUMBER(1,0),
	IS_EASTER NUMBER(1,0),
	IS_DAY_AFTER_EASTER NUMBER(1,0),
	IS_EASTER_WEEKEND NUMBER(1,0),
	IS_CINCODEMAYO NUMBER(1,0),
	IS_MOTHERS_DAY NUMBER(1,0),
	IS_MEMORIAL_DAY NUMBER(1,0),
	IS_MEMORIAL_DAY_WEEKEND NUMBER(1,0),
	IS_FATHERS_DAY NUMBER(1,0),
	IS_JUNETEENTH NUMBER(1,0),
	IS_NATIONAL_WING_DAY NUMBER(1,0),
	IS_INDEPENDENCE_DAY NUMBER(1,0),
	IS_LABOR_DAY NUMBER(1,0),
	IS_LABOR_DAY_WEEKEND NUMBER(1,0),
	IS_HALLOWEEN NUMBER(1,0),
	IS_BLACK_FRIDAY NUMBER(1,0),
	IS_THANKSGIVING_DAY NUMBER(1,0),
	IS_FISCAL_COMP_THANKSGIVING_DAY NUMBER(1,0),
	IS_CALENDER_COMP_THANKSGIVING_DAY NUMBER(1,0),
	IS_CYBER_MONDAY NUMBER(1,0),
	IS_CHRISTMAS_EVE NUMBER(1,0),
	IS_CHRISTMAS_DAY NUMBER(1,0),
	IS_FISCAL_COMP_CHRISTMAS_DAY NUMBER(1,0),
	IS_CALENDER_COMP_CHRISTMAS_DAY NUMBER(1,0),
	IS_NEWYEARS_EVE NUMBER(1,0),
	BRAND_ID VARCHAR(3),
	SOURCE_SYSTEM_NM VARCHAR(6),
	LOAD_ID VARCHAR(16777216),
	LOAD_DTTM TIMESTAMP_NTZ(9),
	UPDATE_ID VARCHAR(16777216),
	UPDATE_DTTM TIMESTAMP_NTZ(9)
);
create TABLE IF NOT EXISTS TMP_HOLIDAY_DIM (
	DATE_KEY DATE NOT NULL,
	HOLIDAY_KEY VARCHAR(16777216) NOT NULL,
	BRAND_ID VARCHAR(16777216),
	HOLIDAY_DESC VARCHAR(16777216),
	SOURCE_SYSTEM_NM VARCHAR(16777216),
	LOAD_ID VARCHAR(16777216),
	LOAD_DTTM TIMESTAMP_NTZ(9),
	UPDATE_ID VARCHAR(16777216),
	UPDATE_DTTM TIMESTAMP_NTZ(9),
	constraint XPKHOLIDAY_DIM primary key (DATE_KEY, HOLIDAY_KEY)
);
create TABLE IF NOT EXISTS TMP_SW_DATE_DIM (
	DATE_KEY NUMBER(38,0) NOT NULL,
	CALENDAR_DATE DATE COMMENT 'Calendar Date is the actual Day, Month, and Year for a given day.',
	DATE_DISPLAY_NM VARCHAR(16777216) COMMENT 'Current Day in date format ',
	CALENDAR_YEAR_NBR NUMBER(38,0) COMMENT 'Current Year in 4 digit  Number format ',
	CALENDAR_DAY_IN_YEAR_NBR NUMBER(38,0) COMMENT 'Day number for the calendar Year',
	CALENDAR_MONTH_NBR NUMBER(38,0) COMMENT 'Current Month number',
	CALENDAR_MONTH_NM VARCHAR(16777216) COMMENT 'Name of the current Month',
	CALENDAR_DAYS_IN_YEAR_QTY NUMBER(38,0) COMMENT 'Total Number of days in calendar Year',
	CALENDAR_DAY_NM VARCHAR(16777216) COMMENT 'Calendar Day Name ',
	CALENDAR_YEAR_START_DT DATE COMMENT 'Start Date for the current Calendar',
	CALENDAR_YEAR_END_DT DATE COMMENT 'End Date for the current Calendar',
	CALENDAR_QUARTER_NBR NUMBER(38,0),
	CALENDAR_QUARTER_NM VARCHAR(16777216),
	CALENDAR_QUARTER_START_DT DATE,
	CALENDAR_QUARTER_END_DT DATE,
	CALENDAR_DAYS_IN_QUARTER_QTY NUMBER(38,0) COMMENT 'Number of days in Calendar quarter',
	CALENDAR_MONTH_START_DT DATE,
	CALENDAR_MONTH_END_DT DATE,
	CALENDAR_DAYS_IN_MONTH_QTY NUMBER(38,0),
	CALENDAR_WEEK_IN_YEAR_NBR NUMBER(38,0),
	CALENDAR_WEEK_START_DT DATE,
	CALENDAR_WEEK_END_DT DATE,
	WEEKDAY_IND VARCHAR(1) COMMENT 'Y- Date is weekday,N- Date is a weekend ',
	FISCAL_YEAR_NBR NUMBER(38,0),
	FISCAL_YEAR_START_DT DATE,
	FISCAL_YEAR_END_DT DATE,
	FISCAL_DAYS_IN_QUARTER_QTY NUMBER(38,0),
	FISCAL_DAYS_IN_YEAR_QTY NUMBER(38,0) COMMENT 'Fiscal Days in Year Quantity',
	FISCAL_DAY_IN_PERIOD_NBR NUMBER(38,0) COMMENT 'Day number in Fiscal period',
	FISCAL_PERIOD_NBR NUMBER(38,0) COMMENT 'Fiscal Period Number ',
	FISCAL_QUARTER_NBR NUMBER(38,0),
	FISCAL_QUARTER_START_DT DATE,
	FISCAL_QUARTER_END_DT DATE,
	FISCAL_PERIOD_START_DT DATE,
	FISCAL_PERIOD_END_DT DATE,
	FISCAL_DAYS_IN_PERIOD_QTY NUMBER(38,0),
	FISCAL_WEEKS_IN_PERIOD_QTY NUMBER(38,0),
	FISCAL_WEEKS_IN_YEAR_QTY NUMBER(38,0),
	FISCAL_WEEK_NBR NUMBER(38,0),
	FISCAL_WEEKS_IN_QUARTER_QTY NUMBER(38,0),
	FISCAL_WEEK_START_DT DATE,
	FISCAL_WEEK_END_DT DATE,
	FISCAL_DAY_IN_WEEK_NBR NUMBER(38,0),
	CALENDAR_COMPARABLE_DT DATE COMMENT 'Prior Year Calendar comp Date( the date is -364) ',
	CALENDAR_COMPARABLE_START_DT DATE,
	CALENDAR_COMPARABLE_END_DT DATE,
	CALENDAR_COMPARABLE_DAYS_IN_YEAR_QTY NUMBER(38,0),
	CALENDAR_COMPARABLE_IN_YEAR_NBR NUMBER(38,0),
	CALENDAR_COMPARABLE_DAYS_IN_PERIOD_QTY NUMBER(38,0),
	CALENDAR_COMPARABLE_PERIOD_NBR NUMBER(38,0),
	CALENDAR_COMPARABLE_QUARTER_NBR NUMBER(38,0),
	CALENDAR_COMPARABLE_PERIOD_START_DT DATE,
	CALENDAR_COMPARABLE_PERIOD_END_DT DATE,
	CALENDAR_COMPARABLE_WEEK_START_DT DATE,
	CALENDAR_COMPARABLE_WEEK_END_DT DATE,
	COMPARABLE_DAY_IN_WEEK_NBR NUMBER(38,0),
	BRAND_ID VARCHAR(16777216),
	SOURCE_SYSTEM_NM VARCHAR(16777216),
	LOAD_ID VARCHAR(16777216) COMMENT 'This is the User Identifier of the Person or Process that Loaded the Table',
	LOAD_DTTM TIMESTAMP_NTZ(9) COMMENT 'The Date/Datetime the Record was Inserted',
	UPDATE_ID VARCHAR(16777216) COMMENT 'This is the User Identifier of the Person or Process that Updated the Table',
	LAST_UPDATE_DTTM TIMESTAMP_NTZ(9) COMMENT 'The Date/Datetime the Record was Updated',
	constraint XPKDATE_DIM primary key (DATE_KEY)
)COMMENT='Date dimension provides hierarchies for analyzing data for different dates or date ranges, such as over weeks, months, or individual days. '
;
create TABLE IF NOT EXISTS TMP_SW_HOLIDAY_DIM (
	HOLIDAY_KEY NUMBER(38,0) NOT NULL,
	DATE_KEY NUMBER(38,0) NOT NULL,
	BRAND_ID VARCHAR(16777216) COMMENT 'campaignInspire recognized brand id. irb when applied to all brands ',
	HOLIDAY_NM VARCHAR(255) NOT NULL COMMENT 'The Name of the Holiday',
	HOLIDAY_DESC VARCHAR(16777216) COMMENT 'Name of the objective Holiday.',
	SOURCE_SYSTEM_NM VARCHAR(16777216) COMMENT 'Inspire level project',
	LOAD_ID VARCHAR(16777216) COMMENT 'This is the User Identifier of the Person or Process that Loaded the Table',
	LOAD_DTTM TIMESTAMP_NTZ(9) COMMENT 'The Date/Datetime the Record was Inserted',
	UPDATE_ID VARCHAR(16777216) COMMENT 'This is the User Identifier of the Person or Process that Updated the Table',
	LAST_UPDATE_DTTM TIMESTAMP_NTZ(9) COMMENT 'The Date/Datetime the Record was Updated',
	constraint XPKHOLIDAY_DIM primary key (HOLIDAY_KEY),
	constraint R_308 foreign key (DATE_KEY) references TMP_SW_DATE_DIM(DATE_KEY)
)COMMENT='Store Holiday Dimension contains a list of holidays that are observed by brand. The holidays that are recognized across all Inspire Recognized Brands will have a brand identifier of irb.'
;
create TABLE IF NOT EXISTS TRAFFIC_SOURCE_DETAIL_DIM (
	TRAFFIC_SOURCE_DETAIL_KEY NUMBER(38,0) NOT NULL COMMENT 'This is unique Identifier for a Traffic Source Detail, This is a sorrogate Key',
	INFO_CAMPAIGN_ID VARCHAR(16777216) NOT NULL COMMENT 'The Google Ads campaign ID.\n',
	INFO_CUST_ID VARCHAR(16777216) NOT NULL COMMENT 'The Google ad ID.\n',
	REFERRAL_PATH_TXT VARCHAR(16777216) COMMENT 'If trafficSource.medium is \"referral\", then this is set to the path of the referrer. (The host name of the referrer is in trafficSource.source.)\n',
	KEYWORD_VAL VARCHAR(16777216) COMMENT 'The keyword of the traffic source, usually set when the trafficSource.medium is \"organic\" or \"cpc\". Can be set by the utm_term URL parameter.\n',
	AD_CONTENT_NM VARCHAR(16777216) COMMENT 'The ad content of the traffic source. Can be set by the utm_content URL parameter.\n',
	IS_TRUE_DIRECT_IND BOOLEAN COMMENT 'True if the source of the session was Direct (meaning the user typed the name of your website URL into the browser or came to your site via a bookmark), This field will also be true if 2 successive but distinct sessions have exactly the same campaign details. Otherwise NULL.\n',
	INFO_AD_GROUP_ID VARCHAR(16777216) COMMENT 'The Google ad-group ID.\n',
	INFO_CREATIVE_ID VARCHAR(16777216) COMMENT 'The Google ad ID.\n',
	INFO_CRITERIA_ID VARCHAR(16777216) COMMENT 'The ID for the targeting criterion.\n',
	INFO_PAGE_NBR VARCHAR(16777216) COMMENT 'Page number in search results where the ad was shown.\n',
	INFO_SLOT_NBR VARCHAR(16777216) COMMENT 'Position of the Ad. Takes one of the following values:{“RHS\", \"Top\"}\n',
	INFO_CRITERIA_PARAM_VAL VARCHAR(16777216) COMMENT 'Descriptive string for the targeting criterion.\n',
	INFO_GCL_ID VARCHAR(16777216) COMMENT 'The Google Click ID.\n\n',
	INFO_AD_NTWK_TYP VARCHAR(16777216) COMMENT 'Network Type. Takes one of the following values: {“Google Search\", \"Content\", \"Search partners\", \"Ad Exchange\", \"Yahoo Japan Search\", \"Yahoo Japan AFS\", “unknown”}\n',
	INFO_TGTNG_CRITERIA_BOOM_USER_LIST_ID VARIANT COMMENT 'Remarketing list ID (if any) in Google Ads, derived from matching_criteria in click record.\n',
	INFO_IS_VIDEO_AD_IND VARCHAR(16777216) COMMENT 'True if it is a Trueview video ad.\n',
	SOURCE_SYSTEM_NM VARCHAR(16777216) COMMENT 'The POS System used to load the transaction  information\n',
	LOAD_TYP VARCHAR(16777216) COMMENT 'Indicates whether data is part of a large historical data pull or was added from a smaller data pull (daily, weekly etc.) \n',
	LOAD_ID NUMBER(38,0) COMMENT ' Indicates whether data is part of a large historical data pull or was added from a smaller data pull (daily, weekly etc.) \n',
	LOAD_DTTM TIMESTAMP_NTZ(9) COMMENT '\nThe Date/Datetime the Record was Inserted',
	UPDATE_ID NUMBER(38,0) COMMENT 'This is the User Identifier of the Person or Process that Updated the Table',
	UPDATE_DTTM TIMESTAMP_NTZ(9) COMMENT 'The Date/Datetime the Record was Updated',
	constraint XAK1TRAFFIC_SOURCE_DETAIL_DIMENSION unique (KEYWORD_VAL, IS_TRUE_DIRECT_IND, INFO_SLOT_NBR, INFO_TGTNG_CRITERIA_BOOM_USER_LIST_ID, INFO_IS_VIDEO_AD_IND, INFO_PAGE_NBR, INFO_GCL_ID, INFO_CUST_ID, INFO_CRITERIA_PARAM_VAL, INFO_CRITERIA_ID, INFO_CREATIVE_ID, INFO_CAMPAIGN_ID, INFO_AD_NTWK_TYP, INFO_AD_GROUP_ID, AD_CONTENT_NM, REFERRAL_PATH_TXT),
	constraint XPKTRAFFIC_SOURCE_DETAIL_DIMENSION primary key (TRAFFIC_SOURCE_DETAIL_KEY)
);
create TABLE IF NOT EXISTS TRAFFIC_SOURCE_DIM (
	TRAFFIC_SOURCE_KEY NUMBER(38,0) NOT NULL COMMENT 'This is unique Identifier for a Traffic Source, This is a sorrogate Key',
	CHANNEL_GROUP_TYP VARCHAR(150) NOT NULL COMMENT 'The Default Channel Group associated with an end user''s session for this View.\n',
	CAMPAIGN_NM VARCHAR(16777216) NOT NULL COMMENT 'The campaign value. Usually set by the utm_campaign URL parameter.\n',
	CAMPAIGN_CD VARCHAR(16777216) NOT NULL COMMENT 'Value of the utm_id campaign tracking parameter, used for manual campaign tracking.\n',
	MEDIUM_NM VARCHAR(16777216) COMMENT 'The medium of the traffic source. Could be \"organic\", \"cpc\", \"referral\", or the value of the utm_medium URL parameter.\n',
	SOURCE_NM VARCHAR(16777216) COMMENT 'The source of the traffic source. Could be the name of the search engine, the referring hostname, or a value of the utm_source URL parameter.\n',
	SOURCE_SYSTEM_NM VARCHAR(16777216) COMMENT 'The POS System used to load the transaction  information\n',
	LOAD_TYP VARCHAR(16777216) COMMENT 'Indicates whether data is part of a large historical data pull or was added from a smaller data pull (daily, weekly etc.) \n',
	LOAD_ID NUMBER(38,0) COMMENT ' Indicates whether data is part of a large historical data pull or was added from a smaller data pull (daily, weekly etc.) \n',
	LOAD_DTTM TIMESTAMP_NTZ(9) COMMENT '\nThe Date/Datetime the Record was Inserted',
	UPDATE_ID NUMBER(38,0) COMMENT 'This is the User Identifier of the Person or Process that Updated the Table',
	UPDATE_DTTM TIMESTAMP_NTZ(9) COMMENT 'The Date/Datetime the Record was Updated',
	constraint XAK1TRAFFIC_SOURCE_DIMENSION unique (MEDIUM_NM, SOURCE_NM, CAMPAIGN_CD, CAMPAIGN_NM, CHANNEL_GROUP_TYP),
	constraint XPKTRAFFIC_SOURCE_DIMENSION primary key (TRAFFIC_SOURCE_KEY)
);
create TABLE IF NOT EXISTS UDP_ABBREVIATION (
	ABBREVIATION_NAME VARCHAR(16777216),
	ABBREVIATION_CD VARCHAR(16777216),
	CLASS_WORD_IND VARCHAR(16777216),
	CLASS_DEFAULT_DATA_TYPE_CD VARCHAR(16777216)
);
create TABLE IF NOT EXISTS UDP_CDM_DATA_TABLES (
	DATABASE_NM VARCHAR(16777216),
	TABLE_NM VARCHAR(16777216),
	COLUMN_NM VARCHAR(16777216),
	DATA_TYPE_CD VARCHAR(16777216),
	PROPOSED_IDS_SCHEMA VARCHAR(16777216),
	PROPOSED_CLASS_WORD_CD VARCHAR(16777216),
	USE_PROPOSED_CLASS_IND VARCHAR(16777216),
	PREP_COLUMN_NM VARCHAR(16777216),
	COLUMN_W_SPACE_NM VARCHAR(16777216),
	LOADSEQ NUMBER(38,0)
);
create TABLE IF NOT EXISTS UDP_POLARIS_DATA_TABLES (
	SCHEMA_NM VARCHAR(16777216),
	TABLE_NM VARCHAR(16777216),
	COLUMN_NM VARCHAR(16777216),
	DATA_TYPE VARCHAR(16777216),
	CHARACTER_MAXIMUM_LENGTH VARCHAR(16777216),
	NUMERIC_PRECISION VARCHAR(16777216),
	NUMERIC_SCALE VARCHAR(16777216),
	DATETIME_PRECISION VARCHAR(16777216),
	CLEAN_COLUMN_NM VARCHAR(16777216),
	WITH_CASE_COLUMN_NM VARCHAR(16777216),
	MANUAL_ADJ_COLUMN_NM VARCHAR(16777216),
	LOADSEQ NUMBER(38,0)
);
create TABLE IF NOT EXISTS UDP_WORD_TRANSLATION (
	WORD_PART VARCHAR(16777216),
	TOTAL_CNT NUMBER(38,0),
	POLARIS_WORD_CNT NUMBER(38,0),
	CDM_WORD_CNT NUMBER(38,0),
	UDP_TRANSLATION_WORD VARCHAR(16777216),
	WORD_CHANGE_IND VARCHAR(16777216),
	WORD_DEFINITION VARCHAR(16777216)
);
create TABLE IF NOT EXISTS USER_DIM (
	USER_KEY NUMBER(38,0) NOT NULL COMMENT 'This is unique Identifier for a User, This is a sorrogate Key',
	FULL_VISITOR_ID VARCHAR(150) NOT NULL COMMENT 'The unique visitor ID (also known as client ID).\n',
	USER_ID VARCHAR(150) NOT NULL COMMENT 'Overridden User ID sent to Analytics.\n',
	CLIENT_ID VARCHAR(150) NOT NULL COMMENT 'Unhashed version of the Client ID for a given user associated with any given visit/session.\n',
	SOURCE_SYSTEM_NM VARCHAR(16777216) COMMENT 'The POS System used to load the transaction  information\n',
	LOAD_TYP VARCHAR(16777216) COMMENT 'Indicates whether data is part of a large historical data pull or was added from a smaller data pull (daily, weekly etc.) \n',
	LOAD_ID NUMBER(38,0) COMMENT ' Indicates whether data is part of a large historical data pull or was added from a smaller data pull (daily, weekly etc.) \n',
	LOAD_DTTM TIMESTAMP_NTZ(9) COMMENT '\nThe Date/Datetime the Record was Inserted',
	UPDATE_ID NUMBER(38,0) COMMENT 'This is the User Identifier of the Person or Process that Updated the Table',
	UPDATE_DTTM TIMESTAMP_NTZ(9) COMMENT 'The Date/Datetime the Record was Updated',
	constraint XAK1USER_DIMENSION unique (FULL_VISITOR_ID, USER_ID),
	constraint XPKUSER_DIMENSION primary key (USER_KEY)
);
create TABLE IF NOT EXISTS VW_COMP_CAL_DATE_3YR (
	DATE_KEY NUMBER(38,0),
	DATE_ID DATE,
	FISCAL_YEAR_START_DT DATE,
	FISCAL_QUARTER_START_DT DATE,
	FISCAL_PERIOD_START_DT DATE,
	FISCAL_WEEK_START_DT DATE,
	FISCAL1YRCOMP_DATEID DATE,
	FISCAL1YRCOMP_YEAR DATE,
	FISCAL1YRCOMP_QUARTER DATE,
	FISCAL1YRCOMP_PERIOD DATE,
	FISCAL1YRCOMP_WEEK DATE,
	CALENDAR1YRCOMP_DATEID DATE,
	CALENDAR1YRCOMP_YEAR DATE,
	CALENDAR1YRCOMP_QUARTER DATE,
	CALENDAR1YRCOMP_PERIOD DATE,
	CALENDAR1YRCOMP_WEEK DATE,
	CALENDAR2YRCOMP_DATEID DATE,
	CALENDAR2YRCOMP_YEAR DATE,
	CALENDAR2YRCOMP_QUARTER DATE,
	CALENDAR2YRCOMP_PERIOD DATE,
	CALENDAR2YRCOMP_WEEK DATE,
	CALENDAR3YRCOMP_DATEID DATE,
	CALENDAR3YRCOMP_YEAR DATE,
	CALENDAR3YRCOMP_QUARTER DATE,
	CALENDAR3YRCOMP_PERIOD DATE,
	CALENDAR3YRCOMP_WEEK DATE
);
create TABLE IF NOT EXISTS VW_COMP_CAL_DATE_3YR_AS cluster by (Date_ID,DATE_KEY)(
	DATE_KEY NUMBER(38,0),
	DATE_ID DATE,
	FISCAL_YEAR_START_DT DATE,
	FISCAL_QUARTER_START_DT DATE,
	FISCAL_PERIOD_START_DT DATE,
	FISCAL_WEEK_START_DT DATE,
	FISCAL1YRCOMP_DATEID DATE,
	FISCAL1YRCOMP_YEAR DATE,
	FISCAL1YRCOMP_QUARTER DATE,
	FISCAL1YRCOMP_PERIOD DATE,
	FISCAL1YRCOMP_WEEK DATE,
	CALENDAR1YRCOMP_DATEID DATE,
	CALENDAR1YRCOMP_YEAR DATE,
	CALENDAR1YRCOMP_QUARTER DATE,
	CALENDAR1YRCOMP_PERIOD DATE,
	CALENDAR1YRCOMP_WEEK DATE,
	CALENDAR2YRCOMP_DATEID DATE,
	CALENDAR2YRCOMP_YEAR DATE,
	CALENDAR2YRCOMP_QUARTER DATE,
	CALENDAR2YRCOMP_PERIOD DATE,
	CALENDAR2YRCOMP_WEEK DATE,
	CALENDAR3YRCOMP_DATEID DATE,
	CALENDAR3YRCOMP_YEAR DATE,
	CALENDAR3YRCOMP_QUARTER DATE,
	CALENDAR3YRCOMP_PERIOD DATE,
	CALENDAR3YRCOMP_WEEK DATE
);
create view IF NOT EXISTS DAILY_DAY_PART_FLASH_SALES_FACT_V(
	STORE_ID COMMENT 'Number that uniquely identifies the Store',
	BUSINESS_DT COMMENT 'Date of the Flash Sales',
	DAY_PART_NM COMMENT 'This is the Name of the Date Part',
	BRAND_ID COMMENT 'Brand for the Order\n',
	CHANNEL_ID COMMENT 'This is a unique Channel Identifier',
	FULFILLMENT_CHANNEL_NM,
	TRX_CNT COMMENT 'Records whether order has been voided or not. (previously called GrossQuantity)',
	NET_SALES_AMT COMMENT 'Net Amount for the sales',
	LOAD_TYP COMMENT 'Indicates whether data is part of a large historical data pull or was added from a smaller data pull (daily, weekly etc.)',
	SOURCE_SYSYEM_NM COMMENT 'The POS System used to load the transaction  information',
	LOAD_ID COMMENT 'Indicates whether data is part of a large historical data pull or was added from a smaller data pull (daily, weekly etc.) \n',
	LOAD_DTTM COMMENT 'The Date/Datetime the Record was Inserted',
	UPDATE_ID COMMENT 'This is the User Identifier of the Person or Process that Updated the Table',
	UPDATE_DTTM COMMENT 'The Date/Datetime the Record was Inserted'
) as 
SELECT FACT.STORE_ID,FACT.BUSINESS_DT,FACT.DAY_PART_NM,FACT.BRAND_ID,FACT.CHANNEL_ID,CD.FULFILLMENTCHANNELNAME,FACT.TRX_CNT,FACT.NET_SALES_AMT,FACT.LOAD_TYP,FACT.SOURCE_SYSYEM_NM,FACT.LOAD_ID,FACT.LOAD_DTTM,FACT.UPDATE_ID,FACT.UPDATE_DTTM
FROM DAILY_DAY_PART_FLASH_SALES_FACT  FACT LEFT JOIN POLARIS_DEV.SADM.CHANNEL_DIM CD ON  FACT.CHANNEL_ID = CD.CHANNELID;
create view IF NOT EXISTS POLARIS_DATA_TABLES_V(
	SCHEMA_NM,
	TABLE_NM,
	COLUMN_NM,
	CLEAN_COLUMN_NM,
	WITH_CASE_COLUMN_NM,
	MANUAL_ADJ_COLUMN_NM,
	LOADSEQ
) as select * from polaris_DATA_tables;
create view IF NOT EXISTS V_DATE_DIM(
	DATE_KEY,
	DATE_ID,
	CALENDER_YEAR_NBR,
	CALENDER_DAY_IN_YEAR_NBR,
	CALENDER_MONTH_NBR,
	CALENDER_MONTH_NM,
	CALENDER_DAYS_IN_YEAR_QTY,
	CALENDAR_DAY_NM,
	CALENDER_YEAR_START_DT,
	CALENDER_YEAR_END_DT,
	CALENDER_QUARTER_NBR,
	CALENDER_QUARTER_NM,
	CALENDER_QUARTER_START_DT,
	CALENDAR_QUARTER_END_DT,
	CALENDAR_DAYS_IN_QUARTER_QTY,
	CALENDAR_MONTH_START_DT,
	CALENDAR_MONTH_END_DT,
	CALENDAR_DAYS_IN_MONTH_QTY,
	CALENDAR_WEEK_IN_YEAR_NBR,
	CALENDAR_WEEK_START_DT,
	CALENDAR_WEEK_END_DT,
	WEEKDAY_IND,
	CALENDER_DAY_IN_WEEK_NBR,
	CALENDER_SAMEDAY_LAST_YEAR_DT,
	FISCAL_YEAR_NBR,
	FISCAL_YEAR_START_DT,
	FISCAL_YEAR_END_DT,
	FISCAL_DAYS_IN_YEAR_NBR,
	FISCAL_DAY_NUMBER_IN_YEAR,
	FISCAL_DAYS_LEFT_IN_YEAR_QTY,
	FISCAL_QUARTER_NBR,
	FISCAL_DAY_IN_QTR_NBR,
	FISCAL_QUARTER_START_DT,
	FISCAL_QUARTER_END_DT,
	FISCAL_DAYS_IN_QUARTER_NBR,
	FISCAL_PERIOD_NBR,
	FISCAL_PERIOD_START_DT,
	FISCAL_PERIOD_END_DT,
	FISCAL_DAYS_IN_PERIOD_QTY,
	FISCAL_DAY_IN_PERIOD_NBR,
	FISCAL_WEEKS_IN_YEAR_QTY,
	FISCAL_WEEKS_IN_QUARTER_QTY,
	FISCAL_WEEKS_IN_PERIOD_QTY,
	FISCAL_WEEK_NBR,
	FISCAL_WEEK_START_DT,
	FISCAL_WEEK_END_DT,
	FISCAL_DAY_IN_WEEK_NBR,
	FISCAL_COMPARABLE_DT,
	CALENDER_COMPARABLE_DT,
	CALENDER_COMPARABLE_START_DT,
	CALENDER_COMPARABLE_END_DT,
	CALENDER_COMPARABLE_DAYS_IN_YEAR_QTY,
	CALENDER_COMPARABLE_IN_YEAR_NBR,
	CALENDER_COMPARABLE_WEEK_START_DT,
	CALENDER_COMPARABLE_WEEK_END_DT,
	CALENDAR_COMPARABLE_WEEK_IN_YEAR_NBR,
	CALENDER_COMPARABLE_PERIOD_START_DT,
	CALENDER_COMPARABLE_PERIOD_END_DT,
	CALENDER_COMPARABLE_DAYS_IN_PERIOD_QTY,
	CALENDER_COMPARABLE_QUARTER_START_DT,
	CALENDAR_COMPARABLE_QUARTER_END_DT,
	IS_NEWYEARS_DAY,
	IS_MLKINGS_BIRTHDAY,
	IS_MLK_WEEKEND,
	IS_SUPERBOWL_DAY,
	IS_VALENTINES_DAY,
	IS_ASHWEDNESDAY,
	IS_STPATRICKS_DAY,
	IS_LENT,
	IS_MARCH_MADNESS,
	IS_GOODFRIDAY,
	IS_EASTER,
	IS_DAY_AFTER_EASTER,
	IS_EASTER_WEEKEND,
	IS_CINCODEMAYO,
	IS_MOTHERS_DAY,
	IS_MEMORIAL_DAY,
	IS_MEMORIAL_DAY_WEEKEND,
	IS_FATHERS_DAY,
	IS_JUNETEENTH,
	IS_NATIONAL_WING_DAY,
	IS_INDEPENDENCE_DAY,
	IS_LABOR_DAY,
	IS_LABOR_DAY_WEEKEND,
	IS_HALLOWEEN,
	IS_BLACK_FRIDAY,
	IS_THANKSGIVING_DAY,
	IS_FISCAL_COMP_THANKSGIVING_DAY,
	IS_CALENDER_COMP_THANKSGIVING_DAY,
	IS_CYBER_MONDAY,
	IS_CHRISTMAS_EVE,
	IS_CHRISTMAS_DAY,
	IS_FISCAL_COMP_CHRISTMAS_DAY,
	IS_CALENDER_COMP_CHRISTMAS_DAY,
	IS_NEWYEARS_EVE,
	BRAND_ID,
	SOURCE_SYSTEM_NM,
	LOAD_ID,
	LOAD_DTTM,
	UPDATE_ID,
	UPDATE_DTTM
) as (select * from "IDS_DEV"."DATASTORE"."DATE_DIM");
create view IF NOT EXISTS _A(
	A
) as select 1 A UNION SELECT '2 ' a;
CREATE FILE FORMAT IF NOT EXISTS MJ_CSV
;