create view IF NOT EXISTS AUTHORIZATION_ARBYS(
	SITE_STATE,
	SITE_ADDRESS,
	PROCESSOR_CODE_MERCHANT,
	SITE_CITY,
	SITE_ALT_ID,
	SITE_ZIP_CODE,
	SITE_PHONE_NO,
	PROCESSOR_MERCHANT,
	SITE_NAME,
	CARD_EBT_STATE,
	CARD_ISSUE_DETAIL_CODE,
	CARD_B2B_PROGRAM,
	CARD_FAST_FUNDS_CODE,
	CARD_ONLINE_GAMBLING_INDICATOR,
	CARD_RELOADABLE,
	CARD_FUND_SOURCE,
	CARD_DEBIT_NETWORK_PARTICIPANT,
	CARD_PRODUCT_SUBTYPE_CODE,
	CARD_ISSUE_TYPE,
	CARD_FAST_FUNDS,
	BIN_ID_CARD,
	CARD_ISSUING_CNTRY,
	CARD_ORIGINAL_CREDIT_INDICATOR,
	CARD_DEBIT_NETWORK_PARTICIPANT_CODE,
	CARD_ISSUER,
	CARD_FUND_SOURCE_CODE,
	CARD_ISSUER_BIN,
	CARD_CLASS_CODE,
	CARD_ISSUER_CODE,
	CARD_ISSUE_DETAIL,
	CARD_ISSUER_REGULATED_CODE,
	CARD_ORIGINAL_CREDIT_INDICATOR_CODE,
	TOKEN_BIN_INDICATOR,
	CARD_ISSUER_REGULATED,
	CARD_BILLING_CURRENCY,
	CARD_BILLING_CURRENCY_CODE,
	CARD_BRAND_CODE,
	CARD_EBT_STATE_CODE,
	TOKEN_BIN_INDICATOR_CODE,
	CARD_CLASS,
	CARD_ONLINE_GAMBLING_INDICATOR_CODE,
	CARD_PRODUCT_SUBTYPE,
	CARD_MONEY_SEND_INDICATOR_CODE,
	CARD_MONEY_SEND_INDICATOR,
	CARD_PROCESSING_INDICATOR,
	CARD_MONEY_TRANSFER_INDICATOR,
	CARD_RELOADABLE_CODE,
	CARD_PROCESSING_INDICATOR_CODE,
	CARD_ISSUE_TYPE_CODE,
	CARD_MONEY_TRANSFER_INDICATOR_CODE,
	CARD_B2B_PROGRAM_CODE,
	CARD_BRAND,
	CARD_ISSUING_CNTRY_CODE,
	CARD_NETWORK_DATA_ERROR,
	BANKNET_REF,
	MERCHANT_ADVICE_CODE,
	PAYMENT_METHOD,
	TRACKER_ID,
	NETWORK_POS_DATA,
	MERCHANT_CATEGORY,
	EMV_CRYPTOGRAM_INFORMATION_DATA,
	NETWORK_TOKEN_ELIGIBLE_INDICATOR,
	AUTHORIZATION_RESPONSE_CODE,
	NETWORK_TOKEN_OFFERING_TYPE,
	POS_CONDITION_DESCRIPTION_CODE,
	PAYPAL_TRANS_ID,
	P2PE_ENCRYPTION_TYPE_CODE,
	NETWORK_INPUT_INDICATOR_CODE,
	UNPREDICTABLE_NBR,
	CROSS_BORDER_INDICATOR,
	TIP_AMT,
	ACCOUNT_NBR_LAST_4,
	TXN_DATE_AND_TIME,
	AMT,
	ALTERNATIVE_MERCHANT_ID,
	PARTNER_ORDER_ID,
	THIRD_PARTY_PROCESSOR_VAR_ID_CODE,
	SUBTYPE_CODE,
	NETWORK_AUTH_INDICATOR_3_CODE,
	EMV_TERMINAL_VERIFICATION_RESULT,
	EMV_EXPIRY_DATE,
	CAVV_RESPONSE,
	MARKET_SPECIFIC_DATA_INDICATOR,
	EMV_APPLICATION_VERSION_NBR,
	MERCHANT_ADVICE,
	CASH_BACK_AMT,
	CAVV_DOWNGRADE_REASON,
	DCC_CURRENCY,
	SERVER_ID,
	ORIGINAL_AUTHORIZATION_RESPONSE_DESCRIPTION,
	NETWORK_TOKEN_OFFERING_TYPE_CODE,
	REFERENCE_NBR,
	TERMINAL_CAPABILITY_CODE,
	EQUIVALENT_TRACK2_DATA,
	TOKEN_RESPONSE,
	EMV_DEDICATED_FILE_NAME,
	ORDER_NBR,
	DRD_GROUP_ROUTE_ID,
	P2PE_TOKEN_ASSURANCE_CODE,
	PROCESSOR_CODE,
	EMV_APPLICATION_TRANS_CNTER,
	AUTH_ATTEMPT,
	AUTH_OP_ACTION,
	TOKEN_NBR,
	MARKET_SPECIFIC_DATA_INDICATOR_CODE,
	AUTH_CURRENCY,
	NETWORK_AUTH_INDICATOR_2_CODE,
	SEND_MODE_CODE,
	DCC_RATE,
	AUTHORIZATION_CHARACTERISTICS_INDICATORS,
	VOUCHER_NBR,
	P2PE_TOKEN_ASSURANCE,
	DCC_INDICATOR,
	CVV_RESULT_CODE,
	SHIPMENT_TO_ZIPCODE,
	ONLINE_TRANS_INDICATOR,
	CARD_GROUP,
	DEBIT_FEE_AMT,
	NATIVE_EXPERIENCE_PROVIDER,
	PAYPAL_ACCOUNT_NBR,
	MERCHANT_CATEGORY_CODE,
	SHIPMENT_FROM_ZIP_CODE,
	TRANS_CATEGORY_CODE,
	DCC_INDICATOR_CODE,
	TYPE_CODE,
	CVV_RESULT,
	EMV_APPLICATION_INTERCHANGE_PROFILE,
	PAYMENT_METHOD_CODE,
	SUB_MERCHANT_ID,
	CASH_BACK_INDICATOR,
	SOURCE,
	CARD_LEVEL_RESULT,
	PARTIAL_APPROVAL_FLAG,
	EC_INDICATOR_CODE,
	SETTLE_CUTOFF_TIME,
	NETWORK_AUTH_INDICATOR,
	NATIVE_TRANS_SUBTYPE,
	ENTRY_MODE_INDICATOR,
	MOBILE_WALLET_CODE,
	NATIVE_REJECT_CODE,
	LOCAL_DATE_TIME,
	TRANS_ORIGINATOR,
	ACCOUNT_NBR_FIRST_6,
	AUTHORIZATION_TRACE_NBR,
	ONLINE_TRANS_INDICATOR_CODE,
	EMV_APPLICATION_CRYPTOGRAM,
	GUID,
	EMV_TERMINAL_CAPABILITY_PROFILE,
	INITIAL_ASSOC_RESP_CODE,
	NETWORK_TOKEN_NBR,
	EXTERNAL_MERCHANT_ID,
	P2PE_TOKEN_TYPE,
	EC_INDICATOR,
	CAVV_RESPONSE_CODE,
	REVERSED,
	PROCESSOR,
	DCC_CNTRY_CODE,
	DRD_NETWORK_LIST,
	RECURRING_TYPE,
	MOBILE_WALLET,
	ORIGINAL_AUTHORIZATION_RESPONSE,
	AUTH_CODE,
	EMV_ISSUER_APPLICATION_DATA,
	INITIAL_ASSOC_RESP,
	DRD_REGULATOR_INDICATOR,
	CUSTOMER_NAME,
	MESSAGE_TYPE_IDENTIFIER,
	LINK_RESPONSE_DESC,
	EMV_CHIP_TRANS_IND,
	TIME_TAKEN,
	POS_TERM_CAP,
	NETWORK_AUTH_INDICATOR_3,
	NETWORK_AUTH_INDICATOR_2,
	DRD_NETWORK_USED,
	SOURCE_CODE,
	AVS_RESPONSE,
	RECURRING_TYPE_CODE,
	VAT_REFERENCE_NBR,
	EXPERIENCE_PROVIDER,
	MC_PROMOTION_CODE,
	EMV_TERMINAL_CNTRY_CODE,
	TERMINAL_ID,
	ADJUSTMENT_AMT,
	TYPE,
	SEQUENCE_NBR,
	SALES_TAX_AMT,
	EMV_TRANS_TYPE,
	LINK_RESPONSE,
	THIRD_PARTY_PROCESSOR_VAR_ID,
	POS_CONDITION_DESCRIPTION,
	NETWORK_INPUT_INDICATOR,
	SITE_ID__FE,
	APPROVAL_STATUS_CODE,
	CARD_EXPIRY_DATE,
	NETWORK,
	AUTH_CURRENCY_CODE,
	CASH_BACK_INDICATOR_CODE,
	TERMINAL_SERIAL_NBR,
	NATIVE_AUTH_OP_ACTION,
	CARD_GROUP_CODE,
	TERMINAL_TYPE,
	VISA_VALID_CODE,
	SEND_MODE,
	APPROVAL_STATUS,
	EXTERNAL_TERMINAL_ID,
	VELOCITY_INDICATOR,
	AUTH_OP_ACTION_CODE,
	LINK_RESPONSE_DESC_CODE,
	EXTERNAL_REFERENCE_ID,
	BANK_FIID,
	P2PE_ENCRYPTION_TYPE,
	NETWORK_AUTH_INDICATOR_CODE,
	DECLINE_REASON_CODE,
	TOKEN_RESPONSE_CODE,
	AUTH_OP_STATUS,
	DISCOUNT_AMT,
	ADJUSTMENT_INDICATOR,
	EMV_ISSUER_AUTHENTICATION_DATA,
	EMV_CARD_HOLDER_VERIFICATION_RESULTS,
	CARD_NETWORK_CVC_ERROR,
	DRD_ROUTE_FUNCTION,
	NETWORK_TRANS_ID,
	MASTERCARD_BANKNET_DATE,
	SUBTYPE,
	P2PE_TOKEN_TYPE_CODE,
	SERVICE_CODE,
	DECLINE_REASON,
	NATIVE_DEBIT_REJECT_CODE,
	NETWORK_CODE,
	GIFT_CARD_NBR,
	SHIPMENT_TO_CNTRY_CODE,
	TIME_IN_EPOCH,
	AVS_RESPONSE_CODE,
	AUTH_ATTEMPT_CODE,
	FRAUD_SCORE,
	RECORD_NBR,
	MERCHANT_NAME,
	EMV_CHIP_AUTHENTICATION_RESULT,
	PAR_ID,
	AUTH_OP_STATUS_CODE,
	DCC_AMT,
	ISSUER_SCRIPT_RESULTS,
	SOURCE_SYSTEM_NAME,
	FILE_NAME,
	LOAD_ID,
	LOAD_DTTM
) as ( 
SELECT 
Site_State AS Site_State,
Site_Address AS Site_Address,
Processor_Code_Merchant AS Processor_Code_Merchant,
Site_City AS Site_City,
Site_Alternate_ID AS Site_ALT_ID,
Site_Zip_Code AS Site_Zip_Code,
Site_Phone_No AS Site_Phone_No,
Processor_Merchant AS Processor_Merchant,
Site_Name AS Site_Name,
Card_EBT_State AS Card_EBT_State,
Card_Issue_Detail_Code AS Card_Issue_Detail_Code,
Card_B2B_Program AS Card_B2B_Program,
Card_Fast_Funds_Code AS Card_Fast_Funds_Code,
Card_Online_Gambling_Indicator AS Card_Online_Gambling_Indicator,
Card_Reloadable AS Card_Reloadable,
Card_Fund_Source AS Card_Fund_Source,
Card_Debit_Network_Participant AS Card_Debit_Network_Participant,
Card_Product_SubType_Code AS Card_Product_SubType_Code,
Card_Issue_Type AS Card_Issue_Type,
Card_Fast_Funds AS Card_Fast_Funds,
Bin_ID_Card AS Bin_ID_Card,
Card_Issuing_Country AS Card_Issuing_CNTry,
Card_Original_Credit_Indicator AS Card_Original_Credit_Indicator,
Card_Debit_Network_Participant_Code AS Card_Debit_Network_Participant_Code,
Card_Issuer AS Card_Issuer,
Card_Fund_Source_Code AS Card_Fund_Source_Code,
Card_Issuer_Bin AS Card_Issuer_Bin,
Card_Class_Code AS Card_Class_Code,
Card_Issuer_Code AS Card_Issuer_Code,
Card_Issue_Detail AS Card_Issue_Detail,
Card_Issuer_Regulated_Code AS Card_Issuer_Regulated_Code,
Card_Original_Credit_Indicator_Code AS Card_Original_Credit_Indicator_Code,
Token_Bin_Indicator AS Token_Bin_Indicator,
Card_Issuer_Regulated AS Card_Issuer_Regulated,
Card_Billing_Currency AS Card_Billing_Currency,
Card_Billing_Currency_Code AS Card_Billing_Currency_Code,
Card_Brand_Code AS Card_Brand_Code,
Card_EBT_State_Code AS Card_EBT_State_Code,
Token_Bin_Indicator_Code AS Token_Bin_Indicator_Code,
Card_Class AS Card_Class,
Card_Online_Gambling_Indicator_Code AS Card_Online_Gambling_Indicator_Code,
Card_Product_SubType AS Card_Product_SubType,
Card_Money_Send_Indicator_Code AS Card_Money_Send_Indicator_Code,
Card_Money_Send_Indicator AS Card_Money_Send_Indicator,
Card_Processing_Indicator AS Card_Processing_Indicator,
Card_Money_Transfer_Indicator AS Card_Money_Transfer_Indicator,
Card_Reloadable_Code AS Card_Reloadable_Code,
Card_Processing_Indicator_Code AS Card_Processing_Indicator_Code,
Card_Issue_Type_Code AS Card_Issue_Type_Code,
Card_Money_Transfer_Indicator_Code AS Card_Money_Transfer_Indicator_Code,
Card_B2B_Program_Code AS Card_B2B_Program_Code,
Card_Brand AS Card_Brand,
Card_Issuing_Country_Code AS Card_Issuing_CNTry_Code,
Card_Network_Data_Error AS Card_Network_Data_Error,
BankNet_Ref AS BankNet_Ref,
Merchant_Advice_Code AS Merchant_Advice_Code,
Payment_Method AS Payment_Method,
Tracker_ID AS Tracker_ID,
Network_POS_Data AS Network_POS_Data,
Merchant_Category AS Merchant_Category,
Emv_Cryptogram_Information_Data AS Emv_Cryptogram_Information_Data,
Network_Token_Eligible_Indicator AS Network_Token_Eligible_Indicator,
Authorization_Response_Code AS Authorization_Response_Code,
Network_Token_Offering_Type AS Network_Token_Offering_Type,
POS_Condition_Description_Code AS POS_Condition_Description_Code,
Paypal_Transaction_ID AS Paypal_TRANS_ID,
P2PE_Encryption_Type_Code AS P2PE_Encryption_Type_Code,
Network_Input_Indicator_Code AS Network_Input_Indicator_Code,
Unpredictable_Number AS Unpredictable_NBR,
Cross_Border_Indicator AS Cross_Border_Indicator,
Tip_Amount AS Tip_AMT,
Account_Number_Last_4 AS Account_NBR_Last_4,
Txn_Date_and_Time AS Txn_Date_and_Time,
Amount AS AMT,
Alternative_Merchant_Id AS Alternative_Merchant_Id,
Partner_Order_ID AS Partner_Order_ID,
Third_Party_Processor_VAR_ID_Code AS Third_Party_Processor_VAR_ID_Code,
SubType_Code AS SubType_Code,
Network_Auth_Indicator_3_Code AS Network_Auth_Indicator_3_Code,
Emv_Terminal_Verification_Result AS Emv_Terminal_Verification_Result,
Emv_Expiry_Date AS Emv_Expiry_Date,
CAVV_Response AS CAVV_Response,
Market_Specific_Data_Indicator AS Market_Specific_Data_Indicator,
Emv_Application_Version_Number AS Emv_Application_Version_NBR,
Merchant_Advice AS Merchant_Advice,
Cash_Back_Amount AS Cash_Back_AMT,
CAVV_Downgrade_Reason AS CAVV_Downgrade_Reason,
DCC_Currency AS DCC_Currency,
Server_Id AS Server_Id,
Original_Authorization_Response_Description AS Original_Authorization_Response_Description,
Network_Token_Offering_Type_Code AS Network_Token_Offering_Type_Code,
Reference_Number AS Reference_NBR,
Terminal_Capability_Code AS Terminal_Capability_Code,
Equivalent_Track2_Data AS Equivalent_Track2_Data,
Token_Response AS Token_Response,
Emv_Dedicated_File_Name AS Emv_Dedicated_File_Name,
Order_Number AS Order_NBR,
DRD_Group_Route_ID AS DRD_Group_Route_ID,
P2PE_Token_Assurance_Code AS P2PE_Token_Assurance_Code,
Processor_Code AS Processor_Code,
Emv_Application_Transaction_Counter AS Emv_Application_TRANS_CNTer,
Auth_Attempt AS Auth_Attempt,
Auth_Op_Action AS Auth_Op_Action,
Token_Number AS Token_NBR,
Market_Specific_Data_Indicator_Code AS Market_Specific_Data_Indicator_Code,
Auth_Currency AS Auth_Currency,
Network_Auth_Indicator_2_Code AS Network_Auth_Indicator_2_Code,
Send_Mode_Code AS Send_Mode_Code,
DCC_Rate AS DCC_Rate,
Authorization_Characteristics_Indicators AS Authorization_Characteristics_Indicators,
Voucher_Number AS Voucher_NBR,
P2PE_Token_Assurance AS P2PE_Token_Assurance,
DCC_Indicator AS DCC_Indicator,
CVV_Result_Code AS CVV_Result_Code,
Shipment_To_ZipCode AS Shipment_To_ZipCode,
Online_Transaction_Indicator AS Online_TRANS_Indicator,
Card_Group AS Card_Group,
Debit_Fee_Amount AS Debit_Fee_AMT,
Native_Experience_Provider AS Native_Experience_Provider,
Paypal_Account_Number AS Paypal_Account_NBR,
Merchant_Category_Code AS Merchant_Category_Code,
Shipment_From_Zip_Code AS Shipment_From_Zip_Code,
Transaction_Category_Code AS TRANS_Category_Code,
DCC_Indicator_Code AS DCC_Indicator_Code,
Type_Code AS Type_Code,
CVV_Result AS CVV_Result,
Emv_Application_Interchange_Profile AS Emv_Application_Interchange_Profile,
Payment_Method_Code AS Payment_Method_Code,
Sub_Merchant_ID AS Sub_Merchant_ID,
Cash_Back_Indicator AS Cash_Back_Indicator,
Source AS Source,
Card_Level_Result AS Card_Level_Result,
Partial_Approval_Flag AS Partial_Approval_Flag,
EC_Indicator_Code AS EC_Indicator_Code,
Settle_CutOff_Time AS Settle_CutOff_Time,
Network_Auth_Indicator AS Network_Auth_Indicator,
Native_Transaction_SubType AS Native_TRANS_SubType,
Entry_Mode_Indicator AS Entry_Mode_Indicator,
Mobile_Wallet_Code AS Mobile_Wallet_Code,
Native_Reject_Code AS Native_Reject_Code,
Local_Date_Time AS Local_Date_Time,
Transaction_Originator AS TRANS_Originator,
Account_Number_First_6 AS Account_NBR_First_6,
Authorization_Trace_Number AS Authorization_Trace_NBR,
Online_Transaction_Indicator_Code AS Online_TRANS_Indicator_Code,
Emv_Application_Cryptogram AS Emv_Application_Cryptogram,
GUID AS GUID,
Emv_Terminal_Capability_Profile AS Emv_Terminal_Capability_Profile,
Initial_Assoc_Resp_Code AS Initial_Assoc_Resp_Code,
Network_Token_Number AS Network_Token_NBR,
External_Merchant_ID AS External_Merchant_ID,
P2PE_Token_Type AS P2PE_Token_Type,
EC_Indicator AS EC_Indicator,
CAVV_Response_Code AS CAVV_Response_Code,
Reversed AS Reversed,
Processor AS Processor,
DCC_Country_Code AS DCC_CNTry_Code,
DRD_Network_List AS DRD_Network_List,
Recurring_Type AS Recurring_Type,
Mobile_Wallet AS Mobile_Wallet,
Original_Authorization_Response AS Original_Authorization_Response,
Auth_Code AS Auth_Code,
Emv_Issuer_Application_Data AS Emv_Issuer_Application_Data,
Initial_Assoc_Resp AS Initial_Assoc_Resp,
DRD_Regulator_Indicator AS DRD_Regulator_Indicator,
Customer_Name AS Customer_Name,
Message_Type_Identifier AS Message_Type_Identifier,
Link_Response_Desc AS Link_Response_Desc,
Emv_Chip_Transaction_Ind AS Emv_Chip_TRANS_Ind,
Time_Taken AS Time_Taken,
POS_Term_Cap AS POS_Term_Cap,
Network_Auth_Indicator_3 AS Network_Auth_Indicator_3,
Network_Auth_Indicator_2 AS Network_Auth_Indicator_2,
DRD_Network_Used AS DRD_Network_Used,
Source_Code AS Source_Code,
AVS_Response AS AVS_Response,
Recurring_Type_Code AS Recurring_Type_Code,
VAT_Reference_Number AS VAT_Reference_NBR,
Experience_Provider AS Experience_Provider,
MC_Promotion_Code AS MC_Promotion_Code,
Emv_Terminal_Country_Code AS Emv_Terminal_CNTry_Code,
Terminal_ID AS Terminal_ID,
Adjustment_Amount AS Adjustment_AMT,
Type AS Type,
Sequence_Number AS Sequence_NBR,
Sales_Tax_Amount AS Sales_Tax_AMT,
Emv_Transaction_Type AS Emv_TRANS_Type,
Link_Response AS Link_Response,
Third_Party_Processor_VAR_ID AS Third_Party_Processor_VAR_ID,
POS_Condition_Description AS POS_Condition_Description,
Network_Input_Indicator AS Network_Input_Indicator,
Site_ID__FE AS Site_ID__FE,
Approval_Status_Code AS Approval_Status_Code,
Card_Expiry_Date AS Card_Expiry_Date,
Network AS Network,
Auth_Currency_Code AS Auth_Currency_Code,
Cash_Back_Indicator_Code AS Cash_Back_Indicator_Code,
Terminal_Serial_Number AS Terminal_Serial_NBR,
Native_Auth_Op_Action AS Native_Auth_Op_Action,
Card_Group_Code AS Card_Group_Code,
Terminal_Type AS Terminal_Type,
Visa_Valid_Code AS Visa_Valid_Code,
Send_Mode AS Send_Mode,
Approval_Status AS Approval_Status,
External_Terminal_ID AS External_Terminal_ID,
Velocity_Indicator AS Velocity_Indicator,
Auth_Op_Action_Code AS Auth_Op_Action_Code,
Link_Response_Desc_Code AS Link_Response_Desc_Code,
External_Reference_ID AS External_Reference_ID,
Bank_Fiid AS Bank_Fiid,
P2PE_Encryption_Type AS P2PE_Encryption_Type,
Network_Auth_Indicator_Code AS Network_Auth_Indicator_Code,
Decline_Reason_Code AS Decline_Reason_Code,
Token_Response_Code AS Token_Response_Code,
Auth_Op_Status AS Auth_Op_Status,
Discount_Amount AS Discount_AMT,
Adjustment_Indicator AS Adjustment_Indicator,
Emv_Issuer_Authentication_Data AS Emv_Issuer_Authentication_Data,
Emv_Card_Holder_Verification_Results AS Emv_Card_Holder_Verification_Results,
Card_Network_CVC_Error AS Card_Network_CVC_Error,
DRD_Route_Function AS DRD_Route_Function,
Network_Transaction_ID AS Network_TRANS_ID,
MasterCard_Banknet_Date AS MasterCard_Banknet_Date,
SubType AS SubType,
P2PE_Token_Type_Code AS P2PE_Token_Type_Code,
Service_Code AS Service_Code,
Decline_Reason AS Decline_Reason,
Native_Debit_Reject_Code AS Native_Debit_Reject_Code,
Network_Code AS Network_Code,
Gift_Card_Number AS Gift_Card_NBR,
Shipment_To_Country_Code AS Shipment_To_CNTry_Code,
Time_in_EPOCH AS Time_in_EPOCH,
AVS_Response_Code AS AVS_Response_Code,
Auth_Attempt_Code AS Auth_Attempt_Code,
Fraud_Score AS Fraud_Score,
Record_Number AS Record_NBR,
Merchant_Name AS Merchant_Name,
Emv_Chip_Authentication_Result AS Emv_Chip_Authentication_Result,
Par_ID AS Par_ID,
Auth_Op_Status_Code AS Auth_Op_Status_Code,
DCC_Amount AS DCC_AMT,
Issuer_Script_Results AS Issuer_Script_Results,
source_system_name,
FILENAME as FILE_NAME,
LOAD_ID,
LOAD_DTTM
FROM 
%%RDS%%.ARB.AUTHORIZATION);


create view IF NOT EXISTS CHARGEBACK_ARBYS(
	ACQUIRER_REFERENCE_NBR,
	ORIG_SLIP_NBR,
	PROCESSED_CURRENCY_CODE,
	MERCHANT_FUNDING_CURRENCY_CODE,
	DISPUTE_REASON_CODE,
	CHARGEBACK_STATUS,
	DISPUTE_CURRENCY_CODE,
	PROCESSOR,
	PRE_DISPUTE_INDICATOR,
	TOKEN_REQUESTER_ID,
	AUTH_RECORD_SEQUENCE,
	PROCESSOR_CODE,
	PAYMENT_METHOD,
	DEBIT_NETWORK_ID_CODE,
	SEND_MODE_CODE,
	DEBITED_MERCHANT,
	MERCHANT_CATEGORY,
	FINANCIAL_CATEGORY,
	VME_ADDITIONAL_AUTH_REASON_CODE,
	CHARGEBACK_DISPOSITION,
	DEBIT_NETWORK_ID,
	MERCHANT_CATEGORY_CODE,
	CHARGEBACK_WIN_LOSS_CODE,
	EC_INDICATOR,
	BANKNET_REF,
	TOKEN_RESPONSE,
	PRE_DISPUTE_INDICATOR_CODE,
	MOBILE_INDICATOR,
	CHARGEBACK_DISPOSITION_CODE,
	SUBMITTED_MERCHANT_ID,
	TOKEN_RESPONSE_CODE,
	INVOICE_NBR,
	REVERSED_TO_ISSUER,
	CHARGEBACK_CYCLE,
	NETWORK_SETTLE_CURRENCY,
	SERVICE_CODE_CODE,
	ORIGINAL_CHARGEBACK_SLIP_NBR,
	CHARGEBACK_CATEGORY_CODE,
	DISPUTE_REASON_KEY,
	CAVV_RESPONSE,
	MERCHANT_FUNDING_AMT,
	CHARGEBACK_WIN_LOSS,
	BATCH_NBR,
	ORDER_NBR,
	MERCHANT_FUNDING_CURRENCY,
	ACCOUNT_NBR_FIRST_6,
	BATCH_DATE,
	FINANCIAL_CATEGORY_CODE,
	EC_INDICATOR_CODE,
	CHARGEBACK_AMT,
	CAVV_RESPONSE_CODE,
	DOCUMENT_INDICATOR,
	REQUEST_DATE,
	MULTIPLE_CLEARING_SEQUENCE_NBR,
	RESPONDED_ON_DATE,
	SITE_ID__BE,
	STATUS_DATE,
	DUE_DATE,
	CHARGEBACK_RELEVANCE,
	TRANS_TYPE_CODE,
	PAYMENT_METHOD_CODE,
	RECEIVED_DATE,
	RECURRING_TYPE,
	MOBILE_WALLET_CODE,
	CASE_NBR,
	PROCESSED_CURRENCY,
	SERVICE_CODE,
	MULTIPLE_CLEARING_SEQUENCE_CNT,
	MOBILE_WALLET,
	CHARGEBACK_STATUS_CODE,
	CENTRAL_PROCESSING_DATE,
	SEND_MODE,
	CHARGEBACK_WORK_TYPE_CODE,
	ACCOUNT_NBR,
	REVERSED_BY_MERCHANT,
	UNIQUE_TRANS_ID,
	CHARGEBACK_REFERENCE_ID,
	DISPUTE_AMT,
	ALT_CASE_NBR,
	ADJUSTMENT_AMT,
	RECURRING_TYPE_CODE,
	TRANS_AMT,
	TERMINAL_ID,
	DISPUTE_CURRENCY_CODE_CODE,
	MEMBER_MESSAGE_TEXT,
	ADJUSTMENT_DATE,
	ORIG_TRAN_CURRENCY,
	TRANS_ID,
	NETWORK_SETTLE_AMT,
	RETRIEVAL_REQUEST_ID,
	ACCOUNT_NBR_LAST_4,
	AUTHORIZATION_CODE,
	ADJUSTMENT_AMT_SIGN,
	CHARGEBACK_WORK_TYPE,
	AUTH_NETWORK_CODE,
	DISPOSITION_DATE,
	SUBMITTED_TRANS_CURRENCY_CODE,
	MERCHANT_SETTLE_AMT,
	DISPUTE_REASON,
	EXTERNAL_MID,
	NETWORK_SETTLE_CURRENCY_CODE,
	CHARGEBACK_CATEGORY,
	PARTIAL_AMT_FLAG,
	SUBMITTED_TRANS_CURRENCY_CODE_CODE,
	CHARGEBACK_RELEVANCE_CODE,
	TXN_DATE,
	AUTH_NETWORK,
	VME_ADDITIONAL_AUTH_METHOD,
	TRANS_TYPE,
	ALT_MID,
	CB_RESPONSE_RECEIVED,
	BIN_ID,
	CAPTURE_METHOD,
	EXTERNAL_REFERENCE_ID,
	SITE_STATE,
	SITE_ADDRESS,
	PROCESSOR_CODE_MERCHANT,
	SITE_CITY,
	SITE_ALT_ID,
	SITE_ZIP_CODE,
	SITE_PHONE_NO,
	PROCESSOR_MERCHANT,
	SITE_NAME,
	CARD_EBT_STATE,
	CARD_ISSUE_DETAIL_CODE,
	CARD_B2B_PROGRAM,
	CARD_FAST_FUNDS_CODE,
	CARD_ONLINE_GAMBLING_INDICATOR,
	CARD_RELOADABLE,
	CARD_FUND_SOURCE,
	CARD_DEBIT_NETWORK_PARTICIPANT,
	CARD_PRODUCT_SUBTYPE_CODE,
	CARD_ISSUE_TYPE,
	CARD_FAST_FUNDS,
	BIN_ID_CARD,
	CARD_ISSUING_CNTRY,
	CARD_ORIGINAL_CREDIT_INDICATOR,
	CARD_DEBIT_NETWORK_PARTICIPANT_CODE,
	CARD_ISSUER,
	CARD_FUND_SOURCE_CODE,
	CARD_ISSUER_BIN,
	CARD_CLASS_CODE,
	CARD_ISSUER_CODE,
	CARD_ISSUE_DETAIL,
	CARD_ISSUER_REGULATED_CODE,
	CARD_ORIGINAL_CREDIT_INDICATOR_CODE,
	TOKEN_BIN_INDICATOR,
	CARD_ISSUER_REGULATED,
	CARD_BILLING_CURRENCY,
	CARD_BILLING_CURRENCY_CODE,
	CARD_BRAND_CODE,
	CARD_EBT_STATE_CODE,
	TOKEN_BIN_INDICATOR_CODE,
	CARD_CLASS,
	CARD_ONLINE_GAMBLING_INDICATOR_CODE,
	CARD_PRODUCT_SUBTYPE,
	CARD_MONEY_SEND_INDICATOR_CODE,
	CARD_MONEY_SEND_INDICATOR,
	CARD_PROCESSING_INDICATOR,
	CARD_MONEY_TRANSFER_INDICATOR,
	CARD_RELOADABLE_CODE,
	CARD_PROCESSING_INDICATOR_CODE,
	CARD_ISSUE_TYPE_CODE,
	CARD_MONEY_TRANSFER_INDICATOR_CODE,
	CARD_B2B_PROGRAM_CODE,
	CARD_BRAND,
	CARD_ISSUING_CNTRY_CODE,
	SOURCE_SYSTEM_NAME,
	FILE_NAME,
	LOAD_ID,
	LOAD_DTTM
) as ( 
SELECT 
Acquirer_Reference_Number AS Acquirer_Reference_NBR,
Orig_Slip_Number AS Orig_Slip_NBR,
Processed_Currency_Code AS Processed_Currency_Code,
Merchant_Funding_Currency_Code AS Merchant_Funding_Currency_Code,
Dispute_Reason_Code AS Dispute_Reason_Code,
Chargeback_Status AS Chargeback_Status,
Dispute_Currency_Code AS Dispute_Currency_Code,
Processor AS Processor,
Pre_Dispute_Indicator AS Pre_Dispute_Indicator,
Token_Requester_ID AS Token_Requester_ID,
Auth_Record_Sequence AS Auth_Record_Sequence,
Processor_Code AS Processor_Code,
Payment_Method AS Payment_Method,
Debit_Network_ID_Code AS Debit_Network_ID_Code,
Send_Mode_Code AS Send_Mode_Code,
Debited_Merchant AS Debited_Merchant,
Merchant_Category AS Merchant_Category,
Financial_Category AS Financial_Category,
VME_Additional_Auth_Reason_Code AS VME_Additional_Auth_Reason_Code,
Chargeback_Disposition AS Chargeback_Disposition,
Debit_Network_ID AS Debit_Network_ID,
Merchant_Category_Code AS Merchant_Category_Code,
Chargeback_Win_Loss_Code AS Chargeback_Win_Loss_Code,
EC_Indicator AS EC_Indicator,
BankNet_Ref AS BankNet_Ref,
Token_Response AS Token_Response,
Pre_Dispute_Indicator_Code AS Pre_Dispute_Indicator_Code,
Mobile_Indicator AS Mobile_Indicator,
Chargeback_Disposition_Code AS Chargeback_Disposition_Code,
Submitted_Merchant_Id AS Submitted_Merchant_Id,
Token_Response_Code AS Token_Response_Code,
Invoice_Number AS Invoice_NBR,
Reversed_to_Issuer AS Reversed_to_Issuer,
Chargeback_Cycle AS Chargeback_Cycle,
Network_Settle_Currency AS Network_Settle_Currency,
Service_Code_Code AS Service_Code_Code,
Original_Chargeback_Slip_Number AS Original_Chargeback_Slip_NBR,
Chargeback_Category_Code AS Chargeback_Category_Code,
Dispute_Reason_Key AS Dispute_Reason_Key,
CAVV_Response AS CAVV_Response,
Merchant_Funding_Amount AS Merchant_Funding_AMT,
Chargeback_Win_Loss AS Chargeback_Win_Loss,
Batch_Number AS Batch_NBR,
Order_Number AS Order_NBR,
Merchant_Funding_Currency AS Merchant_Funding_Currency,
Account_Number_First_6 AS Account_NBR_First_6,
Batch_Date AS Batch_Date,
Financial_Category_Code AS Financial_Category_Code,
EC_Indicator_Code AS EC_Indicator_Code,
Chargeback_Amount AS Chargeback_AMT,
CAVV_Response_Code AS CAVV_Response_Code,
Document_Indicator AS Document_Indicator,
Request_Date AS Request_Date,
Multiple_Clearing_Sequence_Number AS Multiple_Clearing_Sequence_NBR,
Responded_On_Date AS Responded_On_Date,
Site_ID__BE AS Site_ID__BE,
Status_Date AS Status_Date,
Due_Date AS Due_Date,
Chargeback_Relevance AS Chargeback_Relevance,
Transaction_Type_Code AS TRANS_Type_Code,
Payment_Method_Code AS Payment_Method_Code,
Received_Date AS Received_Date,
Recurring_Type AS Recurring_Type,
Mobile_Wallet_Code AS Mobile_Wallet_Code,
Case_Number AS Case_NBR,
Processed_Currency AS Processed_Currency,
Service_Code AS Service_Code,
Multiple_Clearing_Sequence_Count AS Multiple_Clearing_Sequence_CNT,
Mobile_Wallet AS Mobile_Wallet,
Chargeback_Status_Code AS Chargeback_Status_Code,
Central_Processing_Date AS Central_Processing_Date,
Send_Mode AS Send_Mode,
Chargeback_Work_Type_Code AS Chargeback_Work_Type_Code,
Account_Number AS Account_NBR,
Reversed_by_Merchant AS Reversed_by_Merchant,
Unique_Transaction_ID AS Unique_TRANS_ID,
Chargeback_Reference_ID AS Chargeback_Reference_ID,
Dispute_Amount AS Dispute_AMT,
Alternate_Case_Number AS ALT_Case_NBR,
Adjustment_Amount AS Adjustment_AMT,
Recurring_Type_Code AS Recurring_Type_Code,
Transaction_Amount AS TRANS_AMT,
Terminal_ID AS Terminal_ID,
Dispute_Currency_Code_Code AS Dispute_Currency_Code_Code,
Member_Message_Text AS Member_Message_Text,
Adjustment_Date AS Adjustment_Date,
Orig_Tran_Currency AS Orig_Tran_Currency,
Transaction_ID AS TRANS_ID,
Network_Settle_Amount AS Network_Settle_AMT,
Retrieval_Request_Id AS Retrieval_Request_Id,
Account_Number_Last_4 AS Account_NBR_Last_4,
Authorization_Code AS Authorization_Code,
Adjustment_Amount_Sign AS Adjustment_AMT_Sign,
Chargeback_Work_Type AS Chargeback_Work_Type,
Auth_Network_Code AS Auth_Network_Code,
Disposition_Date AS Disposition_Date,
Submitted_Transaction_Currency_Code AS Submitted_TRANS_Currency_Code,
Merchant_Settle_Amount AS Merchant_Settle_AMT,
Dispute_Reason AS Dispute_Reason,
External_Mid AS External_Mid,
Network_Settle_Currency_Code AS Network_Settle_Currency_Code,
Chargeback_Category AS Chargeback_Category,
Partial_Amount_Flag AS Partial_AMT_Flag,
Submitted_Transaction_Currency_Code_Code AS Submitted_TRANS_Currency_Code_Code,
Chargeback_Relevance_Code AS Chargeback_Relevance_Code,
Txn_Date AS Txn_Date,
Auth_Network AS Auth_Network,
VME_Additional_Auth_Method AS VME_Additional_Auth_Method,
Transaction_Type AS TRANS_Type,
Alternate_Mid AS ALT_Mid,
CB_Response_Received AS CB_Response_Received,
Bin_ID AS Bin_ID,
Capture_Method AS Capture_Method,
External_Reference_ID AS External_Reference_ID,
Site_State AS Site_State,
Site_Address AS Site_Address,
Processor_Code_Merchant AS Processor_Code_Merchant,
Site_City AS Site_City,
Site_Alternate_ID AS Site_ALT_ID,
Site_Zip_Code AS Site_Zip_Code,
Site_Phone_No AS Site_Phone_No,
Processor_Merchant AS Processor_Merchant,
Site_Name AS Site_Name,
Card_EBT_State AS Card_EBT_State,
Card_Issue_Detail_Code AS Card_Issue_Detail_Code,
Card_B2B_Program AS Card_B2B_Program,
Card_Fast_Funds_Code AS Card_Fast_Funds_Code,
Card_Online_Gambling_Indicator AS Card_Online_Gambling_Indicator,
Card_Reloadable AS Card_Reloadable,
Card_Fund_Source AS Card_Fund_Source,
Card_Debit_Network_Participant AS Card_Debit_Network_Participant,
Card_Product_SubType_Code AS Card_Product_SubType_Code,
Card_Issue_Type AS Card_Issue_Type,
Card_Fast_Funds AS Card_Fast_Funds,
Bin_ID_Card AS Bin_ID_Card,
Card_Issuing_Country AS Card_Issuing_CNTry,
Card_Original_Credit_Indicator AS Card_Original_Credit_Indicator,
Card_Debit_Network_Participant_Code AS Card_Debit_Network_Participant_Code,
Card_Issuer AS Card_Issuer,
Card_Fund_Source_Code AS Card_Fund_Source_Code,
Card_Issuer_Bin AS Card_Issuer_Bin,
Card_Class_Code AS Card_Class_Code,
Card_Issuer_Code AS Card_Issuer_Code,
Card_Issue_Detail AS Card_Issue_Detail,
Card_Issuer_Regulated_Code AS Card_Issuer_Regulated_Code,
Card_Original_Credit_Indicator_Code AS Card_Original_Credit_Indicator_Code,
Token_Bin_Indicator AS Token_Bin_Indicator,
Card_Issuer_Regulated AS Card_Issuer_Regulated,
Card_Billing_Currency AS Card_Billing_Currency,
Card_Billing_Currency_Code AS Card_Billing_Currency_Code,
Card_Brand_Code AS Card_Brand_Code,
Card_EBT_State_Code AS Card_EBT_State_Code,
Token_Bin_Indicator_Code AS Token_Bin_Indicator_Code,
Card_Class AS Card_Class,
Card_Online_Gambling_Indicator_Code AS Card_Online_Gambling_Indicator_Code,
Card_Product_SubType AS Card_Product_SubType,
Card_Money_Send_Indicator_Code AS Card_Money_Send_Indicator_Code,
Card_Money_Send_Indicator AS Card_Money_Send_Indicator,
Card_Processing_Indicator AS Card_Processing_Indicator,
Card_Money_Transfer_Indicator AS Card_Money_Transfer_Indicator,
Card_Reloadable_Code AS Card_Reloadable_Code,
Card_Processing_Indicator_Code AS Card_Processing_Indicator_Code,
Card_Issue_Type_Code AS Card_Issue_Type_Code,
Card_Money_Transfer_Indicator_Code AS Card_Money_Transfer_Indicator_Code,
Card_B2B_Program_Code AS Card_B2B_Program_Code,
Card_Brand AS Card_Brand,
Card_Issuing_Country_Code AS Card_Issuing_CNTry_Code,
source_system_name,
FILENAME as FILE_NAME,
LOAD_ID,
LOAD_DTTM
FROM 
%%RDS%%.ARB.CHARGEBACK);

create view IF NOT EXISTS SETTLEMENT_ARBYS(
	AVS_FLAG,
	RATE_DIFFERENCE,
	CARD_SERVICE_TYPE,
	CARD_SCHEME_DESCRIPTION,
	NETWORK_CODE,
	ISA_FEE_CAP_IND,
	TOKEN_TYPE,
	INVALID_TRANS_INDICATOR,
	TRANS_TYPE,
	REJECT_REASON,
	SUB_MERCHANT_ID,
	MC_CARDHOLDER_AUTHENTICATION,
	NEW_AUTH_FEE,
	PER_TRAN_DIFFERENCE,
	TOTAL_AUTH_AMT,
	PROCESSOR,
	REJECT_INDICATOR,
	TERMINAL_TRANS_DATE,
	TRANS_SOURCE,
	CLIENT_NBR,
	ORDER_NBR,
	NON_QUALIFICATION_CNT,
	TXN_DATE,
	VISA_PRODUCT_ID,
	AUTHORIZATION_AMT,
	SITE_NAME,
	AUTH_TYPE_CODE,
	INFRASTRUCTURE_FEE_PER_TRAN_AMT,
	POSTING_METHOD,
	ISA_FEE_AMT,
	TERMINAL_BATCH_NBR,
	CARD_USAGE,
	NETWORK_SECURITY_FEE_PER_TRAN_AMT,
	MULTIPLE_CLEARING_SEQUENCE_NBR,
	EC_INDICATOR,
	BANK_REFERENCE_NBR,
	AUTH_CODE,
	BASE_RATE,
	PLAN_CODE_DESCRIPTION,
	REFUND_CNT,
	TRANS_TIME,
	REJECT_REASON_CODE,
	ACQUIRER_FEE_CAP_IND,
	CASH_BACK_AMT,
	EC_INDICATOR_CODE,
	ACQUIRER_FEE_PER_TRAN_RATE,
	RETAILER_FEE_CAP_IND,
	DEBIT_NETWORK_ID,
	POS_ENTRY_MODE,
	PAYMENT_METHOD_CODE_CODE,
	REJECT_REASON_CODE_CODE,
	NON_AUGMENT_NET_AMT,
	ISA_FEE_PER_TRAN_AMT,
	NON_QUALIFICATION_CODE,
	MERCHANT_CATEGORY,
	INTEGRITY_CLASS,
	BATCH_SEQUENCE_ID,
	DOWNGRADE_REJECT_REASON_FLAG_CODE,
	SUBMITTED_CURRENCY,
	REFERENCE_SEQ_ID,
	REFUND_AMT,
	QUALIFIED_I_C_CODE,
	IC_FEE_CAP_IND,
	MARKET_SPECIFIC_INDICATOR,
	BILLBACK_REASON,
	BATCH_DATE,
	TERMINAL_ID,
	REJECT_CNT,
	PLATFORM_NAME,
	PRODUCT_CODE,
	SITE_ID__BE_CODE,
	CARD_SCHEME,
	BANK_NET_REFERENCE_NBR,
	MERCHANT_SERVICE,
	RETAILER_FEE_AMT,
	BASE,
	PROCESSOR_CODE,
	NON_QUALIFICATION_AMT,
	VISA_PURCHASE_IDENTIFIER_FORMAT,
	BATCH_SOURCE,
	RECEIPT_NBR,
	SUBMITTED_REJECT_AMT,
	IC_FEE_RATE,
	FILE_TYPE_CODE,
	PROCESSED_CURRENCY,
	TRAN_TYPE_2,
	TRAN_TYPE_1,
	TRAN_TYPE_4,
	TRAN_TYPE_3,
	TRAN_TYPE_5,
	SETTLE_SPEND_QUALIFIED_INDICATOR,
	RETAILER_FEE_PER_TRAN_RATE,
	MULTI_CURRENCY_CONFIG_TYPE,
	NON_AUGMENT_PLAN_FLAG_CODE,
	PRODUCT_CODE_CODE,
	BATCH_SOURCE_CODE,
	MINIMUM,
	SUB_MERCHANT_NAME,
	RECORD_ID,
	CARD_USAGE_TYPE,
	FUNDED_DATE,
	REJECTED_AMT,
	CROSS_BOARDER_ACQUIRER_FEE_CAP_IND,
	CARD_USAGE_CODE_DESCRIPTION,
	DEBIT_CASH_BACK_AMT,
	ISA_FEE_PER_TRAN_RATE,
	CARD_PRESENCE_INDICATOR,
	BIN_ID,
	DISCOUNT_AMT,
	ACCOUNT_NBR_LAST_4,
	AUGMENT_AVERAGE_DISCOUNT,
	MOBILE_INDICATOR,
	DDA_NBR__LAST4,
	CHARGE_TIER_LEVEL,
	MC_SECURITY_PROTOCOL,
	NON_QUALIFICATION_REASON,
	PROCESSED_SALES_AMT,
	SURCHARGE_AMT,
	CUSTOM_TRACKING,
	MAXIMUM,
	ADMIN_FEE_CAP_IND,
	TOKEN_REQUESTOR_FLAG,
	NETWORK_SECURITY_FEE_AMT,
	CHIP_CONDITION_CODE,
	ACCOUNT_NBR_FIRST_6,
	PAN_SEQUENCE_NBR,
	EXPIRY_DATE,
	POSTED_INDICATOR,
	TOKEN_REQUESTOR_FLAG_CODE,
	EXTERNAL_ID,
	READ_TERMINAL_CAPACITY,
	BATCH_DESCRIPTION,
	SERVICE_CODE_ID,
	PAYMENT_METHOD,
	FEE_CATEGORY_1,
	FEE_CATEGORY_4,
	FEE_CATEGORY_5,
	FEE_CATEGORY_2,
	FEE_CATEGORY_3,
	NET_SALES_CNT,
	TRANS_MODE_CODE,
	RECLASS_INDICATOR,
	CARD_EXPIRATION_DATE,
	PINLESS_INDICATOR,
	SUBMITTED_REFUND_AMT,
	INFRASTRUCTURE_FEE_PER_TRAN_RATE,
	DOWNGRADE_REJECT_REASON_FLAG,
	FOREIGN_CURR_RATE,
	SUBMITTED_CURRENCY_CODE,
	PROCESSED_CURRENCY_CODE,
	INFRASTRUCTURE_FEE_AMT,
	BATCH_SLIP_NBR,
	ACQUIRER_FEE_PER_TRAN_AMT,
	TOKEN_REQUESTER_ID,
	PER_TRANS_FEE,
	DEBIT_NETWORK_ID_CODE,
	CARD_USAGE_DESCRIPTION,
	MULTI_CURRENCY_CONFIG_TYPE_CODE,
	CVV2_RESULT,
	INVOICE_NBR,
	PROCESSED_INTERCHANGE_SAVINGS_AMT,
	CROSS_BOARDER_ACQUIRER_FEE_PER_TRAN_AMT,
	DOWNGRADE_REJECT_DESCRIPTION_CODE,
	EXPANDED_TERMINAL_ID,
	MERCHANT_REFERENCE_NBR,
	CROSS_BOARDER_ACQUIRER_FEE_AMT,
	VISA_SERVICE_DEVELOP,
	VISA_TRANS_ID,
	ACQUIRER_REFERENCE_NBR,
	ADMIN_FEE_AMT,
	INTERCHANGE_CHARGE_FEE_AMT,
	SALES_CNT,
	NETWORK_SECURITY_FEE_CAP_IND,
	TIP_AMT,
	TRANS_ID,
	PLAN_CODE,
	NETWORK,
	SUBMITTED_SALES_AMT,
	CHARGE_TYPE_5,
	CHARGE_TYPE_4,
	CHARGE_TYPE_3,
	CHARGE_TYPE_2,
	NETWORK_SECURITY_FEE_PER_TRAN_RATE,
	MASTERCARD_PRODUCT_ID,
	INTERCHANGE_PERCENT,
	PURCHASE_IDENTIFIER,
	DEFAULT_CHARGE,
	SERVICE_CODE,
	CROSS_BOARDER_ACQUIRER_FEE_PER_TRAN_RATE,
	SWITCH_FEE_AMT,
	FILE_TYPE,
	FEE_PROGRAM_INDICATOR,
	FOREIGN_CURR_AMT,
	NON_AUGMENT_INTERCHANGE_CHARGE_FEE_AMT,
	CONVENIENCE_FEE,
	TRANS_MODE,
	SUBMITTED_INTERCHANGE_SAVINGS_AMT,
	ADMIN_FEE_PER_TRAN_RATE,
	ACQUIRER_FEE_AMT,
	STORE_NBR,
	CARD_USAGE_CODE,
	AGREEMENT_ID,
	SITE_ID__BE,
	NET_AMT,
	CAT_LEVEL,
	PINLESS_INDICATOR_CODE,
	BATCH_NO,
	SURCHARGE_INDICATOR,
	GLOBAL_TRANS_ID,
	BATCH_UID,
	SALES_TAX_AMT,
	CARDHOLDER_ID_METHOD,
	TRANS_STATUS,
	EXTERNAL_REFERENCE_ID,
	DEBIT_TERMINAL_TIME,
	PROCESSED_SURCHARGE_CNT,
	AUTHORIZATION_RESPONSE_CODE,
	MULTIPLE_CLEARING_SEQUENCE_CNT,
	AUTHORIZATION_DATE,
	SWITCH_FEE_CAP_IND,
	MOBILE_WALLET_CODE,
	PAYMENT_METHOD_CODE_POS,
	AUTH_SOURCE,
	RETAILER_FEE_PER_TRAN_AMT,
	TRANS_CNTRY,
	TERMINAL_BATCH_CLOSE_TIME,
	ORIGINAL_PLAN_CODE,
	SALES_AMT,
	CLEARING_I_C_CODE,
	INFRASTRUCTURE_FEE_CAP_IND,
	PAYMENT_METHOD_CODE,
	DOWNGRADE_REJECT_CODE,
	TRANS_TYPE_CODE,
	PINLESS_FLAG,
	CAPTURE_METHOD,
	SWITCH_FEE_PER_TRAN_RATE,
	AUTH_TYPE,
	SWITCH_FEE_PER_TRAN_AMT,
	TRAN_UID,
	RECORD_DATE,
	ORIGINAL_PLAN_CODE_DESCRIPTION,
	RECLASS_INDICATOR_CODE,
	MERCHANT_CATEGORY_CODE,
	MOBILE_WALLET,
	TRANS_STATUS_CODE,
	ACCOUNT_NBR,
	TERMINAL_BATCH_CLOSE_DATE,
	IC_CARD_CONDITION_CODE,
	NON_QUALIFICATION_REASON_CODE,
	DOWNGRADE_REJECT_DESCRIPTION,
	DEBIT_TERMINAL_DATE,
	CHARGE_AMT_5,
	CHARGE_AMT_4,
	CHARGE_AMT_3,
	CHARGE_AMT_2,
	CHARGE_AMT_1,
	CVC2_RESULT,
	PC_TERMINAL_CAPABILITY,
	SITE_STATE,
	SITE_ADDRESS,
	PROCESSOR_CODE_MERCHANT,
	SITE_CITY,
	SITE_ALT_ID,
	SITE_ZIP_CODE,
	SITE_PHONE_NO,
	PROCESSOR_MERCHANT,
	SITE_NAME_MERCHANT,
	CARD_EBT_STATE,
	CARD_ISSUE_DETAIL_CODE,
	CARD_B2B_PROGRAM,
	CARD_FAST_FUNDS_CODE,
	CARD_ONLINE_GAMBLING_INDICATOR,
	CARD_RELOADABLE,
	CARD_FUND_SOURCE,
	CARD_DEBIT_NETWORK_PARTICIPANT,
	CARD_PRODUCT_SUBTYPE_CODE,
	CARD_ISSUE_TYPE,
	CARD_FAST_FUNDS,
	BIN_ID_CARD,
	CARD_ISSUING_CNTRY,
	CARD_ORIGINAL_CREDIT_INDICATOR,
	CARD_DEBIT_NETWORK_PARTICIPANT_CODE,
	CARD_ISSUER,
	CARD_FUND_SOURCE_CODE,
	CARD_ISSUER_BIN,
	CARD_CLASS_CODE,
	CARD_ISSUER_CODE,
	CARD_ISSUE_DETAIL,
	CARD_ISSUER_REGULATED_CODE,
	CARD_ORIGINAL_CREDIT_INDICATOR_CODE,
	TOKEN_BIN_INDICATOR,
	CARD_ISSUER_REGULATED,
	CARD_BILLING_CURRENCY,
	CARD_BILLING_CURRENCY_CODE,
	CARD_BRAND_CODE,
	CARD_EBT_STATE_CODE,
	TOKEN_BIN_INDICATOR_CODE,
	CARD_CLASS,
	CARD_ONLINE_GAMBLING_INDICATOR_CODE,
	CARD_PRODUCT_SUBTYPE,
	CARD_MONEY_SEND_INDICATOR_CODE,
	CARD_MONEY_SEND_INDICATOR,
	CARD_PROCESSING_INDICATOR,
	CARD_MONEY_TRANSFER_INDICATOR,
	CARD_RELOADABLE_CODE,
	CARD_PROCESSING_INDICATOR_CODE,
	CARD_ISSUE_TYPE_CODE,
	CARD_MONEY_TRANSFER_INDICATOR_CODE,
	CARD_B2B_PROGRAM_CODE,
	CARD_BRAND,
	CARD_ISSUING_CNTRY_CODE,
	SOURCE_SYSTEM_NAME,
	FILE_NAME,
	LOAD_ID,
	LOAD_DTTM
) as ( 
SELECT 
AVS_Flag AS AVS_Flag,
Rate_Difference AS Rate_Difference,
Card_Service_Type AS Card_Service_Type,
Card_Scheme_Description AS Card_Scheme_Description,
Network_Code AS Network_Code,
ISA_Fee_Cap_Ind AS ISA_Fee_Cap_Ind,
Token_Type AS Token_Type,
Invalid_Transaction_Indicator AS Invalid_TRANS_Indicator,
Transaction_Type AS TRANS_Type,
Reject_Reason AS Reject_Reason,
Sub_Merchant_ID AS Sub_Merchant_ID,
MC_Cardholder_Authentication AS MC_Cardholder_Authentication,
New_Auth_Fee AS New_Auth_Fee,
Per_Tran_Difference AS Per_Tran_Difference,
Total_Auth_Amount AS Total_Auth_AMT,
Processor AS Processor,
Reject_Indicator AS Reject_Indicator,
Terminal_Transaction_Date AS Terminal_TRANS_Date,
Transaction_Source AS TRANS_Source,
Client_Number AS Client_NBR,
Order_Number AS Order_NBR,
Non_Qualification_Count AS Non_Qualification_CNT,
Txn_Date AS Txn_Date,
Visa_Product_ID AS Visa_Product_ID,
Authorization_Amount AS Authorization_AMT,
Site_Name AS Site_Name,
Auth_Type_Code AS Auth_Type_Code,
Infrastructure_Fee_Per_Tran_Amount AS Infrastructure_Fee_Per_Tran_AMT,
Posting_Method AS Posting_Method,
ISA_Fee_Amount AS ISA_Fee_AMT,
Terminal_Batch_Number AS Terminal_Batch_NBR,
Card_Usage AS Card_Usage,
Network_Security_Fee_Per_Tran_Amount AS Network_Security_Fee_Per_Tran_AMT,
Multiple_Clearing_Sequence_Number AS Multiple_Clearing_Sequence_NBR,
EC_Indicator AS EC_Indicator,
Bank_Reference_Number AS Bank_Reference_NBR,
Auth_Code AS Auth_Code,
Base_Rate AS Base_Rate,
Plan_Code_Description AS Plan_Code_Description,
Refund_Count AS Refund_CNT,
Transaction_Time AS TRANS_Time,
Reject_Reason_Code AS Reject_Reason_Code,
Acquirer_Fee_Cap_Ind AS Acquirer_Fee_Cap_Ind,
Cash_Back_Amount AS Cash_Back_AMT,
EC_Indicator_Code AS EC_Indicator_Code,
Acquirer_Fee_Per_Tran_Rate AS Acquirer_Fee_Per_Tran_Rate,
Retailer_Fee_Cap_Ind AS Retailer_Fee_Cap_Ind,
Debit_Network_Id AS Debit_Network_Id,
POS_Entry_Mode AS POS_Entry_Mode,
Payment_Method_Code_Code AS Payment_Method_Code_Code,
Reject_Reason_Code_Code AS Reject_Reason_Code_Code,
Non_Augment_Net_Amount AS Non_Augment_Net_AMT,
ISA_Fee_Per_Tran_Amount AS ISA_Fee_Per_Tran_AMT,
Non_Qualification_Code AS Non_Qualification_Code,
Merchant_Category AS Merchant_Category,
Integrity_Class AS Integrity_Class,
Batch_Sequence_ID AS Batch_Sequence_ID,
Downgrade_Reject_Reason_Flag_Code AS Downgrade_Reject_Reason_Flag_Code,
Submitted_Currency AS Submitted_Currency,
Reference_Seq_ID AS Reference_Seq_ID,
Refund_Amount AS Refund_AMT,
Qualified_I_C_Code AS Qualified_I_C_Code,
IC_Fee_Cap_Ind AS IC_Fee_Cap_Ind,
Market_Specific_Indicator AS Market_Specific_Indicator,
Billback_Reason AS Billback_Reason,
Batch_Date AS Batch_Date,
Terminal_ID AS Terminal_ID,
Reject_Count AS Reject_CNT,
Platform_Name AS Platform_Name,
Product_Code AS Product_Code,
Site_ID__BE_Code AS Site_ID__BE_Code,
Card_Scheme AS Card_Scheme,
Bank_Net_Reference_Number AS Bank_Net_Reference_NBR,
Merchant_Service AS Merchant_Service,
Retailer_Fee_Amount AS Retailer_Fee_AMT,
Base AS Base,
Processor_Code AS Processor_Code,
Non_Qualification_Amount AS Non_Qualification_AMT,
Visa_Purchase_Identifier_Format AS Visa_Purchase_Identifier_Format,
Batch_Source AS Batch_Source,
Receipt_Number AS Receipt_NBR,
Submitted_Reject_Amount AS Submitted_Reject_AMT,
IC_Fee_Rate AS IC_Fee_Rate,
File_Type_Code AS File_Type_Code,
Processed_Currency AS Processed_Currency,
Tran_Type_2 AS Tran_Type_2,
Tran_Type_1 AS Tran_Type_1,
Tran_Type_4 AS Tran_Type_4,
Tran_Type_3 AS Tran_Type_3,
Tran_Type_5 AS Tran_Type_5,
Settle_Spend_Qualified_Indicator AS Settle_Spend_Qualified_Indicator,
Retailer_Fee_Per_Tran_Rate AS Retailer_Fee_Per_Tran_Rate,
Multi_Currency_Config_Type AS Multi_Currency_Config_Type,
Non_Augment_Plan_Flag_Code AS Non_Augment_Plan_Flag_Code,
Product_Code_Code AS Product_Code_Code,
Batch_Source_Code AS Batch_Source_Code,
Minimum AS Minimum,
Sub_Merchant_Name AS Sub_Merchant_Name,
Record_ID AS Record_ID,
Card_Usage_Type AS Card_Usage_Type,
Funded_Date AS Funded_Date,
Rejected_Amount AS Rejected_AMT,
Cross_Boarder_Acquirer_Fee_Cap_Ind AS Cross_Boarder_Acquirer_Fee_Cap_Ind,
Card_Usage_Code_Description AS Card_Usage_Code_Description,
Debit_Cash_Back_Amount AS Debit_Cash_Back_AMT,
ISA_Fee_Per_Tran_Rate AS ISA_Fee_Per_Tran_Rate,
Card_Presence_Indicator AS Card_Presence_Indicator,
Bin_ID AS Bin_ID,
Discount_Amount AS Discount_AMT,
Account_Number_Last_4 AS Account_NBR_Last_4,
Augment_Average_Discount AS Augment_Average_Discount,
Mobile_Indicator AS Mobile_Indicator,
DDA_Number__Last4 AS DDA_NBR__Last4,
Charge_Tier_Level AS Charge_Tier_Level,
MC_Security_Protocol AS MC_Security_Protocol,
Non_Qualification_Reason AS Non_Qualification_Reason,
Processed_Sales_Amount AS Processed_Sales_AMT,
Surcharge_Amount AS Surcharge_AMT,
Custom_Tracking AS Custom_Tracking,
Maximum AS Maximum,
Admin_Fee_Cap_Ind AS Admin_Fee_Cap_Ind,
Token_Requestor_Flag AS Token_Requestor_Flag,
Network_Security_Fee_Amount AS Network_Security_Fee_AMT,
Chip_Condition_Code AS Chip_Condition_Code,
Account_Number_First_6 AS Account_NBR_First_6,
PAN_Sequence_Number AS PAN_Sequence_NBR,
Expiry_Date AS Expiry_Date,
Posted_Indicator AS Posted_Indicator,
Token_Requestor_Flag_Code AS Token_Requestor_Flag_Code,
External_ID AS External_ID,
Read_Terminal_Capacity AS Read_Terminal_Capacity,
Batch_Description AS Batch_Description,
Service_Code_Id AS Service_Code_Id,
Payment_Method AS Payment_Method,
Fee_Category_1 AS Fee_Category_1,
Fee_Category_4 AS Fee_Category_4,
Fee_Category_5 AS Fee_Category_5,
Fee_Category_2 AS Fee_Category_2,
Fee_Category_3 AS Fee_Category_3,
Net_Sales_Count AS Net_Sales_CNT,
Transaction_Mode_Code AS TRANS_Mode_Code,
Reclass_Indicator AS Reclass_Indicator,
Card_Expiration_Date AS Card_Expiration_Date,
Pinless_Indicator AS Pinless_Indicator,
Submitted_Refund_Amount AS Submitted_Refund_AMT,
Infrastructure_Fee_Per_Tran_Rate AS Infrastructure_Fee_Per_Tran_Rate,
Downgrade_Reject_Reason_Flag AS Downgrade_Reject_Reason_Flag,
Foreign_Curr_Rate AS Foreign_Curr_Rate,
Submitted_Currency_Code AS Submitted_Currency_Code,
Processed_Currency_Code AS Processed_Currency_Code,
Infrastructure_Fee_Amount AS Infrastructure_Fee_AMT,
Batch_Slip_Number AS Batch_Slip_NBR,
Acquirer_Fee_Per_Tran_Amount AS Acquirer_Fee_Per_Tran_AMT,
Token_Requester_ID AS Token_Requester_ID,
Per_Transaction_Fee AS Per_TRANS_Fee,
Debit_Network_Id_Code AS Debit_Network_Id_Code,
Card_Usage_Description AS Card_Usage_Description,
Multi_Currency_Config_Type_Code AS Multi_Currency_Config_Type_Code,
CVV2_Result AS CVV2_Result,
Invoice_Number AS Invoice_NBR,
Processed_Interchange_Savings_Amount AS Processed_Interchange_Savings_AMT,
Cross_Boarder_Acquirer_Fee_Per_Tran_Amount AS Cross_Boarder_Acquirer_Fee_Per_Tran_AMT,
Downgrade_Reject_Description_Code AS Downgrade_Reject_Description_Code,
Expanded_Terminal_ID AS Expanded_Terminal_ID,
Merchant_Reference_Number AS Merchant_Reference_NBR,
Cross_Boarder_Acquirer_Fee_Amount AS Cross_Boarder_Acquirer_Fee_AMT,
Visa_Service_Develop AS Visa_Service_Develop,
Visa_Transaction_ID AS Visa_TRANS_ID,
Acquirer_Reference_Number AS Acquirer_Reference_NBR,
Admin_Fee_Amount AS Admin_Fee_AMT,
Interchange_Charge_Fee_Amount AS Interchange_Charge_Fee_AMT,
Sales_Count AS Sales_CNT,
Network_Security_Fee_Cap_Ind AS Network_Security_Fee_Cap_Ind,
Tip_Amount AS Tip_AMT,
Transaction_ID AS TRANS_ID,
Plan_Code AS Plan_Code,
Network AS Network,
Submitted_Sales_Amount AS Submitted_Sales_AMT,
Charge_Type_5 AS Charge_Type_5,
Charge_Type_4 AS Charge_Type_4,
Charge_Type_3 AS Charge_Type_3,
Charge_Type_2 AS Charge_Type_2,
Network_Security_Fee_Per_Tran_Rate AS Network_Security_Fee_Per_Tran_Rate,
Mastercard_Product_ID AS Mastercard_Product_ID,
Interchange_Percent AS Interchange_Percent,
Purchase_Identifier AS Purchase_Identifier,
Default_Charge AS Default_Charge,
Service_Code AS Service_Code,
Cross_Boarder_Acquirer_Fee_Per_Tran_Rate AS Cross_Boarder_Acquirer_Fee_Per_Tran_Rate,
Switch_Fee_Amount AS Switch_Fee_AMT,
File_Type AS File_Type,
Fee_Program_Indicator AS Fee_Program_Indicator,
Foreign_Curr_Amount AS Foreign_Curr_AMT,
Non_Augment_Interchange_Charge_Fee_Amount AS Non_Augment_Interchange_Charge_Fee_AMT,
Convenience_Fee AS Convenience_Fee,
Transaction_Mode AS TRANS_Mode,
Submitted_Interchange_Savings_Amount AS Submitted_Interchange_Savings_AMT,
Admin_Fee_Per_Tran_Rate AS Admin_Fee_Per_Tran_Rate,
Acquirer_Fee_Amount AS Acquirer_Fee_AMT,
Store_Number AS Store_NBR,
Card_Usage_Code AS Card_Usage_Code,
Agreement_ID AS Agreement_ID,
Site_ID__BE AS Site_ID__BE,
Net_Amount AS Net_AMT,
CAT_Level AS CAT_Level,
Pinless_Indicator_Code AS Pinless_Indicator_Code,
Batch_No AS Batch_No,
Surcharge_Indicator AS Surcharge_Indicator,
Global_Transaction_ID AS Global_TRANS_ID,
Batch_UID AS Batch_UID,
Sales_Tax_Amount AS Sales_Tax_AMT,
Cardholder_ID_Method AS Cardholder_ID_Method,
Transaction_Status AS TRANS_Status,
External_Reference_ID AS External_Reference_ID,
Debit_Terminal_Time AS Debit_Terminal_Time,
Processed_Surcharge_Count AS Processed_Surcharge_CNT,
Authorization_Response_Code AS Authorization_Response_Code,
Multiple_Clearing_Sequence_Count AS Multiple_Clearing_Sequence_CNT,
Authorization_Date AS Authorization_Date,
Switch_Fee_Cap_Ind AS Switch_Fee_Cap_Ind,
Mobile_Wallet_Code AS Mobile_Wallet_Code,
Payment_Method_Code_POS AS Payment_Method_Code_POS,
Auth_Source AS Auth_Source,
Retailer_Fee_Per_Tran_Amount AS Retailer_Fee_Per_Tran_AMT,
Transaction_Country AS TRANS_CNTry,
Terminal_Batch_Close_Time AS Terminal_Batch_Close_Time,
Original_Plan_Code AS Original_Plan_Code,
Sales_Amount AS Sales_AMT,
Clearing_I_C_Code AS Clearing_I_C_Code,
Infrastructure_Fee_Cap_Ind AS Infrastructure_Fee_Cap_Ind,
Payment_Method_Code AS Payment_Method_Code,
Downgrade_Reject_Code AS Downgrade_Reject_Code,
Transaction_Type_Code AS TRANS_Type_Code,
Pinless_Flag AS Pinless_Flag,
Capture_Method AS Capture_Method,
Switch_Fee_Per_Tran_Rate AS Switch_Fee_Per_Tran_Rate,
Auth_Type AS Auth_Type,
Switch_Fee_Per_Tran_Amount AS Switch_Fee_Per_Tran_AMT,
Tran_UID AS Tran_UID,
Record_Date AS Record_Date,
Original_Plan_Code_Description AS Original_Plan_Code_Description,
Reclass_Indicator_Code AS Reclass_Indicator_Code,
Merchant_Category_Code AS Merchant_Category_Code,
Mobile_Wallet AS Mobile_Wallet,
Transaction_Status_Code AS TRANS_Status_Code,
Account_Number AS Account_NBR,
Terminal_Batch_Close_Date AS Terminal_Batch_Close_Date,
IC_Card_Condition_Code AS IC_Card_Condition_Code,
Non_Qualification_Reason_Code AS Non_Qualification_Reason_Code,
Downgrade_Reject_Description AS Downgrade_Reject_Description,
Debit_Terminal_Date AS Debit_Terminal_Date,
Charge_Amount_5 AS Charge_AMT_5,
Charge_Amount_4 AS Charge_AMT_4,
Charge_Amount_3 AS Charge_AMT_3,
Charge_Amount_2 AS Charge_AMT_2,
Charge_Amount_1 AS Charge_AMT_1,
CVC2_Result AS CVC2_Result,
PC_Terminal_Capability AS PC_Terminal_Capability,
Site_State AS Site_State,
Site_Address AS Site_Address,
Processor_Code_Merchant AS Processor_Code_Merchant,
Site_City AS Site_City,
Site_Alternate_ID AS Site_ALT_ID,
Site_Zip_Code AS Site_Zip_Code,
Site_Phone_No AS Site_Phone_No,
Processor_Merchant AS Processor_Merchant,
Site_Name_Merchant AS Site_Name_Merchant,
Card_EBT_State AS Card_EBT_State,
Card_Issue_Detail_Code AS Card_Issue_Detail_Code,
Card_B2B_Program AS Card_B2B_Program,
Card_Fast_Funds_Code AS Card_Fast_Funds_Code,
Card_Online_Gambling_Indicator AS Card_Online_Gambling_Indicator,
Card_Reloadable AS Card_Reloadable,
Card_Fund_Source AS Card_Fund_Source,
Card_Debit_Network_Participant AS Card_Debit_Network_Participant,
Card_Product_SubType_Code AS Card_Product_SubType_Code,
Card_Issue_Type AS Card_Issue_Type,
Card_Fast_Funds AS Card_Fast_Funds,
Bin_ID_Card AS Bin_ID_Card,
Card_Issuing_Country AS Card_Issuing_CNTry,
Card_Original_Credit_Indicator AS Card_Original_Credit_Indicator,
Card_Debit_Network_Participant_Code AS Card_Debit_Network_Participant_Code,
Card_Issuer AS Card_Issuer,
Card_Fund_Source_Code AS Card_Fund_Source_Code,
Card_Issuer_Bin AS Card_Issuer_Bin,
Card_Class_Code AS Card_Class_Code,
Card_Issuer_Code AS Card_Issuer_Code,
Card_Issue_Detail AS Card_Issue_Detail,
Card_Issuer_Regulated_Code AS Card_Issuer_Regulated_Code,
Card_Original_Credit_Indicator_Code AS Card_Original_Credit_Indicator_Code,
Token_Bin_Indicator AS Token_Bin_Indicator,
Card_Issuer_Regulated AS Card_Issuer_Regulated,
Card_Billing_Currency AS Card_Billing_Currency,
Card_Billing_Currency_Code AS Card_Billing_Currency_Code,
Card_Brand_Code AS Card_Brand_Code,
Card_EBT_State_Code AS Card_EBT_State_Code,
Token_Bin_Indicator_Code AS Token_Bin_Indicator_Code,
Card_Class AS Card_Class,
Card_Online_Gambling_Indicator_Code AS Card_Online_Gambling_Indicator_Code,
Card_Product_SubType AS Card_Product_SubType,
Card_Money_Send_Indicator_Code AS Card_Money_Send_Indicator_Code,
Card_Money_Send_Indicator AS Card_Money_Send_Indicator,
Card_Processing_Indicator AS Card_Processing_Indicator,
Card_Money_Transfer_Indicator AS Card_Money_Transfer_Indicator,
Card_Reloadable_Code AS Card_Reloadable_Code,
Card_Processing_Indicator_Code AS Card_Processing_Indicator_Code,
Card_Issue_Type_Code AS Card_Issue_Type_Code,
Card_Money_Transfer_Indicator_Code AS Card_Money_Transfer_Indicator_Code,
Card_B2B_Program_Code AS Card_B2B_Program_Code,
Card_Brand AS Card_Brand,
Card_Issuing_Country_Code AS Card_Issuing_CNTry_Code,
source_system_name,
FILENAME as FILE_NAME,
LOAD_ID,
LOAD_DTTM
FROM 
%%RDS%%.ARB.SETTLEMENT);

create view IF NOT EXISTS FUNDING_ARBYS(
	FEES,
	NOTE,
	FEES_CODE,
	ACCOUNT_CURRENCY_NET_AMT,
	MINOR_CATEGORY_CODE,
	MAJOR_CATEGORY_CODE,
	SITE_ID__BE,
	REFERENCE_NBR,
	NET_SALES_CODE,
	PROCESSED_FEES,
	LOCAL_AMOUNT,
	FEE_SEQUENCE_DESCRIPTION,
	END_DATE,
	PROCESSED_DEPOSIT,
	TRAN_AMT,
	POSTED_DATE,
	DDA_NBR__LAST4,
	DEPOSIT_TYPE_CODE,
	INTRA_ACCOUNT_REF_NO,
	BATCH_NO,
	SERVICE_CHARGES_CODE,
	LAST_EXECUTION_DATE,
	CHARGEBACKS_REVERSALS_CODE,
	PAYMENT_MINIMUM_AMT,
	CNT_LIMIT,
	PROCESSED_CURRENCY_CODE,
	CHARGEBACKS_REVERSALS,
	MINOR_CATEGORY,
	PAID_BY_OTHERS_CODE,
	MAJOR_CATEGORY,
	ITEM_CNT,
	FUNDED_DATE,
	PAYMENT_STATUS,
	CREDIT_AMT,
	DEPOSIT_TYPE,
	ADJUSTMENTS_CODE,
	EXECUTION_CNT,
	PROCESSED_NET_SALES,
	PROCESSED_CURRENCY,
	PROCESSED_CHARGEBACKS_REVERSALS,
	DESTINATION_ACCOUNT_TYPE,
	PAYMENT_PERCENT,
	IC_CHARGES,
	ACCOUNT_CURRENCY_GROSS_AMT,
	TRANS_CATEGORY_,
	PAYMENT_REF_NO,
	PROCESSED_I_C_CHARGES,
	MERCHANT_ID_SHORT,
	INTERCHANGE_CD,
	ADJUSTMENTS,
	RECORD_DATE,
	PAYMENT_BASE_AMT,
	PROCESSED_AMT_PAID,
	ACCOUNT_TYPE,
	FEE_SEQUENCE_CODE,
	ACCOUNT_NET_AMT,
	IC_CHARGES_CODE,
	PRODUCT_CODE,
	FACTOR_AGENT,
	PROCESSED_SERVICE_CHARGES,
	DEBIT_AMT,
	BANK_REFERENCE_NBR,
	TRANS_TYPE_CODE,
	PROCESSOR_CODE,
	PROCESSED_PAID_BY_OTHERS,
	ADDENDUM_ARN,
	BATCH_DATE,
	PROCESSED_ADJUSTMENTS,
	ACCOUNT_ID,
	REVERSAL_INDICATOR,
	PERIOD,
	INSTRUCTION_TYPE,
	START_DATE,
	AMT_LIMIT,
	PRODUCT_CODE_CODE,
	DESCRIPTION,
	ACQUIRER_REFERENCE_NUMBER,
	PAID_BY_OTHERS,
	VALUE_DATE,
	ACCOUNT_CURRENCY,
	NET_SALES,
	PROCESSOR,
	RELATED_SOURCE_TRANS,
	SERVICE_CHARGES,
	PAYMENT_MAXIMUM_AMT,
	SOURCE_SYSTEM_NAME,
	FILE_NAME,
	LOAD_ID,
	LOAD_DTTM
) as (
SELECT 
Fees AS Fees,
Note AS Note,
Fees_Code AS Fees_Code,
Account_Currency_Net_Amount AS Account_Currency_Net_AMT,
Minor_Category_Code AS Minor_Category_Code,
Major_Category_Code AS Major_Category_Code,
Site_ID__BE AS Site_ID__BE,
Reference_Number AS Reference_NBR,
Net_Sales_Code AS Net_Sales_Code,
Processed_Fees AS Processed_Fees,
Local_amount AS Local_amount,
Fee_Sequence_Description AS Fee_Sequence_Description,
End_Date AS End_Date,
Processed_Deposit AS Processed_Deposit,
Tran_Amount AS Tran_AMT,
Posted_Date AS Posted_Date,
DDA_Number__Last4 AS DDA_NBR__Last4,
Deposit_Type_Code AS Deposit_Type_Code,
Intra_Account_Ref_No AS Intra_Account_Ref_No,
Batch_No AS Batch_No,
Service_Charges_Code AS Service_Charges_Code,
Last_Execution_Date AS Last_Execution_Date,
Chargebacks_Reversals_Code AS Chargebacks_Reversals_Code,
Payment_Minimum_Amount AS Payment_Minimum_AMT,
Count_Limit AS CNT_Limit,
Processed_Currency_Code AS Processed_Currency_Code,
Chargebacks_Reversals AS Chargebacks_Reversals,
Minor_Category AS Minor_Category,
Paid_By_Others_Code AS Paid_By_Others_Code,
Major_Category AS Major_Category,
Item_Count AS Item_CNT,
Funded_Date AS Funded_Date,
Payment_Status AS Payment_Status,
Credit_Amount AS Credit_AMT,
Deposit_Type AS Deposit_Type,
Adjustments_Code AS Adjustments_Code,
Execution_Count AS Execution_CNT,
Processed_Net_Sales AS Processed_Net_Sales,
Processed_Currency AS Processed_Currency,
Processed_Chargebacks_Reversals AS Processed_Chargebacks_Reversals,
Destination_Account_type AS Destination_Account_type,
Payment_Percent AS Payment_Percent,
IC_Charges AS IC_Charges,
Account_Currency_Gross_Amount AS Account_Currency_Gross_AMT,
Transaction_Category_ AS TRANS_Category_,
Payment_Ref_No AS Payment_Ref_No,
Processed_I_C_Charges AS Processed_I_C_Charges,
Merchant_ID_Short AS Merchant_ID_Short,
Interchange_CD AS Interchange_CD,
Adjustments AS Adjustments,
Record_Date AS Record_Date,
Payment_Base_Amount AS Payment_Base_AMT,
Processed_Amount_Paid AS Processed_AMT_Paid,
Account_Type AS Account_Type,
Fee_Sequence_Code AS Fee_Sequence_Code,
Account_Net_Amount AS Account_Net_AMT,
IC_Charges_Code AS IC_Charges_Code,
Product_Code AS Product_Code,
Factor_Agent AS Factor_Agent,
Processed_Service_Charges AS Processed_Service_Charges,
Debit_Amount AS Debit_AMT,
Bank_Reference_Number AS Bank_Reference_NBR,
Transaction_Type_Code AS TRANS_Type_Code,
Processor_Code AS Processor_Code,
Processed_Paid_by_Others AS Processed_Paid_by_Others,
Addendum_ARN AS Addendum_ARN,
Batch_Date AS Batch_Date,
Processed_Adjustments AS Processed_Adjustments,
Account_ID AS Account_ID,
Reversal_Indicator AS Reversal_Indicator,
Period AS Period,
Instruction_Type AS Instruction_Type,
Start_Date AS Start_Date,
Amount_Limit AS AMT_Limit,
Product_Code_Code AS Product_Code_Code,
Description AS Description,
Acquirer_Reference_number AS Acquirer_Reference_number,
Paid_By_Others AS Paid_By_Others,
Value_Date AS Value_Date,
Account_Currency AS Account_Currency,
Net_Sales AS Net_Sales,
Processor AS Processor,
Related_Source_Transaction AS Related_Source_TRANS,
Service_Charges AS Service_Charges,
Payment_Maximum_Amount AS Payment_Maximum_AMT,
source_system_name,
FILENAME AS FILE_NAME,
LOAD_ID,
LOAD_DTTM
FROM 
%%RDS%%.ARB.FUNDING);

CREATE view IF NOT EXISTS SITES_ARBYS(
	PROCESSOR,
	SITE_ID,
	MERCHANT_ID,
	SITE_NAME,
	SITE_ADDRESS,
	SITE_CITY,
	SITE_STATE,
	SITE_ZIP_CODE,
	SITE_PHONE_NO,
	MCC_CODE,
	WEB_SITE,
	CARD_PRESENT_IN,
	CONTACT_NAME_FOR_MERCHANT,
	CONTACT_NAME_AT_MERCHANT_LOCATION,
	PHONE_MERCHANT_ADDRESS,
	EMAIL,
	STORE_IDENTIFIER,
	SITE_ALTERATE_ID,
	CORP_ID,
	CORP_NAME,
	LEAD_ID,
	LEAD_NAME,
	AGENT_ID,
	AGENT_NAME,
	EFFECTIVE_FROM,
	EFFECTIVE_TO,
	STATE,
	FAX_MERCHANT_ADDRESS,
	ACTIVE,
	CORPORATE_CONTACT,
	CORPORATE_ADDRESS,
	NETWORK_TOKEN_OFFERING_TYPE,
	SOURCE_SYSTEM_NAME,
	FILENAME,
	LOAD_ID,
	LOAD_DTTM
) AS ( 
SELECT 
Processor AS Processor,
Site_ID AS Site_ID,
Merchant_ID AS Merchant_ID,
Site_Name AS Site_Name,
Site_Address AS Site_Address,
Site_City AS Site_City,
Site_State AS Site_State,
Site_Zip_Code AS Site_Zip_Code,
Site_Phone_No AS Site_Phone_No,
MCC_Code AS MCC_Code,
Web_Site AS Web_Site,
Card_Present_In AS Card_Present_In,
Contact_Name_for_Merchant AS Contact_Name_for_Merchant,
Contact_Name_at_Merchant_Location AS Contact_Name_at_Merchant_Location,
Phone_Merchant_address AS Phone_Merchant_address,
Email AS Email,
Store_Identifier AS Store_Identifier,
Site_Alternate_ID AS Site_Alternate_ID,
Corp_ID AS Corp_ID,
Corp_Name AS Corp_Name,
Lead_ID AS Lead_ID,
Lead_Name AS Lead_Name,
Agent_ID AS Agent_ID,
Agent_Name AS Agent_Name,
Effective_From AS Effective_From,
Effective_To AS Effective_To,
State AS State,
Fax_Merchant_address AS Fax_Merchant_address,
Active AS Active,
Corporate_Contact AS Corporate_Contact,
Corporate_Address AS Corporate_Address,
Network_Token_Offering_Type AS Network_Token_Offering_Type,
source_system_name AS source_system_name,
FILENAME AS FILE_NAME,
LOAD_ID AS LOAD_ID,
LOAD_DTTM AS LOAD_DTTM
FROM 
%%RDS%%.ARB.SITES where filename = (select max(filename) from %%RDS%%.ARB.SITES) and  Active='Yes');


CREATE OR REPLACE view SITES_BWW(
	PROCESSOR,
	SITE_ID,
	MERCHANT_ID,
	SITE_NAME,
	SITE_ADDRESS,
	SITE_CITY,
	SITE_STATE,
	SITE_ZIP_CODE,
	SITE_PHONE_NO,
	MCC_CODE,
	WEB_SITE,
	CARD_PRESENT_IN,
	CONTACT_NAME_FOR_MERCHANT,
	CONTACT_NAME_AT_MERCHANT_LOCATION,
	PHONE_MERCHANT_ADDRESS,
	EMAIL,
	STORE_IDENTIFIER,
	SITE_ALTERATE_ID,
	CORP_ID,
	CORP_NAME,
	LEAD_ID,
	LEAD_NAME,
	AGENT_ID,
	AGENT_NAME,
	EFFECTIVE_FROM,
	EFFECTIVE_TO,
	STATE,
	FAX_MERCHANT_ADDRESS,
	ACTIVE,
	CORPORATE_CONTACT,
	CORPORATE_ADDRESS,
	NETWORK_TOKEN_OFFERING_TYPE,
	SOURCE_SYSTEM_NAME,
	FILENAME,
	LOAD_ID,
	LOAD_DTTM
) AS ( 
SELECT 
Processor AS Processor,
Site_ID AS Site_ID,
Merchant_ID AS Merchant_ID,
Site_Name AS Site_Name,
Site_Address AS Site_Address,
Site_City AS Site_City,
Site_State AS Site_State,
Site_Zip_Code AS Site_Zip_Code,
Site_Phone_No AS Site_Phone_No,
MCC_Code AS MCC_Code,
Web_Site AS Web_Site,
Card_Present_In AS Card_Present_In,
Contact_Name_for_Merchant AS Contact_Name_for_Merchant,
Contact_Name_at_Merchant_Location AS Contact_Name_at_Merchant_Location,
Phone_Merchant_address AS Phone_Merchant_address,
Email AS Email,
Store_Identifier AS Store_Identifier,
Site_Alternate_ID AS Site_Alternate_ID,
Corp_ID AS Corp_ID,
Corp_Name AS Corp_Name,
Lead_ID AS Lead_ID,
Lead_Name AS Lead_Name,
Agent_ID AS Agent_ID,
Agent_Name AS Agent_Name,
Effective_From AS Effective_From,
Effective_To AS Effective_To,
State AS State,
Fax_Merchant_address AS Fax_Merchant_address,
Active AS Active,
Corporate_Contact AS Corporate_Contact,
Corporate_Address AS Corporate_Address,
Network_Token_Offering_Type AS Network_Token_Offering_Type,
source_system_name AS source_system_name,
FILENAME AS FILE_NAME,
LOAD_ID AS LOAD_ID,
LOAD_DTTM AS LOAD_DTTM
FROM 
%%RDS%%.BWW.SITES where filename = (select max(filename) from %%RDS%%.BWW.SITES) and  Active='Yes');