drop TABLE hive_schema_stg.seaware_commission_fact

CREATE EXTERNAL TABLE hive_schema_stg.seaware_commission_fact(
res_id int, 
guest_id int, 
package_id int, 
addon_id int,
invoice_item_type_id int, 
ship_id int, 
agency_id int, 
agent_id int, 
sail_id int, 
currency_code VARCHAR(5), 
currency_rate float, 
commission_type_skey int,
  charge_id int, 
  is_cancelled char(1),  
commission_percent float, 
commission_amount float, 
commission_fare float, 
commission_payout_date timestamp, 
base_commission_voyagefare_regular float, 
base_commission_voyagefare_protected float, 
base_commission_voyagefare_manual float, 
base_commission_voyagefare float, 
base_commission_taxesandfees_regular float, 
base_commission_taxesandfees_protected float, 
base_commission_taxesandfees_manual float, 
base_commission_taxesandfees float, 
base_commission_shorex_regular float, 
base_commission_shorex_protected float, 
base_commission_shorex_manual float, 
base_commission_shorex float, 
base_commission_sailorloot_regular float,
base_commission_sailorloot_protected float,
base_commission_sailorloot_manual float,
base_commission_sailorloot float, 
base_commission_hotelfare_regular float,
base_commission_hotelfare_protected float,
base_commission_hotelfare_manual float,
base_commission_hotelfare float,
base_commission_insurance_regular float,
base_commission_insurance_protected float,
base_commission_insurance float, 
bonus_commission_voyagefare_regular float, 
bonus_commission_voyagefare_protected float, 
bonus_commission_voyagefare_manual float, 
bonus_commission float, 
voyagefare_commission float,
gsa_commission_voyagefare float, 
gsa_commission_taxesandfees float, 
gsa_commission_insurance float, 
gsa_commission_shorex float, 
gsa_commission_sailorloot float, 
protected_commission float, 
base_protected_commission float,
base_commission_other_bookable float,
base_commission_voyagefare_regular_usd float,
base_commission_voyagefare_protected_usd float,
base_commission_voyagefare_manual_usd float,
base_commission_voyagefare_usd float, 
base_commission_taxesandfees_regular_usd float,
base_commission_taxesandfees_protected_usd float,
base_commission_taxesandfees_manual_usd float,
base_commission_taxesandfees_usd float, 
base_commission_shorex_regular_usd float,
base_commission_shorex_protected_usd float,
base_commission_shorex_manual_usd float,
base_commission_shorex_usd float, 
base_commission_sailorloot_regular_usd float, 
base_commission_sailorloot_protected_usd float, 
base_commission_sailorloot_manual_usd float, 
base_commission_sailorloot_usd float, 
base_commission_hotelfare_regular_usd float,
base_commission_hotelfare_protected_usd float,
base_commission_hotelfare_manual_usd float,
base_commission_hotelfare_usd float,
base_commission_insurance_regular_usd float,
base_commission_insurance_protected_usd float,
base_commission_insurance_usd float, 
bonus_commission_voyagefare_regular_usd float,
bonus_commission_voyagefare_protected_usd float,
bonus_commission_voyagefare_manual_usd float,
bonus_commission_usd float, 
voyagefare_commission_usd float,
gsa_commission_voyagefare_usd float, 
gsa_commission_taxesandfees_usd float, 
gsa_commission_insurance_usd float, 
gsa_commission_shorex_usd float, 
gsa_commission_sailorloot_usd float, 
protected_commission_usd float, 
base_protected_commission_usd float,
base_commission_other_bookable_usd float,
etl_ld_dt timestamp)
PARTITIONED BY ( 
  snapshot_date date)
ROW FORMAT SERDE 
  'org.apache.hadoop.hive.ql.io.parquet.serde.ParquetHiveSerDe' 
WITH SERDEPROPERTIES ( 
  'timestamp.formats'='yyyy-MM-dd HH:mm:ss') 
STORED AS INPUTFORMAT 
  'org.apache.hadoop.hive.ql.io.parquet.MapredParquetInputFormat' 
OUTPUTFORMAT 
  'org.apache.hadoop.hive.ql.io.parquet.MapredParquetOutputFormat'
LOCATION
  's3://vv-dev-emr-cluster/data/core/seaware/hvtb_nbx_core_sw_commission_fact'

ALTER TABLE hive_schema_stg.seaware_commission_fact ADD IF NOT EXISTS  PARTITION (snapshot_date = '2020-10-06') location 's3://vv-prod-emr-cluster/data/core/seaware/hvtb_nbx_core_sw_commission_fact/snapshot_date=2020-10-06';
