# Global settings
dag_id: "E2E_SALES_RECON_ALTAMETRICS_DQ"
dag_description: "Mailing DAG for DQ framework"
emails: ['shashikala.g@inspirebrands.com','theja.h@inspirebrands.com','murugan.thirunavukar@inspirebrands.com','divya.s@inspirebrands.com',ravi.voleti@inspirebrands.com]
owner: "DQ"

warehouse_name: "IRB_PRCSSA_IRB_WH"
env: "DEV"

database: "IDS_DEV"
schema_name: "INT_REF"
target_schema: "Sales Recon (BOS)-Arbys"
brand: "%"
table_list:
  - BOS_DAILY_SALES_MEASURE


# Paths
utils_path: "/opt/airflow/dags/transaction/global_utils"
airflow_path: "/opt/airflow/dags/transaction/global_utils/airflow"
