dag_id: "E2E_SALES_RECON_BWW_DPVHST_GNDTENDER_SQL_TO_RDS"
dag_description: "DPVHST_GNDTENDER data load from SQL to ADLS2 and then from ADLS2 to RDS"
email: ["DataServicesHelp@inspirebrands.com", "itdataservicessupport@inspirebrands.com"]
env : "PROD"
warehouse_id : "RA_PRCSSA_IRB_PROD_WH"
snowflake_conn_id : "Snowflake-IRB-PROD-OWNER"
schema_id : "BWW"
file_format: "RDS_PROD.BWW.NBO_BWW_FILE_FORMAT"
pattern: ".*"
azure:
  adf:
    pipeline_name: "COPY_GNDTENDER_ADLS"
    pipeline_file_size: "PL_GET_METADATA_FILE_ADLS"
    sourceFolderName: "landing/ftp/SalesRecon/bww_insight/dpvHstGndTender/"


