create TABLE IF NOT EXISTS FLYWAY_SCHEMA_HISTORY (
	INSTALLED_RANK NUMBER(38,0) NOT NULL,
	VERSION VARCHAR(50),
	DESCRIPTION VARCHAR(200),
	TYPE VARCHAR(20) NOT NULL,
	SCRIPT VARCHAR(1000) NOT NULL,
	CHECKSUM NUMBER(38,0),
	INSTALLED_BY VARCHAR(100) NOT NULL,
	INSTALLED_ON TIMESTAMP_LTZ(9) NOT NULL DEFAULT CURRENT_TIMESTAMP(),
	EXECUTION_TIME NUMBER(38,0) NOT NULL,
	SUCCESS BOOLEAN NOT NULL,
	primary key (INSTALLED_RANK)
);
create view IF NOT EXISTS MEDIA_CAMPAIGNDETAIL_PLR_BV(
	BRANDID,
	CAMPAIGNID,
	FILENAME,
	CHANNELID,
	STRATEGYID,
	CDMUPDATEDATE,
	LOADTYPE,
	SOURCE,
	CAMPAIGNDETAILID,
	PARTNERID,
	CDMLOADDATE
) as SELECT
                               BRANDID, CAMPAIGNID, FILENAME, CHANNELID, STRATEGYID, CDMUPDATEDATE, LOADTYPE, SOURCE, CAMPAIGNDETAILID, PARTNERID, CDMLOADDATE
                            FROM IDS_DEV.MEDIA_BV."MEDIA_CAMPAIGNDETAIL_PLR_BV";
create view IF NOT EXISTS MEDIA_CAMPAIGN_BV(
	CAMPAIGN_ID,
	CAMPAIGN_NM,
	CAMPAIGN_DESC,
	STANDARD_CAMPAIGN_NM,
	STANDARD_CAMPAIGN_DESC,
	STANDARD_OBJECTIVE_TYP,
	MEDIA_TYP,
	LOAD_TYPE,
	BRAND_ID,
	SOURCE_SYSTEM_NM,
	LOAD_ID,
	LOAD_DTTM,
	UPDATE_ID,
	UPDATE_DTTM
) as SELECT
                               CAMPAIGN_ID, CAMPAIGN_NM, CAMPAIGN_DESC, STANDARD_CAMPAIGN_NM, STANDARD_CAMPAIGN_DESC, STANDARD_OBJECTIVE_TYP, MEDIA_TYP, LOAD_TYPE, BRAND_ID, SOURCE_SYSTEM_NM, LOAD_ID, LOAD_DTTM, UPDATE_ID, UPDATE_DTTM
                            FROM IDS_DEV.MEDIA_BV."MEDIA_CAMPAIGN_BV";
create view IF NOT EXISTS MEDIA_CAMPAIGN_DETAIL_BV(
	CAMPAIGN_DETAIL_ID,
	CHANNEL_ID,
	CAMPAIGN_ID,
	PARTNER_ID,
	STRATEGY_ID,
	LOAD_TYP,
	BRAND_ID,
	SOURCE_SYSTEM_NM,
	LOAD_ID,
	LOAD_DTTM,
	UPDATE_ID,
	UPDATE_DTTM
) as SELECT
                               CAMPAIGN_DETAIL_ID, CHANNEL_ID, CAMPAIGN_ID, PARTNER_ID, STRATEGY_ID, LOAD_TYP, BRAND_ID, SOURCE_SYSTEM_NM, LOAD_ID, LOAD_DTTM, UPDATE_ID, UPDATE_DTTM
                            FROM IDS_DEV.MEDIA_BV."MEDIA_CAMPAIGN_DETAIL_BV";
create view IF NOT EXISTS MEDIA_CAMPAIGN_PLR_BV(
	CAMPAIGNDESC,
	LOADTYPE,
	SOURCE,
	CAMPAIGNID,
	CDMUPDATEDATE,
	FILENAME,
	CAMPAIGNNAME,
	CDMLOADDATE,
	BRANDID
) as SELECT
                               CAMPAIGNDESC, LOADTYPE, SOURCE, CAMPAIGNID, CDMUPDATEDATE, FILENAME, CAMPAIGNNAME, CDMLOADDATE, BRANDID
                            FROM IDS_DEV.MEDIA_BV."MEDIA_CAMPAIGN_PLR_BV";
create view IF NOT EXISTS MEDIA_CHANNEL_BV(
	CHANNEL_ID,
	CHANNEL_TYPE_ID,
	CHANNEL_NM,
	CHANNEL_DESC,
	PARENT_CHANNEL_ID,
	LOAD_TYP,
	BRAND_ID,
	SOURCE_SYSTEM_NM,
	LOAD_ID,
	LOAD_DTTM,
	UPDATE_ID,
	UPDATE_DTTM
) as SELECT
                               CHANNEL_ID, CHANNEL_TYPE_ID, CHANNEL_NM, CHANNEL_DESC, PARENT_CHANNEL_ID, LOAD_TYP, BRAND_ID, SOURCE_SYSTEM_NM, LOAD_ID, LOAD_DTTM, UPDATE_ID, UPDATE_DTTM
                            FROM IDS_DEV.MEDIA_BV."MEDIA_CHANNEL_BV";
create view IF NOT EXISTS MEDIA_CHANNEL_HIERARCHY_REF_BV(
	CHANNEL_HIERARCHY_ID,
	SOURCE_CHANNEL_NM,
	SOURCE_SUBCHANNEL_NM,
	SOURCE_SUBCHANNEL2_NM,
	SOURCE_PARTNER_NM,
	INSPIRE_CHANNEL_NM,
	INSPIRE_SUBCHANNEL_NM,
	INSPIRESUBCHANNEL2_NM,
	INSPIRE_PARTNER_NM,
	BRAND_ID,
	SOURCE_SYSTEM_NM,
	LOAD_ID,
	LOAD_DTTM,
	UPDATE_ID,
	UPDATE_DTTM
) as SELECT
                               CHANNEL_HIERARCHY_ID, SOURCE_CHANNEL_NM, SOURCE_SUBCHANNEL_NM, SOURCE_SUBCHANNEL2_NM, SOURCE_PARTNER_NM, INSPIRE_CHANNEL_NM, INSPIRE_SUBCHANNEL_NM, INSPIRESUBCHANNEL2_NM, INSPIRE_PARTNER_NM, BRAND_ID, SOURCE_SYSTEM_NM, LOAD_ID, LOAD_DTTM, UPDATE_ID, UPDATE_DTTM
                            FROM IDS_DEV.MEDIA_BV."MEDIA_CHANNEL_HIERARCHY_REF_BV";
create view IF NOT EXISTS MEDIA_CHANNEL_TYPE_BV(
	CHANNEL_TYPE_ID,
	CHANNEL_TYPE_NM,
	CHANNEL_TYPE_DESC,
	LOAD_TYP,
	BRAND_ID,
	SOURCE_SYSTEM_NM,
	LOAD_ID,
	LOAD_DTTM,
	UPDATE_ID,
	UPDATE_DTTM
) as SELECT
                               CHANNEL_TYPE_ID, CHANNEL_TYPE_NM, CHANNEL_TYPE_DESC, LOAD_TYP, BRAND_ID, SOURCE_SYSTEM_NM, LOAD_ID, LOAD_DTTM, UPDATE_ID, UPDATE_DTTM
                            FROM IDS_DEV.MEDIA_BV."MEDIA_CHANNEL_TYPE_BV";
create view IF NOT EXISTS MEDIA_DMA_REF_BV(
	DMA_CROSSWALK_ID,
	SOURCE_DMA_CD,
	SOURCE_DMA_NM,
	INSPIRE_DMA_CD,
	INSPIRE_DMA_NM,
	BRAND_ID,
	SOURCE_SYSTEM_NM,
	LOAD_ID,
	LOAD_DTTM,
	UPDATE_ID,
	UPDATE_DTTM
) as SELECT
                               DMA_CROSSWALK_ID, SOURCE_DMA_CD, SOURCE_DMA_NM, INSPIRE_DMA_CD, INSPIRE_DMA_NM, BRAND_ID, SOURCE_SYSTEM_NM, LOAD_ID, LOAD_DTTM, UPDATE_ID, UPDATE_DTTM
                            FROM IDS_DEV.MEDIA_BV."MEDIA_DMA_REF_BV";
create view IF NOT EXISTS MEDIA_MENU_PLR_BV(
	CDMLOADDATE,
	PURE_MIX,
	PURE_MIX_NBR_UNITS,
	MAIN_GROUP,
	HARD_CODE_PURE_MIX,
	PLU_NBR,
	STORE_NBR,
	ADD_DATE,
	MAIN_SORT_ORDER,
	PRICE,
	BRANDID,
	COMPONENT,
	PLU_DESCRIPTION,
	SOURCE,
	FILENAME,
	NBR_UNITS,
	BOGO,
	COMPONENT_ID,
	TYPE,
	AFA_PRODUCT_ID,
	AFA_PROD_DESC
) as SELECT
                               CDMLOADDATE, PURE_MIX, PURE_MIX_NBR_UNITS, MAIN_GROUP, HARD_CODE_PURE_MIX, PLU_NBR, STORE_NBR, ADD_DATE, MAIN_SORT_ORDER, PRICE, BRANDID, COMPONENT, PLU_DESCRIPTION, SOURCE, FILENAME, NBR_UNITS, BOGO, COMPONENT_ID, TYPE, AFA_PRODUCT_ID, AFA_PROD_DESC
                            FROM IDS_DEV.MEDIA_BV."MEDIA_MENU_PLR_BV";
create view IF NOT EXISTS MEDIA_PARTNER_BV(
	PARTNER_ID,
	CHANNEL_TYPE_ID,
	PARTNER_NM,
	PARTNER_DESC,
	LOAD_TYP,
	BRAND_ID,
	SOURCE_SYSTEM_NM,
	LOAD_ID,
	LOAD_DTTM,
	UPDATE_ID,
	UPDATE_DTTM
) as SELECT
                               PARTNER_ID, CHANNEL_TYPE_ID, PARTNER_NM, PARTNER_DESC, LOAD_TYP, BRAND_ID, SOURCE_SYSTEM_NM, LOAD_ID, LOAD_DTTM, UPDATE_ID, UPDATE_DTTM
                            FROM IDS_DEV.MEDIA_BV."MEDIA_PARTNER_BV";
create view IF NOT EXISTS MEDIA_PARTNER_PLR_BV(
	LOADTYPE,
	CHANNELTYPEID,
	BRANDID,
	PARTNERNAME,
	SOURCE,
	PARTNERDESC,
	CDMLOADDATE,
	CDMUPDATEDATE,
	PARTNERID,
	FILENAME
) as SELECT
                               LOADTYPE, CHANNELTYPEID, BRANDID, PARTNERNAME, SOURCE, PARTNERDESC, CDMLOADDATE, CDMUPDATEDATE, PARTNERID, FILENAME
                            FROM IDS_DEV.MEDIA_BV."MEDIA_PARTNER_PLR_BV";
create view IF NOT EXISTS MEDIA_PRODUCT_PLR_BV(
	PRODUCT_SORT_ORDER,
	CDMLOADDATE,
	FOOD_PAPER_PCT,
	MAIN_SORT_ORDER,
	MENU_GROUP,
	SUPER_GROUP_SORT_ORDER,
	SUPER_GROUP,
	PRODUCT,
	FOOD_PAPER_DOLLARS,
	BRANDID,
	CONSOLIDATE,
	MENU_TYPE_ORDER,
	PRODUCT_ID,
	SUBGROUP1,
	MENU_STATUS,
	RPT_PRODUCT,
	ORIGINAL_NAME,
	KEY_PRODUCT,
	MAIN_GROUP,
	FILENAME,
	MENU_GROUP_ORDER,
	MENU_TYPE,
	SOURCE,
	NBR_UNITS,
	RPT_SORT_ORDER
) as SELECT
                               PRODUCT_SORT_ORDER, CDMLOADDATE, FOOD_PAPER_PCT, MAIN_SORT_ORDER, MENU_GROUP, SUPER_GROUP_SORT_ORDER, SUPER_GROUP, PRODUCT, FOOD_PAPER_DOLLARS, BRANDID, CONSOLIDATE, MENU_TYPE_ORDER, PRODUCT_ID, SUBGROUP1, MENU_STATUS, RPT_PRODUCT, ORIGINAL_NAME, KEY_PRODUCT, MAIN_GROUP, FILENAME, MENU_GROUP_ORDER, MENU_TYPE, SOURCE, NBR_UNITS, RPT_SORT_ORDER
                            FROM IDS_DEV.MEDIA_BV."MEDIA_PRODUCT_PLR_BV";
create view IF NOT EXISTS MEDIA_PROMOTION_PLR_BV(
	PROMO_ABR1,
	SOURCE,
	PROMO_ID1,
	PROMO_DES1,
	SORT_ORDER,
	PRICE_LEVEL,
	CURRENT_PROMO,
	KEY_PRODUCT,
	PRODUCT_ID,
	PROMO_PRICE,
	FILENAME,
	CDMLOADDATE,
	BRANDID
) as SELECT
                               PROMO_ABR1, SOURCE, PROMO_ID1, PROMO_DES1, SORT_ORDER, PRICE_LEVEL, CURRENT_PROMO, KEY_PRODUCT, PRODUCT_ID, PROMO_PRICE, FILENAME, CDMLOADDATE, BRANDID
                            FROM IDS_DEV.MEDIA_BV."MEDIA_PROMOTION_PLR_BV";
create view IF NOT EXISTS MEDIA_PROMOTION_WEEK_PLR_BV(
	FLIGHT_ID,
	INSERTDATETY,
	ONE_RADIO_COST,
	OUTDOORTRP,
	RADIO_ID1,
	SPOT_CABLEP,
	PROMO_ID2,
	SPOTPRIMARY15,
	LSM_P,
	ADI,
	CABLEPRIMARY15,
	CABLESECONDARY15,
	FILENAME,
	ONE_RADIOS,
	TEST_FLIGHT,
	DJ_RADIO,
	SPORTSP,
	FRANID,
	SOURCE,
	DGTL_AUDIO,
	SPORTSPRIMARY15,
	LOCAL_SEASON,
	OUTDOOR,
	FLIGHT_MONTH,
	POST_BUY_ALL_LOCAL,
	SPOTSECONDARY15,
	CDMLOADDATE,
	CONVERTRATE,
	CRAVE,
	EQUALIZEDP,
	EXTRAS_EMAIL,
	FLIGHT_YEAR,
	RADIO_ID2,
	EQUALIZEDN,
	ONE_TV,
	OTHERTVS,
	SPORTSS,
	ONE_PRICE,
	ONE_CABLE_TV,
	FOCUS,
	SPOT_CABLE,
	UPDATE_DATE,
	BOOKEND_PCT,
	VEHICLE,
	SPORTSSECONDARY15,
	MOBILE_OFFER,
	MONTH,
	ONE_TVS,
	OTHERPRIMARY15,
	SPOT_CABLES,
	TV_SPILL,
	PROMO_ID1,
	RADIO_FOCUS,
	ONE_RADIO,
	ONE_TVS_DM,
	YEAR,
	EQUALIZEDS,
	LSM,
	ONE_RADIOP,
	SPORTS_RADIO,
	BRANDID,
	EQUALIZED_TRPS,
	ONE_TVP,
	OTHERTVP,
	SUB_MKT_RADIO_PTS,
	ONE_TV_ACTUAL,
	RADIO_SPILL,
	SPOT_CABLES_DM,
	WEEK,
	DISPLAY,
	OTHERSECONDARY15,
	TRAFFIC_RADIO,
	NATL_ONLINE,
	ONE_INSERT,
	SPORTS,
	LOCAL_ONLINE,
	PRINT_PARTICIPANTS
) as SELECT
                               FLIGHT_ID, INSERTDATETY, ONE_RADIO_COST, OUTDOORTRP, RADIO_ID1, SPOT_CABLEP, PROMO_ID2, SPOTPRIMARY15, LSM_P, ADI, CABLEPRIMARY15, CABLESECONDARY15, FILENAME, ONE_RADIOS, TEST_FLIGHT, DJ_RADIO, SPORTSP, FRANID, SOURCE, DGTL_AUDIO, SPORTSPRIMARY15, LOCAL_SEASON, OUTDOOR, FLIGHT_MONTH, POST_BUY_ALL_LOCAL, SPOTSECONDARY15, CDMLOADDATE, CONVERTRATE, CRAVE, EQUALIZEDP, EXTRAS_EMAIL, FLIGHT_YEAR, RADIO_ID2, EQUALIZEDN, ONE_TV, OTHERTVS, SPORTSS, ONE_PRICE, ONE_CABLE_TV, FOCUS, SPOT_CABLE, UPDATE_DATE, BOOKEND_PCT, VEHICLE, SPORTSSECONDARY15, MOBILE_OFFER, MONTH, ONE_TVS, OTHERPRIMARY15, SPOT_CABLES, TV_SPILL, PROMO_ID1, RADIO_FOCUS, ONE_RADIO, ONE_TVS_DM, YEAR, EQUALIZEDS, LSM, ONE_RADIOP, SPORTS_RADIO, BRANDID, EQUALIZED_TRPS, ONE_TVP, OTHERTVP, SUB_MKT_RADIO_PTS, ONE_TV_ACTUAL, RADIO_SPILL, SPOT_CABLES_DM, WEEK, DISPLAY, OTHERSECONDARY15, TRAFFIC_RADIO, NATL_ONLINE, ONE_INSERT, SPORTS, LOCAL_ONLINE, PRINT_PARTICIPANTS
                            FROM IDS_DEV.MEDIA_BV."MEDIA_PROMOTION_WEEK_PLR_BV";
create view IF NOT EXISTS MEDIA_SPENDTYPE_PLR_BV(
	BRANDID,
	FILENAME,
	LOADTYPE,
	CDMUPDATEDATE,
	SOURCE,
	CDMLOADDATE,
	SPENDTYPEID,
	SPENDTYPEDESC,
	SPENDTYPENAME
) as SELECT
                               BRANDID, FILENAME, LOADTYPE, CDMUPDATEDATE, SOURCE, CDMLOADDATE, SPENDTYPEID, SPENDTYPEDESC, SPENDTYPENAME
                            FROM IDS_DEV.MEDIA_BV."MEDIA_SPENDTYPE_PLR_BV";
create view IF NOT EXISTS MEDIA_SPEND_TYPE_BV(
	SPEND_TYPE_ID,
	SPEND_TYPE_NM,
	SPEND_TYPE_DESC,
	LOAD_TYP,
	BRAND_ID,
	SOURCE_SYSTEM_NM,
	LOAD_ID,
	LOAD_DTTM,
	UPDATE_ID,
	UPDATE_DTTM
) as SELECT
                               SPEND_TYPE_ID, SPEND_TYPE_NM, SPEND_TYPE_DESC, LOAD_TYP, BRAND_ID, SOURCE_SYSTEM_NM, LOAD_ID, LOAD_DTTM, UPDATE_ID, UPDATE_DTTM
                            FROM IDS_DEV.MEDIA_BV."MEDIA_SPEND_TYPE_BV";
create view IF NOT EXISTS MEDIA_SPEND_WEEK_BV(
	SPEND_ID,
	WEEK_START_DT,
	DMA_CD,
	CAMPAIGN_DETAIL_ID,
	SPEND_TYPE_ID,
	SPEND_AMT,
	CURRENCY_CD,
	LOAD_TYP,
	BRAND_ID,
	SOURCE_SYSTEM_NM,
	LOAD_ID,
	LOAD_DTTM,
	UPDATE_ID,
	UPDATE_DTTM
) as SELECT
                               SPEND_ID, WEEK_START_DT, DMA_CD, CAMPAIGN_DETAIL_ID, SPEND_TYPE_ID, SPEND_AMT, CURRENCY_CD, LOAD_TYP, BRAND_ID, SOURCE_SYSTEM_NM, LOAD_ID, LOAD_DTTM, UPDATE_ID, UPDATE_DTTM
                            FROM IDS_DEV.MEDIA_BV."MEDIA_SPEND_WEEK_BV";
create view IF NOT EXISTS MEDIA_SPEND_WEEK_PLR_BV(
	SPENDAMOUNT,
	SPENDID,
	FILENAME,
	LOADTYPE,
	CAMPAIGNDETAILID,
	DMACODE,
	SPENDTYPEID,
	CURRENCYCODE,
	BRANDID,
	WEEKSTARTDATE,
	CDMLOADDATE,
	CDMUPDATEDATE,
	SOURCE
) as SELECT
                               SPENDAMOUNT, SPENDID, FILENAME, LOADTYPE, CAMPAIGNDETAILID, DMACODE, SPENDTYPEID, CURRENCYCODE, BRANDID, WEEKSTARTDATE, CDMLOADDATE, CDMUPDATEDATE, SOURCE
                            FROM IDS_DEV.MEDIA_BV."MEDIA_SPEND_WEEK_PLR_BV";
create view IF NOT EXISTS MEDIA_STRATEGYTYPE_PLR_BV(
	SOURCE,
	BRANDID,
	STRATEGYTYPENAME,
	STRATEGYTYPEID,
	LOADTYPE,
	CDMLOADDATE,
	FILENAME,
	STRATEGYTYPEDESC,
	CDMUPDATEDATE
) as SELECT
                               SOURCE, BRANDID, STRATEGYTYPENAME, STRATEGYTYPEID, LOADTYPE, CDMLOADDATE, FILENAME, STRATEGYTYPEDESC, CDMUPDATEDATE
                            FROM IDS_DEV.MEDIA_BV."MEDIA_STRATEGYTYPE_PLR_BV";
create view IF NOT EXISTS MEDIA_STRATEGY_BV(
	STRATEGY_ID,
	STRATEGY_TYPE_ID,
	STRATEGY_NM,
	LOAD_TYP,
	BRAND_ID,
	SOURCE_SYSTEM_NM,
	LOAD_ID,
	LOAD_DTTM,
	UPDATE_ID,
	UPDATE_DTTM
) as SELECT
                               STRATEGY_ID, STRATEGY_TYPE_ID, STRATEGY_NM, LOAD_TYP, BRAND_ID, SOURCE_SYSTEM_NM, LOAD_ID, LOAD_DTTM, UPDATE_ID, UPDATE_DTTM
                            FROM IDS_DEV.MEDIA_BV."MEDIA_STRATEGY_BV";
create view IF NOT EXISTS MEDIA_STRATEGY_PLR_BV(
	SOURCE,
	CDMLOADDATE,
	STRATEGYTYPEID,
	BRANDID,
	LOADTYPE,
	STRATEGYID,
	STRATEGYNAME,
	CDMUPDATEDATE,
	FILENAME
) as SELECT
                               SOURCE, CDMLOADDATE, STRATEGYTYPEID, BRANDID, LOADTYPE, STRATEGYID, STRATEGYNAME, CDMUPDATEDATE, FILENAME
                            FROM IDS_DEV.MEDIA_BV."MEDIA_STRATEGY_PLR_BV";
create view IF NOT EXISTS MEDIA_STRATEGY_TYPE_BV(
	STRATEGY_TYPE_ID,
	STRATEGY_TYPE_NM,
	STRATEGY_TYPE_DESC,
	LOAD_TYP,
	BRAND_ID,
	SOURCE_SYSTEM_NM,
	LOAD_ID,
	LOAD_DTTM,
	UPDATE_ID,
	UPDATE_DTTM
) as SELECT
                               STRATEGY_TYPE_ID, STRATEGY_TYPE_NM, STRATEGY_TYPE_DESC, LOAD_TYP, BRAND_ID, SOURCE_SYSTEM_NM, LOAD_ID, LOAD_DTTM, UPDATE_ID, UPDATE_DTTM
                            FROM IDS_DEV.MEDIA_BV."MEDIA_STRATEGY_TYPE_BV";
create view IF NOT EXISTS MEDIA_TRACKER_WEEK_PLR_BV(
	CDMLOADDATE,
	CLICKS,
	CAMPAIGNDETAILID,
	BRANDID,
	GRP,
	LOADTYPE,
	SOURCE,
	WEEKSTARTDATE,
	DMACODE,
	TRACKERID,
	FILENAME,
	IMPRESSIONS,
	CDMUPDATEDATE,
	RATINGS,
	TRP
) as SELECT
                               CDMLOADDATE, CLICKS, CAMPAIGNDETAILID, BRANDID, GRP, LOADTYPE, SOURCE, WEEKSTARTDATE, DMACODE, TRACKERID, FILENAME, IMPRESSIONS, CDMUPDATEDATE, RATINGS, TRP
                            FROM IDS_DEV.MEDIA_BV."MEDIA_TRACKER_WEEK_PLR_BV";