dag_id: "DUNKIN_BOS_SFTP_TO_ADLS_ALL_HI_PL"
dag_description: "DUNKIN BOS data load from SFTP to ADLS2"
email: ['vagicharla.sudana@inspirebrands.com']

azure:
  adf:
    pipeline_name: "PL_COPY_SFTP_SOURCE"
    job_name: "DUNKINSRC_Ingest_BOS"