dag_id: "E2E_SALES_RECON_BWW_NBO_SQL_TO_RDS"
dag_description: "NBO Menulink data load from SQL to ADLS2 and then from ADLS2 to RDS"
email: ["DataServicesHelp@inspirebrands.com", "itdataservicessupport@inspirebrands.com"]
env : "PROD"
warehouse_id : "RA_PRCSSA_IRB_PROD_WH"
snowflake_conn_id : "Snowflake-IRB-PROD-OWNER"
schema_id : "BWW"
file_format: "RDS_PROD.BWW.NBO_BWW_FILE_FORMAT"
pattern: ".*NBO_SALES.*[.]csv"
stage_name: "@RDS_PROD.BWW.SALES_RECON_BWW_NBO_CSV_ADLS2"
snowflake_rds_database_name: "RDS_PROD"

azure:
  adf:
    pipeline_name: "Copy_nbo_st_register_to_ADLS"
    pipeline_file_size: "PL_GET_METADATA_FILE_ADLS"
    sourceFolderName: "landing/db/NBO_Sales/"
    


